acemod/ACE3

- addons/dragging/stringtable.xml
> Spanish: Update stringtable.xml

- addons/aircraft/Heli_Attack_01_base_F.hpp
- addons/laser_selfdesignate/CfgVehicles.hpp
Fixes #412 and also removes NVG from optics of gunner on comanche.
> Comanche roll

- addons/flashsuppressors/CfgVehicles.hpp
- addons/flashsuppressors/CfgWeapons.hpp
- addons/flashsuppressors/config.cpp
- addons/flashsuppressors/newclasses.txt
- addons/flashsuppressors/stringtable.xml
- addons/magazines/CfgWeapons.hpp
Also moving some stuff around to guarantee modularity
> flashsupressors for new weapons, #264

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_dropBackpack.sqf
This is a function that drops the current backpack of given unit.
Requested by @MarcBook who is working on a carry-backpack-in-ventral-position-script.
Potentially usefull for removing items / frisking in future, threrefore common
> function to drop backpack

- addons/common/functions/fnc_endRadioTransmission.sqf
- addons/common/functions/fnc_setVolume.sqf
My own mod was broken, dafuq you do guys? HATE!
> ACRE API functions and core functions were incorrect.

- addons/common/stringtable.xml
I have just added italian translation to the uncovered terms ;)
> Added italian translation to the last terms.

- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
Fixed breaking of unconscious animation on drop object. #457
> Fixed breaking of unconscious animation on drop object.

- addons/interaction/stringtable.xml
> Very small typo in CZ translation

- addons/magazines/CfgAmmo.hpp
- addons/magazines/CfgMagazines.hpp
- addons/magazines/CfgVehicles.hpp
- addons/magazines/CfgWeapons.hpp
- addons/magazines/newclasses.txt
- addons/magazines/stringtable.xml
WIP
How would the values for Subsonic and AP ammo have to be choosen?
> WIP: additional ammotypes for the DLC calibers

- addons/attach/stringtable.xml
- addons/captives/stringtable.xml
- addons/common/stringtable.xml
- addons/disposable/stringtable.xml
- addons/dragging/stringtable.xml
- addons/explosives/stringtable.xml
- addons/fcs/stringtable.xml
- addons/frag/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/inventory/stringtable.xml
- addons/laser_selfdesignate/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/logistics_wirecutter/stringtable.xml
- addons/magazinerepack/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/nametags/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/overheating/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/reload/stringtable.xml
- addons/reloadlaunchers/stringtable.xml
- addons/respawn/stringtable.xml
- addons/weaponselect/stringtable.xml
- addons/wep_javelin/stringtable.xml
Could not find more stringtables :panda_face:  :+1: 
Enjoy!
> Official polish translation

- AUTHORS.txt
- addons/aircraft/stringtable.xml
- addons/attach/stringtable.xml
- addons/captives/stringtable.xml
- addons/common/stringtable.xml
- addons/disposable/stringtable.xml
- addons/dragging/stringtable.xml
- addons/explosives/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/inventory/stringtable.xml
- addons/laser_selfdesignate/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/logistics_wirecutter/stringtable.xml
- addons/magazinerepack/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/movement/stringtable.xml
- addons/nametags/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/overheating/stringtable.xml
- addons/reload/stringtable.xml
- addons/reloadlaunchers/stringtable.xml
- addons/respawn/stringtable.xml
- addons/safemode/stringtable.xml
- addons/switchunits/stringtable.xml
- addons/weaponselect/stringtable.xml
- addons/wep_javelin/stringtable.xml
- addons/winddeflection/stringtable.xml
This version adding some translations for the french community.
> French Translation

- AUTHORS.txt
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/nametags/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/reload/stringtable.xml
- addons/winddeflection/stringtable.xml
did some translations, gonna continue once i have more time on hand
> Added German translation for a couple of things,

- addons/magazines/CfgWeapons.hpp
Am I doin it right?
Works for me.
> fix missing class

- addons/common/stringtable.xml
- addons/disarming/stringtable.xml
- addons/explosives/stringtable.xml
- addons/flashsuppressors/stringtable.xml
- addons/grenades/stringtable.xml
- addons/logistics_uavbattery/stringtable.xml
- addons/logistics_wirecutter/stringtable.xml
- addons/magazinerepack/stringtable.xml
- addons/magazines/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/overheating/stringtable.xml
- addons/vector/stringtable.xml
- addons/vehiclelock/stringtable.xml
Used tabler this time and this is why there are so many changes. Good tool I must say!
> Further PL translation fixes

- AUTHORS.txt
- addons/attach/CfgMagazines.hpp
- addons/attach/CfgWeapons.hpp
- addons/attach/functions/fnc_attach.sqf
- addons/attach/functions/fnc_detach.sqf
- addons/attach/functions/fnc_getChildrenAttachActions.sqf
- addons/attach/stringtable.xml
This adds a new config value: `ACE_attachable_effect` it contains the classname for the effect (vehicle)
> Added ACE Attach posibility to add more types of attachable items

- addons/common/stringtable.xml
- addons/disarming/stringtable.xml
- addons/magazines/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/nametags/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/overheating/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/respawn/stringtable.xml
> Added another new CZ strings

- addons/optics/CfgRscTitles.hpp
- addons/optics/CfgWeapons.hpp
- addons/optics/functions/fnc_handleFired.sqf
- addons/optics/functions/fnc_onDrawScope2D.sqf
also fixes preload texture issue in rpt and night reticles being active simply by it being cloudy.
> fix misc issues with optics, fix #537

- addons/advanced_ballistics/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/kestrel4500/stringtable.xml
- addons/scopes/stringtable.xml
- addons/weather/stringtable.xml
> Advanced Ballistics PL translation

- addons/interaction/stringtable.xml
Fix for addons/interaction translation.
> Russian translation for addons/interaction

- addons/ballistics/stringtable.xml
- addons/common/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
Some french, german and russian entries were listed twice, had to remove
one of two here and there so this list is for revision by different translators
> PL translation

- addons/ballistics/stringtable.xml
Typo, wrote Mk248 Mod 0, should be Mk248 Mod 1
> PL translation fix

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_adjustPainLevel.sqf
#69 - Tweaks to flashbangs
uses eyepos for LOS check
3d eye direction angle checks
adds medical pain
> Flashbang tweaks

- documentation/user/how-to-make-a-feature-request.md
minor spelling fixes in feature requests documentation
> minor spelling fixes in feature requests documentation

- AUTHORS.txt
because of https://github.com/acemod/ACE3/pull/521
> added myself to authors.txt as requested

- addons/advanced_ballistics/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/disarming/stringtable.xml
- addons/explosives/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/overheating/stringtable.xml
- addons/scopes/stringtable.xml
Explosives, overheating, disarming, atragmx, laserpointer, advanced_ballistics, scopes
> Russian translation fixes

- addons/interaction/stringtable.xml
Some entries not taken from tabler changes
> French : update / fix stringtable

- addons/interaction/stringtable.xml
> German - Update stringtable.xml

- addons/captives/stringtable.xml
Yeap, one more russian translation fix.
Probably, you hate me for all this pull requests. Sorry.
> One more russian translation fix

- addons/parachute/functions/fnc_showAltimeter.sqf
Also includes minor readability fixes.
> Altimeter fix, division by zero when no time has passed (game paused, etc.)

- addons/respawn/stringtable.xml
- addons/vehiclelock/stringtable.xml
- addons/weaponselect/stringtable.xml
Filled all the missing lines, little errors fixed.
> Russian stringtables finished

- addons/parachute/XEH_postInit.sqf
- addons/parachute/XEH_preInit.sqf
- addons/parachute/functions/fnc_handleInfoDisplayChanged.sqf
Before someone asks: No this is not a difficulty setting. It's just always there no matter what setting or difficulty.
> hide height / velocity while parachuting, freefallig in expert mode, fix #692

- addons/logistics_wirecutter/CfgEventHandlers.hpp
- addons/logistics_wirecutter/CfgSounds.hpp
- addons/logistics_wirecutter/CfgVehicles.hpp
- addons/logistics_wirecutter/CfgWeapons.hpp
- addons/logistics_wirecutter/config.cpp
- addons/logistics_wirecutter/functions/fnc_cutDownFence.sqf
- addons/logistics_wirecutter/functions/fnc_getNearestFence.sqf
- addons/logistics_wirecutter/functions/fnc_interactEH.sqf
- addons/logistics_wirecutter/functions/fnc_isFence.sqf
Changes wirecutters sound effect from that powersaw to a manual wire clipper.
Also makes it a playSound3d (10m range) so your teammates can tell what you're doing and for tvt game-play.
> Wire cutters sound effect

- addons/nametags/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/parachute/stringtable.xml
- addons/reload/stringtable.xml
- addons/reloadlaunchers/stringtable.xml
- addons/respawn/stringtable.xml
- addons/safemode/stringtable.xml
- addons/scopes/stringtable.xml
- addons/switchunits/stringtable.xml
- addons/vehiclelock/stringtable.xml
- addons/weaponselect/stringtable.xml
- addons/weather/stringtable.xml
- addons/winddeflection/stringtable.xml
2nd part traduction, will take a look if all make sense ingame (context of some strings) and in case will pull some modify next days
> Italian translation

- documentation/development/coding-guidelines.md
- documentation/development/extension-guidelines.md
- documentation/development/modularity-and-pbo-structure.md
Some minor spelling fixes and wrongly used words. Let me know if anything doesn't fit.
> Wiki wording

- addons/advanced_ballistics/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/kestrel4500/stringtable.xml
- addons/overheating/stringtable.xml
- addons/scopes/stringtable.xml
- addons/weather/stringtable.xml
advanced ballistics, atragmx, interactmenu,kestrel4500,scopes,weather
> added missing german translations

- addons/attach/stringtable.xml
- addons/ballistics/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/inventory/stringtable.xml
- addons/medical/stringtable.xml
- addons/nametags/stringtable.xml
Reviewed this one https://github.com/acemod/ACE3/pull/675 and fixed some other problems.
> Russian translation fixes and multilanguage fix in ballistics

- addons/common/XEH_postInit.sqf
- addons/optics/CfgWeapons.hpp
- addons/optics/XEH_postInit.sqf
Attempt at fixing broken PIP scopes.
> Fix for PIP scopes, fix #547

- optionals/asdg_comp/config.cpp
Added the  scopes and railitems to the according ASDG rails.
> Config for compatiblity to ASDG Joint Rails

- optionals/asdg_comp/script_component.hpp
Included in config.cpp of #485
> script_component.hpp for asdg_comp

- AUTHORS.txt
Added myself to the contirbutors, after #485
> Added my name to AUTHORS.txt

- tools/make.cfg
- tools/make.py
Copies important files
Support for building modules in the "optionals" folder
Support for re-building any missing PBO files. 
Modification of the make.cfg to change the directory of the "optionals" location
> Make.py and Make.cfg ehancements - Copy Important Files

- tools/make.py
Moved "copy_important_files" call in front of make release and after building is done
Moved "cleanup_optionals" call in front of make release and after building is done
added a few prints
> Indent cleanup_optionals correct

- tools/make.py
> Userconfig folder is now properly added to the release folder 

- addons/map/functions/fnc_determineMapLight.sqf
Small change to fix illimunation for gunners in helicopters for the map. Should this be applied to any other aircraft/unit types?
> Illuminate map for gunner of helicopters. Fixes #558

- addons/attach/CfgWeapons.hpp
- addons/common/CfgWeapons.hpp
- addons/explosives/CfgVehicles.hpp
- addons/logistics_wirecutter/CfgWeapons.hpp
- addons/microdagr/CfgWeapons.hpp
- addons/missileguidance/CfgVehicles.hpp
- addons/overheating/CfgWeapons.hpp
- addons/vehiclelock/CfgWeapons.hpp
> Revert "remove author from items inheriting ACE_ItemCore"

- addons/reload/CfgActions.hpp
- addons/reload/CfgEventHandlers.hpp
- addons/reload/CfgVehicles.hpp
- addons/reload/XEH_postInit.sqf
- addons/reload/functions/fnc_canCheckAmmo.sqf
- addons/reload/functions/fnc_checkAmmo.sqf
- addons/reload/functions/fnc_displayAmmo.sqf
Simple version of PR #248 - issue #238
Shows ammo count and ammo type on static weapons
> Show Loaded Ammo for static weapons

- addons/dragging/functions/fnc_canCarry.sqf
- addons/dragging/functions/fnc_canDrag.sqf
fixes #659
Tested, works without medical, and with basic & advanced medical.
> Fixed dragging always available when medical module is removed

- addons/realisticnames/CfgWeapons.hpp
- addons/realisticnames/stringtable.xml
(talk: #704)
SPMG is basically 1:1 LWMMG.
Ref: http://en.wikipedia.org/wiki/Lightweight_Medium_Machine_Gun
Ref: http://www.gd-ots.com/armament_systems/ics_lwmmg.html
Mk 14 is pretty obvious
> Adjust realnames, fix some russian

- addons/interact_menu/XEH_clientInit.sqf
- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/functions/fnc_ctrlSetParsedTextCached.sqf
- addons/interact_menu/functions/fnc_renderIcon.sqf
- addons/interact_menu/functions/fnc_renderSelector.sqf
is this currently done every frame? If so, this could really improve the FPS with opened menu, especially if there are a lot of sub menu options visible.
Currently bugs out when opening / closing sub menues. Need to investigate why...
> cache ctrlSetStructedText parseText

- tools/make.py
Adding support for removing obsolete file and their signatures. 
Moving some notices around
> Remove obsolete PBOs

- addons/frag/CfgAmmo.hpp
- addons/frag/XEH_pre_Init.sqf
- addons/frag/functions/fnc_doSpall.sqf
- addons/frag/functions/fnc_fired.sqf
- addons/frag/functions/fnc_frago.sqf
- addons/modules/XEH_preInit.sqf
- addons/modules/config.cpp
- addons/modules/functions/fnc_bi_moduleProjectile.sqf
#747 
- Configuration for the ammo classes needs to be checked. They are not correct atm.
> Curator fragmentation

- addons/medical/stringtable.xml
Перевел как смог, вероятно данная настройка будет в ACE3 Настройки. Нужно проверить влезет ли туда. Если влезет, то подкорректировать перевод. Правки строго приветствуются.
> Updated russian translation (medical)

- addons/medical/ACE_Medical_Actions.hpp
- addons/medical/ACE_Medical_Treatments.hpp
- addons/medical/functions/fnc_actionCheckBloodPressureLocal.sqf
- addons/medical/functions/fnc_actionCheckPulseLocal.sqf
- addons/medical/functions/fnc_displayPatientInformation.sqf
- addons/medical/functions/fnc_displayTriageCard.sqf
- addons/medical/stringtable.xml
- addons/medical/ui/RscTitles.hpp
- addons/medical/ui/triagecard.hpp
> Add translations for adv. medical

- addons/medical/functions/fnc_setUnconscious.sqf
- addons/medical/functions/fnc_unconsciousPFH.sqf
> mute unconsious units

- addons/recoil/CfgEventHandlers.hpp
- addons/recoil/CfgMoves.hpp
- addons/recoil/CfgRecoils.hpp
- addons/recoil/XEH_preInit.sqf
- addons/recoil/config.cpp
- addons/recoil/functions/fnc_camshake.sqf
- addons/recoil/functions/script_component.hpp
> tweaking recoil

- addons/medical/stringtable.xml
> german translations for medical

- addons/realisticnames/stringtable.xml
Is this okay? 
MAR-10 -> Noreen Bad news
EMR-1 -> SIG 762
Navid -> HK 122
> Realistic weapon names: Update stringtable.xml

- addons/interact_menu/stringtable.xml
- addons/overheating/stringtable.xml
Added some french entries and removed a german duplicate
> Some french entries and a german duplicate

- addons/realisticnames/stringtable.xml
ACP-C2 -> Custom Covert II
KT2002 Katiba -> KH2002 Khaybar
> Less fictional weapon names

- AUTHORS.txt
- addons/aircraft/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/dragging/stringtable.xml
- addons/explosives/stringtable.xml
- addons/medical/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/realisticnames/stringtable.xml
* fixed ramp in /aircraft
* added aragmx entry
* added multiple medical entries
* translated missileguidance
* completed mk6mortar
* changed Sanitaire to Médical in realisticnames
also fixed some typos in there
* added myself to contributors
will need to get updated if an other translations pass first.
edit rebased all the changes into one commit for clarity, hope the commit is clear enough now (sorry for the bad one previously)
conflicts resolved ready for merging
> french translation pass

- AUTHORS.txt
- addons/common/stringtable.xml
- addons/explosives/stringtable.xml
- addons/fcs/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/kestrel4500/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/logistics_wirecutter/stringtable.xml
- addons/medical/stringtable.xml
Hello, 
i've added some changes to the italian translation.
I will add more translations as soon as possible.
Thanks
> Some Italian Translation's Changes

- addons/ballistics/stringtable.xml
I found some errors. please merge!
> german translations - found some errors

- addons/medical/ACE_Medical_Treatments.hpp
- addons/medical/stringtable.xml
Fixes #716
Merge for medicalImprovements branch #861
> Display Name Progress Text

- addons/ballistics/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/medical/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/optics/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/overheating/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/reloadlaunchers/stringtable.xml
- addons/weaponselect/stringtable.xml
Sorry for the mess up, I couldn't update my fork so had to re-create it and resubmit.
Original pull request: https://github.com/acemod/ACE3/pull/888
> Russian localization update.

- addons/captives/stringtable.xml
Need more context to translate STR_ACE_Captives_Zeus_OnlyAlive and STR_ACE_Captives_Zeus_OnlyInfentry.
> Added - Portuguese translation to Captive surendering

- addons/common/stringtable.xml
Everything translated. Even the banana.
> Added - Portuguese translation

- addons/ballistics/stringtable.xml
- addons/interact_menu/stringtable.xml
last translation's update before 3.0.0?
> French: update and fix stringtable

- addons/dragging/CfgMovesBasic.hpp
- addons/dragging/config.cpp
My knowledge of animation stuff is limited, but this seems to fix issue #278
Switches the `up` animation change from "Helper_SwitchToCarryRfl", which is an elaborate long animation which fails to complete over to a simple stance change.
> Fix Dragging StanceChange Anim

- addons/atragmx/stringtable.xml
- addons/attach/stringtable.xml
- addons/ballistics/stringtable.xml
- addons/captives/stringtable.xml
- addons/medical/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/overheating/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/respawn/stringtable.xml
- addons/vehiclelock/stringtable.xml
Added translations
- atragmx
- attach
- ballistics
- captives
Cordially
> Italian's Translation fixes

- addons/interact_menu/stringtable.xml
- addons/medical/stringtable.xml
-Added missing translations in the interact_menu
-Fixed spelling errors in the medical
> Localization update (Russian)

- addons/advanced_ballistics/initKeybinds.sqf
- addons/atragmx/initKeybinds.sqf
- addons/fcs/initKeybinds.sqf
- addons/grenades/XEH_postInit.sqf
- addons/javelin/initKeybinds.sqf
- addons/kestrel4500/initKeybinds.sqf
- addons/laserpointer/initKeybinds.sqf
- addons/microdagr/XEH_clientInit.sqf
- addons/movement/XEH_postInit.sqf
- addons/nightvision/XEH_postInitClient.sqf
- addons/overheating/XEH_postInit.sqf
- addons/parachute/XEH_postInit.sqf
- addons/reload/XEH_postInit.sqf
- addons/safemode/XEH_postInit.sqf
- addons/scopes/XEH_postInit.sqf
- addons/vector/initKeybinds.sqf
- addons/vehicles/XEH_postInit.sqf
- addons/weaponselect/XEH_postInit.sqf
> Split keybindings into different sub-categories

- mod.cpp
Expand the name for the Configure Expansions screen. 
Also include the version number for yet another easy identification. 
Allows a different look which will give us another evidence point that the user changed something. 
References: 
(1) EXPANSIONS - http://gyazo.com/2490e923e5a9d2f9828f62b5e8dce6a3
(2) RPT - http://gyazo.com/e099d529c11d78ed6757685d619b6502
> ACE3 Name Adjustment

- addons/fcs/functions/fnc_firedEH.sqf
> Revert "Takes negative initSpeed values into account"

- addons/advanced_ballistics/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/disarming/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/kestrel4500/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/respawn/stringtable.xml
- addons/scopes/stringtable.xml
- addons/weather/stringtable.xml
> Hungarian translation update

- addons/respawn/stringtable.xml
> Update Stringtable: Rallypoint

- AUTHORS.txt
- addons/advanced_ballistics/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/kestrel4500/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/medical/stringtable.xml
adv. ballistics, atragmx, interaction menu, kestrel4500, laser pointer
and little part of medical
I had some time so I translated something into czech language. I've never worked with github before, so if I fucked up something I am sorry about that.
I would appreciate some feedback, if I have done somethink wrong.
Adam
> Translation of some stuff into czech language

- tools/make.cfg
set new default key for make.cfg
> set new default key for make.cfg

- AUTHORS.txt
- addons/advanced_ballistics/stringtable.xml
- addons/atragmx/stringtable.xml
- addons/attach/stringtable.xml
- addons/ballistics/stringtable.xml
- addons/captives/stringtable.xml
- addons/disarming/stringtable.xml
- addons/disposable/stringtable.xml
- addons/dragging/stringtable.xml
- addons/frag/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/kestrel4500/stringtable.xml
- addons/laser/stringtable.xml
- addons/laser_selfdesignate/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/logistics_uavbattery/stringtable.xml
- addons/medical/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/respawn/stringtable.xml
- addons/scopes/stringtable.xml
- addons/vector/stringtable.xml
- addons/weaponselect/stringtable.xml
- addons/weather/stringtable.xml
Done all remaining portuguese translations, including some minor
corrections
> Translation to Portuguese

- addons/laser/stringtable.xml
Added spanish translation for three strings.
> Added spanish translation

- addons/medical/functions/fnc_createLitter.sqf
- addons/medical/functions/fnc_treatment_failure.sqf
- addons/medical/functions/fnc_treatment_success.sqf
#1000
Should prevent the error/treatment from breaking, but doesn't fix the cause.
> Fix treatment script error

- documentation/missionmaker/modules.md
> Module documentation

- addons/medical/ACE_Medical_Treatments.hpp
new healing animation added to animationCaller                                                                  animationCallerSelf stays the same
> New anim update

- addons/interact_menu/XEH_clientInit.sqf
> Fix script error when going unconscious with interaction menu opened

- documentation/development/arma-3-issues.md
> Added Switching between sniper optics modes A3 feedback tracker issue

- addons/common/functions/fnc_loadSettingsOnServer.sqf
- addons/common/functions/fnc_setSetting.sqf
- addons/common/functions/fnc_setSettingFromConfig.sqf
> Added missing privates to settings framework

- extensions/advanced_ballistics/AdvancedBallistics.cpp
Just a few tweaks to AB for some lookup and resizing optimization.
> AB ext tweaking. Just a bit of optimization and crash checking.

- addons/laserpointer/functions/fnc_switchLaserLightMode.sqf
> disable laserpointer inheritance for rhs, fix #1070

- addons/weather/functions/fnc_updateWind.sqf
Fixes: https://github.com/acemod/ACE3/issues/1025
> Fixes bugged waves

- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_hasMedicalEnabled.sqf
> Fixed medical setting spelling mistake

- tools/make.py
> Do not execute CfgConvert if $NOBIN$ is found.

- addons/aircraft/Heli_Attack_01_base_F.hpp
Bit of a hack, but fixes the order to
Unstab Wide
Wide
Medium
Narrow
Narrower
> Fix for Comanche zoom levels

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_waveHeightAt.sqf
- addons/interact_menu/functions/fnc_keyDown.sqf
- addons/interact_menu/functions/fnc_renderActionPoints.sqf
> Added: waveHeightAt Function

- addons/medical/functions/fnc_isMedicalVehicle.sqf
> Fix medical vehicle return value

- addons/realisticnames/CfgVehicles.hpp
- addons/realisticnames/CfgWeapons.hpp
>
20:43] jaynus: thats leftover from AGM
[20:43] jaynus: thats not me
[20:43] jaynus: Its *going to be a spike*
[20:43] jaynus: but its not there yet
[20:43] jonpas: enver said it's you :smile:
[20:43] jonpas: so should I rename it yet to save you some time?
[20:43] jaynus: No, because I do not know how I'm setting up the variances for all of that yet
[20:43] alganthe: rename what ?
[20:43] jaynus: and I'm going to have to leave vanilla shit untouched once i do
[20:43] jonpas: k capiche
[20:43] jaynus: so call it poopoo caca for all i care :stuck_out_tongue:
**[20:44] jonpas: then I'll remove current name, since it won't be mini-spike anyways you say .P
[20:44] jaynus: yah sure please**
[20:44] jaynus: Right now its a javelin in a spikes body
> Removed Titan realistic name as it's not implemented yet as a Spike

- documentation/feature/ai.md
- documentation/feature/aircraft.md
- documentation/feature/attach.md
- documentation/feature/captives.md
Documentation improved for 
- ai
- aircraft
- attach
- Captives
> Documentation pass

- addons/viewdistance/ACE_Settings.hpp
- addons/viewdistance/CfgVehicles.hpp
- addons/viewdistance/XEH_postInit.sqf
- addons/viewdistance/functions/fnc_adaptViewDistance.sqf
- addons/viewdistance/functions/fnc_changeViewDistance.sqf
- addons/viewdistance/functions/fnc_initModule.sqf
> ACE_ViewDistance tweaks

- documentation/feature/aircraft.md
- documentation/feature/attach.md
- documentation/feature/ballistics.md
- documentation/feature/captives.md
Features edited: Aircraft, Attach, Ballistics, Captives
> Documentation: Fix typos, grammar, redundancy

- AUTHORS.txt
- documentation/feature/windeflection.md
Remove irrelevant features (humidity/pressure)
Add 2d Module guide
Also add myself to Authors.txt
> Documentation: Update WindDeflection

- addons/safemode/functions/fnc_firstMode.sqf
- addons/safemode/functions/fnc_lockSafety.sqf
- addons/safemode/functions/fnc_playChangeFiremodeSound.sqf
- addons/safemode/functions/fnc_setSafeModeVisual.sqf
- addons/safemode/functions/fnc_unlockSafety.sqf
- addons/weaponselect/functions/fnc_displayGrenadeTypeAndNumber.sqf
- addons/weaponselect/functions/fnc_findNextGrenadeMagazine.sqf
- addons/weaponselect/functions/fnc_findNextGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_fireSmokeLauncher.sqf
- addons/weaponselect/functions/fnc_playChangeFiremodeSound.sqf
- addons/weaponselect/functions/fnc_putWeaponAway.sqf
- addons/weaponselect/functions/fnc_selectWeaponMode.sqf
- addons/weaponselect/functions/fnc_selectWeaponMuzzle.sqf
- addons/weaponselect/functions/fnc_selectWeaponVehicle.sqf
- addons/weaponselect/functions/fnc_setNextGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_throwGrenade.sqf
More work for #88
I'll make another PR for safemode's indentation.
> Module cleanup (Macros)

- addons/safemode/functions/fnc_lockSafety.sqf
- addons/safemode/functions/fnc_playChangeFiremodeSound.sqf
- addons/safemode/functions/fnc_setSafeModeVisual.sqf
- addons/safemode/functions/fnc_unlockSafety.sqf
#88 should be able to be closed after this.
> Fixed safemode module indentation

- documentation/feature/weather.md
- documentation/feature/windeflection.md
- documentation/missionmaker/modules.md
Edit Documentation: Weather.md - remove template, add short description
Edit Missionmaker: module.md - add under-the-hood explanation + example
> Documentation+Missionmaker - edit Weather

- documentation/feature/medical-system.md
Mainly based on my community experience with CMS, translated from exact same PL guide.
> Medical guide improvements

- documentation/development/Documentation guidelines and tips.md
- documentation/feature/ai.md
- documentation/feature/aircraft.md
- documentation/feature/attach.md
- documentation/feature/backpacks.md
- documentation/feature/captives.md
- documentation/feature/difficulties.md
- documentation/feature/disarming.md
- documentation/feature/disposable.md
- documentation/feature/dragging.md
- documentation/feature/explosives.md
- documentation/feature/flashsuppressors.md
- documentation/feature/frag.md
- documentation/feature/gforces.md
- documentation/feature/goggles.md
- documentation/feature/grenades.md
- documentation/missionmaker/classnames.md
- [backpack] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/backpacks.md)
- [difficulties] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/difficulties.md)
- [disarming] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/disarming.md)
- [disposable] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/disposable.md)
- [dragging] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/dragging.md)
- [explosives] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/explosives.md)
- [flashsuppressors] (https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/feature/flashsuppressors.md)
- [frag] …
> Documentation pass 2

- documentation/feature/windeflection.md
- documentation/missionmaker/modules.md
Update Windeflection.md with additional information
Update Missionmaker/modules.md with correct description
> Update documentation: Windeflecion

- addons/laser/README.md
- documentation/development/Documentation guidelines and tips.md
- documentation/feature/ai.md
- documentation/feature/fcs.md
- documentation/feature/hearing.md
- documentation/feature/hitreactions.md
- documentation/feature/interact_menu.md
- documentation/feature/interaction.md
- documentation/feature/inventory.md
- documentation/feature/javelin.md
- documentation/feature/laser.md
- documentation/feature/laser_selfdesignate.md
- documentation/feature/laserpointer.md
- documentation/feature/logistics_uavbattery.md
- documentation/feature/logistics_wirecutter.md
- documentation/feature/magazinerepack.md
- documentation/feature/main.md
- documentation/feature/map.md
- documentation/feature/maptools.md
- documentation/feature/markers.md
- Fixed typos in laser/readme
- Documentation guidelines updated
- ACE3 mentions updated in
- ai
- Updated doc
- [fcs] (https://github.com/alganthe/ACE3ganthe/blob/documentation_pass_3/documentation/feature/fcs.md)
- [hearing] (https://github.com/alganthe/ACE3ganthe/blob/documentation_pass_3/documentation/feature/hearing.md)
- [hitreaction] (https://github.com/alganthe/ACE3ganthe/blob/documentation_pass_3/documentation/feature/hitreactions.md)
- [interact_menu] (https://github.com/alganthe/ACE3ganthe/blob/documentation_pass_3/documentation/feature/interact_menu.md)
- [interaction] (https://github.com/alganthe/ACE3ganthe/blob/documentation_pass_3/documentation/feature/interaction.md)
- [inventory] (https://github.com/alganthe/ACE3ganthe/blob/documentation_pass_3/documentation/feature/invent …
> Documentation pass 3

- addons/vehiclelock/readme.md
- documentation/feature/vehiclelock.md
- documentation/feature/weather.md
- documentation/feature/windeflection.md
- documentation/missionmaker/modules.md
Create feature/vehiclelock.md
Edit addon readme.md and missionmaker.md
> Documentation: Vehiclelock, Weather

- documentation/feature/advanced_ballistics.md
- documentation/feature/ai.md
- documentation/feature/aircraft.md
- documentation/feature/attach.md
- documentation/feature/backpacks.md
- documentation/feature/ballistics.md
- documentation/feature/captives.md
- documentation/missionmaker/modules.md
Add standardization, fix typos, fix grammar
Will reiterate again after all docs are written
> Proofread docs: improvements

- addons/advanced_ballistics/ACE_Settings.hpp
- addons/advanced_ballistics/CfgVehicles.hpp
- addons/advanced_ballistics/functions/fnc_handleFired.sqf
- addons/advanced_ballistics/functions/fnc_initModuleSettings.sqf
- addons/advanced_ballistics/stringtable.xml
* alwaysSimulateForGroupMembers
> Added a new module option for advanced ballistics:

- optionals/compat_bwa3/$PBOPREFIX$
- optionals/compat_bwa3/CfgAmmo.hpp
- optionals/compat_bwa3/CfgWeapons.hpp
- optionals/compat_bwa3/config.cpp
- optionals/compat_bwa3/script_component.hpp
Compatibility PBO for BW-Mod weapon, ammo and optic classes.
> Compat BWA3

- addons/explosives/functions/fnc_placeExplosive.sqf
- addons/explosives/functions/fnc_place_Approve.sqf
Added a put animation when setting the trigger for an explosive.
Fixes: https://github.com/acemod/ACE3/issues/354
> Changed the animation from medic to put when placing an explosive.

- addons/medical/functions/fnc_handleDamage_basic.sqf
Should only do a max of 1 PFH at a time. If new damage is received before the PFH is completed, it will reset.
> fix for #1297

- addons/medical/ACE_Medical_Treatments.hpp
- addons/medical/CfgWeapons.hpp
- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_addToInjuredCollection.sqf
- addons/medical/functions/fnc_handleUnitVitals.sqf
- addons/medical/functions/fnc_init.sqf
- addons/medical/functions/fnc_modifyMedicalAction.sqf
- addons/medical/functions/fnc_onMedicationUsage.sqf
- addons/medical/functions/fnc_setUnconscious.sqf
- addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medicationLocal.sqf
Some minor enhancements for advanced medical and a fix for setUnconscious (non critical).
Largest change is the first step for the improved medication system in advanced by suppressing pain instead of removing it. Adjustments are compatible with the current method so basic medical does not have to change anything (but obviously can make use of this if wanted).
I am considering making the suppress pain a setting.
> Adv medical medication enhancements, minor fixes and feature requests

- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_hasMedicalEnabled.sqf
> Fixes to medical handleDamage

- addons/scopes/CfgWeapons.hpp
- addons/scopes/functions/fnc_adjustScope.sqf
- documentation/development/ace3-config-entries.md
- optionals/compat_bwa3/CfgWeapons.hpp
- optionals/compat_hlcmods_ak/CfgWeapons.hpp
- optionals/compat_rh_acc/CfgWeapons.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
- optionals/compat_rksl_pm_ii/CfgWeapons.hpp
- optionals/compat_sma3_iansky/CfgWeapons.hpp
* ACE_ScopeAdjust_VerticalIncrement
* ACE_ScopeAdjust_HorizontalIncrement
> Elevation and windage can now have different adjustment increments:

- addons/advanced_ballistics/functions/fnc_handleFired.sqf
Tries to improve the visibility of the bullet trace effect on smaller screen.
> Experiment with the bullet trace effect size

- documentation/feature/medical-system.md
> Update medical guide

- documentation/user/Installation.md
- documentation/user/installation-guide.md
First draft.
Need to add PWS guide
Verify nothing important is missing
> Docs: Installation guide

- documentation/feature/apl.md
- documentation/feature/mk6mortar.md
- documentation/missionmaker/classnames.md
- mk6 mortar doc added
- apl doc added
- classnames fixed (forgot an entry)
> mk6mortar and missing entries

- documentation/user/installation-guide.md
Divide Installation process from Launch process
WIP, need to add image URLs
> Doc: Installation-guide - improve

- documentation/feature/vehiclelock.md
- documentation/feature/weather.md
- documentation/feature/windeflection.md
- documentation/feature/zeus.md
- documentation/missionmaker/modules.md
- documentation/user/installation-guide.md
Some fixes, sorry about the extra noise..
> Docs: Add zeus, add images to installation

- documentation/missionmaker/modules.md
> Fix copypasta

- documentation/feature/viewdistance.md
- documentation/missionmaker/modules.md
Create viewdistance.md doc
Add relevant module info about viewdistance to modules.md
> Docs: viewdistance

- addons/medical/ACE_Medical_Treatments.hpp
- addons/medical/functions/fnc_treatmentBasic_bloodbag.sqf
- addons/medical/functions/fnc_treatmentBasic_bloodbagLocal.sqf
- addons/medical/functions/fnc_treatmentIV.sqf
- addons/medical/functions/fnc_treatmentIVLocal.sqf
#1325 (All IVs add the same amount of blood - 1000 ml)
Both basic and advanced always added 1000 of blood.
*Basic: Added treatements for all bag sizes, and scale the amount added based on treatment.
*Advanced: It was looking up treatment by item name not treatment name.
> Medical blood bags size matters

- optionals/compat_rhs_usf3/CfgAmmo.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
Fix #1321 
Just adds missle guidance to the Ammo
> #1321 - Add MGuidance to RHS Javelin Ammo

- tools/setup.py
In case any of those ever change, it'll make it easier.
All my last 3 pull requests are with the same thing in mind, making it easier to define everything with as less fiddling with code as possible in case it's ever used for something else than ACE3. Additionally I am getting a grasp of how Python syntax works so why not submit if I did something.
Feel free to close if you deem these PRs useless/unfitting.
> Added maindir, projectdir and cba variables to setup.py

- addons/optionsmenu/functions/fnc_exportSettings.sqf
> Send directly to extension instead of splitting it

- AUTHORS.txt
More recent additions seem to have been just stacked unsorted at the bottom.
> Alphabetized the contributor list

- addons/atragmx/functions/fnc_update_range_card.sqf
- addons/weather/XEH_preInit.sqf
- addons/weather/functions/fnc_calculateSpeedOfSound.sqf
- extensions/advanced_ballistics/AdvancedBallistics.cpp
* Influences the advanced ballistics transonic instability
* Influences the ATragMX range card output
> Added speed of sound calculation:

- addons/atragmx/functions/fnc_calculate_range_card.sqf
- addons/atragmx/functions/fnc_calculate_target_solution.sqf
- addons/weather/functions/fnc_calculateBarometricPressure.sqf
- extensions/advanced_ballistics/AdvancedBallistics.cpp
Replaces broken barometric pressure calculation:
* Both temperature and altitude are now taken into account
> Fixed incorrect barometric pressure calculation

- addons/interact_menu/ACE_Settings.hpp
- addons/interact_menu/XEH_clientInit.sqf
- addons/interact_menu/stringtable.xml
Added blur background client setting
> Blur background while interaction menu is open

- addons/overheating/CfgWeapons.hpp
- added navid class to barrel swapping config
- added SPMG class to barrel swapping config
> navid and SPMG barrel swapping added

- addons/rangecard/functions/fnc_calculateSolution.sqf
- addons/rangecard/functions/fnc_updateRangeCard.sqf
* Calculates correct solutions when parts of the ammo config are missing
* Calculates correct solutions when parts of the weapon config are missing
* Performance improvement when AB is enabled
> Improved error handling when AB is enabled with incomplete configs

- optionals/compat_cup/CfgAmmo.hpp
- optionals/compat_cup/CfgWeapons.hpp
- optionals/compat_cup/config.cpp
* Added CUP weapon config
* Added CUP scope config
* Completed CUP ammo config
> CUP config

- addons/common/functions/fnc_progressBar.sqf
> Progress bar stops on death

- AUTHORS.txt
- addons/advanced_ballistics/stringtable.xml
- addons/ballistics/stringtable.xml
- addons/captives/stringtable.xml
- addons/common/stringtable.xml
- addons/explosives/stringtable.xml
- addons/fcs/stringtable.xml
- addons/frag/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interaction/stringtable.xml
- addons/inventory/stringtable.xml
- addons/magazinerepack/stringtable.xml
- addons/map/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/missionmodules/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/nametags/stringtable.xml
- addons/nightvision/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/respawn/stringtable.xml
- addons/switchunits/stringtable.xml
- addons/vehiclelock/stringtable.xml
- addons/weather/stringtable.xml
- addons/winddeflection/stringtable.xml
Added a lot of German translations and fixed even more typos.
> German translations

- documentation/README_PL.md
@gienkov, could you please verify if my translations are correct?
> README_PL: localized shields

- addons/medical/ACE_Medical_Treatments.hpp
- addons/medical/functions/fnc_actionPlaceInBodyBag.sqf
* Increased the treatment time to match the animation duration
* Fixed the body bag alignment with the dead unit
> Body bag cleanup:

- documentation/feature/missileguidance.md
- documentation/feature/overheating.md
- documentation/feature/rangecard.md
- documentation/feature/switchunits.md
- documentation/feature/vector.md
- documentation/missionmaker/classnames.md
- documentation/user/getting-started.md
- documentation/user/how-to-report-an-issue.md
- Added AMG doc
- Clarified overheating doc
- Getting started remade
- Vector doc moved from getting started to vector
- Classnames updated
- Switchunits doc fixed
- Rangecard doc added
> Documentation pass 6

- optionals/compat_cup/CfgMagazines.hpp
- optionals/compat_cup/CfgWeapons.hpp
- optionals/compat_cup/config.cpp
Used the same values that I had used for the AGM CUP launcher compatibility. Tested & working in game, would appreciate a sanity check.
> CUP Launchers Backblast + Disposable

- addons/attach/CfgVehicles.hpp
changed the intensity of the strobe light, it's still VERY visible on a
very long distance, (around 1.6k maybe more)
Before  http://steamcommunity.com/sharedfiles/filedetails/?id=455041609
after http://steamcommunity.com/sharedfiles/filedetails/?id=455048548
RL : ![](http://warjunkies.net/ploggerb3/images/gears___equipments/military_strobe___lights/ir-c.jpg)
> strobe light more bearable

- addons/zeus/ACE_Settings.hpp
- addons/zeus/CfgVehicles.hpp
- addons/zeus/functions/fnc_moduleCaptive.sqf
- addons/zeus/functions/fnc_moduleSurrender.sqf
- addons/zeus/functions/fnc_moduleUnconscious.sqf
- addons/zeus/stringtable.xml
Pretty self explanatory, also changed the disabled string to use the existing A3 one
> Macroified ACE_Zeus Strings

- addons/main/script_macros.hpp
Adds a guard for xSTRING macros, as discussed with @Glowbal and @ViperMaul
> Added Macro Guard to string macros

- README.md
Also, changed the download  link from source code to the official compiled version.
> README: Shields back up

- addons/safemode/functions/fnc_playChangeFiremodeSound.sqf
Foreach does not return the value.
> Fixed find file extension in playChangefiremode

- addons/ui/$PBOPREFIX$
- addons/ui/README.md
- addons/ui/config.cpp
- addons/ui/functions/script_component.hpp
- addons/ui/script_component.hpp
Changed text and background colour for chat while on the map to let it be more visible
> Chat visibility enhancement

- addons/zeus/functions/fnc_bi_moduleCurator.sqf
- addons/zeus/functions/fnc_bi_moduleMine.sqf
- addons/zeus/functions/fnc_bi_moduleProjectile.sqf
- addons/zeus/functions/fnc_bi_moduleRemoteControl.sqf
Just updating the edited BI functions to match the new public game version
> Update ace_zeus with 1.46 changes

- addons/sandbag/CfgVehicles.hpp
- addons/spottingscope/CfgVehicles.hpp
- addons/tripod/CfgVehicles.hpp
As discussed with @ulteq this was a copy/pasta boo-boo. :grimacing:
> Removed isNotInside from Sandbag, SpottingScope and Tripod placement

- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_actionCheckBloodPressureLocal.sqf
- addons/medical/functions/fnc_actionCheckPulseLocal.sqf
- addons/medical/functions/fnc_addHeartRateAdjustment.sqf
- addons/medical/functions/fnc_addToLog.sqf
- addons/medical/functions/fnc_addToTriageCard.sqf
- addons/medical/functions/fnc_setCardiacArrest.sqf
- addons/medical/stringtable.xml
#1473
Check pluse/rate had it's log localized globably
also swaped a few EFUNCs
tested working in mixed language mp:
> #1473 - Fix Medical Log Localization

- addons/rangecard/CfgVehicles.hpp
- addons/rangecard/functions/fnc_canShow.sqf
- addons/rangecard/functions/fnc_canShowCopy.sqf
* Also added the ability to copy your own rangecards
* Reference: https://github.com/acemod/ACE3/pull/1118
> Reordered the rangecard menu entries:

- addons/huntir/CfgVehicles.hpp
- addons/huntir/functions/fnc_cam.sqf
- addons/huntir/functions/fnc_handleFired.sqf
* Shooting the parachute will increase its damage
* The falling speed now increases with damage
* Damaged cameras won't be able to transmit video
* The HuntIR spawn positions now really depends on the grenade trajectory
> Made the HuntIR camera destroyable:

- addons/interaction/functions/fnc_addPassengersActions.sqf
http://i.imgur.com/QgfnUfe.jpg
> slot icons in passengers menu

- addons/interaction/CfgVehicles.hpp
> Manual MainActions position for some statics weapons

- addons/weather/XEH_postInit.sqf
- addons/weather/functions/fnc_updateRain.sqf
> Update rain each frame

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_unloadPersonLocal.sqf
- addons/medical/functions/fnc_actionUnloadUnit.sqf
Fix animation and unconscious unloading from vehicles #1575 and #1577
Switch to event driven.
> fix animation and consistently unload units from vehicle

- optionals/compat_cup/CfgAmmo.hpp
- optionals/compat_cup/CfgMagazines.hpp
- optionals/compat_cup/CfgWeapons.hpp
* Adjusted magazine initSpeed values
* Adjusted weapon initSpeed coefficients
* Recalculated all airFriction values
* Added missing ace configs to some classes
> CUP weapon config improvement:

- addons/huntir/CfgVehicles.hpp
- addons/tacticalladder/CfgVehicles.hpp
Fixes https://github.com/acemod/ACE3/issues/1664
> Added HuntIR and tactical ladder to ACE_Box_Misc

- version.html
Reported by @jastreb http://i.imgur.com/M8MPzhZ.png?1
> Update version number in version.html

- addons/common/CfgVehicles.hpp
And applied coding standards to `common/CfgVehicles.hpp`.
> Fixed CheckPBOs Module Whitelist defaultValue

- addons/map/CfgVehicles.hpp
- addons/map/XEH_postInitClient.sqf
- addons/map/functions/fnc_blueForceTrackingModule.sqf
- addons/map/functions/fnc_moduleMap.sqf
- addons/map/stringtable.xml
At least until new BFT is ready. Fixes https://github.com/acemod/ACE3/issues/414#issuecomment-93979783
> Blue Force Tracking ACE_Settings

- addons/microdagr/functions/fnc_showApplicationPage.sqf
- addons/microdagr/functions/fnc_updateDisplay.sqf
#573
Switch to common ambientBrightness and update live instead of on loading.
> mdagr use ambientBrightness

- addons/interaction/CfgVehicles.hpp
- addons/interaction/stringtable.xml
Simple action for opening boxes. Arma "Inventory" action can be annoying sometimes.
Demo: http://i.imgur.com/yY1RjHg.jpg
> Open action for boxes

- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_afrf3/config.cpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/config.cpp
RHS Headgear compatibility to https://github.com/acemod/ACE3/pull/1775
> RHS Headgear compat to hearing

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_checkFiles.sqf
- addons/common/functions/fnc_checkPBOs.sqf
- addons/common/functions/fnc_moduleCheckPBOs.sqf
> CheckPBO should ensure client isn't running any addons the server isn't

- addons/spectator/XEH_preInit.sqf
- addons/spectator/stringtable.xml
> [ace_spectator] Remove last remnants of view distance

- addons/concertina_wire/stringtable.xml
- addons/explosives/stringtable.xml
- addons/huntir/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/map/stringtable.xml
- addons/medical/stringtable.xml
- addons/sandbag/stringtable.xml
- addons/sitting/stringtable.xml
- addons/spectator/stringtable.xml
- addons/spottingscope/stringtable.xml
Update spanish translation.
Now no merge conflicts.
> Update spanish translation

- addons/main/script_macros.hpp
- addons/reloadlaunchers/functions/fnc_load.sqf
I don't even know how that happened.
> Fixed ELSTRING macro typo

- addons/nametags/ACE_Settings.hpp
> Revert "Fixed NameTags Settings defaults"

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/hearing/XEH_postInit.sqf
- addons/hearing/functions/fnc_earRinging.sqf
- addons/hearing/functions/fnc_explosionNear.sqf
- addons/hearing/functions/fnc_firedNear.sqf
- addons/hearing/functions/fnc_moduleHearing.sqf
- addons/hearing/functions/fnc_putInEarplugs.sqf
- addons/hearing/functions/fnc_removeEarplugs.sqf
- addons/hearing/functions/fnc_updateVolume.sqf
- addons/hearing/script_component.hpp
Fixes #1696 
Hearing had 2 PFEH: Volume adjust (I think from AGM) and ear ringing (from ACE2)
Merged together, keeping ACE2 logic for volume and deafness-recovery.
> Hearing PFEH unification / Flashbangs

- addons/huntir/functions/fnc_cam.sqf
- addons/huntir/functions/fnc_huntir.sqf
Fix #1856 (HuntIR monitor stays open even though its removed from inventory)
> Close huntIR monitor if item removed

- addons/concertina_wire/XEH_postInit.sqf
- addons/concertina_wire/XEH_preInit.sqf
- addons/concertina_wire/functions/fnc_handleKilled.sqf
- addons/concertina_wire/functions/fnc_vehicleDamage.sqf
- addons/concertina_wire/script_component.hpp
#1639 
handleKilled happens where wire is local,
this sends an event so the damage is applied where the car is local
> concWire - Apply damage where vehicle is local

- addons/parachute/CfgVehicles.hpp
> fix parachutes

- addons/medical/CfgActions.hpp
- addons/medical/config.cpp
Fix for http://i.imgur.com/XEUhwGC.jpg
> Fix for 'Treat at...' option

- addons/aircraft/CfgWeapons.hpp
- addons/hearing/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
As @jonpas suggested:
Little fix for M134 minigun rate of fire & dispersion
Change of hearing protection values for heli pilot helmets
> M134 minigun rate of fire & dispersion fix + hearing protection for heli pilots

- addons/common/functions/fnc_unloadPersonLocal.sqf
> Fix load unload unconscious

- addons/common/functions/fnc_loadPerson.sqf
- addons/common/functions/fnc_loadPersonLocal.sqf
Fixes boats #1729 and co-pilot seats #1727
> Fix load unconscious into boats and co-pilot seats

- documentation/feature/spectator.md
- documentation/missionmaker/modules.md
Work in progress documentation on the new ace_spectator feature. Includes:
- Configuration details
- Shortcut details
- Interface notes
- Module description
> ace_spectator documentation

- addons/parachute/functions/fnc_cutParachute.sqf
- addons/parachute/functions/fnc_doLanding.sqf
- addons/parachute/functions/fnc_storeParachute.sqf
> change form addBackpack to addBackpackGlobal

- addons/explosives/CfgModule.hpp
> #1931 - Fix Explosives Module Strings

- addons/map/CfgVehicles.hpp
- addons/map/XEH_postInitClient.sqf
- addons/map/functions/fnc_blueForceTrackingModule.sqf
Redone PR for release branch
Fix #1957
BFT module wasn't a ACE_Module
> Fix BFT Module / Settings (for 3.2.1)

- addons/finger/stringtable.xml
cherry-picked Pabst's description change
> PointingInsteadOfFinger

- addons/medical/functions/fnc_handleUnitVitals.sqf
I received feedback about the pain handling in advanced medical (@viperMaul). This could be a (temp) solution.
> Improvement for handling minor levels of pain in advanced medical

- documentation/feature/fcs.md
- documentation/feature/finger.md
- documentation/feature/interaction.md
- documentation/feature/parachute.md
- documentation/feature/sitting.md
- documentation/feature/slideshow.md
- documentation/missionmaker/class-names.md
- documentation/missionmaker/mission-tools.md
- documentation/missionmaker/modules.md
Updated the documentation for ACE 3.2.0
> Documentation pass 10

- documentation/feature/medical-system.md
- Did some formatting.
- Fixed some typos
Mean html bullied my markdown :/
> doc pass 9 typos fixed

- addons/zeus/functions/fnc_handleZeusUnitAssigned.sqf
- addons/zeus/functions/fnc_moduleCaptive.sqf
- addons/zeus/functions/fnc_moduleSurrender.sqf
- addons/zeus/functions/fnc_moduleUnconscious.sqf
- addons/zeus/functions/fnc_moduleZeusSettings.sqf
Code cleanup of the Zeus module.
> Code cleanup Zeus module

- addons/attach/functions/fnc_attach.sqf
- addons/attach/functions/fnc_canAttach.sqf
- addons/attach/functions/fnc_canDetach.sqf
- addons/attach/functions/fnc_detach.sqf
- addons/attach/functions/fnc_getChildrenAttachActions.sqf
- addons/attach/functions/fnc_placeApprove.sqf
Code cleanup of the Attach module.
> Code cleanup of the Attach module.

- addons/vehicles/functions/fnc_speedLimiter.sqf
- addons/vehicles/functions/fnc_startEngine.sqf
Code cleanup of the Vehicle module.
> Code cleanup Vehicle module

- addons/captives/functions/fnc_canApplyHandcuffs.sqf
- addons/captives/functions/fnc_canEscortCaptive.sqf
- addons/captives/functions/fnc_canFriskPerson.sqf
- addons/captives/functions/fnc_canLoadCaptive.sqf
- addons/captives/functions/fnc_canRemoveHandcuffs.sqf
- addons/captives/functions/fnc_canStopEscorting.sqf
- addons/captives/functions/fnc_canSurrender.sqf
- addons/captives/functions/fnc_canUnloadCaptive.sqf
- addons/captives/functions/fnc_doApplyHandcuffs.sqf
- addons/captives/functions/fnc_doEscortCaptive.sqf
- addons/captives/functions/fnc_doFriskPerson.sqf
- addons/captives/functions/fnc_doLoadCaptive.sqf
- addons/captives/functions/fnc_doRemoveHandcuffs.sqf
- addons/captives/functions/fnc_doUnloadCaptive.sqf
- addons/captives/functions/fnc_handleGetIn.sqf
- addons/captives/functions/fnc_handleGetOut.sqf
- addons/captives/functions/fnc_handleKilled.sqf
- addons/captives/functions/fnc_handleOnUnconscious.sqf
- addons/captives/functions/fnc_handlePlayerChanged.sqf
- addons/captives/functions/fnc_handleRespawn.sqf
- addons/captives/functions/fnc_handleUnitInitPost.sqf
- addons/captives/functions/fnc_handleZeusDisplayChanged.sqf
- addons/captives/functions/fnc_moduleSettings.sqf
- addons/captives/functions/fnc_moduleSurrender.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- addons/captives/functions/fnc_vehicleCaptiveMoveIn.sqf
- addons/captives/functions/fnc_vehicleCaptiveMoveOut.sqf
Code cleanup of the Captives module.
> Code cleanup of the Captives module.

- addons/medical_menu/functions/fnc_collectActions.sqf
- addons/medical_menu/functions/fnc_getTreatmentOptions.sqf
- addons/medical_menu/functions/fnc_handleUI_DisplayOptions.sqf
- addons/medical_menu/functions/fnc_handleUI_dropDownTriageCard.sqf
- addons/medical_menu/functions/fnc_onMenuOpen.sqf
- addons/medical_menu/functions/fnc_openMenu.sqf
- addons/medical_menu/functions/fnc_setTriageStatus.sqf
- addons/medical_menu/functions/fnc_updateActivityLog.sqf
- addons/medical_menu/functions/fnc_updateBodyImage.sqf
- addons/medical_menu/functions/fnc_updateIcons.sqf
- addons/medical_menu/functions/fnc_updateInformationLists.sqf
- addons/medical_menu/functions/fnc_updateUIInfo.sqf
Just went over the PR #2039's code to clean up some of code to bring them up to par, before it get's merged into master.
> Cleanup for medical_menu PR #2039

- addons/vehiclelock/functions/fnc_addKeyForVehicle.sqf
- addons/vehiclelock/functions/fnc_getVehicleSideKey.sqf
- addons/vehiclelock/functions/fnc_handleVehicleInitPost.sqf
- addons/vehiclelock/functions/fnc_hasKeyForVehicle.sqf
- addons/vehiclelock/functions/fnc_lockpick.sqf
- addons/vehiclelock/functions/fnc_moduleInit.sqf
- addons/vehiclelock/functions/fnc_moduleSync.sqf
- addons/vehiclelock/functions/fnc_onOpenInventory.sqf
- addons/vehiclelock/functions/fnc_serverSetupCustomKeyEH.sqf
- addons/vehiclelock/functions/fnc_setVehicleLockEH.sqf
Code cleanup of the Vehiclelock module.
> Code cleanup Vehiclelock module

- addons/slideshow/functions/fnc_addSlideActions.sqf
- addons/slideshow/functions/fnc_autoTransition.sqf
- addons/slideshow/functions/fnc_createSlideshow.sqf
- addons/slideshow/functions/fnc_makeList.sqf
- addons/slideshow/functions/fnc_moduleInit.sqf
Code cleanup of the Slideshow module.
> Code cleanup of Slideshow module

- addons/spottingscope/functions/fnc_pickup.sqf
- addons/spottingscope/functions/fnc_place.sqf
Code cleanup of the Spottingscope module.
> Cleanup code of Spottingscope module

- addons/tacticalladder/functions/fnc_cancelTLdeploy.sqf
- addons/tacticalladder/functions/fnc_confirmTLdeploy.sqf
- addons/tacticalladder/functions/fnc_deployTL.sqf
- addons/tacticalladder/functions/fnc_handleScrollWheel.sqf
- addons/tacticalladder/functions/fnc_pickupTL.sqf
- addons/tacticalladder/functions/fnc_positionTL.sqf
Code cleanup of the Tacticalladder module.
> Code cleanup in Tacticalladder module

- addons/tripod/functions/fnc_adjust.sqf
- addons/tripod/functions/fnc_handleScrollWheel.sqf
- addons/tripod/functions/fnc_pickup.sqf
- addons/tripod/functions/fnc_place.sqf
Code cleanup of the Tripod module.
> Code cleanup in Tripod module

- addons/common/functions/fnc_unloadPersonLocal.sqf
Fixes Unable to Unload Patient from Vehicle #2020
> isTouchingGround is unreliable for ground vehicles

- addons/weaponselect/functions/fnc_countMagazinesForGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_displayGrenadeTypeAndNumber.sqf
- addons/weaponselect/functions/fnc_findNextGrenadeMagazine.sqf
- addons/weaponselect/functions/fnc_findNextGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_fireSmokeLauncher.sqf
- addons/weaponselect/functions/fnc_getSelectedGrenade.sqf
- addons/weaponselect/functions/fnc_playChangeFiremodeSound.sqf
- addons/weaponselect/functions/fnc_putWeaponAway.sqf
- addons/weaponselect/functions/fnc_selectGrenadeAll.sqf
- addons/weaponselect/functions/fnc_selectGrenadeFrag.sqf
- addons/weaponselect/functions/fnc_selectGrenadeOther.sqf
- addons/weaponselect/functions/fnc_selectWeaponMode.sqf
- addons/weaponselect/functions/fnc_selectWeaponMuzzle.sqf
- addons/weaponselect/functions/fnc_selectWeaponVehicle.sqf
- addons/weaponselect/functions/fnc_setNextGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_throwGrenade.sqf
Code cleanup of the Weaponselect module.
> Code cleanup Weaponselect module

- addons/viewdistance/functions/fnc_adaptViewDistance.sqf
- addons/viewdistance/functions/fnc_changeViewDistance.sqf
- addons/viewdistance/functions/fnc_initModule.sqf
- addons/viewdistance/functions/fnc_returnObjectCoeff.sqf
- addons/viewdistance/functions/fnc_returnValue.sqf
Code cleanup of the Viewdistance module.
> Code cleanup Viewdistance module

- addons/medical/functions/fnc_treatment.sqf
- addons/medical/functions/fnc_treatment_failure.sqf
- addons/medical/functions/fnc_treatment_success.sqf
Fix #1866 (Fire mode resets after medical interaction)
> Treatment reset weapon mode

- addons/medical/ACE_Medical_Treatments.hpp
It uses animations that don't match at all what you are doing anyway so I think it's better to just disable anim for that actions which are:
* Checking pulse
* Checking BP
* Checking response
> Fix checking vitals anim

- addons/weaponselect/functions/fnc_countMagazinesForGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_displayGrenadeTypeAndNumber.sqf
- addons/weaponselect/functions/fnc_findNextGrenadeMagazine.sqf
- addons/weaponselect/functions/fnc_findNextGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_fireSmokeLauncher.sqf
- addons/weaponselect/functions/fnc_getSelectedGrenade.sqf
- addons/weaponselect/functions/fnc_playChangeFiremodeSound.sqf
- addons/weaponselect/functions/fnc_putWeaponAway.sqf
- addons/weaponselect/functions/fnc_selectGrenadeAll.sqf
- addons/weaponselect/functions/fnc_selectGrenadeFrag.sqf
- addons/weaponselect/functions/fnc_selectGrenadeOther.sqf
- addons/weaponselect/functions/fnc_selectWeaponMode.sqf
- addons/weaponselect/functions/fnc_selectWeaponMuzzle.sqf
- addons/weaponselect/functions/fnc_selectWeaponVehicle.sqf
- addons/weaponselect/functions/fnc_setNextGrenadeMuzzle.sqf
- addons/weaponselect/functions/fnc_throwGrenade.sqf
Thank you @jonpas for pointing that out.
(Also my deepest appologies to @Glowbal. Our hero of PRs)
> Updated function documentation of Weaponselect

- addons/ballistics/scripts/initTargetWall.sqf
Code cleanup of the Ballistics module.
> Code cleanup Ballistics module.

- addons/winddeflection/functions/fnc_handleFired.sqf
- addons/winddeflection/functions/fnc_initModuleSettings.sqf
- addons/winddeflection/functions/fnc_updateTrajectoryPFH.sqf
Code cleanup of the Winddeflection module.
> Code cleanup Winddeflection module

- addons/sitting/functions/fnc_canSit.sqf
- addons/sitting/functions/fnc_canStand.sqf
- addons/sitting/functions/fnc_getRandomAnimation.sqf
- addons/sitting/functions/fnc_handleInterrupt.sqf
- addons/sitting/functions/fnc_hasChairMoved.sqf
- addons/sitting/functions/fnc_moduleInit.sqf
- addons/sitting/functions/fnc_sit.sqf
- addons/sitting/functions/fnc_stand.sqf
Code cleanup of the Sitting module.
> Code cleanup of Sitting module

- addons/interaction/CfgVehicles.hpp
- addons/interaction/stringtable.xml
- addons/medical/CfgVehicles.hpp
- addons/medical/stringtable.xml
- addons/nametags/ACE_Settings.hpp
- addons/nametags/CfgVehicles.hpp
- addons/nametags/stringtable.xml
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateList.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateList.sqf
- addons/optionsmenu/stringtable.xml
Those were moved to common in #1985
> Removed duplicated strings

- addons/maptools/functions/fnc_canUseMapTools.sqf
> MapTools work on children of itemMap

- addons/medical/CfgVehicles.hpp
Any reason this is not a BOOL in the first place?
> Fixed missing string

- addons/scopes/functions/fnc_adjustScope.sqf
- addons/scopes/functions/fnc_adjustZero.sqf
- addons/scopes/functions/fnc_applyScopeAdjustment.sqf
- addons/scopes/functions/fnc_canAdjustZero.sqf
- addons/scopes/functions/fnc_firedEH.sqf
- addons/scopes/functions/fnc_getOptics.sqf
- addons/scopes/functions/fnc_inventoryCheck.sqf
- addons/scopes/functions/fnc_showZeroing.sqf
Code cleanup of the Scopes module.
> Code cleanup Scopes module

- addons/interact_menu/functions/fnc_addActionToClass.sqf
- addons/interact_menu/functions/fnc_addActionToObject.sqf
- addons/interact_menu/functions/fnc_collectActiveActionTree.sqf
- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_compileMenuZeus.sqf
- addons/interact_menu/functions/fnc_createAction.sqf
- addons/interact_menu/functions/fnc_ctrlSetParsedTextCached.sqf
- addons/interact_menu/functions/fnc_findActionNode.sqf
- addons/interact_menu/functions/fnc_handlePlayerChanged.sqf
- addons/interact_menu/functions/fnc_isSubPath.sqf
- addons/interact_menu/functions/fnc_keyDown.sqf
- addons/interact_menu/functions/fnc_keyUp.sqf
- addons/interact_menu/functions/fnc_removeActionFromClass.sqf
- addons/interact_menu/functions/fnc_removeActionFromObject.sqf
- addons/interact_menu/functions/fnc_renderActionPoints.sqf
- addons/interact_menu/functions/fnc_renderBaseMenu.sqf
- addons/interact_menu/functions/fnc_renderIcon.sqf
- addons/interact_menu/functions/fnc_renderMenu.sqf
- addons/interact_menu/functions/fnc_renderSelector.sqf
- addons/interact_menu/functions/fnc_setupTextColors.sqf
- addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf
- addons/interact_menu/functions/fnc_userActions_getHouseActions.sqf
Code cleanup of the Interact_menu module.
> Code cleanup Interact_menu module

- addons/disposable/XEH_postInit.sqf
- addons/disposable/functions/fnc_replaceATWeapon.sqf
- addons/disposable/functions/fnc_takeLoadedATWeapon.sqf
- addons/disposable/functions/fnc_updateInventoryDisplay.sqf
Code cleanup of Disposable module.
> Code cleanup of Disposable module

- addons/sandbag/functions/fnc_canDeploy.sqf
- addons/sandbag/functions/fnc_carry.sqf
- addons/sandbag/functions/fnc_deploy.sqf
- addons/sandbag/functions/fnc_deployCancel.sqf
- addons/sandbag/functions/fnc_deployConfirm.sqf
- addons/sandbag/functions/fnc_drop.sqf
- addons/sandbag/functions/fnc_handleScrollWheel.sqf
- addons/sandbag/functions/fnc_pickup.sqf
Code cleanup of the Sandbag module.
> Code cleanup of Sandbag module

- addons/finger/functions/fnc_incomingFinger.sqf
- addons/finger/functions/fnc_keyPress.sqf
- addons/finger/functions/fnc_moduleSettings.sqf
- addons/finger/functions/fnc_perFrameEH.sqf
Code cleanup of Fingering module is Incomming.
> Code cleanup of Finger module.

- addons/backpacks/XEH_postInit.sqf
- addons/backpacks/functions/fnc_backpackOpened.sqf
- addons/backpacks/functions/fnc_getBackpackAssignedUnit.sqf
- addons/backpacks/functions/fnc_isBackpack.sqf
- addons/backpacks/functions/fnc_onOpenInventory.sqf
Code cleanup of the Backpack module.
> Code cleanup of the Backpack module.

- addons/captives/CfgVehicles.hpp
- addons/captives/functions/fnc_canLoadCaptive.sqf
- addons/captives/functions/fnc_doLoadCaptive.sqf
> Don't use old Helicopter_F

- addons/hitreactions/functions/fnc_fallDown.sqf
Code cleanup of HitReaction module.
> Code cleanup of HitReaction module

- addons/cargo/XEH_preInit.sqf
- addons/cargo/functions/fnc_findNearestVehicle.sqf
- addons/cargo/functions/fnc_getSizeItem.sqf
- addons/cargo/functions/fnc_handleDestroyed.sqf
- addons/cargo/functions/fnc_initVehicle.sqf
- addons/cargo/functions/fnc_onMenuOpen.sqf
- addons/cargo/functions/fnc_startUnload.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/cargo/functions/fnc_validateCargoSpace.sqf
Fix findNearestVehicle dont return BOOL
Fix that findNearestVehicle dont return any time the nearest car
Small Performance Improvement in getSizeItem/handleDestroyed/startUnload
Enhance Some legibility
> some Cargo Changes

- addons/nametags/XEH_postInit.sqf
- addons/nametags/functions/fnc_canShow.sqf
- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- addons/nametags/functions/fnc_getVehicleData.sqf
- addons/nametags/functions/fnc_initIsSpeaking.sqf
- addons/nametags/functions/fnc_moduleNameTags.sqf
- addons/nametags/functions/fnc_onDraw3d.sqf
- addons/nametags/functions/fnc_setText.sqf
Cleanup to params and fix #2139
> nametag cleanup and fix cursortarget distance

- addons/common/functions/fnc_loadSettingsLocalizedText.sqf
- addons/interact_menu/ACE_Settings.hpp
- addons/medical/ACE_Settings.hpp
- addons/nametags/ACE_Settings.hpp
- addons/optionsmenu/functions/fnc_onCategorySelectChanged.sqf
- addons/optionsmenu/functions/fnc_onListBoxSettingsChanged.sqf
- addons/optionsmenu/functions/fnc_onServerCategorySelectChanged.sqf
- addons/optionsmenu/functions/fnc_onServerSaveInputField.sqf
- addons/optionsmenu/functions/fnc_onServerSettingsMenuOpen.sqf
- addons/optionsmenu/functions/fnc_onSettingsMenuOpen.sqf
- addons/optionsmenu/functions/fnc_onSliderPosChanged.sqf
- addons/optionsmenu/functions/fnc_resetSettings.sqf
- addons/optionsmenu/functions/fnc_serverResetSettings.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateList.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateList.sqf
- addons/optionsmenu/functions/fnc_stringEscape.sqf
- addons/optionsmenu/gui/settingsMenu.hpp
#2098
We need the filtered selection index in about 6 different places, so just store it in the lbValue.
> Option Menu Fixes for categories

- addons/laser/initKeybinds.sqf
removed shift from default Laser code down keybind
> default laser code down keybind fix

- addons/disarming/XEH_postInit.sqf
- addons/disarming/functions/fnc_canBeDisarmed.sqf
- addons/disarming/functions/fnc_canPlayerDisarmUnit.sqf
- addons/disarming/functions/fnc_disarmDropItems.sqf
- addons/disarming/functions/fnc_eventCallerFinish.sqf
- addons/disarming/functions/fnc_eventTargetFinish.sqf
- addons/disarming/functions/fnc_eventTargetStart.sqf
- addons/disarming/functions/fnc_getAllGearContainer.sqf
- addons/disarming/functions/fnc_getAllGearUnit.sqf
- addons/disarming/functions/fnc_openDisarmDialog.sqf
- addons/disarming/functions/fnc_showItemsInListbox.sqf
- addons/disarming/functions/fnc_verifyMagazinesMoved.sqf
Code cleanup of the Disarming module.
> Code cleanup of Disarming module

- addons/grenades/XEH_postInit.sqf
- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/grenades/functions/fnc_flashbangThrownFuze.sqf
- addons/grenades/functions/fnc_nextMode.sqf
- addons/grenades/functions/fnc_throwGrenade.sqf
- addons/grenades/textures/ace_m84.rvmat
Code cleanup of Grenades module.
> Code cleanup of Grenades module

- addons/common/functions/fnc_loadSettingsLocalizedText.sqf
- addons/common/functions/fnc_setSettingFromConfig.sqf
smaller `publicVariable`
non-dedicated server will still localize
> Don't broadcast localization for settings

- addons/logistics_uavbattery/functions/fnc_canRefuelUAV.sqf
- addons/logistics_uavbattery/functions/fnc_refuelUAV.sqf
Code Cleanup Logistic UAV Battery.
> Code Cleanup Logistic UAV Battery

- addons/captives/CfgVehicles.hpp
- addons/captives/stringtable.xml
- addons/common/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/optionsmenu/stringtable.xml
> Gienkov pl translation 5

- addons/common/functions/fnc_getAllGear.sqf
- addons/respawn/functions/fnc_restoreGear.sqf
> after respawn select last weapon, muzzle and mode

- addons/cargo/ACE_Settings.hpp
- addons/cargo/CfgVehicles.hpp
- addons/cargo/stringtable.xml
- addons/main/CfgModuleCategories.hpp
- addons/main/CfgVehicleClasses.hpp
- addons/main/config.cpp
- addons/main/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/repair/ACE_Settings.hpp
- addons/repair/CfgVehicleClasses.hpp
- addons/repair/CfgVehicles.hpp
- addons/repair/config.cpp
- addons/repair/stringtable.xml
- `ACE Logistics` group for mission modules
- `Logistics` category for ACE Options
- `ACE Logistics` vehicle class (`ACE_Logistics_Items`)
> Added Logistics Categories

- addons/cargo/CfgEventHandlers.hpp
- addons/concertina_wire/CfgVehicles.hpp
- addons/medical/CfgVehicles.hpp
Fixed version of accidentally removed https://github.com/acemod/ACE3/pull/2190
> Cargo support for bodybag and concertina

- addons/magazinerepack/functions/fnc_getMagazineChildren.sqf
- addons/magazinerepack/functions/fnc_magazineRepackFinish.sqf
- addons/magazinerepack/functions/fnc_magazineRepackProgress.sqf
- addons/magazinerepack/functions/fnc_simulateRepackEvents.sqf
- addons/magazinerepack/functions/fnc_startRepackingMagazine.sqf
Code Cleanup Magazine Repack Module.
> Code Cleanup Magazine Repack Module

- addons/safemode/XEH_preInit.sqf
- addons/safemode/functions/fnc_firstMode.sqf
- addons/safemode/functions/fnc_lockSafety.sqf
- addons/safemode/functions/fnc_playChangeFiremodeSound.sqf
- addons/safemode/functions/fnc_setSafeModeVisual.sqf
- addons/safemode/functions/fnc_unlockSafety.sqf
Code Cleanup of the Safemode module
> Code cleanup Safemode module

- addons/attach/stringtable.xml
- addons/cargo/stringtable.xml
- addons/explosives/stringtable.xml
- addons/interaction/stringtable.xml
- addons/main/stringtable.xml
- addons/medical/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/repair/stringtable.xml
- addons/zeus/stringtable.xml
This is a WIP since there are many new modules to come and stringtables to translate, I will confirm when this is ready to merge.
> PL translation and fixes

- addons/medical_menu/functions/fnc_canOpenMenu.sqf
- addons/medical_menu/functions/fnc_collectActions.sqf
- addons/medical_menu/functions/fnc_handleUI_DisplayOptions.sqf
- addons/medical_menu/functions/fnc_onMenuOpen.sqf
- addons/medical_menu/functions/fnc_openMenu.sqf
- addons/medical_menu/functions/fnc_updateInformationLists.sqf
- addons/medical_menu/stringtable.xml
- addons/medical_menu/ui/menu.hpp
Code Cleanup Medical Menu Module.
> Code Cleanup Medical Menu Module

- addons/markers/XEH_preInit.sqf
- addons/markers/functions/fnc_initInsertMarker.sqf
- addons/markers/functions/fnc_mapDrawEH.sqf
- addons/markers/functions/fnc_onLBSelChangedColor.sqf
- addons/markers/functions/fnc_onLBSelChangedShape.sqf
- addons/markers/functions/fnc_onSliderPosChangedAngle.sqf
- addons/markers/functions/fnc_placeMarker.sqf
- addons/markers/functions/fnc_sendMarkersJIP.sqf
- addons/markers/functions/fnc_setMarkerJIP.sqf
- addons/markers/functions/fnc_setMarkerNetwork.sqf
> Code Cleanup Marker Module

- addons/laserpointer/XEH_postInit.sqf
> remove asdg message

- addons/rangecard/stringtable.xml
rangecard stringtable : french translation
> rangecard stringtable : french translation

- addons/optionsmenu/functions/fnc_exportSettings.sqf
Fix #2188
Fix outputting color arrays when including client settings.
>  - Fix Exporting Color Arrays

- addons/dragging/XEH_clientInit.sqf
- addons/dragging/XEH_serverInit.sqf
- addons/dragging/functions/fnc_canCarry.sqf
- addons/dragging/functions/fnc_canDrag.sqf
- addons/dragging/functions/fnc_canDrop.sqf
- addons/dragging/functions/fnc_canDrop_carry.sqf
- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dragObject.sqf
- addons/dragging/functions/fnc_dragObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/dragging/functions/fnc_getWeight.sqf
- addons/dragging/functions/fnc_handleAnimChanged.sqf
- addons/dragging/functions/fnc_handleKilled.sqf
- addons/dragging/functions/fnc_handlePlayerChanged.sqf
- addons/dragging/functions/fnc_handlePlayerWeaponChanged.sqf
- addons/dragging/functions/fnc_handleScrollWheel.sqf
- addons/dragging/functions/fnc_handleUnconscious.sqf
- addons/dragging/functions/fnc_initObject.sqf
- addons/dragging/functions/fnc_initPerson.sqf
- addons/dragging/functions/fnc_isObjectOnObject.sqf
- addons/dragging/functions/fnc_setCarryable.sqf
- addons/dragging/functions/fnc_setDraggable.sqf
- addons/dragging/functions/fnc_startCarry.sqf
- addons/dragging/functions/fnc_startCarryPFH.sqf
- addons/dragging/functions/fnc_startDrag.sqf
- addons/dragging/functions/fnc_startDragPFH.sqf
Code cleanup of Dragging module.
> Code cleanup of Dragging module

- addons/switchunits/functions/fnc_addMapFunction.sqf
- addons/switchunits/functions/fnc_handleMapClick.sqf
- addons/switchunits/functions/fnc_initPlayer.sqf
- addons/switchunits/functions/fnc_isValidAi.sqf
- addons/switchunits/functions/fnc_markAiOnMap.sqf
- addons/switchunits/functions/fnc_module.sqf
- addons/switchunits/functions/fnc_nearestPlayers.sqf
- addons/switchunits/functions/fnc_startSwitchUnits.sqf
- addons/switchunits/functions/fnc_switchBack.sqf
- addons/switchunits/functions/fnc_switchUnit.sqf
Code cleanup of the Switchunits module.
> Code cleanup of Switchunits module

- addons/huntir/functions/fnc_cam.sqf
- addons/huntir/functions/fnc_handleFired.sqf
- addons/huntir/functions/fnc_huntir.sqf
- addons/huntir/functions/fnc_huntirCompass.sqf
Code cleanup of HuntIR module.
> Code cleanup of HuntIR module

- addons/microdagr/CfgVehicles.hpp
- addons/microdagr/functions/fnc_appMarkKeypadEntry.sqf
- addons/microdagr/functions/fnc_appMenuButtonConnectRangefinder.sqf
- addons/microdagr/functions/fnc_appSettingsLBClick.sqf
- addons/microdagr/functions/fnc_appWaypointsButtonDeleteWP.sqf
- addons/microdagr/functions/fnc_appWaypointsButtonSetWP.sqf
- addons/microdagr/functions/fnc_canShow.sqf
- addons/microdagr/functions/fnc_deviceAddWaypoint.sqf
- addons/microdagr/functions/fnc_deviceDeleteWaypoint.sqf
- addons/microdagr/functions/fnc_deviceGetWaypoints.sqf
- addons/microdagr/functions/fnc_dialogClosedEH.sqf
- addons/microdagr/functions/fnc_mapButtonDownEH.sqf
- addons/microdagr/functions/fnc_mapDoubleTapEH.sqf
- addons/microdagr/functions/fnc_mapOnDrawEH.sqf
- addons/microdagr/functions/fnc_modeMapButtons.sqf
- addons/microdagr/functions/fnc_moduleMapFill.sqf
- addons/microdagr/functions/fnc_openDisplay.sqf
- addons/microdagr/functions/fnc_recieveRangefinderData.sqf
- addons/microdagr/functions/fnc_saveCurrentAndSetNewMode.sqf
- addons/microdagr/functions/fnc_showApplicationPage.sqf
- addons/microdagr/functions/fnc_updateDisplay.sqf
- addons/microdagr/stringtable.xml
Code Cleanup MicroDagr Module.
> Code Cleanup MicroDagr Module

- addons/interaction/CfgVehicles.hpp
- addons/interaction/XEH_postInit.sqf
- addons/interaction/functions/fnc_push.sqf
#2045
Note: sub couldn't be pushed because it's `mass` is 2600 and we had a limit of 1000.
2600 is more than twice a hatchback, mass is kinda wonky in this game.
I just upped it to 2600.  The big big assault boat is 9600, so it still cannot be pushed.
Also switched to use event system.
> Push SDV sub, cleanup push

- addons/realisticnames/CfgWeapons.hpp
New Hitpoints have some really messy inheritance
> realisticnames 1.50 Updating Base Class Changes

- addons/hearing/ACE_Settings.hpp
- addons/hearing/CfgVehicles.hpp
- addons/hearing/functions/fnc_earRinging.sqf
- addons/hearing/functions/fnc_moduleHearing.sqf
- addons/hearing/stringtable.xml
Feature request from @SzwedzikPL
Add setting for hearing to effect zeus RC - (part of #1961)
> Setting to disable hearing for zeus RC

- AUTHORS.txt
- README.md
- documentation/README_DE.md
- documentation/README_PL.md
Someone check new German translations, I used @jokoho48 but he isn't too confident. :grin: 
- Changed `ACE` to `ACE3`
- Fixed links
- Added missing parts in DE version
- Changed `*` to `-`
> Updated README.md files

- addons/attach/CfgEventHandlers.hpp
- addons/attach/XEH_preInit.sqf
- addons/attach/functions/fnc_attach.sqf
- addons/attach/functions/fnc_canAttach.sqf
- addons/attach/functions/fnc_canDetach.sqf
- addons/attach/functions/fnc_detach.sqf
- addons/attach/functions/fnc_handleGetIn.sqf
- addons/attach/functions/fnc_handleGetOut.sqf
- addons/attach/functions/fnc_handleKilled.sqf
- addons/attach/functions/fnc_placeApprove.sqf
* #2200 - Because attach doesn't work when mounted, uses @rebelvg idea and just deleted when getting in and then restores when getting out.
* #2300 - Handles units and vehicles getting "killed", detaches attached. Deletes if they are a vehicle.
* #1571 - Handles "null" attached objects
> Attach event handlers

- addons/main/config.cpp
- addons/main/script_component.hpp
> Update Main Config File

- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/medical/stringtable.xml
- addons/slideshow/stringtable.xml
- addons/spectator/stringtable.xml
New PT-BR translations, including the slideshow and spectator module.
> Added PT-BR translations

- addons/slideshow/functions/fnc_addSlideActions.sqf
- addons/slideshow/functions/fnc_autoTransition.sqf
- addons/slideshow/functions/fnc_createSlideshow.sqf
- addons/slideshow/functions/fnc_makeList.sqf
- addons/slideshow/functions/fnc_moduleInit.sqf
Mainly removed privatizing of non-existing variables as they were removed with #1986
> Cleaned up Slideshow privates

- addons/respawn/functions/fnc_restoreGear.sqf
Fixes an error when dying in vehicles
> fix restore gear

- addons/ballistics/CfgAmmo.hpp
I entered what feels right. All values are from Arma, except those with comments.
> better scaling for tracer sizes, fix #1008

- addons/repair/ACE_Settings.hpp
Setting "engineerSetting_fullRepair" had an out of bounds default value.
> Repair: Fix possible out of bounds setting

- addons/optionsmenu/config.cpp
> Fix main menu info151

- addons/repair/ACE_Repair.hpp
- addons/repair/ACE_Settings.hpp
- addons/repair/CfgVehicles.hpp
- addons/repair/functions/fnc_canRepair.sqf
- addons/repair/functions/fnc_moduleRepairSettings.sqf
- addons/repair/functions/fnc_repair.sqf
- addons/repair/stringtable.xml
Add ace setting to allow replace/remove wheels without a toolkit.
> Add Setting for toolkit requirement for wheel repair

- addons/aircraft/CfgAmmo.hpp
- addons/aircraft/CfgMagazines.hpp
> disable a10 tracers, commanche tracers only nvg

- addons/aircraft/CfgAmmo.hpp
- addons/aircraft/CfgMagazines.hpp
Reverts acemod/ACE3#2441
Until we have done some more search and because https://youtu.be/Vv6EST9Te_I?t=32m26s 
@ViperMaul
> Revert "disable a10 tracers, commanche tracers only nvg"

- addons/cargo/CfgVehicles.hpp
tweak Cargo Size for B_Truck_01_Base and B_Truck_01_box_F
fixes #2453
> tweak Cargo Size for B_Truck_01_Base and B_Truck_01_box_F

- addons/advanced_ballistics/functions/fnc_handleFirePFH.sqf
- addons/advanced_ballistics/functions/fnc_handleFired.sqf
> Fix Advaced Basllistic Performance bug

- addons/cargo/functions/fnc_loadItem.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/cargo/stringtable.xml
closes https://github.com/acemod/ACE3/issues/2476
> display text when loading / unloading cargo

- addons/common/functions/fnc_checkFiles.sqf
- optionals/noactionmenu/$PBOPREFIX$
- optionals/noactionmenu/CfgActions.hpp
- optionals/noactionmenu/README.md
- optionals/noactionmenu/config.cpp
- optionals/noactionmenu/script_component.hpp
hides:
Weapon P07
Weapon MX
Weapon NLAW
#414
> optional pbo to hide select weapon actions

- addons/repair/CfgEventHandlers.hpp
> only run addSpareParts on server

- addons/common/functions/fnc__handleNetEvent.sqf
- addons/common/functions/fnc__handleRequestAllSyncedEvents.sqf
- addons/common/functions/fnc__handleRequestSyncedEvent.sqf
- addons/common/functions/fnc__handleSyncedEvent.sqf
- addons/common/functions/fnc_addActionEventHandler.sqf
- addons/common/functions/fnc_addActionMenuEventHandler.sqf
- addons/common/functions/fnc_addCanInteractWithCondition.sqf
- addons/common/functions/fnc_addCuratorUnloadEventhandler.sqf
- addons/common/functions/fnc_addEventHandler.sqf
- addons/common/functions/fnc_addLineToDebugDraw.sqf
- addons/common/functions/fnc_addMapMarkerCreatedEventHandler.sqf
- addons/common/functions/fnc_addScrollWheelEventHandler.sqf
- addons/common/functions/fnc_addSetting.sqf
- addons/common/functions/fnc_addSyncedEventHandler.sqf
- addons/common/functions/fnc_addToInventory.sqf
- addons/common/functions/fnc_ambientBrightness.sqf
- addons/common/functions/fnc_applyForceWalkStatus.sqf
- addons/common/functions/fnc_binarizeNumber.sqf
- addons/common/functions/fnc_blurScreen.sqf
ref: https://github.com/acemod/ACE3/pull/2012/files
> common code cleanup part 2

- addons/advanced_ballistics/stringtable.xml
- addons/captives/stringtable.xml
- addons/cargo/stringtable.xml
- addons/common/stringtable.xml
- addons/dagr/stringtable.xml
- addons/explosives/stringtable.xml
- addons/finger/stringtable.xml
- addons/flashlights/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/main/stringtable.xml
- addons/map/stringtable.xml
- addons/medical/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/parachute/stringtable.xml
- addons/repair/stringtable.xml
- addons/slideshow/stringtable.xml
- addons/spectator/stringtable.xml
- addons/zeus/stringtable.xml
update spanish translation after 330
> update spanish translation after 330

- addons/vehiclelock/functions/fnc_lockpick.sqf
> Fix for #2495

- addons/medical/CfgVehicles.hpp
Solves #2526 where medical litter would appear in zeus with no name.
> Fix medical litter scopeCurator values

- addons/spectator/stringtable.xml
- tools/search_undefinedFunctions.py
Python script to generate a sqf script that checks all functions in game and makes sure they are defined.
I know there are some false positives in javelin as there functions are defined when used and not in preInit.
Output:
```
*********** Scaning for nil functions [count 857]
ace_interaction_fnc_showMenu is nil
ace_common_fnc_waitAndExec is nil
ace_common_fnc_localAnim is nil
ace_common_fnc_sendDisplayInformationTo is nil
ace_repair_fnc_isInStableCondition is nil
ace_interaction_fnc_openSubMenuSelf is nil
ace_interaction_fnc_addToTooltip is nil
ace_common_fnc_sendDisplayMessageTo is nil
ace_scopes_fnc_onDrawShortdot is nil
ace_common_fnc_makeCopyOfBody is nil
ace_common_fnc_displayMessage is nil
ace_common_fnc_disableKeyInput is nil
ace_common_fnc_sendHintTo is nil …
```
> Script to search for undefined functions

- wiki/feature/spectator.md
Remove outdated note
Provide the available camera modes in function header preview
Clarify the side filtering mechanism
> Update spectator document

- addons/repair/CfgVehicles.hpp
- addons/repair/README.md
- addons/repair/config.cpp
- addons/repair/functions/fnc_addRepairActions.sqf
- addons/repair/functions/fnc_canMiscRepair.sqf
- addons/repair/stringtable.xml
Picked from #2366 as it contained merges from master, as requested by @Glowbal
> Minor Repair Cleanup for release

- addons/medical/ACE_Medical_Actions.hpp
> Torso diag fix

- addons/cargo/CfgEventHandlers.hpp
- addons/cargo/functions/fnc_addCargoItem.sqf
- addons/cargo/functions/fnc_initVehicle.sqf
- addons/cargo/functions/fnc_loadItem.sqf
- addons/cargo/script_component.hpp
- addons/repair/CfgEventHandlers.hpp
- addons/repair/script_component.hpp
Actually fix #2488
Switching to InitPost seems to fix the problem with setVariable not working
Also fixes the same problem with `ACE_Cargo` in cargo.
> Fix cargo setVariable on server with InitPost

- addons/explosives/functions/fnc_addExplosiveActions.sqf
> Delay one frame when selecting explosives

- wiki/development/coding-guidelines.md
> Added Private Variable naming conventions to PR #2571

- addons/common/functions/fnc_fixFloating.sqf
ref: #2279
uses new hit indecies and getAllHitPointDamges command
> fix fixFloating resetting reflector hitpoints, close #2279

- addons/cargo/functions/fnc_initVehicle.sqf
> dont access cargo of destroyed vehicles, fix #2523

- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dragObjectPFH.sqf
- addons/dragging/functions/fnc_startCarryPFH.sqf
- addons/dragging/functions/fnc_startDragPFH.sqf
`EFUNC(common,isAlive)` is deprecated.
> Replaced isAlive function with alive command

- addons/slideshow/functions/fnc_createSlideshow.sqf
- addons/slideshow/functions/fnc_moduleInit.sqf
- addons/slideshow/script_component.hpp
- Improved public function parameter handling
- Fixed possible issue with synchronized objects
- Changed default duration to a macro
> Improved Slideshow API

- team.html
https://en.wiktionary.org/wiki/contributers :banana:
> Fix misspelling of Contributers

- addons/interact_menu/XEH_clientInit.sqf
- addons/interact_menu/functions/fnc_render.sqf
fix #2486 (might fix #1171 as well???)
* setupTextColors now runs after SettingsInitialized and only then do we install render
* settingsChanged uses count to handle possible capitalization differences
* minor optimization in fnc_render - (save 0.015ms wow !!!!!!!!)
> Interact menu settings after init

- addons/medical/functions/fnc_addToTriageCard.sqf
- addons/medical_menu/functions/fnc_handleUI_DisplayOptions.sqf
#2672
ACE_gameTime is just `time`, which should be synchronized
> Use ACE_gameTime for triage card

- addons/cargo/functions/fnc_canLoad.sqf
> Disable loading into locked vehicles.

- wiki/missionmaker/class-names.md
> doc pass 12 classnames

- .travis.yml
- tools/sqf_validator.py
* Checks all sqf files within given module or entire project for missing [] {} or ()
* Prints out information regarding anything it marks as a possible error
> Add a first implementation of the sqf validator/parser/linter.

- addons/weather/functions/fnc_calculateAirDensity.sqf
- addons/weather/functions/fnc_calculateBarometricPressure.sqf
- addons/weather/functions/fnc_calculateDewPoint.sqf
- addons/weather/functions/fnc_calculateHeatIndex.sqf
- addons/weather/functions/fnc_calculateRoughnessLength.sqf
- addons/weather/functions/fnc_calculateTemperatureAtHeight.sqf
- addons/weather/functions/fnc_calculateWetBulb.sqf
- addons/weather/functions/fnc_calculateWindChill.sqf
- addons/weather/functions/fnc_calculateWindSpeed.sqf
- addons/weather/functions/fnc_getWind.sqf
- addons/weather/functions/fnc_initModuleSettings.sqf
- addons/weather/functions/fnc_updateRain.sqf
Code cleanup of the Weather module.
> Code cleanup Weather module

- addons/common/CfgVehicles.hpp
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_binocularMagazine.sqf
- addons/common/functions/fnc_dropBackpack.sqf
- addons/common/functions/fnc_getAllGear.sqf
- addons/common/functions/fnc_removeBinocularMagazine.sqf
- addons/common/functions/fnc_selectWeaponMode.sqf
- addons/common/functions/fnc_setAllGear.sqf
- addons/disposable/functions/fnc_takeLoadedATWeapon.sqf
- addons/respawn/functions/fnc_handleKilled.sqf
- addons/respawn/functions/fnc_restoreGear.sqf
fixes:
- respawn script adding additional weapon items if you were having an already equipped weapon class (similar to the prefilled backpack issue)
- certain scripts that add (launcher) magazines no longer worked, because BI changed the maximum load of "Bag_Base" to zero. (includes respawning with launcher magazine)
- compatibility with "binoculars" with magazines (custom laserrangefinders)
> fix missing magazines after certain scenarios

- tools/sqf_validator.py
Should be python 2x compatible
> Validate sqf - python 3 compat

- tools/deploy.py
> Fix link in deploy tool

- addons/cargo/CfgVehicles.hpp
> Cargo: Make "Supply Box" pallets heavy

- .travis.yml
- LICENSE
- addons/attach/functions/fnc_handleGetIn.sqf
- addons/attach/functions/fnc_handleGetOut.sqf
- addons/reload/functions/fnc_canCheckAmmo.sqf
- tools/deploy.py
@Glowbal 
Used proper syntax, fixed `GH_TOKEN` check, improved if checks, merged both pygithub installs into one IF, moved SQF Validator before deploy.
All the commits before last 2 are from merging branch `master` into this branch, it's non-issue, just GitHub going weird when PRing into a PR.
> Enhance Travis Config

- .travis.yml
- tools/deploy.py
- Enable sqf validation on all branches
- Have the deploy script only run on the master branch.
> Run the travis deploy on master only

- .travis.yml
Adds slack notifications for failed CI builds to the dev channel.
> Add slack notification for ace3public dev channel

- tools/sqf_validator.py
- fix not all string cases were caught
- add basic semi column validation after code blocks
- Improve print output
- Fix a dot in file path when reporting an error
> Improve sqf validator

- tools/sqf_validator.py
Use a forward slash in path for travis to work properly
> Revert the backslash in sqf validator

- addons/missileguidance/functions/fnc_seekerType_Optic.sqf
We found the Titan didn't hit correctly the Punisher. In this link
http://www.15bandenere.com/forum/showthread.php?tid=619&pid=12002#pid12002 you can see the screenshots of an NLAW and Titan.
After looking for some memory points, I guess the simplest solution is to use aimPos, but I don't know if it breaks something else.
> Fix: Titan hitting ground instead of vehicle

- addons/concertina_wire/XEH_init.sqf
- addons/concertina_wire/functions/fnc_deploy.sqf
- addons/concertina_wire/functions/fnc_dismount.sqf
- addons/concertina_wire/functions/fnc_dismountSuccess.sqf
- addons/concertina_wire/functions/fnc_handleDamage.sqf
- addons/concertina_wire/functions/fnc_handleKilled.sqf
- addons/concertina_wire/functions/fnc_vehicleDamage.sqf
Code cleanup Concertina_wire Module.
> Code cleanup of Concertina_wire Module

- addons/map/ACE_Settings.hpp
- addons/map/CfgVehicles.hpp
- addons/map/XEH_postInitClient.sqf
- addons/map/functions/fnc_moduleMap.sqf
- addons/map/stringtable.xml
From @NemesisRE
ACE_setting to set the marker channel at mission start
> Set Default Channel at mission start

- wiki/missionmaker/modules.md
modules list updated for 3.3.2.
> doc pass 12 modules

- README.md
- docs/README_DE.md
- docs/README_PL.md
See https://github.com/acemod/ACE3/pull/2714#issuecomment-146703378 for reference.
> Use "flat-square" badge style

- addons/medical/functions/fnc_createLitter.sqf
- addons/medical_menu/ACE_Settings.hpp
- addons/medical_menu/XEH_postInit.sqf
- addons/medical_menu/functions/fnc_canOpenMenu.sqf
- addons/medical_menu/functions/fnc_collectActions.sqf
- addons/medical_menu/functions/fnc_getTreatmentOptions.sqf
- addons/medical_menu/functions/fnc_handleUI_DisplayOptions.sqf
- addons/medical_menu/functions/fnc_handleUI_dropDownTriageCard.sqf
- addons/medical_menu/functions/fnc_module.sqf
- addons/medical_menu/functions/fnc_onMenuClose.sqf
- addons/medical_menu/functions/fnc_onMenuOpen.sqf
- addons/medical_menu/functions/fnc_openMenu.sqf
- addons/medical_menu/functions/fnc_updateActivityLog.sqf
- addons/medical_menu/functions/fnc_updateBodyImage.sqf
- addons/medical_menu/functions/fnc_updateIcons.sqf
- addons/medical_menu/functions/fnc_updateInformationLists.sqf
- addons/medical_menu/functions/fnc_updateQuickViewLog.sqf
- addons/medical_menu/functions/fnc_updateUIInfo.sqf
- addons/medical_menu/ui/menu.hpp
#2580 - Fix Litter always created at 0 ATL
#2528 - Menu didn't check distance, and add dragging actions
> Medical Menu Fixes

- addons/medical/ACE_Settings.hpp
- addons/medical/functions/fnc_canTreat.sqf
- addons/medical/functions/fnc_treatment.sqf
Fix #2765
When set to 4 it should return false.
> Fix medical location check when set to disabled for PAK/Surgical

- CONTRIBUTING.md
@alganthe @PabstMirror 
https://ace3public.slack.com/archives/documentation/p1445374371000023
> Fix contributing guidelines links

- addons/map/CfgAmmo.hpp
- addons/map/XEH_postInitClient.sqf
Fix #2828
@voiperr - this should be fine, just wanted to check with you
> Fix empty flashlightProxy model + Delete map glow lights from disconnecting players

- addons/repair/functions/fnc_addRepairActions.sqf
Only valid hit selection + hit point combinations are usable for repair points:
- Empty hit points mean there isn't enough information to display to the user
- Empty hit selections mean that the hit point doesn't actually exist
Fixes the random repair actions with no text that didn't work as well as the lack of actions for valid repair points on some vehicles.
This also removes the restriction on glass hit points since 3rd party content doesn't necessarily use the same names. However the amount of glass points is kind of obnoxious so maybe that should be added back in - plus they don't seem like a priority vehicle part and takes up some screen space.
Tried to make the code a bit more readable, but it looks like the repair stuff is kind of messy as is. Should probably go through and make …
> Fix broken repair point selection code

- tools/search_privates.py
> Local privates to search_privates.py

- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_dumpArray.sqf
- addons/common/functions/fnc_getTurretIndex.sqf
- addons/common/functions/fnc_hasHatch.sqf
- addons/common/functions/fnc_selectWeaponMode.sqf
- addons/common/functions/fnc_setAllGear.sqf
- addons/common/functions/fnc_timePFH.sqf
- addons/goggles/XEH_postInit.sqf
- addons/goggles/functions/fnc_applyDirtEffect.sqf
- addons/goggles/functions/fnc_applyDustEffect.sqf
- addons/goggles/functions/fnc_applyRainEffect.sqf
- addons/goggles/functions/fnc_applyRotorWashEffect.sqf
- addons/goggles/functions/fnc_handleFired.sqf
- addons/goggles/functions/fnc_isDivingGoggles.sqf
- addons/goggles/functions/fnc_isInRotorWash.sqf
- addons/interaction/XEH_postInit.sqf
- addons/logistics_wirecutter/functions/fnc_isFence.sqf
- addons/medical/functions/fnc_translateSelections.sqf
- addons/medical_menu/XEH_postInit.sqf
- addons/medical_menu/functions/fnc_updateBodyImage.sqf
- addons/reload/functions/fnc_canCheckAmmo.sqf
- addons/respawn/functions/fnc_restoreGear.sqf
> replace local keyword with private

- addons/goggles/config.cpp
- addons/hearing/CfgWeapons.hpp
- addons/medical/CfgVehicles.hpp
Soldiers no longer inherit hitpoints from CaManBase
Adds a macro to deal with them
> Fix UBC for 1.54

- addons/inventory/RscDisplayInventory.hpp
Add inventory resize for the new GL magazines
> Inventory Resize UI - changes for 154 GL-Mags

- addons/hearing/ACE_Settings.hpp
- addons/hearing/CfgEventHandlers.hpp
- addons/hearing/CfgVehicles.hpp
- addons/hearing/XEH_preInit.sqf
- addons/hearing/functions/fnc_addEarPlugs.sqf
- addons/hearing/functions/fnc_handleRespawn.sqf
- addons/hearing/functions/fnc_moduleHearing.sqf
- addons/hearing/stringtable.xml
Fix #2833
Use same loudness calc as firedNear (replacing old audibleFire)
Give ear plugs to machine gunners (depends on magzine size)
Changes from old system (when used with RHS compat pbos):
Seems reasonable, mainly adds MGs, and drops the SMG
`weapon - audibleFire (old system) - effective loudness (boosted for MGs)`
```
Diff: New will get - LMG_Mk200_F - 8 - 0.246045
Diff: New will get - LMG_Mk200_MRCO_F - 8 - 0.246045
Diff: New will get - LMG_Mk200_pointer_F - 8 - 0.246045
Diff: New will get - arifle_MX_SW_F - 8 - 0.246045
Diff: New will get - arifle_MX_SW_pointer_F - 8 - 0.246045
Diff: New will get - arifle_MX_SW_Hamr_pointer_F - 8 - 0.246045
Diff: New will get - arifle_MX_SW_Black_F - 8 - 0.246045
Diff: New will get - arifle_MX_SW_Black_Hamr_pointer_F - 8 - 0.246045
Diff: New won't …
```
> Hearing - Add earplugs based on loudness and give to MGs and fix respawn issues

- addons/laser/CfgVehicles.hpp
> Fixed Laser Update Position Bug

- addons/nametags/functions/fnc_drawNameTagIcon.sqf
> fix UGV Nametag issue

- addons/cargo/CfgEventHandlers.hpp
- addons/cargo/CfgVehicles.hpp
- addons/dragging/CfgVehicles.hpp
- addons/interaction/CfgVehicles.hpp
I remade it and removed comments and unnecessary strings. I also removed the nonworking one from the last version.
> [REMADE] RoadCone_F and its inhered RoadBarrier_F intractable

- AUTHORS.txt
Please add my name to the credits. :smiley:
> Add name to authors.txt

- wiki/framework/sitting-framework.md
This will be live in 3.4.0, currently in master.
Tagging @alganthe
> Add Sitting Framework Documentation

- addons/common/functions/fnc_binocularMagazine.sqf
> Fix binocular related bugs

- addons/microdagr/gui.hpp
> MicroDagr - Add #undef to config for pboProject

- wiki/framework/settings-framework.md
> Add Mission Parameter Information to ace wiki

- addons/cargo/stringtable.xml
- addons/common/stringtable.xml
- addons/hearing/stringtable.xml
- addons/main/stringtable.xml
- addons/medical/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/nametags/stringtable.xml
- addons/repair/stringtable.xml
- addons/respawn/stringtable.xml
- addons/sitting/stringtable.xml
- addons/slideshow/stringtable.xml
- addons/zeus/stringtable.xml
@licht-im-Norden87
Fixed merge conflicts and rebased both your PRs for release branch if we wanted this for 3.4.1?
Replaces #2658 #2660
> Update German Stringtables

- addons/captives/stringtable.xml
- addons/cargo/stringtable.xml
- addons/common/stringtable.xml
- addons/dagr/stringtable.xml
- addons/dragging/stringtable.xml
- addons/finger/stringtable.xml
- addons/grenades/stringtable.xml
- addons/hearing/stringtable.xml
- addons/huntir/stringtable.xml
- addons/map_gestures/stringtable.xml
- addons/medical/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/repair/stringtable.xml
- addons/slideshow/stringtable.xml
- addons/spectator/stringtable.xml
- addons/tacticalladder/stringtable.xml
- addons/weaponselect/stringtable.xml
- addons/zeus/stringtable.xml
Fixed Merge conflcits for #2838 
Rebased for release if we want for 3.4.1?
> Czech Translations - Update

- addons/common/functions/fnc_unloadPersonLocal.sqf
- addons/rearm/XEH_postInit.sqf
- addons/refuel/XEH_postInit.sqf
Fix #2963 refuel `handleOnUnconscious` doesn't exist
Fix #2961 air unload logic inverted
> Fix refuel unconc error - Man unloading for air

- addons/common/stringtable.xml
Unexpected stringtable format inside <Text ID="STR_ACE_Common_CheckPBO_Action_WarnPerm"><German>
> fix Unexpected stringtable format

- addons/laserpointer/functions/fnc_drawLaserpoint.sqf
Same as #2998 , but for release branch.
> tweak size of laserpointer - release

- addons/markers/CfgEventHandlers.hpp
- addons/markers/InsertMarker.hpp
- addons/markers/XEH_postInit.sqf
- addons/markers/XEH_preInit.sqf
- addons/markers/functions/fnc_getEnabledChannels.sqf
- addons/markers/functions/fnc_initInsertMarker.sqf
- addons/markers/functions/fnc_mapDrawEH.sqf
- addons/markers/functions/fnc_onLBSelChangedChannel.sqf
- addons/markers/functions/fnc_onLBSelChangedColor.sqf
- addons/markers/functions/fnc_onLBSelChangedShape.sqf
- addons/markers/functions/fnc_onSliderPosChangedAngle.sqf
- addons/markers/functions/fnc_placeMarker.sqf
- addons/markers/functions/fnc_setMarkerJIP.sqf
- addons/markers/functions/fnc_setMarkerNetwork.sqf
- addons/markers/script_component.hpp
Same as  #2990 , but for release branch.
> code cleanup markers

- addons/fcs/CfgEventHandlers.hpp
- addons/fcs/CfgVehicles.hpp
- addons/fcs/XEH_postInit.sqf
- addons/fcs/XEH_preInit.sqf
- addons/fcs/functions/fnc_adjustRange.sqf
- addons/fcs/functions/fnc_canResetFCS.sqf
- addons/fcs/functions/fnc_canUseFCS.sqf
- addons/fcs/functions/fnc_canUseRangefinder.sqf
- addons/fcs/functions/fnc_firedEH.sqf
- addons/fcs/functions/fnc_getAngle.sqf
- addons/fcs/functions/fnc_handleAirBurstAmmunitionPFH.sqf
- addons/fcs/functions/fnc_keyDown.sqf
- addons/fcs/functions/fnc_keyUp.sqf
- addons/fcs/functions/fnc_onForceUpdate.sqf
- addons/fcs/functions/fnc_reset.sqf
- addons/fcs/functions/fnc_updateRangeHUD.sqf
- addons/fcs/functions/fnc_vehicleInit.sqf
- addons/fcs/initKeybinds.sqf
> code cleanup fcs

- addons/gestures/ACE_Settings.hpp
- addons/gestures/CfgVehicles.hpp
- addons/gestures/config.cpp
- addons/gestures/functions/fnc_playSignal.sqf
- addons/gestures/key.sqf
- addons/gestures/stringtable.xml
Setting to hide from interaction menu or disable competly.
Fix keyBinds for the BI* gestures.
> Setting For Gestures - Fix BI* gestures

- addons/common/functions/fnc_getName.sqf
- addons/common/functions/fnc_receiveRequest.sqf
- addons/common/functions/fnc_sanitizeString.sqf
- addons/common/functions/fnc_setName.sqf
- addons/disarming/functions/fnc_openDisarmDialog.sqf
- addons/finger/functions/fnc_incomingFinger.sqf
- addons/medical/functions/fnc_actionCheckBloodPressureLocal.sqf
- addons/medical/functions/fnc_actionCheckResponse.sqf
- addons/medical/functions/fnc_treatmentAdvanced_CPRLocal.sqf
- addons/medical/functions/fnc_treatmentAdvanced_bandage.sqf
- addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medication.sqf
- addons/medical/functions/fnc_treatmentIV.sqf
- addons/medical/functions/fnc_treatmentTourniquet.sqf
- addons/movement/XEH_postInit.sqf
- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- addons/respawn/functions/fnc_showFriendlyFireMessage.sqf
Fix #2912
The raw `&lt;` showed up in nametags and anything besides strucText
`[ / ]` is fairly close and will work in either text mode.
> Sanitize less/greater-than symbol to square

- addons/common/RscInfoType.hpp
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_getStaminaBarControl.sqf
- addons/main/script_macros.hpp
this disables the stamina bar for the whole game sitting (not just mission):
`(call ace_common_fnc_getStaminaBarControl) ctrlShow false`
> add function to retrieve the control of the stamina bar

- addons/attach/CfgVehicles.hpp
- addons/captives/CfgVehicles.hpp
- addons/explosives/CfgVehicles.hpp
- addons/gestures/CfgVehicles.hpp
- addons/hearing/CfgVehicles.hpp
- addons/interaction/CfgVehicles.hpp
- addons/medical/ACE_Medical_Actions.hpp
- addons/medical/ACE_Medical_SelfActions.hpp
- addons/overheating/CfgVehicles.hpp
- addons/parachute/CfgVehicles.hpp
This has been used in AGM and is not needed anymore. At least I wasn't able to find a place where hotkeys are being read and actively used.
Someone correct me if I'm mistaken.
> Remove obsolete hotkey entries

- addons/goggles/XEH_postInit.sqf
- addons/goggles/functions/fnc_applyDirtEffect.sqf
- addons/goggles/functions/fnc_applyDustEffect.sqf
- addons/goggles/functions/fnc_externalCamera.sqf
- addons/goggles/functions/fnc_handleExplosion.sqf
> Fix Third Person Goggle Effect Not Displaying

- addons/sitting/XEH_clientInit.sqf
- addons/sitting/functions/fnc_addSitActions.sqf
- addons/sitting/functions/fnc_getRandomAnimation.sqf
- addons/sitting/functions/fnc_sit.sqf
- addons/sitting/functions/fnc_stand.sqf
@Jonpas - Minor Cleanup of sitting module
- Add modern privates
- Don't add actions, canInteractWith condition, or EH if not enabled
> Sitting Cleanup

- optionals/compat_rhs_afrf3/CfgAmmo.hpp
- optionals/compat_rhs_afrf3/CfgMagazines.hpp
- optionals/compat_rhs_afrf3/config.cpp
- optionals/compat_rhs_usf3/CfgMagazines.hpp
Fix for the SMAW's spotting rifle causing backblast
> RHS Compat fix for SMAW spotting rifle backblast

- optionals/compat_rhs_usf3/CfgVehicles.hpp
Fix for missing turret inheritance bug introduced in #3040.
> RHS Compat. Fix M113 inheritance

- addons/dagr/stringtable.xml
- addons/explosives/stringtable.xml
- addons/gestures/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interact_menu/stringtable.xml
- addons/interaction/stringtable.xml
- addons/map/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/nightvision/stringtable.xml
- addons/rearm/stringtable.xml
- addons/refuel/stringtable.xml
- addons/tripod/stringtable.xml
- addons/viewdistance/stringtable.xml
Contains German And Portuguese Translation PRs
@licht-im-Norden87 - Rebased commits on  #3031
@ToasterBR - Fixed merge conflict for #3051
> Fix stringtables merge

- wiki/feature/advanced-ballistics.md
Close #2926 Ref @sargken
Used https://forums.bistudio.com/topic/171256-advanced-ballistics-wip/ as base.  
Converted to metric and added a few examples.
> Document AB weapon/ammo configs

- wiki/framework/events-framework.md
Somehow managed to miss that when rewriting that page and moving it to Frameworks.
> Add Target Event to Events Framework

- wiki/development/setting-up-the-development-environment.md
Learned this the hard way. I hope I got it right,
> Update the file patching documentation post A3 v1.50

- tools/config_validator.py
Simple python script to run makePbo's lint and extFile ref check on all configs
> Python tool to validate configs (using MakePbo)

- wiki/development/setting-up-the-development-environment.md
> Add the DISABLE_COMPILE_CACHE macro to documentation

- addons/gforces/XEH_postInit.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
> Code cleanup of Gforces module V2

- optionals/compat_rhs_afrf3/CfgWeapons.hpp
Add missing windage adjustment for one of the PSO-1 variants.
Ref #3171
> RHS Compat: Add PSO-1M2-1 windage adjust

- wiki/missionmaker/useful-functions.md
> Useful functions page

- addons/hearing/CfgWeapons.hpp
> Fix typo in ACE_hearing config

- AUTHORS.txt
Forgot to change the AUTHORS.txt in the last pull request
> As bux578 requested: Added myself to AUTHORS.txt

- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_actionRemoveTourniquet.sqf
- addons/medical/functions/fnc_init.sqf
- addons/medical/functions/fnc_onMedicationUsage.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medication.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medicationLocal.sqf
> Tourniquets block medication until released

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/grenades/functions/fnc_flashbangThrownFuze.sqf
- addons/grenades/functions/fnc_throwGrenade.sqf
> Flashbangs - pass pos instead of obj reference

- addons/fcs/XEH_preInit.sqf
- addons/fcs/functions/fnc_calculateSolution.sqf
- addons/fcs/functions/fnc_getRange.sqf
- addons/fcs/functions/fnc_keyDown.sqf
- addons/fcs/functions/fnc_keyUp.sqf
Another thing that started out as a relatively simple fix has spiralled out of control as I make way too many branches that inevitably start intermingling with rewrites and cleanups from here to Frankfurt.
> Cleaning up the FCS code

- addons/common/functions/fnc_getTargetDistance.sqf
Turns out it wasn't really needed after all, but better is better :p
> Rewrite ace_common_fnc_getTargetDistance to use LineIntersectsSurfaces.

- addons/cargo/XEH_postInit.sqf
- addons/cargo/functions/fnc_addCargoItem.sqf
- addons/cargo/functions/fnc_canLoadItemIn.sqf
- addons/cargo/functions/fnc_canUnloadItem.sqf
- addons/cargo/functions/fnc_initVehicle.sqf
- addons/cargo/functions/fnc_loadItem.sqf
- addons/cargo/functions/fnc_startLoadIn.sqf
- addons/cargo/functions/fnc_startUnload.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_findUnloadPosition.sqf
- addons/common/functions/fnc_unloadPerson.sqf
- addons/common/functions/fnc_unloadPersonLocal.sqf
- addons/common/stringtable.xml
- addons/medical/functions/fnc_actionUnloadUnit.sqf
Based on branch #3191
fix #2475 
fix #1908
fix #2525
Redo of PR #2593
> findUnloadPosition (Redo)

- addons/fcs/CfgVehicles.hpp
Adds FCS to the XM307 GMG.
This PR requires #3189.
> Add FCS to more things

- addons/goggles/functions/fnc_externalCamera.sqf
> Fix ACE_goggle changing the tint on the 3den camera

- addons/map/stringtable.xml
- addons/maptools/stringtable.xml
Error correction and addition to the French translations of "ace_map" and "ace_maptools"
> Fixed and added French Translation

- addons/map/stringtable.xml
As per @alganthe's comment on #3114
> Fix french translation refresh marker interval

- addons/zeus/XEH_preInit.sqf
> Remove extra PREPs in the ACE_Zeus 

- addons/common/functions/fnc_setAllGear.sqf
> Document the locality requirements of fnc_setAllGear.

- addons/common/functions/fnc_setAllGear.sqf
> setAllGear - abort function and print warning when used on remote units,

- addons/interaction/functions/fnc_canPassMagazine.sqf
Tag @BaerMitUmlaut 
Restriction so you can't pass to crew in a tank from outside.
> Don't allow passing mags when not in same veh

- addons/realisticnames/CfgVehicles.hpp
- addons/realisticnames/CfgWeapons.hpp
- addons/realisticnames/stringtable.xml
> correct name for wheeled apc 01 cannon

- meta.cpp
- tools/make.py
https://community.bistudio.com/wiki/How_to_enable_Steam_Workshop_support_in_Server_Browser
> Add steam workshop support

- README.md
- docs/README_DE.md
- docs/README_PL.md
- Update each README to reflect the changes made in #3278
> Update README to reflect #3278

- addons/common/XEH_postInit.sqf
- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_actionCheckBloodPressure.sqf
- addons/medical/functions/fnc_actionCheckPulse.sqf
- addons/medical/functions/fnc_addToInjuredCollection.sqf
- addons/medical/functions/fnc_addToLog.sqf
- addons/medical/functions/fnc_addToTriageCard.sqf
- addons/medical/functions/fnc_setDead.sqf
- addons/medical/functions/fnc_setHitPointDamage.sqf
- addons/medical/functions/fnc_setUnconscious.sqf
- addons/medical/functions/fnc_treatmentAdvanced_CPR.sqf
- addons/medical/functions/fnc_treatmentAdvanced_bandage.sqf
- addons/medical/functions/fnc_treatmentAdvanced_fullHeal.sqf
- addons/medical/functions/fnc_treatmentBasic_bandage.sqf
- addons/medical/functions/fnc_treatmentBasic_bloodbag.sqf
- addons/medical/functions/fnc_treatmentBasic_morphine.sqf
- addons/medical/functions/fnc_treatmentIV.sqf
- addons/medical/functions/fnc_treatmentTourniquet.sqf
- addons/medical/functions/fnc_useItem.sqf
> Replace execRemoteFnc in ace_medical

- addons/frag/stringtable.xml
> frag PL translation

- addons/medical/stringtable.xml
> medical PL translation

- addons/medical/functions/fnc_displayPatientInformation.sqf
- addons/medical_menu/functions/fnc_updateUIInfo.sqf
This fixes not round number of wounds, see image below (1.7x wound). This happens when you use wrong type of bandage on wound. Thing below that is just my experiment that failed, sadly.
> ceil number of wounds

- wiki/feature/mk6mortar.md
- wiki/missionmaker/class-names.md
- wiki/missionmaker/modules.md
Doc update for new features implemented in #3043.
> Mk6 documentation update

- addons/refuel/XEH_postInit.sqf
- addons/refuel/XEH_preInit.sqf
- addons/refuel/functions/fnc_connectNozzleAction.sqf
- addons/refuel/functions/fnc_handleDisconnect.sqf
- addons/refuel/functions/fnc_resetLocal.sqf
- addons/refuel/functions/fnc_returnNozzle.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
Adding HandleDisconnect EH
Detecting deletion of fuel truck by zeus
Fixes #3327
> Handling disconnect and removal of fuel truck

- addons/medical/XEH_postInit.sqf
- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_actionPlaceInBodyBag.sqf
- addons/medical/functions/fnc_actionRemoveTourniquet.sqf
- addons/medical/functions/fnc_serverRemoveBody.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medication.sqf
Fix #1301 
Alternate fix instead of PR #3316
Much simpler, just moves the body out of the way, then deletes after player has re-spawned.
> Fix bagging respawning players (alt)

- addons/advanced_ballistics/XEH_postInit.sqf
- addons/cargo/CfgVehicles.hpp
- addons/gestures/CfgVehicles.hpp
- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_addToTriageCard.sqf
- addons/missileguidance/functions/fnc_seekerType_Optic.sqf
- addons/repair/functions/fnc_setDamage.sqf
- addons/zeus/CfgVehicles.hpp
Yay for `search_undefinedFunctions.py`
missileguidance-checkSeekerLos should probably be checkLos, but that will need some more testing
> Fix some undefined functions / strings

- addons/medical/stringtable.xml
1. Fix the medical translations
> Properly fix the medical translation file

- addons/captives/CfgEden.hpp
- addons/captives/config.cpp
1. Add captivity options to units in 3DEN:
This require some stringtabling still
WIP
---
> integrate captivity modules with 3DEN

- addons/cargo/stringtable.xml
- addons/common/stringtable.xml
- addons/explosives/stringtable.xml
- addons/finger/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interaction/stringtable.xml
- addons/overheating/stringtable.xml
- addons/switchunits/stringtable.xml
- addons/viewdistance/stringtable.xml
Since my other PR was merged I have to open another one to add a few things a fix one or two mistakes. It should be done in <30 minutes. (<--- Nope not anymore)
(Guess you guys want to release 3.5.0 as soon as possible.)
Is this a valid comment inside a code? 
> "< German>blabla< /German> //please check!"    (meaning "  //comment  " like c++)
Addon:
finger:
Iam not happy with my translation in any way. 
"Zeige Zeiger" sounds terrible
"Zeige Fingerzeig (middlefinger)" can be misunderstood 
(maybe there is a nice solution Iam not aware of.) This is truely a pain in the ass
Maybe @KoffeinFlummi , @commy2  (or who else is a native german) can help me out.
> Update German Stringtable

- addons/interact_menu/XEH_displayLoad.sqf
> fix error when loading save game, fix #3391

- addons/mk6mortar/stringtable.xml
Somehow Github fucked the whole thing up and i was not able to merge this into my other PR.
> German translation Update: MK6 Mortar

- addons/rearm/XEH_PREP.hpp
- addons/rearm/functions/fnc_disable.sqf
There has been a hidden way to disable rearm for a vehicle. Now there is an official API fnc.
> Rearm added API

- addons/refuel/functions/fnc_connectNozzleAction.sqf
- addons/refuel/functions/fnc_makeJerryCan.sqf
- addons/refuel/functions/fnc_reset.sqf
> Refuel change documentation header for API fnc

- addons/medical/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/nightvision/stringtable.xml
- addons/overheating/stringtable.xml
- addons/rearm/stringtable.xml
- addons/refuel/stringtable.xml
- addons/repair/stringtable.xml
- addons/respawn/stringtable.xml
- addons/switchunits/stringtable.xml
- addons/tacticalladder/stringtable.xml
- addons/tagging/stringtable.xml
- addons/trenches/stringtable.xml
- addons/viewdistance/stringtable.xml
- addons/zeus/stringtable.xml
1. Add remaining spanish translations
> Remaining Spanish translations

- addons/medical/ACE_Settings.hpp
> Add missing medical category to delayUnconCaptive

- addons/hearing/stringtable.xml
- addons/medical/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/overheating/stringtable.xml
- addons/tagging/stringtable.xml
1. *Add all missing PL translations*
2. *Change MK6 to Mk6 in stringtable*
3. Make some preliminary work with unwinding pl translations `Ogr.` -> `Ograniczenie` etc. (more space for names in 3DEN)
---
> Polish translation 3.5.0 (FIXED)

- addons/mk6mortar/CfgEventHandlers.hpp
- addons/mk6mortar/XEH_postInit.sqf
- addons/mk6mortar/functions/fnc_turretDisplayLoaded.sqf
> Fix Mortar Display

- addons/headless/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/sitting/stringtable.xml
- addons/tagging/stringtable.xml
- addons/tripod/stringtable.xml
1. *Add missing spanish translations*
---
> Spanish Translation (3.5.0)

- addons/captives/stringtable.xml
- addons/common/stringtable.xml
translated lines in french from "/captives/stringtable.xml"
> Translation Fr Captives

- addons/medical/stringtable.xml
- addons/refuel/stringtable.xml
- addons/switchunits/stringtable.xml
Habe gerade Arma gestartet und dabei ist mir das ein oder andere Problem aufgefallen.
> German translation

- addons/advanced_ballistics/stringtable.xml
- addons/aircraft/stringtable.xml
- addons/captives/stringtable.xml
- addons/cargo/stringtable.xml
- addons/common/stringtable.xml
- addons/concertina_wire/stringtable.xml
- addons/dagr/stringtable.xml
- addons/dragging/stringtable.xml
- addons/explosives/stringtable.xml
- addons/finger/stringtable.xml
- addons/flashlights/stringtable.xml
- addons/gestures/stringtable.xml
- addons/headless/stringtable.xml
- addons/hearing/stringtable.xml
- addons/medical/stringtable.xml
Add missing french translations and fixing existing texts in "Advanced_Ballistics, Aircraft, Captive, Cargo, Concertina_wire, DAGR, Dragging, Explosives, Finger, Flashlights, Gestures, Headless, Hearing, Medical" addons.
> Traduction fr

- addons/explosives/stringtable.xml
- addons/frag/stringtable.xml
- addons/interaction/stringtable.xml
- addons/map_gestures/stringtable.xml
- addons/medical/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/overheating/stringtable.xml
- addons/repair/stringtable.xml
- addons/slideshow/stringtable.xml
- addons/zeus/stringtable.xml
1. Re-PR #3423 with fixed merge conflicts
> German translations by @System98

- addons/refuel/functions/fnc_canConnectNozzle.sqf
- addons/refuel/functions/fnc_connectNozzleAction.sqf
- addons/refuel/functions/fnc_getFuel.sqf
- addons/refuel/functions/fnc_readFuelCounter.sqf
- addons/refuel/functions/fnc_refuel.sqf
- addons/refuel/functions/fnc_reset.sqf
- addons/refuel/functions/fnc_returnNozzle.sqf
- addons/refuel/functions/fnc_setFuel.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
- addons/refuel/script_component.hpp
Some minor improvements to refuel
Documentation for other modders/creators on how to enable refuel will be in a different PR
> Refuel improvements

- addons/medical/ACE_Settings.hpp
- addons/medical/stringtable.xml
> Make unused medical strings be used

- addons/optionsmenu/functions/fnc_onCategorySelectChanged.sqf
- addons/optionsmenu/functions/fnc_onSettingsMenuOpen.sqf
Hide categories that have no user settable options
#3447
> Hide categories that have no user settable options

- addons/medical/stringtable.xml
> Remove duplicate medical string

- addons/tagging/script_component.hpp
> Disable logging in tagging

- extras/blank/CfgEventHandlers.hpp
- extras/blank/XEH_PREP.hpp
- extras/blank/script_component.hpp
1. Add "newly" used defines to blank as well
```
// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define CBA_DEBUG_SYNCHRONOUS
// #define ENABLE_PERFORMANCE_COUNTERS
```
> Add defines to blank component

- addons/repair/CfgEventHandlers.hpp
> Don't try adding repair actions to fastrope helper

- wiki/development/ace3-config-entries.md
- wiki/feature/fastroping.md
- wiki/framework/fastroping-framework.md
> Fast roping documentation

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Make this thing nicer
- Improve the other 2 things
- Remove the HTML markup from CONTRIBUTING.md
- Get rid of italic text because people never remove it and I always have to twist my head to read it
- Make it more direct (I guess)
> Improve GitHub files

- .github/ISSUE_TEMPLATE.md
- Require specifying the CBA version in issues.
> Require specifying the CBA version in issues.

- addons/fastroping/stringtable.xml
Added Spanish Translations, some of these can have multiple translations but according to the context, they match properly their meanings.
> Added Spanish Translation to fastroping module

- AUTHORS.txt
> Added FFAAMOD to AUTHORS.txt

- addons/fastroping/CfgVehicles.hpp
- Make the FRIES inherit from Helicopter_Base_F
- Fix #3504
I've tested it and received no UBC errors. Helicopters follow waypoints properly.
Anyway, I don't ever trust my config work, so some review would be welcome.
EDIT: tested fastroping a few times using this FRIES and it work fine, although a couple of times my unit fell the last couple of meters. I don't think it's related though.
> Make the FRIES inherit from Helicopter_Base_F. Fix #3504

- addons/mk6mortar/CfgVehicles.hpp
Fixes #3491 (Don't know why the commit message says 3490)
> Replace transportMax... with maximumLoad for mortar boxes.

- wiki/development/ace3-config-entries.md
- wiki/feature/rearm.md
- wiki/feature/refuel.md
- wiki/framework/rearm-framework.md
- wiki/framework/refuel-framework.md
- wiki/missionmaker/modules.md
> Add rearm and refuel documentation

- addons/smallarms/CfgWeapons.hpp
- removes an old fix about unrealistic pistol / smg magazines
- fixes problems with certain new(ish) tracer mags being incompatible with some pistols and smg
> remove obsolete fix, fix #3545

- addons/common/functions/fnc_addActionEventHandler.sqf
- addons/common/functions/fnc_addActionMenuEventHandler.sqf
- execute addActionEvents in unscheduled env
- all my tears
> execute addActionEvents in unscheduled env

- addons/fastroping/CfgMoves.hpp
- addons/fastroping/CfgVehicles.hpp
1. Add a bunch of QUOTE macros to the fastroping configs where they were not used yet.
> Added QUOTE macros to fastroping configs

- wiki/development/setting-up-the-development-environment.md
- Correct mention of `diag_mergeConfigFile` in the documentation.
- Replace and close #2370
> Correct documentation regarding diag_mergeConfigFile

- addons/mk6mortar/XEH_postInit.sqf
- addons/mk6mortar/functions/fnc_handlePlayerVehicleChanged.sqf
- addons/mk6mortar/functions/fnc_mortarInit.sqf
- Change mortarInit into global event with turret locality check to be sure that mortar init is executed on machine that owns turret.
- Fix for https://github.com/acemod/ACE3/issues/3557
- Tested on dedicated multiplayer
> Fix mortar ammo handling init on dedicated

- _includes/_footer.html
- wiki/user/how-to-make-a-feature-request.md
- Update the feature request URL's
> update new feature request urls

- addons/mk6mortar/functions/fnc_mortarInit.sqf
- Remove needless tolower from mortarinit
- Suggested by @commy2 in https://github.com/acemod/ACE3/pull/3584#discussion_r56408786
> Remove needless tolower from mortarinit

- addons/fastroping/CfgVehicles.hpp
- fix all helicopter actions missing
- ... ?
> don't overwrite helicopter sub class self actions

- addons/medical/ACE_Settings.hpp
- Fix double displayName in medical settings after https://github.com/acemod/ACE3/pull/3568
> Fix double displayName in medical settings

- wiki/feature/medical-system.md
- Fix an extra HTML tag on line 256 on the wiki.-
> Fix extra HTML tag

- wiki/feature/medical-system.md
- Fixes misaligned lists in sections 2.2.2.2 and 2.2.2.3
> Fix for misaligned list

- wiki/feature/medical-system.md
Fixes linebreaks messing with lists from previous 2 PRs.
> Linebreak fix

- addons/advanced_ballistics/XEH_postInit.sqf
- addons/main/CfgDependencies.hpp
- addons/main/CfgSettings.hpp
- addons/main/config.cpp
- Add warnings for missing compat PBOs
Replace #3569
> Compat pbo warnings

- addons/cargo/CfgVehicles.hpp
- add fitting cargo capacities to all helicopters
- fix #3591
- should've made this ages ago
> specify helicopter cargo spaces

- addons/tagging/functions/fnc_tagTestingThread.sqf
> fix script error in tagging

- addons/maptools/functions/fnc_openMapGpsUpdate.sqf
- Account for map altitude in GPS display
- Fixes #3650
> Add map altitude to GPS

- addons/cargo/CfgEventHandlers.hpp
- addons/cargo/CfgVehicles.hpp
- addons/dragging/CfgVehicles.hpp
- add carrying and dragging for smal-, medium- and large- plastic & metal cases.
- add cargo load for smal-, medium- and large- plastic & metal cases.
> Carry, drag and load metal and plastic cases

- wiki/framework/interactionMenu-framework.md
- Close #3673 - Adds documentation for interaction menu
> Wiki for Interaction Menu Framework

- addons/common/XEH_postInit.sqf
- addons/repair/ACE_Settings.hpp
- addons/repair/functions/fnc_canRepair.sqf
- addons/repair/functions/fnc_repair.sqf
- addons/repair/stringtable.xml
- Show repair action, but exit and show warning when selected
- Optional (default off) setting to auto shut off engine to keep
Close #3348
> Clarify repair while engine is running

- addons/cargo/CfgEventHandlers.hpp
- addons/cargo/functions/fnc_initVehicle.sqf
- Lower the amount of XEH classes in CfgEventHandlers
- Move `hasCargo` check to top of function.
> Improve cargo initialization XEH

- addons/medical/functions/fnc_setCardiacArrest.sqf
- Fix redundant privates in setCardiacArrest
> Fixed redundant privates in setCardiacArrest

- addons/advanced_ballistics/functions/fnc_handleFired.sqf
- addons/dagr/functions/fnc_menuInit.sqf
- addons/vector/CfgWeapons.hpp
- addons/vector/config.cpp
- addons/vector/functions/fnc_onKeyHold.sqf
- addons/vector/initKeybinds.sqf
- addons/vector/stringtable.xml
- Add day (non night vision) version of the vector 21
- Add "Nite" to the name of the current NV capable vector
Ref http://www.vectronix.us/handhelds/vector-family-all-1
> Add day (non night vision) version of the vector 21

- addons/gestures/CfgVehicles.hpp
- addons/gestures/XEH_postInit.sqf
- From #3635 - FUNC(playSignal) needs "BIgesture" prefix on all BI gestures
- Interaction conditions are checked on parent, don't need on every
child
> Fix BIS gesture keybinds

- addons/common/functions/fnc_findUnloadPosition.sqf
- Handle unloading on terrain slopes - Close #3667
> Better handle unloading on slopes

- wiki/framework/overheating-framework.md
- Update the overheating documentation for the new* config changes.
* new: at least 3 months old.
> Update ovearheating documentation

- addons/recoil/CfgMoves.hpp
> fix wrong macro names

- addons/cargo/stringtable.xml
- addons/common/stringtable.xml
- addons/explosives/stringtable.xml
- addons/fastroping/stringtable.xml
- addons/gforces/stringtable.xml
- addons/interaction/stringtable.xml
- addons/medical/stringtable.xml
- addons/medical_menu/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/overheating/stringtable.xml
- addons/repair/stringtable.xml
- addons/spectator/stringtable.xml
- addons/tagging/stringtable.xml
- addons/trenches/stringtable.xml
- addons/ui/stringtable.xml
> Czech translation - Update

- addons/movement/XEH_PREP.hpp
- addons/movement/XEH_postInit.sqf
- addons/movement/functions/fnc_addLoadToUnitContainer.sqf
- addons/movement/functions/fnc_handleVirtualMass.sqf
- title
- for https://github.com/acemod/ACE3/pull/3749
> add framework to add virtual mass to containers

- addons/missionmodules/config.cpp
- addons/nametags/functions/fnc_getVehicleData.sqf
- addons/optionsmenu/gui/define.hpp
- Remove old occurances of AGM and CSE which are either outdated or unused.
> Removed old occurances of AGM and CSE

- addons/overheating/ACE_Settings.hpp
- addons/overheating/CfgEventHandlers.hpp
- addons/overheating/CfgVehicles.hpp
- addons/overheating/XEH_postInit.sqf
- addons/overheating/functions/fnc_swapBarrelCallback.sqf
- addons/overheating/functions/fnc_updateSpareBarrelsTemperaturesThread.sqf
- addons/overheating/stringtable.xml
- Add Master Enabled Setting for the overheating module
Replace PR #3725 
This will be merged into pr #3438
> Overheating - Add Master Enabled Setting (barrelPR)

- addons/tacticalladder/data/model.cfg
- Close #3745
- Update the model.cfg for armaMan with one from Arma 3 Samples Pack.
> Tactical Ladder - Update model cfg

- addons/common/functions/fnc_setHearingCapability.sqf
- addons/rearm/functions/fnc_makeDummy.sqf
- Remove the remaining usage of `player` instead of `ACE_player`.
> Remove remaining usage of player

- addons/fastroping/functions/fnc_fastRope.sqf
- addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- Fix getting stuck on rope whilst fastroping
- Fix the twitching issues that appeared again with 3.5.1
> Fix getting stuck on rope whilst fastroping

- addons/common/CfgEventHandlers.hpp
- addons/common/XEH_PREP.hpp
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_handleEngine.sqf
- addons/refuel/functions/fnc_reset.sqf
- addons/refuel/functions/fnc_returnNozzle.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
- Add a status effect for blocking the engine of a vehicle without setting hitpoint damage.
- Use this new status effect in ACE_Refuel.
> Add blockEngine status effect

- addons/minedetector/CfgVehicles.hpp
- addons/minedetector/XEH_clientInit.sqf
- addons/minedetector/functions/fnc_canDeactivateDetector.sqf
- addons/minedetector/functions/fnc_detectorLoop.sqf
- addons/minedetector/functions/fnc_getDetectedObject.sqf
- addons/minedetector/functions/fnc_playDetectorSound.sqf
- addons/minedetector/stringtable.xml
For PR #3755
Stringtables, minor cleanup and when debug is one will show the 3d position of the detection point.
It looks fairly close, but we might be able to tweak it a little closer.
> Stringtables, Add Detector Pos Deubg

- addons/zeus/ACE_Settings.hpp
- addons/zeus/CfgVehicles.hpp
- addons/zeus/functions/fnc_addObjectToCurator.sqf
- addons/zeus/functions/fnc_moduleZeusSettings.sqf
Original PR: #2451
- Add module setting (original PR)
- Add read module setting from module function
- Add run at settings initialized for addObjectToZeus
> Add zeus objects setting

- addons/common/functions/fnc_getMGRSdata.sqf
fnc_getMGRSdata.sqf update3 : 
- rechecked all "worldname" 
- minor fixes 
- add new maps
> fnc_getMGRSdata.sqf update3

- addons/medical/CfgWeapons.hpp
- Adjust the weight of the bodybags to ~330g ([reference](https://l3.cdnwm.com/ip/celulosas-vascas-leichensack-mit-reissverschluss-leichensack-365713.pdf))
> Adjusted weight of bodybag

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_assignedItemFix.sqf
- addons/common/functions/fnc_getAllGear.sqf
- addons/common/functions/fnc_setAllGear.sqf
- addons/goggles/XEH_postInit.sqf
- addons/medical/XEH_postInit.sqf
- addons/nightvision/XEH_postInitClient.sqf
- addons/parachute/XEH_postInit.sqf
- addons/respawn/functions/fnc_handleKilled.sqf
- addons/respawn/functions/fnc_handleRespawn.sqf
- addons/respawn/functions/fnc_restoreGear.sqf
- addons/scopes/XEH_postInit.sqf
- title
- massive performance improvement every frame
```
B_Soldier_F
getUnitLoadout player
0.0251 ms
10000/10000
player call ACE_common_fnc_getAllGear
0.535412 ms
1892/10000
```
> use 'getUnitLoadout' instead of 'FUNC(getAllGear)' and deprecate it

- optionals/compat_rhs_afrf3/CfgAmmo.hpp
- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/CfgAmmo.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
> Fix UBC errors for RHS 4.1

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_setHearingCapability.sqf
- addons/hearing/CfgEventHandlers.hpp
- addons/hearing/XEH_postInit.sqf
- addons/hearing/functions/fnc_explosionNear.sqf
- addons/hearing/functions/fnc_firedNear.sqf
- addons/hearing/functions/fnc_updateVolume.sqf
- addons/medical/XEH_postInit.sqf
- CBA/addClassEventHandlers optimization
- Fix ear-ringing playing for units in spectator
- Medical now uses hearing's `unconsciousnessVolume` if it exists
> Hearing - New XEH, Fix dead effects, Medical var

- addons/respawn/functions/fnc_teleportToRallypoint.sqf
> replace a comma with semi colon

- addons/respawn/functions/fnc_initRallypoint.sqf
- fixes image below
- no idea why it happens though. must be some unknown bug in Arma. Couldn't find reason for it
> fix rallypoint being objNull, when created via 'createvehicle'

- addons/common/functions/fnc_getConfigType.sqf
- addons/common/functions/fnc_getConfigTypeObject.sqf
- addons/common/functions/fnc_getItemType.sqf
> Use new CBA get config functions and deprecate ACE functions 

- addons/common/functions/fnc_unloadPerson.sqf
- addons/common/functions/fnc_unloadPersonLocal.sqf
- addons/explosives/CfgModule.hpp
- addons/fastroping/CfgVehicles.hpp
- addons/frag/functions/fnc_spallTrack.sqf
- addons/hitreactions/functions/fnc_fallDown.sqf
- addons/main/script_macros.hpp
- addons/medical/CfgVehicles.hpp
- addons/missionmodules/CfgVehicles.hpp
- addons/nightvision/CfgVehicles.hpp
- addons/repair/functions/fnc_useItem.sqf
- **Requires CBA >2.3.1**
- Use new CBA's `QFUNC()` and `QEFUNC()` instead of `QUOTE(FUNC())` and `QUOTE(EFUNC())` - Moved to CBA in https://github.com/CBATeam/CBA_A3/pull/307
> Use new quoted function macros

- addons/cargo/CfgVehicles.hpp
- addons/dragging/CfgVehicles.hpp
- addons/interaction/CfgVehicles.hpp
- addons/rearm/CfgVehicles.hpp
- addons/refuel/CfgVehicles.hpp
> Fix 1.60 UBC (slingloads)

- addons/main/script_mod.hpp
- addons/medical_menu/config.cpp
- Title
@commy2 merging is too quick.
> Fix WEB_URL end of line error

- addons/huntir/XEH_postInit.sqf
- addons/huntir/functions/fnc_handleFired.sqf
- Create only one HuntIR when fired (previously, there was one created for every connected player)
> Fixed HuntIR deployment

- addons/minedetector/CfgWeapons.hpp
Removed Valon from any vest properly configured to use a holster
> Don't show mine detector in holster

- addons/common/XEH_preInit.sqf
- addons/main/script_mod.hpp
- addons/optionsmenu/functions/fnc_debugDumpToClipboard.sqf
- Minor Cleanup from transistion to CBA's waitAndExec
> Cleanup transistion to CBA's waitAndExec

- addons/medical/CfgEden.hpp
- addons/repair/CfgEden.hpp
- Update 3den attributes to use 1.60 scaling
> Update 3den attributes to use 1.60 scaling

- addons/tacticalladder/CfgVehicles.hpp
- addons/tripod/CfgVehicles.hpp
- Move all deployables to equipment submenu
> Unify deployables

- addons/common/functions/fnc_goKneeling.sqf
- Would cause magazine repack to set you to crouched animation even inside vehicles.
> Fix goKneeling changing animation inside vehicle (1.60)

- addons/nightvision/functions/fnc_blending.sqf
> Fix NVG overbright when player throws grenades

- addons/movement/CfgInventoryGlobalVariable.hpp
- addons/movement/XEH_postInit.sqf
- addons/movement/config.cpp
- addons/movement/functions/fnc_canClimb.sqf
- Remove unused `CfgInventoryGlobalVariable`
- Make debug lines persist longer (5s)
Contains cleanup parts form #3847
> Cleanup movement and improve debugging

- addons/ui/XEH_clientInit.sqf
- addons/ui/functions/fnc_setAdvancedElement.sqf
- Follow up of #3872
- Title
- Fix config name check
I think I finally fixed all the bugs with this...
> Fix selective UI in FFV slots

- addons/nightvision/functions/fnc_blending.sqf
- cont. from #3873
- also fix this bug for mines and satchel charges ("Put")
- private
> code cleanup fnc_blending

- addons/explosives/CfgVehicles.hpp
- Title
- There are no other actions apart from "Defuse" once the mine is set and it's quite stupid that you need to expand the menu
- Remove redundant entries
- Stringtable author
> Move Defuse action to main action

- addons/weather/XEH_postInit.sqf
- addons/weather/stringtable.xml
- "Show Wind Info" and "Show Wind Info (Toggle)" were inverted
> Fix wind info keybind string

- addons/medical/ACE_Medical_Treatments.hpp
Changes the bandage configuration to match the following:
- Field dressing has average treatment
- Packing bandage has average treatment, higher reopen change, longer reopening delay
- Elastic bandage has higher treatment, higher reopen change, shorter reopen delay
- QuikClot has lower treatment, lower reopen change, longer reopening delay
Fixes #3732
> Adjust bandage configuration

- addons/gunbag/CfgVehicles.hpp
@ir0n1e 
Without this you can put a gun into any backpack on a target
> Only do gunbag things when target has a gunbag

- addons/finger/XEH_postInit.sqf
> Always add finger keybind so it is changeable

- addons/minedetector/CfgAmmo.hpp
- addons/minedetector/CfgVehicles.hpp
- addons/minedetector/XEH_clientInit.sqf
- addons/minedetector/XEH_preInit.sqf
- addons/minedetector/config.cpp
- addons/minedetector/functions/fnc_detectorLoop.sqf
- addons/minedetector/functions/fnc_disableDetector.sqf
- addons/minedetector/functions/fnc_enableDetector.sqf
- addons/minedetector/functions/fnc_getDetectedObject.sqf
- addons/minedetector/functions/fnc_isDetectorEnabled.sqf
- addons/minedetector/functions/fnc_playDetectorSound.sqf
- Adding CfgAmmo config for fused explosives
- Fix broken nearestObject filter
> fix mine detector not picking up fused explosives

- addons/rearm/XEH_postInit.sqf
- addons/rearm/functions/fnc_pickUpAmmo.sqf
- addons/rearm/functions/fnc_rearmEntireVehicleSuccess.sqf
- addons/rearm/functions/fnc_rearmSuccess.sqf
- Title
- Cherry-picked from #3431
> Replace execRemoteFnc with CBA events in rearm

- addons/medical/ACE_Medical_Treatments.hpp
> Fix strange animation played when using PAK

- addons/sitting/functions/fnc_canSit.sqf
- addons/sitting/functions/fnc_sit.sqf
- addons/sitting/functions/fnc_stand.sqf
- Use claim system to prevent carrying when someone is sitting
- Change module scope back to 2 until ACEX is released
> Fix ability to carry a chair someone is sitting on

- optionals/compat_rhs_usf3/CfgGlasses.hpp
- optionals/compat_rhs_usf3/config.cpp
- It will fix the Issues with RHS Ballistic Glasses using the combat goggles overlay.
> RHS Ballistic Glasses Tint - Fix

- addons/minedetector/CfgVehicles.hpp
> fix mine ubc

- wiki/development/arma-3-scheduler-and-our-practices.md
- Rewrite a large part of the "Arma 3 Scheduler And Our Practices" explanations
- Add `waitAndExecute` and `waitUntilAndExecute` mentions and examples
- Remove the severely outdated mention of delayed execution by PFH
- Unify the blank line formatting (two blank lines before each heading, one blank line below each heading that's followed by another heading)
> Overhaul of ACE3 scheduler practices

- optionals/compat_r3f/config.cpp
Add correct requiredAddons entries since the last @R3F_ARMES update
> Update compat_r3f config.cpp

- addons/goggles/functions/fnc_applyDirtEffect.sqf
- addons/goggles/functions/fnc_applyDustEffect.sqf
> Make dirt/dust effects less bright at night

- addons/medical/functions/fnc_showBloodEffect.sqf
> Switch EFUNC(common,waitAndExecute) to CBA

- addons/medical/ACE_Medical_Treatments.hpp
- Fix some medical bandage configuration mistakes
> Fix incorrect values for bandage configuration

- addons/javelin/CfgWeapons.hpp
- addons/missileguidance/functions/fnc_onFired.sqf
> Add javelin configs for new apex launchers

- addons/ballistics/CfgWeapons.hpp
- addons/huntir/CfgWeapons.hpp
Fix
```
Warning Message: Error: creating weapon Single with scope=private
Warning Message: Error: creating weapon FullAuto with scope=private
Warning Message: Error: creating weapon GL_3GL_F with scope=private
```
These don't really have anything to do with changes in apex; They've been wrong the whole time and apex is just now throwing an error at game start.
> Fix ballisitics and huntir configs

- addons/explosives/CfgVehicles.hpp
- addons/smallarms/CfgWeapons.hpp
- Fix UBC errors for 1.62 Apex
> Fix UBC for 1.62 Apex

- addons/javelin/functions/fnc_cycleFireMode.sqf
- addons/javelin/functions/fnc_onOpticDraw.sqf
- addons/javelin/functions/fnc_onOpticLoad.sqf
- addons/javelin/functions/fnc_showFireMode.sqf
Dir/Top selector didn't work on static titans as it was storing variable on player instead of staticWeapon.
> Fix no attack profile on static titan launcher

- addons/refuel/CfgVehicles.hpp
- addons/refuel/XEH_postInit.sqf
- Move connect to main actions as it was the only one in the tree.
- Tweak fuel nozzle interaction pos
- Fix Van_01 config
- Added debuger code to find vehicles with transportFuel
Tag @GitHawk
> Refuel - Simplify Actions, Fix Van_01 config

- addons/realisticnames/CfgVehicles.hpp
- addons/realisticnames/CfgWeapons.hpp
- addons/realisticnames/stringtable.xml
- Add realistic names for APEX content
Note:
Both LSVs seem to look very similar to existing vehicles (namely the [Polaris Defense DAGOR](http://soldiersystems.net/blog1/wp-content/uploads/2014/10/WDP_8727-Front-Three-Quarters-mid-hight_Wht.jpg) and the [LSV Mk.II](http://www2.tnp.sg/sites/default/files/styles/medium/public/01c9c2cb.jpg?itok=dRpONFAw)), but they're not quite the same so they keep their original name.
*I would like some feedback on the translation of "Green Hex".*
> Realistic names for APEX content

- addons/main/stringtable.xml
- Title
- 1.62 adds support for Korean and Japanese
> Add Korean and Japanese strings to tracker

- version.html
> Simplify version.html for apex changes

- addons/common/XEH_PREP.hpp
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_actionKeysNamesConverted.sqf
- addons/common/functions/fnc_doGesture.sqf
- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_startDrag.sqf
- addons/explosives/functions/fnc_placeExplosive.sqf
- addons/explosives/functions/fnc_setupExplosive.sqf
- addons/explosives/functions/fnc_startDefuse.sqf
- addons/finger/functions/fnc_keyPress.sqf
- addons/gestures/CfgVehicles.hpp
- addons/gestures/functions/fnc_playSignal.sqf
- addons/goggles/functions/fnc_clearGlasses.sqf
- addons/interaction/functions/fnc_getDown.sqf
- addons/interaction/functions/fnc_passMagazine.sqf
- addons/interaction/functions/fnc_sendAway.sqf
- addons/interaction/functions/fnc_tapShoulder.sqf
- addons/overheating/XEH_postInit.sqf
- addons/overheating/functions/fnc_checkTemperature.sqf
- addons/overheating/functions/fnc_clearJam.sqf
- addons/overheating/functions/fnc_swapBarrel.sqf
- addons/overheating/functions/fnc_swapBarrelCallback.sqf
- addons/parachute/functions/fnc_doLanding.sqf
- addons/reload/XEH_postInit.sqf
- addons/reload/functions/fnc_checkAmmo.sqf
- addons/reload/functions/fnc_startLinkingBelt.sqf
- addons/sandbag/functions/fnc_deployConfirm.sqf
- addons/sandbag/functions/fnc_pickup.sqf
- addons/tagging/functions/fnc_tag.sqf
- creates `doGesture` so we can apply the reload mutex to every gesture
- removes the `canInteractWith` condition for `!isReloading`
> use a function to do gestures

- addons/medical/CfgEden.hpp
- addons/repair/CfgEden.hpp
> Fix 3den attribute layout for 1.62, target release

- addons/interact_menu/functions/fnc_renderBaseMenu.sqf
- addons/medical/functions/fnc_canTreatCached.sqf
Noticed big arrays:
```
ace_common_clearcache_interactmenuclosed - ARRAY SIZE: 67
ace_common_clearcache_clearconditioncaches - ARRAY SIZE: 863
```
> Fix cached call events

- wiki/development/coding-guidelines.md
- Fix typos and code brackets in coding guidelines
> Fix typos and code brackets in coding guidelines

- addons/frag/functions/fnc_pfhRound.sqf
shotbullet, shotShell don't seem to explode when touching water, so
don't create frags
Fix #4134
> Don't frag for some shells that end in water

- wiki/framework/cargo-framework.md
- Title - there were 2 titles in a row numbered `2.`
> Fix Cargo Framework title numbering

- addons/common/functions/fnc_insertionSort.sqf
- Deprecate FUNC(insertionSort) in favor of SQF sort.
> deprecate sort function

- .github/ISSUE_TEMPLATE.md
- Title.
- CBA will have 3.x.x releases from now on.
> Bump CBA's version in Issue Template

- addons/frag/XEH_postInit.sqf
- addons/frag/functions/fnc_addPfhRound.sqf
- addons/scopes/functions/fnc_firedEH.sqf
- addons/scopes/functions/fnc_inventoryCheck.sqf
- addons/winddeflection/functions/fnc_handleFired.sqf
Mostly trivial stuff
`_doFragTrack` should always be false for non-local players, so need to add listener
> Minor cleanup of fired EH listeners

- optionals/compat_rhs_usf3/CfgWeapons.hpp
> Add missing semi-colon

- addons/laser/XEH_pre_init.sqf
- addons/laser/functions/fnc_drawVisibleLaserTargets.sqf
- addons/laser/functions/fnc_handleLaserOff.sqf
- addons/laser/functions/fnc_handleLaserOn.sqf
- addons/laser/functions/fnc_seekerFindLaserSpot.sqf
> Convert laser to CBA hashes

- addons/map_gestures/functions/fnc_drawMapGestures.sqf
- addons/map_gestures/functions/fnc_moduleGroupSettings.sqf
> Convert map-gestures to CBA hashes

- addons/finger/XEH_postInit.sqf
- addons/finger/functions/fnc_incomingFinger.sqf
- addons/finger/functions/fnc_perFrameEH.sqf
> Convert finger to CBA hashes

- wiki/framework/dragging-framework.md
From issue #4141
- remove notes about setMass
- add notes about weight limit variables
> Update dragging framework wiki

- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- close #4189
Someone with RHS please test inheritance
> RHS ZSU-23-4 compat with FCS

- addons/explosives/CfgVehicles.hpp
- addons/explosives/functions/fnc_interactEH.sqf
Fix #4144
- Adds a 2nd defuse helper with increased range
> Increase defuse range for underwater mines

- addons/repair/CfgEventHandlers.hpp
- addons/repair/XEH_postInit.sqf
- addons/repair/functions/fnc_addSpareParts.sqf
- Fix #4200 (add delay for units created via zeus)
- Use ace_settingsInitialized to add events
> Fix repair cargo not added to zeus created objects

- addons/common/functions/fnc_stringRemoveWhiteSpace.sqf
> Improve stringRemoveWhitespace function header

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc__handleRequestAllSyncedEvents.sqf
- addons/common/functions/fnc__handleRequestSyncedEvent.sqf
- addons/common/functions/fnc__handleSyncedEvent.sqf
- addons/common/functions/fnc_addSyncedEventHandler.sqf
- addons/common/functions/fnc_removeSyncedEventHandler.sqf
- addons/common/functions/fnc_showHud.sqf
- addons/common/functions/fnc_syncedEvent.sqf
- addons/common/functions/fnc_syncedEventPFH.sqf
> Convert common to CBA hashes

- addons/gunbag/functions/fnc_calculateMass.sqf
> Fix wrong config path in FUNC(calculateMass)

- addons/fcs/ACE_UI.hpp
- addons/fcs/CfgVehicles.hpp
> Fix missing zeroing UI on vehicles without FCS

- addons/cargo/CfgVehicles.hpp
- addons/dragging/CfgVehicles.hpp
- Added Cargo and cargo inventory to`Land_WoodenBox_F`
- Added Cargo and cargo inventory to `Land_WoodenCrate_01_F`
- Added Dragging to  `Land_WoodenBox_F`
- Added Dragging to  `Land_WoodenCrate_01_F`
> Added additional cargo and dragging for crates

- addons/cookoff/ACE_Settings.hpp
- addons/cookoff/XEH_postInit.sqf
- Changes `ace_cookoff_enableCookoff` to `ace_cookoff_enable`
> rename cookoff setting to 'GVAR(enable)'

- addons/reload/CfgMagazines.hpp
- addons/reload/functions/fnc_canLinkBelt.sqf
> Add ACE_isBelt for DLC/Expansion magazines

- wiki/framework/interactionMenu-framework.md
Adds example using some of the advanced parts of the interaction menu.
> Add advanced example for interaction menu framework

- wiki/feature/ui.md
- wiki/framework/ui-framework.md
- Title
This is all already on stable, can be merged whenever.
> Add UI framework and update feature documentation

- wiki/framework/events-framework.md
> Add documentation for tagging to event wiki

- addons/tagging/README.md
- addons/tagging/functions/fnc_applyCustomTag.sqf
- addons/tagging/functions/fnc_compileConfigTags.sqf
- Title
- Add maintainers
- Use `configProperties` with inheritance instead of `configClasses`
- Invert a condition to be more readable
> Use pushBackUnique in Tags cache

- docs/wiki/feature/rearm.md
- docs/wiki/framework/rearm-framework.md
- docs/wiki/missionmaker/modules.md
> Remove never-merged rearm feature and framework documentation

- addons/common/functions/fnc_checkFiles.sqf
> skip DLL check on non-windows machines

- addons/common/functions/fnc_objectEvent.sqf
> fix FUNC(objectEvent)

- tools/make.py
- Title
If we want this I will update the doc as well.
> Read git version from file rather than using Git client in make.py

- addons/cookoff/functions/fnc_cookOff.sqf
> eject ai during cookoff

- addons/explosives/CfgVehicles.hpp
> add explosive devices to missing units, close #4181

- docs/.gitignore
- docs/README.md
- Update development environment setup instructions for our website/wiki for Windows CMD and Debian/Bash on Ubuntu on Windows in detail.
> Update documentation development environment instructions

- docs/wiki/missionmaker/useful-functions.md
> Wiki - Add link from missionmaker to framework for interaction menu

- docs/_config_dev.yml
- docs/_layouts/wiki.html
- docs/wiki/feature/advancedthrowing.md
**When merged this pull request will**
- title
- the version thing (@jonpas will know) 😜
> add version to frontmatter and display it in the wiki

- .lgtm
- Add configuration for LGTM
PRs require at least 1 approval from anyone in the MAINTAINERS group from @acemod or a MAINTAINERS file in the repo.
You may not self approve PRs.
Approval is done with placing a comment containing: `LGTM`, `:+1:` or `:shipit:`
New commits added to a PR will require reapproval.
This is not yet enabled for the ACE3 repository.
> add LGTM configuration

- docs/wiki/development/setting-up-the-development-environment.md
- Title
- Format the others as they actually are when installed
> Add DeRap to required Mikero's Tools

- docs/wiki/development/arma-3-issues.md
- Title
Apparently old links are no longer linked to the new ones.
> Fix Arma 3 issues links

- addons/common/XEH_postInit.sqf
> Fix INFO Macro not in CBA 3.0

- addons/advanced_fatigue/config.cpp
> Fix AF author String

- docs/README.md
> Fix documentation development environment guide formatting

- addons/ballistics/CfgWeapons.hpp
> Add ace mags to 7.62 SPAR_03

- addons/medical/functions/fnc_addDamageToUnit.sqf
- addons/medical/functions/fnc_handleDamage.sqf
> Fix handleDamage params for addDamageToUnit

- addons/medical_ai/ACE_Settings.hpp
- addons/medical_ai/XEH_postInit.sqf
- addons/medical_ai/config.cpp
- addons/medical_ai/stringtable.xml
Adds setting for medical AI
- Always Run (default)
- Only Server and HC
- Disabled
> Add setting for medical ai

- addons/medical_menu/functions/fnc_updateUIInfo.sqf
Never updated medical_menu with changes from #4306
> Fix blood bags not showing in medical menu

- docs/wiki/development/arma-3-issues.md
> Remove voting text in Arma 3 Issues list

- addons/medical/functions/fnc_handleDamage_wounds.sqf
> Medical - Fix adv wound not stacking

- addons/gestures/XEH_postInit.sqf
This matches the interaction menu
stop -> gesutreFreze
freeze -> freeze
> Fix stop gesture keybind
