acemod/ACE3

addons/cargo/functions/fnc_paradropItem.sqf
- `q2` meant to be `_vehicle` ?
=> Fix script error in cargo drop function

addons/advanced_fatigue/functions/fnc_pfhMain.sqf
=> Exit fatiuge loop when dead (don't play breathing sound)

addons/medical_ai/functions/fnc_healSelf.sqf
- Fix medical AI forcing bandage even if the AI is remote controlled.
=> Disable medical AI for remote controlled AI and players

addons/captives/functions/fnc_doLoadCaptive.sqf, addons/captives/functions/fnc_findEmptyNonFFVCargoSeat.sqf, addons/captives/functions/fnc_setHandcuffed.sqf, addons/captives/functions/fnc_setSurrendered.sqf, addons/captives/functions/fnc_vehicleCaptiveMoveIn.sqf
Simplify func using `fullCrew`
Fix #4339
also switch hard `ERROR(` macro to `WARNING(`
=> Captives - rewrite findEmptyNonFFVCargoSeat

docs/wiki/feature/medical-ai.md
- Add documentation for Medical AI
=> Medical AI documentation

docs/wiki/development/documentation-guidelines-and-tips.md, docs/wiki/feature/medical-ai.md
=> Fix dependencies list prefix that shouldn't exist

addons/nocrosshair/$PBOPREFIX$, addons/nocrosshair/CfgInGameUI.hpp, addons/nocrosshair/README.md, addons/nocrosshair/config.cpp, addons/nocrosshair/script_component.hpp, optionals/nocrosshair/$PBOPREFIX$, optionals/nocrosshair/CfgInGameUI.hpp, optionals/nocrosshair/README.md, optionals/nocrosshair/config.cpp, optionals/nocrosshair/script_component.hpp
- Dunno if this is still needed. Someone made a request for it and I forgot about it. Found it while going through my unmerged branches.
=> optional pbo to disable cross hair

addons/advanced_fatigue/XEH_postInit.sqf
`linearConversion` is cleaner and a little faster
fix weather factor
=> Tweak fatgiue duty factors

addons/weather/functions/fnc_getMapData.sqf
- Fix weather values for maps that inherit their CfgWorlds class from another map
- Restructure and simplify the getMapData function a little bit
=> Fixed weather for inherited CfgWorlds

docs/wiki/feature/grenades.md
- Add a hint to the grenades page for advanced throwing
=> Add hint to grenades pages for advanced throwing

.lgtm
Reverts acemod/ACE3#4298
Closes #4403
=> Remove LGTM configuration

addons/dogtags/CfgVehicles.hpp, addons/dogtags/XEH_postInit.sqf, addons/dogtags/functions/fnc_addDogtagItem.sqf, addons/dogtags/functions/fnc_checkDogtag.sqf, addons/dogtags/functions/fnc_takeDogtag.sqf, addons/dogtags/script_component.hpp
- plays animation, rustling sounds and delays the showing of the dogtag when applicable
- switches `displayText` (`hintSilent`) to better looking `displayTextStructured`
- puts dogtag interaction position on neck instead of main interaction point
=> more immersive dogtag interaction

docs/wiki/feature/advanced-throwing.md
=> Add version note to yellow Advanced Throwing circle documentation

addons/advanced_fatigue/XEH_PREP.hpp, addons/advanced_fatigue/XEH_postInit.sqf, addons/advanced_fatigue/functions/fnc_mainLoop.sqf, addons/advanced_fatigue/functions/fnc_pfhMain.sqf
Close #4379
- Will use CBA_missionTime so it respects pause and time acceleration
- Possible performance improvements over using a PFEH
=> Use waitAndExecute for fatigue loop

addons/common/CfgEden.hpp, addons/map/Cfg3DEN.hpp, addons/map/config.cpp, addons/map/stringtable.xml
- Adds a 3den group attribute to disable BFT even when it's enabled in the module
=> Add 3den attribute to disable bft

addons/cargo/functions/fnc_paradropItem.sqf
- setPos'ing parachutes too far seems to break them
=> fix broken parachutes

addons/interact_menu/functions/fnc_addActionToClass.sqf, addons/interact_menu/functions/fnc_addActionToObject.sqf
Fix #4460
Fix returning number from pushBack
Will still safely make a copy of the array `_parentAction`
=> Fix interaction addActionToX return values

addons/dogtags/CfgWeapons.hpp
- Remove visible id from the dog tag item
- Fix #4476
=> Remove visible id from the dog tag item

addons/medical_blood/README.md, addons/medical_blood/XEH_postInit.sqf, addons/medical_blood/config.cpp, addons/medical_blood/functions/fnc_createBlood.sqf, addons/medical_blood/functions/fnc_hit.sqf, addons/medical_blood/functions/fnc_onBleeding.sqf, addons/medical_blood/state_machine.hpp
- Fix ace_setting
- Don't run on headless if enabledFor = 1
- Don't create blood for non-local units
- Don't create blood when mounted (except static weapons)
- Add Readme
=> Fix medical blood locality / bleeding in vehicles

addons/captives/functions/fnc_handlePlayerChanged.sqf, addons/captives/functions/fnc_handleZeusDisplayChanged.sqf, addons/captives/functions/fnc_setHandcuffed.sqf, addons/captives/functions/fnc_setSurrendered.sqf, addons/common/functions/fnc_showHud.sqf, addons/ui/ACE_Settings.hpp, addons/ui/CfgVehicles.hpp, addons/ui/functions/fnc_moduleInit.sqf, addons/ui/functions/fnc_setElements.sqf, addons/ui/script_component.hpp, addons/ui/stringtable.xml
- Replaces #4043 for `master` branch (didn't make it into 1.62)
=> Update showHud setter for Squad Radar

addons/captives/functions/fnc_handlePlayerChanged.sqf, addons/captives/functions/fnc_handleZeusDisplayChanged.sqf, addons/captives/functions/fnc_setHandcuffed.sqf, addons/captives/functions/fnc_setSurrendered.sqf, addons/common/functions/fnc_showHud.sqf, addons/ui/ACE_Settings.hpp, addons/ui/CfgVehicles.hpp, addons/ui/functions/fnc_moduleInit.sqf, addons/ui/functions/fnc_setElements.sqf, addons/ui/script_component.hpp, addons/ui/stringtable.xml
Reverts acemod/ACE3#4085
Apparently it's still not in 1.64... I bet @PabstMirror told me that and I forgot.
=> Revert "Update showHud setter for Squad Radar"

addons/cookoff/functions/fnc_cookOff.sqf
=> Fix cookoff event calling

optionals/compat_rhs_usf3/CfgVehicles.hpp
=> Disable FCS on RHS helicopters

addons/advanced_fatigue/XEH_postInit.sqf, addons/advanced_fatigue/functions/fnc_handleEffects.sqf
- implement arithmetic source for fatigue system
=> implement arithmetic source for fatigue system

addons/mk6mortar/functions/fnc_handlePlayerVehicleChanged.sqf
Fix #3757
Seems to be working, will want to retest after laser rewrite merged.
=> Show correct elev for mortar with no ammo

addons/laserpointer/XEH_postInit.sqf, addons/nametags/functions/fnc_onDraw3d.sqf
=> avoid PCTW error on certain vehicles

docs/README.md
=> Fix documentation README commands

addons/laserpointer/functions/fnc_drawLaserpoint.sqf
- ![http://i.imgur.com/bxcRxZG.png](http://i.imgur.com/bxcRxZG.png)
this is maxed out alpha (1). won't get any better unless someone provides a custom texture
=> increase red laser alpha, close #4535

addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- Fix going unconscious while fastroping
=> Fix going unconscious while fastroping

addons/grenades/functions/fnc_incendiary.sqf, addons/grenades/functions/fnc_throwGrenade.sqf
- this should emulate the hard coded behaviour pretty accurately
=> emulate frag grenade ai behaviour for incendiaries

addons/medical/functions/fnc_getBloodLoss.sqf, addons/medical/functions/fnc_getBloodVolumeChange.sqf, addons/medical/functions/fnc_getCardiacOutput.sqf, addons/medical/functions/fnc_getHeartRateChange.sqf, addons/medical/functions/fnc_handleStateDefault.sqf, addons/medical/functions/fnc_handleStateInjured.sqf, addons/medical/functions/fnc_handleStateRevive.sqf, addons/medical/functions/fnc_handleStateUnconscious.sqf, addons/medical/functions/fnc_handleUnitVitals.sqf, addons/medical/functions/fnc_init.sqf, addons/medical/script_macros_medical.hpp, addons/medical_treatment/functions/fnc_treatmentBloodbagLocal.sqf, addons/medical_treatment/functions/fnc_treatmentFullHealLocal.sqf, addons/medical_treatment/functions/fnc_treatmentIVLocal.sqf
- Change the magic 100 of blood volume to 6 liters.
- also add macros / config to adjust certain other magic numbers
- change what is recorded as "lost some" or "a lot of" blood.
=> use liters for blood volume variable

docs/wiki/feature/medical-system.md
=> Add missing line in medical doc

docs/README.md
=> fix spelling of ruby

addons/mk6mortar/functions/fnc_handlePlayerVehicleChanged.sqf
=> Fix mortar changes for laser shootRay changes

addons/cookoff/stringtable.xml, addons/laser/stringtable.xml, addons/map/stringtable.xml, addons/maptools/stringtable.xml, addons/medical_blood/stringtable.xml
To translate the new word (v380) to the Japanese.
=> Jpn translation v380

addons/vehiclelock/functions/fnc_lockpick.sqf
=> Fix vehLock warning about bad func type

addons/cookoff/CfgVehicles.hpp, addons/cookoff/XEH_postInit.sqf
this should be closer to vanilla behaviour and should solve issues with unconfigured vehicles taking too many hits
=> cookoff ammo selections default values

addons/medical_blood/XEH_postInit.sqf
Logic was inverted, if player was hit it wouldn't create blood
=> Fix bleeding hit logic for enabledFor = 1

docs/_config.yml, docs/_config_dev.yml
=> WebDoc Version to 3.8.1

addons/cookoff/functions/fnc_cookOff.sqf
- Changes header example
- Orders crew to move 100m away from the vehicle in random direction ASAP
- https://www.youtube.com/watch?v=KX1UOjsI4bA
=> Blocks AI getting back into the vehicle on cookoff

addons/javelin/RscInGameUI.hpp
- None of these are supposed to have a scrollbar... so I removed them.
=> remove scrollbars from javelin scope

docs/wiki/development/setting-up-the-development-environment.md
=> Fix make.py documentation lists

addons/atragmx/functions/fnc_update_zero_range.sqf
- Fixes a minor bug in the zero range update routine
Fixes: #3607
=> Fixes the ATragMX 'Done' button issue

addons/medical_ai/functions/fnc_playTreatmentAnim.sqf
Same as PR #4371 for medical AI
After healing themselves civilians would be stuck like this (makes them look threatening):
=> MedicalAI - Fix treatment animion with no weapon

docs/wiki/development/setting-up-the-development-environment.md
- Title
@Glowbal I am sorry, but you were properly using the wrong one. :/
=> Fix make.py checkexternal argument documentation

addons/atragmx/functions/fnc_calculate_target_solution.sqf
* Fix the ATragMX spin drift calculation
=> ATragMX - Estimate bullet length instead of using a fixed value

addons/microdagr/functions/fnc_mapOnDrawEH.sqf
Head-dir is what everythign else uses.
=> Use head direction for drawing microdag wp

addons/advanced_fatigue/functions/fnc_getAnimDuty.sqf
- Fix low stamina usage in any adjusted stance
=> Fix advanced fatigue for adjusted stances

addons/ballistics/CfgVehicles.hpp
* Add 20Rnd 6.5mm Lapua Scenar / Creedmor magazines to various ammoboxes
=> Ballistics - AmmoBox update (Apex magazines)

docs/wiki/framework/scopes-framework.md
Documented the changes to the scopes framework made in this pull request: https://github.com/acemod/ACE3/pull/4642
=> Scopes - Updated wiki framework

addons/mk6mortar/XEH_postInit.sqf
=> Change mortar to ammo handling weapon on init

addons/atragmx/functions/fnc_parse_input.sqf, addons/atragmx/functions/fnc_recalculate_c1_ballistic_coefficient.sqf, addons/atragmx/functions/fnc_recalculate_muzzle_velocity.sqf, addons/atragmx/functions/fnc_show_c1_ballistic_coefficient_data.sqf, addons/atragmx/functions/fnc_update_c1_ballistic_coefficient_data.sqf, addons/atragmx/functions/fnc_update_gun_ammo_data.sqf, addons/atragmx/functions/fnc_update_unit_selection.sqf, addons/atragmx/functions/fnc_update_zero_range.sqf
* Fix a possible divison through zero
* Fix a unit conversion issues in the interpolation table input/output handling
* Add proper input range checks for both metric and imperial data inputs
=> ATragMX - Various bug fixes

extensions/advanced_ballistics/AdvancedBallistics.cpp
* Decrease the ballistic coefficient once the bullet goes transonic
* Introduce yawing and pitching of the bullet nose during transonic flight (instead of modifying the bullet velocity directly)
=> Advanced Ballistics - Improved simulation of transonic flight

addons/advanced_ballistics/functions/fnc_handleFired.sqf
- Always adjust the muzzle velocity when advanced ballistics is enabled
=> AdvancedBallistics - Abort after adjusting the muzzle velocity

tools/make.py
=> Remove build number from release archive

docs/wiki/feature/modules.md, docs/wiki/framework/modules-framework.md
- Adds documentation explaining the module pbo 
- Adds documentation explaining how to use the module framework
=> Add module documentation

addons/atragmx/functions/fnc_calculate_target_solution.sqf
The goal is to keep the integration error below 0.1 MRAD.
=> ATragMX - Minimize the integration error

addons/repair/stringtable.xml, addons/scopes/stringtable.xml, addons/weather/stringtable.xml, addons/zeus/stringtable.xml
Japanese translation for v3.8.2 and some fix
=> Jpn translation v382

optionals/compat_rhs_usf3/functions/fnc_onCut.sqf, optionals/compat_rhs_usf3/functions/fnc_onPrepare.sqf
Switched obsolete EFUNC(common,waitAndExecute) to CBA_fnc_waitAndExecute
=> Switched to CBA_fnc_waitAndExecute

addons/atragmx/functions/fnc_calculate_solution.sqf
`average speed` = `distance` / `time of flight`
=> ATragMX - Simplified Coriolis calculation

docs/wiki/development/setting-up-the-development-environment.md
=> Add PboProject .hpp exclusion note

addons/frag/CfgAmmo.hpp, addons/frag/XEH_postInit.sqf, addons/frag/functions/fnc_dev_debugAmmo.sqf, addons/frag/functions/fnc_frago.sqf
=> Add frag definitions for remaining ammo

addons/ai/CfgWeapons.hpp, addons/ballistics/CfgWeapons.hpp, addons/realisticweights/CfgWeapons.hpp, addons/smallarms/CfgWeapons.hpp
Ref https://github.com/CBATeam/CBA_A3/pull/552
=> Update SMG_02 base class for 1.66

addons/medical_blood/functions/fnc_onBleeding.sqf
=> Fix blood drop selection if blood loss is high

addons/minedetector/functions/fnc_getDetectorConfig.sqf
=> fix usage of reserved variable "" in FUNC(getDetectorConfig)

addons/rearm/CfgVehicles.hpp
=> add rearm to Vehicle Ammo boxes

optionals/particles/CfgAmmo.hpp
=> Fix ace_particles smoke on arty shells

addons/trenches/stringtable.xml
- improve the german translation for entrenchment tool (no one uses "Schanzzeug")
=> improve german translation for entrenchment tool

addons/ballistics/stringtable.xml, addons/medical_menu/stringtable.xml, addons/zeus/stringtable.xml
fix the html tag in ballistics and medical_menu in the Japanese translation. Also support for new strings in zeus.
=> Fix jpn translate v383

tools/publish.py
=> Fix reversed RHS compats for steam workshop

.github/PULL_REQUEST_TEMPLATE.md, docs/README.md, docs/README_DE.md, docs/README_PL.md, docs/_config.yml, docs/_includes/_footer.html, docs/_includes/_header.html, docs/_posts/2015-07-30-ace3-version320.md, docs/_posts/2015-09-17-ace3-version331.md, docs/_posts/2015-12-03-ace3-version340.md, docs/_posts/2016-03-02-ace3-version350.md, docs/_posts/2016-06-21-moving-ace3-frameworks-to-cba.md, docs/_posts/2016-06-30-ace3-version360.md, docs/_posts/2016-09-17-ace3-version370.md, docs/_posts/2016-11-04-ace3-version381.md, docs/index.html, docs/wiki/development/coding-guidelines.md, docs/wiki/feature/rangecard.md, docs/wiki/user/information-center.md
- Use https for EVERYTHING!!!!!!!!!!!!!
=> Use https for ace3mod

docs/_includes/_footer.html, docs/index.html
=> add some rel="noopener" to external links

addons/missileguidance/XEH_pre_init.sqf, addons/missileguidance/functions/fnc_attackProfile_JAV_TOP.sqf
`private` in wrong place, left cruise height at max
=> Fix javelin cruise heigh on close shots

addons/medical_ai/functions/fnc_healUnit.sqf
=> Ensure movingToInjured is false whenever _target no longer needs healing

addons/zeus/stringtable.xml
- Title
Looks like Polish translation merge went a bit sideways.
=> Remove duplicated Zeus strings

addons/tacticalladder/functions/fnc_cancelTLdeploy.sqf
Doesn't fix the core issue behind #4814 but it fixes the issue that bothered me so much that i reported this.
- Fix the script error described in #4814
=> Fixes #4814 Tactical Ladder script error

addons/medical/stringtable.xml
- Title
Not sure if I should have PRed that into medical rewrite branch.
=> Fix medical typo 'to' -> 'too'

addons/map/CfgLights.hpp
- Fixes "missing config" error
=> Add missing orange map chemlight entry

addons/repair/CfgVehicles.hpp
also remove non-existent class Truck_02_engineeral_base_F
=> fix kamaz medical can repair

addons/laserpointer/XEH_postInit.sqf
Requires https://github.com/CBATeam/CBA_A3/pull/582
=> Use CBA ACC EH to prevent switching to unusable lzr

addons/medical/functions/fnc_handleDamage.sqf
- title
- fixes #4863
It's just a bandaid and shouldn't be an issue in the first place in the medical-rewrite branch.
=> fix script error caused by new arguments passed to handleDamage

.github_changelog_generator
- Remove redundant config lines
- Include `translation` PRs in generation
=> Cleanup GitHub Changelog Generator config file

addons/realisticnames/stringtable.xml
=> Fix double single quote to single double quote

addons/realisticnames/stringtable.xml
=> fix HK416 name

addons/laserpointer/XEH_PREP.hpp, addons/laserpointer/XEH_postInit.sqf, addons/laserpointer/XEH_preInit.sqf, addons/laserpointer/functions/fnc_getNearUnits.sqf, addons/laserpointer/functions/fnc_onDraw.sqf, addons/laserpointer/script_component.hpp
- title
- removes the 10 simulated units limit
todo:
- ~~will have to process the player every frame anyway to remove delay when turning on the laser with units nearby (responsiveness)~~
- ~~clearing the array at once means that the laser point is blinking atm. (bug)~~
=> Optimize Laserpointer

addons/missionmodules/functions/fnc_moduleAmbianceSound.sqf
I messed up [distance, angle] order
=> Fix getPos order for mission modules

addons/frag/XEH_postInit.sqf, addons/frag/functions/fnc_frago.sqf, addons/frag/functions/fnc_startTracing.sqf
Fix script errors from #4581 
It uses `MUL(` macro that doesn't seem to exist in cba/ace :confused:
=> Fix frag MUL macros

addons/advanced_fatigue/stringtable.xml, addons/advanced_throwing/stringtable.xml, addons/cookoff/stringtable.xml, addons/dogtags/stringtable.xml, addons/explosives/stringtable.xml, addons/frag/stringtable.xml, addons/goggles/stringtable.xml, addons/grenades/stringtable.xml, addons/inventory/stringtable.xml, addons/markers/stringtable.xml, addons/medical/stringtable.xml, addons/medical_ai/stringtable.xml, addons/medical_menu/stringtable.xml, addons/minedetector/stringtable.xml, addons/movement/stringtable.xml, addons/nametags/stringtable.xml, addons/tagging/stringtable.xml, addons/ui/stringtable.xml, addons/zeus/stringtable.xml, optionals/compat_adr_97/stringtable.xml
When merged this pull request will :
Add french translation to "Advanced throwing" and "Advanced fatigue"
=> French translation to "Advanced throwing" and "Advanced fatigue"

addons/tagging/functions/fnc_createTag.sqf
=> Use createSimpleObject to create tags

README.md, addons/main/script_mod.hpp, addons/main/script_version.hpp, docs/README_DE.md, docs/README_PL.md, mod.cpp
=> Update CBA required version

addons/main/CfgSettings.hpp, optionals/compat_rhs_gref3/$PBOPREFIX$, optionals/compat_rhs_gref3/CfgAmmo.hpp, optionals/compat_rhs_gref3/config.cpp, optionals/compat_rhs_gref3/script_component.hpp
=> Add RHS GREF compat for RKG-3 grenade

docs/wiki/frameworkx/headless-framework.md
- Add End Mission setting description
- Update limitations with what is handles by Headless component already
Can be merged as it's all noted in version.
=> Update ACEX Headless framework documentation

addons/common/functions/fnc_getMapData.sqf
- add Dingor
- add MSKE 2017
- add G.O.S Leskovets
- add Trung Si
- add I44 Terrains, except I44: Merderet River maps (correct latitude)
- add I44: Omaha v2
- add I44: Neaville and Neaville (Winter)
- add I44: Battle of the Bulge
=> Add maps with correct latitude

addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf
=> Prevent starting additional vital loops on full heal

addons/medical/stringtable.xml
korean player, confused about name of wounds.
replaced it more accurate name.
=> More accurate Korean translate for medical

addons/atragmx/functions/fnc_toggle_option_menu.sqf
=> atragMX - Give options menu list focus

addons/scopes/functions/fnc_inventoryCheck.sqf
=> Fix intergrated scopes

addons/medical/XEH_preInit.sqf
=> Reload medical configs into extension when loading save

addons/map_gestures/functions/fnc_receiverInit.sqf
=> Pass map gestures draw by reference

addons/vehiclelock/functions/fnc_lockpick.sqf
- Fix vehicle lock lockpick condition
- Fix lockpicking from inside
=> Fix vehicle lock conditions

addons/rearm/CfgVehicles.hpp, addons/rearm/XEH_postInit.sqf
=> Add rearm config for Nemmera

addons/tagging/stringtable.xml
=> Duplicate Polish entry

addons/tagging/stringtable.xml
- Removes a duplicate French entry
=> Duplicate French entry

docs/wiki/feature/kestrel4500.md
=> Wiki Kestrel 4500 updated

addons/medical_treatment/XEH_postInit.sqf
- Convert FAKs or vanilla Medikits into corrosponding ace bandages and injections on pick up.
This is a really minor fix, however i was told to make even prs for those, so here you go.
=> [Medical Rewrite]  Convert FAKs and Medkits on pickup

addons/cargo/stringtable.xml
Minor French text additions
- add two French entries
=> French additions (Cargo)

addons/ballistics/stringtable.xml
- fixes some minors French text issues
=> French loc fixes (ballistics)

docs/wiki/feature/vector.md
Add explanation on how to switch range and azimuth units
=> Update documentation for Vector21

addons/dagr/functions/fnc_outputWP.sqf
=> Fix dagr not showing bearing in mils

addons/cargo/functions/fnc_canLoadItemIn.sqf
=> Fix cargo loading to locked vehicle

docs/_config.yml
- Fix the ACEX download button on the main page
=> Update ACEX to 3.2.0.4

addons/optionsmenu/config.cpp, addons/optionsmenu/init_loadMainMenuBox.sqf
- title
- https://github.com/acemod/ACE3/pull/5073#issuecomment-293164458
=> use https for main menu

addons/optionsmenu/init_loadMainMenuBox.sqf
- makes our info box the same color as the other ones when hovering over it. was slightly darker, oops.
=> fix highlighted info box color

addons/zeus/functions/fnc_ui_teleportPlayers.sqf
=> Filter headless clients from zeus teleportation

addons/medical/stringtable.xml
- improve French accuracy and usability
=> (Medical) French text - minor changes

addons/chemlights/stringtable.xml, addons/cookoff/stringtable.xml, addons/laser/stringtable.xml, addons/map/stringtable.xml, addons/maptools/stringtable.xml, addons/medical_blood/stringtable.xml, addons/overpressure/stringtable.xml, addons/scopes/stringtable.xml, addons/slideshow/stringtable.xml, addons/tagging/stringtable.xml, addons/zeus/stringtable.xml
- add French entries, everywhere they were missing as far as I can tell
@alganthe
=> French localization complete

optionals/compat_rhs_usf3/CfgAmmo.hpp
=> Fix AI usage of RHS Javelin

addons/refuel/functions/fnc_dropNozzle.sqf
=> Fix refuel nozzle dropping to ground

optionals/compat_rhs_afrf3/CfgVehicles.hpp
=> Disable ACE_FCS on RHS Russian Attack Helis

addons/hitreactions/functions/fnc_fallDown.sqf
=> hitreactions - Close map on hit

docs/wiki/feature/atragmx.md
=> Wiki AtragMx minor changes

addons/common/functions/fnc_getMapData.sqf
**Lythium map with the Advanced Ballistics module.**
- Afghanistan: positive latitude 34° (default -34°).
=> AB: Lythium latitude

docs/wiki/development/arma-3-issues.md
ACE rearm has some issues like it can't rearm vehicle with different localities of vehicle and turret, or it can't fully rearm turret with multiple magazines of the same type. It's all because of mentioned Arma 3 issues.
=> Add Arma 3 Issues breaking ace_rearm

addons/map_gestures/functions/fnc_transmitterInit.sqf
=> MapGesutres - Fix dependency on maptools

addons/zeus/stringtable.xml
Adds and Fixes in the zeus section.
I hope I have not forgotten nothing.
=> Italian translation for Zeus updated

addons/advanced_throwing/XEH_postInit.sqf, addons/cargo/functions/fnc_initObject.sqf, addons/cargo/functions/fnc_initVehicle.sqf, addons/common/functions/fnc__handleRequestAllSyncedEvents.sqf, addons/common/functions/fnc_cachedCall.sqf, addons/common/functions/fnc_getNumberMagazinesIn.sqf, addons/common/functions/fnc_switchToGroupSide.sqf, addons/concertina_wire/functions/fnc_deploy.sqf, addons/concertina_wire/functions/fnc_dismountSuccess.sqf, addons/dragging/functions/fnc_handleAnimChanged.sqf, addons/dragging/functions/fnc_setDraggable.sqf, addons/finger/functions/fnc_perFrameEH.sqf, addons/interact_menu/functions/fnc_compileMenu.sqf, addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf, addons/interact_menu/functions/fnc_compileMenuZeus.sqf, addons/interact_menu/functions/fnc_isSubPath.sqf, addons/interact_menu/functions/fnc_renderBaseMenu.sqf, addons/interaction/functions/fnc_canJoinTeam.sqf, addons/kestrel4500/functions/fnc_generateOutputData.sqf, addons/laser/functions/fnc_dev_drawVisibleLaserTargets.sqf, addons/laser/functions/fnc_seekerFindLaserSpot.sqf, addons/magazinerepack/functions/fnc_simulateRepackEvents.sqf, addons/nametags/functions/fnc_doShow.sqf, addons/nametags/functions/fnc_getVehicleData.sqf, addons/overheating/functions/fnc_canCheckSpareBarrelsTemperatures.sqf, addons/overheating/functions/fnc_getWeaponData.sqf, addons/overheating/functions/fnc_updateSpareBarrelsTemperaturesThread.sqf
- Fix bug in getNumberMagazinesIn (func not used)
- Fix bug in seekerFindLaserSpot (func not used yet)
Everything else is just cleanup
=> Minor fixes, cleanup, add lint ignore directives

addons/interaction/ACE_ZeusActions.hpp
Hides actions that aren't appropriate based on what is selected.
=> Only show zeus interactions when thing is selected

addons/medical/functions/fnc_displayPatientInformation.sqf
=> Fix IVs not showing in patient display

addons/spectator/functions/fnc_handleIcons.sqf
- Fixes number I accidentally changed in #5067
=> Fix accidental numerical change

addons/cargo/stringtable.xml, addons/common/stringtable.xml, addons/hellfire/stringtable.xml, addons/nlaw/stringtable.xml, addons/quickmount/stringtable.xml, addons/refuel/stringtable.xml, addons/zeus/stringtable.xml
Added Italian translation for:
-cargo
-hellfire
-nlaw
-quickmount
-refuel
-zeus
=> Italian Translation Update

addons/weaponselect/functions/fnc_throwGrenade.sqf
=> Fix weapon select grenade count when using advThrow

addons/medical_engine/functions/fnc_handleDamage.sqf
=> Med rw handle fire damage

docs/wiki/feature/kestrel4500.md
- Add `CROSSWIND` / `HEADWIND` feature with the official video.
=> Update Kestrel 4500 Wiki

docs/squad/squad.xml, docs/wiki/framework/cargo-framework.md
- Add documentation on new cargo public functions and editor attributes
- Add myself to the ace3 squad.xml (I didn't realise we had this 😄)
=> Update cargo docs with new public functions

addons/rearm/stringtable.xml, addons/repair/stringtable.xml
Added newest lines for:
-Rearm
-Repair
Fixed 1 line for:
-Rearm
=> Italian translation updated and fixed

docs/wiki/feature/kestrel4500.md
- Kestrel's wiki: fix video link
=> Kestrel's wiki: fix video link

addons/cargo/CfgVehicles.hpp, addons/dragging/CfgVehicles.hpp, addons/interaction/CfgVehicles.hpp
Close #4783
- Make taru pods non loadable
- Make taru pods non draggable
- Increase interaction range for huron pods
=> Cleanup heli pod actions

addons/cargo/XEH_preInit.sqf, addons/cargo/functions/fnc_addCargoVehiclesActions.sqf, addons/cargo/functions/fnc_initObject.sqf, addons/cargo/functions/fnc_initVehicle.sqf, addons/cargo/functions/fnc_startLoadIn.sqf, addons/cargo/script_component.hpp
Fix #5272
Every holder needs to run initVehicle to get the cargo actions
So we can add to the array of holders dynamically
=> Make array of cargo holders dynamic

addons/medical/stringtable.xml, addons/repair/stringtable.xml
fix medical
support new entry
localization is based on d02dacf61314627a7ac6a2e3141504b57e61b295
=> Japanese translation d02dacf

addons/repair/functions/fnc_isNearRepairVehicle.sqf
=> Allow repairing from slingload pods

addons/cargo/CfgVehicles.hpp
Makes them match the Taru pods
Fix #5313
=> Add cargo space to huron containers

addons/rearm/XEH_postInit.sqf, addons/rearm/functions/fnc_rearmEntireVehicleSuccess.sqf, addons/rearm/functions/fnc_rearmSuccess.sqf
=> Rearm - Fix locality event passing

.gibot.yml
=> Updated gibot script labels

addons/cargo/stringtable.xml, addons/hellfire/stringtable.xml, addons/nlaw/stringtable.xml, addons/quickmount/stringtable.xml, addons/rearm/stringtable.xml, addons/refuel/stringtable.xml, addons/repair/stringtable.xml, addons/spectator/stringtable.xml, addons/zeus/stringtable.xml
- Add remaining polish translations
=> Add missing polish translations

docs/wiki/development/setting-up-the-development-environment.md
=> Fixed a spelling error

docs/wiki/development/setting-up-the-development-environment.md
it can be used for MACRO way only
=> Fix fast recompiling documentation

docs/wiki/development/setting-up-the-development-environment.md
Current Mikero Tools link now leads to a "we're shutting down dev-heaven" page. :(
Changing to Maverick Applications homepage.
=> update Mikero's download link

addons/medical/ACE_Medical_SelfActions.hpp
=> fix issue that Adenosine had the wrong displayName in self Interaction

addons/map/XEH_postInitClient.sqf, addons/map/functions/fnc_determineMapLight.sqf, docs/wiki/framework/map-framework.md, optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
=> Customized map lighting for vehicle interiors

docs/wiki/framework/map-framework.md
=> Map wiki fix

addons/spectator/functions/fnc_ui.sqf, addons/spectator/functions/fnc_ui_fadeList.sqf, addons/spectator/ui.hpp
- Fix the text colour of the tab UI element when it is faded
=> Improve spectator tab fading

addons/common/functions/fnc_canDig.sqf, addons/common/script_component.hpp
Close #5450
Malden uses `GdtGrassGreen` which has a dust of 0.05
=> Allow digging in malden grass

docs/wiki/framework/explosives-framework.md
- Fix the GVARs in the explosives framework section
- Add trigger type and delay time in example configs
=> Fix GVARs in explosives wiki

addons/spectator/functions/fnc_ui_draw3D.sqf, addons/spectator/functions/fnc_ui_handleMouseButtonDown.sqf, addons/spectator/functions/fnc_ui_updateIconsToDraw.sqf
- Limit selection distance to within nametag drawing range
- Optimise drawing and selection code
- Fix some drawing behaviour (mostly related to mounted units)
- Fix potential for drawing to fail when in FPP view
- Fix that entities which weren't spectatable could be selected via cursor
=> Improve spectator drawing and selection

addons/dogtags/functions/fnc_ssn.sqf
=> Dogtags - Fix error with cyrillic names

addons/atragmx/functions/fnc_calculate_target_solution.sqf, addons/atragmx/functions/fnc_update_zero_range.sqf
=> ATragMX - Fixed AT mode

addons/explosives/CfgAmmo.hpp, addons/explosives/CfgMagazines.hpp, addons/explosives/CfgVehicles.hpp, addons/explosives/functions/fnc_detonateExplosive.sqf
=> Add ace_explosive support for orange dlc mines

addons/respawn/functions/fnc_restoreGear.sqf
=> Don't add fake weapon in restoreGear

addons/cargo/CfgVehicles.hpp, addons/logistics_uavbattery/CfgVehicles.hpp, addons/refuel/CfgVehicles.hpp
- Remove cargo from orange drones (and apex heli drone)
- Allow battery replacement on orange drone
=> Add support for orange drone (UAV_06)

addons/sandbag/functions/fnc_handleUnconscious.sqf, addons/tacticalladder/functions/fnc_handleUnconscious.sqf, addons/trenches/functions/fnc_handleUnconscious.sqf, addons/tripod/functions/fnc_handleUnconscious.sqf
=> Fix unconscious handlers run globally

addons/cargo/XEH_PREP.hpp, addons/cargo/functions/fnc_removeCargoItem.sqf, docs/wiki/framework/cargo-framework.md
- Adds a function called `ace_cargo_fnc_removeCargoItem` to do the opposite of what `ace_cargo_fnc_addCargoItem` does.
- Adds appropriate event and documentation.
=> Cargo: Add removeCargoItem Function

addons/map/CfgMarkers.hpp
- Re-enable the placement of the medical markers on the ingame map
Marking a medical FOB ingame would be quite nice so this could be re-enabled.
=> Re enable all markers (except civ and quantity)

AUTHORS.txt, addons/captives/ACE_Settings.hpp, addons/captives/CfgVehicles.hpp, addons/captives/functions/fnc_canApplyHandcuffs.sqf, addons/captives/functions/fnc_moduleSettings.sqf, addons/captives/stringtable.xml
- Add new ace_captives setting: require AI to be surrendered before one can handcuff them
=> Add requireSurrender setting for AI

addons/magazinerepack/functions/fnc_magazineRepackFinish.sqf, addons/magazinerepack/stringtable.xml
stringtable optimization
- fixes #5390
=> magazinerepack stringtable fix #5390

addons/captives/functions/fnc_canStopEscorting.sqf, addons/cargo/functions/fnc_canUnloadItem.sqf, addons/chemlights/functions/fnc_throwIR.sqf, addons/common/functions/fnc_dumpArray.sqf, addons/common/functions/fnc_findUnloadPosition.sqf, addons/common/functions/fnc_showHud.sqf, addons/common/functions/fnc_unloadPersonLocal.sqf, addons/common/functions/fnc_watchVariable.sqf, addons/disarming/functions/fnc_disarmDropItems.sqf, addons/explosives/functions/fnc_placeExplosive.sqf, addons/explosives/functions/fnc_scriptedExplosive.sqf, addons/explosives/functions/fnc_startTimer.sqf, addons/hearing/functions/fnc_updateVolume.sqf, addons/interact_menu/functions/fnc_handleEscapeMenu.sqf, addons/interaction/functions/fnc_showMouseHint.sqf, addons/laser/functions/fnc_laserOn.sqf, addons/laser/functions/fnc_seekerFindLaserSpot.sqf, addons/laser/functions/fnc_shootCone.sqf, addons/laser/functions/fnc_shootRay.sqf, addons/microdagr/functions/fnc_openDisplay.sqf, addons/mk6mortar/functions/fnc_loadMagazineTimer.sqf, addons/zeus/functions/fnc_showMessage.sqf
=> Cleanup optional argument headers

addons/flashlights/stringtable.xml
=> Typo in flashlights translation, Fix #5552

addons/rearm/functions/fnc_getHardpointMagazines.sqf, addons/rearm/functions/fnc_getNeedRearmMagazines.sqf, addons/rearm/functions/fnc_readSupplyCounter.sqf
- getHardpointMagazines wasn't public so should be fine to drop
- switch to getPylonTurret instead of configs
- fix bad LSTRING
=> Minor rearm fixes

optionals/compat_rhs_usf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgWeapons.hpp
Quickly tested javelin working fine (worked fine with UBC warning as well)
=> Fix UBC for RHS 4.3

addons/kestrel4500/CfgWeapons.hpp
Ref #5502
somehow missed this one
=> Fix kestrel ItemInfo for cba misc items

README.md
=> Fix README license note

optionals/compat_r3f/CfgWeapons.hpp
=> Compat R3F : fix zero J10 Mildot

addons/medical/ACE_Settings.hpp
- Remove legacy airway and fractures medical settings
Both have no effect and only confuse users, see Slack.
=> Remove legacy medical settings

addons/overheating/CfgVehicles.hpp
Unconscious civilian would show the check weapon temp action
=> Disable checking weapon temp on fakeWeapon

docs/wiki/feature/advanced-fatigue.md
- Remove the dead link to the VBS Advanced Fatigue manual
Closes #5602.
=> Remove dead link in AF docs

optionals/nouniformrestrictions/CfgVehicles.hpp
- Unrestrict side usage for 1.76 uniforms
=> Update No Uniform Restrictions definitions for Arma 3 1.76

addons/zeus/functions/fnc_moduleGarrison.sqf, addons/zeus/functions/fnc_moduleUnGarrison.sqf
=> Fix garrison header and use showMessage

addons/weather/XEH_postServerInit.sqf, addons/weather/functions/fnc_updateRain.sqf
`GVAR(nextUpdateRain) = 0;` was inside the pfeh
=> Fix server rain PFEH

docs/team.md
=> Update team page from authors.txt

addons/scopes/functions/fnc_applyScopeAdjustment.sqf, addons/scopes/functions/fnc_firedEH.sqf, addons/scopes/script_component.hpp
* Same issue as https://github.com/acemod/ACE3/pull/5640
=> Scopes - Fixed MRAD conversion

addons/dragging/functions/fnc_handleScrollWheel.sqf
- Fix objects teleporting underwater when carrying them above water (on a carrier etc.)
Fixes #5658.
=> Fix carrying on water (AGL->ASL)

docs/wiki/feature/refuel.md, docs/wiki/framework/refuel-framework.md
Adds 3.11 changes documentation.
=> Fix refuel documentation

addons/pylons/functions/fnc_showDialog.sqf
=> Pylons: Evaluate String Values from config

addons/realisticnames/CfgWeapons.hpp, addons/realisticnames/stringtable.xml
=> Remove duplicate weapon srifle_DMR_03_spotter_F

optionals/compat_rhs_usf3/CfgGlasses.hpp
=> RHS Compatibility - fixes shemagh having overlay despite no goggles

addons/zeus/functions/fnc_moduleLoadIntoCargo.sqf
=> Zeus - Fix moduleLoadIntoCargo using wrong function

tools/make.py
`-N do Nothing special. Make a pbo wysiwig`
=> make.py - Make no-bin work

addons/pylons/functions/fnc_canConfigurePylons.sqf
- allow ace engineers to configure pylons
=> Ability for ace engineer to configure pylons

addons/weaponselect/XEH_postInit.sqf, addons/weaponselect/stringtable.xml
- Add collision lights keybind
- Unbound by default (any suggestions for good default?)
=> Collision lights keybind

docs/wiki/framework/checkPBOs-framework.md
=> fix wiki suggesting activatedAddon to export addon list

addons/pylons/XEH_postInit.sqf
=> Add more sources for pylon (Taru and Huron pods)

addons/scopes/CfgWeapons.hpp
* Manually fix rail heights where the automated gathering process failed
* Affects: Noreen "Bad News" ULR, Vector SMG and ASP-1 Kir
=> Scopes - Fixes zero of three vanilla weapons

docs/wiki/feature/pylons.md
- Add documentation for ace3 pylons component. 
- Created pylons.md in wiki/feature
=> Pylons documentation

addons/atragmx/functions/fnc_calculate_truing_drop.sqf, addons/atragmx/functions/fnc_update_range_card.sqf, addons/atragmx/functions/fnc_update_result.sqf, addons/atragmx/functions/fnc_update_truing_drop_data.sqf, addons/atragmx/script_component.hpp, addons/rangecard/script_component.hpp
I accidentally swapped the names of the two macros.
=> ATragMX | Scopes - Fixed typo

addons/ballistics/CfgWeapons.hpp, addons/ballistics/script_component.hpp
* Adds `MOA_TO_RAD` macro
* Adds its actual name to each configuration entry
=> Ballistics - Dispersion Cleanup

addons/rangecard/functions/fnc_updateRangeCard.sqf
* Accounts for the latest accuracy improvements of the Advanced Ballistics module
* Reduces the expected error within the maximum range to 0.1 Mil.
=> RangeCard - Increased level of accuracy

docs/wiki/feature/map-gestures.md, docs/wiki/feature/markers.md
- Update markers.md to include moveable map markers.
=> Moveable Map Markers Documentation

extensions/common/vector.hpp
This makes vector functions constexpr which will allow the compiler to evaluate some stuff at compile time (currently not done anywhere)
=> Extension: Refactor vector math functions

circle.yml
Add configuration file for CircleCI.
=> Add circleCI yml file

tools/generate_airfriction_config.py
=> Tools - Fixed typo

docs/wiki/featurex/fortify.md
- Fortify not fortify
- Edited wiki header, upper case title.
=> Fortify not fortify

addons/common/functions/fnc_fixPosition.sqf
- title
Assigning @jonpas , because he wrote it.
=> simplify some code

addons/advanced_fatigue/stringtable.xml, addons/ai/stringtable.xml, addons/captives/stringtable.xml, addons/cargo/stringtable.xml, addons/fastroping/stringtable.xml, addons/hellfire/stringtable.xml, addons/interaction/stringtable.xml, addons/logistics_uavbattery/stringtable.xml, addons/markers/stringtable.xml, addons/maverick/stringtable.xml, addons/medical/stringtable.xml, addons/nlaw/stringtable.xml, addons/pylons/stringtable.xml, addons/quickmount/stringtable.xml, addons/rearm/stringtable.xml, addons/refuel/stringtable.xml, addons/repair/stringtable.xml, addons/slideshow/stringtable.xml, addons/spectator/stringtable.xml, addons/weaponselect/stringtable.xml, addons/weather/stringtable.xml, addons/zeus/stringtable.xml
Misfit text Modified, translate for 3.11
=> korean translation

addons/scopes/ACE_Settings.hpp, addons/scopes/RscTitles.hpp, addons/scopes/functions/fnc_showZeroing.sqf, addons/scopes/stringtable.xml
| Before  | After |
| ------------- | ------------- |
| ![before1wk9i](https://user-images.githubusercontent.com/9437207/32137734-e67eb1e6-bc25-11e7-9181-46b894e74b20.jpg) | ![after7mjid](https://user-images.githubusercontent.com/9437207/32137735-e960aafe-bc25-11e7-8a70-658c690e5208.jpg) |
=> Scopes - UI improvement

docs/wiki/frameworkx/sitting-framework.md
- Changed sitting framework group from "framework" to "frameworkx"
=> Sitting documentation fix 

docs/wiki/frameworkx/sitting-framework.md
Update header group.
- Revert group from "frameworkx" to "framework"
=> Sitting documentation fix

addons/scopes/functions/fnc_calculateZeroAngleCorrection.sqf, addons/scopes/functions/fnc_initModuleSettings.sqf
* Fixed typo in the module setting parsing (reference temperature was way off)
* Fixed bug in the zero angle calculator (muzzle velocity was off in most cases)
=> Scopes - Fixed bugs in the zero angle calculation

addons/quickmount/functions/fnc_getInNearest.sqf
ref @Dystopian / https://github.com/acemod/ACE3/pull/5630#discussion_r149043888
=> QuickMount - Use correct cargo index

addons/atragmx/functions/fnc_lookup_c1_ballistic_coefficient.sqf, addons/atragmx/functions/fnc_recalculate_muzzle_velocity.sqf
* Improved muzzle velocity table lookup speed
* Improved drag coefficient table lookup speed
=> ATragMX - Utilize 'linearConversion'

addons/overheating/functions/fnc_calculateCooling.sqf, addons/overheating/functions/fnc_firedEH.sqf
* Do not try to cool down an already cooled barrel
* Do not run the projectile direction update routine if we know that the max. possible deflection is less than 0.05 mrad.
=> Overheating - Minor performance tweaks

addons/logistics_wirecutter/script_component.hpp
=> Wirecutter - Fix net_fence_8m_f on malden

addons/maptools/ACE_Settings.hpp, addons/maptools/functions/fnc_drawLinesOnRoamer.sqf, addons/maptools/stringtable.xml
UTF BOM in xml removed accidentally.
=> Fix misprint in maptools

addons/fastroping/CfgVehicles.hpp, addons/map_gestures/CfgVehicles.hpp, addons/optionsmenu/stringtable.xml, addons/respawn/CfgVehicles.hpp, addons/vehiclelock/CfgVehicles.hpp
These aren't setting modules and shouldn't be disabled
=> Restore some modules set to scope = 1

addons/scopes/functions/fnc_showZeroing.sqf, addons/scopes/stringtable.xml
=> Scopes - Hide 'up' direction lettering

addons/captives/CfgWeapons.hpp, addons/dagr/CfgWeapons.hpp, addons/explosives/CfgWeapons.hpp, addons/flashlights/CfgWeapons.hpp, addons/hearing/CfgWeapons.hpp, addons/huntir/CfgWeapons.hpp, addons/logistics_uavbattery/CfgWeapons.hpp, addons/maptools/CfgWeapons.hpp, addons/medical/CfgWeapons.hpp, addons/spottingscope/CfgWeapons.hpp, addons/tacticalladder/CfgVehicles.hpp, addons/tripod/CfgWeapons.hpp
- Add or fix missing author entries so they show up properly in vanilla / ACE arsenal.
=> Add / Fix missing author entries

addons/map/CfgWeapons.hpp
=> Map - Allow the pistol flashlight to do illumination

addons/yardage450/functions/fnc_acquireTarget.sqf, addons/yardage450/functions/fnc_turnOn.sqf
* Utilize 'params' / 'selectMin' / 'selectMax'
=> Yardage 450 - Minor performance tweak

addons/refuel/CfgVehicles.hpp
=> Refuel - Remove fuel capability from IDAB water truck

addons/captives/stringtable.xml, addons/common/stringtable.xml, addons/cookoff/stringtable.xml, addons/finger/stringtable.xml, addons/goggles/stringtable.xml, addons/hitreactions/stringtable.xml, addons/interaction/stringtable.xml, addons/magazinerepack/stringtable.xml, addons/mk6mortar/stringtable.xml, addons/noradio/stringtable.xml, addons/overheating/stringtable.xml, addons/pylons/stringtable.xml, addons/rearm/stringtable.xml, addons/respawn/stringtable.xml, addons/scopes/stringtable.xml, addons/spectator/stringtable.xml, addons/switchunits/stringtable.xml, addons/vehiclelock/stringtable.xml, addons/weaponselect/stringtable.xml, addons/weather/stringtable.xml, addons/zeus/stringtable.xml
=> Update Chinese stringtable

addons/advanced_ballistics/functions/fnc_diagnoseWeapons.sqf, addons/advanced_ballistics/functions/fnc_initializeTerrainExtension.sqf, addons/advanced_ballistics/functions/fnc_readWeaponDataFromConfig.sqf
* Makes it easier to detect errors in 3rd party weapon compats
=> Advanced Ballistics - Better diagnostic tools

docs/wiki/framework/scopes-framework.md
=> Scopes - wiki/framework update

addons/laserpointer/functions/fnc_onDraw.sqf, addons/medical_ai/functions/fnc_isInjured.sqf, addons/overheating/functions/fnc_firedEH.sqf, addons/overheating/functions/fnc_overheat.sqf
* Medical_ai - Optimize 'fnc_isInjured'
* Laserpointer - Optimize 'fnc_onDraw'
* Overheating - firedEH: Skip ground detection if possible
* Overheating - firedEH: Replace function call with inline code
* Overheating - firedEH: Nest abort conditions
=> Minor performance tweaks

addons/advanced_ballistics/ACE_Settings.hpp, addons/advanced_ballistics/CfgVehicles.hpp, addons/advanced_ballistics/functions/fnc_diagnoseWeapons.sqf, addons/advanced_ballistics/functions/fnc_handleFired.sqf, addons/advanced_ballistics/functions/fnc_initModuleSettings.sqf, addons/advanced_ballistics/functions/fnc_readAmmoDataFromConfig.sqf, addons/advanced_ballistics/script_component.hpp, addons/advanced_ballistics/stringtable.xml, addons/ballistics/CfgAmmo.hpp, addons/scopes/functions/fnc_calculateZeroAngleCorrection.sqf, docs/wiki/framework/advanced-ballistics-framework.md, optionals/compat_r3f/CfgAmmo.hpp, optionals/compat_rhs_afrf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgAmmo.hpp
* Simulates slight variations in muzzle velocity between each shot
=> Advanced Ballistics - Muzzle velocity variation

addons/common/script_component.hpp
it was lost accidentally in #4895
=> Get compile cache back

addons/captives/XEH_postInit.sqf
=> Captives - Fix handcuff keybind distance check

addons/safemode/stringtable.xml
=> fix some Russian grammar

addons/medical/ACE_Settings.hpp
this only effected dev version
=> fix medical enableAdvancedWounds setting

AUTHORS.txt, addons/ballistics/CfgWeapons.hpp
Moderate version of: https://github.com/acemod/ACE3/pull/5755
* Updated rifle dispersion according to the data from @quickdagger: ![image](https://user-images.githubusercontent.com/9437207/33230151-890a35b6-d1de-11e7-83c2-78fd89a86e53.png)
=> Ballistics - Dispersion overhaul

addons/spectator/functions/fnc_compat_spectatorBI.sqf
=> Prevent virtual spectators falling into water

addons/winddeflection/ACE_Settings.hpp, addons/winddeflection/CfgVehicles.hpp, addons/winddeflection/functions/fnc_handleFired.sqf, addons/winddeflection/functions/fnc_initModuleSettings.sqf, addons/winddeflection/stringtable.xml
Similar to: https://github.com/acemod/ACE3/pull/5814
=> Wind Deflection - Removed 'simulationRadius' setting

addons/spectator/functions/fnc_ui.sqf
=> Remove some pp effects while in spectator

addons/rearm/stringtable.xml
=> remove duplicate japanese entry

addons/nightvision/stringtable.xml
=> Remove dash from NV category name

addons/arsenal/stringtable.xml, addons/movement/functions/fnc_handleVirtualMass.sqf
- Same as #5866 but for Arsenal
- Change enum error message formatting and version 1.78+
=> Remove dash from Arsenal category name

addons/zeus/functions/fnc_bi_moduleMine.sqf, addons/zeus/functions/fnc_bi_moduleProjectile.sqf, addons/zeus/functions/fnc_bi_moduleRemoteControl.sqf, addons/zeus/functions/fnc_getModuleDestination.sqf, addons/zeus/functions/fnc_handleZeusUnitAssigned.sqf, addons/zeus/functions/fnc_moduleAddOrRemoveFRIES.sqf, addons/zeus/functions/fnc_moduleAddSpareTrack.sqf, addons/zeus/functions/fnc_moduleAddSpareWheel.sqf, addons/zeus/functions/fnc_moduleCaptive.sqf, addons/zeus/functions/fnc_moduleConfigurePylons.sqf, addons/zeus/functions/fnc_moduleGlobalSetSkill.sqf, addons/zeus/functions/fnc_moduleGroupSide.sqf, addons/zeus/functions/fnc_moduleLoadIntoCargo.sqf, addons/zeus/functions/fnc_moduleSearchNearby.sqf, addons/zeus/functions/fnc_moduleSetMedic.sqf, addons/zeus/functions/fnc_moduleSetMedicalFacility.sqf, addons/zeus/functions/fnc_moduleSetMedicalVehicle.sqf, addons/zeus/functions/fnc_moduleSurrender.sqf, addons/zeus/functions/fnc_moduleUnconscious.sqf, addons/zeus/functions/fnc_moduleZeusSettings.sqf, addons/zeus/functions/fnc_ui_attributePosition.sqf, addons/zeus/functions/fnc_ui_groupSide.sqf, addons/zeus/functions/fnc_ui_toggleFlashlight.sqf, addons/zeus/functions/fnc_ui_toggleNvg.sqf
- Cleanup/optimise some of the zeus functions
- Update the vanilla functions to match latest arma version
=> Update vanilla zeus functions

addons/explosives/XEH_postInit.sqf, addons/explosives/XEH_preInit.sqf, addons/explosives/functions/fnc_setPosition.sqf
- appears to be no longer needed and be done by the game
requires: #5894
original fix: #3398
original bug report: #3317
Can no longer reproduce, even with this disabled.
=> remove obsolete mine jip synch

addons/cookoff/ACE_Settings.hpp
=> Add cookoff setting category

addons/scopes/functions/fnc_getBoreHeight.sqf, addons/scopes/functions/fnc_inventoryCheck.sqf
* Reverts the getBoreHeight API change from: https://github.com/acemod/ACE3/commit/91425f857682e2b69973c77120664cde117bc1d3
=> Rangecard - Fixes broken bore height display

addons/scopes/functions/fnc_inventoryCheck.sqf
Ref https://github.com/acemod/ACE3/pull/5907#discussion_r157117479
=> scopes - Fix base angle

addons/arsenal/functions/fnc_onSelChangedLeft.sqf, addons/arsenal/functions/fnc_onSelChangedRight.sqf, addons/arsenal/functions/fnc_updateRightPanel.sqf
- Weight is now indicated as follows: "kilos (lbs)".
=> Update how weight is displayed in ACE arsenal

addons/common/functions/fnc_getWeight.sqf, addons/movement/ACE_Settings.hpp, addons/movement/CfgEventHandlers.hpp, addons/movement/XEH_PREP.hpp, addons/movement/config.cpp, addons/movement/functions/fnc_inventoryDisplayLoad.sqf
=> display carried weight in SI and imperial

addons/nightvision/ACE_Settings.hpp, addons/nightvision/XEH_postInit.sqf, addons/nightvision/functions/fnc_pfeh.sqf, addons/nightvision/stringtable.xml
Adds an addition setting to scale the aim down sights blur
=> Nightvision - Add setting for blur when ADS

addons/arsenal/functions/fnc_onKeyDown.sqf
=> Arsenal numpad enter for search

docs/wiki/feature/nightvision.md, docs/wiki/framework/nightvision-framework.md
- Rewrite nightvision documentation to include the stNVG update.
=> Rewrite night vision documentation

docs/wiki/framework/atragmx.md
* Explains how to add custom gun list entries via config classes
=> Docs - Added ATragMX framework documentation

addons/common/functions/fnc_checkFiles.sqf, addons/medical/XEH_preInit.sqf, addons/medical/config.cpp
- correctly display `ace_extension_name_x64.dll` and `ace_extension_name.so` in error message
- do `ace_medical` check together with all the other ones
=> update extension check

docs/wiki/feature/arsenal.md
- Add feature documentation for ACE Arsenal, needs proofreading.
=> Arsenal feature doc

addons/frag/functions/fnc_fired.sqf
=> Ignore explosives placed without ace_explosives

addons/arsenal/ui/RscAttributes.hpp
- Fix various text elements using the default sizeEx values instead of pixelGrid
- Extend the weight control so it doesn't cut off at lower res
- include #5958
=> Fix some scaling issues in ACE Arsenal

.github/ISSUE_TEMPLATE.md
=> Fix debug info step in github issue template

docs/wiki/frameworkx/fortify-framework.md
=> Update fortify wiki with working example

addons/arsenal/XEH_PREP.hpp, addons/arsenal/XEH_postInit.sqf, addons/arsenal/defines.hpp, addons/arsenal/functions/fnc_handleLoadoutsSearchbar.sqf, addons/arsenal/functions/fnc_onKeyDown.sqf, addons/arsenal/functions/fnc_onLoadoutsClose.sqf, addons/arsenal/functions/fnc_onLoadoutsOpen.sqf, addons/arsenal/ui/RscAttributes.hpp
- Add a search bar for the loadouts screen
- Add keyDown support
- Ctrl+F to select the search bar
- Copy / cut / paste
- Ctrl + A
- Arrow keys to naviguate the content panel
#5965
=> Add QOL improvement for the ACE Arsenal loadouts screen

addons/rearm/functions/fnc_rearmEntireVehicle.sqf
Fix #5944
FUNC(rearmEntireVehicleSuccess) expected `_truck,_vehicle`
=> Rearm - Fix rearm entire vehicle arg order

AUTHORS.txt, addons/common/functions/fnc_player.sqf, addons/medical/functions/fnc_getCardiacOutput.sqf, addons/medical/functions/fnc_setCardiacArrest.sqf, addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/ACE_Settings.hpp, addons/medical_treatment/XEH_PREP.hpp, addons/medical_treatment/functions/fnc_calculateBlood.sqf, addons/medical_treatment/functions/fnc_treatment.sqf, addons/medical_treatment/functions/fnc_treatmentCPR.sqf, addons/medical_treatment/functions/fnc_treatmentCPR_failure.sqf, addons/medical_treatment/functions/fnc_treatmentCPR_progress.sqf, addons/medical_treatment/functions/fnc_treatmentCPR_start.sqf, addons/medical_treatment/stringtable.xml, addons/reloadlaunchers/functions/fnc_canLoad.sqf, addons/reloadlaunchers/functions/fnc_load.sqf, addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- Allow only one cpr at the time. You can not pump together at the same time.
- Improve cpr:
- Cpr will now create a pulse for the patient.
- When applying cpr to a patient with open wounds, the patient will bleed just as normal.
- IV's will flow as normal as long cpr is applied.
The CPR pulse is toggable by a setting. 
I consider this my 'fix' for reveiving people who got into hypovolemic shock as you can now apply IV's but they will only flow if you pump them in.
Requires #4960 to work.
=> [Medical Rewrite] Improved CPR

addons/tripod/script_component.hpp
=> disable debug mode

addons/explosives/functions/fnc_addCellphoneIED.sqf
- Implement my comment on #5963
=> Optimise cellphone IED function slightly

addons/medical/functions/fnc_handleRespawn.sqf
=> Fix unconscious hidden status not being reset on respawn

addons/repair/CfgVehicles.hpp
NATO quadbike was added in #2245, don't know why not all.
=> Add custom repair positions to all quadbikes

docs/Dockerfile, docs/Gemfile, docs/_config.yml, docs/_config_dev.yml, docs/docker-compose.yml, docs/entrypoint.sh
- Updates dockerfile and docker-compose file to current standards
- Use a different base image
=> Fix docker

addons/medical/ACE_Settings.hpp
@Lorenz94B
https://github.com/acemod/ACE3/issues/3594#issuecomment-354485276
=> Medical - Increase revive setting max to 60 min

docs/wiki/class-names.md
- Remove a classname that's no longer in use from the wiki
=> Removing unused classname from wiki

addons/arsenal/functions/fnc_initBox.sqf, addons/arsenal/functions/fnc_onArsenalOpen.sqf, addons/arsenal/functions/fnc_openBox.sqf
- Change "ok" text to "apply" while in 3DEN
- Move execNextFrame from the initBox ace interaction to openBox in order to avoid crashes with custom actions (most users wouldn't know that not using execNextFrame would result in a crash).
=> Minor arsenal fixes

addons/arsenal/missions/Arsenal.VR/script_component.hpp
=> fix make error

docs/wiki/development/coding-guidelines.md
- extends the header guidlines
- multiple input types
- default value(s)
=> Documentation: extending header guidelines

addons/arsenal/missions/Arsenal.VR/XEH_postInit.sqf
=> Enabled cancel button when exiting arsenal

addons/hellfire/CfgMagazines.hpp
=> Add ace hellfire support to rhs apaches

addons/spectator/functions/fnc_ui.sqf
Fixes a missing call to the spectator grenade handling
=> Fix a missing call to the spectator grenade handling

addons/pylons/functions/fnc_showDialog.sqf, docs/wiki/framework/pylons-framework.md
- Enable missionmakers to set a pylon "whitelist"
=> Add pylon whitelist option

addons/advanced_throwing/functions/fnc_canPrepare.sqf
=> Advanced Throwing - Disable when controlling UAV

addons/hearing/CfgWeapons.hpp
- Adds `ace_hearing_protection` and `ace_hearing_lowerVolume` to the new LOW headsets and ear protection
- Close #6105
=> Hearing: Add muffling to new LOW headsets

addons/advanced_ballistics/stringtable.xml, addons/arsenal/stringtable.xml, addons/ballistics/stringtable.xml, addons/common/stringtable.xml, addons/cookoff/stringtable.xml, addons/interaction/stringtable.xml, addons/markers/stringtable.xml, addons/maverick/stringtable.xml, addons/nightvision/stringtable.xml, addons/parachute/stringtable.xml, addons/realisticnames/stringtable.xml, addons/repair/stringtable.xml, addons/scopes/stringtable.xml
=> Chinese Language Update

docs/_includes/dependencies_list.md, tools/extract_dependencies.py
=> Sort directories before extracting dependency information

addons/hellfire/CfgAmmo.hpp
=> Decrease direct hit damage done by AGM-114N

addons/common/functions/fnc_isFeatureCameraActive.sqf, addons/huntir/functions/fnc_cam.sqf
=> HuntIR - Register as a feature cam (block NVG border)

addons/common/functions/fnc_cbaSettings_convertHelper.sqf, addons/vehiclelock/ACE_Settings.hpp, addons/vehiclelock/XEH_preInit.sqf, addons/vehiclelock/initSettings.sqf, addons/vehiclelock/stringtable.xml
Switch vehicleStartingLockState from slider to list
Close #6014
=> Vehicle Lock - Convert to cba settings

addons/interaction/functions/fnc_getVehiclePos.sqf, addons/interaction/functions/fnc_getVehiclePosComplex.sqf
=> Interaction - Fix div0 error in getVehiclePos

addons/hearing/ACE_Settings.hpp, addons/hearing/stringtable.xml, addons/medical/ACE_Settings.hpp, addons/medical/stringtable.xml, addons/medical_ai/ACE_Settings.hpp, addons/medical_ai/stringtable.xml, addons/medical_menu/ACE_Settings.hpp, addons/medical_menu/stringtable.xml, addons/nametags/ACE_Settings.hpp, addons/nametags/stringtable.xml, addons/repair/ACE_Settings.hpp, addons/repair/stringtable.xml
**This pull request will:**
- Add displayname (and description where applicable) to each addons `ACE_Settings.hpp` where they're missing.
- Add said displayname/description to each `stringtable.xml` (english only).
=> Settings strings

AUTHORS.txt, addons/medical/stringtable.xml
- fix some Korean translations on ACE3 medical's wounds
- add my nickname & e-mail to Authors.txt
=> Korean translations fix

docs/wiki/frameworkx/fortify-framework.md
Ref https://github.com/acemod/ACEX/pull/110
=> acex_fortify - add events to wiki

addons/common/XEH_postInit.sqf
=> fix empty return value of getUnitTrait

addons/arsenal/XEH_preStart.sqf, addons/arsenal/functions/fnc_addStat.sqf, addons/arsenal/functions/fnc_compileStats.sqf, addons/arsenal/functions/fnc_handleStats.sqf, addons/arsenal/functions/fnc_removeStat.sqf
Tag @Alganthe
Compiles the stats arrays on first use in a mission
Prevents stats added during one mission from having persistent effects
=> Arsenal - Compile stats on first use

addons/interact_menu/functions/fnc_addActionToObject.sqf
=> InteractionMenu - Always compile before adding main action

addons/map/initSettings.sqf
- Change BFT settings to be placed in subcategory under map settings
=> ace_map - BFT settings subcategory

addons/overheating/functions/fnc_canSwapBarrel.sqf
Closes: https://github.com/acemod/ACE3/issues/6169
=> Fix allowSwapBarrel condition

addons/arsenal/functions/fnc_compileStats.sqf, addons/arsenal/functions/fnc_handleStats.sqf, addons/arsenal/functions/fnc_onArsenalClose.sqf
- Fix an error in the face, voice, insignias tabs stats.
- Shorten handleStats a bit.
- Fix curatorCam being forced after ACE Arsenal is closed when a remote unit is used to access it instead of the modules.
=> Fix error in ACE Arsenal stats

addons/logistics_wirecutter/script_component.hpp
- Add support for wires on Prei Khmaoch Luong
=> Add support for Razor Wire on Prei Khmaoch Luong

addons/advanced_ballistics/stringtable.xml
- Fix french translation
- Added 2 french translation
=> Fix french translation

AUTHORS.txt, addons/medical/stringtable.xml
1. Update the portuguese translation of ACE3 Medical.
=> Fixes for portuguese translation of ACE medical

addons/medical/stringtable.xml
=> Fix german medical translation

addons/medical/functions/fnc_displayTriageCard.sqf, addons/medical_treatment/functions/fnc_treatmentFullHealLocal.sqf
=> Reset triage card on full heal

addons/cargo/CfgVehicles.hpp, addons/frag/CfgAmmo.hpp, addons/main/config.cpp, addons/main/script_mod.hpp, addons/realisticnames/CfgMagazines.hpp, addons/realisticnames/CfgWeapons.hpp, addons/rearm/CfgAmmo.hpp, addons/repair/CfgVehicles.hpp, addons/repair/XEH_preInit.sqf, addons/repair/functions/fnc_isInRepairFacility.sqf
=> Arma 1.82 compat

addons/hellfire/CfgWeapons.hpp
Inherit from RocketPods instead of scalpel which has changed
Fix #6256
=> Hellfire - Fix hellfires not showing after 1.82

addons/realisticnames/CfgWeapons.hpp
=> Realistic Names - Fix for pylon version of maverick

addons/javelin/CfgVehicles.hpp, addons/javelin/CfgWeapons.hpp
=> Fix titan on blufor LSV AT (1.82)

addons/rearm/script_component.hpp
Close #6177 #6075
Still want to look into using `ace_interaction_fnc_getInteractionDistance`, but this will work fine for now.
=> Rearm - Increase rearm distance check

addons/rearm/stringtable.xml, optionals/compat_adr_97/stringtable.xml
- fixed typo
- improved readability
- standardized expression
=> Japanese Translation Tweak

addons/mk6mortar/functions/fnc_canLoadMagazine.sqf, addons/mk6mortar/functions/fnc_canUnloadMagazine.sqf, addons/mk6mortar/functions/fnc_loadMagazine.sqf, addons/mk6mortar/functions/fnc_loadMagazineTimer.sqf, addons/mk6mortar/functions/fnc_unloadMagazineTimer.sqf
- fix #5671
- tested and all seams ok
=> Fixed mortar double loading

addons/interact_menu/functions/fnc_compileMenu.sqf, addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf, addons/interact_menu/functions/fnc_compileMenuZeus.sqf, addons/interact_menu/functions/fnc_createAction.sqf, addons/interact_menu/functions/fnc_renderIcon.sqf
- Add ability to modify action icon color without multiple icon files
- Quick demo: https://gfycat.com/SmoggySlimyGazelle
=> Interaction Menu - Ability to modify icon color

addons/arsenal/functions/fnc_statBarStatement_accuracy.sqf, addons/arsenal/functions/fnc_statBarStatement_rateOfFIre.sqf, addons/arsenal/functions/fnc_statTextStatement_accuracy.sqf, addons/arsenal/functions/fnc_statTextStatement_rateOfFire.sqf
- Apparently that's a thing, I also added param to the accuracy code, just in case.
=> Fix possible issue with weapons without firemodes in ACE Arsenal

addons/advanced_fatigue/stringtable.xml, addons/arsenal/stringtable.xml, addons/ballistics/stringtable.xml, addons/common/stringtable.xml, addons/explosives/stringtable.xml, addons/finger/stringtable.xml, addons/flashlights/stringtable.xml, addons/frag/stringtable.xml, addons/gforces/stringtable.xml, addons/hearing/stringtable.xml, addons/huntir/stringtable.xml, addons/interact_menu/stringtable.xml, addons/map/stringtable.xml, addons/map_gestures/stringtable.xml, addons/maverick/stringtable.xml, addons/medical/stringtable.xml, addons/medical_ai/stringtable.xml, addons/medical_menu/stringtable.xml, addons/missileguidance/stringtable.xml, addons/mx2a/stringtable.xml, addons/nametags/stringtable.xml, addons/nightvision/stringtable.xml, addons/overpressure/stringtable.xml, addons/pylons/stringtable.xml, addons/quickmount/stringtable.xml, addons/realisticnames/stringtable.xml, addons/repair/stringtable.xml, addons/zeus/stringtable.xml
=> Translations-  Chinese: Modify grammar

addons/vehicles/XEH_postInit.sqf, addons/vehicles/functions/fnc_speedLimiter.sqf, addons/vehicles/script_component.hpp, addons/vehicles/stringtable.xml
- Add two keybinds for increasing and decreasing the speed limiter limit by 1 kmh each step
- Default bound to `Ctrl + Mouse Wheel Scroll Up & Down`
=> Vehicles - Set speed limited with mouse scroll wheel

addons/disposable/CfgMagazines.hpp
=> Disposable - Fix nlaw picture popup error

addons/medical/ACE_Settings.hpp
- Fix settings in medical-rewrite-(restructure)
=> Fix settings in medical rewrite

addons/medical_engine/functions/fnc_handleDamage.sqf
- Add in a way to disable damage (backwards compatible with the old variable method, also supports new `isDamageAllowed` command)
=> Add support to toggle allowDamage

addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
- Fix duplicate entry in HandleUnitVitals and change it to heartRate > 220
=> Fix duplicate entry

addons/arsenal/functions/fnc_onSelChangedLeft.sqf, addons/arsenal/functions/fnc_scanConfig.sqf
- Remove unnecessary itemInfo check in scanConfig 
- Change onSelChangedLeft to use global variant of addWeapon and addBackpack
=> Arsenal - Fix locality issue for adding weapons/backpacks and remove unnecessary check in scanConfig

addons/medical/functions/fnc_dev_watchMedicalStats.sqf, addons/medical_engine/script_macros_medical.hpp, addons/medical_gui/functions/fnc_displayPatientInformation.sqf, addons/medical_gui/functions/fnc_modifyAction.sqf, addons/medical_gui/functions/fnc_updateUIInfo.sqf, addons/medical_status/functions/fnc_getBloodLoss.sqf, addons/medical_status/functions/fnc_getBloodVolumeChange.sqf, addons/medical_status/functions/fnc_initUnit.sqf, addons/medical_status/functions/fnc_isBeingCarried.sqf, addons/medical_status/functions/fnc_isBeingDragged.sqf, addons/medical_status/functions/fnc_isInStableCondition.sqf, addons/medical_treatment/functions/fnc_canAccessMedicalEquipment.sqf, addons/medical_treatment/functions/fnc_canTreatCached.sqf, addons/medical_treatment/functions/fnc_handleBandageOpening.sqf, addons/medical_treatment/functions/fnc_hasItem.sqf, addons/medical_treatment/functions/fnc_hasTourniquetAppliedTo.sqf, addons/medical_treatment/functions/fnc_healTime.sqf, addons/medical_treatment/functions/fnc_isInMedicalFacility.sqf, addons/medical_treatment/functions/fnc_isInMedicalVehicle.sqf, addons/medical_treatment/functions/fnc_isMedic.sqf, addons/medical_treatment/functions/fnc_treatmentBandage.sqf, addons/medical_treatment/functions/fnc_treatmentFullHeal.sqf, addons/medical_treatment/functions/fnc_treatmentFullHealLocal.sqf, addons/medical_treatment/functions/fnc_treatmentMedicationLocal.sqf, addons/medical_treatment/functions/fnc_treatmentTourniquet.sqf, addons/medical_treatment/functions/fnc_treatmentTourniquetLocal.sqf, addons/medical_treatment/functions/fnc_treatmentTourniquetRemove.sqf, addons/medical_treatment/functions/fnc_useItems.sqf, addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
Cleaning up some confusing bits and pieces.
=> Minor code clean up

addons/medical_menu/XEH_postInit.sqf
=> Medical Menu - Check cursorObject if cursorTarget is invalid

addons/arsenal/functions/fnc_buttonLoadoutsLoad.sqf, addons/arsenal/functions/fnc_onArsenalOpen.sqf
- Apparently terminals are simulation `Weapon` instead of `ItemGps` now
=> Arsenal - Fix terminals not being properly added to currentItems

addons/main/script_mod.hpp
- Title
Because of that `getFov` issue and newer version should be used anyways.
=> Bump required Arma 3 version to 1.84 and CBA to 3.8.0

addons/realisticnames/stringtable.xml
=> Fix Japanese stringtable

docs/wiki/frameworkx/fortify-framework.md
Depends on [acex PR #124](https://github.com/acemod/ACEX/pull/124/)
- Add docs for custom deploy handlers
- Add docs for local event on deploy start
=> Wiki - ACEX fortify #124 documentation

docs/wiki/user/installation-guide.md
=> Remove play with six launch method

optionals/nouniformrestrictions/CfgVehicles.hpp
=> Update No Uniform Restrictions for Arma 3 v1.84

optionals/compat_rhs_gref3/CfgMagazines.hpp, optionals/compat_rhs_gref3/CfgWeapons.hpp, optionals/compat_rhs_gref3/config.cpp
=> RHS GREF Compat - MG42

addons/advanced_fatigue/XEH_postInit.sqf, addons/advanced_fatigue/initSettings.sqf
=> don't hide stamina twice when changing the setting

optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
- title.
SPG-9, Kornet and M252 have too weird interaction points so we should fix them.
=> RHS Compat - Fix static turrets interaction point

addons/advanced_ballistics/functions/fnc_diagnoseWeapons.sqf, addons/arsenal/functions/fnc_addVirtualItems.sqf, addons/arsenal/functions/fnc_scanConfig.sqf, addons/common/functions/fnc_getItemType.sqf, addons/explosives/CfgWeapons.hpp, addons/main/script_macros.hpp
- title.
These macros are used: https://github.com/acemod/ACE3/blob/2767fddd92bd48199ba580601dd148f77e001f00/addons/main/script_macros.hpp#L65-L68
=> Fix some item type magic numbers

optionals/compat_rhs_gref3/CfgVehicles.hpp, optionals/compat_rhs_gref3/config.cpp
- Fix RHS GREF canoes so that they cannot receive fuel
- Add authors
=> RHS Compat - Fix GREF canoes refuel interaction

addons/medical/functions/fnc_setUnconscious.sqf
- close #6506 
- implementation of fix by severgun
=> make setUnconscious not reset firing mode

tools/sqf_validator.py
=> sqf_validator compatibility with findIf command

addons/zeus/functions/fnc_bi_moduleProjectile.sqf
=> Zeus - fix script error fnc_bi_moduleProjectile

tools/sqf_validator.py
ugly, but the test is failing valid code, so best to disable for now
=> Skip semi-colon test with findIf

addons/explosives/functions/fnc_interactEH.sqf, addons/logistics_wirecutter/script_component.hpp
- title, missed these in the original PR
=> Convert CBA_fnc_uniqueUnitItems to common uniqueItems function

docs/wiki/development/arma-3-scheduler-and-our-practices.md, docs/wiki/development/documentation-guidelines-and-tips.md, docs/wiki/development/how-to-translate-ace3.md, docs/wiki/development/index.html, docs/wiki/development/modularity-and-pbo-structure.md, docs/wiki/development/setting-up-the-development-environment.md, docs/wiki/feature/dagr.md, docs/wiki/feature/fastroping.md, docs/wiki/feature/interact-menu.md, docs/wiki/feature/spotting-scope.md, docs/wiki/feature/tacticallader.md, docs/wiki/framework/atragmx-framework.md, docs/wiki/user/ace3-and-acex.md, docs/wiki/user/how-to-make-a-feature-request.md, docs/wiki/user/how-to-report-an-issue.md
=> Consitently capitalize first letters of wiki titles

addons/vehicles/functions/fnc_startEngine.sqf
- fixes: https://gfycat.com/FlimsyHealthyGreendarnerdragonfly
=> fix engine start delay turning viv laoded vehicle when starting the engine

addons/arsenal/functions/fnc_attributeInit.sqf, addons/arsenal/functions/fnc_initBox.sqf
=> Arsenal - Fix attribute blacklist not working in multiplayer

addons/nightvision/CfgWeapons.hpp
- Fix #6535
- Make all overlays for ENVGs the same for consistency
=> Fix ENVG II overlay

addons/cargo/functions/fnc_startLoadIn.sqf, addons/cargo/functions/fnc_startUnload.sqf, addons/cargo/initSettings.sqf, addons/cargo/stringtable.xml
- title
- flag paradrop setting as `canBeChanged`
=> Cargo - Add load time coefficient setting

addons/common/functions/fnc_lightIntensityFromObject.sqf
```
class ACE_acc_pointer_green: ACE_acc_pointer_red {
ACE_laserpointer = 2;
```
=> Common - disable light from green weap lasers

addons/explosives/functions/fnc_setupExplosive.sqf, addons/interaction/RscTitles.hpp, addons/interaction/functions/fnc_hideMouseHint.sqf, addons/interaction/functions/fnc_showMouseHint.sqf, addons/interaction/script_component.hpp
- Improve spacing of mouse hint
- Change font of extra icon sets
- Before: 
- After:
=> Interaction - Improve mouse hint

addons/goggles/functions/fnc_externalCamera.sqf
=> Goggles - Fix `Show Goggle Effects in Third Person` setting

addons/logistics_wirecutter/script_component.hpp
- add three more fences from CUP-Core, to be cut down with Ace-Wirecutter.
=> Wirecutters - Add compatibility with more fences from CUP

optionals/compat_rhs_afrf3/CfgWeapons.hpp, optionals/compat_rhs_gref3/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgWeapons.hpp
=> RHS Compats - Update allowSwapBarrels for some guns

tools/sqf_validator.py
=> Revert "Support # command in SQF Validator "

docs/wiki/feature/aircraft.md
=> Wiki - Update feature list for ace_aircraft (ah9 hud)

.github/CONTRIBUTING.md
Expand our contributing.md file with:
- A mention of our PR process 
- where to go for assistance.
- What issue labels we use for getting help.
=> Expand contributing docs

docs/team.md
- Add @654wak654 to the list of maintainers on our team page.
=> add 654wak654 as maintainer

addons/arsenal/functions/fnc_addVirtualItems.sqf
Thanks @Dystopian
https://github.com/acemod/ACE3/pull/6694/files#r234542372
=> Arsenal - Fix script error from hide changes

addons/microdagr/functions/fnc_updateDisplay.sqf
=> MicroDagr - Fix waypoint scrolling

addons/arsenal/stringtable.xml, addons/cargo/stringtable.xml, addons/chemlights/stringtable.xml, addons/explosives/stringtable.xml, addons/interaction/stringtable.xml, addons/microdagr/stringtable.xml, addons/optionsmenu/stringtable.xml, addons/quickmount/stringtable.xml, addons/realisticnames/stringtable.xml, addons/rearm/stringtable.xml, addons/zeus/stringtable.xml
- Update translations for Japanese
- fix the miss translations
=> Update Japanese translations

addons/chemlights/CfgMagazines.hpp
- add back the original class for bwc
- inherits the new one
- closes #6707 and closes #6716
=> Add bwc class name for orange chemlight, close #6707, close #6716

circle.yml
=> add sqflint to circleci

docs/docker-compose.yml, docs/entrypoint.sh
=> Fix Docker again

addons/interaction/functions/fnc_openDoor.sqf
=> Interaction - Disable open door action on houses with no user actions

addons/medical/functions/fnc_actionLoadUnit.sqf, addons/medical/stringtable.xml
=> Medical - Add vehicle hint when loading unconc

addons/medical/functions/fnc_displayPatientInformation.sqf
=> Medical - Skip distance check if in same vehicle

addons/cookoff/stringtable.xml
=> remove the only entry of "Original" and replace it by "English"

addons/goggles/config.cpp
=> Goggles - Add entries for APEX/Laws of War facewear

addons/rearm/CfgAmmo.hpp, addons/rearm/XEH_PREP.hpp, addons/rearm/XEH_postInit.sqf, addons/rearm/functions/fnc_addRearmActions.sqf, addons/rearm/functions/fnc_getCaliber.sqf, addons/rearm/functions/fnc_getMagazineName.sqf, addons/rearm/functions/fnc_readSupplyCounter.sqf, addons/rearm/functions/fnc_rearm.sqf, addons/rearm/functions/fnc_rearmSuccessLocal.sqf, addons/rearm/functions/fnc_storeAmmo.sqf, addons/rearm/functions/fnc_takeAmmo.sqf
Close #6414
Also fix missing caliber for B_20mm_AP
=> Rearm - Use non-ambigious magazine names

addons/pylons/XEH_postInit.sqf
- Update configure pylons action to use `addActionToClass` instead of `addActionToObject` with `CBA_fnc_addClassEventHandler`
- Only use `createAction` once
- Update action condition to use `findIf` instead of `count` for checking rearm vehicles (should provide small performance benefit)
=> Pylons - Update configure pylons action

addons/ballistics/CfgWeapons.hpp
- keeps 100Rnd mags magwell for all MX variants after this CBA PR: https://github.com/CBATeam/CBA_A3/pull/1058
=> add 100Rnd mags magwell to all MX variants

addons/advanced_ballistics/CfgEventHandlers.hpp, addons/atragmx/CfgEventHandlers.hpp, addons/attach/CfgEventHandlers.hpp, addons/concertina_wire/CfgEventHandlers.hpp, addons/dagr/CfgEventHandlers.hpp, addons/flashlights/CfgEventHandlers.hpp, addons/hearing/CfgEventHandlers.hpp, addons/huntir/CfgEventhandlers.hpp, addons/kestrel4500/CfgEventHandlers.hpp, addons/maptools/CfgEventHandlers.hpp, addons/microdagr/CfgEventHandlers.hpp, addons/minedetector/CfgEventHandlers.hpp, addons/overheating/CfgEventHandlers.hpp, addons/rangecard/CfgEventHandlers.hpp, addons/recoil/CfgEventHandlers.hpp, addons/reload/CfgEventHandlers.hpp, addons/switchunits/CfgEventHandlers.hpp, addons/tacticalladder/CfgEventHandlers.hpp, addons/tripod/CfgEventHandlers.hpp, addons/yardage450/CfgEventHandlers.hpp
match expected pattern in https://github.com/CBATeam/CBA_A3/pull/1056/files
=> Cleanup spacing on call COMPILE_FILE

addons/cargo/XEH_postInit.sqf, addons/cargo/XEH_preStart.sqf
2.7 out of 10.8 seconds postInit.. ugh..
=> Cargo - Cache cargo vehicle classes

addons/tagging/XEH_postInit.sqf, addons/tagging/XEH_preStart.sqf
=> Tagging - Cache tagging static models

optionals/nouniformrestrictions/CfgVehicles.hpp
=> Update No Uniform Restrictions for Arma 3 v1.88

addons/repair/functions/fnc_repair.sqf
=> Repair - Add condition check to progressBar

addons/main/script_mod.hpp
- Title
No Uniform Restrictions got updated for 1.88.
=> Increase required Arma 3 version to 1.88

addons/arsenal/functions/fnc_scanConfig.sqf, addons/dagr/functions/fnc_menuInit.sqf, addons/gforces/functions/fnc_pfhUpdateGForces.sqf, addons/hearing/functions/fnc_putInEarplugs.sqf, include/x/cba/addons/main/$PBOPREFIX$, include/x/cba/addons/xeh/$PBOPREFIX$
Minor things that I fell into when testing the script compiler.
These actually triggered bugs in sqf-vm, but they are either really a bug, or just style problems.
=> Trivial code fixes

addons/medical/stringtable.xml
Updated <Portuguese> values for the Saline quantity.
(Every Saline was 1000mL)
=> Translations - Portuguese

addons/arsenal/stringtable.xml, addons/fastroping/stringtable.xml, addons/markers/stringtable.xml, addons/medical/stringtable.xml, addons/zeus/stringtable.xml
=> Translations - Polish

docs/wiki/frameworkx/field-rations-framework.md
=> Wiki - Add field rations documentation

addons/vehicles/stringtable.xml
=> hideEjectAction - Polish translation

addons/medical_treatment/functions/fnc_actionLoadUnit.sqf, addons/medical_treatment/stringtable.xml
- Medical rewrite recitfy: removes label from #6759
=> Rewrite rectify. Medical - Add vehicle hint when loading unconscious

addons/medical_gui/functions/fnc_displayPatientInformation.sqf
- Medical rewrite rectify: Removes label from #6757
=> Rewrite rectify - Skip distance check if in same vehicle

addons/medical_treatment/ACE_Settings.hpp, addons/medical_treatment/functions/fnc_checkItems.sqf, addons/medical_treatment/stringtable.xml
- Rewrite rectify: Adding option to convert vanilla medical gear #6680
=> Rewrite rectify convert option

optionals/compat_rhs_usf3/CfgWeapons.hpp
=> RHS Compat - Update hearing configs values for helmets

addons/medical_feedback/XEH_preInit.sqf
- Fix the pain effects which were no longer appearing due to effect type variable being Nil after moving the setting to SQF
=> Medical rewrite - Fix pain effects no longer appearing

addons/medical_gui/functions/fnc_canOpenMenu.sqf
- Title
- Partially ~~fixes~~ #6913
=> Prevent opening the medical menu if the player is unconscious

addons/arsenal/XEH_preInit.sqf
- see: https://github.com/CBATeam/CBA_A3/pull/1105
=> compatibility with CBA scripted 2d optics framework

addons/interaction/functions/fnc_canPassMagazine.sqf, addons/medical_engine/script_component.hpp, addons/overheating/functions/fnc_overheat.sqf
- pass mag (if weapon == "" then CBA_fnc_compatibleMagazines will throw warning
- med-engine - add ace tag to debug line
- overheat, `_energyIncrement ` would be nil on first run because of inner private
=> Fix trivial bugs

addons/arsenal/functions/fnc_verifyLoadout.sqf
=> [ACE Arsenal] Fix NVGs not being subject to blacklisting in loadouts

addons/arsenal/XEH_preInit.sqf
- title
- also change 2doptics -> optics
=> compatibility with CBA disposable framework

addons/refuel/functions/fnc_dropNozzle.sqf
=> Refuel - Drop nozzle at unit's feet if no valid pos found

addons/fcs/XEH_postInit.sqf, addons/fcs/functions/fnc_vehicleInit.sqf
Don't add fired event handlers unless we need them
=> FCS - Skip adding firedEH until needed

addons/winddeflection/config.cpp
=> remove weather dependancy from winddeflection

addons/rearm/functions/fnc_setTurretMagazineAmmo.sqf
- Fix rearming for vehicles using magazine wells, for example GM's Leopard 1
- Remove some unnecessary whitespace, I guess
Thanks @madpat3 for the report.
=> Fix rearming for vehicles using magazine wells

addons/spectator/ACE_Settings.hpp, addons/spectator/XEH_preInit.sqf, addons/spectator/functions/fnc_ui_handleMouseZChanged.sqf, addons/spectator/initSettings.sqf, addons/spectator/stringtable.xml
- title, #6986 
- Convert other settings to use `CBA_settings_fnc_init`
=> Spectator - Add setting for follow camera max distance

addons/medical_feedback/XEH_preInit.sqf
- Pointed out by https://github.com/acemod/ACE3/issues/6452#issuecomment-409697516
=> Fix volume level of max injury sounds

circle.yml
- Title - Using acemod/armake, it is already installed.
=> Remove pygithub installation from CircleCI

addons/medical_feedback/XEH_postInit.sqf
Was this the only problem with turrets?
#6913 
>Fix unconscious UI effects in copilot camera / turrets.
=> Medical - Exit turret gunner view when going unconscious

addons/grenades/CfgMagazineWells.hpp
=> Add vanilla magwells for 40mm grenades

addons/medical/stringtable.xml
@Drofseh
- correct the misspelling
=> Fractures is misspelled

docs/src/package-lock.json, docs/src/package.json
- Update grunt and all dependencies
- `npm audit` -> all fixed
dependabot failed to do it on his own. :-1:
=> Fix js-yaml vulnerability

addons/medical_treatment/functions/fnc_ivBagLocal.sqf, addons/medical_treatment/functions/fnc_medication.sqf
=> Medical Treatment - Fix medication and ivBagLocal typos

addons/medical_treatment/ACE_Medical_Facilities.hpp, addons/medical_treatment/Cfg3DEN.hpp, addons/medical_treatment/XEH_preInit.sqf, addons/medical_treatment/config.cpp
- title, https://github.com/acemod/ACE3/pull/6933#discussion_r274387363
=> Medical Treatment - Add medical facility classes config

addons/common/functions/fnc_isEOD.sqf
=> Common - Let isEOD handle non bools

addons/cargo/XEH_preInit.sqf, addons/cargo/functions/fnc_paradropItem.sqf
=> Cargo - Add array to disable paradrop effects

addons/main/config.cpp, addons/main/script_mod.hpp
- Title
**Merge after 1.94 releases!**
=> Update Load Order for 1.94 Contact DLC

docs/wiki/development/setting-up-the-development-environment.md
- Add disable of 'rebuild requiredAddons' in Mikero tools
- Remove DeRap as a requirement
- Simplify Arma 3 Tools and P-drive (obviously has to be 'properly' set up)
=> Update development environment requirements

addons/common/functions/fnc_disableUserInput.sqf, addons/common/functions/fnc_setDisableUserInputStatus.sqf, addons/medical/functions/fnc_adjustPainLevel.sqf, addons/medical/functions/fnc_setUnconscious.sqf, addons/medical_engine/script_macros_medical.hpp, addons/medical_feedback/XEH_postInit.sqf, addons/medical_statemachine/functions/fnc_handleStateUnconscious.sqf, addons/medical_status/functions/fnc_adjustPainLevel.sqf, addons/medical_status/functions/fnc_isInStableCondition.sqf, addons/medical_status/functions/fnc_setCardiacArrest.sqf, addons/medical_status/functions/fnc_setUnconscious.sqf, addons/medical_treatment/XEH_preInit.sqf, addons/medical_treatment/functions/fnc_fullHealLocal.sqf, addons/medical_treatment/functions/fnc_treatment.sqf
Trying to track down bugs with unconsciousness (not sure if related)
- Unit fails to trigger wakeUp events when stable
- Full heal leaves unit semi-unconsciousness (locked input)
=> Medical - Various debugging and fix cpr anim speed

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/functions/fnc_canStitch.sqf, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
- Add self stitching setting for medical rewrite.
=> Add self stitching setting

docs/wiki/framework/cargo-framework.md
=> Wiki - Update "ace_cargo_fnc_loadItem" arguments

.github/ISSUE_TEMPLATE/bug_report.md
=> Fix Bug report issue template

addons/medical_treatment/functions/fnc_splintLocal.sqf, addons/medical_treatment/stringtable.xml
Adds activity log entry for applying splints
=> Medical Treatment - Add logging for splints

addons/medical/dev/watchVariable.sqf, addons/medical_treatment/ACE_Medical_Treatment.hpp, addons/medical_treatment/functions/fnc_findMostEffectiveWound.sqf
-  Switch BP in watchVariable to the standard order
- Correct Elastic Effectiveness on abrasionMinor (43 to 4)
- Correct incorrect selection of elements in findMostEffectiveWound
=> Medical - Minor fixes

addons/medical_treatment/functions/fnc_canCPR.sqf, addons/medical_treatment/stringtable.xml
- title, add description of how this setting affects the visibility of the CPR action
=> Medical Treatment - Expand advanced diagnose setting tooltip

addons/laserpointer/CfgJointRails.hpp
Ref: https://github.com/CBATeam/CBA_A3/pull/1235#issuecomment-537182256
Fixes #7182
=> Laserpointer - Add vanilla Joint Rails

addons/reload/functions/fnc_checkAmmo.sqf
=> Fix undefined variable in reload checkAmmo function

addons/chemlights/stringtable.xml
=> Add missing German translation for chemlights

addons/common/scripts/checkVersionNumber.sqf
=> Common - Log checkPBO errors to server log

addons/medical_treatment/ACE_Medical_Treatment.hpp, addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/CfgVehicles.hpp, addons/medical_treatment/CfgWeapons.hpp
- Remove atropine
As per decided, atropine has been commented out for the moment, I feel that deleting the entries would just create more work later when we decide to add it back.
=> Remove Atropine

addons/medical_treatment/CfgWeapons.hpp
=> Change medical item masses to be same as old medical

addons/medical/stringtable.xml
=> Medical - Add descriptions for limping and fracture settings

addons/dragging/CfgMovesMaleSdr.hpp, addons/dragging/config.cpp, addons/dragging/functions/fnc_startCarry.sqf
- Speed up the carry animation from 15 to 10 seconds
10 seconds feels quite natural, I tried it even faster (8s) and it looked wrong.
=> Speed up carry animation

.github/workflows/arma.yml, circle.yml, docs/wiki/feature/dragon.md, tools/search_privates.py, tools/search_undefinedFunctions.py, tools/search_unused_privates.py, tools/sqf_linter.py
=> Add Arma CI Workflow (validate, lint, build)

addons/medical/XEH_postInit.sqf, addons/medical/dev/reportSettings.sqf
```
[ACE] (medical) INFO: -- Checking 48 medical Settings --
ace_medical_spontaneousWakeUpChance: [Current 0.0828254] [Default: 0.05]
```
=> Medical - Report non-default settings to rpt

addons/medical/functions/fnc_addDamageToUnit.sqf, addons/medical_engine/functions/fnc_handleDamage.sqf, addons/overpressure/functions/fnc_firedEHBB.sqf, addons/overpressure/functions/fnc_overpressureDamage.sqf
Fix blackblast having no effect from #7214
=> Medical - Fix addDamageToUnit

optionals/nouniformrestrictions/CfgVehicles.hpp
=> Update No Uniform Restrictions for vanilla 1.92-1.96

addons/explosives/functions/fnc_dialingPhone.sqf, addons/hot/functions/fnc_attackProfile_WIRE.sqf, addons/tagging/functions/fnc_tag.sqf
- Adhere to the new 5x sound limit in MP with playsound3d
I've bumped the ranges on some of the sounds to counter the volume lowering. I've not tested it in-game, just used some guess work on the numbers.
=> Fixing playsound3d limits

addons/advanced_ballistics/stringtable.xml, addons/advanced_fatigue/stringtable.xml, addons/advanced_throwing/stringtable.xml, addons/finger/stringtable.xml, addons/spectator/stringtable.xml, addons/switchunits/stringtable.xml, addons/tagging/stringtable.xml, addons/trenches/stringtable.xml, addons/ui/stringtable.xml, addons/vehicles/stringtable.xml, addons/weaponselect/stringtable.xml, addons/weather/stringtable.xml, addons/zeus/stringtable.xml
Add more Czech translations to:
addons/advanced_ballistics/stringtable.xml
addons/advanced_fatigue/stringtable.xml
addons/advanced_throwing/stringtable.xml
addons/finger/stringtable.xml
addons/spectator/stringtable.xml
addons/switchunits/stringtable.xml
addons/tagging/stringtable.xml
addons/trenches/stringtable.xml
addons/ui/stringtable.xml
addons/vehicles/stringtable.xml
addons/weaponselect/stringtable.xml
addons/weather/stringtable.xml
addons/zeus/stringtable.xml
=> Add Czech translation

addons/kestrel4500/functions/fnc_createKestrelDialog.sqf, addons/kestrel4500/functions/fnc_displayKestrel.sqf
- Update the hardcoded layer id to dynamic id
- Tested with ACE-Dev and DUI Squad Radar
Solves https://github.com/CBATeam/CBA_A3/issues/1193, and possibly other issues .....
All credits to @commy2
=> [kestrel_4500] Update hardcoded layer id

addons/trenches/functions/fnc_continueDiggingTrench.sqf, addons/trenches/functions/fnc_removeTrench.sqf
=> Trenches - Add item check to progressBar

addons/arsenal/stringtable.xml, addons/cargo/stringtable.xml, addons/csw/stringtable.xml, addons/dragon/stringtable.xml, addons/grenades/stringtable.xml, addons/hot/stringtable.xml, addons/markers/stringtable.xml, addons/medical/stringtable.xml, addons/rearm/stringtable.xml, addons/zeus/stringtable.xml
Adding and update trad chinese string
=> Add\Update Trad Chinese Translate

README.zh-TW.md, addons/ballistics/stringtable.xml, addons/chemlights/stringtable.xml, addons/common/stringtable.xml, addons/cookoff/stringtable.xml, addons/csw/stringtable.xml, addons/explosives/stringtable.xml, addons/fastroping/stringtable.xml, addons/flashsuppressors/stringtable.xml, addons/interaction/stringtable.xml, addons/medical_ai/stringtable.xml, addons/medical_blood/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_gui/stringtable.xml, addons/medical_statemachine/stringtable.xml, addons/medical_status/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/microdagr/stringtable.xml, addons/mk6mortar/stringtable.xml, addons/quickmount/stringtable.xml, addons/realisticnames/stringtable.xml, addons/repair/stringtable.xml, addons/spectator/stringtable.xml, addons/vehicles/stringtable.xml
i check every folder,seem didn't miss one,if miss comment below please
-add missing chinese string
-fix some werid string(not too much)
-make most unit(like mm,m)to chinese
=> Add tchinese translation,for almost every stringtable i can find

addons/flashlights/stringtable.xml
=> Polish translation for Maglite ML300L

Makefile, docs/README.zh-TW.md, tools/make.py
putting it next to pl and de readmes
I guess we could move them to base folder, but it should just be consistent
=> Move readme to doc folder and use versioning system

addons/arsenal/functions/fnc_addDefaultLoadout.sqf
- Fix default loadouts public function not checking for base items.
close #7275
=> Arsenal - Fix default loadout public func not checking base items

tools/stringtable_validator.py
- Check files (and print output) in alphabetical order
- Fix printing file error count when parsing failed
- Improve wording on multiple keys error
=> Stringtable validator improvements

addons/dragging/CfgEventHandlers.hpp, addons/interact_menu/XEH_preInit.sqf, addons/interact_menu/functions/fnc_compileMenu.sqf
Fix #7248
Skip adding inherited CaManBase actions to VirtualMan_F
Exclude from Dragging
=> Interact Menu - Don't show interactions for virtual units

AUTHORS.txt, addons/cargo/config.cpp, addons/cargo/functions/fnc_setSpace.sqf
- Modifies ace_cargo_fnc_setSpace to check for cargo already in the vehicle and set the total space, rather than the remaining space
Fixes #7131
=> Cargo - setSpace checks for existing cargo

addons/medical_ai/functions/fnc_healingLogic.sqf
-Allows AI to deal with wounded in the cardiac arrest state. 
-Refines AI usage of blood IV's to minimise wastage.
=> Medical AI - Improve Healing Logic

addons/medical_treatment/functions/fnc_bodyCleanupLoop.sqf
=> Medical Treatment - Fix bodyCleanupLoop typo

docs/wiki/feature/vehicles.md
- add documentation for prevent auto engine shut-off.
=> Add documentation for prevent auto shut-off

AUTHORS.txt, addons/goggles/CfgVehicles.hpp, addons/goggles/XEH_PREP.hpp, addons/goggles/XEH_postInit.sqf, addons/goggles/XEH_preInit.sqf, addons/goggles/config.cpp, addons/goggles/functions/fnc_canWipeGlasses.sqf, addons/goggles/initSettings.sqf, addons/goggles/stringtable.xml
- Wipe glasses self interaction
- Toggleable via settings (default: false)
=> Add Wipe glasses self interaction

docs/_posts/2019-12-18-medical-rewrite.md
=> Add Medical Rewrite post

addons/common/XEH_postInit.sqf
- Fix regression from #7173 
`[ACE] (common) INFO: Updating ACE from [3.12.6.43] to []`
=> Fix version comparison (CBA Settings transfer)

addons/common/stringtable.xml, addons/switchunits/stringtable.xml
=> Update tchinese translate

addons/medical_treatment/stringtable.xml
like title.
-make all bandage name on tch look like : bandage (%Type) 
-make all iv name on tch look live :IV(%Type %amount)
-fix some string or make it smooth on grammar
=> [Tchinese]Medical - Group Bandage&IV Items 

addons/arsenal/XEH_preInit.sqf
=> Arsenal - Register feature camera

addons/ai/CfgEventHandlers.hpp, addons/ai/XEH_PREP.hpp, addons/ai/functions/fnc_drawCuratorGarrisonPathing.sqf, addons/ai/functions/fnc_initDisplayCurator.sqf
=> AI - Pass function by reference to Draw3D EH

addons/tagging/ACE_Settings.hpp, addons/tagging/XEH_preInit.sqf, addons/tagging/initSettings.sqf
edit: this moves it to a subcategory to reduce clutter (it's only a single setting)
=> Tagging - Convert to CBA Settings

addons/advanced_throwing/stringtable.xml, addons/artillerytables/initSettings.sqf, addons/artillerytables/stringtable.xml, addons/ballistics/stringtable.xml, addons/chemlights/stringtable.xml, addons/common/stringtable.xml, addons/fastroping/initSettings.sqf, addons/fastroping/stringtable.xml, addons/goggles/initSettings.sqf, addons/goggles/stringtable.xml, addons/grenades/stringtable.xml, addons/magazinerepack/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/microdagr/stringtable.xml, addons/overheating/ACE_Settings.hpp, addons/overheating/stringtable.xml, addons/quickmount/initSettings.sqf, addons/quickmount/stringtable.xml, addons/reload/stringtable.xml, addons/switchunits/stringtable.xml, addons/weather/initSettings.sqf, addons/weather/stringtable.xml
- Upgrade the French translation, by translating the keys added during the last updates.
=> French translation of the latest updates

addons/repair/functions/fnc_addRepairActions.sqf
Fix #7245
see notes in https://github.com/acemod/ACE3/issues/7245#issuecomment-569429941
=> Repair - Handle turret hitpoints with no selection

addons/common/stringtable.xml, addons/fastroping/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/quickmount/stringtable.xml
=> Update Tchinese String

.github/release-drafter.yml
=> Improve Release Drafter configuration

addons/advanced_ballistics/stringtable.xml, addons/advanced_fatigue/stringtable.xml, addons/artillerytables/stringtable.xml, addons/ballistics/stringtable.xml, addons/common/stringtable.xml, addons/goggles/stringtable.xml, addons/grenades/stringtable.xml, addons/medical/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_gui/stringtable.xml, addons/quickmount/stringtable.xml, addons/reload/stringtable.xml, addons/repair/stringtable.xml, addons/switchunits/stringtable.xml, addons/weather/stringtable.xml, optionals/tracers/stringtable.xml
Portuguese Translation, pretty much everything is done. 
=> Portuguese Translations

.github/release-drafter.yml, .github/workflows/release-drafter.yml
- Fix Release Drafter replacer for titles
- Add ability to test Release Drafter configuration on another branch
=> Fix Release Drafter replacer

tools/make.py
- Remove -X flag whitch not supporting with current version of Micero pboProject
- Fix #7350
=> Tools - Update `make.py` for pboProject 2.63

optionals/compat_rhs_usf3/CfgMagazineGroups.hpp, optionals/compat_rhs_usf3/CfgMagazines.hpp
=> Update CSW RHS compat for new Mk-19 ammo type

addons/goggles/XEH_postInit.sqf
Not tested on GM map, which might use same effect system?
=> Goggles - Skip rain effects on snow maps

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
- Add setting to control self PAK usage, default no to match old medical
- Close #7365
=> Medical Treatment - Add self PAK setting

docs/wiki/development/how-to-translate-ace3.md
- Add a new sections that people should start looking for existing PRs in their language
- Add new target blanks to all external links (we don't want people to leave the homepage)
=> Improve "How to translate.." page

addons/medical_vitals/functions/fnc_updatePainSuppress.sqf
- Fix basic medication not suppressing pain
Addressing #7409
=> Fix suppression for basic medication

addons/advanced_fatigue/stringtable.xml, addons/common/stringtable.xml, addons/csw/stringtable.xml, addons/medical/stringtable.xml, addons/medical_blood/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/quickmount/stringtable.xml
=> Changed: Updated italian translation

addons/medical/stringtable.xml, addons/medical_blood/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_gui/stringtable.xml, addons/medical_statemachine/stringtable.xml, addons/medical_treatment/stringtable.xml
- same as #7398 but without merge conflicts
- close #7398
=> Changed: German translation for Medical Rewrite

addons/medical_treatment/stringtable.xml
- Change "Checking Heart Beat..." to "Checking Pulse..." to conform with "Check Pulse" action and setting names.
@IllidanS4
@TBakerBR
@D3L7A01
@classicarma
@dfr1238
Tag other translators as well!
=> Medical Treatment - Fix Checking Pulse progress bar text

addons/aircraft/stringtable.xml, addons/medical_treatment/stringtable.xml
=> Translations: French

optionals/compat_rhs_usf3/CfgWeapons.hpp
=> Fixed: RHS Compatibility - Remove scope adjust from ACOG Scopes

addons/medical_treatment/stringtable.xml
Moves `AllowSelfPAK_Description` below the display name.
=> Translations: fix medical_treatment order introduce on #7430

addons/advanced_fatigue/stringtable.xml
Added missing translation to Russian
=> Russian Translations

addons/aircraft/CfgAmmo.hpp
ref https://github.com/acemod/ACE3/pull/7118#discussion_r365496944
=> Aircraft - Fix ACE_Gatling_30mm_Sub class

addons/hearing/CfgVehicles.hpp
- title
- Fix bug introduced in #7400
=> Hearing - Fix missing earplug actions (regression)

addons/medical_damage/stringtable.xml
Added missing translation to Russian
=>   Russian translation

.github/release-drafter.yml
and remove `enhancement` so label to title 1-1 mapping
=> release-drafter - Add category for translations

addons/medical_ai/functions/fnc_isSafe.sqf
=> Medical AI - Block healing when handcuffed

addons/cookoff/functions/fnc_handleDamage.sqf
- Enable cook off for AI vehicles depending on cook off settings correctly
https://github.com/acemod/ACE3/blob/e908345eaeaf7fdaf4a7b7fab98d1e1d6fc98391/addons/cookoff/initSettings.sqf#L7
=> Cook Off - Adjust players only settings check

addons/common/functions/fnc_canDig.sqf
=> Common - Fix canDig returning non-bool

.github/PULL_REQUEST_TEMPLATE.md
- Title
- Facilitate automatic change log generation
Not sure where else we should add this, doesn't really fit anywhere on the wiki. @acemod/core-maintainers
=> Add Pull Request title standard to PR Template

addons/hitreactions/XEH_PREP.hpp, addons/hitreactions/functions/fnc_throwWeapon.sqf
- title
```sqf
player call ACE_hitreactions_fnc_throwWeapon
```
Let it fly.
=> add function to throw current weapon

addons/arsenal/missions/Arsenal.VR/CfgEventHandlers.hpp
=> Use macros

addons/medical/initSettings.sqf, addons/medical_treatment/initSettings.sqf
=> Medical - Use percentage sliders for chance settings

addons/arsenal/functions/fnc_onSelChangedLeft.sqf
- Address https://github.com/acemod/ACE3/pull/7445#pullrequestreview-363051195
=> Arsenal - Optimize non-scope 2 mags filtering

addons/common/XEH_postInit.sqf
- title, this was removed in rewrite
=> Common - Add isNotUnconscious canInteractWith condition

addons/atragmx/functions/fnc_can_show.sqf, addons/atragmx/functions/fnc_create_dialog.sqf, addons/kestrel4500/functions/fnc_canShow.sqf, addons/kestrel4500/functions/fnc_createKestrelDialog.sqf, addons/kestrel4500/functions/fnc_displayKestrel.sqf, addons/rangecard/functions/fnc_canShow.sqf, addons/rangecard/functions/fnc_canShowCopy.sqf
=> Remove requirements for usable items to be in backpack

docs/wiki/development/coding-guidelines.md
=> Documentation - Add spaces between array elements coding guideline

addons/medical_treatment/functions/fnc_treatment.sqf, addons/medical_treatment/script_component.hpp
=> Medical Treatment - Prevent extremely slow or fast animations

addons/nightvision/functions/fnc_refreshGoggleType.sqf
=> NightVision - Fix border missing while in FFV

addons/ballistics/CfgMagazineWells.hpp, addons/ballistics/CfgWeapons.hpp
- title
- fix #7559
- removes some TERRIBLE changes from #7557
=> Ballistics - Fix some magazine wells

tools/make.py
- Make `make.py` compatible with latest Mikero Tools updates
=> Tools - Removed deprecated Mikero tools arguments from make.py

addons/csw/functions/fnc_reload_handleRemoveTurretMag.sqf, addons/javelin/script_component.hpp, addons/medical_treatment/functions/fnc_fullHealLocal.sqf, addons/missileguidance/functions/fnc_seekerType_ARH.sqf
- Fix issues found with @dedmen's preprocessor.
=> General - Fix preprocessor issues

.github/workflows/arma.yml
=> Tools - Build release build with HEMTT on CI

addons/aircraft/stringtable.xml, addons/medical/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_treatment/stringtable.xml, optionals/tracers/stringtable.xml
finally I learn Github for Windows
=> Update Japanese translation

addons/csw/dev/checkStaticWeapons.sqf, addons/csw/functions/fnc_aceRearmGetCarryMagazines.sqf, addons/csw/functions/fnc_assemble_pickupWeapon.sqf, addons/csw/functions/fnc_reload_actionsUnload.sqf, addons/csw/functions/fnc_staticWeaponInit_unloadExtraMags.sqf
=> CSW - Check carry mag exists

AUTHORS.txt, docs/team.md
title
I'm assuming `AUTHORS.txt` is in alphabetical order, otherwise that's a really neat coincidence
=> Add myself to website Team page and update Authors.txt

addons/dragging/functions/fnc_dragObject.sqf, addons/dragging/functions/fnc_dropObject.sqf
=> Fix being stuck dragging when in combat pace

addons/medical_engine/functions/fnc_handleDamage.sqf
- Title
- Should _help_ with #7459
=> Medical Engine - Fixed typo in handledamage

docs/wiki/development/setting-up-the-development-environment.md
- Title
Was added as a requirement in recent pboProject (2.63?).
Is it also worth changing the minimal required version due to recent changes with arguments?
=> Documentation - Add DeTex as Mikero requirement

addons/realisticnames/CfgWeapons.hpp, addons/realisticnames/config.cpp, addons/realisticnames/stringtable.xml
- add the ace 2d optics to realistic names.
=> Realistic Names - Add 2D optics

docs/wiki/feature/mk6mortar.md
- Corrected a mistake in the wiki, regarding the elevation of mortars and its effect on dtop
- Line 45 was changed from lower to higehr
- see https://github.com/acemod/ACE3/issues/7628
=> Documentation - Fix Mk6 Mortar elevation mistake

addons/magazinerepack/CfgEventHandlers.hpp, addons/magazinerepack/XEH_PREP.hpp, addons/magazinerepack/XEH_postInit.sqf, addons/magazinerepack/functions/fnc_canRepackMagazine.sqf
=> Magazine Repack - Add inventory context menu action

addons/medical/stringtable.xml
=> Translation: fix inaccurate ACE_Medical_Fractures_SplintHasEffects' key.

addons/csw/Cfg3den.hpp
not even sure if this will make it into final 1.98, but on dev branch now
(making a PR so I don't forget)
```
Updating base class Controls->, by z\ace\addons\csw\config.cpp/Cfg3DEN/Attributes/Combo/Controls/ (original (a3\3den\config.bin - no unload))
```
=> CSW - Update 3den config for 1.98 changes

.github/workflows/arma.yml
=> Tools - Enable CI HEMTT artifacts

docs/src/package-lock.json
=> Documentation - Update packages

addons/cargo/XEH_postInit.sqf
Followup to #7636
Thanks to Liquid for spotting this
=> Cargo - Re-enable damage on unloaded tanks

addons/dragging/stringtable.xml
Add french translation for the `STR_ACE_Dragging_RaiseLowerRotate` key.
=> Translations - Add French Dragging RaiseLowerRotate key

docs/wiki/feature/medical-system.md
=> Documentation - Remove outdated medical info and add sample medical settings

addons/common/functions/fnc_checkFiles.sqf, addons/medical/XEH_postInit.sqf, addons/medical_damage/XEH_preInit.sqf
=> Minor RPT cleanup

addons/common/XEH_postInit.sqf
- Should fix "Unknown" being reported by getName in certain situations.
=> Common - fix player's name showing as "Unknown"

addons/advanced_ballistics/stringtable.xml, addons/advanced_fatigue/stringtable.xml, addons/advanced_throwing/stringtable.xml, addons/artillerytables/stringtable.xml, addons/dragging/stringtable.xml, addons/explosives/stringtable.xml, addons/goggles/stringtable.xml, addons/hearing/stringtable.xml, addons/interaction/stringtable.xml, addons/map/stringtable.xml, addons/map_gestures/stringtable.xml, addons/markers/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/overheating/stringtable.xml, addons/quickmount/stringtable.xml, addons/respawn/stringtable.xml, addons/switchunits/stringtable.xml, addons/vehicles/stringtable.xml
- improve and support for few entries
=> Translation - Update Japanese

addons/medical_gui/stringtable.xml, addons/trenches/stringtable.xml
- Improves the french `blood loss` status
- Improves the french `trenches` translation
=> Translations - fix some french keys (blood status and trenches)

addons/map/functions/fnc_blueForceTrackingUpdate.sqf, addons/map/initSettings.sqf
- fix PFEH was always being added
- fix bft markers were missing because name was not unique
=> Map - Only add BFT PFEH if enabled and fix missing markers

addons/advanced_ballistics/stringtable.xml
=> Translations - Spanish

addons/fcs/XEH_postInit.sqf, addons/fcs/functions/fnc_vehicleInit.sqf, addons/main/script_macros.hpp
Fix #7666
also fix TRACE_10 macro
=> FCS - Fix firedEH not being added in MP

AUTHORS.txt, addons/advanced_fatigue/XEH_postInit.sqf
- Allow modifying aimFatigue buildup via the SwayFactor setting as per v3.12.6
Fixes https://github.com/acemod/ACE3/issues/7679
> ~perhaps someone with the build process already set up could verify this works as intended?~
Or, your CI could do that automatically 🤩
=> Advanced Fatigue - Fix SwayFactor setting

addons/realisticnames/stringtable.xml
=> Realistic Names - Fix german abbreviation of Ozelot Wiesel

addons/realisticnames/CfgWeapons.hpp
=> Realistic Names - Fix MG3 Manufacturer

addons/csw/stringtable.xml
- Add french translation for the `STR_ACE_CSW_StaticM2ShieldBag_displayName` key.
=> Translations - Add French CSW StaticM2ShieldBag key

optionals/compat_rhs_usf3/CfgWeapons.hpp
=> Fix inheritence issue for m14ebrri for RHS 0.5.1

addons/ballistics/stringtable.xml
Added some shotgun shells translations.
=> Translations - Spanish Ballistics

addons/dogtags/stringtable.xml
=> Dogtags - Improve spanish translation

addons/artillerytables/stringtable.xml
Little correction to the traslation, so now it has more sense.
=> Translations - Improve Artillery Tables

addons/cookoff/stringtable.xml
Added translations to cook-off
=> Translations - Spanish Cookoff

addons/csw/stringtable.xml
-Added spanish translations
-Minor corrections
-"Armas de manejo colectivo" could be more appropriate.
https://www.linguee.co/ingles-espanol/traduccion/crew-served+weapons.html
https://www.defensa.com/en-abierto/armamento-ligero-colectivo-pesado-infanteria-marina-espanola-20
=> Crew served weapons - Add spanish translations

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
- title
Bodybag spawned inside vehicle goes booom.
=> Medical - Prevent packing into bodybag for bodies in vehicle

AUTHORS.txt, addons/aircraft/stringtable.xml, addons/artillerytables/stringtable.xml, addons/ballistics/stringtable.xml, addons/common/stringtable.xml, addons/csw/stringtable.xml, addons/dragging/stringtable.xml, addons/dragon/stringtable.xml, addons/explosives/stringtable.xml, addons/fastroping/stringtable.xml, addons/flashlights/stringtable.xml, addons/goggles/stringtable.xml, addons/grenades/stringtable.xml, addons/medical/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_gui/stringtable.xml, addons/medical_statemachine/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/quickmount/stringtable.xml, addons/rearm/stringtable.xml, addons/reload/stringtable.xml, addons/repair/stringtable.xml, addons/switchunits/stringtable.xml, addons/vehicles/stringtable.xml, addons/weather/stringtable.xml
Added missing translation to Russian
=> Add Russian translation

addons/trenches/functions/fnc_canContinueDiggingTrench.sqf, addons/trenches/functions/fnc_continueDiggingTrench.sqf, addons/trenches/functions/fnc_placeConfirm.sqf, addons/trenches/functions/fnc_removeTrench.sqf
Fix #7671
Assume progress is 1 if undefined
define placeData if undefined
=> Trenches - Fix mission placed trench interactions

AUTHORS.txt, optionals/compat_rhs_usf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/config.cpp
- Change CfgVehicles.hpp's RHS_CH_47F class to inherit UserActions from RHS_CH_47F_base to resolve #7708
=> RHS USF Compatibility - Change RHS_CH_47F class (#7708)

addons/spectator/functions/fnc_ui_handleLoad.sqf, addons/spectator/functions/fnc_ui_handleUnload.sqf, addons/spectator/ui.hpp, docs/wiki/framework/spectator-framework.md
- title, need loaded one for ACRE spectator handling
=> Spectator - Add display loaded and unloaded events

addons/microdagr/gui_controls.hpp
=> MicroDagr - Don't show markers on compass "map" control

addons/gforces/ACE_Settings.hpp, addons/gforces/XEH_preInit.sqf, addons/gforces/config.cpp, addons/gforces/functions/fnc_pfhUpdateGForces.sqf, addons/gforces/initSettings.sqf, addons/gforces/stringtable.xml
- title
- Move old setting to CBA Settings
=> GForces - Add forces strength coefficient setting

addons/dragging/XEH_postInit.sqf, addons/dragging/stringtable.xml
- Add a Carry/Release Object key bind, using the same implementation as the Drag/Release Object key bind
=> Dragging - Add Keybind for Carry

optionals/compat_rhs_afrf3/CfgAmmo.hpp, optionals/compat_rhs_afrf3/CfgMagazines.hpp, optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_afrf3/config.cpp
- Add **RHS:AFRF** compatibility with `ACE Explosives`
Addresses #7714
=> Compat_rhs_afrf3 - Add RHS:AFRF explosives compatibility

addons/aircraft/Heli_Attack_01_base_F.hpp, addons/hellfire/CfgVehicles.hpp, addons/hellfire/config.cpp
This now matches vanilla
Close #7712
=> Aircraft - Restore missing laser designator on Commanche

addons/dragging/stringtable.xml, addons/gforces/stringtable.xml, addons/medical_gui/stringtable.xml
- Add french translations in `dragging`, `gforces` and `medical_gui` modules
- Fix a typo error on `gforces` module
=> Translations - Update / Fix French Translations

addons/pylons/functions/fnc_handleDisconnect.sqf
- title, `getVariable` was passed the string `"_uid"` instead of the variable `_uid`
=> Pylons - Fix disconnect handling

addons/medical/stringtable.xml
- Add Chinese Localization to medical stringtable.xml
=> Add Simplify Chinese Localization to medical stringtable.xml

addons/gunbag/stringtable.xml, addons/map_gestures/stringtable.xml
Added missing Russian translations to map gestures and gunbag modules.
=> Translations - Russian

addons/csw/stringtable.xml, addons/gunbag/stringtable.xml, addons/medical/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_treatment/stringtable.xml
-  Fix punctuation and typos in Polish translation
=> Translations - fix Polish punctuation

addons/medical/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_gui/stringtable.xml, addons/medical_treatment/stringtable.xml
- Add: Simplified Chinese Translation for medical items and GUI
- Fix: Corrected some wrong Simplified Chinese Translation
- Fix: Improve Simplified Chinese Translation
=> Add: Simplified Chinese Translation for medical items and GUI

addons/gunbag/stringtable.xml, addons/map_gestures/stringtable.xml
- Add french translations in `gunbag` and `map_gestures` modules,
- Fix french translation of `Gunbag_OffGunbag` key.
=> Translations - Update / Fix French Translations (gunbag and map_gestures modules)

docs/wiki/frameworkx/fortify-framework.md
https://github.com/acemod/ACEX/pull/238
- Update documentation to suit linked pull request
=> Update fortify documentation

tools/search_undefinedFunctions.py
=> Tools - Update search_undefinedFunctions.py
