acemod/ACE3

addons/advanced_fatigue/functions/fnc_getAnimDuty.sqf, addons/advanced_fatigue/functions/fnc_getMetabolicCosts.sqf, addons/advanced_fatigue/functions/fnc_mainLoop.sqf, addons/movement/functions/fnc_handleVirtualMass.sqf
Fix #4880 - Adds `GVAR(isProne)` which is set in getAnimDuty
Minor performance improvements; 
main one is setting total virtual load in movement (on `loadout` EH) so we can skip forEach loop
=> AdvFatigue - Fix unarmed sprint->prone + minor perf improvments

tools/publish.py
New compat mod is published but set as private until 3.9.1 is out
=> Update publish.py for RHS Gref Compat

addons/optionsmenu/config.cpp, addons/optionsmenu/gui/pauseMenu.hpp, addons/optionsmenu/init_loadMainMenuBox.sqf, addons/optionsmenu/script_component.hpp
- simplified config by using inheritance from other buttons
- macro defines for IDC's
- fixed no spacing between our button and the vanilla ones
- added hover highlighting like the other buttons
- fixed how version number is generated (old method: 3.10.X would be shown as "3.10.")
- changed url to link directly to the /releases/ page of github.
Pabst, you made this originally. Please review. Thanks.
=> tweak ACE main menu info box

addons/advanced_throwing/functions/fnc_exitThrowMode.sqf, addons/advanced_throwing/functions/fnc_prime.sqf, addons/common/XEH_postInit.sqf
=> Use setShotParents in Advanced Throwing

addons/fcs/CfgEventHandlers.hpp
Related to findings in https://github.com/CBATeam/CBA_A3/pull/628
vehicleInit.sqf runs several `setVariables [,,true]` that were not synced
=> Fix FCS Vehicle Init

addons/common/functions/fnc_interpolateFromArray.sqf, addons/overheating/functions/fnc_firedEH.sqf, addons/overheating/functions/fnc_swapBarrelCallback.sqf, addons/overheating/functions/fnc_updateTemperature.sqf, addons/overheating/script_component.hpp
Small changes to overheating system
- Slightly reduce jam chance; mainly delaying the 150x multiplier
- Change barrel mass calc; this will effect heat buildup and cooldown rate
=> Tweak overheating

addons/tagging/XEH_postInit.sqf, addons/tagging/functions/fnc_checkTaggable.sqf, addons/tagging/functions/fnc_tag.sqf
- postInit wasn't saving p3d name to cache (wrong index)
- other functions had inverted logic for exitWith (so it still worked)
- config class isn't used, so just save bool
Could possibly cause array bounds error if a building had an odd model path (see #5035)
```
7:25:43 Error in expression <aticModels setVariable [toLower (_array select ((count _array) - 2)), _cfgClass]>
7:25:43   Error position: <select ((count _array) - 2)), _cfgClass]>
7:25:43   Error Zero divisor
```
If array only had 1 element you could get something like `["x"] select -1`
=> Fix tagging model cache

docs/wiki/featurex/volume.md
=> Add volume toggle docs

addons/medical_ui/XEH_postInit.sqf
- Fixing a bug where zeus would receive the unnconsious effect and the input block when his remote controlled unit becomes unnconsious.
This will not work by now as the `unit` player eventhandler is still broken for zeus leaving a remote controlled unit. Fixed with [this commit](https://github.com/CBATeam/CBA_A3/commit/2f37af3110ac8b03d4b397d7db2a9b9f751de964) in cba.
=> [Medical Rewrite] Fixing zeus remote controll unnconsious problem

addons/refuel/functions/fnc_makeJerryCan.sqf
- Fix #5106 
- Add jerry can actions under `"ACE_MainActions"`, mimicking the standard Refuel actions on vehicles.
=> Fix jerry can refuel interaction overlapping

addons/common/stringtable.xml, addons/interact_menu/XEH_clientInit.sqf
@HeadTraumaZA
Ref https://github.com/acemod/ACE3/issues/3594#issuecomment-296169526
Adds seperate keybind that just toggles the interaction menu.
When combined with the "Do action when releasing key: No" setting, it should be much easier to use.
Should we add new keybinds, or just add a setting to change behaviour of the existing keybinds?
=> Add keybind to toggle interaction menu

addons/cargo/ACE_Settings.hpp, addons/cargo/CfgVehicles.hpp, addons/cargo/functions/fnc_moduleSettings.sqf, addons/cargo/functions/fnc_onMenuOpen.sqf, addons/cargo/functions/fnc_paradropItem.sqf, addons/cargo/functions/fnc_startUnload.sqf, addons/cargo/stringtable.xml
- Add a new setting so it's possible to modify how long it takes for cargo to unload while paradropping. If the setting is 0 the progress bar is skipped and cargo is dropped immediately.
- Show how long it's going to take to unload something in the list dialog by it's name.
Counter point to any realism concerns people might have (even though it's a setting using the current value as default): IRL the aircraft's crew would have to unstrap the cargo container, slowly and safely move it to the ramp area, attach the drop hook etc... I know that. This setting is so _filthy casuals_ don't have to make 2 minutes of flight planning and fail the first attempt anyway because the random ammo box zeus chose that day took 17.8 seconds to drop, and there was no …
=> Add Paradrop Time Coefficient Setting

addons/spectator/UI/interface.hpp, addons/spectator/config.cpp, addons/spectator/functions/fnc_handleCompass.sqf, addons/spectator/functions/fnc_updateCameraModes.sqf, addons/spectator/functions/fnc_updateUnits.sqf, addons/spectator/functions/fnc_updateVisionModes.sqf, addons/spectator/stringtable.xml
- Fix #5081 
- Disable searching on the spectator unit tree
- Add stringtables for the eden respawn template dialog
- Optimise some spectator functions
~~This can be merged now, but I'll leave it open for a little bit in case anyone wants to review.~~
Forgot the new system requires a review from someone else :+1: It's been a while :laughing:
=> Spectator Improvements

addons/spottingscope/CfgVehicles.hpp
Close #5128
Spotting scope was using rear glass as interaction point.
New point is right on the main pivot near the center.
=> Fix Spotting Scope Interaction Point

addons/frag/XEH_postInit.sqf, addons/weather/XEH_postInit.sqf
These are never removed and run every frame, so no reason not to use EachFrame
None: 12.8ms
1000 pfeh: 21.7 ms [+8.9]
1000 EachFrame: 18.6 ms [+5.8]
=> Switch 2 perm PFEH to EachFrame

addons/explosives/XEH_PREP.hpp, addons/explosives/XEH_preInit.sqf, addons/explosives/functions/fnc_addDetonateActions.sqf, addons/explosives/functions/fnc_addDetonateHandler.sqf, addons/explosives/functions/fnc_defuseExplosive.sqf, addons/explosives/functions/fnc_detonateExplosive.sqf, addons/explosives/functions/fnc_detonateExplosiveAll.sqf, addons/explosives/functions/fnc_dialPhone.sqf, addons/explosives/functions/fnc_dialingPhone.sqf, addons/explosives/functions/fnc_onIncapacitated.sqf, addons/explosives/functions/fnc_scriptedExplosive.sqf, addons/explosives/functions/fnc_startTimer.sqf, docs/wiki/framework/explosives-framework.md
Close #5101
Allows mission/addon makers to block detonations in the explosive system.
See example in addDetonateHandler.sqf
=> Explosives - Add code handler for detonation

addons/zeus/CfgVehicles.hpp, addons/zeus/XEH_PREP.hpp, addons/zeus/XEH_postInit.sqf, addons/zeus/config.cpp, addons/zeus/functions/fnc_getModuleDestination.sqf, addons/zeus/functions/fnc_moduleSuppressiveFire.sqf, addons/zeus/functions/fnc_moduleSuppressiveFireLocal.sqf, addons/zeus/stringtable.xml
- Add a module that will allow a zeus to direct suppression fire to certain location / unit
@PabstMirror did all the real work
_click to enlarge_
[![](https://i.gyazo.com/thumb/200/_6fb111ae0c7dc05c73f5a1145ae2ecc4-gif.gif)](https://i.gyazo.com/b77353e2b44e290f72871f783e444c9a.gif)
=> Zeus Suppression Module

optionals/compat_r3f/CfgAmmo.hpp, optionals/compat_r3f/CfgWeapons.hpp
**AB compat with the new R3F weapons pack v3.5**
- Add HK416S (barrel 11").
- Add SIG 551.
- Add HK USP Tactical.
- Update with the new Scopes Framework: reference BH=62mm with the PGM poly and the NF x42 scope.
Many thanks to Nanucq, R3F team.
- Add AtragMx GunList references for the bullets.
- Minor changes.
- Coherent dispersion for sniper and marksman rifles.
=> AB: update compat R3F v3.5

addons/refuel/functions/fnc_makeJerryCan.sqf
makeJerryCan needs to run on all machines, because the interaction actions are local effects.
FUNC(setFuel) has global effects
so if someone jips, it would reset the fuel var
=> Jerry Can - only set global var on server

addons/gforces/XEH_postInit.sqf, addons/gforces/functions/fnc_pfhUpdateGForces.sqf
A zeus can remote control UAV
Doing so means that typeOf ace_player = B_UAV_AI
(has some other weird effects)
This exits the gfroce pfeh if the unit is virtual or AI
=> Disable g-forces for UAV AI

addons/dragging/functions/fnc_startCarry.sqf, addons/medical/functions/fnc_treatment_failure.sqf, addons/medical/functions/fnc_treatment_success.sqf, addons/rearm/script_component.hpp, addons/refuel/script_component.hpp, addons/repair/functions/fnc_repair_failure.sqf, addons/repair/functions/fnc_repair_success.sqf, addons/respawn/functions/fnc_restoreGear.sqf, addons/safemode/functions/fnc_unlockSafety.sqf, addons/weaponselect/functions/fnc_putWeaponAway.sqf, addons/weaponselect/functions/fnc_selectWeaponMode.sqf, addons/weaponselect/functions/fnc_selectWeaponMuzzle.sqf, addons/weaponselect/functions/fnc_selectWeaponVehicle.sqf
=> Increase max weapon index for large modsets

addons/rearm/functions/fnc_canRearm.sqf, addons/rearm/functions/fnc_canStoreAmmo.sqf, addons/rearm/functions/fnc_canTakeAmmo.sqf, addons/refuel/CfgVehicles.hpp, addons/refuel/functions/fnc_canConnectNozzle.sqf, optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
=> Disable rearm,refuel on dead vehicles

addons/advanced_ballistics/functions/fnc_readAmmoDataFromConfig.sqf, addons/advanced_ballistics/functions/fnc_readWeaponDataFromConfig.sqf, addons/advanced_fatigue/functions/fnc_handlePlayerChanged.sqf, addons/advanced_throwing/XEH_postInit.sqf, addons/attach/functions/fnc_attach.sqf, addons/attach/functions/fnc_canDetach.sqf, addons/captives/functions/fnc_doEscortCaptive.sqf, addons/captives/functions/fnc_handleAnimChangedHandcuffed.sqf, addons/captives/functions/fnc_handleGetIn.sqf, addons/captives/functions/fnc_handleRespawn.sqf, addons/common/XEH_postInit.sqf, addons/common/functions/fnc_checkFiles.sqf, addons/common/functions/fnc_deviceKeyFindValidIndex.sqf, addons/common/functions/fnc_getDoorTurrets.sqf, addons/common/functions/fnc_getMGRSdata.sqf, addons/common/functions/fnc_getMapGridData.sqf, addons/common/functions/fnc_throttledPublicVariable.sqf, addons/common/scripts/checkVersionNumber.sqf, addons/hearing/functions/fnc_firedNear.sqf, addons/magazinerepack/functions/fnc_magazineRepackProgress.sqf, addons/map/functions/fnc_compileFlashlightMenu.sqf, addons/minedetector/XEH_postInit.sqf, addons/overpressure/functions/fnc_getDistance.sqf, addons/refuel/functions/fnc_dropNozzle.sqf, addons/repair/functions/fnc_addRepairActions.sqf, addons/tagging/functions/fnc_tag.sqf, tools/sqf_linter.py
Did a quick pass with the SQF Lint tool. (https://github.com/LordGolias/sqf)
Most are just private cleanups which aren't a big deal, but it did find some actual errors.
- Fixed: getDoorTurrets (Not used, was broken, could drop?)
- Fixed: getMGRSdata (Was ignoring getMapData altitude)
- Fixed: throttledPublicVariable (Not used anywhere, should probably test if we use it in the future)
- Fixed: handleRespawn (Using bad var name, escort setVar would not be reset)
- Fixed dropNozzle
- magazineRepackProgress (magically not broken because progressbar uses same var name)
- readWeaponDataFromConfig (same thing, `_weapon` always existed from upper scope)
=> SQF Lint Cleanup Pass

addons/aircraft/CfgWeapons.hpp, addons/aircraft/stringtable.xml
- Remove our version of countermeasure mode switching (burst - single) as vanilla will have it in 1.70.
=> 1.70 CMs - Remove countermeasure mode switching

addons/fcs/CfgOptics.hpp, addons/fcs/CfgVehicles.hpp, addons/fcs/CfgWeapons.hpp, addons/fcs/XEH_postInit.sqf, addons/fcs/functions/dev_debugConfigs.sqf, optionals/compat_rhs_afrf3/CfgVehicles.hpp
Right now 1.70 RC has the new FCS system
In some quick testing it's fairly close to ace's system.
New "Laze Target" button 
- just like ace you now have to hit the button to get a range in most things like the handheld RangeFinder
- Their moving target calculations seem to be using some magic based off of looking at the velocity of the cursorTarget instead of using real relative movement of the aim point like ace does, but it's not that bad imho.
There is a major conflict from fcs doing
```
discreteDistance[] = {};
discreteDistanceInitIndex = 0;
```
which seems to mess up their FCS and delete the projectile and cause some bizarre script errors in overpressure and winddeflection.
```
getPosASL _projectile=[2492.92,5692.51,-1.#IND], vectorDir _projectile=[-1.#IND,-1.#IND,-1.#IND]
```
This …
=> 1.70 FCS - Remove ACE_FCS from most vics

addons/realisticnames/CfgMagazines.hpp, addons/realisticnames/dev_dumpPylon.sqf
3den pylon interface uses CfgMagazines name
=> Realistic names for 1.70 pylon magazines

addons/grenades/CfgVehicles.hpp, addons/minedetector/CfgVehicles.hpp, addons/mx2a/CfgVehicles.hpp, addons/overheating/CfgVehicles.hpp, addons/vector/CfgVehicles.hpp, addons/yardage450/CfgVehicles.hpp
Fix #5068
As far as I can tell arma can handle the wrong entries.
This does seem to put he mine detectors at the top of the "misc items" box, but I noticed no other changes.
=> Use correct TransportX type for ace items

addons/common/functions/fnc_checkFiles.sqf
Having old compat pbos is less critical
Depending on how people update, they may get `@ace` way before `@ace_compat_X` and would be unable to play at all.
=> Just warn for old compat pbos

addons/realisticnames/CfgVehicles.hpp, addons/realisticnames/stringtable.xml
- Transfer existing realistic names to the new dynamic loadout classes (Fix #5184)
=> Add realistic names to dynamic loadout classes

optionals/compat_rhs_usf3/functions/fnc_canCloseDoor.sqf
Fix #5196
Matches their config for ch47:
```
condition = "this animationSourcePhase 'ramp_anim' > 0
```
Other vehicles still use `doorPhase`
=> RHS CH-47 - use animationSourcePhase

addons/common/XEH_PREP.hpp, addons/common/functions/fnc_dummy.sqf, addons/zeus/CfgVehicles.hpp, addons/zeus/XEH_postInit.sqf, addons/zeus/functions/fnc_moduleTeleportPlayers.sqf
- Fix zeus teleport module on non-local units (i.e all other players)
- Remove BI error message when using zeus UI modules that have no function
=> Fix Zeus teleport players module

addons/advanced_throwing/functions/fnc_exitThrowMode.sqf
Fix #5207
Actual problem is from 
https://github.com/acemod/ACE3/blob/master/addons/chemlights/functions/fnc_throwIR.sqf
grenade gets replaced, but not setShotParents.
Not a real problem because it's a chemlight
In any case, using `_unit` will be safe
=> Adv Throw - Handle getShotParents being []

optionals/compat_rh_acc/script_component.hpp, optionals/compat_rh_de/script_component.hpp, optionals/compat_rh_m4/script_component.hpp, optionals/compat_rh_pdw/script_component.hpp, optionals/compat_rksl_pm_ii/script_component.hpp, optionals/compat_sma3_iansky/script_component.hpp
- Update compats `compat_rh_acc`, `compat_rh_de`, `compat_rh_m4`, `compat_rh_pdw`, `compat_rksl_pm_ii` and `compat_sma3_iansky` to correct classnames
- Fixes #5203
=> [Compats] Fix classnames

addons/reload/functions/fnc_startLinkingBelt.sqf
startLinkingbelt now uses canLinkBelt so if condition needs to be changed then you can do it on one position.
Nothing will change with this, only easier to edit condition in the future.
First time edit so please point out malpractice.
=> Linking belt refactoring

addons/advanced_throwing/functions/fnc_drawThrowable.sqf
`currentThrowable` can get glitched and show a magazine that you don't have in inventory
Advanced throwing lets you throw unlimited grenades.
Effects vanilla throw as well, although there you can only do a single throw of a `x0` grenade.
This also breaks `ace_weaponselect_fnc_selectNextGrenade` because removing has no effect
=> AdvThrow - Handle bugged currentThrowable

addons/refuel/CfgVehicles.hpp, addons/refuel/functions/fnc_checkFuel.sqf, addons/refuel/functions/fnc_connectNozzleAction.sqf, addons/refuel/functions/fnc_maxDistanceDropNozzle.sqf, addons/refuel/functions/fnc_readFuelCounter.sqf, addons/refuel/functions/fnc_reset.sqf, addons/refuel/functions/fnc_returnNozzle.sqf, addons/refuel/functions/fnc_takeNozzle.sqf, addons/refuel/functions/fnc_turnOff.sqf, addons/refuel/functions/fnc_turnOn.sqf, addons/refuel/script_component.hpp, addons/repair/CfgEventHandlers.hpp
- Add helper.p3d from fastroping
- Create helper object for non-AllVehicles objects, allowing refuel to be configured for more stuff (sling-loadable barrels for example)
- Un-magic refuel progress timer value
This adds a workaround which makes it possible to have a fuel hose (an arma rope) coming from a non-physx object (limitation of ropeCreate) by using an invisible helper object which the rope is connected to instead - such that it looks like it connects to the actual object.
This has been used for sling-loadable fuel barrels for a number of weeks with no issues. These can be found here: https://github.com/uksf/modpack/blob/master/addons/vehicles/CfgVehicles.hpp#L102
=> Refuel for non-AllVehicle objects

addons/reload/CfgVehicles.hpp, addons/reload/XEH_PREP.hpp, addons/reload/functions/fnc_getAmmoToLinkBelt.sqf, addons/reload/functions/fnc_startLinkingBelt.sqf
Removed redundant code fnc_canLinkBelt now returns a value over  0 if success and -1 if error.
This is so there is no equal code in canLinkBelt and startLinkBelt.
Changes to config so it works.
=> Linkingbelt refactoring

addons/reload/ACE_UI.hpp, addons/ui/functions/fnc_setAdvancedElement.sqf
Fixes UAVs having no ammo count displayed
@jonpas - this could also be fixed in
https://github.com/acemod/ACE3/blob/master/addons/reload/ACE_UI.hpp#L4
wasn't sure which was best place to put it
=> Fix ammo count hidden in UAVs

addons/laserpointer/XEH_postInit.sqf, addons/laserpointer/functions/fnc_getNearUnits.sqf
Fix #5189
`if (_laser isEqualTo "") exitWith {};` - never removed people from laser lists
I slightly reordered to exitWith early if `!isFlashlightOn` as I think that should common case
=> Remove unit from laser pointer list if laser removed

addons/interact_menu/CfgEventHandlers.hpp, addons/interact_menu/XEH_PREP.hpp, addons/interact_menu/functions/fnc_handleEscapeMenu.sqf, addons/interact_menu/functions/fnc_keyDown.sqf
=> Handle escape menu with toggle iteractMenu

addons/cargo/stringtable.xml, addons/spectator/stringtable.xml, addons/zeus/stringtable.xml
Hello,
- Add french translation to Cargo, spectator and Zeus
- Cargo : 
-- Add on : <Key ID="STR_ACE_Cargo_paradropTimeCoefficent">
--- <French>Coefficient Temps de larguage de cargaison</French>
-- Add on : <Key ID="STR_ACE_Cargo_paradropTimeCoefficent_description">
-- <French>Modifier le temps qu'il faut pour larguer la cargaison.</French>
- Spectator :
-- Add on : <Key ID="STR_ACE_Spectator_DisplayName">
--- <French>Spectateur ACE</French>
- Zeus : 
-- Add on : <Key ID="STR_ACE_Zeus_ModuleSuppressiveFire_DisplayName">
--- <French>Tir de suppression</French>
=> French translation missing

addons/vehicles/functions/fnc_speedLimiter.sqf
Minimum speed limit of 10 km/h was needed in the past due to engine limitations. Multiple user tests have shown that the minimum speed is not needed anymore. The new minimum of 0 km/h allows for example setting walking speed for vehicles (<10 km/h).
=> Lower minimum speed limiter speed to 5 km/h

addons/interaction/ACE_ZeusActions.hpp, addons/interaction/XEH_postInit.sqf
- The `setUnitPos`, `setFormation`, `setSpeedMode` and `setBehaviour` commands require local arguments
- The waypoint equivalents require server execution
=> Fix zeus unit and group interactions locality

addons/aircraft/CfgAmmo.hpp, addons/aircraft/CfgMagazines.hpp, addons/aircraft/CfgWeapons.hpp
Fix #5221
Removes the submunition (`Deploy`) ammo type for the a-10 cannon
Ref PR #5197
=> Remove submuntion ammo changes to A-10

addons/medical/functions/fnc_determineIfFatal.sqf
Closes #5218
Use the boolean parameter for common_isPlayer to exclude remote controlled units
=> Fix zeus RC units using player damage treshold

addons/interaction/XEH_PREP.hpp, addons/interaction/functions/fnc_getDoor.sqf, addons/interaction/functions/fnc_getDoorAnimations.sqf, addons/interaction/functions/fnc_getGlassDoor.sqf, addons/interaction/functions/fnc_openDoor.sqf
Will make sure that you can Ace slow open glass doors.
Also a bit flexible animation gathering instead of fixed strings.
CUP houses now works to incremental open!
The reason behind getGlassDoor is that if you do the regular door check you will get the hide and unhide of the glass pane. So you then need to find the closest doorobject because thats the door.
=> Open glass and CUP doors

addons/spectator/functions/fnc_handleCamera.sqf, addons/spectator/functions/fnc_handleIcons.sqf
- Fix stuttering of the camera and icons when camera is following the unit.
- Moves icons directly to the unit position.
It uses ```getPosASLVisual``` and ```ASLToAGL``` which simulates what ```modelToWorldVisual``` does but it updates properly. Tested this in the spectator we use in my community, works properly for any surface (water, underwater, above ground).
Example video.
Old - https://youtu.be/j7L0hg4POtY?t=0
New - https://youtu.be/j7L0hg4POtY?t=16
=> Use getPosASLVisual for icons and camera position.

addons/advanced_throwing/functions/fnc_drawThrowable.sqf
Ref https://github.com/acemod/ACE3/pull/5216
Fixes bug from last PR that prevents throwing last grenade
I didn't account for the fact that ` ACE_player setAmmo [_muzzle, 0];` seems to remove the magazines from `magazines` command
But they still show with the `xItems` commands.
=> Fix being unable to throw last mag

docs/wiki/development/coding-guidelines.md
- Update website with more guidelines to make sure people know what to do.
- Added info about EditorConfig
=> Added more info about indentations, tabs and EditorConfig

addons/gforces/functions/fnc_pfhUpdateGForces.sqf, addons/medical/ACE_Medical_StateMachine.hpp, addons/medical/ACE_Settings.hpp, addons/medical/CfgVehicles.hpp, addons/medical/XEH_PREP.hpp, addons/medical/functions/fnc_handleStateUnconscious.sqf, addons/medical/functions/fnc_moduleMedicalSettings.sqf, addons/medical/functions/fnc_setCardiacArrest.sqf, addons/medical/functions/fnc_setUnconscious.sqf, addons/medical/functions/fnc_setUnconsciousStatemachine.sqf, addons/medical/script_macros_medical.hpp, addons/medical/stringtable.xml, addons/zeus/functions/fnc_moduleUnconscious.sqf
Splits `setUnconscious` function
- `setUnconscious` is meant to be called publicly, just responsible for changing state
Also added ability to set minimum waiting time and forced wakeup for g-forces/zeus
- `setUnconsciousStatemachine` is called from the statemachine on transition
- Added spontaneousWakeUpChance setting - Close #4830
=> Split setUnconscious func, add spontaneousWakeUpChance setting

docs/wiki/development/setting-up-the-development-environment.md
As old PboProject produce invalid ACE PBOs while lying to your face about what a great success the compilation was, and because there might be more people in this world who are sitting on an old PboProject version without knowing the danger they're in… let's drop a hint as to which version works :D
=> note required PboProject version

addons/repair/ACE_Settings.hpp, addons/repair/CfgEden.hpp, addons/repair/CfgVehicles.hpp, addons/repair/functions/fnc_getPostRepairDamage.sqf, addons/repair/stringtable.xml, docs/team.md
- Will change the translation from Repair specialist to Advanced Engineer. See picture.
- Translation on other languages than English might be weird so  if its your native language and wrong then please review.
Did not have time to look through all stringtables in ACE so if you know there is a mention of ACE repair specialist somewhere else than repair then please say so. Should not be mentioned anywhere else.
http://steamcommunity.com/sharedfiles/filedetails/?id=940226455
Fixes #3186
=> Repair specialist rename, fixes #3186

addons/attach/CfgVehicles.hpp, addons/attach/functions/fnc_canAttach.sqf
- Title
Max distance of 7 (4.5 in config had no impact) prevents attaching things to large vehicles such as VTOLs, unless you crawl under them. There is no real reason to have a max distance check here, as you can only attach to a vehicle you interacted with after picking the item to attach.
=> Remove maximum distance of attach to vehicle action

addons/explosives/CfgAmmo.hpp, addons/explosives/CfgVehicles.hpp, addons/explosives/functions/fnc_interactEH.sqf, docs/wiki/feature/explosives.md, docs/wiki/framework/explosives-framework.md
- IED will get size variable. 0 for small, 1 for large.
- This size will determine how far the defuse range should be, might be used for other things aswell.
- Increase defusal range for large IEDs to replicate behaviour of small IEDs, you can now crouch to big IEDs but be aware!
- Will add Tip on wiki about defusing 
- Will fix #5258 
PS I know _size == 1 might be redundant but its how I write because _size is formally a number not a bool then you have to compare it and not just if (_size)
=> Fix Large IED defuse distance

addons/common/functions/fnc_isEOD.sqf, addons/common/functions/fnc_isEngineer.sqf, addons/medical/functions/fnc_isMedic.sqf, addons/repair/functions/fnc_isEngineer.sqf
- Make the functions which check whether units are medics, engineers or explosive specialists use the newer `getUnitTrait` command which makes them compatible with use of `setUnitTrait` and not purely checking the config
=> Use getUnitTrait for medics, engineers and EOD

addons/common/functions/fnc_isFeatureCameraActive.sqf
At the moment, isFeatureCameraActive does *not* detect ACE spectator mode, because `ace_spectator_camera` as a variable was removed in 77c2b99ee542e3825c4f25e7b5a399597fd436e2 .
spectator module initializes three separate cameras instead, of which for example `ace_spectator_freeCamera` could be used to check if spec mode is active.
=> Fix isFeatureCameraActive for Spectator enhacements

addons/common/functions/fnc_getMapData.sqf
**G.O.S N'Djenahoud map with the Advanced Ballistics module enabled.**
- Ennedi Massif (Republic of Chad): positive latitude 20° N (default -20).
=> AB: G.O.S N'Djenahoud latitude

tools/make.py
=> Count untraced errors in make.py

addons/common/functions/fnc_isFeatureCameraActive.sqf
Fix #5290
#5269 had reversed logic because the whole thing is wrapped in a NOT
=> Fix isFeatureCameraActive

addons/interaction/CfgVehicles.hpp, addons/interaction/XEH_PREP.hpp, addons/interaction/functions/fnc_modifyJoinGroupAction.sqf
Shows group name in action menu.
Edit:
I see this as a small usability improvement. 
But I guess it does give some _meta_ information about the specific group a unit is part of??
There is an ace setting `GVAR(EnableTeamManagement)` that could disable the interaction if it's a problem.
=> Modify JoinGroup action to show group name

addons/repair/dev/draw_showRepairInfo.sqf, addons/repair/functions/fnc_addRepairActions.sqf, addons/repair/functions/fnc_normalizeHitPoints.sqf, addons/repair/functions/fnc_setHitPointDamage.sqf
Close #5180
Depends can be `"0"` and still haven no effect
https://community.bistudio.com/wiki/Arma_3_Jets_Hitpoint_Configuration
>depends - simple expressions for creating dependencies between hitpoints. Clearing 'depends' in case of inheritance cannot be an empty string (rpt warnings), but rather a "0" value. It can be used for more detailed damage model.
=> Repair - Handle depends = "0"

addons/common/functions/fnc_addLineToDebugDraw.sqf, addons/refuel/functions/fnc_checkFuel.sqf, addons/refuel/functions/fnc_connectNozzle.sqf, addons/refuel/functions/fnc_connectNozzleAction.sqf, addons/refuel/functions/fnc_readFuelCounter.sqf, addons/refuel/functions/fnc_returnNozzle.sqf, addons/refuel/functions/fnc_takeNozzle.sqf, addons/refuel/functions/fnc_turnOff.sqf, addons/refuel/functions/fnc_turnOn.sqf, addons/refuel/script_component.hpp
Fix #5143
Removes the old binary search and now uses `lineIntersectsSurfaces`
Default is to aim at player's viewing angle (what you see is what you get) instead of using model center
=> Refuel - change nozzle position calc

addons/cargo/functions/fnc_initObject.sqf
var `ace_cargo_canLoad` used to be 0/1
some addons are still setting to scalar
e.g. r3f-logistics does
```
_object setVariable ['ace_dragging_canCarry', false];
_object setVariable ['ace_dragging_canDrag', false];
_object setVariable ['ace_cargo_canLoad', 0];
```
Throws error
```
Error ||: Type Number, expected Bool,code
File z\ace\addons\cargo\functions\fnc_initObject.sqf, line 13
```
=> Handle ace_cargo_canLoad set to scalar

addons/modules/config.cpp
Ref https://github.com/CBATeam/CBA_A3/pull/708
=> Add XEH to ace_module

addons/hellfire/CfgAmmo.hpp, addons/hellfire/CfgMagazines.hpp, addons/hellfire/CfgWeapons.hpp, addons/hellfire/functions/fnc_setupVehicle.sqf, addons/hellfire/stringtable.xml
- Change the check in the interaction condition to check for `ace_hellfire_enabled` config value instead of just the raw `ace_hellfire_launcher` weapon.
- This allows other launchers to be made and be compatible (for example, N-variant hellfires)
- Added November (Thermobaric) hellfire ammo, magazines, and weapon. (https://en.wikipedia.org/wiki/AGM-114_Hellfire#Variants) Have used the settings committed for some time with no balance issue. Not as good against tanks, better against infantry and bunkers etc.
=> Changed hellfire interaction check & added N variant

addons/cookoff/CfgSFX.hpp, addons/cookoff/CfgVehicles.hpp, addons/cookoff/functions/fnc_cookOff.sqf
what means that different players can get different pressure Cookoff sounds
to prevent that I split up the sounds in 3 types and used a Weighted select to have the before used values back
=> Fix the issue that SFX variants are not global 

addons/maptools/MapGpsUI.hpp
EtelkaNarrowMediumPro broke with 1.72 hotfix
=> Fix broken fonts for map gps display

addons/interaction/functions/fnc_openDoor.sqf
=> Handle locked doors

addons/respawn/functions/fnc_handleInitPostServer.sqf
From slack, user was using `this setVariable ["ACE_canMoveRallypoint", false, true];` 
to block ability to move rally points.
ACE's initPost XEH runs after unit's init and changed it to true
This will prevent ace from modifying that variable if it's already defined
=> Rallypoints- Don't modify setVar if already set

addons/refuel/functions/fnc_canTakeNozzle.sqf
- Title
If allowed, it caused the unit that carried it to completely glitch out, as it was still "carrying" it, just unable to do anything. Not something you'd want to do due to it being a logistical thing (not in combat), so this fix should be enough.
=> Prevent taking nozzle if already carried

addons/main/config.cpp, addons/main/script_mod.hpp, addons/refuel/CfgEventHandlers.hpp, addons/refuel/CfgVehicles.hpp, addons/refuel/XEH_postInit.sqf, addons/refuel/script_component.hpp
- Title
- Make Fuel Canister automatically set as a Jerry Can
- Add debug drawing of refuel hooks
Changed interactions to `House_F` to support that pump, unsure if this effects performance a lot.
=> Add support for Tanoa and Malden Fuel Pumps, Flexible Tanks and Fuel Canister

addons/advanced_throwing/XEH_postInit.sqf, addons/advanced_throwing/functions/fnc_canPrepare.sqf, addons/common/XEH_postInit.sqf
I use one key for vanilla and ACE throwing (if ACE is loaded adv. one is used, if not - vanilla one).
If current weapon reloading time is not correctly calculated, you can suddenly throw vanilla way instead of ACE. This can be easily reproduced with `MX_3GL` or `KH2002 Sama 3GL` UGL reloading because UGL reloading time is less than calculated one.
This PR adds UGL reloading time considering to `ace_common_isReloading` var calculating.
Also this PR adds blocking of adv. throwing key when reloading (if once another reloading time is not correctly calculated).
=> Fix adv. throw key handling when reloading

AUTHORS.txt, addons/repair/ACE_Settings.hpp, addons/repair/CfgVehicles.hpp, addons/repair/stringtable.xml
- Correct typos ("enginer" to "engineer").
=> Correct typos ("enginer" to "engineer")

docs/wiki/framework/settings-framework.md
- Delete the invalid shortcut for Modules (F7) and add the shortcut for Systems (F5).
- Add that you need to place a playable character (to be able to interact with the `ACE Options` dialog, otherwise the game will become unresponsive when opening it).
- Add that the scenario must be played in single-player (for the `Open Export Menu` button to be displayed).
- Change the non-existent `Config Export` button to `Open Export Menu`.
- Change the wording in other parts for clarity.
=> Update the Wiki for the Settings Framework

docs/wiki/development/coding-guidelines.md, docs/wiki/development/setting-up-the-development-environment.md
- Add addon template and LINKFUNC macro descriptions to Coding Guidelines
- Add fast function recompiling description to Setting Up The Development Environment
=> Add addon template and fast recompiling descriptions to wiki

addons/hellfire/functions/fnc_showHud.sqf, addons/laser/functions/fnc_seekerFindLaserSpot.sqf, addons/laser/functions/fnc_shootRay.sqf
- Add a workaround for the max hardcoded range of `lineIntersectsSurfaces` (5000m). Simply attempts another ray from the end of the previous ray. It does this twice, so the new max range is 15000m, which is overcompensating.
- Change hellfire HUD seeker call to use values of current ammunition
- Fix spelling of distance in `fnc_seekerFindLaserSpot`
=> Laser seeker range improvements

docs/wiki/framework/frag-framework.md
Hard to find a reference for this, but figure it is useful to others as it's fairly common in older HEAT shells (WW2 stuff is why this even came to my attention) and modern fast-acting explosives.
It's a bit of an approximation as I had to interpolate the value of the first reference so that it was correct relative to the other values on our wiki (by using two other explosives common to both tables). The second reference in fps converts to roughly the same value in m/s so I'm content to call it good.
References:
http://axpro.mines.edu/documents/MNGN%20444_Fragmentation%20and%20Safety%20Distances%20_Examples.pdf, p.3
http://dtic.mil/dtic/tr/fulltext/u2/783941.pdf, p.25
=> Add Pentolite Gurney constant to wiki

addons/spectator/functions/fnc_ui_toggleMap.sqf
- Prevents camera panning when right-click dragging the map around
=> Disable spect camera movement while map is open

docs/wiki/feature/vector.md
Typo correction to the Vector feature description in section 2.4.   Typo in kbd tag open.
This is a simple on-line change.
=> Typo correction to wiki for Vector feature - malformed kbd tag.

addons/repair/functions/fnc_setHitPointDamage.sqf
Hello,
Since 1.67, you can  skip destruction effects if you want (see  : https://community.bistudio.com/wiki/setDamage and https://community.bistudio.com/wiki/setHitPointDamage https://community.bistudio.com/wiki/setHitIndex).
This is usefull in some cases where you don't want to see the vehicle explode and damage objects around (During a database loading for exemple).
This PR add an optional parameter  to ace_repair_fnc_setHitPointDamage to allow this new choice.
I would know if this change is possible ?
Thanks
- Add: Optional parameter `_useEffects`  to ace_repair_fnc_setHitPointDamage
- update the header
- change `params` with an optional param `"_useEffects"`
- `setDamage ` and `setHitIndex` have the new param `_useEffects`
- …
=> Add: Optional parameter to useEffects during setdamage/sethit

addons/cargo/XEH_postInit.sqf, addons/cargo/functions/fnc_loadItem.sqf, addons/common/XEH_postInit.sqf
Fix #5398
Seems like cars are hard-coded to take water damage,
`_item attachTo [_vehicle,[0,0,-100]];` can put the car below 0 ASL which triggers the effect
(tested on a 75m high hill, -70 was fine, -80 caused damage)
Once water logged the vehicle seems to be permently disabled (fixing HitEngine does not fix)
This just disables damage (`allowDamage`) on the car while in cargo
=> Fix cars loaded as cargo taking water damage

addons/common/XEH_postInit.sqf, addons/common/XEH_preInit.sqf, addons/interact_menu/functions/fnc_keyDown.sqf, addons/interact_menu/functions/fnc_renderActionPoints.sqf, addons/interact_menu/functions/fnc_renderBaseMenu.sqf
- Add condition to interact_menu allowing for UAV self-interactions
- Tested with https://github.com/uksf/modpack/blob/drone/addons/reaper/CfgVehicles.hpp#L335 and all works as intended, including when sat in other vehicles.
=> UAV Self-interactions

addons/common/XEH_postInit.sqf, addons/hellfire/XEH_postInit.sqf, addons/interact_menu/functions/fnc_keyDown.sqf, addons/interact_menu/functions/fnc_renderActionPoints.sqf, addons/interact_menu/functions/fnc_renderBaseMenu.sqf, addons/laser/functions/fnc_keyLaserCodeChange.sqf, addons/missileguidance/functions/fnc_cycleAttackProfileKeyDown.sqf
Fix #5301
Needs testing on dedicated, as `PlayerViewChanged` was unreliable in the past.
=> Add EH for UAV control, Add Hellfire support

addons/common/functions/fnc_loadPerson.sqf
Hello,
Should fix https://github.com/acemod/ACE3/issues/5456
When you load somebody inside a vehicle the [`ace_common_fnc_loadPerson`](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_loadPerson.sqf) is used. This fonction actually search `nearestObjects` of type `["Car","Air", "Tank", "Ship_F"]` to put player inside. 
Infortunatly, the taru family with crew position (exemple:` "Land_Pod_Heli_Transport_04_medevac_black_F"`) are not detected because the corresponding parents class of `"Land_Pod_Heli_Transport_04_medevac_black_F"` is : `["Land_Pod_Heli_Transport_04_medevac_F","Pod_Heli_Transport_04_crewed_base_F","StaticWeapon","LandVehicle","Land","AllVehicles","All"]`. To avoid this, the `"Pod_Heli_Transport_04_crewed_base_F"` parent class should also be search by …
=> FIX: ace_common_fnc_loadPerson don't detect Taru pod with place for crew

addons/fonts/CfgFontFamilies.hpp, addons/noidle/CfgMoves.hpp, addons/noradio/CfgEventhandlers.hpp, addons/noradio/XEH_postInit.sqf, addons/norearm/CfgActions.hpp, addons/optics/CfgEventHandlers.hpp, addons/optics/CfgOpticsEffect.hpp, addons/optics/CfgRscTitles.hpp, addons/optics/CfgWeapons.hpp, addons/optics/XEH_PREP.hpp, addons/optics/XEH_postInit.sqf, addons/optics/functions/fnc_handleFired.sqf, addons/optics/functions/fnc_onDrawScope.sqf, addons/optics/functions/fnc_onDrawScope2D.sqf, addons/thermals/config.cpp
- This pull request will perform some minor clean up on fonts, noidle, noradio, norearm, optics and thermals.
=> Cleanup some configs and array spacing

addons/spectator/XEH_postInit.sqf, addons/spectator/functions/fnc_cam.sqf, addons/spectator/functions/fnc_cam_setCameraMode.sqf, addons/spectator/functions/fnc_cam_tick.sqf, addons/spectator/functions/fnc_getCameraAttributes.sqf, addons/spectator/functions/fnc_respawnTemplate.sqf, addons/spectator/functions/fnc_setCameraAttributes.sqf, addons/spectator/functions/fnc_setFocus.sqf, addons/spectator/functions/fnc_setSpectator.sqf, addons/spectator/functions/fnc_switchFocus.sqf, addons/spectator/functions/fnc_ui_draw3D.sqf, addons/spectator/functions/fnc_ui_handleListClick.sqf, addons/spectator/functions/fnc_ui_handleMapClick.sqf, addons/spectator/functions/fnc_ui_handleMouseButtonDown.sqf, addons/spectator/functions/fnc_ui_updateHelp.sqf, addons/spectator/functions/fnc_ui_updateListFocus.sqf, addons/spectator/functions/fnc_ui_updateWidget.sqf, addons/spectator/functions/fnc_updateCameraModes.sqf
- Fix virtual spectators exiting spectator when the respawn template is active (#5440)
- Simplify/optimise some of the code used for virtual spectators
- Rename the `GVAR(camTarget)` to `GVAR(camFocus)` to stop the linter complaining (probably bad practise to use script command in a variable name anyway)
=> Fix virtual spectator breaking if template active

.travis.yml
- Title
Python 3.5 is pre-installed on Trusty environment:
>  This job ran on our Trusty environment, which is gradually becoming our default Linux environment. Read all about this [in our blog: Trusty as a default Linux is coming](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) and take note that you can add `dist: precise` in your .travis.yml file to continue using Precise.
This will just speed up the build as it won't need to download another Python version.
=> Use Python 3.5 in Travis

addons/realisticnames/CfgWeapons.hpp
`srifle_DMR_03_spotter_F` does not exist in base game, and parent srifle_DMR_03_F is scope 2
So we were adding a duplicate weapon with only the name changed??
- Hide weapon for now via `scope = 1` to avoid breaking loadouts
- Can remove later
=> Hide duplicate weapon srifle_DMR_03_spotter_F

addons/cargo/CfgVehicles.hpp, addons/dragging/CfgVehicles.hpp
- Added cargo to pallet food stacks crate
- Added cargo to water stacks crate
- Added cargo to Paper Box stacks
- Added cargo to Paper Box
- Added cargo to UAV box
- Added dragging and carry to Paper Box
- Added dragging and carry to UAV box
- Moved Land_PortableLight_single_F up to objects category
=> Added drag and Cargo ability to Orange crates

addons/cookoff/functions/fnc_cookOff.sqf, addons/main/script_mod.hpp
- Use [`selectRandomWeighted`](https://community.bistudio.com/wiki/selectRandomWeighted) command instead of function in `cookoff`
- Increase required Arma 3 version to 1.76 - `selectRandomWeighted` was added in 1.76
=> Use selectRandomWeighted 1.76 command

addons/medical/data/model.cfg
- Fixed missing semicolon in `model.cfg` for `ACE_Medcrate_Skeleton`
=> Added missing semicolon for ACE_Medcrate_Skeleton model.cfg

addons/kestrel4500/functions/fnc_generateOutputData.sqf
- The wind direction was not taken into account when calculating head- and crosswinds.
- The output of the wind direction was formatted incorrectly.
- Those changes are only relevant when AdvancedBallistics is disabled.
- Fixes #5181
=> Kestrel4500 - Fixed head- and crosswind calculation

addons/interaction/XEH_postInit.sqf, addons/interaction/functions/fnc_openDoor.sqf
- Title
There are 3 animations for carrier doors:
```
"door_1_rot","door_handle_1_rot_1","door_handle_1_rot_2"
```
`rot_2` does not seem to be used with normal action menu opening at all, so using `animationSource` does not work, because it will activate both of those animations as well and handle will end up in original position (and also be broken for action menu usage).
I didn't find any other good way to extract those handle animations, so it's just checking for the USS Freedom carrier directly and adding the handle based on the door number.
https://i.imgur.com/HzJZ058.gifv
=> Move handle on carrier doors

addons/atragmx/CfgWeapons.hpp, addons/attach/CfgWeapons.hpp, addons/captives/CfgWeapons.hpp, addons/chemlights/CfgWeapons.hpp, addons/common/CfgWeapons.hpp, addons/dagr/CfgWeapons.hpp, addons/disarming/CfgWeapons.hpp, addons/dogtags/CfgWeapons.hpp, addons/explosives/CfgWeapons.hpp, addons/flashlights/CfgWeapons.hpp, addons/hearing/CfgWeapons.hpp, addons/huntir/CfgWeapons.hpp, addons/logistics_uavbattery/CfgWeapons.hpp, addons/logistics_wirecutter/CfgWeapons.hpp, addons/main/script_mod.hpp, addons/maptools/CfgWeapons.hpp, addons/medical/CfgWeapons.hpp, addons/microdagr/CfgWeapons.hpp, addons/mk6mortar/CfgWeapons.hpp, addons/overheating/CfgWeapons.hpp, addons/rangecard/CfgWeapons.hpp, addons/sandbag/CfgWeapons.hpp, addons/spottingscope/CfgWeapons.hpp, addons/tagging/CfgWeapons.hpp, addons/trenches/CfgWeapons.hpp, addons/tripod/CfgWeapons.hpp, addons/vehiclelock/CfgWeapons.hpp
For https://github.com/CBATeam/CBA_A3/pull/744
```
class ACE_ItemCore: CBA_MiscItem {};
```
Should we keep `ACE_ItemCore` or just drop it and use the CBA item base for everything?
=> Use CBA Misc Items

addons/laser/CfgVehicles.hpp, addons/laser/functions/fnc_handleLaserTargetCreation.sqf
laserTarget fails if the turret does not have "primaryGunner" config
this adds a backup method that checks if the player's vehicle is a likely canidate for the laser's source
It effects the vanilla strider and indy hellcat chopper.
I think this is a better method than changing their configs
=> Handle laser targets from non-primaryGunner turrets

addons/advanced_ballistics/functions/fnc_handleFirePFH.sqf, extensions/advanced_ballistics/AdvancedBallistics.cpp
- Decent performance improvement compared to the old `call compile` approach
- Requires DLL rebuild.
=> AdvancedBallistics - Utilize new 'parseSimpleArray' command

addons/cargo/CfgVehicles.hpp, addons/refuel/functions/fnc_connectNozzleAction.sqf, addons/refuel/functions/fnc_disconnect.sqf, addons/refuel/functions/fnc_refuel.sqf
Fix #5438
- Make canister loadable via cargo
- Also block cargo action when being used (attached to vehicle as a nozzle)
Don't need to make it drag/carrayble as that functionality is already handled by refuel
=> Allow loading fuel canister via ace_cargo

addons/spectator/functions/fnc_ui_handleKeyDown.sqf, addons/spectator/ui.hpp
- Store the spectator display in a uiNamespace variable (so external scripts can access it #5469)
- Update the toggle hotkeys to match the docs branch waiting to be merged after release
=> Add uiNamespace variable to spectator display

addons/spectator/ui.hpp
Fix crash on start
```
File z\ace\addons\spectator\ui.hpp, line 20: '/ace_spectator_display.onLoad': Missing ';' at the end of line
Error context , _this select 0]";
ErrorMessage: File z\ace\addons\spectator\ui.hpp, line 20: '/ace_spectator_display.ace_spectator_display': '"' encountered instead of '='
```
I guess the macro doesn't like being in a quote macro
=> Fix spectator onLoad

addons/aircraft/CfgEventHandlers.hpp, addons/aircraft/CfgVehicles.hpp, addons/aircraft/Heli_Attack_01_base_F.hpp, addons/aircraft/XEH_PREP.hpp, addons/aircraft/XEH_postInitClient.sqf, addons/aircraft/XEH_preInit.sqf, addons/aircraft/XEH_preStart.sqf, addons/aircraft/config.cpp, addons/aircraft/functions/fnc_canShowEject.sqf, addons/aircraft/functions/fnc_initEjectAction.sqf, addons/aircraft/functions/script_component.hpp
- remove `*canEject` config entries;
- add Eject action with vanilla `addAction` command to appropriate helicopters.
This is replacement of #4749.
There may be another approach with getIn/getOut EH, but I decided it's more difficult.
~Question: can it happen that initPost EH fires more then once? If yes, many actions will be added.~ OK
Problems with used `moveOut` comand:
1. ~It stops engine while vanilla `Eject` doesn't (driver only).~ Fixed
1. AI subordinate just really moves out by order while with vanilla AI unit doesn't do it until he has a parachute and then he moves out.
=> Replace Helicopter eject configs with universal scripted action

addons/fastroping/functions/fnc_canDeployRopes.sqf, addons/fastroping/functions/fnc_cutRopes.sqf, addons/fastroping/functions/fnc_deployAI.sqf, addons/fastroping/functions/fnc_deployAIWaypoint.sqf, addons/fastroping/functions/fnc_equipFRIES.sqf, addons/fastroping/functions/fnc_fastRope.sqf, addons/fastroping/functions/fnc_fastRopeLocalPFH.sqf, addons/fastroping/functions/fnc_fastRopeServerPFH.sqf, addons/fastroping/functions/fnc_onCutCommon.sqf, addons/fastroping/functions/fnc_onPrepareCommon.sqf, addons/fastroping/functions/fnc_prepareFRIES.sqf, addons/fastroping/script_component.hpp
- Add animations from older Arma games (support for eg. CUP which are still using those - not including any special new animations like fancy ramps)
- Macroize animations names
- Change to in-line privatization
- Fix inverted comments for public `onPrepare(/Cut)Common` functions
=> Fastrope animations and in-line privatization

optionals/compat_r3f/CfgAmmo.hpp, optionals/compat_r3f/CfgMagazines.hpp, optionals/compat_r3f/CfgWeapons.hpp, optionals/compat_r3f/config.cpp, optionals/compat_r3f/script_component.hpp
- Change to G1 BC (AtragMx values) for the 5.56x45 and 7.62x51 bullets (G7 BC).
- Remove the R3F safety and the ghost "R3F_securite_mag", redondant with the ACE3 Safe Mode.
- ACE3 values for all RF3 suppressors.
- Adjustment between R3F `typicalSpeed`, `initSpeed` and ACE3 `airFriction` (playability for all players : AB and non-AB users and ballistically better).
- Minors updates.
=> AB : update R3F compat

addons/rangecard/functions/fnc_updateRangeCard.sqf
More uniform appearance with advanced ballistics enabled or disabled:
- Barrel length and bore height are now always visible on the range card
- Bullet diameter and bullet weight as well
=> RangeCard - Always display barrel length and bore height

addons/common/XEH_PREP.hpp, addons/common/functions/fnc_getPylonTurret.sqf
Needed for ace_pylons and rearm
It can fail if aircraft is configured with same weapon on pilot and gunner but those configurations don't really make any sense and probably won't be an issue.
=> Add ace_common_fnc_getPylonTurret func

addons/common/functions/fnc_isUnderwater.sqf
- Title
Both check if head is underwater, but from testing command is more precise. It was only made compatible with units in 1.66, so it makes sense why we used our own function before. It is not used anywhere in ACE3 though.
=> Deprecate isUnderwater (replaced by underwater command from 1.66)

addons/captives/CfgEventHandlers.hpp, addons/captives/XEH_PREP.hpp, addons/captives/functions/fnc_canLoadCaptive.sqf, addons/captives/functions/fnc_canUnloadCaptive.sqf, addons/captives/functions/fnc_handleKilled.sqf, addons/captives/functions/fnc_handleRespawn.sqf, addons/medical/CfgVehicles.hpp
- Disable "Load Patient" action if unit is dead but was unconscious before (we don't want loading of dead units do their weirdness) - `ACE_isUnconscious` flag doesn't get reset on death
- Remove handcuffs on death to prevent ability to remove them later which causes the unit to stand up and run the ragdoll again (looks quite hilarious though)
- Change "Load Captive" to show only if unit is not unconscious ("Load Patient" and "Load Captive" do the same thing and it's easier to notice someone is unconscious)
- Disable "Unload Patient" action when inside a vehicle - fix #5525 (more of a bandaid, but it makes more sense anyways)
=> Fix Load Patient/Captive actions

addons/explosives/CfgWeapons.hpp
Muzzle won't be used because explosives has a custom placing engine.
But arsenal needs this to categorize it as an "explosive"
Close #5563
=> Add trip flare to Put muzzle

tools/generate_airfriction_config.py
- This Python tool calculates optimal `airFriction` values for all ammo classes currently used in ACE3
- Can also be used to calculate `airFriction` values for 3rd party ammo classes
Example input:
`["B_556x45_Ball", [300, 500, 500], [750, 870, 910], 7, 0.151]`
Example output:
```Ammo Class: B_556x45_Ball
MaxRanges (m): [300, 500, 500]
MuzzleVelocities (m/s): [750, 870, 910]
Max. Velocity diff (m/s): 26.68
Max. Drop diff (cm): 1.98
Max. Tof diff (ms): 10.5
Optimal airFriction: 0.00130094
```
Which means that in this case, the maximum drop deviation with an `airFriction` value of `0.00130094` is around 2 cm out to 300 m with a muzzle velocity of 750 m/s and out to 500 m with a muzzle velocity between 870 m/s and 910 m/s.
=> Conversion tool: 'Ballistic coefficient' -> 'airFriction'

addons/fcs/CfgVehicles.hpp, optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
Ref last FCS PR: #5152
Will no longer be enabled by default for `Tank_F`
Mod makers can still enable with `ace_fnc_enabled`
=> Leave ACE_FCS off by default

optionals/compat_r3f/CfgAmmo.hpp
- Revert to the default G7 drag model for the 5.56x45 and 7.62x51 bullets.
- Update all `airFriction ` according with the new ACE3's ones.
=> Short R3F compat update according with the new AB drag models

optionals/compat_rhs_usf3/CfgWeapons.hpp
* Add ace_reloadlaunchers capability and ace_overpressure config to Mk 153 SMAW launcher
* Add ace_reloadlaunchers capability and ace_overpressure config to M3 MWAAS launcher
Overpressure for the Gustaf based on the vanilla `launch_RPG32_F` values and increased a bit. SMAW got default inherited values from `Launcher_Base_F`, but with a narrower cone angle.
Let me know if the values are unacceptable and i'll scale them back a bit.
=> [compat_rhs_usf3] Reload Launchers and Overpressure

addons/medical/functions/fnc_setUnconscious.sqf
- fix a timing issue that the setCaptive delay can be incorrect on a rapid switching of unconscious or long Captive Delays
=> fix the delay timing when a unit switch to Captive

optionals/compat_rhs_usf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgGlasses.hpp
Adds the new Oakley SI Ballistics googles and the googles integrated into the new shemags.
Also add's M855 Ammo which is the same as M855A1 because our A1 data is incorrect. But it doesn't matter that it's incorrect. The difference is too small to matter for such a short-range round.
The `rhs_ess_black` is not new in 3.4 as far as I can see. But it was missing.
=> RHS 3.4 Goggles and AB Ammo compat update

addons/ballistics/CfgAmmo.hpp, addons/ballistics/CfgMagazines.hpp
Accord the `typicalSpeed`, `initSpeed` and `airFriction` for the both bullets due to the difference of the ballistic trajectory in-game :
- 127x108 : `typicalSpeed = 820;` /  `initSpeed = 820;` / `airFriction = -0.00065098;`
- APDS default values: `typicalSpeed = 1060;` / `initSpeed = 1060;` / `airFriction = -0.00036;`
=> AB : same values for the both 127x108 bullets

addons/cookoff/functions/fnc_getVehicleAmmo.sqf
CUP has some dummy magazines (like `CUP_2Rnd_pylonblank_M`, ammo: `CUP_pylonblank`)
Doing createVehicle on these causes a popup config error.
Edit: this does add some cost which I don't like, but most vehicles have <10 magazines.
Also changes the transport ammo vics to use the new rearm configs.
=> Cookoff - Filter bad ammo, use new rearm config

addons/fastroping/XEH_postInit.sqf
=> Added fastrope keybind

optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
- add Ural Repair and FMTV Rearm/Refuel/Repair;
- replace `era_*_hitpoint` elements with macros;
- fix `t72bd` ERA config;
- add missing T-80 and M2A2 ERA grouping configs.
It looks like it's better/simpler to create 1 big enough ERA grouping array (e.g. 100 elements) and not mess with exact ERA hitpoints count.
In fact `rhsusf_M1078A1R_SOV_M2_D_fmtv_socom` is not real refuel vehicle, so I made refuel hook at most appropriate (for me) place.
=> Add compat for RHS 0.4.3 new vehicles

addons/explosives/functions/fnc_interactEH.sqf, addons/minedetector/functions/fnc_getDetectedObject.sqf
- Fix #5508 
Not too pretty, but UXOs behave weirdly, see https://github.com/acemod/ACE3/issues/5508#issuecomment-336666987
=> Fix defused UXOs being able to be defused again and detected by mine detector

addons/quickmount/functions/fnc_getInNearest.sqf
- Handle locked turrets (fix #5611)
- Switch to use `GetInTurret` which fixes "GetIn" event handler args
- Pass cargo index to `GetInCargo`
This should fix the issues from PR #5610
Any vic with a  gunner:
`player action ["GetInGunner", cursorObject];` // GetIn EH: `[z_1,"gunner",q,[]]`
`player action ["GetInTurret", cursorObject, [0]];` // GetIn EH: `[z_1,"gunner",q,[0]]`
The wrong turret index is probably why the driver's door gets left open.
RHS UAZ:
`player action ["GetInCargo", cursorObject];` player becomes glitched (headbug fix does nothing)
`player action ["GetInCargo", cursorObject, 4];` works as expected
=> QuickMount - fix locked seats, getIn EH

addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- Fix a specific case where fastroping could result in a teleport to [0, 0, -1]
A teleport would happen in the following situation:
- player starts fastrope
- player is moved out of the vehicle, attached to the dummy
- at the same time, rope gets cut, hook gets deleted
- server PFH just now arrives at `if (getMass _dummy != 80) exitWith {`, the dummy position gets set to 1m below nonexistant hook, teleport to [0, 0, -1] happens
See #5569.
=> Prevent fastroping teleport serverside

addons/weather/ACE_Settings.hpp, addons/weather/CfgVehicles.hpp, addons/weather/XEH_postInit.sqf, addons/weather/XEH_postServerInit.sqf, addons/weather/functions/fnc_initModuleSettings.sqf, addons/weather/functions/fnc_serverController.sqf, addons/weather/functions/fnc_updateAceWeather.sqf, addons/weather/functions/fnc_updateWind.sqf, addons/weather/init3DEN.sqf, addons/weather/stringtable.xml
- Close #5465 
- Move `setRain` to server (correctly synced in vanilla), we still want proper map data calculation
- Removed lightnings sync (synced correctly in vanilla), we didn't do anything else with it
- Moved `setWind` to only execute on server (correctly synced in vanilla), `FUNC(updateWind)` runs globally (I think), we still need to sync gusts and waves
This should resolve extreme wind bug (assuming it works). Completely untested.
=> Remove rain, lightnings and wind sync

addons/atragmx/functions/fnc_calculate_solution.sqf, addons/atragmx/functions/fnc_calculate_truing_drop.sqf, addons/atragmx/functions/fnc_update_range_card.sqf, addons/atragmx/functions/fnc_update_result.sqf, addons/atragmx/functions/fnc_update_truing_drop_data.sqf, addons/atragmx/script_component.hpp, addons/rangecard/functions/fnc_calculateRangeCard.sqf, addons/rangecard/script_component.hpp
- This greatly improves the accuracy of the MRAD output in both modules
- Old and incorrect conversion factor: 3.38 [(360 * 60) / 6400]
- New and correct conversion factor: 3.44 [54 / (5 * PI)]
=> ATragMX and RangeCard - Fixed incorrect MRAD conversions

addons/common/functions/fnc_playConfigSound3D.sqf
**Comments out Debug define that was left enabled in release version.**
- Fixes Traces getting logged to rpt especially when using mine detector.
The file [fnc_diagnoseWeapons](https://github.com/acemod/ACE3/blob/master/addons/advanced_ballistics/functions/fnc_diagnoseWeapons.sqf) also contains a debug define that is not commented out but it appears to be intentional. Unless I am mistaken by my assumption.
=> Disable Debug Define

optionals/compat_r3f/CfgWeapons.hpp, optionals/compat_rh_acc/CfgWeapons.hpp, optionals/compat_rhs_afrf3/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgWeapons.hpp, optionals/compat_rksl_pm_ii/CfgWeapons.hpp
Compat variant of #5648
I only updated the weapons we already had in compat and only added new ones were really necessary.
I noticed we are missing all RHS AK variants with NPZ which have a different railheight that the non-NPZ ones.
If someone else want's to add the missing stuff here is a table of all rail heights: https://docs.google.com/spreadsheets/d/1d5O_nC0Cq26CWGI4sqjZU9jdhArV5pkSm-VMDT7uvM4/edit?usp=sharing
=> AB compat rail/scope height update

addons/pylons/functions/fnc_showDialog.sqf, addons/pylons/menu.hpp
- Fix combo boxes cutting off. Goodbye #5649 
- 😢 
Using the old `RscCombo` type but making it look like `ctrlCombo` looks like the ideal way to get a proper combo box that doesn't cut off at an arbitrary control height limit.
=> Fix Pylons' Combo Box Cut off When There Are Too Many Magazines to List

docs/wiki/framework/refuel-framework.md
- Title
Jekyll thinks `{{ something }}` is a variable in code blocks too.
=> Fix refuel framework page build failure

addons/trenches/CfgWeapons.hpp, addons/vehiclelock/CfgWeapons.hpp
`ACE_ItemCore` is always above `CBA_MiscItem_ItemInfo` except here.
=> Fix ACE_ItemCore order

addons/spectator/functions/fnc_setSpectator.sqf
This looks incorrect.
- Set the spectator state using `_set` variable instead of `true`
=> (spectator) set correct state on unit

addons/advanced_ballistics/functions/fnc_handleFired.sqf, addons/weather/XEH_postInit.sqf, addons/weather/functions/fnc_calculateBarometricPressure.sqf, addons/weather/functions/fnc_getMapData.sqf, addons/weather/functions/fnc_serverController.sqf, addons/weather/functions/fnc_updateAceWeather.sqf, addons/weather/functions/fnc_updateHumidity.sqf, addons/weather/functions/fnc_updateTemperature.sqf
* Makes sure that all clients share the same (numeric) overcast value
* Only affects the barometric pressure calculation
* Does not affect the actual weather on the clients
Avoids barometric pressure synchronization issues between clients due to overcast drift.
Reference: https://cuel.github.io/
=> Weather - Properly sync overcast value

addons/spectator/functions/fnc_setSpectator.sqf
- unmute/unhide player when exiting spectator
previously doing `[true] call ace_spectator_fnc_setSpectator` and then `[false] call ace_spectator_fnc_setSpectator` would result in a hidden player
I'm not entirely sure this is the best way. What if the player is dead when exiting?
=> (spectator) unhide/unmute unit on exiting

addons/smallarms/CfgMagazines.hpp
- title;
- fix #5656.
5.56 mags have correct names in vanilla ATM. There is no need to disable reload tracers there.
=> Fix 5.56 Reload Tracer mags are not tracer

addons/tagging/functions/fnc_quickTag.sqf, addons/tagging/stringtable.xml
Close #5662
When using the "Last Used" setting, nothing would happen when hitting the hot key.
This changes it to just do a random X
`GVAR(quickTag == 2)` :smile:
=> Tagging - For lastUsed setting, use random X tag if none selected yet

addons/atragmx/functions/fnc_change_target_slot.sqf, addons/atragmx/functions/fnc_init.sqf, addons/atragmx/functions/fnc_parse_input.sqf, addons/atragmx/functions/fnc_sord.sqf
* The C1 coefficient needs to be updated automatically whenever the target range changes
=> ATragMX - Fixed UI (C1 vs. Distance interpolation)

addons/spectator/functions/fnc_cam.sqf, addons/spectator/functions/fnc_respawnTemplate.sqf, addons/spectator/functions/fnc_setSpectator.sqf, addons/spectator/functions/fnc_ui.sqf, addons/spectator/functions/fnc_ui_draw3D.sqf
```
[ACE] (spectator) TRACE: 85515 respawnTemplate: _newCorpse=unit1, _oldKiller=unit1, _respawn=3, _respawnDelay=10 z\ace\addons\spectator\functions\fnc_respawnTemplate.sqf:26
[ACE] (spectator) TRACE: 85515 Params: _set=false, _force=true, _hide=true z\ace\addons\spectator\functions\fnc_setSpectator.sqf:25
[ACE] (spectator) TRACE: 85515 cam: _init=false z\ace\addons\spectator\functions\fnc_cam.sqf:20
[ACE] (spectator) TRACE: 85515 : player=unit1, _hidden=false z\ace\addons\spectator\functions\fnc_setSpectator.sqf:107
Error in expression <30625 ) then {
private _intersections = lineIntersectsSurfaces [_start, _end, _c>
Error position: <lineIntersectsSurfaces [_start, _end, _c>
Error Type Any, expected Object
File z\ace\addons\spectator\functions\fnc_ui_draw3D.sqf, line 18
[ACE] …
```
=> Spectator - Fix script error in ui_draw3d

addons/cargo/functions/fnc_addCargoVehiclesActions.sqf, addons/cargo/functions/fnc_canLoadItemIn.sqf, addons/cargo/functions/fnc_initObject.sqf, addons/cargo/functions/fnc_initVehicle.sqf, addons/cargo/functions/fnc_onMenuOpen.sqf, addons/cargo/functions/fnc_startLoadIn.sqf, addons/cargo/script_component.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
Close #5685 
Use getInteractionDistance, which approximately gets a distance to the outer hull of a vehicle
Great for very large aircraft as when near the rear you might be 12m from the center but 2m from the exit ramp.
=> cargo - Improve interaction distance checks on very large vehicles.

addons/logistics_wirecutter/functions/fnc_cutDownFence.sqf
This hook could be used to script things happening when player 'touches' fence when wirecutting. Would reduce overhead if you want to script electric fences (no need for distance checks).
- add global event to wirecut start
=> Wirecutter - Add global event when cutting fences

addons/scopes/functions/fnc_adjustZero.sqf, addons/scopes/functions/fnc_inventoryCheck.sqf
* Makes manual zero adjustments for each weapon & scope combination persistent across game restarts / mission restarts / weapon or scope changes.
=> Scopes - Persistent zero adjustments (only with advanced ballistics)

addons/scopes/functions/fnc_firedEH.sqf
It was my own mistake caused by careless copy & paste in this commit: https://github.com/acemod/ACE3/commit/7fa73744e9c51195ff3bbc0b8578521868e2df2a
I can not believe that this bug was undetected for so long ...
=> Scopes - Fixed major bug in the trajectory synchronization

addons/scopes/CfgWeapons.hpp, addons/scopes/functions/fnc_calculateZeroAngleCorrection.sqf, addons/scopes/functions/fnc_firedEH.sqf, addons/scopes/functions/fnc_getBaseAngle.sqf, addons/scopes/functions/fnc_getBoreHeight.sqf, addons/scopes/functions/fnc_inventoryCheck.sqf, addons/scopes/script_component.hpp
* Added new config entry `ACE_IronSightBaseAngle` to fix the iron sight zeroing
* Added `DISABLE_DISPERSION` helper flag which allows you to disable any vanilla dispersion for testing purposes
=> Scopes - Fixed iron sight zeroing

tools/make.py
- Changes the find_depbo_tools function to look inside both root keys for each tool individually instead of as a group.
- Allowing for situations where some keys for the tools would be in different root keys 
Maybe an edge case issue but I don't see a reason not to fix it.
_Will also be making PR to project template_
=> Make.py Mikero tools detection fix

addons/advanced_ballistics/functions/fnc_calculateAmmoTemperatureVelocityShift.sqf, addons/advanced_ballistics/functions/fnc_calculateBarrelLengthVelocityShift.sqf, addons/advanced_ballistics/functions/fnc_handleFired.sqf, addons/advanced_ballistics/functions/fnc_readAmmoDataFromConfig.sqf, addons/advanced_ballistics/functions/fnc_readWeaponDataFromConfig.sqf
* Utilizes `linearConversion` where appropriate
* Limits some configuration values to numbers greater or equal than 0
=>  Advanced Ballistics - Minor performance tweaks

addons/advanced_ballistics/functions/fnc_handleFirePFH.sqf, addons/advanced_ballistics/functions/fnc_handleFired.sqf
* Reorders the abort condition checks
* Makes use of lazy evals where appropriate.
* Removes `_bulletSpeed < 100` check, which is almost never true.
=> Advanced Ballistics - Optimized abort conditions

addons/advanced_ballistics/functions/fnc_handleFired.sqf
* We need to use the natural logarithm here.
=> Advanced Ballistics - Typo: 'log' -> 'ln'

addons/microdagr/functions/fnc_updateDisplay.sqf
- change the range from 0.1km to 0.001km to allow a usage with mortar (needs excact meter values)
=> [MicroDAGR] get the meters for mortars (better rangetable calcs)

addons/common/functions/fnc_cbaSettings_loadFromConfig.sqf, addons/common/stringtable.xml, addons/gestures/stringtable.xml, addons/noradio/XEH_preInit.sqf, addons/optionsmenu/XEH_preInit.sqf
- replace `ACE3 ` and `ACE -` prefixes and suffixes with `ACE ` prefix, as discussed in Slack.
=> Unify settings and keybinds categories prefix

addons/scopes/ACE_Settings.hpp, addons/scopes/CfgVehicles.hpp, addons/scopes/functions/fnc_adjustScope.sqf, addons/scopes/functions/fnc_applyScopeAdjustment.sqf, addons/scopes/functions/fnc_canAdjustZero.sqf, addons/scopes/functions/fnc_firedEH.sqf, addons/scopes/functions/fnc_getCurrentZeroRange.sqf, addons/scopes/functions/fnc_initModuleSettings.sqf, addons/scopes/functions/fnc_inventoryCheck.sqf, addons/scopes/functions/fnc_showZeroing.sqf, addons/scopes/stringtable.xml
* Client side setting to choose the preferred zeroing method
* Replicates the behavior of the vanilla zeroing system
This allows you to zero your scope in 50 meter increments if you don't like the current adjustment turrets.
=> Scopes - Adds simplified zeroing subsystem

addons/common/functions/fnc_playConfigSound3D.sqf, addons/repair/CfgMoves.hpp, addons/repair/config.cpp, addons/repair/functions/fnc_repair.sqf
- remove sound from vanilla repair animation;
- add sound playback with `playSound3D` to repair function;
- improve `ace_common_fnc_playConfigSound3D` (doc, optional parameters, default file extension, etc);
- fix #5653.
=> Fix repair sound

addons/cargo/functions/fnc_startLoadIn.sqf, addons/common/functions/fnc_claim.sqf
- title;
- disable static weapon disassembling while it's claimed.
This will restrict interaction with static weapons which are being dragged/carried/(loaded to cargo).
I would also like to disable `Set-up the tripod` feature while it's claimed, but suddenly it's a vanilla feature and there are some troubles.
=> Lock object while loading to cargo

addons/advanced_ballistics/CfgVehicles.hpp
really doesn't matter because it's deprecated
```
String STR_ace_advanced_ballistics_muzzleVelocityVariation_DisplayName not found
String STR_ace_advanced_ballistics_muzzleVelocityVariation_Description not found
```
=> Fix ab module strings

addons/aircraft/CfgWeapons.hpp, addons/movement/functions/fnc_handleVirtualMass.sqf, addons/vehicles/CfgAmmo.hpp
Fix 
```
Updating base class M_Mo_82mm_AT->Missile_AGM_02_F, by z\ace\addons\vehicles\config.cpp/CfgAmmo/M_Mo_120mm_AT/ (original a3\weapons_f\config.bin)
Updating base class close->LowROF, by z\ace\addons\aircraft\config.cpp/CfgWeapons/M134_minigun/medium/ (original a3\weapons_f\config.bin)
Updating base class close->medium, by z\ace\addons\aircraft\config.cpp/CfgWeapons/M134_minigun/far/ (original a3\weapons_f\config.bin)
```
- aircraft - the inhertiance did nothing and can be removed
- movement - repoted here https://forums.bistudio.com/forums/topic/183856-release-candidate-branch-discussion/?do=findComment&comment=3251025
but I bet it will make it into final? doesn't hurt to print small warning in rpt.
- vehicles - weaponLockSystem was same as vanilla, I'm not even sure if we want the …
=> Minor fixes for 1.78 RC

addons/cookoff/ACE_Settings.hpp, addons/cookoff/CfgVehicles.hpp, addons/cookoff/functions/fnc_handleDamage.sqf, addons/cookoff/stringtable.xml, docs/wiki/framework/cookoff-framework.md
- Add cook-off probability for vehicles. Configurable via config value `ace_cookoff_cookoffProbability` for tanks and APCs. ACE setting `ace_cookoff_probabilityCoef ` is used as a multiplier for the probability. Higher values mean cook-off is more likely.
- Probability values (up for discussion, figured tanks less likely to cook-off):
- `Tank_F: 0.5 (50%)`
- `Wheeled_APC_F: 0.8 (80%)`
- `ace_cookoff_probabilityCoef 1 (multiplier)`
- Tweak the way cook-off works somewhat (major impact on end-effect)
- Increased damage threshold for other hit locations on tanks, but a high enough hit will cause instant destruction. This means high-damage munitions (Javelin, Hellfire, GBU, etc) are capable of instantly destroying heavy armour like they should be able …
=> Cook-off probability and cook-off tweaks

addons/advanced_ballistics/ACE_Settings.hpp, addons/advanced_ballistics/CfgVehicles.hpp, addons/advanced_ballistics/functions/fnc_handleFirePFH.sqf, addons/advanced_ballistics/functions/fnc_handleFired.sqf, addons/advanced_ballistics/functions/fnc_initModuleSettings.sqf, addons/advanced_ballistics/script_component.hpp, addons/advanced_ballistics/stringtable.xml
Replaced `simulateForSnipers`, `simulateForGroupMembers`, `simulateForEveryone`, `disabledInFullAutoMode` and `simulationRadius` with some automagic.
Advanced Ballistics is now only running if:
a) The projectile is local
b) The projectile is a tracer (or has a visible bullet trace effect) and is reasonably close to the player
=>  Advanced Ballistics - Removed all unnecessary settings

addons/cargo/functions/fnc_paradropItem.sqf, addons/cargo/functions/fnc_unloadItem.sqf, addons/interaction/ACE_ZeusActions.hpp, addons/medical/functions/fnc_actionPlaceInBodyBag.sqf, addons/spectator/functions/fnc_compat_spectatorBI.sqf
=> Fix enum errors

addons/advanced_ballistics/functions/fnc_handleFired.sqf
Fixes `_maxTime` calculation if `airFriction == 0`.
=> Advanced Ballistics - Avoids a possible division by zero

addons/advanced_ballistics/functions/fnc_handleFired.sqf, addons/winddeflection/functions/fnc_handleFired.sqf
* Do not run the PFH for remote projectiles unless they are tracers
=> Wind Deflection - Only track remote bullets if they are tracers

addons/parachute/XEH_preInit.sqf, addons/parachute/functions/fnc_handleInfoDisplayChanged.sqf, addons/parachute/stringtable.xml
- Currently broken, because `cadetMode` is synonymous with `true` now
- solves part of #5596
=> add setting to hide freefall altimeter, ref #5596

addons/map/functions/fnc_updateMapEffects.sqf
Close #5830
Dead player had very small velocity (0.001) for a bit after dying, maybe from ragdoll
Caused mapshake to trigger on respawn screen (which I guess uses the same map)
=> Map - Don't shake map when player is dead

addons/advanced_throwing/CfgAmmo.hpp, addons/advanced_throwing/functions/fnc_throw.sqf
Close #5835
- Add config to GrenadeCore (IRStrobeBase: GrenadeCore)
- Verify array is valid 3d vector in throw.sqf
=> AdvThrow - Fix torque script error for IR strobes

addons/common/XEH_PREP.hpp, addons/common/XEH_postInit.sqf, addons/common/XEH_preInit.sqf, addons/common/functions/fnc_switchPersistentLaser.sqf, addons/common/stringtable.xml
- add automatically enabled laserpointer/flashlight after weapon switch or vehicle enter/exit.
It's very useful in coop modes (where laserpointer are used IMO) when you often have to switch to launcher or enter/exit vehicles. In vanilla laserpointer is disabled after these actions and you have to switch it on each time.
Option is added to `ACE Weapons` category (after #5815), which I plan to extend with some uncategorized settings.
=> Add persistent laserpointer

addons/spectator/functions/fnc_cam.sqf, addons/spectator/functions/fnc_cam_prepareTarget.sqf
Using 3rd person follow in spectator caused hard game crash.
It pushed camera out to infinity
```
TRACE: 9649 pre1: _zoom=1, _zoomTemp=-3.48678e+009 z\ace\addons\spectator\functions\fnc_cam_prepareTarget.sqf:28
TRACE: 9649 pre2: ace_spectator_camDistance=1, ace_spectator_camDistanceTemp=-3.48678e+009 z\ace\addons\spectator\functions\fnc_cam_prepareTarget.sqf:29
TRACE: 9649 new: ace_spectator_camDeltaTime=0.171005, _zoomTemp=3.13811e+010 z\ace\addons\spectator\functions\fnc_cam_prepareTarget.sqf:34
TRACE: 9649 x: _bbd=[1.6,2.2,2], _distance=3.13811e+010 z\ace\addons\spectator\functions\fnc_cam_prepareTarget.sqf:40
```
1.78 changed BIS_fnc_lerp, both files still exist but the one that gets used has changed.
Current (a3\functions_f\animation\interp)
```
params [["_a", 0.0, [0.0]], ["_b", …
```
=> Spectator - Fix BIS_fnc_lerp causing crash in 3rd person spectator

addons/overpressure/functions/fnc_firedEHBB.sqf, addons/overpressure/functions/fnc_overpressureDamage.sqf
@Neviothr 
Blocks backblast damage if not using ace medical AND damage is disabled via `allowDamage`
=> Overpressure - Don't add backblast damage if blocked

tools/make.py
- change the find_depbo_tools function to detect if the key it found has values or not. 
should fix @Dystopian issue when attempting to make a release build
=> Make.py Mikero tools duplicate key fix

addons/ballistics/CfgAmmo.hpp, addons/ballistics/stringtable.xml
`ACE_338_Ball` -> `.338 Lapua Scenar 300 gr`
* Fixes bullet length
* Fixes magazine name and description
=> Ballistics - Fix .338 misnomer

addons/realisticnames/CfgWeapons.hpp, addons/vehicles/CfgWeapons.hpp
- ~~Adds magazine from HE muzzle to AP muzzle for Blackfish Autocannon (`autocannon_40mm_VTOL_01`)~~
- Removes muzzle tweak from all autocannons in ace_vehicles to fix problems with inheriting from autocannon classes.
- Fixes #5847
- Changes displayName to `"L/60 Bofors Autocannon"`. See reason below.
=> Fix missing HE magazine for Blackfish Autocannon.

addons/cookoff/CfgEden.hpp, addons/cookoff/XEH_postInit.sqf, addons/cookoff/functions/fnc_cookOffBox.sqf, addons/grenades/functions/fnc_incendiary.sqf
- Add second eden attribute to boxes/vehicles to toggle the ammunition cook off independently
- Remove the general cook off toggle from boxes (only ammunition cook off is relevant)
- Remove the `GVAR(enableAmmoCookoff)` setting condition from boxes as they already have their own setting `GVAR(enableAmmobox)`
- Make the eden default values respect the ace_setting value
The aim here is to change the way boxes respect cook off settings and make the UX cleaner.
Old behaviour:
Boxes are sharing both possible attributes vehicles use to toggle their individual cook off components (`GVAR(enableAmmoCookoff)` and `GVAR(enable)`) as well as the global setting for `GVAR(enableAmmoCookoff)` and their own setting `GVAR(enableAmmobox)`.
New behaviour:
Boxes only …
=> Improve cook off settings UX

addons/spectator/functions/fnc_cam.sqf, addons/spectator/functions/fnc_cam_setCameraMode.sqf
This is a weird engine behaviour where draw3D doesn't work if the current camera unit is not alive (or going to respawn), so we switch to a temporary agent unit while in free camera to work around this edge case.
Closes #5856
=> Fix draw3D in specator free camera when perma-dead

addons/common/functions/fnc_endRadioTransmission.sqf
Add's ACE_endRadioTransmissions Event that can be hooked by other Radio mods.
The TFAR code causes Problems in combination with spectator. TFAR 1.0 has a new function that handles that but I don't want to keep adding a TFAR 1.0 check into here and modify this everytime something changes. So I just added one Event for all Radio mods.
Also calling `TFAR_fnc_onDDTangentReleased` will throw a deprecation warning with 1.0. So the old code should be removed once the new version is released and properly gained traction.
=> Add endRadioTransmissions Event

addons/spectator/XEH_PREP.hpp, addons/spectator/functions/fnc_ui_handleKeyDown.sqf, addons/spectator/functions/fnc_ui_handleLoad.sqf, addons/spectator/ui.hpp
- ACRE2 v2.5.1 will have `acre_api_fnc_addDisplayPassthroughKeys` function (https://github.com/IDI-Systems/acre2/pull/437) for better compatibility with all spectator systems. It will hook all required buttons (only "Mute Spectators" as of this time) and also support CBA's new multiple keybinds.
=> Spectator - Use ACRE2 add display passthrough keys API

addons/common/XEH_postInit.sqf, addons/main/script_mod.hpp, addons/movement/functions/fnc_handleVirtualMass.sqf
Adds a big `IGNORE THIS` to start of on screen error
I had to change var name to make it fit
Also bump required cba/arma ver
=> Attempt to make enum errors more clear

addons/arsenal/XEH_postInit.sqf, addons/arsenal/functions/fnc_addVirtualItems.sqf, addons/arsenal/functions/fnc_removeVirtualItems.sqf
- Previously adding / removing virtual items would do:
`_object setVariable [QGVAR(virtualItems), _cargo, _global];`
which is not the intended behavior, now the func is re-ran on every machine locally to avoid overriding local changes every time you add / remove an item.
- Also add support for passing false as second argument for both of those functions, previously it would error out.
=> Fix global bool behavior for add / remove virtual items

addons/common/XEH_PREP.hpp, addons/common/XEH_postInit.sqf, addons/common/functions/fnc_cbaSettings_transferUserSettings.sqf
Transfer old ace setting to the cba setting profile var
Should make the conversion smoother for normal users.
Example output:
```
[ACE] (common) INFO: -Transfering old ACE_Settings to CBA-
[ACE] (common) INFO: Transfering setting [ace_interact_menu_alwaysUseCursorSelfInteraction: true] returned true
[ACE] (common) INFO: Transfering setting [ace_interact_menu_menuBackground: 2] returned true
``
=> Transfer old client settings to CBA

addons/arsenal/functions/fnc_buttonHide.sqf, addons/arsenal/stringtable.xml
- Said string was lost while merging the german translation a while back, it has been added back.
- The unused code in buttonHide can be safely removed, it's a remnant from when I was designing the left panel a month ago.
=> Fix ACE arsenal missing string and unused code in buttonHide

addons/laserpointer/ACE_Settings.hpp, addons/reload/ACE_Settings.hpp
- move uncategorized `Laser Pointer` and `Check ammo on weapon reload` settings to `ACE Weapons` category. `Display text on grenade throw` will be moved there after #5581 (when?).
Should these uncategorized settings be moved to `ACE Vehicles`?
- `Cook-off probability coefficient`
- `Gforces Effects`
- `Overpressure Distance Coefficient`
=> Add category for laserpointer and reload settings

addons/slideshow/CfgVehicles.hpp
Slideshow is mission utility not setting
- Change ace_slideshow_module.scope from 1 to 2
=> Revert slideshow module to scope = 2

addons/common/script_component.hpp
- Allow digging trenches on some jungle maps (e.g. Prei Khmaoch Luong)
Probably this whitelist and blacklist should be included in CfgSurfaces to allow 3rd party mods to whitelist their surfaces on purpose.
=> Adjusted dig surface whitelist for jungle maps

addons/scopes/functions/fnc_firedEH.sqf, addons/scopes/functions/fnc_getBaseAngle.sqf, addons/scopes/functions/fnc_getBoreHeight.sqf, addons/scopes/functions/fnc_inventoryCheck.sqf
* Unifies the 'getBaseAngle' & 'getBoreHeight' API
* Fixes the issue that the `boreHeight` and `baseAngle` information is always used from the local player
We should probably cache the calculation or use publicVariables instead at some point.
=> Scopes - Fix 'boreHeight' and 'baseAngle' MP synchronization

addons/attach/functions/fnc_attach.sqf, addons/attach/functions/fnc_detach.sqf, addons/attach/functions/fnc_placeApprove.sqf
- Add space at the bottom of hint to make it look nicer
- Before: 
- After:
=> Make attach/detach hint look uniform

addons/advanced_ballistics/ACE_Settings.hpp, addons/advanced_fatigue/ACE_Settings.hpp, addons/cargo/ACE_Settings.hpp, addons/common/functions/fnc_cbaSettings_loadFromConfig.sqf, addons/cookoff/ACE_Settings.hpp, addons/finger/ACE_Settings.hpp, addons/frag/ACE_Settings.hpp, addons/hearing/ACE_Settings.hpp, addons/hitreactions/ACE_Settings.hpp, addons/laser/ACE_Settings.hpp, addons/map/ACE_Settings.hpp, addons/map_gestures/ACE_Settings.hpp, addons/medical/ACE_Settings.hpp, addons/medical_menu/ACE_Settings.hpp, addons/nametags/ACE_Settings.hpp, addons/nightvision/ACE_Settings.hpp, addons/overheating/ACE_Settings.hpp, addons/overpressure/ACE_Settings.hpp, addons/pylons/ACE_Settings.hpp, addons/refuel/ACE_Settings.hpp, addons/repair/ACE_Settings.hpp, addons/respawn/ACE_Settings.hpp, addons/scopes/ACE_Settings.hpp, addons/switchunits/ACE_Settings.hpp, addons/vehiclelock/ACE_Settings.hpp, addons/viewdistance/ACE_Settings.hpp, addons/winddeflection/ACE_Settings.hpp
Adds proper min/max for slider settings
Without it would use `[-1, 5000, 0, 1]` because it needed to handle long distances, but that's pretty bad for settings in the 0-1 range.
These values were a little tricky to come up with, some of them are a little subjective.
I tried to give plenty of room for the min/max as they are hard limits.
e.g. medical_bleedingCoefficient has max of 25, which I think should be ok
There also are some special cases where -1 means something else, I tried to check everything, but this could use a thorough review.
=> Add slider settings

addons/arsenal/functions/fnc_onKeyDown.sqf
- Add Ctrl+F, Ctrl+A, and Ctrl+X support for ACE Arsenal
Pressing it while no search field are in focus: select left field
Pressing it while a search field is in focus: select the other field.
=> Add Ctrl+F search shortcut for ACE Arsenal

addons/nightvision/XEH_postInit.sqf, addons/nightvision/functions/fnc_changeNVGBrightness.sqf, addons/nightvision/functions/fnc_onVisionModeChanged.sqf
- get back brightness control from 3.11 when NV effects disabled with `ace_nightvision_effectScaling`==0.
=> Add brightness control when NV effects disabled

addons/fastroping/CfgVehicles.hpp
Attributes that are specific to objects are saved even when the default value is set, so the helicopters using this one would always be equipped with FRIES if the checkbox had ever been toggled.
=> Fix FRIES being applied when attribute unchecked

addons/common/XEH_preInit.sqf, addons/common/functions/fnc_getVehicleIcon.sqf, addons/interact_menu/functions/fnc_createVehiclesActions.sqf
- Make `interact_menu` function `createVehiclesActions` (used by `cargo`) use `common` function `getVehicleIcon` which utilises caching (used by `spectator` currently).
- Consequently remove a dependence on external BI function `BIS_fnc_textureVehicleIcon`
=> Use common icon function for vehicle actions

docs/wiki/framework/atragmx.md
```
The page build failed for the `master` branch with the following error:
The variable `{{-15,0}` on line 15 in `wiki/framework/atragmx.md` was not properly closed with `}}`. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-terminated/.
```
=> Fix Jekyll

addons/common/functions/fnc_canDig.sqf, addons/trenches/README.md
- Add config switches to allow 3rd party mods to white/blacklist single surfaces for digging.
Current black/whitelist macros could be preserved otherwise a lot of config entries have to be made. Plus some maps could be misconfigured.
=> Added config params for white/blacklisting digging

addons/laser/XEH_postInit.sqf
Fix #5938
Fixes HUD PFEH running after exiting uav interface.
=> Laser - Reset hud when exiting UAV

addons/scopes/functions/fnc_adjustScope.sqf
=> Scopes - Fix undefined enum types

addons/explosives/functions/fnc_addCellphoneIED.sqf, addons/explosives/functions/fnc_onIncapacitated.sqf
- move `_code` var to outer scope, close #5808
- close cellphone dialog when being killed
=> Fix(explosives): Selecting a cellphone as an IEDs trigger would throw an error

addons/arsenal/XEH_PREP.hpp, addons/arsenal/functions/fnc_portVALoadouts.sqf, addons/arsenal/stringtable.xml, addons/arsenal/ui/RscCommon.hpp
- Adds a function that can be called to port over BI VA loadouts to ACE Arsenal.
=> Add a function to port BI VA loadouts to ACE Arsenal

addons/frag/functions/fnc_doSpall.sqf
- Update spalling function to use `selectRandomWeighted`
This slightly changes distribution of size selected, previously the random selection wasn't uniform anyway because it was using the `round` command. The new distribution will select "small" more often than "medium" whereas previously it was the other way around, but I figure it makes sense to decrease probability with size in the context of spalling.
=> Use engine command to select weighted spall size

addons/spectator/config.cpp
- Revert the template display name back to "ACE Spectator" instead of "Spectator" (disambiguate from BI's "Spectator")
=> Fix displayName of spectator respawn template

addons/arsenal/RscDisplayMain.hpp
`File z\ace\addons\arsenal\RscDisplayMain.hpp, line 20: '/RscDisplayMain/controls/GroupTutorials/Controls/ace_arsenal_mission.animTextureNormal': Missing ';' at the end of line`
=> Arsenal - Add Missing semicolons

addons/arsenal/functions/fnc_scanConfig.sqf
Fix #5983
Uses same logic as bis's arsenal
`_scope = if (isnumber (_class >> "scopeArsenal")) then {getnumber (_class >> "scopeArsenal")} else {getnumber (_class >> "scope")};`
What gets filtered with my modset:
```
rhs_weap_ak74m_zenitco01_npz [2:0]
rhs_weap_ak74m_zenitco01_npz_grip1 [2:0]
rhs_weap_ak74m_zenitco01_npz_afg [2:0]
rhs_weap_ak105_zenitco01_npz [2:0]
rhs_weap_ak105_zenitco01_npz_grip1 [2:0]
rhs_weap_ak105_zenitco01_npz_afg [2:0]
rhs_weap_ak104_zenitco01_npz [2:0]
rhs_weap_ak104_zenitco01_npz_grip1 [2:0]
rhs_weap_ak104_zenitco01_npz_afg [2:0]
rhs_weap_ak103_zenitco01_npz [2:0]
rhs_weap_ak103_zenitco01_npz_grip1 [2:0]
rhs_weap_ak103_zenitco01_npz_afg [2:0]
rhs_weap_ak74m_dtk [2:0]
rhs_weap_ak105_pgs64 [2:0]
hlc_rifle_G36A1_CMAG [2:0]
hlc_rifle_G36A1AG36_CMAG [2:0] …
```
=> Arsenal - Filter items with scopeArsenal = 0

addons/captives/XEH_postInit.sqf, addons/captives/functions/fnc_doEscortCaptive.sqf, addons/common/functions/fnc_errorMessage.sqf, addons/common/functions/fnc_isFeatureCameraActive.sqf, addons/goggles/XEH_postInit.sqf, addons/goggles/script_component.hpp, addons/main/script_macros.hpp, addons/parachute/functions/fnc_handleReserve.sqf, addons/tacticalladder/functions/fnc_handleInteractMenuOpened.sqf, addons/tacticalladder/functions/fnc_handleKilled.sqf, addons/tacticalladder/functions/fnc_handlePlayerChanged.sqf, addons/tacticalladder/functions/fnc_handleUnconscious.sqf
- add parentheses to `GETVAR` and `ARR_SELECT` macros;
- remove superfluous parentheses in some scripts.
=> Add parentheses to GETVAR macros

addons/maverick/stringtable.xml, addons/realisticnames/CfgMagazines.hpp, addons/realisticnames/CfgVehicles.hpp, addons/realisticnames/stringtable.xml
* Use "sMG" instead of "SMG" as abbreviation for German "schweres Maschinengewehr".
* Rename "Punisher" to "Karatel". It seems odd to me to use translations for names. **Discussion requested**.
* Rename "KamAZ" to "KamAS" and "ZSU-35 Tigris" to "SSU-35 Tigris" in German translations. The Cyrillic letter `з` is transcribed as `s` in German.
* Use `ß` instead of `ss` in all German strings where applicable.
* Rename "TAR-21 EGLM" to "GTAR-21 EGLM". 
* Corrected some German translations for camo variants of rifles.
* Rename "M249" to "FN Minimi". M249 is the American designation, but given the Syndicat which uses it is francophone and Tanoa is not in any way connected to the US, i would prefer using the producer's name. **Discussion requested**.
* Rename "Hydra 70" pylon magazine to "Hydra 70 …
=> Updates to realisticnames

addons/maverick/CfgAmmo.hpp, addons/maverick/CfgMagazines.hpp, addons/maverick/CfgWeapons.hpp, addons/maverick/README.md, addons/maverick/config.cpp, addons/maverick/stringtable.xml
* CSAT was sad that NATO had it's new Maverick L, so they decided they needed a semi-active laser homing air-to-ground missile themselves. Seems that Russian KH-25ML fits the job.
=> Add Kh25ML Laser Guided AGMs

docs/wiki/framework/missile-guidance-framework.md
- In the code examples for seeker types and attack profiles config, class names were switched between both.
=> Fix typos in missile guidance framework wiki page

addons/explosives/XEH_postInit.sqf, addons/explosives/XEH_preInit.sqf, addons/explosives/functions/fnc_setPosition.sqf, addons/markers/XEH_postInit.sqf, addons/markers/functions/fnc_sendMarkersJIP.sqf, addons/markers/functions/fnc_setMarkerJIP.sqf
- simplification using newish tools
Needs testing in two ways: first if it works, secondly if it's even still needed.
marker synch:
explosives synch:
=> use ownerEvent instead of game logics

addons/common/XEH_postInit.sqf
- title
Question is if this breaks anything else? Maybe just apply it to enemy groups?
=> make setHidden use forgetTarget

addons/common/functions/fnc_numberToDigits.sqf, addons/common/functions/fnc_numberToDigitsString.sqf, addons/parachute/functions/fnc_showAltimeter.sqf
- Deprecate common function `numberToDigitsString` in favour of `CBA_fnc_formatNumber`
- Optimise common function `numberToDigits`
=> Deprecate common function numberToDigitsString

addons/spectator/functions/fnc_ui_toggleMap.sqf
Instead of centering on the camera object use `positionCameraToWorld` to
get the actual viewpoint
=> Center spectator map correctly in FPP

addons/spectator/functions/fnc_ui_updateHelp.sqf
Could result in an on-screen error if the spectator API was used in a scheduled environment.
=> Serialize spectator help control variable

addons/nightvision/CfgEventHandlers.hpp, addons/nightvision/XEH_postInit.sqf, addons/nightvision/functions/fnc_onFiredPlayer.sqf, addons/nightvision/functions/fnc_setupDisplayEffects.sqf
Fix #6017 - Delete grain effect when opening escape menu in SP
Fix #5961 - Just use `cutText`
=> NVG - Fix grain and color effects

addons/spectator/functions/fnc_respawnTemplate.sqf, addons/spectator/functions/fnc_ui_draw3D.sqf, addons/spectator/functions/fnc_ui_handleMapDraw.sqf, addons/spectator/functions/fnc_ui_updateIconsToDraw.sqf, addons/spectator/functions/fnc_ui_updateListEntities.sqf
`count` is only quicker than `forEach` when the final command returns a
boolean or nil. `forEach` is quicker if the final command returns any
other data type.
=> Optimise spectator loops

addons/overpressure/functions/fnc_firedEHBB.sqf
=> Fix back blast if damage not allowed

addons/atragmx/functions/fnc_update_gun.sqf, addons/atragmx/functions/fnc_update_gun_ammo_data.sqf
The bullet mass (in [grains](https://en.wikipedia.org/wiki/Grain_(unit))) is still going to be limited to integers.
Closes: #6040
=> ATragMX - Allow one decimal place for the bullet mass

addons/arsenal/functions/fnc_fillRightPanel.sqf, addons/arsenal/ui/RscAttributes.hpp
- Match case for magazines in fillRightPanel.
For some reason you're able to have different case between the entry in the weapon magazines array and its actual configName, meaning that some mags won't show up in the currentMag and currentMag2 tabs even tho they should.
=> Match case for magazines in fillRightPanel (ACE Arsenal)

addons/common/functions/fnc_fixPosition.sqf
If you carry "house" type object (like `Portable light`) inside building and drop it, it will be aligned to terrain level instead of building floor. This can be avoided with `lineIntersectsSurfaces` using.
This is #3497 partial rewrite.
=> Fix house-type object carrying in building

optionals/compat_r3f/CfgWeapons.hpp
- Dispersion overhaul for all R3F rifles :
- Assuming that a dispersion depends of many, many parameters (rifle/ammo harmonisation, position, supports or not, shooter, etc ...).
- Assuming that a dispersion is not a constant value but increases with the distance.
- Assuming that a bipod is not a Bench Rest support.
- Assuming that all muzzles velocities are correct with RL values.
- According with https://github.com/acemod/ACE3/pull/5755 and the `0.562` value (should be increased a little bit imo).
For all rifles, I got the corresponding distance at the end of the supersonic domain (approximately Mach 1.2 or 408 m/s at the normal conditions) with Strelok Pro and applied a dispersion's square of 50/50 cm for the assault rifles, a dispersion's square of 30/30 cm for the Marksman and Sniper …
=> R3F compat: dispersion overhaul & AtragMx presets

addons/medical_ai/XEH_postInit.sqf
- Fix medical AI not being enabled when the medical `enableFor` setting was set to 1 with basic medical
The `enableFor` should have no effect when used with basic medical. Fixes #6020, #6073.
=> Fix medical AI activation

addons/arsenal/defines.hpp, addons/arsenal/functions/fnc_addVirtualItems.sqf, addons/arsenal/functions/fnc_onArsenalOpen.sqf, addons/arsenal/functions/fnc_scanConfig.sqf, addons/arsenal/stringtable.xml, addons/arsenal/ui/RscAttributes.hpp
- Change backpack check in scanConfig and addVirtualItems for a better one #6082
- Convert remaining scope checks in scanConfig that were somehow forgotten in #5988 
- Add IDCs to menuBar buttons and disable import in MP #6061
- Add tooltips for the remaining menuBar buttons
=> Misc arsenal fixes

addons/huntir/CfgVehicles.hpp, addons/huntir/functions/fnc_huntir.sqf
Fix #6093
`[_nearestHuntIRs select 0] call FUNC(cam);` would pass nill
Also delay opening GUI for a frame to prevent issue with interaction menu
=> HuntIR - Fix connecting when ammo is null

addons/cargo/menu.hpp
- Small change to make the cargo menu a little nicer (remove lower empty space)
- Before: 
- After:
=> Cargo - Remove excess lower empty space in menu

addons/nightvision/ACE_Settings.hpp, addons/nightvision/XEH_postInit.sqf, addons/nightvision/functions/fnc_pfeh.sqf, addons/nightvision/stringtable.xml
- Add a seperate setting for NVG noise intensity
A seperate setting for this makes sense as it can cause headaches with long time use. The other effects do not cause this issue. Was also requested in #3594 by @ghost.
=> Add seperate setting for NVG noise intensity

addons/scopes/functions/fnc_firedEH.sqf, addons/scopes/functions/fnc_getCurrentZeroRange.sqf
Fix #6126
Minor performance improvments in firedEH
Fix in getCurrentZeroRange, was using adjustment elev (defaulted to 300) when gun was non-scope-adjustable
Had major effect on pistols, but effected all guns
=> Scopes - Use real zero for non-adjustable scopes

addons/arsenal/functions/fnc_onArsenalOpen.sqf
Tag @Alganthe
This pretty much matches the args passed by the vanilla event:
```
[missionnamespace,"arsenalOpened",[_display,_toggleSpace]] call bis_fnc_callscriptedeventhandler;
```
e.g. we add extra buttons to allow exporting gear to the format we want
=> Arsenal - Pass arsenal dispay to displayOpened event

addons/common/functions/fnc_cbaSettings.sqf
`_settingsConfig >> _settingName >> "movedToSQF"`
_settingsConfig was the missionConfig, not main config
=> CBA Settings Conversion - Fix movedToSQF

addons/common/functions/fnc_switchPersistentLaser.sqf
- increase `sunOrMoon` threshold because some maps are very dark even when `sunOrMoon == 1`;
- add loadout EH as activator because when player drops secondary weapon, laser is disabled too.
=> Small changes to persistent laserpointer

addons/pylons/XEH_postInit.sqf, addons/pylons/functions/fnc_configurePylons.sqf, addons/pylons/functions/fnc_showDialog.sqf
Fix  #6088
- Use removeWeaponTurret instead of removeWeaponGlobal
- Fix "Too Far" warning showing on completion
Tag @654wak654
I have no idea why `removeWeaponGlobal` doesn't work for pilot seat of some RHS helis, but `removeWeaponTurret` works just fine.
=> Pylons - Fix old weapons not being removed

addons/nightvision/ACE_Settings.hpp, addons/nightvision/XEH_preInit.sqf, addons/nightvision/functions/fnc_onFiredPlayer.sqf, addons/nightvision/initSettings.sqf, addons/nightvision/stringtable.xml
Also convert to cba settings
Close #6119
=> NightVision - Add setting for shutter effects

addons/arsenal/functions/fnc_initBox.sqf
- Remove the exceptions from the ace_common_fnc_canInteractWith call.
=> Fix ACE Arsenal interaction condition

addons/arsenal/ACE_Arsenal_Stats.hpp, addons/arsenal/XEH_PREP.hpp, addons/arsenal/functions/fnc_statTextStatement_scopeMag.sqf, addons/arsenal/stringtable.xml
=> Arsenal - Add stat for scope magnification

addons/ballistics/ACE_Arsenal_Stats.hpp, addons/scopes/ACE_Arsenal_Stats.hpp, addons/scopes/config.cpp, addons/scopes/stringtable.xml
- Hide some ballistics stats if the config entries they use aren't defined (ballistic coef / bullet mass / mag muzzle velocity) to avoid "weird" looking stats in the GL tab.
- Add scope horizontal and vertical limits stats.
=> Scope stats and ballistic stats improvement

addons/cargo/CfgVehicles.hpp, addons/cargo/XEH_postInit.sqf, addons/cargo/functions/fnc_initObject.sqf, addons/cargo/functions/fnc_initVehicle.sqf
- replace per-class cargo init with automatic init of all configured classes;
- fix `Static` classes not initialized properly;
- remove container ruins from config.
No more need to additionally init some classes in `XEH_postInit.sqf`. Just add config values.
Also placed in editor `Portable Light` ATM can't be loaded because it's kind of `Static` class and should be initialized accordingly. This PR fixes that.
=> Cargo - Improve class initialization

docs/wiki/feature/optionsmenu.md
- Add a note saying that the options menu is deprecated in the doc, the same that is in the ACE settings page.
=> Add note in options menu doc

addons/arsenal/functions/fnc_handleStats.sqf
- Shorten `handleStats` function window resize code by getting rid of `switch`
=> Arsenal - Shorten handleStats window resize

optionals/compat_r3f/CfgAmmo.hpp, optionals/compat_r3f/CfgWeapons.hpp
- update all `airFriction` for the Marksman and Sniper ammos with the [generate_airfriction tool](https://github.com/acemod/ACE3/blob/master/tools/generate_airfriction_config.py) by @ulteq.
Many thanks Ruthberb. :)
- update 5.56, 7.62 and 12.7 `ACE_ammoTempMuzzleVelocityShifts` for a zero MV shift at 15°C.
(same `ACE_muzzleVelocities` and `initSpeed` in-game for a better BDC reticle compatibility between the both ballistics).
- update the `R3F_762x51_Ball2` with the `ACE_762x51_Ball_M993_AP` [values](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L226).
- update the AtragMx presets' airFrictions, MV vs. T°C tables and minor fixes.
=> AB and ACE3 ballistic : compat r3f updated

addons/slideshow/functions/fnc_createSlideshow.sqf
Slideshow Action vaiable names would not be named on clients because counting was only done on the server, this would result in all actions on one object showing up in the same slideshow set
Changed:
Moved counting outside of Server Scope, therfore counting is also done on the client and everything works correctly
PR as discussed with @jonpas on slack, tested both locally and on dedicated server
=> Fixed Slideshow action numbering

optionals/compat_r3f/CfgMagazines.hpp, optionals/compat_r3f/CfgWeapons.hpp
- update the AtragMx presets' `Scope Base Angle` for all rifles :
**From the ACE3 Slack by @ulteq**
>I have an idea how you could calculate it yourself with the current ace3 release.
>1. Load your custom profile (with an arbitrary scope base angle) into the ATragMX
>2. Open the Gun/Ammo Page and close it with the 'Done' button.
>3. Execute `copyToClipboard Str(ace_atragmx_workingMemory select 3);` into the debug console
>This should dump the correct scope base angle for the current profile into the windows clipboard.
As usual, many thanks for your help. :)
- fix my splendid mistakes to the J4,J8 and J10 `ACE_ScopeAdjust_Vertical`.
- update the CfgMagazines according to the new Gunlist.
=> Compat R3F: #6171 updated

addons/cargo/functions/fnc_paradropItem.sqf
=> Fixed airdrops sink in the ground

addons/hitreactions/functions/fnc_fallDown.sqf
=> Fix undefined variable in hitreactions_fnc_fallDown

addons/explosives/CfgEventHandlers.hpp, addons/reload/CfgEventHandlers.hpp
No reason to call `_this select 0` 7 times in total.
Improvement should be around 0.03ms per call. Yeah. Not much.
Gonna take a look at taking items from containers in general. Maybe I can find more improvements.
Biggest cause of lag when taking items from containers in my setup seems to be ASR AI. config lookup for uniform/vest/backpack each time you take whatever item even if your clothing didn't change.
=> Improve Reload TakeEH

addons/realisticnames/CfgWeapons.hpp, addons/vehicles/CfgVehicles.hpp, addons/vehicles/CfgWeapons.hpp
Close #6220
Vanilla 1.82 changes: Some tanks now have HEAT rounds, APCs seem to have much more 30mm ammo, they split up the 2000rnd tank mg into individual belts, same with HMGs
- Now use vanilla magazine loadouts for most vehicles
- mem2 weapons no long exist
- cleanup configs
=> Cleanup ace_vehicles for 1.82

addons/repair/dev/draw_showRepairInfo.sqf, addons/repair/functions/fnc_addRepairActions.sqf, addons/repair/functions/fnc_canMiscRepair.sqf, addons/repair/functions/fnc_doRepair.sqf, addons/repair/script_component.hpp
Since 1.82 `getAllHitPointsDamage` returns lower case
Fix track repair and hit point groups being case sensitive
Part of #6248
=> Repair - Handle changes to getAllHitPointsDamage

addons/arsenal/XEH_preInit.sqf, addons/arsenal/defines.hpp, addons/arsenal/functions/fnc_addStat.sqf, addons/arsenal/functions/fnc_fillLeftPanel.sqf, addons/arsenal/functions/fnc_fillRightPanel.sqf, addons/arsenal/functions/fnc_handleMouse.sqf, addons/arsenal/functions/fnc_handleStats.sqf, addons/arsenal/functions/fnc_itemInfo.sqf, addons/arsenal/functions/fnc_onArsenalOpen.sqf, addons/arsenal/functions/fnc_onSelChangedLeft.sqf, addons/arsenal/functions/fnc_onSelChangedRight.sqf, addons/arsenal/functions/fnc_onSelChangedRightListnBox.sqf, addons/arsenal/functions/fnc_removeStat.sqf, addons/arsenal/functions/fnc_showItem.sqf, addons/arsenal/functions/fnc_sortPanel.sqf, addons/arsenal/functions/fnc_updateCamPos.sqf, addons/arsenal/functions/fnc_updateRightPanel.sqf, addons/arsenal/script_component.hpp, addons/arsenal/ui/RscAttributes.hpp, addons/gunbag/XEH_preInit.sqf
- Fix case issue in verifyLoadout
- Remove uneeded lines related to the perf profiler (doesn't need them anymore)
- Move that one line this PR was about where it should be;
- Fix the ace arsenal camera weird behavior underwater or around rocks, the camera will now clip through rocks or other objects to avoid those issues.
- Gunbags will keep their weapons if you switch to another backpack then back to a gunbag in ace arsenal.
=> More various ace arsenal fixes

tools/make.py
make tried to rename (cut/paste) and would fail because a pbo from an older build already existed in that spot
```
Copying dll => P:\z\ace\ace_parse_imagepath_x64.dll
Cleaning P:\z\ace\addons\compat_adr_97
Cleanuping up old file P:\z\ace\release\@ace\optionals\@ace_compat_adr_97\addons\ace_compat_adr_97.pbo
ERROR: ace_compat_adr_97.pbo already exists
Cleaning P:\z\ace\addons\compat_r3f
Cleanuping up old file P:\z\ace\release\@ace\optionals\@ace_compat_r3f\addons\ace_compat_r3f.pbo
ERROR: ace_compat_r3f.pbo already exists
```
=> make.py - cleanup old optional pbos before rename

addons/fcs/CfgVehicles.hpp, optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
1.82 changelog:
>Tweaked: Blackfish and gunship helicopters gunners now use FCS instead of CCIP (press 'T' before firing)
No difference between their system and ours now.
=> FCS - Switch to using vanilla FCS for attack helicopters

addons/cookoff/ACE_Settings.hpp
Ref
#5102
#6261
#6255
With the recent damage system changes in 1.82 ace_cookoff may have issues.
This PR will simply change the default setting to disabled.
=> Cookoff- Damage handling disabled by default

addons/nlaw/CfgAmmo.hpp
```
No shape for ammo type ACE_NLAW_Explosion
No shape for ammo type ACE_NLAW_ShapedCharge
```
=> NLAW - Fix "no shape for" rpt warning

addons/missionmodules/stringtable.xml
- Remove [ACE] from displayName of Ambiance Sounds module
- Not needed as no other modules have this and the category has ACE in its name
=> Mission Modules - Remove [ACE] from Ambiance Sounds module displayName

addons/medical/XEH_preInit.sqf, addons/medical/functions/fnc_conditionCardiacArrestTimer.sqf, addons/medical/functions/fnc_enteredStateCardiacArrest.sqf, addons/medical/stringtable.xml
This was changed from minutes to seconds at some point, but not everywhere. Just making it consistent.
Relates to #5510 as the unit would enter cardiac arrest at some point and die quickly (though doesn't fix the issue - we need another fatal condition for many wounds at once or similar).
=> Fix cardiac arrest time scale consistency by using seconds everywhere

addons/repair/ACE_Repair.hpp, addons/repair/CfgVehicles.hpp, addons/repair/functions/fnc_addRepairActions.sqf, addons/repair/functions/fnc_isEngineer.sqf, addons/repair/functions/fnc_modifyInteraction.sqf, addons/repair/functions/fnc_modifySelectionInteraction.sqf, addons/repair/stringtable.xml, optionals/compat_rhs_afrf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
- Disable "miscRepair" action for all era and slat armor hitpoints.
- Can still be repaired via "Full Repair"
ERA is consumable and it doesn't really make sense to be repairable with just a toolkit.
There are multiple hit-points and leaving them in makes interaction cluttered.
ToDo?
FullRepair has steep requirements by default (adv engineer, repair facility)
We could add a "Repair ERA" action, availiable when near a repair vehicle or facility.
=> Repair - Disable repair on ERA/Slat armor hitpoints

addons/hearing/CfgWeapons.hpp
- `H_Tank_black_F` doesn't have hearing support yet, so here it is.
=> Add ace hearing support to the tank DLC helmet

addons/goggles/ACE_Settings.hpp
From what I can see goggles are all handled locally and do not need to be globally enabled/disabled. If a group wants to force the setting, CBA provides optional force functionality.
=> Allow goggle effects to be set locally per client

addons/repair/functions/fnc_isRepairVehicle.sqf
The wiki states that `ACE_isRepairVehicle` is a boolean but this function only checked for integer values, resulting in a script error for whoever used the wiki value. 
-  Make isRepairVehicle handle both types
=> (repair) - isRepairVehicle handling values according to wiki

addons/zeus/functions/fnc_moduleSuicideBomber.sqf
- increase check delay from 0/each frame to 1 seconds (reset to 0 in debug mode for line drawing)
- use more appropriate `skillFinal`
- changed spotting distance formula to increase distance linearly starting from 0 skill instead of .5 skill
- remove some very redundant parenthesis
- re-formated if control structure for readability
=> optimize suicide bomber zeus module

addons/zeus/functions/fnc_moduleSuicideBomber.sqf
- Use `_unit` (Object) as position parameter for `createVehicle` instead of `getPos _unit` (Position array). 
- The bomb spawn at the correct altitude so the player and the suicider are killed as intended.
- basic testing code in debug console : 
```
// On Altis,
player allowdamage false;
player setPosASL [16894.5,13467.2,2.19884];
private _group = createGroup civilian;
private _unit = _group createUnit ["C_Man_casual_5_F", [16900.5,13458.1,2.19796], [], 0, "CAN_COLLIDE"];
createVehicle ["R_TBG32V_F", getPos _unit, [], 0, "CAN_COLLIDE"]; //Nobody is killed
//createVehicle ["R_TBG32V_F", _unit, [], 0, "CAN_COLLIDE"]; //Everybody is killed
```
=> FIX: Explosive does not spawn at the correct altitude in fnc_moduleSuicideBomber

addons/zeus/functions/fnc_moduleSuicideBomber.sqf
Not sure if it is intended but this will prevent the detonation if the suicide bomber is unconscious. From my point of view, the suicider is not supposed to activate his bomb when he is unconscious. Let me know ...
- check  if `[_unit] call EFUNC(common,isAwake)` before trigger the bomb.
=> Zeus - Don't trigger suicide bomber if unconsicous

addons/arsenal/functions/fnc_statTextStatement_mass.sqf
Fix #6320
Prioritize using `itemInfo` before `WeaponSlotsInfo`
Only effects NVGs, and this behaviour matches engine (`loadAbs player`)
=> Arsenal - Fix weight stat for NVGs

addons/arsenal/functions/fnc_openBox.sqf
- Change `openBox` to check for `CAManBase` rather than `Man`
- Prevents opening arsenal on animals, like goats...
=> Arsenal - Correct openBox center check

addons/frag/functions/fnc_doSpall.sqf, addons/frag/functions/fnc_fired.sqf, addons/frag/functions/fnc_spallHP.sqf, addons/frag/functions/fnc_spallTrack.sqf
- Fix #5614
- Don't run tracking simulation on small caliber ammo that won't ever spall
=> Spall - Don't throw script errors in doSpall if input is bad

addons/interaction/CfgVehicles.hpp
- title.
RHIB has in-game mass of 5000. It's more than CUP RHIB (2700) but less than Armed Speedboat (9000). That's why I'm not sure what is better: increase `FUNC(canPush)` mass limit (2600) or add config value.
=> Interaction - Allow RHIB push

addons/advanced_fatigue/functions/fnc_handleEffects.sqf, addons/common/XEH_PREP.hpp, addons/common/functions/fnc_setAimCoef.sqf, addons/common/functions/fnc_setHearingCapability.sqf
- Add function **ace_common_fnc_setAimCoef**. This is a partial copy of the [setHearingCapability](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_setHearingCapability.sqf) function and allows for scripts to raise the aiming coefficient (weapon sway) above the current value. The highest value set will be applied. It is designed so that scripts can simulate stress, fear, suppression and other mental or physical conditions that will likely reduce a soldier's ability to aim correctly.
- Make ace_advanced_fatigue_fnc_handleEffects use the above-mentioned function instead of `setCustomAimCoef`.
I would however prefer a framework for similar functionality (having a max/min setting that can be set by different functions/scripts).
=> Add ability to set aiming coefficient for mission scripting.

addons/common/functions/fnc_cachedCall.sqf
Sorry. But I just couldn't stop thinking about it.
Also as I see _event is a string.. Shouldn't that default to empty string and test for empty string? as users might pass in empty string to show "no event"
=> Fix minor typo in fnc_cachedCall

addons/captives/functions/fnc_handleLocal.sqf, addons/captives/functions/fnc_setHandcuffed.sqf, addons/captives/functions/fnc_setSurrendered.sqf, addons/pylons/XEH_postInit.sqf, addons/refuel/XEH_postInit.sqf
- Pass functions by reference to `addEventHandler` and `addMissionEventHandler`
Should provide a slight performance improvement
=> Pass functions by reference to BI event handlers

addons/frag/CfgAmmo.hpp, addons/hellfire/CfgAmmo.hpp
- Change hellfire to use Vikhr (`M_Scalpel_AT`) as base missile along with its submunition configuration
- Remove damage changes to Kilo as damage is dealt by submunition
- Remove submunition from November
- Increase hellfire seeker max range to 8km
- Update frag base class
=> Hellfire - Update to use 1.82 submunition

addons/arsenal/ACE_Arsenal_Stats.hpp, addons/arsenal/XEH_PREP.hpp, addons/arsenal/functions/fnc_fillLeftPanel.sqf, addons/arsenal/functions/fnc_fillLoadoutsList.sqf, addons/arsenal/functions/fnc_fillRightPanel.sqf, addons/arsenal/functions/fnc_loadoutsChangeTab.sqf, addons/arsenal/functions/fnc_onLoadoutsClose.sqf, addons/arsenal/functions/fnc_onLoadoutsOpen.sqf, addons/arsenal/functions/fnc_onSelChangedLeft.sqf, addons/arsenal/functions/fnc_removeStat.sqf, addons/arsenal/functions/fnc_statBarStatement_accuracy.sqf, addons/arsenal/functions/fnc_statTextStatement_accuracy.sqf
- Add 4 new EHs for the loadouts display:
| Name  | Arguments |
| ------------- | ------------- |
| ace_arsenal_loadoutsDisplayOpened | loadouts screen display (DISPLAY) |
| ace_arsenal_loadoutsDisplayClosed | none |
| ace_arsenal_loadoutsTabChanged | loadouts screen display (DISPLAY), tab control (CONTROL) |
| ace_arsenal_loadoutsListFilled | loadouts screen display (DISPLAY), tab control (CONTROL) |
- Fix the accuracy stat not being accurate, the stat used the default value, now the bar and numbers shown are what they should be.
- Improve onSelChangedLeft to limit the accessory stripping issue #6307 , using setUnitLoadout with a modified array would potentially break multiple other features or cause other issues, this is the best fix until we get …
=> Arsenal - Various additions and fixes

addons/explosives/config.cpp
- Fixes #6342
The only other way to hide the action would be adding another magazine to the GroundWeaponHolder. That's not really an option though since we'd have to continously check all of them on the map.
=> Hide "Activate Mine" action

addons/arsenal/functions/fnc_fillRightPanel.sqf, addons/arsenal/functions/fnc_scanConfig.sqf
Support for magazineGroups that were renamed to magazineWell's in 1.82
Example config https://gist.github.com/dedmen/beeadaa4389519025b75799fff2e3c59
Ref: https://github.com/CBATeam/CBA_A3/issues/108
=> Arsenal - Add magazineWell support

addons/hearing/CfgWeapons.hpp
- Active hearing protection for all CSAT helmets. All of them cover the ears, most feature some kind of bulge, indicating hearing protection underneath.
- Active hearing protection for CTRG Stealth Helmet. It features visible hearing protection.
- Muffling for Racing Helmets (same as crew helmets etc.)
=> Hearing - Added config for CSAT, Stealth and Racing Helmets

addons/maverick/CfgAmmo.hpp, addons/missileguidance/functions/fnc_attackProfile_LIN.sqf
- Prevent Mavericks and KH25ML from diving into the ground right before reaching their target.
- Decrease Mavericks and KH25ML maximum steering angle to more reasonable amount.
fixes #6311
=> Fix Mavericks and KH25ML diving into the ground.

addons/realisticnames/CfgVehicles.hpp, addons/realisticnames/CfgWeapons.hpp, addons/realisticnames/stringtable.xml, addons/vehicles/CfgVehicles.hpp, addons/vehicles/CfgWeapons.hpp
Add realistic names for new assets from Tanks DLC.
Vehicles:
- Wiesel 2 Ozelot (AA)
- Wiesel 2 ATGM
- Wiesel 2 AFF
- Wiesel 2 MK20
Vehicle Weapons:
Weapons:
I was in the flow, so I added Optics Attachments as well.
More to be added. Please add assets i may have missed in this PR.
=> Realistic names for new assets from Tanks DLC

addons/cargo/functions/fnc_unloadItem.sqf, addons/common/functions/fnc_findUnloadPosition.sqf
close #6357 
Actually, if `_typeofcargo` does not have `ace_cargo_size` define in config, the `_radiusOfItem` of the object is `1`. This inconsistency can be avoid by using the `ace_cargo_fnc_getSizeItem` which take an object as parameter and get the size of the object defined manually by user ( `ace_cargo_fnc_setsize`). 
By having a `_radiusOfItem` more accurate, the `ace_common_fnc_findUnloadPosition` will find better position for unloading and avoid vehicle explosion when big objects, without `ace_cargo_size` defined in config, are unloaded.
I don't know if it is the best way to handle this case but at least it is a work around. Cheers.
- `ace_common_fnc_findUnloadPosition` can take object as parameter
- Prefer the config way instead to determine …
=> Cargo - Support of object without `ace_cargo_size` defined in config or `-1` config value

addons/arsenal/ACE_Arsenal_Stats.hpp, addons/arsenal/XEH_PREP.hpp, addons/arsenal/functions/fnc_statBarStatement_rateOfFIre.sqf, addons/arsenal/functions/fnc_statTextStatement_rateOfFire.sqf
- The stat was wrong when the default ROF was different than the firemode one (example: hlc pistols)
=> Arsenal - Fix Rate Of Fire stat

addons/arsenal/defines.hpp, addons/arsenal/ui/RscAttributes.hpp
- Fix the right tab listNbox from eating the last item of the list. 
~Go figure why that happens tho :/ , at least it's fixed.~
Welp, if you resize listBox and listNbox controls while they're filled, the rows will get eaten by the arma dragon.
Bugged behavior can be seen below, (not my gif, thanks mharis001 for bringing up this issue):
https://gfycat.com/MassiveThreadbareDavidstiger
=> Fix right tab listNbox not showing last item on first load in ACE Arsenal

addons/cargo/functions/fnc_canLoadItemIn.sqf, addons/cargo/functions/fnc_loadItem.sqf
- Add an optional parameter to `ace_cargo_loadItem` & `ace_cargo_canLoadItemIn`
- Parameter allows interaction distance check in `ace_cargo_canLoadItemIn` to be ignored
- I needed this for a persistence implementation where supply boxes with inventories as ace cargo are made persistent, and couldn't previously be loaded in due to distance
- Maybe someone else will find this useful
=> Cargo load ignore interaction distance parameter

addons/fastroping/CfgVehicles.hpp
Disables Racks, Intercom, Infentry Phone on fast roping helper objects
(Inherited because they are type `Helicopter`)
Configs shouldn't cause issue if not using acre.
=> Fastroping - Disable ACRE features for helper objects

addons/realisticnames/stringtable.xml
=> Fix typo in realistic name for MRCO

addons/explosives/functions/fnc_onIncapacitated.sqf
Explosives closes one display at killed.
This breaks e.g. the Life Respawn menu.
This PR makes the component no longer kill a display indiscriminately, but only the Cellphone one.
Debug script:
```sqf
player addEventHandler ["Killed", {
createDialog "RscDisplayEmpty";
}];
```
Before this PR: no display created, after this PR: display created successfully.
Note: don't run the code twice. Only one display is closed, so executing it twice seemingly fixes the issue, but doesn't really.
=> don't make Explosives close one display at death

addons/medical/ACE_Medical_Actions.hpp, addons/medical/ACE_Medical_SelfActions.hpp, addons/medical/functions/fnc_unconsciousPFH.sqf
- Fix adenosine displayname being wrong in some medical interactions 
- Fix unconscious units waking up while being carried staying muted 
For the unconscious units, turns out the global EH isn't called if the unit is being carried, and the muting / unmutting relies on it.
=> Fix typo in med and issue related to unconsciousness

addons/arsenal/stringtable.xml, addons/common/stringtable.xml, addons/explosives/stringtable.xml, addons/flashlights/stringtable.xml, addons/gforces/stringtable.xml, addons/hearing/stringtable.xml, addons/interact_menu/stringtable.xml, addons/interaction/stringtable.xml, addons/markers/stringtable.xml, addons/medical/stringtable.xml, addons/medical_ai/stringtable.xml, addons/medical_menu/stringtable.xml, addons/nametags/stringtable.xml, addons/nightvision/stringtable.xml, addons/pylons/stringtable.xml, addons/repair/stringtable.xml, addons/vehicles/stringtable.xml, addons/zeus/stringtable.xml
- Add and fix Italian translation for the modules: arsenal, nightvision, common, explosives, maverick, gforces, pylons, hearing, marksers, repair, flashlights, nametags, interaction, vehicles, medical_menu, medical_ai, interact_menu, medical
Just for info, the PBOs for testing have been built by using the `armake` branch with `tools\make.ps1` .
=> Italian Translation Update

addons/explosives/functions/fnc_interactEH.sqf
- Optimize explosives `interactEH` function (various minor improvements but mainly `createVehicleLocal [0, 0, 0]`)
Performance results for `ace_explosives_interactEH_counter`:
Test | Old | New
--- | --- | ---
count allMines = 30 (somewhat close) | 0.09198s / 43 = 2.13907ms | 0.0169678s / 35 = 0.484794ms
count allMines = 42 (nearby) | 0.0439453s / 24 = 1.83105ms | 0.0249634s / 28 = 0.891549ms
count allMines = 47 (far away) | 0.00402832s / 31 = 0.129946ms | 0.00604248s / 59 = 0.102415ms
count allMines = 159 (nearby) | 0.685913s / 106 = 6.47088ms | 0.248962s / 123 = 2.02408ms
=> Explosives - Optimize interactEH function

addons/common/CfgEventHandlers.hpp, addons/common/RscInfoType.hpp
- add 'RscUnitInfo' to Extended_DisplayLoad_EventHandlers
- because 90% of the RscInGameUIs are use BIS_fnc_initDisplay with RscUnitInfo
- instead of adding onLoad to all mod RscInGameUIs (example: RHS) it will go over the cba xeh
This works now perfect for my desire, the rhs jets now also get a limited UI by the Ace_UI addon. But i dont know what side effects this triggers.
=> ace_infoDisplayChanged will now trigger also for mods

addons/common/RscInfoType.hpp
Fix for #6422
```
Application terminated intentionally
ErrorMessage: File z\ace\addons\common\RscInfoType.hpp, line 5: /RscInGameUI.RscUnitInfoSoldier: Undefined base class 'RscUnitInfo'
```
=> Fix unit info base class

addons/explosives/CfgAmmo.hpp
Fix #6427
(Same fix as #4195, but those changes got lost at some point)
=> Explosives - Increase defuse range for underwater mines

addons/medical_engine/functions/fnc_handleDamage.sqf
Units accumulate damage in the local variables
"ACE_Medical_Engine_$HitXXXX", but these are never reset. The way these
vars are used is as a single-damage-event tracker, and the end result of
not resetting their value when they're done being used is that a
specific $HitXXXX can accumulate enough damage to cause the "select
wound with highest damage" code to always select _it_ for the next wound
event, even if it wasn't the primary target of the last wound event.
I.E. I get shot in the right leg badly. If I then get winged in the left
arm, that wound will end up on my right leg, because when the code runs,
it finds QGVAR($HitRightLeg) > QGVAR($HitLeftArm), and so it applies the
wound to the right leg.
- Fix the above-described issue
=> Fixes damage redirection issues

addons/medical/script_macros_medical.hpp, addons/medical_damage/functions/fnc_woundsHandler.sqf, addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf, addons/medical_vitals/functions/fnc_handleUnitVitals.sqf, addons/medical_vitals/script_component.hpp
Move all events in handleUnitVitals to single switch statement to make it easier to see when each event is fired.
Also adds a case for the lower blood volume, that will trigger if medication is at play. This means it's now more urgently to bandage up.
=> Move all events in handleUnitVitals to single switch statement

addons/medical_statemachine/functions/fnc_conditionCardiacArrestTimer.sqf, addons/medical_statemachine/functions/fnc_enteredStateCardiacArrest.sqf
- Fix units not dying when their cardiac arrest timer runs out (some misaligned GVARs after restructure).
=> Fix cardiac arrest timeout

addons/finger/functions/fnc_keyPress.sqf, addons/rearm/functions/fnc_rearmSuccessLocal.sqf
- Rearm pylon magazines properly if the `Rearm Amount` setting is set to `Entire Magazine` (Previously if the magazine was a pylon magazine then it would only rearm based on caliber. Did not check `ace_rearm_level`)
- Adds the `displayTextStructured` text box to inform the player of the number of rounds rearmed if the magazine is a pylon magazine.
- Sets the `forced` flag on the `setPylonLoadOut` command to `true` so the rearm system is capable of rearming scripted pylon weapons.
- Fixes [#5395](https://github.com/acemod/ACE3/issues/5395)
=> Fix Rearming Pylon Magazines

addons/gforces/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
- g force adjustments
- RHS g force adjustments
- MH6M can now fastrope
=> RHS Compatibility - g force adjustments and MH6M can now fastrope

addons/medical_engine/CfgMoves.hpp
Not sure of the original reason we interpolate to this ACE unconscious animation, but removing it seemingly has no effect and fixes all the other animations that were broken by it. Thanks to Bismarck for the fix 👍
Fixes #6227
=> Fix ladder dismount animation bug

addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
- Enter in cardiac arrest state if 50/40 blood pressure and heart rate is below 40.
- Chance to enter  cardiac arrest if heart rate is below 30 but higher than 20.
- Enter cardiac arrest if Blood pressure L is above 190.
=> Changes unit vitals rw

addons/medical_feedback/XEH_postInit.sqf, addons/medical_feedback/script_component.hpp, addons/medical_statemachine/Statemachine.hpp, addons/medical_statemachine/XEH_PREP.hpp, addons/medical_statemachine/functions/fnc_enteredStateDeath.sqf
- Lower the player's hearing when they go unconscious (both game sounds and addon local/radio voices).
- Perhaps this should only affect voices?
- Re-evaluate player's ability to talk and hear upon changing unit
- Fix potential for players to be able to talk if they transition into an already unconscious AI unit that was previously local to dedicated/headless.
- Fix potential for players to respawn and not be able to hear or talk.
- This also removes the large number of variables being set on AI and never used.
=> Improve unconscious volume handling

addons/arsenal/functions/fnc_onArsenalClose.sqf, addons/arsenal/functions/fnc_onArsenalOpen.sqf, addons/captives/functions/fnc_handlePlayerChanged.sqf, addons/captives/functions/fnc_handleZeusDisplayChanged.sqf, addons/captives/functions/fnc_setHandcuffed.sqf, addons/captives/functions/fnc_setSurrendered.sqf, addons/common/functions/fnc_showHud.sqf, addons/ui/functions/fnc_setElements.sqf
`showhud` command has been updated to 10 elements
9th is the Jets Panels/GPS
10 is unknown. possibly something to do with `showKillConfirmations`?
Replaces PR https://github.com/acemod/ACE3/pull/4491
Do we want a UI setting for pannels?
I don't think it's needed, there is a far better `enableInfoPanelComponent ` command to deal with that stuff.
=> Common - Update showHud function for new elements

addons/zeus/functions/fnc_moduleLoadIntoCargo.sqf
- Uses ignore parameter for `loadItem` to ignore interaction distance check when loading cargo through zeus
=> Zeus - Ignore interaction distance check with cargo load module

addons/medical_engine/script_macros_medical.hpp, addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/XEH_PREP.hpp, addons/medical_treatment/functions/fnc_findMostEffectiveWound.sqf, addons/medical_treatment/functions/fnc_getBandageTime.sqf, addons/medical_treatment/functions/fnc_treatment.sqf, addons/medical_treatment/functions/fnc_treatmentBandage.sqf, addons/medical_treatment/functions/fnc_treatmentBandageLocal.sqf
- Change the time it takes to bandage based on:
- The size of wound to be targeted (and how much has already been treated)
- ~~If the head or torso is being bandaged~~
- Whether the bandage user is a trained medic
- Whether the patient ~~is unconscious or~~ self treating
Note:
- There are a few goals to this PR:
- To reward use of medically trained units and teamwork
- To reduce annoyance of how long it takes to treat minor wounds
- To improve realism
- The times I've set are arbitrary and just based on what I figured makes sense, probably needs to be tested to check if it feels right.
- This isn't an outright penalty because it can make treatment faster if a wound is already mostly closed up.
- We might also want to factor in wound type (an …
=> Vary time taken to bandage based on circumstances

addons/medical_gui/functions/fnc_displayPatientInformation.sqf, addons/medical_gui/functions/fnc_updateUIInfo.sqf, addons/medical_gui/stringtable.xml
- Always use the more descriptive hemorrhage strings in GUI feedback (otherwise we're just arbitrarily limiting information the player can see).
- Update the hemorrhage descriptions to more closely reflect the blood volume simulation.
=> Fix and use hemorrhage stringtable descriptions

addons/medical_gui/functions/fnc_displayPatientInformation.sqf, addons/medical_gui/functions/fnc_updateUIInfo.sqf, addons/medical_statemachine/Statemachine.hpp, addons/medical_statemachine/functions/fnc_handleStateDefault.sqf, addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
Make sure vitals handling works properly again.
- fix some syntax mistakes in vitals handling.
- fix incorrect event name in statemachine.
- fix stringtable references.
=> fix(medical): make sure vitals handling works properly again

addons/medical/CfgVehicles.hpp, addons/medical_gui/CfgVehicles.hpp
- Remove the Icon property from the old setting module.
- The icon was moved from `medical` component to `medical_gui` causing errors during build.
=> [medical-rewrite] Removed icon from legacy modules

addons/attach/functions/fnc_attach.sqf, addons/explosives/functions/fnc_setupExplosive.sqf, addons/viewdistance/functions/fnc_setFovBasedOvdPFH.sqf
- getFov has a params check now, this function was passing args to it and causing an error.
Fixes #6475
=> Fix error in setupExplosive with CBA 3.8.0

addons/dragging/CfgVehicles.hpp, addons/reload/XEH_postInit.sqf
Disable dragging for 1.84 things (Fix #6491)
Also disable check ammo keybind when controlling uav
Ctrl+R turns radar on/off on some of these new "UAVs"
=> Dragging - Add compatibilty for 1.84 static weapons and radars

addons/repair/functions/fnc_isInRepairFacility.sqf
- (1) fix config-based facility acts as repair vehicles;
- fix repair at dead facility (if it's possible);
- optimize `fnc_isInRepairFacility` a little.
(1) Config-based facilities have the same config value name as repair vehicles (`GVAR(canRepair)`). When there is a dead config-based repair vehicle near it becomes repair facility and can affect repair routines. This PR excludes `AllVehicles` child classes from facilities. Maybe simulation check would be more efficient but I think it's OK.
=> Repair - Fix facility is like vehicle

addons/medical_treatment/ACE_Settings.hpp
- Nightly build failed because the macro was broken (either `EGVAR` with two arguments or `GVAR` with one)
- For backwards compatibility it should be `EGVAR`.
However i would plead to not maintain backwards comp with the rewrite and so change it to `GVAR`, but thats up to you.
=> [medical-rewrite] Fix wrong macro

docs/wiki/framework/arsenal-framework.md
- Add the 4 new EHs for ace arsenal to the wiki (Added in 3.12.3)
- Add stat tab index to the wiki.
=> Wiki - Add new Arsenal EHs and stat indexes to arsenal framework doc

addons/medical_treatment/functions/fnc_treatmentCPR_progress.sqf
- Add a `alive` check to the cpr treatment condition.
- `fnc_treatmentCPR_progress.sqf` checks if the target is alive. If its dead cpr is stopped.
- This leads to the situation where you have cpr as an option but it stops right after the start.
Question here is what is intended behaviour: Should cpr be always available (and the alive checks therefor removed) or should it be only available when the target is alive (current state).
The first option has the downside that it allow players to fast check if somebody is alive (cpr option there => alive, cpr missing => dead).
=> [medical-rewrite] Fix cpr condition

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/ACE_Settings.hpp, addons/medical_treatment/functions/fnc_treatment.sqf, addons/medical_treatment/stringtable.xml
This was causing bodies to glitch out on dedicated servers according to feedback.
=> Prevent treatment animation on dead bodies

addons/medical_gui/functions/fnc_handleUI_DisplayOptions.sqf, addons/medical_statemachine/functions/fnc_conditionExecutionDeath.sqf, addons/medical_statemachine/functions/fnc_enteredStateDeath.sqf, addons/medical_status/CfgEventHandlers.hpp, addons/medical_status/functions/fnc_initUnit.sqf, addons/medical_vitals/functions/fnc_updateHeartRate.sqf
- Fix medical menu reopen setting
- Fix second delay on execution condition which had a broken macro causing players to fall through cardiac arrest to death immediately 
- Fix people reporting 40 HR (set from leaving cardiac arrest state) when dead
- Fix players having old stats on respawn (including references to arrays causing wounds to the old corpse to apply to the new player too)
- Fix locality issue on unit init causing JiP to reset all variables (wounds etc) on all units
- Fix updateHeartRate being allowed to go passed the target heart rate. This is an especially large issue as it made it completely impossible to perform CPR. During CPR the vitals would not be checked leading to the maximum deltaT of 10. On the first tick of handle vitals …
=> Medical rewrite bug fixes

addons/medical_engine/functions/fnc_handleDamage.sqf
- Tidy, optimise and comment handle damage code.
- Fix some environmental damage conditions:
- ~~There was no sanity check on fall damage to see if the unit was in a vehicle to avoid weird edge cases.~~ Outdated, we now first check for a `_shooter` to handle this.
- Vehicle crashes would never trigger because they don't fire the EH for all hitpoints like most damage sources do.
- ~~Being hit by a vehicle would work (unintentionally), but was not explicitly checked for - which is now done by checking if a shooter exists.~~ Outdated, we now only check if a shooter exists to know collision damage has occurred, it's irrelevant if a vehicle caused it.
I tested all of this in the editor and can confirm the added traces for each damage source now fire when …
=> Fix environmental damage sources

extras/CfgWeaponsReference.hpp
- Add a missing semicolon in the CfgWeaponsReference.hpp file, at line 1562.
=> Fix missing semicolon in CfgWeaponsReference

addons/arsenal/functions/fnc_fillLeftPanel.sqf, addons/arsenal/functions/fnc_onSelChangedLeft.sqf
- Add support for mission defined unitInsignias in ACE Arsenal, with a working author infobox.
=> Arsenal - Add support for mission defined unit insignias

addons/repair/functions/fnc_isInRepairFacility.sqf
Fix #6560
On carrier, `position player` z is 0
=> Repair - Fix isInRepairFacility for buildings at height

addons/arsenal/functions/fnc_sortPanel.sqf
- Fix sort by value not sorting items with a count under 10 properly.
@bux
=> Arsenal - Fix sort by value not sorting properly

optionals/compat_rhs_afrf3/CfgMagazines.hpp, optionals/compat_rhs_afrf3/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgMagazines.hpp
```
Updating base class rhs_30Rnd_545x39_7N6_AK->rhs_30Rnd_545x39_AK, by z\ace\addons\compat_rhs_afrf3\config.cpp/cfgMagazines/rhs_100Rnd_762x54mmR/ (original rhsafrf\addons\rhs_c_weapons\config.bin)
Updating base class rhs_weap_rpk74->rhs_weap_pkp, by z\ace\addons\compat_rhs_afrf3\config.cpp/CfgWeapons/rhs_weap_rpk74m/ (original rhsafrf\addons\rhs_c_weapons\config.bin)
Updating base class rhsusf_100Rnd_556x45_soft_pouch->rhs_mag_30Rnd_556x45_M200_Stanag, by z\ace\addons\compat_rhs_usf3\config.cpp/cfgMagazines/rhsusf_100Rnd_556x45_M200_soft_pouch/ (original rhsusf\addons\rhsusf_c_weapons\config.bin)
```
=> RHS Compats - Update bases classes for RHS 4.6

addons/zeus/XEH_postInit.sqf, addons/zeus/functions/fnc_ui_editableObjects.sqf, addons/zeus/functions/fnc_ui_garrison.sqf, addons/zeus/functions/fnc_ui_toggleFlashlight.sqf, addons/zeus/functions/fnc_ui_toggleNvg.sqf, addons/zeus/script_component.hpp, addons/zeus/stringtable.xml, addons/zeus/ui/RscAttributes.hpp
- Add "Additional Objects" setting to Update Editable Objects module
- Allows for quickly adding units to Zeus without trying to place the module in range or using a large radius
- Fix Teleport Players UI height and use A3 strings
- Improve Garrison module UI and capitalize module names
- Before: 
- After: 
- Improve/cleanup Toggle NVGs and Toggle Flashlights UI by adding combo items through config
=> Zeus - UI improvements and additional objects setting for Editable Objects module

addons/arsenal/functions/fnc_statTextStatement_accuracy.sqf
- Change the precision display in the ACE Arsenal to ignore AI-only firemodes
There is a number of weapons, such as the NIArms M14DMR, RHS M249s and NIArms SiG 553s, that have an AI-only firemode with a lower `dispersion` value than any mode available to players. The current implementation shows those values on the Arsenal interface, painting a rather misleading picture.
I have considered checking for existence of the `showToPlayer` property first, but it is already defined on the base classes for weapons (`Default`) and firemodes (`Mode_SemiAuto`).
=> Arsenal - Filter firemodes for precision display by showToPlayer

addons/arsenal/missions/Arsenal.VR/XEH_postInit.sqf
Prevents
```
[CBA] (diagnostic) WARNING: Unit has no or a wrong eventId (-1). x\cba\addons\diagnostic\fnc_removeUnitTrackProjectiles.sqf:32
```
=> Arsenal - Don't warn when calling removeUnitTrackProjectiles

AUTHORS.txt, addons/markers/XEH_preInit.sqf, addons/markers/functions/fnc_getEnabledChannels.sqf, addons/markers/functions/fnc_initInsertMarker.sqf, addons/markers/functions/fnc_placeMarker.sqf, addons/markers/script_component.hpp
- Add the ability to edit user placed markers by double clicking at a marker
- Remove the direct channel as a valid channel because selecting it ingame will not select the default (group) channel but instead the global
- Optimize the method to get the current map display
- To some extend also allow to copy markers by e.g. starting to edit a marker, canceling it and then creating a new marker with the same properties as the edited marker
=> Add the ability to edit user placed markers

addons/laserpointer/CfgWeapons.hpp
- Add an IR beam to a visible laser mode for vanilla laser pointers
Visible laser is low enough power that the beam leading to the dot  is not visible to the naked eye but should still be visible for light magnification devices like NVGs. 
This PR enables the vanilla IR pointer module in addition the previously displayed laser dot which uses the vanilla flashlight module and drawIcon3D.
=> Add IR beam to visible laser mode

addons/tagging/functions/fnc_addCustomTag.sqf, addons/tagging/functions/fnc_addTagActions.sqf, addons/tagging/functions/fnc_applyCustomTag.sqf, addons/tagging/functions/fnc_checkTaggable.sqf, addons/tagging/functions/fnc_compileConfigTags.sqf, addons/tagging/functions/fnc_quickTag.sqf
=> Tagging - Cache required items check and use uniqueItems

addons/explosives/CfgVehicles.hpp, addons/explosives/functions/fnc_addExplosiveActions.sqf, addons/explosives/functions/fnc_hasExplosives.sqf
- Optimize explosive place action (remove useless condition) and creating its children (optimized function and return is cached)
All of these were tested with `count magazines = 28` and `placeable explosives => 6, 2, 1, 1` (where each number represents the amount of a unique type of explosive).
- The old function took ~0.31 ms
- Useless condition on `ACE_Place` action took ~0.1 ms (time it takes `hasExplosives`)
- New function takes ~0.20 ms (without any caching)
- New function first time (with caching) takes ~0.23 ms (cachedCall adds ~0.03 ms)
- New function (when return is cached) takes ~0.009 ms
**Overall**: Instead of ~0.41 ms every second, the new method is ~0.23 ms after a change in the player's loadout and then ~0.009 ms (accessing the cached …
=> Explosives - Optimize creating explosive place actions

addons/fastroping/functions/fnc_cutRopes.sqf
- Fix #5686 
Broken since #5533, this specific handling was removed, somehow missing this case. This just restores it without the delay (as FRIES stowing is still manual).
=> Fix rope redeploying without FRIES

addons/realisticnames/CfgMagazines.hpp, addons/realisticnames/stringtable.xml
- Rename vanilla "RGN" grenade to "V40 Mini-Grenade"
- Add German translation for V40
- Remove trailing spaces in Czech strings for M67 grenade, M15 AT mine and M112 demo block; and in Italian string for HEMTT (Container).
**This pull request will not:**
- Add any other translation for V40
- Attempt to do any fixes on strings in non-Latin charsets.
And while we're at it: Shouldn't it be "Nebel" instead of "Rauch" for the German smokes?
=> Realistic Names - Rename RGN to V40 Mini-Grenade, fix some trailing spaces

addons/realisticnames/stringtable.xml
- 43c52585852205afdd4a61bf61d0c1ba9a2d2b63 created 2 duplicate strings in realisticNames, this PR remove the 2 extras.
=> Fix duplicate japanese strings

docs/.gitattributes
Docker Container won't start, because the linux image can't execute the entrypoint file with crlf line endings
=> Force lf line endings for docker entrypoint file

addons/explosives/CfgEventHandlers.hpp
- Fix #2770
Center of mass was previously not centered but too far back. It's now a little lower than the actual model's center. Mass was increased to 5 imaginary units, default is 0. Looks more realistic when falling now.
=> Fix slow motion falling of SLAM mines

README.md, docs/README_DE.md, docs/README_PL.md
We are no longer using Travis and the status badge should reflect this.
=> Use CircleCI instead of Travis for build status

addons/cargo/functions/fnc_canLoadItemIn.sqf, addons/cargo/functions/fnc_loadItem.sqf, addons/zeus/functions/fnc_moduleLoadIntoCargo.sqf
Close #6616
- `_ignoreInteraction` now also skips the check for vehicle height and speed
- Zeus load cargo module uses 2d distance searching, making it possible to load into a flying helicopter 
(still tricky as you need to click on the ground below the chopper)
=> Cargo - CanLoadItem ignores vehicle height on scripted load

addons/quickmount/ACE_Settings.hpp, addons/quickmount/XEH_preInit.sqf, addons/quickmount/functions/fnc_getInNearest.sqf, addons/quickmount/initSettings.sqf, addons/quickmount/stringtable.xml
- Close #6516 
Hotkey is unset by default, no reason to have a setting in that case as described in #6516.
@jameslkingsley review please.
=> Quickmount - Default enable quick mount (empty keybind) and Move to CBA Settings

addons/scopes/CfgWeapons.hpp
Update the `ACE_ScopeAdjust_Vertical` and the `ACE_ScopeAdjust_Horizontal` according with the real US Optics (AMS), KAHLES (KHS) and NF NXS 5.5-22x56 (LRPS) technical datas : 
- [US Optics MR-10 specifications](https://www.usoptics.com/discontinued-optics/#MR)
- [KAHLES Helia technical data](http://www.kahles.at/en/hunt/products/riflescopes/?tx_kahlesproducts_category%5Bproduct%5D=3&tx_kahlesproducts_category%5Baction%5D=show&tx_kahlesproducts_category%5Bcontroller%5D=Product&cHash=39ce16ce5f7c7a36f20179a249d6200d)
- The LRPS texture part with the NF magnification : https://imgur.com/3TBBplS
[Nightforce NXS 5.5-22x56 specifications](http://nightforceoptics.com/nxs/5-5-22x56)
=> Scopes - Update AMS, KHS and LRPS "ACE_ScopeAdjust"

addons/realisticnames/CfgWeapons.hpp, addons/realisticnames/stringtable.xml
Add the real name to these two scopes : 
- Magnification graduation AMS texture : https://imgur.com/a/9ppBAyR
[The only US Optics scope](https://www.usoptics.com/discontinued-optics/#MR) with this magnification.
- Magnification graduation KHS texture : https://imgur.com/a/0F0UkuK
This Kahles scope was certainly the discontinued Kahles Helia 5 scope 3D model
but the actual [Kahles Helia](http://www.kahles.at/jagd/produkte/zielfernrohre/?tx_kahlesproducts_category%5Bproduct%5D=3&tx_kahlesproducts_category%5Baction%5D=show&tx_kahlesproducts_category%5Bcontroller%5D=Product&cHash=39ce16ce5f7c7a36f20179a249d6200d) could be a decent choice.
As usual, the 3D models don't match exactly with the real scopes, only with the 2035 ones.
=> Realisticnames - Update AMS and KHS's name

addons/interaction/ACE_ZeusActions.hpp, addons/rearm/ACE_ZeusActions.hpp, addons/rearm/config.cpp, addons/rearm/functions/fnc_rearmEntireVehicle.sqf, addons/rearm/functions/fnc_rearmEntireVehicleSuccess.sqf, addons/rearm/functions/fnc_rearmEntireVehicleSuccessLocal.sqf
- title;
- optimize conditions for zeus submenus a little;
- add conditions for `Stance` and `Remote Control` menus;
- make `Remote Control` statement multi-line;
- simplify `ace_rearm_fnc_rearmEntireVehicleSuccess` params (remove nested array).
=> Zeus - Add Repair and Rearm interactions

addons/quickmount/functions/fnc_getInNearest.sqf
- title.
Some vehicles have turrets without weapons. They should be treated as cargo not gunners because they can influence (Quick)mount order.
Vanilla vehicles: `B_T_VTOL_01_infantry_F`, `B_T_VTOL_01_vehicle_F` (passengers in cabin).
There are some vehicles in RHS and quite many in CUP. Especially CUP SUVs (like `CUP_I_SUV_Armored_ION`) where you first get in external cargo seats on SUV sides.
=> Quick Mount - Fix turrets without weapon treated as gunner

addons/arsenal/Cfg3DEN.hpp, addons/arsenal/Display3DEN.hpp, addons/arsenal/XEH_PREP.hpp, addons/arsenal/config.cpp, addons/arsenal/functions/fnc_attributeAddItems.sqf, addons/arsenal/functions/fnc_attributeKeyDown.sqf, addons/arsenal/functions/fnc_attributeLoad.sqf, addons/arsenal/ui/RscCommon.hpp
- title, https://github.com/acemod/ACE3/issues/3594#issuecomment-423489691
- Move `Display3DEN` changes from RscCommon to separate file
=> Arsenal - Add key handling to 3DEN attribute

addons/markers/functions/fnc_initInsertMarker.sqf
- Disable marker editing for everything non-icon
[Comment from PabstMirror](https://github.com/acemod/ACE3/pull/6564#issuecomment-423861538)
=> Disable marker editing for everything non-icon

addons/ai/CfgEventHandlers.hpp, addons/ai/XEH_PREP.hpp, addons/ai/XEH_postInit.sqf, addons/ai/functions/fnc_drawCuratorGarrisonPathing.sqf, addons/ai/functions/fnc_garrison.sqf, addons/ai/functions/fnc_garrisonMove.sqf, addons/ai/functions/fnc_unGarrison.sqf
- Cleanup parts of the garrison code, mostly garrisonMove.
- Add garrison path drawing to curator for units that are moving on foot to garrison positions instead of being teleported.
- Removed debug draw mode as it's now permanently enabled while in curator.
Notes:
AI seems to be SLIGHTLY better at pathing, however some of them still get stuck in the open, in front of buildings due to obstacles, in buildings with poor geometry.
=> AI - Cleanup garrison, add garrison path to curator

addons/vehiclelock/CfgEventHandlers.hpp, addons/vehiclelock/CfgVehicles.hpp, addons/vehiclelock/XEH_postInit.sqf, addons/vehiclelock/functions/fnc_handleVehicleInitPost.sqf, addons/vehiclelock/functions/fnc_moduleSync.sqf, addons/vehiclelock/script_component.hpp
=> Vehicle Lock - Enable for planes

addons/repair/CfgEden.hpp
- make `ace_isEngineer` attribute use vanilla engineer value as default;
- make `ace_isRepairVehicle` and `ace_isRepairFacility` attributes use config values as default;
- make these attributes init code assign variables only if they differ from default values;
- simplify config with inheritance.
`ace_isEngineer` attribute init code is more complicated a little because it considers `Default` attribute value.
=> Repair - Make eden attributes use config values as default

addons/ai/XEH_postInit.sqf, addons/ai/functions/fnc_garrisonMove.sqf
- Revert setDestination being moved after doMove, it clearly degrades the ability of the AI to path to their position.
- Reduce the completion area to 0.5m² from 3m² in order to garrison AI too far away.
=> AI - Fix garrison pathing

addons/ai/functions/fnc_garrison.sqf, addons/ai/functions/fnc_garrisonMove.sqf, addons/ai/functions/fnc_unGarrison.sqf
- Fix an issue where units would keep trying to path until it fails even if they're ungarrisoned or garrisoned via teleport, this would also keep drawing the red lines to the old positions.
Not sure how I missed this during testing.
=> AI - Fix units not being removed from the garrison unitMove list consistently

addons/logistics_uavbattery/CfgVehicles.hpp
- Balance the darter battery life to be around 30 minutes.
- Balance the AL-6 Pelican battery life to be around 25 minutes.
Quadcopters and hexacopters can currently fly for hours, not only this is wildly unrealistic, it removes the need for UAV batteries altogether and makes them able to fly absolutely insane distances, this PR fixes this.
Fuel capacity was calculated by giving each drone 1 fuel capacity and making them hover for a minute then multiply the result by the desired battery life.
=> Make small UAVs battery life more realistic

addons/safemode/XEH_postInit.sqf
=> Safemode - Fix indicator when switching units

addons/rearm/functions/fnc_addRearmActions.sqf
- Fix the mk6 mortar being allowed to be rearmed when ammo handling is enabled.
close #6540
=> Rearm - Fix mk6 mortar being reloadable when ammoHandling is enabled

addons/medical/functions/fnc_handleDamage_caching.sqf
- title
- cuts back on excessive PFH use, making missions that run long reach the PFH limit
=> Medical - optimize handle damage caching

addons/interaction/CfgVehicles.hpp, addons/interaction/stringtable.xml
When windshield is partly damaged it becomes less clear so you may want to break it entirely.
Strings are copied from ACE2, I don't know if they are correct.
=> Interaction - Add Smash Windshield action

addons/zeus/functions/fnc_moduleGroupSide.sqf
- Close #6568 
- Preserve the group id when switching the group's side if it is not taken
- Preserve the assigned team color of units in the group being switched
**Notes:**
If the `Move units from group on unconscious` setting is enabled and a unit is unconscious when the module is used they will join the new group when they are woken up as expected. They will not keep their assigned team however and will join the white team when woken up. That would require changing code related to the `moveUnitsFromGroupOnUnconscious` setting and I don't think it is worth it for this edge case.
=> Zeus - Group Side Module: preserve group id and assigned team

addons/weather/functions/fnc_calculateRoughnessLength.sqf
- Fix #6602
The terrain roughness value rises a lot due to the amount of "buildings" nearby - runway lights and even the runway itself. This adds a simple but effective filter for all lights which does the trick without impacting performance much.
=> Weather - Fix wind on airports

AUTHORS.txt, addons/nametags/ACE_Settings.hpp, addons/nametags/XEH_preInit.sqf, addons/nametags/functions/fnc_drawNameTagIcon.sqf, addons/nametags/initSettings.sqf, addons/nametags/stringtable.xml
- Add settings for nametag team colors
- Make default colors lighter to make them easier to read
=> Nametags - Adjustable colors settings

tools/sqf_validator.py
- Support `#` command in SQF Validator (instead of ignore because we don't care about preprocessor directives)
- Will miss missing semi-colons on actual `#` command
=> Support # command in SQF Validator 

circle.yml
This issue has been resolved in Armake on the master branch. By switching to the `:master` tag we can use armake to build the ACE project again.
=> fix armake issues with latest release against ACE3

addons/markers/functions/fnc_movePFH.sqf, addons/markers/script_component.hpp
- without attached event handler, localEvent reports `nil`, which should be treated as `false` (don't overwrite movement)
- fix #6702
=> fix moved markers not synched

addons/tagging/functions/fnc_addCustomTag.sqf, addons/tagging/functions/fnc_addTagActions.sqf, addons/tagging/functions/fnc_applyCustomTag.sqf, addons/tagging/functions/fnc_compileConfigTags.sqf, addons/tagging/functions/fnc_createTag.sqf, addons/tagging/functions/fnc_quickTag.sqf, addons/tagging/functions/fnc_tag.sqf
Allows to use custom materials (rvmat) for tag's.
Adds additional "materials" array to the config.
When there are the same number of materials as textures, it will select a random texture and the corresponding material. If the numbers are different it will select random texture and random material.
Allows for things like this:
Glow-in-the-dark tags.
Next question would be if we also want to directly implement a glow-in-the-dark spraycan directly in ACE.
=> Custom Materials for tagging

addons/markers/XEH_postInit.sqf
- Non critical, should be WARNING instead of ERROR
- Suspect is vehicle channel markers that don't propagate to the server and are never JIP synched anyway
=> change an ERROR to WARNING in Markers component

addons/mk6mortar/RscInGameUI.hpp
shifts the mortar charge text to the right to match the rest of the UI which changed slightly
bis: `Added: Current fire mode indicator to the IGUI of mortars`
they now both show up, but I think that's fine for now
=> mk6mortar - Tweak charge UI for 1.86

docs/wiki/framework/arsenal-framework.md
Added 1.3: Making an arsenal only with items from precreated loadouts. A very powerful addition when you want default loadouts spawnable without giving a full arsenal or looking up all classnames yourself.
Discussed with commy2 and alganthe in the ArmA 3 Mission creation discord channel.
If the format is not perfect, please change it to your liking.
-Miles T. Focus
=> Extended arsenal framework documentation

addons/common/RscInfoType.hpp, addons/parachute/functions/fnc_handleInfoDisplayChanged.sqf, addons/parachute/functions/fnc_showAltimeter.sqf
- Fix the altimeter hide setting
- Clean up the altimeter PFH
the altimeter hide setting was broken by #6422 , this PR might've broken other things relying on those EH.
=> Parachute - Fix "hide altimeter" setting

addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- title
- also reduces ear ringing strength by damageCoefficent if above a certain threshold (not that it matters too much with our current ear ringing implementation)
=> Changed: Remove ear ringing from flashbang explosions when wearing protective gear (e.g. ComTacs)

addons/common/scripts/checkVersionNumber.sqf
- Change the error messages for PBO version checking
They were a bit confusing. `Missing server addon(s)` was most of the time interpreted as `You're missing server addon(s)`.
=> Change PBO check error messages

addons/arsenal/defines.hpp
Latest mikroTools (pbo Project 2.45 / Dll 7.15)
```
In File \z\ace\addons\arsenal\defines.hpp: circa Line 371 Expected (...) during define expansion
"arsenal.pbo not produced due to error(s)" 
```
Seems to not like empty macro lines, but I have no clue why only these 3 are causing problems.
=> Arsenal - Adjust macros for newest pboProject

addons/weaponselect/functions/fnc_putWeaponAway.sqf
Fix #6610
Could reproduce issue if rifle was in lowered state.
Tested in local MP, seems to work fine without the call.
=> WeaponSelect - Fix putWeaponAway animation

tools/sqf_validator.py
- Fix the sqf validator to correctly detect the use of # as select or preprocessor command.
=> Fix # command in sqf_validator.py

addons/dragging/functions/fnc_startCarryPFH.sqf
Player could get bugged with `player getVariable "ace_dragging_isCarrying"` set to true
(then cannot use ace interaction menu)
Reproduce:
Try to carry unconscious X
During pickup anim, X gets shot and dies
FUNC(dropObject) sets QGVAR(isDragging)
FUNC(dropObject_carry) sets QGVAR(isCarrying)
=> Dragging - Fix player getting locked with isCarrying

addons/medical/ACE_Medical_SelfActions.hpp, addons/medical/ACE_Settings.hpp, addons/medical/stringtable.xml
=> Medical - Add new setting to hide self-interaction actions

addons/medical/ACE_Medical_Treatments.hpp
This change will correct the typo when describing bandage types.
=> Fixed Typo from change to chance

addons/arsenal/functions/fnc_statBarStatement_accuracy.sqf, addons/arsenal/functions/fnc_statBarStatement_rateOfFIre.sqf, addons/arsenal/functions/fnc_statTextStatement_rateOfFire.sqf
Open arsenal on unconscious civ ("ace fake weapon")
it has odd stats, e.g. `log 0` = bad
```
Error in expression <each _fireModes;
_fireRate sort true;
linearConversion [_statMinMax select 0, >
Error position: <linearConversion [_statMinMax select 0, >
Error Type Not a Number, expected Number
File z\ace\addons\arsenal\functions\fnc_statBarStatement_rateOfFIre.sqf, line 31
Error in expression <am [0, 0];
format ["%1 rpm", round (60 / _fireRate)]
>
Error position: </ _fireRate)]
>
Error Zero divisor
File z\ace\addons\arsenal\functions\fnc_statTextStatement_rateOfFire.sqf, line 32
Error in expression <ch _fireModes;
_dispersion sort true;
linearConversion [_statMinMax select 0, >
Error position: <linearConversion [_statMinMax select 0, >
Error Type Not a Number, expected Number
File …
```
=> Arsenal - Fix script stat script errors for odd weapons

addons/arsenal/functions/fnc_onArsenalClose.sqf, addons/arsenal/functions/fnc_onSelChangedLeft.sqf, addons/zeus/functions/fnc_bi_moduleArsenal.sqf
- Fix weapons not being switched when the AI is remote.
- Fix backpacks being dropped to the ground when the AI is remote.
AddWeaponGlobal is broken, so instead I force the player into remote controlling the unit instead.
This should not break anything unless the mission uses remoteControl scripting, but even then going into zeus should return you to the original unit anyways.
close #6701
=> Arsenal - Fix arsenal not working reliably on remote AI units.

addons/javelin/CfgWeapons.hpp, addons/javelin/functions/fnc_showFireMode.sqf, addons/missileguidance/CfgAmmo.hpp, addons/missileguidance/functions/fnc_cycleAttackProfileKeyDown.sqf, addons/missileguidance/functions/fnc_onFired.sqf, addons/nlaw/CfgAmmo.hpp, addons/nlaw/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgWeapons.hpp
Fix #6595
Uses vanilla fire `mode[]` to select attack profile for some weapons.
(You can press F to cycle direct/topDown)
Fully compatible with the ace's cycle guidance key
=> MissileGuidance - Allow using vanilla fire mode key

addons/minedetector/CfgEventHandlers.hpp, addons/minedetector/XEH_preStart.sqf
Move 100ms of preInit code to preStart
=> Compile minedetector scripts at preStart

addons/common/functions/fnc_checkFiles.sqf
for full modset
`count cba_common_addons = 3275`
most of the cost is in `configClasses`
```
44.7826 ms
private _addons = "true" configClasses (configFile >> "CfgPatches");
_addons = _addons apply {toLower configName _x};
z = _addons select {_x find "ace_" == 0};
4.5045 ms
z = (cba_common_addons select {(_x select [0,4]) == "ace_"}) apply {toLower _x};
```
=> Common - checkfiles use cba's list of CfgPatches

addons/pylons/config.cpp, addons/pylons/functions/fnc_showDialog.sqf
pylons only needed ace_zeus for `EFUNC(zeus,showMessage)`
but the only way the function would be called with `_isCurator ` is from ace_zeus
so no need for requiredAddons entry
=> Pylons - Remove ace_zeus from requiredAddons

addons/huntir/CfgMagazineWells.hpp, optionals/compat_rhs_usf3/CfgMagazineWells.hpp, optionals/compat_rhs_usf3/config.cpp
Removes magWell for huntIR from rhs compat because it was added to the base huntIR configs.
The removes the need to run huntIR when using ace and rhs as it would throw
`Warning Message: No entry 'bin\config.bin/CfgMagazines.ACE_HuntIR_M203'`
=> HuntIR - Move magwell compat to huntIR config

addons/common/scripts/checkVersionNumber.sqf
Ref: https://github.com/CBATeam/CBA_A3/pull/1051#issuecomment-461881408
Related: #6800
=> Common - Use CBA addons instead of activatedAddons

addons/refuel/XEH_postInit.sqf, addons/refuel/XEH_preStart.sqf
=> Refuel - Cache refuel classes

addons/inventory/XEH_postInit.sqf, addons/inventory/XEH_preStart.sqf
A picture says more than a thousand words:
=> Inventory - Cache inventory postInit config lookups

addons/minedetector/XEH_postInit.sqf, addons/minedetector/XEH_preStart.sqf
=> Minedetector - Cache detectableClasses

addons/interact_menu/XEH_preInit.sqf, addons/interact_menu/functions/fnc_compileMenu.sqf
ref #6790
redo of #1294
currently takes ~14.5ms per unique classname for mans
=> Interact Menu - Cache config actions for CAManBase

addons/cargo/XEH_postInit.sqf, addons/cargo/functions/fnc_addCargoVehiclesActions.sqf, addons/cargo/functions/fnc_startLoadIn.sqf, addons/cargo/functions/fnc_startUnload.sqf
Fix:
Car could drive off during loading and progress bar would continue
Showed load actions for blownup/dead vehicles 
postInit - use `findIf`
addCargoVehiclesActions - check alive and not locked
startLoadIn/startUnload - add checks during progressBar
=> Cargo - Add condition checking during load/unload

addons/explosives/CfgAmmo.hpp
- Make SLAM mines set to bottom attack explode upon defusal attempt.
SLAM mines anti-tamper is also active on the bottom attack mode as seen here:
https://en.wikipedia.org/wiki/Selectable_Lightweight_Attack_Munition#Overview
=> Explosives - Change SLAM magnetic to detonate upon defusal

docs/src/package-lock.json, docs/src/package.json
- Update Jekyll packages
- Fix `lodash` security vulnerability (require 4.17.11 or higher)
=> Update Jekyll documentation packages and fix lodash vulnerability

addons/captives/XEH_postInit.sqf
- The problem is that the shortcut checks if the unit has cabletie but if you use the shortcut it will not remove the cabletie from the unit. Better use the thing i changed to do this.
=> Captives - Use the doApplyHandcuffs function for keybind

addons/ui/functions/fnc_setAdvancedElement.sqf
- fix #6547;
- improve `ace_ui_fnc_setAdvancedElement`:
- fix doc;
- add some debug;
- fix magic numbers;
- fix bad variable name (`show` -> `fade`).
Maybe now `VEHICLE_ONLY` and `GROUND_ONLY` macros should be renamed e.g. to `VEHICLE_NOT_CARGO` and `GROUND_AND_CARGO`.
=> UI - Fix selective UI in cargo

addons/safemode/functions/fnc_lockSafety.sqf, addons/safemode/functions/fnc_unlockSafety.sqf
=> Safe Mode - Fix disabled laser on safety switch

optionals/tracers/CfgAmmo.hpp, optionals/tracers/CfgMagazineWells.hpp, optionals/tracers/CfgMagazines.hpp, optionals/tracers/config.cpp, optionals/tracers/stringtable.xml
Adds the following magazines:
| calibre | rounds / shape | tracer (reload, mixed, every) | color (green, red, yellow) | /w image |
|:-------:|:--------:|:----:|:------:|:--------:|
| 5.56x45 | 150 Drum | r, e | g, y   | no       |
| 5.56x45 | 200 Belt | m, e | g      | no       |
| 5.8x42  | 30       | r, e | r, y   | no       |
| 5.8x42  | 100 Drum | r, e | r, y   | no       |
| 6.5 mx  | 30       | r, e | g, y   | yes      |
| 6.5 mx  | 100 Stick| r, e | g, y   | yes      |
| 6.5 kat.| 30       | r, e | r, y   | yes      |
| 6.5 case| 200 Belt | m, e | g, y   | yes      |
| 7.62x51 | 20       | e    | g, y   | no       |
| 7.62x54 | 150 Belt | m, e | r, y   | no       |
| 9.3x64  | 150 Belt | m    | r, y   | no       |
| .338 NM | 130 Belt | m …
=> Add magazines with different tracer colors for some vanilla weapons

addons/interaction/ACE_ZeusActions.hpp, addons/interaction/XEH_preInit.sqf, addons/rearm/ACE_ZeusActions.hpp, addons/rearm/XEH_preInit.sqf
Actually fix #6847
Thanks to @dystopian for testing RC
`getText (configfile >> "ACE_ZeusActions" >> "ZeusUnits" >> "ace_interaction_repair" >> "statement")`
>`"{if (_x isKindOf 'AllVehicles' && {!(_x isKindOf 'Man')}"`
`) then {...` gets cut off
I'm not sure why it breaks, macro usage looks ok to me.
=> Zeus Actions - Fix config code breaking during build

addons/common/scripts/checkVersionNumber.sqf
- fix #6871
Note that a big rewrite of this function, that would for example handle `1.99 < 1.100` etc. correctly is not desirable. The function has to be cross compatible between all versions due to its nature and therefore this transferred variable should stay a number and not become an array or string.
=> version check handle minor versions below 10

addons/explosives/functions/fnc_openTimerUI.sqf, docs/wiki/framework/explosives-framework.md
Can set custom min and max time for the timer trigger
e.g.
`ace_explosives_customTimerMin = 60` - can't set a time less than 60 seconds
=> Explosives - Allow setting custom timer limits

addons/medical_damage/ACE_Medical_Injuries.hpp, addons/medical_damage/functions/fnc_woundsHandler.sqf, addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf, addons/medical_engine/functions/fnc_handleDamage.sqf, addons/medical_status/functions/fnc_setUnconscious.sqf, addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
- Ensure units go unconscious CriticalVitals when bleeding 0.5 of max regardless of bleedingCoefficient (without this fix a bleeding bleedingCoefficient of 0.5 or less prevents units from going KO due to blood loss in any circumstances)
- Fix unit not having lastWakeUpCheck set due to incorrect variable macro
- Fix the detection for unknown damageTypes (should now fire with damageType "Unknown")
- Add collision damageType used by the damageHandler to the config (same settings as vehicleCrash)
- Changes collision wound location selection to be weighted to increase lethality on collisions with high momentum
=> Fixes to unconsciousness and damageTypes systems

addons/quickmount/CfgVehicles.hpp, addons/quickmount/functions/fnc_canShowFreeSeats.sqf
Caches call to `FUNC(addFreeSeatsActions)` on the actions args
Before it would double call the function each time (~0.8ms on a Chinook)
=> Quickmount - optimize generating subActions

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/XEH_PREP.hpp, addons/medical_treatment/functions/fnc_canBandage.sqf
- Prevent the bandage actions from showing when the inspected body part isn't bleeding.
This a quality of life improvement because there's never a situation where you'd want to bandage a body part that isn't bleeding.
=> Prevent bandaging when not bleeding

addons/interaction/functions/fnc_canPassMagazine.sqf, addons/interaction/functions/fnc_passMagazine.sqf
Use CBA_fnc_compatibleMagazines
Fix nil return in canPassMagazine if player has no mags (`forEach` never ran)
Ensure target canAdd (`private _magToPass = _filteredMags select 0;` could be a 200rnd belt that target can't add, but it's ammo count would be larger than smaller mags that the target could add)
=> Interaction - Pass Magazine fixes

addons/cookoff/ACE_Settings.hpp, addons/cookoff/CfgEden.hpp, addons/cookoff/XEH_preInit.sqf, addons/cookoff/initSettings.sqf, addons/cookoff/stringtable.xml
```
class GVAR(enableAmmoCookoff) { 
// For CBA Setting Switch: we can eliminate and just use (ammoCookoffDuration == 0)
```
are we ok actually doing this, I think it might have been written back when we though we would lose all saved setting when converting?
=>  Cookoff - Reword settings and move to cba

addons/common/ACE_Settings.hpp, addons/common/functions/fnc_cbaSettings_convertHelper.sqf, addons/repair/functions/fnc_getHitPointString.sqf, circle.yml, tools/check_strings.py
Checks that all used strings exist in stringtables
Could add to CI
example run with `-u` to check for unused strings
```
-----------
String str_ace_action_accept_request_key_title defined but not used
String str_ace_action_accept_request_key_tooltip defined but not used
String str_ace_action_decline_request_key_title defined but not used
String str_ace_action_decline_request_key_tooltip defined but not used
String str_ace_advanced_ballistics_simulationradius_description defined but not used
String str_ace_advanced_ballistics_simulationradius_displayname defined but not used
String str_ace_advanced_ballistics_windinfokey defined but not used
String str_ace_aircraft_closecargoramp defined but not used
String str_ace_aircraft_opencargoramp defined but not used
String …
```
=> Add tool to verify stringtable entries exist

addons/medical_gui/XEH_postInit.sqf, addons/medical_gui/functions/fnc_addTreatmentActions.sqf
Don't compile self interaction for every man
ref #6792
=> Medical - Add self interaction when needed

optionals/nocrosshair/CfgInGameUI.hpp, optionals/nocrosshair/CfgWeaponCursors.hpp, optionals/nocrosshair/config.cpp
- fix #6904.
Current config doesn't work.
=> No Crosshair - Fix config

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/XEH_PREP.hpp, addons/medical_treatment/functions/fnc_canBandage.sqf, addons/medical_treatment/functions/fnc_canStitch.sqf
- Add fnc_canStitch
- Added condition in Medical Actions
- #6913
=> Medical - Add condition for surgicial kit

addons/hellfire/CfgMagazineWells.hpp, addons/hellfire/CfgWeapons.hpp, addons/hellfire/config.cpp, optionals/compat_rhs_usf3/CfgMagazineWells.hpp, optionals/compat_rhs_usf3/CfgMagazines.hpp, optionals/compat_rhs_usf3/config.cpp
Close #5957
Using RHS model, adds new mag that uses ace's guidance for pylon options RHS choppers.
=> RHS Compat - Add 2 round hellfire to pylon options

addons/ballistics/CfgMagazineWells.hpp
=> Ballistics - Remove ace mags from incompatible weapons

addons/medical_feedback/XEH_postInit.sqf, addons/medical_feedback/functions/fnc_effectHeartBeat.sqf
and limit setVar for acre/tfar (slightly less network traffic)
effectHeartbeat would recurse with no params
`[FUNC(effectHeartBeat), [], _waitTime] call CBA_fnc_waitAndExecute;`
so `_heartbeat` was undefined, this changes it to get the current HR each time the func is run
=> Medical Feedback - fix heart rate effect

addons/medical/functions/fnc_addDamageToUnit.sqf, addons/medical_engine/XEH_postInit.sqf, addons/medical_engine/functions/fnc_handleDamage.sqf, addons/medical_engine/script_macros_medical.hpp, addons/medical_feedback/XEH_postInit.sqf, addons/medical_status/functions/fnc_setDead.sqf
`DISABLE_VANILLA_DAMAGE_EFFECTS` was only defined in medical_feedback
so it wasn't running, and I'm pretty sure this is where it belongs
it's also now under a `hasInterface` check
=> Medical Feedback - Fix DISABLE_VANILLA_DAMAGE_EFFECTS

addons/ballistics/CfgWeapons.hpp, addons/hellfire/CfgWeapons.hpp
- title
- same as https://github.com/CBATeam/CBA_A3/pull/1135
- fixes #6973
=> += for magwells

addons/logistics_wirecutter/script_component.hpp
Finally you can cross the border without explosives 😉 
Some of the fences have spring-guns that should trigger when trying to cut the fence, but that will be handled in compat.
=> Wirecutter - Add GM fences to wirecutter list

addons/medical_status/CfgEventHandlers.hpp, addons/medical_status/functions/fnc_initUnit.sqf, addons/medical_treatment/functions/fnc_treatmentFullHealLocal.sqf
For old issue https://github.com/acemod/ACE3/issues/3169
As long as we have good default values for all of our `getVariable` we should be able to skip broadcasting default values on unit init.
e.g. 200 AI * 20 setVars = useless network traffic
=> Medical - Skip unneeded setVars on initUnit

addons/medical_blood/XEH_postInit.sqf, addons/medical_blood/functions/fnc_onBleeding.sqf, addons/medical_blood/functions/fnc_spurt.sqf
- don't bleed for dead players
- switch to "nextTime" time calc reduces calls to `GET_BLOOD_LOSS`
- min damage in already done in handleWoundReceived
=> Medical Blood - Small optimizations

addons/common/XEH_postInit.sqf, addons/medical_engine/functions/fnc_setStructuralDamage.sqf, addons/repair/XEH_postInit.sqf, addons/repair/functions/fnc_setDamage.sqf, addons/repair/functions/fnc_setHitPointDamage.sqf
- fix #6923
- setHit(PointDamage) fails when used on vehilces with damage disabled! The wiki is wrong on this, but they kept reverting my edit because it apparently worked 5 years ago in Arma 2. Just reset after use
- command has the same locality as setHit(PointDamage) so everything should work out.
=> Repair - Fix taking wheels from invincible vehicles

addons/advanced_fatigue/XEH_preInit.sqf, addons/advanced_fatigue/functions/fnc_handleEffects.sqf, addons/medical_treatment/functions/fnc_getBandageTime.sqf, addons/medical_treatment/functions/fnc_treatment.sqf, addons/medical_treatment/functions/fnc_treatmentFailure.sqf, addons/medical_treatment/functions/fnc_treatmentSuccess.sqf
part of #6913
caps max anim speed to 3x, which still seems fast but not terrible
and add lock to prevent advanced fatigue from reseting setAnimSpeedCoef
needs mp testing, but I don't think we need global events for the setters (AF doesn't use it)
=> Treatment - cap max animation speed

addons/common/functions/fnc_uniqueItems.sqf
Fixes popup script error when using function in scheduled (still worked fine)
`[] spawn {x3 = [player] call ace_common_fnc_uniqueItems};`
```
Error Undefined variable in expression: ace_common_uniqueitemscache
```
tiny bit faster as well
=> Common - Fix script error with uniqueItems in scheduled

optionals/tracers/CfgAmmo.hpp, optionals/tracers/CfgMagazines.hpp
- Fix wrong reference to CfgAmmo classes in CfgMagazines of four magazines
- Fix wrong tracer colour of one ammo class (red tracers are already included in the game)
=> Fixed incorrect classnames in tracer magazines

addons/ballistics/CfgAmmo.hpp, addons/ballistics/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgMagazines.hpp, optionals/compat_rhs_usf3/CfgWeapons.hpp
- Fix the RHS MP7 magazines and zeroing.
- Update the BI P90 and RHS MP7 ballistics with these [HK MVs](https://www.heckler-koch.com/en/products/military/submachine-guns/mp7a1/mp7a2/ammunition.html) and [BCs](https://www.thefirearmblog.com/blog/2016/10/24/modern-personal-defense-weapon-calibers-4-6x30mm-hk/) references.
AirFrictions according with all MVs at the normal conditions (15°C, 1013 hPa, 0%).
> ##########################################
Ammo Class: rhs_ammo_46x30_FMJ
_Drag model: 7_
_Ballistic coefficient: 0.089_
MaxRanges (m): [300, 300]
MuzzleVelocities (m/s): [615, 625]
Max. Velocity diff (m/s): 19.83
Max. Drop diff (cm): 0.99
Max. Tof diff (ms): 4.0
Optimal airFriction: 0.002635
##########################################
Ammo Class: …
=> Ballistics - BI P90 and RHS MP7 updated

addons/gunbag/CfgVehicles.hpp, addons/gunbag/functions/fnc_calculateMass.sqf, addons/gunbag/functions/fnc_canInteract.sqf, addons/gunbag/functions/fnc_hasGunbag.sqf, docs/wiki/framework/gunbag-framework.md
From Feature request
https://github.com/acemod/ACE3/issues/3594#issuecomment-495924308
@ImplicitDeny
Makes it easier for 3rd parties to create gunbags without adding a ACE dependency.
Slight performance hit (I assume) for config lookup instead of isKindOf, though isKindOf is also not much cheaper I think. Not big enough difference to be worth testing or caching.
Or... Maybe caching, leaving that up to you, don't think its worth.
Noticed we don't have a gunbag wiki page. Someone should add one someday ^^
=> Move gunbag type from inheritance to config property

addons/missileguidance/functions/fnc_checkLos.sqf
- Make missiles using optical guidance (for example the Javelin) now lose lock once the target gets behind smoke
0.001 as a visibility limit seemed reasonable with my testing with a smoke grenade, I'd rather go higher (missiles would then easier lose lock) than lower. If a tank pops a smoke wall, it should be _well_ within that limit anyways.
Not tested with actually firing a missile yet, since the tank would have to pop smoke at just the right time and also be moving, because the missile will still fly straight if it loses lock.
Closes #7012, also ref. #6744 which still needs additonal code when actually locking on to fix completely.
=> Missileguidance - Use checkVisibility to test LOS for missile seekers

addons/medical_gui/functions/fnc_onMenuOpen.sqf
Effectively it just hides the "Airway Management" button to reduce confusion
This could also just be done statically in gui.hpp, but this way might be better if we or others implement airway stuff (I think someone has done this?)
=> Medical Menu - Hide categories if they don't have any actions

addons/medical_treatment/CfgWeapons.hpp
- The replacement setting may be disabled so we shouldn't prevent their addition
- If it isn't, they will be replaced with suitable items which is fine (and someone may want to design a mission that works either way)
=> Unblacklist vanilla medical items from arsenal

addons/medical_damage/ACE_Medical_Injuries.hpp, addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf, addons/medical_status/functions/fnc_getBloodLoss.sqf, addons/medical_status/functions/fnc_getBloodPressure.sqf, addons/medical_status/functions/fnc_getCardiacOutput.sqf, addons/medical_status/functions/fnc_updateWoundBloodLoss.sqf, addons/medical_vitals/functions/fnc_updateHeartRate.sqf
My attempt at fixing the bleeding in current medical rewrite. If we go this route it will deprecate #6941. My researching steps before implementing these changes can be found on #6906.
I'm simplifying the nastiness calculations so that the wound config specifies the worst wound and we scale it between 25% to 100% based on the wound damage and number of wounds received. Worth noting that the damage value is larger when limbs are damaged, so I'm scaling wounds to those half as much.
Similarly I've updated the wound configs to more reasonable maximum bleeding values based on the fact that they're percentages of cardiac output being bled.
~~In my testing, these values tend to give a bleeding of roughly 0.075 for a typical single gunshot wound which translates to approximately 5 minutes before …
=> Medical - Fix severity of wound bleeding and adjust cardiac output calculations

addons/medical_statemachine/XEH_preInit.sqf, addons/medical_statemachine/functions/fnc_handleStateUnconscious.sqf, addons/medical_status/functions/fnc_initUnit.sqf, addons/medical_status/functions/fnc_setUnconscious.sqf, addons/medical_treatment/XEH_postInit.sqf, addons/medical_treatment/functions/fnc_fullHealLocal.sqf, addons/medical_vitals/XEH_preInit.sqf, addons/zeus/functions/fnc_moduleHeal.sqf
- #6913 > Fix the unconscious toggle zeus module not being permanent
use `_lastWakeUpCheck max CBA_missionTime`, as ace_medical_fnc_setUnconscious will set this to a large number
- fix problem with fullHealLocal not waking unit up with unstable vitals
=> Medical - Fix unconsicous problems with minWaitingTime and fullHealLocal

addons/medical_treatment/functions/fnc_getBandageTime.sqf
Was scaling treatment time by `_amountOf`
e.g. if you have 10x wounds, a bandage would still only treat the `effectiveness` defined in the configs
so it would take longer, but you wouldn't actually be doing any more work
- `_amountOf > _effectiveness` - scale by 1
- `_effectiveness > _amountOf` - scale down to a max of 2/3
also further increases min bandage time to 2.25 to help with animation problems
=> Medical Treatment - Scale bandage time based on amount of wound treated

addons/medical_engine/script_component.hpp
- Make Medical beautified component names consistent
=> Medical Engine without parentheses

addons/maptools/functions/fnc_handleMouseButton.sqf
If shift is still held down on mouse button release then we can assume they were already drawing a straight line so don't convert it to the thick ace style
=> Maptools - Don't convert vanilla straight lines

addons/medical_blood/CfgEventHandlers.hpp, addons/medical_blood/README.md, addons/medical_blood/XEH_PREP.hpp, addons/medical_blood/XEH_postInit.sqf, addons/medical_blood/config.cpp, addons/medical_blood/functions/fnc_cleanupLoop.sqf, addons/medical_blood/functions/fnc_createBlood.sqf, addons/medical_blood/functions/fnc_handleWoundReceived.sqf, addons/medical_blood/functions/fnc_init.sqf, addons/medical_blood/functions/fnc_isBleeding.sqf, addons/medical_blood/functions/fnc_onBleeding.sqf, addons/medical_blood/functions/fnc_spurt.sqf, addons/medical_blood/initSettings.sqf, addons/medical_blood/script_component.hpp, addons/medical_blood/stringtable.xml
- Make the `enabledFor` setting able to be changed mid-mission
- Add settings for medical blood (max objects, lifetime) similar to litter
- General cleanup of the component
=> Medical Blood - Settings improvements and cleanup

addons/medical_status/functions/fnc_setUnconscious.sqf
This just reimplemented the behaviour from #5864
I believe we thought using `setUnconscious` command would make this unnecessary, but testing seems to show that's not the case.
=> Stop AI firing at unconscious units

addons/quickmount/XEH_postInitClient.sqf, addons/quickmount/functions/fnc_getInNearest.sqf
For small static weapons getInNearest would sometimes not detect the vehicle as the `getCameraViewDirection` may be pointing at the "get in" interaction node and not the vehicle
this makes a 2nd attempt directly at the `aimPos` of the target
(we still need to do the raycast to check `GVAR(distance)`)
=> QuickMount - Improve interact menu getIn for static weapon

addons/medical_feedback/functions/fnc_initEffects.sqf
Fix screen blanking out for 0.3 sec on first time taking any pain
`[player, 0.01] call ace_medical_fnc_adjustPainLevel`
ppEffect uses initial value from initEfects (which was black screen)
and then alternates between _initialAdjust and _delayedAdjust in FUNC(effectPain)
only effected painEffectType = 0
=> Medical Feedback - Fix short blackout on any pain

optionals/compat_rhs_usf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgMagazines.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp, optionals/compat_rhs_usf3/config.cpp
Add ACE Explosives functionality to RHS:USAF explosives (demoblocks and mines). Addresses issue #7054.
close #7054
=> [compat_rhs_usf3] ACE Explosives functionality for RHS USAF

addons/explosives/CfgAmmo.hpp
Update the class inheritance for `ACE_IEDLandSmall_Range_Ammo` from `IEDLandBig_Remote_Ammo` to `IEDLandSmall_Remote_Ammo` so the correct model is used. Addresses issue #7015.
close #7015
=> [explosives] Correct class inheritance for ACE_IEDLandSmall_Range_Ammo

addons/medical_engine/functions/fnc_handleDamage.sqf
Shoot man with autocannon
` incoming: _allDamages=[[2.21103,3,"Head"],[5.88152,4,"Body"],[5.04804,1.15436,"LeftArm"],[5.30232,1.27997,"RightArm"],[20.4579,1.1125,"LeftLeg"],[35.2891,1.05652,"RightLeg"]], _damageStructural=0.398899`
2.2 damage to head should be fatal, but it instead picks the largest leg damage, which takes a while to kill
=> Medical Engine - Report any fatal head damage

addons/common/stringtable.xml
- title
- Remove the camel case in the translation of anywhere in french
=> FIX French STR_ACE_Common_Anywhere

docs/wiki/development/coding-guidelines.md
=> Missing return line in coding guide lines for SETPVAR

addons/zeus/functions/fnc_moduleSetMedicalVehicle.sqf
- Title
- Since medical rewrite a vehicle is medical  if `isMedicalVehicle` is setted to `true`. Now Zeus module set variable `ace_medical_isMedicalVehicle` instead of `ace_medical_medicClass`
=> Zeus - FIX ace_zeus_fnc_moduleSetMedicalVehicle setting wrong variable

addons/interact_menu/XEH_preInit.sqf, addons/interact_menu/functions/fnc_addActionToClass.sqf, addons/interact_menu/functions/fnc_compileMenu.sqf, addons/laser/functions/fnc_addLaserTarget.sqf, addons/medical/dev/test_hitpointConfigs.sqf
- Currently any mission with sufficiently enough soldiers placed crashes when loading a savegame, because the game runs out of memory when deserializing arrays.
- The addInteractionToClass function from interact_menu with allowInheritance flag set adds an (retroactively applied) Init event handler to the object class for every added action, so the actions can be added to descendant classes of the base class the action was added to.
- ACE Medical adds a lot of actions to the CAManBase base class.
- This means ~250 more Init events on CAManBase when Medical is loaded.
- The array is referenced on every CAManBase object and thus creates a big save file, which cannot be loaded without running out of memory.
- This PR rewrites the allowInheritance part …
=> Interaction Menu - fix a crash when loading savegames

addons/viewdistance/functions/fnc_changeViewDistance.sqf
- Fix #7141 
Needs to be tested and made sure switching functions accordingly. I assumed here that when switching to "Off" nothing changes (unless it was in FoV mode) and is simply a way to allow setting object view distance via vanilla settings (simple disable of ACE system).
=> Fix undefined variable in View Distance

addons/movement/functions/fnc_inventoryDisplayLoad.sqf
- Fix the Inventory Weight display from being hidden when the Stream Friendly UI setting is enabled
=> Movement - Display Inventory Weight in Stream Friendly UI Mode

addons/common/XEH_postInit.sqf
https://community.bistudio.com/wiki/UAVControl
>Since Arma 3 v1.95.146028 this command returns both driver and gunner units if the UAV is controlled by 2 players. Here is the list of all expected outputs:
>[player1, "DRIVER", player2, "GUNNER"] - player1 is controlling the UAV and is the pilot, player2 is controlling UAV and is the gunner
Using UAV Terminal, I still can't control a UAV in-use by someone else, but maybe that will come later?
=> Common - Handle changes to UAVControl command (multi seat)

addons/rearm/functions/fnc_addRearmActions.sqf, addons/rearm/functions/fnc_rearm.sqf, addons/rearm/functions/fnc_rearmEntireVehicle.sqf, addons/rearm/initSettings.sqf, addons/rearm/stringtable.xml
- Add a setting to change the distance a vehicle can be rearmed at.
Someone asked for it on slack and I figured that this could indeed be a setting, the default value is set to the current value (20m) minimum at 10 and maximum at 50.
=> Rearm - Add distance setting

AUTHORS.txt, docs/wiki/framework/interactionMenu-framework.md
- update the wiki description of the interaction menu framework
- adds a hint that functions will be not executed on server
- removes 'it is generally preferred to add actions via config' as suggested by jonpas on Slack
=> Update wiki description of interaction framework

README.md
- Use Slack badge from shields.io
- No longer using Slackin, Community Inviter does not provide a Markdown badge.
=> Use Slack badge from shields.io

addons/arsenal/functions/fnc_statBarStatement_accuracy.sqf
- Fix statBarStatement still using AI values for firemodes 
Fixes #7162
=> Fix ACE Arsenal accuracy stat bar being innacurate

addons/common/XEH_postInit.sqf, addons/common/functions/fnc_loadPerson.sqf, addons/common/functions/fnc_loadPersonLocal.sqf, addons/common/functions/fnc_nearestVehiclesFreeSeat.sqf, addons/common/functions/fnc_unloadPerson.sqf, addons/common/functions/fnc_unloadPersonLocal.sqf, addons/medical/dev/watchVariable.sqf, addons/medical_engine/functions/fnc_setUnconsciousAnim.sqf, addons/medical_status/functions/fnc_setUnconscious.sqf, addons/medical_treatment/functions/fnc_loadUnit.sqf, addons/medical_treatment/functions/fnc_unloadUnit.sqf, addons/medical_treatment/stringtable.xml
- Fix unit being in locked animation with switchMove (If unit was unloaded from a vehicle, they may be in anim "deadstate" instead of "unconscious")
- Add hint when unloading unit (on success)
- Don't allow loading uncon into vehicles with `ejectDeadCargo=1` (e.g. quad bike)
- Added error logging (on both machines)
Also, removed use of `getvariable [QGVAR(loaded_persons)`, didn't see any reason why it existed
=> Medical - Improve loading/unloading of unconc patients

addons/main/script_mod.hpp, include/x/cba/addons/main/script_macros_common.hpp
- Title
**Merge after https://github.com/CBATeam/CBA_A3/pull/1221 is released!**
TODO:
- With cleaned-up quoting `##`
=> Use CBA Versioning System properly

docs/wiki/frameworkx/fortify-framework.md
- Chat command is `#ace-fortify` not `#fortify`, acemod/ACEX#192
=> Wiki - Fix incorrect fortify chat command example

Makefile, addons/advanced_ballistics/config.cpp, addons/advanced_ballistics/functions/fnc_initializeTerrainExtension.sqf, addons/common/config.cpp, addons/common/functions/fnc_checkFiles.sqf, addons/fcs/config.cpp, addons/interact_menu/config.cpp, addons/medical_damage/config.cpp, addons/medical_damage/functions/fnc_woundsHandler.sqf, addons/optionsmenu/config.cpp, docs/wiki/development/extension-guidelines.md, docs/wiki/user/information-center.md, extensions/CMakeLists.txt, extensions/advanced_ballistics/AdvancedBallistics.cpp, extensions/break_line/ace_break_line.cpp, extensions/clipboard/ace_clipboard.cpp, extensions/common/shared.hpp, extensions/common/vector.hpp, extensions/fcs/ace_fcs.cpp, extensions/medical/handleDamage.cpp, extensions/medical/medical.cpp, extensions/parse_imagepath/ace_parse_imagepath.cpp, tools/make.py
~~Track in one PR so we don't need to constantly rebuild dlls~~ No rebuilds required for now anyways.
Contains:
- #6809
- #7171
- #5762
=> Extension changes for Medical Rewrite and Linux compilation

addons/medical_gui/functions/fnc_updateInjuryList.sqf, addons/medical_gui/stringtable.xml
- Add stringtable entry for "Partial %1" wound description
- Fix injury list color flashing when an entry was selected
=> Medical GUI - Localize partial wound, fix injury list color flashing

addons/laserpointer/CfgJointRails.hpp
- Fix laserpointer not building
https://github.com/acemod/ACE3/blob/e8b104fe6129f33c1fb2b981afdf4dcf38a2ee13/addons/laserpointer/CfgWeapons.hpp#L3
=> Remove duplicate class declaration from laserpointer

optionals/compat_rhs_afrf3/CfgWeapons.hpp
- Fix missing RHS AFRF static weapon icons
- Change 3d-ish Kord image used by NSV to same style as the other icons and correct NSV image
- Change Metis image used by Kornet to correct Kornet image
**Current pboproject output:**
```
Warning: rapWarning: **********missing file(s)***************
Warning: \z\ace\addons\compat_rhs_afrf3\CfgWeapons.hpp circa Line 172: \rhsafrf\addons\rhs_heavyweapons\data\ico\podnos_2b14_ca.paa
Warning: \z\ace\addons\compat_rhs_afrf3\CfgWeapons.hpp circa Line 213: \rhsafrf\addons\rhs_heavyweapons\data\ico\kord6u16sp_ca.paa
Warning: \z\ace\addons\compat_rhs_afrf3\CfgWeapons.hpp circa Line 233: \rhsafrf\addons\rhs_heavyweapons\data\ico\ags_static_CA.paa
Warning: \z\ace\addons\compat_rhs_afrf3\CfgWeapons.hpp circa Line 253: …
```
=> Update RHS AFRF static weapon carry icons

optionals/compat_rhs_usf3/CfgWeapons.hpp
- Fix missing RHS USF static weapon icons
- Change editor preview image used by M2 to same style as the other icons
**Current pboproject output:**
```
Warning: rapWarning: **********missing file(s)***************
Warning: \z\ace\addons\compat_rhs_usf3\CfgWeapons.hpp circa Line 448: \rhsusf\addons\rhsusf_heavyweapons\data\ico\mortar_m251_CA.paa
Warning: \z\ace\addons\compat_rhs_usf3\CfgWeapons.hpp circa Line 489: \rhsusf\addons\rhsusf_heavyweapons\data\ico\mk19_stat_CA.paa
Warning: \z\ace\addons\compat_rhs_usf3\CfgWeapons.hpp circa Line 509: \rhsusf\addons\rhsusf_heavyweapons\data\Ico\tow_static_CA.paa
\z\ace\addons\compat_rhs_usf3\config.cpp has errors
rapWarning: **********missing file(s)***************
Missing File Summary
CfgWeapons.hpp : …
```
=> Update RHS USF static weapon carry icons

addons/arsenal/functions/fnc_onLoadoutsClose.sqf, addons/arsenal/functions/fnc_onLoadoutsOpen.sqf
It's plain annoying when you are close to a building or wall or any kind of obstacle, then carefully position your camera such that you can see yourself,
but once you open the loadouts selection your camera is suddenly inside a wall and you see pure nothingness, or another player is standing in the way such that you can't see yourself.
You have to constantly enter/leave the loadouts menu to be able to see if the loadout that you just loaded is the one you wanted, and opening the loadout menu with dozens of saved loadouts is quite slow.
=> Arsenal - Don't force Camera position in Arsenal Loadouts list

addons/medical/functions/fnc_addDamageToUnit.sqf
```
#define ALL_BODY_PARTS ["head", "body", "leftarm", "rightarm", "leftleg", "rightleg"]
#define ALL_SELECTIONS ["head", "body", "hand_l", "hand_r", "leg_l", "leg_r"]
```
Old medical took: `[player, 2, "leg_r", "stab"] call ace_medical_fnc_addDamageToUnit`
somehow it got swapped around
now works with either
=> Medical - Fix addDamageToUnit

.github/workflows/extensions.yml, extensions/medical/DamageType.cpp
- Build extensions on every PR that makes changes in `extensions/` folder or its sub-folders (max 5 levels deep due to no `**` pattern support) and provide them in build artifacts for easier testing (they will not be built in `RelWithDebInfo` for Windows, but just `Debug`.
Only Windows at the moment. Not sure how to install multilib package on Ubuntu for `bits/c++config.h`.
=> Add Extensions CI Workflow (Windows)

addons/realisticnames/CfgWeapons.hpp, addons/realisticnames/stringtable.xml
- Add the translation of the Contact rifles (except shotguns).
References from the [MSBS Grot Wiki](https://en.wikipedia.org/wiki/MSBS_rifle) and the [manufacturer](http://fabrykabroni.pl/) for the Promet.
References from various sources and Wikis for the AK15 variants (AK12 chambered in 7.62x39 mm).
=> Realistic names - Contact DLC rifles added

addons/common/functions/fnc_arithmeticGetResult.sqf, addons/common/functions/fnc_arithmeticSetSource.sqf
- Optimize `arithmeticGetResult` common function by using `selectMax` and `selectMin` commands rather than `count` loop
- Will provide a small performance improvement
- For the current `ACE_setCustomAimCoef` (2 sources) with the "max" operation: ~0.0234 ms to ~0.0207 ms
- Change `count` to `forEach` (faster than `count` + `true/false/nil`)
- Cleanup some unnecessary parentheses
=> Common - Optimize arithmeticGetResult function

addons/safemode/functions/fnc_lockSafety.sqf
-  Remove a (legacy?) check from fnc_lockSafety which prevented it from working if the keybind was a superset of the vanilla 'switch fire mode' keybind. The check seems to be trying to prevent a conflict, but that's already handled by cba keybinds.
Example:
- switch fire mode - F
- toggle safety - Ctrl+F
- when pressing Ctrl+F nothing happens
=> Safemode - Fixed keybind conflict

addons/optionsmenu/functions/fnc_debugDumpToClipboard.sqf
Only show no-defaults,
so dumps are a readable ~30 lines instead of 300
also fix max pfeh display (old code was valid for CBA from 2011 😄 )
=> Debug to clipboard - Cleanup settings dump

addons/explosives/Cfg3DEN.hpp, addons/explosives/config.cpp, addons/explosives/stringtable.xml
- Add 3DEN attribute to control if unit is an ace EOD
- #7077
=> Explosives - Add ace_isEOD 3DEN attribute

addons/refuel/functions/fnc_refuel.sqf, addons/refuel/functions/fnc_turnOff.sqf, addons/refuel/functions/fnc_turnOn.sqf, docs/wiki/framework/events-framework.md
@synixebrett requested this.
`ace_refuel_refuelTick` might be renamed to just `ace_refuel_tick` ?
We also want a `refuelDone` event, but for that we need to store the amount of fuel that was transferred in the previous interaction.
I think local event is enough for this?
Todo:
=> Refuel - Add events for start, stop and progress

addons/medical_treatment/initSettings.sqf
Just changes the default of woundReopening; 
I believe this setting has a high chance of causing confusion for unexperienced player.
Matches old medical
```
class GVAR(enableAdvancedWounds) {
value = 0;
```
=> Medical - Change WoundReopening default setting

addons/repair/ACE_Repair.hpp, addons/repair/ACE_Settings.hpp, addons/repair/functions/fnc_canRepair.sqf, addons/repair/functions/fnc_repair.sqf, addons/repair/initSettings.sqf, addons/repair/stringtable.xml
- Add `miscRepairRequiredItems` and `fullRepairRequiredItems` settings to control whether a toolkit is required for misc and full repairs
- Remove need to read `_values` array from `ACE_Settings` config
- Close #6549
=> Repair - Add settings to control item requirements for different actions

addons/arsenal/functions/fnc_fillRightPanel.sqf
Contact device has 10 muzzles
```
13:00:00 Error in expression <{
((_compatibleMagazines select _index) select _subIndex) pushBackUnique (config>
13:00:00   Error position: <select _subIndex) pushBackUnique (config>
13:00:00   Error Zero divisor
13:00:00 File z\ace\addons\arsenal\functions\fnc_fillRightPanel.sqf..., line 83
```
=> Arsenal -  Fix script error for weapons with 3+ muzzles

addons/map/functions/fnc_initMainMap.sqf
Start walking then open map for the first time and it always radically moves map to uppper left corner of map.
`ctrlMapScreenToWorld [0.5, 0.5];` doesn't seem to be set until a frame after it's init
=> Map - Fix map shake moving to upper left corner

addons/cookoff/CfgEden.hpp, addons/cookoff/XEH_postInit.sqf, addons/cookoff/functions/fnc_handleDamage.sqf, addons/cookoff/initSettings.sqf, addons/cookoff/stringtable.xml
- Add an extra cookoff setting to allow cookoff to only occur on player crewed vehicles
I know cookoff is now disabled by default due to it's weird issues where vehicles could take excessive amounts of damage. For people that mainly do co-ops it would be nice to still have it work for player controlled vehicles.
Tested locally and seems to work as expected, open to input especially on names (I'm terrible at them)!
=> Cookoff - Allow enabling only on player crewed vehicles

addons/spectator/functions/fnc_ui.sqf
Fixes #7186
- Restore HUD for player when coming out of spectator just in case it was hidden by `ace_spectator_fnc_cam_setCameraMode`
=> Spectator - Restore HUD when coming out of spectator

addons/tagging/stringtable.xml
- "Black spray paint" -> "Spray Paint (Black)"
I was in the arsenal and this annoyed me, slight QOL improvement
=> Tagging - Group spray paint items in Arsenal

.github/workflows/documentation.yml, tools/deploy.py
Default GitHub provided `${{ secrets.GITHUB_TOKEN }}` has no settable permission to push past protected branches where we specifically allow it. This PR falls back to @ace3mod's Private Access Token (set in repository secrets) which has those permission, like we did with Travis CI.
=> Use @ace3mod for documentation updates

addons/repair/stringtable.xml
ref #7274 👍 - only found after merge because pr was old
Run python3 tools/stringtable_validator.py
Checking addons/repair/stringtable.xml:
ERROR: Key 'STR_ACE_Repair_MiscRepairRequiredItems_DisplayName' has 2 English translations.
ERROR: Key 'STR_ACE_Repair_MiscRepairRequiredItems_Description' has 2 English translations.
ERROR: Key 'STR_ACE_Repair_FullRepairRequiredItems_DisplayName' has 2 English translations.
ERROR: Key 'STR_ACE_Repair_FullRepairRequiredItems_Description' has 2 English translations.
Found 4 error(s).
=> fix repair strings

addons/flashsuppressors/CfgWeapons.hpp
Update for muzzle changes to JR - https://github.com/CBATeam/CBA_A3/pull/1184
```
Updating base class MuzzleSlot_65->asdg_MuzzleSlot_762MG, by z\ace\addons\flashsuppressors\config.cpp/CfgWeapons/LMG_Mk200_F/WeaponSlotsInfo/MuzzleSlot/ (original (a3\weapons_f\machineguns\m200\config.bin - no unload))
Cannot update non class from class z\ace\addons\flashsuppressors\config.cpp/CfgWeapons/LMG_Mk200_F/WeaponSlotsInfo/MuzzleSlot/compatibleItems/
```
=> Flashsuppressors - Update muzzle configs

addons/arsenal/RscDisplayMain.hpp
Ref: https://forums.bohemia.net/forums/topic/193161-ace3-a-collaborative-merger-between-agm-cse-and-ace/?do=findComment&comment=3387061
apparently doesn't exist with contact loaded, and we don't use it anyway.
=> Arsenal - Remove unused VRTraining class from Arsenal config

addons/common/XEH_PREP.hpp, addons/common/XEH_postInit.sqf, addons/common/functions/fnc_claimSafeServer.sqf
Usage:
```
["pickup", { 
systemChat format ["pickup %1", _this]; 
}] call CBA_fnc_addEventHandler; 
["ace_common_claimSafe", [player, x, false, "pickup"]] call cba_fnc_serverEvent;
```
because of network delay, two clients could claim the same object
this allows claims to be made on server, guaranteeing synchronization
=> Common - Network safe claim

addons/dragging/functions/fnc_getWeight.sqf, addons/dragging/script_component.hpp
- Improve dragging's `getWeight` function
- Now correctly handles separating glasses from "regular" items
- Adds weight of items and magazines attached to weapons
- Adds the weight of sub-containers (and their inventories) inside the object
=> Dragging - Improve getWeight function

tools/stringtablediag.py
- Title
We have over 2800 strings, Japanese is currently missing 5, which shows up as 100% because `2795/(2800+) >= 99.82%` which we round. Rounding to 2 decimals will show more accurate values.
=> Round stringtable completion to 2 decimals

addons/main/config.cpp
- `cba_main` requires all other CBA components, and `cba_common` requires A3 load orders
=> Clean up ace_main requiredAddons

addons/ballistics/CfgAmmo.hpp, addons/ballistics/CfgMagazineWells.hpp, addons/ballistics/CfgMagazines.hpp, addons/ballistics/stringtable.xml
- Change the vanilla buckshot from what appears to be No. 3 based on pellet count to No. 00, as No. 00 is the most common for combat shotguns.
- Add multiple additional types of shotgun projectiles, including Nos. 0, 1, 2, 3, 4 buckshot and No. 7 birdshot.
- Add magazines for them for the over/under and underbarrel shotguns.
* Changed to No4 birdshot for better performance. ~~The No. 7 bird shot has many more pellets/submunitions than the others and needs to be tested for performance issues~~.
* I haven't done extra magazines for the demining drone weapon, should they be added?
* I should probably do something with the `caliber` value for the ammo as shot does not penetrate armour well.
=> Ballistics - Add shotgun shell projectile magazine variety

addons/reload/CfgVehicles.hpp, addons/reload/XEH_PREP.hpp, addons/reload/XEH_postInit.sqf, addons/reload/XEH_preInit.sqf, addons/reload/functions/fnc_canCheckAmmoSelf.sqf, addons/reload/initSettings.sqf, addons/reload/stringtable.xml
- Adds an option to always have "Check ammo" self interaction, not only in static weapons
=> Add Check ammo self interaction setting

optionals/compat_rksl_pm_ii/CfgWeapons.hpp
fix the `RKSL_optic_PMII_312_sunshade` inheritance and the `Simplified zeroing` bug.
The ACE3 compat for the outdated RKSL Attachments Pack V2 can be found in the [RKSL official site](https://www.rkslstudios.info/index.php?/files/file/2-rksl-attachments-pack-v2-ace3-plugins/).
=> RKSL compat - Updated with the last RKSL v3.01

optionals/compat_rhs_afrf3/CfgWeapons.hpp, optionals/compat_rhs_usf3/CfgWeapons.hpp
- Change ace_hearing config on the IHADSS helmet to crew helmet level (0.6 muffling, 0.85 protection) instead of Peltor level (no muffling, 0.75 protection). While it inherits from a random FAST helmet, it is actually a heli pilot helmet; RHS's inheritance structure is just that nonsensical.
- Add ace_goggles `ACE_Protection` (protects from post processing caused by rotor downwash) to pilot helmets with visors for RHS blue and red (there don't seem to be any new items in green or other green). Inheritance branches out pretty heavily, so this is about as short as that code is gonna get.
=> RHS Compat - Change IHADSS hearing to crew, add pilot visors

addons/disposable/CfgWeapons.hpp
Fixes problem where the used launcher can still be reloaded, 
seems like bis added nlaw magwell at somepoint
I'm not sure if re-adding the magwell makes sense, but cba_disposables can be disabled by setting
=> Disposable - Fix magazineWell problems

addons/ballistics/stringtable.xml, addons/chemlights/stringtable.xml, addons/common/stringtable.xml, addons/map_gestures/stringtable.xml, addons/switchunits/stringtable.xml
- Add missing Czech translation for chemlights, ballistics, map_gestures, common, switchunits
- *Note: I was somewhat liberal with translating shotgun ammo and added caliber of the various types to description or short name where there was no description to "localize" the names to people who don't know US system (as we don't use it here AFAIK).*
- Part of https://github.com/acemod/ACE3/issues/367
=> Added missing Czech translation strings

addons/smallarms/CfgWeapons.hpp
- Fix #7326 
- Remove remnant from AGM - changing cursor/cross-hair (presumably because it looks better) but breaking item type for `BIS_fnc_itemType`.
Who uses cross-hairs anyways?
=> Remove cursor config for vanilla sniper rifles

addons/medical_treatment/stringtable.xml
The current names may be technically more accurate, but this makes it faster to find them in the arsenal.
=> Medical - Group Bandage Items

addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
- Remove "Atropine" from advanced medication setting description
- Improve clear trauma after bandage setting description - use "body parts" instead of "hitpoints"
- Minor reorganization of settings
- Remove unused strings
=> Medical Treatment - Settings cleanup

addons/medical_gui/stringtable.xml, addons/medical_treatment/stringtable.xml
Fix some typos in the Czech texts for medical items and GUI.
`Zdravotnikcá nabídka` → `Zdravotnická nabídka`
`Obvaz (Standartní)` → `Obvaz (Standardní)`
`Umístni tělo do pytle na mrtvoly` → `Umístit tělo do pytle na mrtvoly`
`Umístňuji tělo do pytle na mrtvoly...` → `Umisťuji tělo do pytle na mrtvoly...`
=> Czech medical typos and grammar

addons/medical_treatment/ACE_Medical_Treatment.hpp
- title, use [value from old medical](https://github.com/acemod/ACE3/blob/v3.12.6/addons/medical/ACE_Medical_Treatments.hpp#L1128), Close #7364
=> Fix incorrect reopening chance for QuikClot on large abrasions

addons/hearing/CfgVehicles.hpp, addons/hearing/functions/fnc_putInEarplugs.sqf, addons/hearing/functions/fnc_removeEarplugs.sqf, addons/interaction/CfgVehicles.hpp, addons/interaction/functions/fnc_joinTeam.sqf
- Added ability to suppress hint message for team switch
- Added ability to suppress hint message for earplugs
This ability can be useful when it comes to scripted auto solutions to avoid a heap of messages on spawn, respawn or recently logged in clients.
=> Changed: Scripted calls to putInEarPlugs/joinTeam won't show hint

addons/medical/stringtable.xml
- Title - ref. https://github.com/acemod/ACE3/issues/7378#issuecomment-570726654
Not sure if it's a direct multiplier due to connection with epinephrine effectiveness, so I used "boost" as is in the setting name.
Could also be improved with showing it as a percentage in the UI.
=> Medical - Fix epinephrine wake-up chance boost string

addons/cookoff/functions/fnc_cookOff.sqf, addons/cookoff/functions/fnc_cookOffBox.sqf, addons/cookoff/functions/fnc_engineFire.sqf, docs/wiki/framework/events-framework.md
- Broadcast `ace_cookoff_cookOff`, `ace_cookoff_cookOffBox` and `ace_cookoff_engineFire` globally, event wasn't sent locally before
- Add both events to events documentation
=> Cook Off - Change Cook Off events to global and add to events docs

.github/workflows/release-drafter.yml
- Prevent running it on forks and failing builds.
=> Tools - Run Release Drafter only on original ACE3 repository

addons/medical_treatment/stringtable.xml
- Because of this simple mention, many urban myths and legends continue to exist about blood conservation.
So I think it is best to remove it, especially because it can only create confusion.
=> fix translations: removes Blood_IV "keep cold"

addons/common/functions/fnc_getVersion.sqf
`ace_common_fnc_getVersion` currently returns "" due to using `getText()` on a number config entry. I'm unsure if using `versionStr` provides intended behavior since `version` is a shorter version of `versionStr`, this however provides a result which seems to be in line with the docstring above.
- Fix #7478 
- Changed `version` to `versionStr` based on the return type specified in docs, its likely that `version` used to contain `versionStr`'s information. If need be the alternative: `str getNumber ()` would also work.
=> Changed version to versionStr as fix for #7478

AUTHORS.txt, addons/overheating/functions/fnc_clearJam.sqf, addons/overheating/functions/fnc_jamWeapon.sqf
Fixed - click sound was heard all over the map
Added missing sounds
Close #6861
=> Overheating - Fix jamming sound

addons/medical_statemachine/initSettings.sqf
- Increase default Cardiac Arrest Time to 5 minutes.
As per research (by @alganthe I believe), this should be closer to reality. It can take more than that for brain cells to start dying.
Additionally, for gameplay reasons, this is a better default combined with all other settings on default.
=> Medical - Increase Cardiact Arrest Time to 5 min

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
- Add setting to allow transfusing blood for certain medic level
- Default value is "Medics only", same as the initial config value
Old medical had such a setting, thought it was nice to have it in the new one as well.
The German translation sounds weird to me, but oh well..
=> Medical - Add setting for medic level to transfuse IVs

docs/wiki/class-names.md
**Update classnames page:**
- Used 'ammo box' as type as that's what's used for the Hunt IR box, unsure on this.
=> Adding medical box to classnames page

addons/frag/functions/fnc_spallTrack.sqf
=> Frag - Fix spallTrack

addons/medical_status/functions/fnc_handleKilled.sqf
- Enables user input before respawn so that the respawn interface can be interacted with.
Addresses https://github.com/acemod/ACE3/issues/7356
=> [medical_status] Enable user input between death and respawn

addons/medical_status/functions/fnc_setCardiacArrestState.sqf
- Set unconsciousness only when entering Cardiac Arrest.
Addresses https://github.com/acemod/ACE3/issues/7448
=> [medical_status] Only set unconscious upon entering Cardiac Arrest

addons/medical_status/functions/fnc_handleKilled.sqf
A quick hotfix for the implementation of #7502
=> Only force enable input when player is killed

addons/map_gestures/functions/fnc_getProximityPlayers.sqf
- Use the given unit as centre for `nearEntities` in `ace_map_gestures_fnc_getProximityPlayers`
- Previous `(getPos _unit)` would result in an empty return when stood in a building as height is reported as ~0, so the search performs at ground level
- `nearEntities` requires `PositionAGL`, `getPos` gives `PositionAGLS`
=> Map Gestures - Use object itself as center for nearEntities in getProximityPlayers

addons/overpressure/functions/fnc_overpressureDamage.sqf
- Will not damage units from over pressure if damage is disabled
Fix for #7429
=> Backblast - Fix damage disabled units receiving damage from backblast

docs/wiki/development/coding-guidelines.md
- Fix formatting for `BIS event handlers warning` under section `7.3`.
Some HTML snuck in there, breaking the markdown.
=> Docs/Wiki - Fix formatting for BIS evh warning

addons/map/XEH_postInitClient.sqf, addons/map/initSettings.sqf
- change to CBA_fnc_addSetting not the internal fnc CBA_settings_fnc_init
- some vars can edited in the mission
- if BFT was disabled at mission start an den enabled it now works...
=> Map - Allow enabling BFT setting after mission start

addons/medical/XEH_preStart.sqf, addons/medical/dev/test_hitpointConfigs.sqf, addons/medical_engine/CfgVehicles.hpp
- Check all units linked by public items instead of public untis
- HitRightArm was missing (HitLeftArm used twice)
This picks up:
```
14:58:49 [ACE] (medical) INFO: Checking mans for medical hitpoints [160 units]
14:58:49 [ACE] (medical) WARNING: I_E_Uniform_01_coveralls_F has bad last hitpoint: ["HitFace","HitNeck","HitHead","HitPelvis","HitAbdomen","HitDiaphragm","HitChest","HitBody","HitArms","HitHands","HitLegs","Incapacitated"]
14:58:49 [ACE] (medical) WARNING: I_E_Uniform_01_coveralls_F missing ace hitpoints: ["HitFace","HitNeck","HitHead","HitPelvis","HitAbdomen","HitDiaphragm","HitChest","HitBody","HitArms","HitHands","HitLegs","Incapacitated"]
```
- close #7526
=> Medical - fix the Enoch pilot uniform not taking damage, fix hitpoints test

.github/stale.yml
Help-wanted tickets are easy to solve things, that the core team usually doesn't do because they are unimportant and to leave them to beginners.
Thus they often go "stale", but they shouldn't.
=> Don't mark help wanted as stale

addons/medical_status/functions/fnc_setUnconsciousState.sqf
When pilot of aircraft goes uncon then do "Unlock controls" user action 
(co-pilot will then have to do the "Take Controls" actions)
Recently saw a need for this 😄 
Could add a setting (or hidden getVar setting), don't really think it needs one.
=> Medical - Unlock air controls when going uncon

addons/fastroping/CfgVehicles.hpp, addons/fastroping/functions/fnc_deployAI.sqf, addons/fastroping/functions/fnc_deployRopes.sqf, addons/fastroping/functions/fnc_fastRopeServerPFH.sqf, addons/fastroping/script_component.hpp
- After introduction of different rope lengths, `deployRopes` does not unwind ropes when called from `deployAI` because a rope class is not provided
- This PR fixes that by using the old rope length of 34.5 when the config entry `GVAR(ropeLength)` is not a positive number
=> Fastroping - Fix deployAI not unwinding ropes

addons/medical_engine/functions/fnc_updateDamageEffects.sqf
- Ensure a splinted arm causes light aim fracture effects with appropriate settings
Currently the setting causes additional aim fracture effects when the arm has a fracture (array element = 1) while a splinted arm (array element = -1) does not cause any effects. Based on the name of the setting I assume it is intended to give light effects (2 per arm) while splinted with the "full fracture" effects being the same regardless of which setting is used.
=> Medical - Arm fracture effect not persisting with setting

addons/reload/functions/fnc_displayAmmo.sqf
For some reason ARMA never returns any muzzle for crewed/non crewed static weapons. Work around this by always returning whatever weapon the static weapon has no matter what
fixes #7540
=> Reload - Fix static weapon ammo check

addons/common/functions/fnc_setVolume.sqf, addons/medical_feedback/XEH_postInit.sqf, addons/medical_status/functions/fnc_setUnconsciousState.sqf
- Set players volume based on unconscious state
Fix https://github.com/acemod/ACE3/issues/7528
=> Medical Feedback - Set volume and radio usage based current unit

addons/main/script_mod.hpp, addons/medical/initSettings.sqf, addons/medical/stringtable.xml, addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf
- Add `fractureChance` setting, https://github.com/acemod/ACE3/issues/3594#issuecomment-570797080
- Cleanup unused strings
=> Medical - Add fracture chance setting

addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- Make players flinch and AI try to look away as a reaction to a flashbang explosion - previously both players and AI turned 180° away from the explosion, making it very confusing and weird for players to be suddenly turned around
- Improve effect strength calculation for AI using eye position instead of ground position
=> Grenades - Make flashbang reaction more authentic

addons/medical_engine/XEH_postInit.sqf
- Get units out of unconscious animation after a physix object hit them
Addressing issue #7403
Note:
This code might not be fully optimal as it runs on every local unit. Thanks to commy2 for show me the way of propositional calculus.
https://streamable.com/com1h
=> Medical - Fix being stuck in unconscious animation after ragdoll

addons/medical_gui/functions/fnc_updateInjuryList.sqf, addons/medical_treatment/functions/fnc_bandageLocal.sqf, addons/medical_treatment/functions/fnc_canBandage.sqf, addons/medical_treatment/functions/fnc_getBandageTime.sqf, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
- Combine `advancedBandages` and `woundReopening` settings into a single 3 option setting
- `woundReopening` was only used when `advancedBandages` was enabled - since `BasicBandage` can't reopen
- Remove "grey bandaged wounds" from displaying in injury lists
- Caused confusion as these weren't actual bandaged wounds instead, open wounds with amount of zero
- Improve injury lists wound entry adding code
=> Medical - Combine advancedBandages and woundReopening settings

addons/arsenal/functions/fnc_onSelChangedLeft.sqf
Fix #7352
`_compatibleMags` was undefined
so this also fixes re-adding same magazines when switching between weapons
e.g.
have rifle with drum mag, switch to different camo and it will keep same drum
=> Arsenal - Filter non-scope 2 mags from being auto-added

addons/interact_menu/XEH_clientInit.sqf, addons/interact_menu/functions/fnc_keyDown.sqf, addons/interact_menu/functions/fnc_keyUp.sqf
- title
- Global variables already prevent double execution of the event in case anyone is worred.
- close #7381
=> Interaction Menu - Fix MenuClosed event may not fire on menu type replacement

addons/nightvision/XEH_postInit.sqf, addons/nightvision/functions/fnc_onCameraViewChanged.sqf, addons/nightvision/functions/fnc_pfeh.sqf, addons/nightvision/script_component.hpp
- fix #6666 super satan
- replace close #6942
To explain: If the Magnification is > 3, we can safely assume that we're not looking down iron/holo/cqb sights, but are instead dealing with an optic with actual (!= from RMB zoom) magnification and thus integrated night vision (potentially with its own blur effects).
We need to refresh the effect every time magnification is changed from <3 to >3 and vice versa, as there is no OpticsMode event.
=> NightVision - Don't apply AimDownSightsBlur on optics with integrated night vision

optionals/realisticdispersion/$PBOPREFIX$, optionals/realisticdispersion/CfgWeapons.hpp, optionals/realisticdispersion/config.cpp, optionals/realisticdispersion/script_component.hpp
according with https://github.com/acemod/ACE3/pull/7532#issuecomment-589994082
=> Ballistics - Move dispersion to optional

addons/medical_status/XEH_PREP.hpp, addons/medical_status/XEH_preInit.sqf, addons/medical_status/functions/fnc_handleKilled.sqf, addons/medical_status/functions/fnc_handleKilledMission.sqf, addons/medical_status/functions/fnc_setDead.sqf
- replace close #7531
- close #7185
- close #3111
- Copies the fix for Object Killed event to the Mission Killed event (a.k.a. EntityKilled, which is a terrible name for a non entity=mission event...).
```sqf
bob1 addEventHandler ["Killed", { 
systemChat str ["Object Killed", _this]; 
}];
addMissionEventHandler ["EntityKilled", { 
systemChat str ["Mission Killed", _this]; 
}];
```
~~Note that execNextFrame is how we killed units pre rewrite. The biggest issue was incorrect returns, but Pabst solved that independently and removed my reason for moving setDamage into HandleDamage in the first place.~~
Secondary execution runs with null objects. Should dedmen fix https://feedback.bistudio.com/T149510, the issue will be gone.
=> Medical Status - Fix double execution of `killed` event

addons/arsenal/missions/Arsenal.VR/CfgEventHandlers.hpp, addons/arsenal/missions/Arsenal.VR/XEH_preInit.sqf, addons/arsenal/missions/Arsenal.VR/fnc_createTarget.sqf
Fix #7584
- Macros broke loading the mission's XEH_preInit
- With double killed XEH, 2nd time it's now objNull and threw script error because of a
`missionNamespace setvariable [_varName`
edit: I still think setting `objNull` is the best solution to the double killed xeh, just need to watch out for odd uses like this one
=> Arsenal - Fix main menu mission

addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- Launchers reloaded by an external player will be instantly loaded since
the external player already has to go through a loading bar.
=> Reload Launchers - Improve External Launcher Reload

addons/rearm/functions/fnc_getTurretMagazineAmmo.sqf
- Remove case sensitivity from class check in getTurretMagazineAmmo
Currently the check in getTurretMagazineAmmo compares the class used in cfgVehicles' magazines array (within the turret) to the config name in cfgMagazines (returned by magazinesAllTurrets). In some cases developers have not used the same capitalization in both of these places. Within most systems this is not a problem as config classes are not case sensitive, but in the case of getTurretMagazineAmmo it means the function fails leading to a failure of the rearm action.
=> Rearm - Fix vehicles failing rearm due to case differences

addons/explosives/config.cpp
The "Activate mine" action menu item was still showing, but only after an explosive was set, then diffused.
- Remove the "Activate mine" action menu item on a diffused explosive/mine
=> Explosives - Remove "Activate mine" action menu item

addons/respawn/functions/fnc_handleKilled.sqf
- Title
Required for ACRE2 to add compatibility for proper radio assignment in combination with ACE Respawn's Save pre-death gear.
Not sure what else to put into the event, since all the data is on the unit anyways.
I am also pretty sure adding the event on killed event is fine, as long as whatever uses the event runs in unscheduled to make sure it happens before respawn kicks in.
=> Respawn - Add save gear event

addons/medical_engine/functions/fnc_setStructuralDamage.sqf, addons/medical_engine/functions/fnc_updateDamageEffects.sqf, addons/medical_feedback/functions/fnc_playInjuredSound.sqf
`ERROR` no longer reports file, so I don't know even what func caused
`[ACE] (medical_engine) ERROR: Unit not local or null`
=> Medical - Improve some error msgs

addons/medical_damage/CfgAmmo.hpp, addons/medical_damage/XEH_preInit.sqf, addons/medical_damage/config.cpp, addons/medical_damage/functions/fnc_getTypeOfDamage.sqf, addons/medical_damage/functions/fnc_parseConfigForInjuries.sqf, addons/medical_engine/functions/fnc_handleDamage.sqf
- Add a new config property, `ACE_damageType`, to a variety of CfgAmmo base classes.
- Alter `fnc_getTypeOfDamage` to read this config property instead of having the values hard-coded. Results are cached.
- Override this property on `B_19mm_HE` and `B_35mm_AA` (fixes #7401)
Vanilla Badger, 1x indirect hit (very close), before:
after:
=> Medical Damage - Determine ammo damage type through config property

addons/reload/functions/fnc_displayAmmo.sqf
After shooting a rifle's GL, hitting check ammo would show there was a loaded shell and an incorrect mag count.
Now on empty it displays the count of total compatible mags
That code wasn't reachable before because there is a `if (_magazine == "") exitWith {};` at the top but seems to be the intent.
=> Reload - Fix check ammo display for empty GL launchers

addons/cargo/functions/fnc_loadItem.sqf
- Include vehicles with the tankx simulation type in the water damage fix
Some vehicles (in our case the M119A2) receive damage when loaded on terrains with low elevation. This seems to be the same issue as was already solved for any vehicle using carx simulation, but as these vehicles use tankx instead they do not get made invulnerable. 
Simply adding an OR statement for tankx is probably not the cleanest solution, but it appears there are only 3 PhysX simulation types in Arma (last being shipx) so it should be ok. Feel free to suggest a different solution otherwise.
=> Cargo - Fix tankx vehicles receiving water damage when loaded

addons/csw/functions/fnc_assemble_deployWeapon.sqf
This will help mission maker to track weapon deployment through CSW like the BI version does: https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#WeaponAssembled 
- This add a local event triggered when a CSW weapon is deployed successfully
- Add a `CBA_fnc_localEvent` under the name `ace_csw_deployWeaponSucceeded`
=> CSW - Add local event when weapon is deployed sucessfully

extensions/advanced_ballistics/AdvancedBallistics.cpp, extensions/artillerytables/artillerytables.cpp, extensions/artillerytables/artillerytables.hpp, extensions/break_line/ace_break_line.cpp, extensions/clipboard/ace_clipboard.cpp, extensions/dynload/ace_dynload.cpp, extensions/fcs/ace_fcs.cpp, extensions/medical/medical.cpp, extensions/parse_imagepath/ace_parse_imagepath.cpp
- Fix buffer overflows (only visible in Debug build) - following https://github.com/IDI-Systems/acre2/pull/924
- Artillery Tables for GCC - use `EXPORT` macro
Builds fine, but not tested in-game.
=> Extensions - Fix buffer overflows and Artillery Tables for GCC

addons/zeus/functions/fnc_moduleLoadIntoCargo.sqf
- the load in module wasnt triggering the ace_cargoLoaded module
Why is the ace_cargoLoaded event not in the https://github.com/acemod/ACE3/blob/master/addons/cargo/functions/fnc_loadItem.sqf fnc?
=> Zeus - Added ace_cargoLoaded event

addons/map_gestures/XEH_postInit.sqf, addons/map_gestures/functions/fnc_transmit.sqf
- simplify map gestures transmit process
- Reduces network traffic
- increases performance
- and opens doors for Zeus and Spectator implementations
=> Map Gestures - Improve transmit process

addons/grenades/functions/fnc_incendiary.sqf
- See title.
- Doesn't error with wrong type (setting was changed from boolean on/off to number off/players only/players and ai)
- Checks variable on vehicle (with setting as fallback)
- Doesn't trigger on empty or ai-only vehicles when setting is on "players only".
=> Grenades - use correct type for cookoff_enabled, check for AI and variable on vehicle

tools/pDummies/readme.md
These are dummy files for p drive to allow building with pboProject (check externals now always enabled)
Normally extracted a3 is still required
=> Tools - Add dummy files for check external

addons/medical_damage/CfgEden.hpp, addons/medical_damage/config.cpp, addons/medical_damage/functions/fnc_determineIfFatal.sqf, addons/medical_damage/functions/fnc_handleIncapacitation.sqf, addons/medical_damage/stringtable.xml, addons/medical_engine/script_macros_medical.hpp
- Allows mission makers to set damage threshold per unit
- added macro to get damage threshold
- if no variable is set on the unit the global CBA setting value will be used
The new macro differentiates between AI and player.
The variable name for this is currently `ace_medical_unitDamageThreshold`. This is the same name the old medical system used. However the value was an array of 3 values in the old system. Now it is just a number.
So, it is debatable which name for the variable should be used.
=> Medical - Add ability for unit specific damage threshold

addons/vehicles/XEH_postInit.sqf, addons/vehicles/initSettings.sqf, addons/vehicles/stringtable.xml
=> Vehicles - Configurable speed limiter step

addons/medical_damage/stringtable.xml
Add french translation for the following keys:
- STR_ACE_Medical_Damage_Eden_threshold_DisplayName
- STR_ACE_Medical_Damage_Eden_threshold_Description
=> Translations - Add French Medical Damage Eden threshold keys

addons/interaction/CfgVehicles.hpp
- Change Leave Group interaction so the new group is the same side as the old group, not the same side as the player themselves. This is the safer behavior, as player side doesn't necessarily match their group side.
=> New group side in Leave Group interaction is same as original group side

addons/interaction/CfgVehicles.hpp, addons/interaction/XEH_PREP.hpp, addons/interaction/functions/fnc_modifyTeamManagementAction.sqf
=> Interaction - Show current team color in Team Management menu

addons/hearing/functions/fnc_updatePlayerVehAttenuation.sqf
Hearing - Fix for "MrapAttenuation"
- Make hearing system understand "MrapAttenuation" used in B_MRAP_01_F
- Prevent players from getting deafened by own HMGs while in MRAPs
=> Hearing - Fix for "MrapAttenuation"

addons/aircraft/stringtable.xml, addons/common/stringtable.xml, addons/csw/stringtable.xml, addons/dragging/stringtable.xml, addons/fastroping/stringtable.xml, addons/medical/stringtable.xml, addons/medical_damage/stringtable.xml, addons/medical_feedback/stringtable.xml, addons/medical_treatment/stringtable.xml, addons/quickmount/stringtable.xml, addons/vehicles/stringtable.xml
- Adds missing Czech translation strings
- Part of #367 
**Notes:**
- Some fairly generic military shorthands like "AP" and "DU" haven't been translated as they're generally known, but their description has been fully translated.
- One medical translation was changed from literal translation to more descriptive of what actually happens.
=> Translations - Add missing Czech translation strings

addons/nightvision/CfgIRLaserSettings.hpp, addons/nightvision/config.cpp
- Increase the maximum amount of rendered IR rays to 64, as mentioned [here](https://youtu.be/sOrUP0Rq6Jg?t=498).
=> Nightvision - Increase max amount of IR rays to 64

docs/wiki/framework/arsenal-framework.md
- title, event handlers section appeared under stats section
=> Wiki - Fix arsenal framework section headings

addons/switchunits/functions/fnc_addMapFunction.sqf, addons/switchunits/functions/fnc_handleMapClick.sqf, addons/switchunits/functions/fnc_initPlayer.sqf, addons/switchunits/functions/fnc_startSwitchUnits.sqf
- Fix switchUnits functionality
***
Clicking on a switchable unit currently does nothing (see #6188). 
It looks like `BIS_fnc_addStackedEventHandler` was changed at some point so that the arguments array is appended to `onMapSingleClick`'s passed params, resulting in switchUnits failing here:
https://github.com/acemod/ACE3/blob/master/addons/switchunits/functions/fnc_addMapFunction.sqf#L24
Quick fix would have been:
```
params ["_pos", "", "", "", "_unit", "_sides"];
if (alive ACE_player && {GVAR(OriginalUnit) getVariable ["ACE_CanSwitchUnits", false]}) then {
[[_unit,_sides], _pos] call FUNC(handleMapClick);
};
```
This replaces `BIS_fnc_addStackedEventHandler` with [MapSingleClick](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissi …
=> switchUnits - Fix switching units not working (#6188)

addons/arsenal/ACE_Arsenal_Stats.hpp, addons/arsenal/XEH_PREP.hpp, addons/arsenal/functions/fnc_statTextStatement_explosionTime.sqf, addons/arsenal/stringtable.xml
- title, https://github.com/acemod/ACE3/issues/3594#issuecomment-625617544
=> Arsenal - Add grenade fuse time stat

addons/advanced_ballistics/XEH_postInit.sqf, addons/advanced_ballistics/functions/fnc_handleFirePFH.sqf, addons/advanced_ballistics/functions/fnc_handleFired.sqf
- Changes the method of how we "clean" the array
=> Advanced Ballistics - Improve Performance in handleFirePFH

addons/winddeflection/functions/fnc_updateTrajectoryPFH.sqf
- Changes the method of how we "clean" the array
- Same as #7699 just in Winddeflection
=> Wind Deflection - Improve Performance in updateTrajectoryPFH

AUTHORS.txt, addons/medical_treatment/functions/fnc_handleBandageOpening.sqf, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
As it says on the tin, this PR adds a Global Wound Reopen Chance Modifier to the Medical Treatment Addon Settings. This modifier is utilized in `fnc_handleBandageOpening.sqf`, where it modifies the re-open chance. This is applied per bandage/wound, allowing the various bandage's distinctive values to be modified equally.
This has been tested and is working.
I'll pop in to Slack, but please let me know what else needs to be done, etc. Thank you!
=> Medical - Add Global Wound Reopen Chance Modifer

addons/csw/functions/fnc_staticWeaponInit.sqf, addons/reload/CfgEventHandlers.hpp, addons/reload/functions/fnc_displayAmmo.sqf
- title;
- ~~fix no `Check ammo` interaction on statics when CSW ammo handling is disabled;~~
- fix and improve `Take` EH;
- optimize fnc_displayAmmo.
When drag magazine to your weapon in gear in vehicle it will display empty ammo count. To fix it `weaponState` should be used instead of `currentWeapon`, `currentMuzzle` and `currentMagazine`.
=> Reload - Fix display ammo count in vehicle

addons/medical_feedback/XEH_postInit.sqf
- Title
Currently if `ace_hearing_unconsciousnessVolume` > 0.25 it will be ignored in favor of
https://github.com/acemod/ACE3/blob/b30f023c042d4182091218f39db92b98f34e24ba/addons/medical_feedback/script_component.hpp#L40
=> Medical Feedback - Fix overriding hearing setting when unconscious

optionals/compat_rhs_gref3/CfgAmmo.hpp, optionals/compat_rhs_gref3/CfgMagazines.hpp, optionals/compat_rhs_gref3/CfgVehicles.hpp, optionals/compat_rhs_gref3/config.cpp
- Add **RHS:GREF** compatibility with `ACE Explosives`
Linked to issue #7714
_Note:_ None of the classes had stringtable entries, so `displayName` attributes are the hardcoded values from **RHS:GREF** config 😒
=> Compat_rhs_gref3 - Add RHS:GREF explosives compatibility

optionals/compat_rhs_usf3/CfgAmmo.hpp, optionals/compat_rhs_usf3/CfgMagazines.hpp, optionals/compat_rhs_usf3/CfgVehicles.hpp
- Improve **RHS:USAF** compatibility with `ACE Explosives`
Linked to issue #7714
*Note:* Tripwire mines did note have stringtable entries, so hardcoded `displayName` properties from **RHS:USAF** config 😞
=> Compat_rhs_usf3 - Improve RHS:USAF explosives compatibility

addons/ballistics/CfgMagazineWells.hpp, addons/ballistics/CfgMagazines.hpp, addons/ballistics/CfgWeapons.hpp
- Fix the `DMR_03_base_F` `initSpeed`.
- Fix the missing `arifle_katiba_Base_F` 30 rnd IR-Dim magazine (KH2002 Sama variants).
- Fix the `ACE_30Rnd_556x45_Stanag_Tracer_Dim` picture (30 rnd magazine icon instead 20 rnd).
=> Ballistics - Fix DMR_03 (SIG556) initSpeed

addons/quickmount/functions/fnc_addFreeSeatsActions.sqf
- title;
- enable for changing seat turrets with configured `enabledByAnimationSource`.
Something changed in last arma updates and changing seat while car is moving (in multiplayer) leads to unit moving out and injury/death. I replaced `allowDamage` workaround with `enableSimulation` and now it works even better than before. Also it has fixed bug with FFV units in ramped helicopters.
=> Quick Mount - Fix change seat while vehicle is moving

AUTHORS.txt, addons/fastroping/XEH_preInit.sqf, addons/fastroping/functions/fnc_equipFRIES.sqf, addons/fastroping/functions/fnc_unequipFRIES.sqf
- Fix FRIES removal when helicopter is killed or deleted
- `equipFRIES` function could be called on any machine and as a result
- the killed event would not work as expected if the locality of the helicopter changed
- the deleted event would not work as expected if added on a client that later disconnects
=> Fastroping - Fix FRIES removal

addons/rearm/functions/fnc_setTurretMagazineAmmo.sqf
- Ensure all compatible magazine types for a turret are detected regardless of config implementation details
- Prevent magazines being infinitely duplicated loading to server performance issues for specific magazine/turret configs
Some vehicles (issue discovered with the RHS's Bradley Busk III) report no compatible magazines when running CBA_fnc_compatibleMagazines without the allMuzzles parameter. This leads to the magazine type which will be added by the rearm action not getting removed before hand. Due to the code's assumption that all magazines have been removed, this leads to the filled magazines being added on top of the old (still loaded) magazines. Due to the old magazines still not being full the rearm option remains leading players to …
=> Rearm - Fix some magazine types duplicating during rearm

addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
- Ensure flow adjustments are applied in vital loop if they are not equal to 0 (instead of checking if heart rate adjustments are not equal to 0)
=> Medical - Fix typo in vital adjustment conditional

addons/arsenal/stringtable.xml, addons/dragging/stringtable.xml, addons/gforces/stringtable.xml, addons/medical_gui/stringtable.xml
Added missing Russian translations and remove traling `>` symbol from Spanish translation
=> Translations - Update / Fix Russian

addons/common/functions/fnc_disableUserInput.sqf
- title, when the curator's unit went unconscious while in Zeus, would require pressing the Zeus key again to see/interact with editable object icons
- Fix some magic numbers
=> Common - Fix disableUserInput blocking already open Zeus display

addons/tagging/XEH_PREP.hpp, addons/tagging/functions/fnc_addCustomTag.sqf, addons/tagging/functions/fnc_applyCustomTag.sqf, addons/tagging/functions/fnc_compileConfigTags.sqf, addons/tagging/functions/fnc_createTag.sqf, addons/tagging/functions/fnc_parseConfigTag.sqf, addons/tagging/functions/fnc_quickTag.sqf, addons/tagging/functions/fnc_tag.sqf, docs/wiki/framework/tagging-framework.md
Parse tags from description.ext
It will also handle mission/mod paths just like https://community.bistudio.com/wiki/Description.ext#CfgSounds
This is based on #7709 branch (sorry but they would conflict either way)
=> Tagging - Add support for mission Tags

addons/medical_feedback/functions/fnc_playInjuredSound.sqf
I notice `ace_medical_feedback_fnc_playInjuredSound` take an average time of execution around 300µs (~1000 call) even when no player is around the injured AI.
The idea of this PR is to reduce this value by exiting the function earlier.
- Exit the  `ace_medical_feedback_fnc_playInjuredSound` earlier if no player is around
- Get the hearing distance 
- Check if players are around
- Exit if no players
=> Medical - Improve injured sound by exiting the function earlier if no player is around

addons/logistics_uavbattery/CfgVehicles.hpp, addons/refuel/CfgVehicles.hpp
- Allow ED-1D and ED-1E drones to be recharged using a battery, remove ability to refuel
- Close #7175
=> Add support for ED-1D and ED-1E drones

addons/nametags/functions/fnc_drawNameTagIcon.sqf
- Fix names jump on nametags when no ranks shown and talking on ACRE/TFAR
When no ranks are shown nametag jumps up and down when player talks on ACRE/TFAR due to soundwave icon pushing the name down. This can be fixed by not scaling the icon to 0 when no icon shown (no icon still takes space).
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=92429296-c375-11ea-bf88-a15b6c7adf9a
=> Nametags - Fix names jump when no ranks shown and talking

addons/goggles/ACE_Settings.hpp, addons/goggles/XEH_postInit.sqf, addons/goggles/functions/fnc_applyGlassesEffect.sqf, addons/goggles/functions/fnc_canWipeGlasses.sqf, addons/goggles/functions/fnc_handleKilled.sqf, addons/goggles/functions/fnc_removeGlassesEffect.sqf, addons/goggles/stringtable.xml
- As the title says, adds an effects only option for goggles.
Translations are from `STR_ACE_Goggles_enabled_tintAndEffects`, they _should_ be accurate
=> Goggles - Add effects only option

addons/medical_engine/XEH_preInit.sqf, addons/medical_engine/functions/fnc_applyAnimAfterRagdoll.sqf
If unit was killed while unconc it will keep `QGVAR(waitForAnim), true])` setVars
=> Medical Engine - Prevent issues with respawning and ragdoll animations

addons/main/CfgSettings.hpp, optionals/compat_rhs_saf3/$PBOPREFIX$, optionals/compat_rhs_saf3/CfgAmmo.hpp, optionals/compat_rhs_saf3/CfgMagazines.hpp, optionals/compat_rhs_saf3/CfgVehicles.hpp, optionals/compat_rhs_saf3/CfgWeapons.hpp, optionals/compat_rhs_saf3/config.cpp, optionals/compat_rhs_saf3/script_component.hpp
- Add optional RHS:SAF compat
Addresses issue #7785
=> RHS Compat - Add RHS:SAF compat

optionals/compat_rhs_gref3/CfgAmmo.hpp, optionals/compat_rhs_gref3/CfgWeapons.hpp
- Update M21 rifles
- Remove G36 rifles _(moved to SAF compat)_
- Remove M84 MG _(moved to SAF compat)_
- General cosmetics
Related to issue https://github.com/acemod/ACE3/issues/7785 and PR https://github.com/acemod/ACE3/pull/7793
Merge after https://github.com/acemod/ACE3/pull/7784 to avoid potential conflicts ....
=> RHS Compat - Fix RHS:GREF M21/G36 weapons

addons/missileguidance/functions/fnc_SACLOS_onFired.sqf, addons/missileguidance/functions/fnc_seekerType_SACLOS.sqf
fix #7811 
doesn't automatically apply to vehicles that want to use the camera since that would require information that we can't infer. All vanilla helicopters use other means for turrets so I am still assuming that to be the default.
=> MissileGuidance - Add config option for using pilot camera as primary SACLOS control method

addons/hearing/CfgWeapons.hpp
- Adds 75% (peltor) hearing protection to the Advanced Modular Helmets (except the base "(Olive)" helmet which doesn't have a headset).
- And adds the same to the Avenger Helmet (the covered helmets inherit).
=> Hearing - Add hearing protection to LDF and Spetsnaz helmets

addons/map_gestures/CfgEventHandlers.hpp, addons/map_gestures/functions/fnc_drawMapGestures.sqf, addons/map_gestures/functions/fnc_getProximityPlayers.sqf, addons/map_gestures/functions/fnc_initDisplayCurator.sqf, addons/map_gestures/functions/fnc_initDisplayDiary.sqf, addons/map_gestures/functions/fnc_initDisplaySpectator.sqf, addons/map_gestures/initSettings.sqf, addons/map_gestures/script_component.hpp, addons/map_gestures/stringtable.xml
- Add Variable Range for Camera Users (Zeus, Spectator) + Settings  
- Add Setting to Disable Zeus and/or Spectator Map Draws  
- Add Ability to use Map Gestures on Briefing screen  
- Add Setting for Briefing Screen mode (All, Only Group, Only Side, Proximity, Disabled)
- Improve Responsiveness of Transmission. Transmission of the position is now started as soon as clicked
Todo:
=> Map Gestures - Add Briefingscreen support, Different Camera Range, Improve Responsiveness, and Toggles for Curators and Spectators Maps

optionals/compat_rhs_usf3/CfgWeapons.hpp
- Fix inheritance for `rhs_weap_sr25_ec_d` and `rhs_weap_sr25_ec_wd`
- Close https://github.com/acemod/ACE3/issues/7869
=> RHS Compats - Fix RHS:USAF Mk11 Mod 0 EC barrel lenghts

addons/arsenal/functions/fnc_sortStatement_rateOfFire.sqf
- The 0 fire rate value of the Flashlight caused a divide by 0 error
=> Arsenal - Fix fire rate sort caused by flashlight

addons/medical_treatment/CfgVehicles.hpp
**Adds splints + torniquets to simple crate**
- Since the basic/advanced split was removed with the rewrite you now (likely) have use for both of these items in the "simple" version of the crate too
=> Medical Treatment: Adding splints + torniquets to simple crate

addons/quickmount/functions/fnc_canShowFreeSeats.sqf, addons/quickmount/functions/fnc_getInNearest.sqf
**Stops players getting to vehicles with simulation disabled**
- You can currently mount in a vehicle witih sim disabled and you get "stuck" inside. Vanilla addActions allow this too (I've asked Ded to see if he can fix). For now this at leasts stops people accidentally getting in to something they shouldn't with a bad key press.
- Reusing the locked message as the player doesn't need to know the difference between locked/sim disabled, they just need to know they can't get in.
- Possibly warrants an RPT line so if you get people complaining they cannot get in a vehicle, RPT shows why (#blamethemissionmaker) - Thoughts?
=> Quick Mount: Check vehicle simulation

addons/arsenal/ACE_Arsenal_Sorts.hpp
- Remove `Sort by accuracy` and `Sort by rate of fire` from launcher tab as they didn't provide anything useful
=> Arsenal - Remove launcher sorts

addons/fastroping/CfgVehicles.hpp
=> Fastroping - Fix invalid usage of ARR macro

extensions/common/pbo/search.cpp
- GetLibraryProcAddress is called with const char* arguments, but PSTR is char*, casting const char* to char* won't be allowed anymore in C++20
=> Fixed casting const char* to char* in extension

addons/grenades/CfgAmmo.hpp
- Fixes issues when building @Dahlgren 's nightly by removing references to missing audio files
- Tested in-game, still has audio and no RPT errors
```
z\ace\addons\grenades\CfgAmmo.hpp circa Line 181: A3\Sounds_F\arsenal\explosives\bombs\Explosion_satchel_01
z\ace\addons\grenades\CfgAmmo.hpp circa Line 182: A3\Sounds_F\arsenal\explosives\bombs\Explosion_satchel_02
z\ace\addons\grenades\CfgAmmo.hpp circa Line 210: A3\Sounds_F\arsenal\explosives\bombs\Explosive_Charge
```
=> Grenades - Remove ref to missing audio

docs/wiki/framework/arsenal-framework.md
Because when I copied it, it definitely was an oopsie moment.
- Fix this wiki entry: https://ace3mod.com/wiki/framework/arsenal-framework.html#51-adding-stats-via-config
=> Documentation - Fix typos and missing semi-colon in Arsenal

addons/refuel/CfgVehicles.hpp
- Fix #7861
Handling of destroyed vehicles was fine, however interacting with the nozzle was not possible because it was destroyed with the vehicle (although it visually seemed to be fine).
The rope might still break and cannot be made invincible, but that's more of a visual problem than a gameplay problem.
=> Refuel - Fix refuel nozzle getting stuck in destroyed vehicles

addons/ballistics/CfgAmmo.hpp, addons/scopes/CfgWeapons.hpp
- update all weapons `ACE_IronSightBaseAngle` according with the last Ama3 v2.00 (both ballistics checked).
- remove the unused `B_56x15_dual` changed by the `B_556x45_dual` (underwater bullets).
> Tweaked: SPAR rifle series iron sights - FT-T149711
> Fixed: Zeroed ironsights on MX, Katiba, TRG, Mk20, Zafir, M320, GM6, Mk18, Rahim, Protector, Sting, Vermin, Zafir and Mk200
_- The `arifle_SDAR_F` `ACE_IronSightBaseAngle` value is a compromise between the default `discreteDistance` 30 m (`20Rnd_556x45_UW_mag`) and the `discreteDistance` 100 m (`30Rnd_556x45_Stanag`)._
_- The green dot of the `SMG_03` variants (ADR-97 or P90) is not centered correctly : POI approximately 0.7 mRad up and right of the POA._
_- **Test conditions** : no saw, …
=> Scopes - Weapons IronSightBaseAngle updated

addons/medical_gui/CfgVehicles.hpp, addons/medical_gui/XEH_PREP.hpp, addons/medical_gui/functions/fnc_modifyActionTriageLevel.sqf, addons/medical_gui/functions/fnc_modifyManMainAction.sqf, addons/medical_gui/initSettings.sqf, addons/medical_gui/stringtable.xml
- Show the triage level color as the `ACE_MainActions` and `Medical Menu` color
<details>
<summary>Images</summary>
</details>
=> Medical - Show triage level in interaction

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
Adds treatment time addon settings for Tourniquets, IV Bags, Syringes, Splints, and Body Bags.
Each value has been defaulted to the current default time for each type, and has been set in a range [0.1,  (currentDefault * 4)].
I have tested all 5 of these new settings without issue.
Thank you.
=> Medical - Add Treatment Time Addon Settings

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp, addons/medical_treatment/XEH_PREP.hpp, addons/medical_treatment/functions/fnc_canPlaceInBodyBag.sqf, addons/medical_treatment/functions/fnc_placeInBodyBag.sqf, addons/medical_treatment/initSettings.sqf, addons/medical_treatment/stringtable.xml
- Adds a setting allowing the placing of unconscious units in a body bag
Makes it a little harder for medics to rapidly determine if someone is dead or unconscious
=> Medical - Allow placing unconscious in a body bag

addons/interaction/functions/fnc_getDoorAnimations.sqf
- Fix #7707
The door in that issue is door_1, but the animation search previously returned all animations for door_1 and door_10 to door_15.
This fix assumes that other buildings also put an underscore after the door name, so if someone could verify this for CUP that would be great.
=> Interaction - Fix door opening for buildings with 10+ doors

addons/arsenal/ACE_Arsenal_Sorts.hpp, addons/arsenal/XEH_PREP.hpp, addons/arsenal/functions/fnc_addSort.sqf, addons/arsenal/functions/fnc_compileSorts.sqf, addons/arsenal/functions/fnc_fillSort.sqf, addons/arsenal/functions/fnc_sortPanel.sqf, addons/arsenal/functions/fnc_sortStatement_amount.sqf
- Add a conditional field to the arsenal sorts
- Add `Sort by Amount` (Closes #7888)
=> Arsenal - Conditional on sorts

addons/repair/CfgVehicles.hpp
- Fix #6142
The hitpoint is only used for visual effects but causes the tire to receive fall damage. Setting `minimalDamage` to 1 basically disables it taking damage on its own and thus disables fall damage completely. Other damage still works fine.
=> Repair - Fix spare wheels receiving fall damage

addons/dagr/Dialog.hpp, addons/dagr/functions/fnc_menuInit.sqf, addons/disarming/functions/fnc_disarmDropItems.sqf, addons/interact_menu/functions/fnc_keyUp.sqf, addons/interact_menu/functions/fnc_render.sqf, addons/interact_menu/functions/fnc_userActions_getHouseActions.sqf, addons/repair/functions/fnc_normalizeHitPoints.sqf
- Fix #7583
Found using the following regex: `^ *[a-z][\w\d_]+ = `
=> DAGR / Interaction Menu / Repair - Fix overwriting globals

addons/ballistics/CfgAmmo.hpp, addons/scopes/CfgWeapons.hpp
- Fix https://github.com/acemod/ACE3/issues/7832
Without real datas about underwater ammo, the airFriction is basically calculated with the Ruthberg values: the `20Rnd_556x45_UW_mag` `initSpeed` and a subsonic 5.56 from the [CfgAmmoReference](https://github.com/acemod/ACE3/blob/master/extras/CfgAmmoReference.hpp#L2760):
> ##########################################
Ammo Class: B_556x45_dual
_drag model 7_
_ballistic coefficient 0.151_
MaxRanges (m): [250, 250]
MuzzleVelocities (m/s): [262, 272]
Max. Velocity diff (m/s): 0.19
Max. Drop diff (cm): 0.44
Max. Tof diff (ms): 0.5
Optimal airFriction: 0.00054976
The goal is something coherent between the both ballistics: [in-game Range cards](https://steamuserimages-a.akamaihd.net/ugc/1680366675632031238/667 …
=> Ballistics - Update the B 556x45 dual
