- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_handleDamage_advanced.sqf
- addons/medical/functions/fnc_handleDamage_advancedSetDamage.sqf
- addons/medical/functions/fnc_handleDamage_basic.sqf
- addons/medical/functions/fnc_handleDamage_caching.sqf
- addons/medical/functions/fnc_handleDamage_wounds.sqf
Reduced performance issues when a lot of units (15+) are taking damage within a few frames from each other.
Should reduce/eliminate the game freeze with basic medical and improve advanced medical performance by ~30% on average.
> Medical performance improvements

- tools/build.py
#576 - Obsolete PBO removal support added to build.py
If a PBO is found but there is no module directory associated it will then be removed. 
Support for empty module folders may be added later. 
Removed statistics are reported
> Added Obsolete PBO removal support added to build.py

- extensions/CMakeLists.txt
Cmake is case-sensitive for the directory name.
> match to exact directory name (case-sensitive)

- addons/missileguidance/stringtable.xml
added german translation to missile guidance stringtable xml
`Erweitertes Raketenlenksystem` sounds better/more formal for me then `Erweiterte Raketenlenkung`, which could also be a possible translation
> added german translation to missile guidance stringtable xml

- README.md
Every time i want to report bug, i need to search around looking for link to issue template. IMHO, this should be in README.
> Add link for issue report details

- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_addToInjuredCollection.sqf
- addons/medical/functions/fnc_handleUnitVitals.sqf
- addons/medical/functions/fnc_setCardiacArrest.sqf
There's an issue with locality and some var's not behing propaged.
This is more of a bandaid than a full fix.  It just changes getVariables to use a default number instead of 0 for stuff like hear rate.
> Medical - Use default value instead of 0 for getVar

- addons/common/functions/fnc_setSettingFromConfig.sqf
- addons/inventory/config.cpp
- addons/optionsmenu/config.cpp
- addons/optionsmenu/functions/fnc_exportSettings.sqf
- addons/optionsmenu/functions/fnc_onServerSaveInputField.sqf
- addons/optionsmenu/functions/fnc_onServerSettingsMenuOpen.sqf
- addons/optionsmenu/functions/fnc_onSettingsMenuOpen.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateList.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateList.sqf
- addons/optionsmenu/gui/settingsMenu.hpp
- addons/optionsmenu/stringtable.xml
The game doesn't seem to localize text in arrays from a config.
e.g.: values[] = {"$str_medium", "$str_large", "$str_very_large"}; won't be translated.
I remember this breaking AGM repair somehow, anyways I just added something to detect and localize them in setSettingFromConfig when we load from config.
Lets you scale the options menu (allowing more rows), just like inventory stuff.
I seemed to be hitting a max string/clipboard limit when exporting server config with user settings via clipboard (I get 423 lines and it ends mid class).  Adds a backup method to dump to rpt.
> Option menu stuff

- addons/interact_menu/functions/fnc_collectActiveActionTree.sqf
- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_createAction.sqf
An optional code entry called  `modifierFunction` can be added to action. That is code, that gets called before evaluating the action, allowing to dynamically change the actions name, icon, etc.
Brings even greater flexibility to the action menu
> Allow to dynamically modify actions at runtime. 

- addons/vehicles/CfgEventHandlers.hpp
Ensures every static weapon to have a mass of at least 250
> fix falling over static weapons

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_loadSettingsFromProfile.sqf
- addons/common/functions/fnc_loadSettingsLocalizedText.sqf
- addons/common/functions/fnc_setSettingFromConfig.sqf
Fixes #744
* Overrides displayName and description on postInit for each client
* Does not do localization of the values on server anymore.
This was the easiest solution I could come up with atm, without having to remove the `$` infront of every settings displayName or description.
> Fix settings localization is done by the server instead of client

- addons/grenades/CfgMagazines.hpp
m84 weighs ~260g compared to a m18 with ~520g. Ingame the m18 has a mass
of 4 but giving the m84 a mass of 2 seems odd to me. That's why I've reduced it from 10 to 4.
And added author as a bonus.
> reduce m84 mass

- addons/interact_menu/XEH_clientInit.sqf
- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/config.cpp
- addons/interact_menu/functions/fnc_renderIcon.sqf
- addons/interact_menu/functions/fnc_renderMenu.sqf
- addons/interact_menu/functions/fnc_setupTextColors.sqf
- addons/interact_menu/stringtable.xml
#682
Adds 4 options to change the text and shadow colors:
Just changing the default min alpha from 0.25 to 0.5 seems about perfect for me, but this should allow people to do whatever they want if they have trouble seeing.
> User changeable text/shadow colors for interaction

- addons/ballistics/CfgAmmo.hpp
Added realistic tracer burn times for several ammo types: 
B_556x45_Ball (parent for several tracer rounds)
ACE_545x39_Ball_7T3M
B_762x51_Ball (parent for several tracer rounds)
ACE_762x54_Ball_7T2
ACE_762x39_Ball_57N231P
Also changed color of russian tracer rounds from yellow to green, which is what they are in the real world.
> Added realistic tracer burn times for several ammo types

- tools/make.cfg
- tools/make.py
Make python build script now creates signature keys by default. 
Public Key folder now resides inside the @ace release folder.
Private Keys are now created at the P:\private_keys by default. This is configurable.
Switch to all lower case folder names. 
Added a notification for the Check External References setting.
Reference: http://gyazo.com/042a5ad655921b87618c05e7addd1b09
> Make Signature Key Building + enhancements

- optionals/compat_hlcmods_core/CfgAmmo.hpp
Fixing missing inheritance: class HLC_762x54_tracer: HLC_762x51_tracer
Now it will build.
> Fixing missing inheritance: class HLC_762x54_tracer: HLC_762x51_tracer

- addons/ballistics/stringtable.xml
Unified some translations in "ballistics" e.g. unit spacing, Schuss=>Patronen, decimal seperator. I checked it three times but please review it!
> German translations fixes

- addons/vehiclelock/CfgEventHandlers.hpp
- addons/vehiclelock/CfgVehicles.hpp
- addons/vehiclelock/XEH_preInit.sqf
- addons/vehiclelock/config.cpp
- addons/vehiclelock/functions/fnc_handleVehicleInitPost.sqf
- addons/vehiclelock/functions/fnc_moduleInit.sqf
- addons/vehiclelock/functions/fnc_onOpenInventory.sqf
Fix for #428
Changes setting default lock from once at start to a per-vehicle postInitEH so it works on spawned vehicles.
Also allows locking/unlocking from inside vehicle.
> Veh lock fix

- optionals/compat_asdg/config.cpp
According to https://github.com/acemod/ACE3/blob/master/addons/optics/CfgWeapons.hpp#L196 there is MRCO PiP version (i can't see it in arsenal anyway, but that's different issue #918), but it's missing from ASDG_JR compatibility module.
> [compat_asdg] fix MRCO PiP compatibility

- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_createAction.sqf
- addons/interact_menu/functions/fnc_renderBaseMenu.sqf
- addons/interaction/CfgVehicles.hpp
- addons/interaction/XEH_preInit.sqf
- addons/interaction/functions/fnc_getWeaponPos.sqf
- addons/respawn/CfgVehicles.hpp
- Allow positions for actions to be computed dynamically. 
- Leverage that for the position of the "Weapon" action, instead of hard coding an exception for that.
- Tweak the position for rally point actions. Fix #837
> Dynamic action positions

- addons/laserpointer/CfgWeapons.hpp
- addons/laserpointer/functions/fnc_onDraw.sqf
- documentation/development/ace3-config-entries.md
- Caches the value to not overload the game with config access.
- adds new CfgWeapons configuration value: `ace_laserpointer` value: 1 = red laser, 2 = green laser.
> Allow 3rd party to add laser pointers

- addons/javelin/functions/fnc_onFired.sqf
- addons/javelin/functions/fnc_onOpticDraw.sqf
`x3 = configProperties [configFile >> "CfgWeapons" >> (currentWeapon (vehicle ACE_player)) >> "ace_javelin_enabled", "true", false];`
is always `[]`for me
`x3 = configProperties [configFile >> "CfgWeapons" >> (currentWeapon (vehicle ACE_player)), "configName _x == 'ace_javelin_enabled'", false];`
seems to work
> Javelin - Fix configProperties

- addons/nametags/stringtable.xml
- addons/nightvision/stringtable.xml
- addons/overheating/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/respawn/stringtable.xml
- addons/switchunits/stringtable.xml
Fixed the last few (hopefully) spelling mistakes and capitalization inconsistencies in the:
-nightvision
-realisticnames
-switchunits
Improved phrasing in the:
-respawn
-overheating
to increase clarity.
Replaced couple of abbreviations in the:
-nametags
for consistency with the translations in the same section (should either keep all of them abbreviated or none, IMO).
> Translation fixes/improvements (RU)

- addons/interact_menu/functions/fnc_renderBaseMenu.sqf
Should avoid LOS checks for medical bodyparts entirely, thus avoiding problems with weaponholders obstructing actions.
> Interact menu: Increase the minimum distance required for LOS checks to 1.5m

- addons/map/config.cpp
fix #940
on brefing screen, current contour interval legend is blocked by cancel button, and blocks chat
Moving it to the right, it's still semi-blocked by button, but the important parts are all readable (tried 2 different aspect ratios)
> #940 - Map Tweak (contor legend) for brefing

- addons/missileguidance/functions/fnc_onFired.sqf
RHS javelin broken right now,
Same as other fix for the ace javelin
```
x3 = configProperties [configFile >> "CfgAmmo" >> "rhs_ammo_M_fgm148_AT" >> "ace_missileguidance", "true", false];
count x3 = 15
```
> MissleGuidance - fix Inheritance check

- tools/make.cfg
- tools/make.py
Proper clean up if user cancels the build or if an error occurs. 
Ability to set the testing folder in make.cfg for use with the command-line parameter called 'test'
> Make.py and Make.cfg ehancements

- addons/advanced_ballistics/functions/fnc_calculateStabilityFactor.sqf
- addons/advanced_ballistics/functions/fnc_handleFired.sqf
- addons/ballistics/CfgAmmo.hpp
- addons/ballistics/CfgWeapons.hpp
- addons/overheating/functions/fnc_overheat.sqf
- extras/CfgAmmoReference.hpp
- extras/CfgWeaponsReference.hpp
- optionals/compat_cup/CfgAmmo.hpp
- optionals/compat_hlc_ar15/CfgWeapons.hpp
- optionals/compat_hlc_wp_mp5/CfgWeapons.hpp
- optionals/compat_hlcmods_ak/CfgWeapons.hpp
- optionals/compat_hlcmods_aug/CfgWeapons.hpp
- optionals/compat_hlcmods_core/CfgAmmo.hpp
- optionals/compat_hlcmods_fal/CfgWeapons.hpp
- optionals/compat_hlcmods_g3/CfgWeapons.hpp
- optionals/compat_hlcmods_m14/CfgWeapons.hpp
- optionals/compat_hlcmods_m60e4/CfgWeapons.hpp
- optionals/compat_rh_de/CfgAmmo.hpp
- optionals/compat_rh_de/CfgWeapons.hpp
- optionals/compat_rh_m4/CfgAmmo.hpp
- optionals/compat_rh_m4/CfgWeapons.hpp
- optionals/compat_rh_pdw/CfgAmmo.hpp
- optionals/compat_rh_pdw/CfgWeapons.hpp
- optionals/compat_rhs_afrf3/CfgAmmo.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgAmmo.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
Convert config values and the relevant lookups in advanced_ballistics.
Everything is either ~~meters~~ millimeters or grams.
The barrel length stuff is purely relative, so no multiplication there.
@ulteq should probably check if he can mash those multiplications in somewhere.
> Metric units

- addons/scopes/CfgEventHandlers.hpp
- addons/scopes/functions/fnc_firedEH.sqf
firedBIS (last one to switch)
also skips call to `EFUNC(common,changeProjectileDirection)` if there are no adjustment (will be true for most bullets, grenades,)
> Switch scopes to use firedBIS

- addons/missionmodules/functions/fnc_moduleAmbianceSound.sqf
used `string_removeWhiteSpace` but had to be `stringRemoveWhiteSpace`
due to 612fa69c1c4cf7ed8b81c5086dc90877d0eda400
> fix removeWhiteSpace function name in ambiance sound module

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_checkFiles.sqf
- addons/common/functions/fnc_checkPBOs.sqf
- addons/common/functions/fnc_errorMessage.sqf
- addons/common/functions/fnc_moduleCheckPBOs.sqf
- addons/common/scripts/Version/checkVersionNumber.sqf
- addons/laser_selfdesignate/config.cpp
- logs full version of ace once
- checks if .dlls are present
- checks if all ace.pbos are up to date
- in MP checks if server and client version match up
- otherwise -> RPT log, message box that ends mission
- this is independant from the checkPBO module, which is now for third party addons only.
________________
this checks all pbos taged as ace on mission start. Popup + RPT error when a file with another version number is detected.
This is meant for all those who simply overwrite their folders and then end up with invalid, outdated and/or conflicting stuff.
> check for outdated pbo files

- documentation/development/coding-guidelines.md
Not showing correctly on the website, but is good directly in the tree, this should fix it by adding a newline between the text around and the list.
> Possibly fixed FUNC Macros list in Coding Guidelines

- addons/medical/functions/fnc_isInMedicalVehicle.sqf
- addons/medical/functions/fnc_isMedicalVehicle.sqf
- addons/medical/functions/fnc_moduleAssignMedicalVehicle.sqf
The rest of the medical vehicle functions are using variable `ace_medical_isMedic` rather than `ace_medical_medicClass` so I changed this one to match.
Probably just an oversight in copy-pasting as the function is very similar to the `moduleAssignMedicRoles` function.
> Trivial variable name fix for moduleAssignMedicalVehicle function

- addons/disarming/functions/fnc_disarmDropItems.sqf
- addons/disarming/functions/fnc_getAllGearUnit.sqf
- addons/disarming/functions/fnc_showItemsInListbox.sqf
- addons/disarming/script_component.hpp
- addons/vehiclelock/CfgMagazines.hpp
Fix #1081
Binocular types items show up as both an `item`/ `assignedItem` and `weapons`.  It was trying to drop them the wrong way.
Also adds `ACE_isUnique` flag for magazines (so they get dropped via action and preserve `magazinesDetail`) which we'll need for BFT or other mods using `magazinesDetail`.
> Fix disarming

- addons/captives/functions/fnc_canSurrender.sqf
Fix being locked in a surrender state if `currentWeapon player` changes.
> Fix not being able to UnSurrender (currentWeapon)

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_timePFH.sqf
- addons/main/script_macros.hpp
There was discussion recently about the fact we use 'time' everywhere in our PFH's so they detect game pausing and support saved games.
However, time is unreliable on slow machines (< 20fps) - so we *should* be using diag_tickTime for PFH functionality.
This provides the following global variables for a hybrid approach of this:
ACE_time = diag_tickTime accuracy, except it does not advance when the game is paused. It will also obviously save and continue forward in a saved game, so supports them as well.
ACE_realTime = diag_tickTime
ACE_gameTime = time
ACE_virtualTime = diag_tickTime accuracy, except taking accTime into account.
ACE_virtualGameTime = time, except takes accTime into account.
ACE_virtualPausedTime = the amount of diag_tickTime time that was paused, except accTime is taken …
> ACE_time variables for accurate purposeful time use

- addons/safemode/stringtable.xml
Safety message was wrong: it was indicating the action, not the status.
> Fixed: Safe mode Italian translation

- documentation/feature/ai.md
- documentation/feature/ballistics.md
- documentation/feature/movement.md
- documentation/feature/nametags.md
- documentation/feature/nightvision.md
Remove outdated instances of "AGM" in documenation. Thanks to @alganthe for catching this :smile:
> Remove outdated references to AGM in documentation

- addons/reload/XEH_postInit.sqf
Fix #1119 (setAmmo isn't synced immediately)
Belt relinking is rare enough that doing an extra global event shouldn't be that bad.
> Manually sync ammo globably on belt reload.

- addons/interact_menu/CursorMenus.hpp
- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/functions/fnc_keyDown.sqf
- addons/interact_menu/functions/fnc_keyUp.sqf
- addons/interact_menu/functions/fnc_renderIcon.sqf
- addons/interact_menu/functions/fnc_renderSelector.sqf
Replaces dialogs by displays, allowing the player to move while using the mouse. Credit to @zx64 for the key idea behind this.
Seems to work pretty well, except that using the default bindings you cannot move while self interacting (e.g. Ctrl+L Win+W makes you change stances instead of walking forward). That can of course be fixed by users by changing the keybinds.
Close #311
> Interact_menu with cursor: Replace dialogs by displays

- addons/medical/functions/fnc_createLitter.sqf
- addons/medical/functions/fnc_handleCreateLitter.sqf
Fixed: Litter spawning at huge radius because createVehicleLocal was moving it on initial spawn. Added a single move on spawn, plus another on the next frame to cover collision issues.
Fixed: Litter spawned over water on carriers or other wierd places caused floating magical litter.
Fixes #1112
> Litter distribution fix and "floating litter over water" fix (medical)

- addons/medical/stringtable.xml
They need to be here otherwise few options are blank inside medical modules.
> Missing strings

- addons/medical/functions/fnc_addToInjuredCollection.sqf
- addons/medical/functions/fnc_handleUnitVitals.sqf
- addons/medical/functions/fnc_treatment_success.sqf
Fixes two related problems with medical:
In handleUnitVitals, _interval is calculated by:
`_interval = time - (_unit getVariable [QGVAR(lastMomentVitalsHandled), 0]);`
so on first run it could be >100000; so all the effects multiplied by interval time will be wrong.  If a player has injected a morphine, the first time handleUnitVitals is run it will stop their heart:
example (inject morphine, wait a minute, shoot in foot):
```
_interval 78.128
(([_unit] call FUNC(getHeartRateChange)) * _interval) = -61.9465
_interval 1.009
(([_unit] call FUNC(getHeartRateChange)) * _interval) = 0
_interval 1.084
(([_unit] call FUNC(getHeartRateChange)) * _interval) = 0
```
Both medical levels are effected by this, but it's a bigger problem on advanced.
The other, minor problem is that handleUnitVital only …
> Medical Vitals Fixes

- AUTHORS.txt
- addons/explosives/CfgAmmo.hpp
- addons/explosives/CfgMagazines.hpp
#1191 
Thanks to @legman for his config!
> IED pressure plates

- extensions/advanced_ballistics/AdvancedBallistics.cpp
- extensions/break_line/ace_break_line.cpp
- extensions/clipboard/ace_clipboard.cpp
- extensions/common/p3d/animation.cpp
- extensions/common/p3d/compressed.cpp
- extensions/common/p3d/compressed.hpp
- extensions/common/pbo/archive.cpp
- extensions/common/pbo/search.cpp
- extensions/common/pbo/search.hpp
- extensions/common/shared.hpp
- extensions/common/simplepipe_win32.cpp
- extensions/common/simplepipe_win32.hpp
- extensions/common/simulation/object.cpp
- extensions/common/simulation/object.hpp
- extensions/common/vector.hpp
- extensions/fcs/ace_fcs.cpp
Since the tool chain was already set up for cross-platform builds, and most code was already done for it, I finished it.
This adds the few extra platform-dependent macros and some GCC syntaxian changes for cross platform builds. These extensions will all now run on linux. 
This closes #1266 and refs #1256
> Finalize port of all extensions for cross-platform builds

- addons/nametags/XEH_postInit.sqf
Vanilla A3 does NOT propegate the assignedTeams between clients; so if a group leader assigns teams, they do not get reflected on all clients and the colors are not uniform; they are local. 
This monitors the assigned teams on the leader and sets them on the player objects, giving the entire squad uniform colors for fireteams. This also persists across respawns, and only changes the color for the nametag when the unit itself changes. 
This means everyone can be identified by their nametag color assigned by the group leader.
> Add assignedTeam color propagation to nametags from the leader

- addons/viewdistance/ACE_Settings.hpp
- addons/viewdistance/functions/fnc_changeViewDistance.sqf
- addons/viewdistance/functions/fnc_returnValue.sqf
Apparently it's not safe to set a large view distance by default, as this overrides Arma video settings instead of using the lowest of both. Now view distance is defaulted to video settings, which renders the pbo inert by default. However, users can still leverage the settings to customize the view distance by vehicle type
To improve granularity, I added additional settings for view distances of 500m and 1000m
> Fix for the viewDistance module

- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
Bandaid for #1281, until we properly solve unreliable init handlers.
1- Menus for CAManBase are precomputed on preInit
2- Class action menus for all men are supposed to be equal to those of CAManBase
Note: we loose the capability of defining actions for specific classes from config (which we don't do on ACE annyway)
> Bandaid to prevent interact menu init from being interrupted

- addons/kestrel4500/functions/fnc_collectData.sqf
- addons/kestrel4500/functions/fnc_generateOutputData.sqf
Fixes: http://forums.bistudio.com/showthread.php?191716-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2939409&viewfull=1#post2939409
> Tailwinds are displayed as negative values.

- addons/medical/functions/fnc_treatment.sqf
To reproduce: Equip Binoculars, Treat self:
```
21:53:32 Error in expression <ller);
};
_wpn = ["non", "rfl", "pst"] select (["", primaryWeapon _caller, hand>
21:53:32   Error position: <select (["", primaryWeapon _caller, hand>
21:53:32   Error Zero divisor
21:53:32 File z\ace\addons\medical\functions\fnc_treatment.sqf, line 145
```
Animation seems to look ok as far as I can tell.
> Fix Script Error when treating with bincos

- addons/explosives/XEH_postInit.sqf
#1157
Any explosive that isn't placed with our system won't have the defuse object attached that has all the actions.  There is no events for CfgAmmo so this constantly watches `allMines` and check that they all have defuse objects attached.
Tested with editor placed explosives, zeus placed and artillery spawned cluster mines.
> Defuse object for all explosives

- documentation/user/installation-guide.md
Rename Arma3Sync to ArmA3Sync to represent the accurate name of the
software. 
No other errors found during a proofread by @jonpas so hopefully it's the last for today.
> Docs: installation - fix typo

- addons/medical/XEH_postInit.sqf
RPT Spamed with:
```
13:24:18 Error in expression < 0) getvariable ["ace_medical_pain", 0] - ((_this select 0) getvariable ["ace_me>
13:24:18   Error position: <- ((_this select 0) getvariable ["ace_me>
13:24:18   Error Generic error in expression
13:24:18 File z\ace\addons\medical\XEH_postInit.sqf, line 255
```
> Medical - Fix Unconscious Condition

- addons/advanced_ballistics/stringtable.xml
```
Unexpected stringtable format inside <Text ID="STR_ACE_AdvancedBallistics_simulateForEveryone_Description"><Key>
```
> Fixed missing close tag in Advanced Ballistics stringtable

- tools/make.py
I felt like I should dive into Python a bit and did that, could prove useful if used for other projects.
- All absolute names have been changed to read from variables, for that `project = "@ace"` has also been copied to non-cfg definitions
- `importantFiles` moved to beginning for easier editing, I can't seem to figure out how to read a list from cfg...
- Also changed "ACE VERSION" to read "ACE" part from `pbo_prefix_name` minues underscore and capitalize, goes for different project names
- Changed prefix elimination in check modules to count prefix length and use that rather than hard-coded 4 chars
This is nothing big, obviously project name would have to be changed at the beginning still in some cases as far as I am aware.
> Changed absolute make.py paths to read from variables

- addons/javelin/CfgMagazines.hpp
- addons/javelin/config.cpp
- addons/javelin/functions/fnc_onOpticDraw.sqf
- addons/missileguidance/CfgAmmo.hpp
Adds custom CfgAmmo's for the Titan and Static-Ttitan.
This should fix A3 vehicles and mods that use `M_Titan_AT` (fix #1175)
Also fixes Static Titans which are broken right now as they use `M_Titan_AT_static` which doesn't have missile guidance enabled.
Also checks the loaded magazine on the javelin code (tab locking and the trigger hold).
This will allow firing of the "AP" (wire-guided) ammo without lock.
I know this isn't what we want in the long run, but for now this should make all these weapon systems usable.
> Titan inheritance fix

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_waitAndExecute.sqf
This is an alternative to glob's #360 (issue  #301).
Uses the native `sort` command, so it should be simple and fast.
Might get some performance gains out of this (at least on servers):
At start we do a waitAndExecute on each local unit.
With about ~200 local units at start:
`count cba_common_perFrameHandlerArray` = 237 (~23 that aren't nil)
CBA runs something like:
```
{
_handlerData = _x;
if (!isNil "_handlerData") then {
doStuff = true;
};
} forEach cba_common_perFrameHandlerArray
```
With a huge array that is eating 0.7 ms each frame for the entire game.
> Single PFEH for waitAndExecute - using sort

- addons/advanced_ballistics/stringtable.xml
- addons/ballistics/stringtable.xml
- addons/captives/stringtable.xml
- addons/common/stringtable.xml
- addons/explosives/stringtable.xml
- addons/frag/stringtable.xml
- addons/hearing/stringtable.xml
- addons/interaction/stringtable.xml
- addons/map/stringtable.xml
- addons/medical/stringtable.xml
- addons/microdagr/stringtable.xml
- addons/missileguidance/stringtable.xml
- addons/missionmodules/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/nametags/stringtable.xml
- addons/optionsmenu/stringtable.xml
- addons/respawn/stringtable.xml
- addons/switchunits/stringtable.xml
- addons/vehiclelock/stringtable.xml
- addons/weather/stringtable.xml
- addons/winddeflection/stringtable.xml
added spansih translate for (advanced_ballistics, ballistics, captives,
common, explosives, frag, hearing, interaction, map, medical, microdagr,
missileguidance, missionmodules, mk6mortar, nametags, optionsmenu,
respawn, switchunits, vehiclelock, weather, winddeflection).
I used the Pull request of #1251 for complete my commit, because #1251
is outdated now.
> added spanish translate

- addons/goggles/XEH_postInit.sqf
- addons/goggles/functions/fnc_dustHandler.sqf
Minor performance gain on google effects when player is shooting prone (code is called for every shot):
Test code: `[player, "arifle_MX_pointer_F"] call  ace_goggles_fnc_dustHandler`
Before:
standing: 0.0172974 ms
prone: 0.193288 ms
After:
standing: 0.0166992 ms
prone: 0.0830994 ms
> Goggles - Cache Surface Dust

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
Problem with #1214 
this should also solve issue #1273
Clients don't localize and they don't load settings from profile.
I think the problem is we never raise the `ServerSettingsReceived` on clients and GVAR(SettingsInitialized) never changes to true, so that PFEH at bottom of postInit runs forever.
Server language english
Client screenshot in spanish:
> Fix ace_settings

- addons/nightvision/functions/fnc_changeNVGBrightness.sqf
#1374
Shots taken at -5, 0 and +5 adjustment:
Current:
New:
> NightVision adjustment - use CSE's gamma

- addons/explosives/XEH_postInit.sqf
- addons/explosives/XEH_preInit.sqf
- addons/explosives/functions/fnc_defuseExplosive.sqf
- addons/explosives/functions/fnc_detonateExplosive.sqf
- addons/explosives/functions/fnc_interactEH.sqf
- addons/explosives/functions/fnc_placeExplosive.sqf
- addons/explosives/functions/fnc_place_Approve.sqf
#1381 (MP Explosive Defusal Issue)
See the debug console from that issue and:
Different clients see different positions on the defuse object.  I don't have a good explanation for this besides the fact that we're attaching to a real object to a CfgAmmo which has some locality issues.
This switches to creating the defuse objects locally, only on clients and only when needed.
With the old system, if someone puts down a 100x minefield site, we'd have 100 extra objects each with a global setVariable.
> Explosives - Local defuse objects

- addons/weather/functions/fnc_updateAceWeather.sqf
* The higher the overcast value the higher the chance for rain
* But you can end up having no rain with an overcast value of 1.0
> Overcast > 0.7 no longer implies rain:

- addons/advanced_ballistics/config.cpp
- addons/common/CfgVehicles.hpp
- addons/common/XEH_postInit.sqf
- addons/common/config.cpp
- addons/explosives/CfgModule.hpp
- addons/hearing/CfgVehicles.hpp
- addons/interaction/CfgVehicles.hpp
- addons/map/CfgVehicles.hpp
- addons/medical/config.cpp
- addons/microdagr/CfgVehicles.hpp
- addons/mk6mortar/CfgVehicles.hpp
- addons/modules/XEH_postInit.sqf
- addons/modules/config.cpp
- addons/nametags/CfgVehicles.hpp
- addons/respawn/CfgVehicles.hpp
- addons/switchunits/CfgVehicles.hpp
- addons/vehiclelock/CfgVehicles.hpp
- addons/weather/config.cpp
- addons/zeus/config.cpp
As part of the reliable settings framework, we need to ensure that settings are not read from modules before the settings lists have arrived from the server.
So this PR does the following:
- Change all modules on ACE using settings to type ACE_Module, so we can guarantee that they wait for settings before initing.
- Command the ACE_Modules to init only once the settings from the server have arrived.
- Make ACE_Common require ACE_Modules, so we can use that functionality everywhere.
> Delay initialization of modules until settings are properly setup

- addons/hitreactions/ACE_Settings.hpp
- addons/hitreactions/config.cpp
- addons/hitreactions/functions/fnc_fallDown.sqf
Disables hit reactions when mounted.
Right now they can happen from FFV seats.
But it looks silly and never resets to normal seated position.
Also adds setting for minimum damage to trigger, and can disable by setting to -1.
> HitReactions - Don't do when mounted, add setting

- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_render.sqf
1)
Expanded render, compileMenu, compileMenuSelfAction so runOnHover can be CODE
e.g. runOnHover = QUOTE([] call DFUNC(myRunOnHoverCheck););
This allows more dynamic menus.
2)
- added SurgicalKit action to other body parts
- fixed vanilla damage in bandageLocal
- added ACE messge to CPRLocal informing about sucess
- added surgicalKit and surgicalKitLocal functions
- fixed some german translations
- added surgicalKit functions to preInit
> runOnHover can now be CODE & SurgicalKits

- addons/medical/XEH_postInit.sqf
Limited _strength of painEffect to 0.1 so a player does not have to watch a flashing screen while he can't do anything about it.
Otherwise we need to include a serious epilepsy warning! See http://en.wikipedia.org/wiki/Photosensitive_epilepsy
> Disabled pain effect while unconscious

- addons/laserpointer/XEH_postInit.sqf
- addons/laserpointer/functions/fnc_switchLaserLightMode.sqf
- optionals/compat_asdg/config.cpp
To reproduce: run @ASDG without the ace_asdg_comp - hit ctrl-L, laser pointer is gone.
ASDG messes with `PointerSlot` and compatible items.
If a user has ASDG installed without our compatibilty patch, then it seems like none of our ACE_x attachements will work on weapons.
With laser pointers, on switch we delete the current and then add the new laser.  If that new laser isn't compatible then it won't get added and the user will have nothing.
This dumps several error messages in the RPT and if the `ACE_nextModeClass` doesn't get added then it reverts back to the current so nothing is lost.
> ASDG- Fail gracefully if attachments not compatible

- addons/medical/functions/fnc_setUnconscious.sqf
- addons/medical/functions/fnc_unconsciousPFH.sqf
- addons/respawn/functions/fnc_restoreGear.sqf
Should fix #1500 (respawn with fakeweapon)
also 2 change to medical:
removes fakeweapon when exiting Unconscious (if added)
fixed exitWith on AI Unconsciousness death
> Hide fake weapon

- addons/medical/functions/fnc_setDead.sqf
I am currently in the process of porting a mission to ACE3, and it contains a scoreboard system which requires capture of the "source" and "projectile" parameters passed to the <a href="https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#HandleDamage" target="_blank">`HandleDamage`</a> event, either when the player falls unconscious or  right before being considered dead, in order to give appropriate credit. For the "unconscious" part, I am able to recover those values within the `medical_onUnconscious` event, but there is no equivalent for the "dead" part.
Since most ACE-handled deaths are triggered via `fnc_setDead` within `medical`'s `fnc_handleDamage` scripts, adding a `medical_onSetDead` event at this location allows extraction of aforementioned parameters, which is enough to …
> Added "medical_onSetDead" local event in fnc_setDead.sqf

- addons/medical/functions/fnc_handleDamage_caching.sqf
Should never return nil. Instead, return a 0 as it's expecting new damage. this may fix the random vanilla damage kicking in.
> Fix handleDamage caching return value

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_execNextFrame.sqf
- addons/common/functions/fnc_waitAndExecute.sqf
For each waitAndExec we create a new `CBA_fnc_addPerFrameHandler` and remove it.
They do have some overhead for stuff like handles that we really don't need.
```
x1 = [{systemChat "x"}, 0, []] call CBA_fnc_addPerFrameHandler; 
[x1] call cba_fnc_removePerFrameHandler;
```
is ~0.3 ms.  There also is an array that permanently grows each time we add: 
`count cba_common_pfhhandles` was about 3500 after an hour.
This just creates one single permanent pfeh that handles both execNextFrame and waitAndExec.  It's pretty lightweight and I'm think having it up all the time should be faster than constantly adding and removing.
> One PFEH for execNextFrame and waitAndExec

- addons/dagr/XEH_postInit.sqf
- addons/dagr/functions/fnc_outputData.sqf
- addons/dagr/functions/fnc_outputWP.sqf
- addons/dagr/functions/fnc_toggleOverlay.sqf
Thanks @SzwedzikPL for bringing this issue up. :+1: 
* Properly resets GVAR(run) when the main PFH aborts
* Prevents having duplicate PFHs
* Auto hides the DAGR overlay when you go into gunner view
> DAGR overlay auto hide

- documentation/development/setting-up-the-development-environment.md
Just a little addition to the setup which I had to perform to get the make.py to run.
* First problem was the PATH variable for git.exe was missing
* Then the make.py was complaining about DeOgg missing
The setup.py went through without a problem and I don't know why I had to add the path to git.exe (in AppData/Local/GitHub/PortableGit_{GUID}/cmd and ../bin), I did clone it (with the Git Shell since the application broke anyway).
> Added steps I had to do for windows to make ace3

- addons/medical/ACE_Settings.hpp
- addons/medical/CfgVehicles.hpp
- addons/medical/functions/fnc_moduleAdvancedMedicalSettings.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medicationLocal.sqf
- addons/medical/stringtable.xml
> [Adv. Medical]  New module options

- addons/grenades/CfgAmmo.hpp
- all UGL flares have a 60s lifespan now
- handheld signals and 20mm flares have smaller flare sizes
flares were extinguishing too fast before to have a real use, they should be more useful now.
> flares modified

- addons/javelin/functions/fnc_onOpticDraw.sqf
- addons/javelin/functions/fnc_onOpticLoad.sqf
#1444 - was my bad
I exited the PFEH when magazine was out of ammo, which meant it broke after the first shot
Now we exit if weapon isn't enabled
and suspend if magazine not loaded or not enabled
> Fix javelin locking

- addons/medical/functions/fnc_treatmentAdvanced_medicationLocal.sqf
Not sure if this is needed, (if current system is tuned correctly then no need to change).
But treatments says
`
How much will the heart rate be increased when the HR is low (below 55)? {minIncrease, maxIncrease, seconds}
`
But the code is doing min + random max so [2,4] could return 6
> Medical - change hrIncrease random min/max

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_adminKick.sqf
- addons/common/functions/fnc_checkPBOs.sqf
- Removed function `adminKick` as it is now redundant
- Used close display 46 in combination with `errorMessage` function
- Actual error message is what it is until a rewrite of CheckPBOs comes, meaning no displaying of what mods in the error pop-up as that is displayed in chat from a separate script - hence why waitUntil is also needed
> Fixed CheckPBO Kick

- tools/make.py
Fix missing backup files for config.cpp and $pboprefix$ in $NOBIN$ situations
Fixes #1682
> make.py - Fix missing backup files forr $NOBIN$ situations

- documentation/feature/attach.md
- documentation/feature/captives.md
- documentation/feature/concertina_wire.md
- documentation/feature/dagr.md
- documentation/feature/disarming.md
- documentation/feature/dragging.md
- documentation/feature/explosives.md
- documentation/feature/fonts.md
- documentation/feature/hearing.md
- documentation/feature/huntIR.md
- documentation/feature/logistics_uavbattery.md
- documentation/feature/logistics_wirecutter.md
- documentation/feature/magazinerepack.md
- documentation/feature/maptools.md
- documentation/feature/mk6mortar.md
- documentation/feature/mx2a.md
- documentation/feature/overheating.md
- documentation/feature/reloadlaunchers.md
- documentation/feature/respawn.md
- documentation/feature/sandbags.md
- documentation/feature/spotting_scope.md
- documentation/feature/tacticallader.md
- documentation/feature/tripod.md
- documentation/feature/ui.md
- documentation/feature/yardage450.md
- documentation/missionmaker/classnames.md
- documentation/missionmaker/modules.md
- Updated missionmaker -> modules
- Updated missionmaker -> classnames
- Changed ```<kbd>Left windows</kbd>``` to ```<kbd>⊞ Win</kbd>```
- Added concertina wire documentation (done)
- Added Dagr documentation (placeholder)
- Added Fonts documentation (doner)
- Added HuntrIR documentation (done)
- Added M2-XA documentation (done)
- Added sandbag documentation (done)
- Added spotting scope documentation (done)
- Added tactical ladder documentation (done)
- Added Yardage 450 documentation (done)
- Added Tripod documentation (done)
> documentation pass 7

- addons/ballistics/CfgVehicles.hpp
#1704 Ammo box missing AnimationSources
Also fixes the overlapping text on the side, as it seems like the animations control what's written on the box.
> #1704 - Add missing AnimationSources

- optionals/compat_rhs_afrf3/CfgMagazines.hpp
- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_afrf3/config.cpp
- optionals/compat_rhs_usf3/CfgMagazines.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/config.cpp
As mentioned in the title, this PR does ~~three~~ four things:
- It adds ACE reload functionality for belted weapons like the PKM or 249 using ace_reload.
- It allows the RPG-7 to be buddy reloaded using ace_reloadablelaunchers
- It disables ace_fcs on RHS vehicles to avoid conflicts with their hardcoded vehicle FCS.
- Sets g-force resistance to the RHS RU pilot.
I think formattings correct - spaces instead of tabs, etc.
> A few items for RHS compatibility (ACE reload and reloadablelaunchers, disabling ACE FCS)

- optionals/compat_rhs_afrf3/CfgMagazines.hpp
- optionals/compat_rhs_usf3/CfgMagazines.hpp
I had submitted pull request #1745 .. I noticed a mistake in what I had submitted.
The magazine class name for the 100rnd 7.62 boxes was inheriting as it was in RHS USF 0.3.7, not as it currently is in 0.3.8. Additionally I'm cleaning up some classes that probably didn't need to be individually defined
> Correcting RHS class inheritence from my previous PR

- addons/respawn/CfgAddons.hpp
- addons/respawn/config.cpp
- addons/respawn/functions/fnc_moveRallypoint.sqf
#1699 (partial fix)
Looks like at some point 
`ACE_RallypointExit_East` became `ACE_Rallypoint_East`
but wasn't switched everywhere
> Rally point object names

- addons/map/XEH_postInitClient.sqf
#1736 (Map can't be scrolled through or zoomed while player is moving)
Allow panning the lastStillPosition while mapShake is active.
Map doesn't stop shaking, just changes the "origin" that it shakes around.
I would be fine moving this to an option (like 3 settings for shake (off, on /w panning, and current-mode).
> Allow moving map while shake effect active

- addons/modules/XEH_postInit.sqf
We switched some modules to the ace_module framework that count on syncronized objects.
Fixes LSD Vehicles (Critical Bug!!!), Rallypoint (#1699) and vehLock.
This still has the huge limitation that normal BIS framework has, in that JIP unit's still won't be synchronized, only objects present at mission start.
> Ace_modules - Pass synced objects to functions

- addons/viewdistance/XEH_postInit.sqf
It now waits for settings to be something before it tries to do something.
Not sure why github thinks line 11 is enormous. This is what it looks like locally: https://imgur.com/p8NZ4d4
Would appreciate a sanity test that this works before merging.
> Viewdistance settingsInitialized

- addons/hearing/CfgWeapons.hpp
- addons/hearing/config.cpp
- addons/hearing/functions/fnc_earRinging.sqf
- addons/hearing/functions/fnc_updateVolume.sqf
- documentation/development/ace3-config-entries.md
- documentation/feature/hearing.md
Headgear can lower player volume and mitigate hearing damage.
Config vars:
protection: % of hearing protection, 1 = 100% protection (no hearing damage)
lowerVolume: % of volume to lower, 0.8 = 80% lowered (player volume will be 20% of normal volume)
> Headgear influence on hearing

- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_handleDamage_advanced.sqf
- addons/medical/functions/fnc_handleDamage_caching.sqf
Vanilla plays damage effects when `damage unit` returns > 0. 
The damage is increased when using return values in the `handleDamage` eventhandler. Returning 0 on the eventhandler appears to be breaking the current implementation of handleDamage in both basic and advanced (all units become invulnerable). 
Solution for advanced only at the moment is to reset damage in the caching and apply proper hitpoint damage after we are done processing the handleDamage calls. As an added side bonus this also seems to be fixing the flashing hitpoint textures.
> Fix vanilla damage effects

- optionals/tracers/CfgAmmo.hpp
Currently, some ammo classes such as B_65x39_Caseless are still laser beams. This PR fixes that.
> Fill gaps in ball tracer config

- addons/sitting/CfgVehicles.hpp
Thanks to @ViperMaul for pointing out (it's actually in current stable as well, not just 1.48 RC)!
```
Updating base class Furniture_base_F->ThingX, by z\ace\addons\sitting\config.cpp/CfgVehicles/Land_ChairPlastic_F/
Updating base class Furniture_base_F->ThingX, by z\ace\addons\sitting\config.cpp/CfgVehicles/Land_ChairWood_F/
Updating base class Furniture_base_F->ThingX, by z\ace\addons\sitting\config.cpp/CfgVehicles/Land_OfficeChair_01_F/
Updating base class Furniture_base_F->ThingX, by z\ace\addons\sitting\config.cpp/CfgVehicles/Land_RattanChair_01_F/
```
> Fixed chairs inheritance in sitting

- addons/javelin/XEH_pre_init.sqf
- addons/javelin/functions/fnc_onFired.sqf
- addons/javelin/functions/fnc_onOpticDraw.sqf
- addons/javelin/functions/fnc_onOpticLoad.sqf
- addons/javelin/functions/fnc_onOpticUnload.sqf
- addons/missileguidance/functions/fnc_onFired.sqf
Javelin - Fixed onOpticUnload, and switched from suing uiNameSpace to store the PFEH.  It was persistent through mission restart and could do some weird things.
Missile Guidance - Moved `PARAMS_7` above were variables are used.
> Missle Guidance / Javelin Fixes

- addons/nametags/ACE_Settings.hpp
Fixed:
```
Error in expression <= false;
_failed = false;
};
if (_value == 1) then {
_value = true;
_failed = fa>
Error position: <== 1) then {
_value = true;
_failed = fa>
Error ==: Type Bool, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
File z\ace\addons\common\functions\fnc_setSetting.sqf, line 32
```
> Fixed NameTags Settings defaults

- addons/medical/functions/fnc_treatment_failure.sqf
- addons/medical/functions/fnc_treatment_success.sqf
User reported that when unarmed, rapidly bandaging themselves they got animation locked into a "holding an invisible gun" in a crouched pose.
Debugging, it seems to be that we're still playing `ainvpknlmstpslaywrfldnon_medic` when we start the 2nd treatment, so that gets saved and replayed again at the end.  And without a fakegun, this seems to lock up the player.
```
12.97 - adding fake weapon
12.97 - saving anim amovpknlmstpsraswrfldnon
18.053 - rem weap
18.053 - playing anim amovpknlmstpsraswrfldnon
//Starting 2nd heal
20.617 - adding fake weapon
20.617 - saving anim ainvpknlmstpslaywrfldnon_medic
25.697 - rem weap
25.697 - playing anim ainvpknlmstpslaywrfldnon_medic
```
> Medical - Don't play *_medic anims at end

- addons/huntir/functions/fnc_handleFired.sqf
- addons/huntir/script_component.hpp
Fix #1843
5 seconds after firing the HuntIR, a secondary explosions launches the camera 50 meters up.
This prevents that from happening if the shell is null or dead on the ground.
> HuntIR - Handle Dead Projectile

- addons/optionsmenu/gui/pauseMenu.hpp
Fix #1812
I don't know much about how intro/outro works, 
but this seems to add the options menu button to them and nothing caught on fire.
> Show Options on Intro/Outro in Missions

- addons/kestrel4500/RscTitles.hpp
#1655
On large interface size, the kestrel would go off the bottom of the screen.
Now takes the min of either original value or a new value that guaranties the bottom is viewable.
e.g:  4x3, extra large interface is fully usable:
> Fix Kestrel Y position on large interface

- addons/vector/functions/fnc_illuminate.sqf
#1871
Doing `ctrlText` or `ctrlSetText` on a `RscControlsGroup` spams the rpt with 
```
control[ACE_ScriptedDisplayControlsGroup]: Unexpected control type [15]
```
We do both each frame so I believe it is the source of the frame lag when using the vector.
> #1871 - Don't do ctrlText(set) on RscControlsGroup

- addons/sitting/XEH_clientInit.sqf
- addons/sitting/XEH_preInit.sqf
- addons/sitting/functions/fnc_canSit.sqf
- addons/sitting/functions/fnc_handleInterrupt.sqf
- addons/sitting/functions/fnc_hasChairMoved.sqf
- addons/sitting/functions/fnc_sit.sqf
Fixes #1796 
Read https://github.com/acemod/ACE3/issues/1795#issuecomment-118667712 for Part 1.
> Akward Sitting Fixes Part 2

- addons/winddeflection/CfgEventHandlers.hpp
- addons/winddeflection/XEH_postInit.sqf
- addons/winddeflection/functions/fnc_handleFired.sqf
- addons/winddeflection/functions/fnc_updateTrajectoryPFH.sqf
Switches fnc_updateTrajectoryPFH to be a master PFEH, bullets get added to an internal array instead of creating/deleting a new cba PFEH each time.
I believe this solves a big performance problem where the `count cba_common_perFrameHandlerArray` can grow too large.
In actual session I saw it hit >2000.  Most entries are nil, but it sill takes time to process them, which happens each frame.  (2000 is about 5.5ms each frame),
In a stress test mission with about 50 ai + disabling the isPlayer check in handleFired so all AI bullets are tracked.  Unscientific results because AI are unpredictable, but I get a huge performance difference:
VS
With PFEH debug enabled:
```
ace_windDeflection_pfeh_counter: Average: 0.812859s / 2257 = 0.36015ms
```
> Wind deflection single pfeh

- AUTHORS.txt
- optionals/compat_rhs_usf3/CfgWeapons.hpp
Added HuntIR as magazine to all RHS AR15s that has a M203 or M320 attached (class rhs_weap_m4_Base).
I've added full magazine list to the M320-class instead of using the += operator due to possible PBO:er version issues when/if binarizing configs. If no binarization is done I'm happy to replace the M320-class  with:
class M320_GL : M203_GL {magazines[] += {};};
Tested and working in my compatibility-mod; http://www.armaholic.com/page.php?id=28963
> RHS Weapon HuntIR Compatibility

- addons/medical/functions/fnc_handleDamage.sqf
fix #1946 
Suggested as a patch/hotfix.
> Fix incorrect damage value return when prevent death is enabled

- addons/advanced_ballistics/functions/fnc_handleFired.sqf
Fix #1962
PR #1886 changed EFUNC(winddeflection,updateTrajectoryPFH) to be called once and bullets added to the array.
I missed that AB called that function to hand-off bullets.
> Fix Changes in Wind Deflection s in AB

- addons/laser/functions/fnc_seekerFindLaserSpot.sqf
This is a bandaid for issues releated to #1959
`fnc_vanillaLaserSeekerHandler.sqf` can set _laser to [-1,-1];
which causes an error with CBA_fnc_vect2polar that expects a vector.
> Laser - Handle Bad Data Returns

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_headBugFix.sqf
Disable headbugfix for Handcuffed/Surrender,unconscious,water surface and log the situation.
> Improve headbugfix

- addons/common/XEH_postInit.sqf
- addons/medical/functions/fnc_handleCreateLitter.sqf
* Common: Top of fnc_syncedEventPFH.sqf is `if(!isServer) exitWith { false };` - so there is no reason to install that PFEH anywhere but the server.
* Medical: GVAR(litterPFHRunning) was never set true, so it installed an additional PFEH for each litter created.
> CreateLitter / syncEvents performance fixes

- addons/common/XEH_postInit.sqf
- addons/common/stringtable.xml
Adding keybinding localization over `CBA_fnc_registerKeybindModPrettyName`, which in the current version of CBA are still broken, but should be functioning perfectly after CBATeam/CBA_A3#105 gets merged.
> Added localizations for keybinding categories

- AUTHORS.txt
- addons/weather/functions/fnc_displayWindInfo.sqf
Replaced direction detection with ```CBA_fnc_headDir``` to calculate the indicator direction off of the head direction instead of the player direction.
This solves #1892.
> Headdirection based wind indication

- addons/interaction/CfgVehicles.hpp
#2024
I'm pretty sure joinGroup should be disabled if EnableTeamManagement is false.
Unless we want separate settings for fireteam team management (different colors) and a setting for joining/leaving groups.
> EnableTeamManagement setting for joinGroup

- addons/common/functions/fnc_setSettingFromConfig.sqf
- addons/interact_menu/ACE_Settings.hpp
- addons/interact_menu/stringtable.xml
- addons/medical/ACE_Settings.hpp
- addons/medical/stringtable.xml
- addons/optionsmenu/CfgEventHandlers.hpp
- addons/optionsmenu/XEH_postInit.sqf
- addons/optionsmenu/XEH_preInit.sqf
- addons/optionsmenu/functions/fnc_exportSettings.sqf
- addons/optionsmenu/functions/fnc_onCategorySelectChanged.sqf
- addons/optionsmenu/functions/fnc_onServerCategorySelectChanged.sqf
- addons/optionsmenu/functions/fnc_onServerSaveInputField.sqf
- addons/optionsmenu/functions/fnc_onServerSettingsMenuOpen.sqf
- addons/optionsmenu/functions/fnc_onSettingsMenuOpen.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_serverSettingsMenuUpdateList.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateKeyView.sqf
- addons/optionsmenu/functions/fnc_settingsMenuUpdateList.sqf
- addons/optionsmenu/functions/fnc_stringEscape.sqf
- addons/optionsmenu/functions/fnc_updateSetting.sqf
- addons/optionsmenu/gui/settingsMenu.hpp
- addons/optionsmenu/stringtable.xml
* Adds a category selection to the options menu, both client and config export variants.
* Two of the larger modules with settings received categories with this PR. All others still require adding them.
* All categories are localized for clients. 
Adding a new category is done through adding the following attribute to a settings entry:
```c++
category = "STR_ACE_Module_Category";
```
Obviously replace module by whatever module the setting belongs to and add the string to the stringtable entry with necessary translations. No other requirements.
> Add category optionsmenu #852

- addons/nametags/ACE_Settings.hpp
Fixes #2076 - The missing one was actually "Enabled".
@gienkov you should get the error `String $STR_ace_nametags_Enabled not found` before.
> Fixed incorrect string path in nametags

- addons/medical_menu/stringtable.xml
The space in the XML metadata leads to XML parser issues.
> Medical Menu stringtable.xml space invalidating xml structure

- addons/nametags/functions/fnc_onDraw3d.sqf
> Don't draw nametags when escape menu is open

- addons/interact_menu/functions/fnc_addActionToClass.sqf
- addons/interact_menu/functions/fnc_addActionToObject.sqf
From @alganthe 
doing `[cursorTarget, 0, ["ACE_TapShoulderRight"], XX] call ace_interact_menu_fnc_addActionToObject;` will cause hard lockup if `XX` is undefined.
Params is very fast and I think it's worth it as these can be publicly used functions.
> AddAction basic param checking

- addons/common/XEH_postInit.sqf
Don't need this anymore with current CBA
Ref:
https://dev.withsix.com/issues/76243
https://github.com/CBATeam/CBA_A3/commit/b430fd076253076a8bd5910bd8c71677d0d0aa77
also our code doesn't actually do anything as `ACE_time > 0` is always true even at breifing :smile:
> Remove PFEH hack

- addons/common/functions/fnc_checkPBOs.sqf
In MP clients will wait forever for `ACE_Version_ClientErrors` in a spawned loop
which can only be set if GVAR(checkPBOsCheckAll) is true and checkVersionNumber is run.
> CheckPBO Fix endless waitUntil if checkAll is false

- addons/map/config.cpp
1. RscDisplayDiary doesn't even have a compass object that needs to be changed
2. The briefing displays (RscDisplayGetReady, RscDisplayClientGetReady, RscDisplayServerGetReady) were all inheriting from base class RscDisplayMainMap and re-defined the compass object subclasses was overriding that subclass inheritance chain (producing missing idc errors in the .rpt).
> Fix ace_map changes to compass display object

- addons/common/functions/fnc_getHitPointsWithSelections.sqf
Fixed error pop-up kicking you out of game in case a third party vehicle has incorrect configured hitpoints/selections.
This is necessary for the vehicle repair module, that makes use of `getHitPointsWithSelections`. Some custom party modifications have incorrectly configured their vehicle hitpoints and as a result you will get kicked out of the game. 
This validation check ensures this doesn't happen anymore.
> Fixed error pop-up invalid configured hitpoints

- addons/medical/functions/fnc_treatment.sqf
Fix #2178 - Un-deploys if bipod is out
Also fixes a minor problem when healing with a pistol when standing, it would switch from pistol back to rifle and then back to pistol.  Picks ending animation based on starting weapon.
> Fix treatment when weapon deployed

- addons/common/functions/fnc_disableUserInput.sqf
- addons/common/functions/fnc_isFeatureCameraActive.sqf
- The `disableUserInput` function allows for use of chat if user has admin access, however it didn't account for the host of listen servers (where `serverCommandAvailable` returns false).
- Expanding the `isFeatureCameraActive` function to support the curator camera and the upcoming ace_spectator camera. Also optimized the lazy evaluation and updated the function header.
> Fix and enhancement of two common functions

- addons/zeus/ACE_Settings.hpp
- addons/zeus/CfgEventHandlers.hpp
- addons/zeus/XEH_preInit.sqf
- addons/zeus/functions/fnc_addObjectToCurator.sqf
- addons/zeus/stringtable.xml
Add objects from mission start and placed down by other curators to all curators.
> Add objects to all curators

- addons/scopes/functions/fnc_firedEH.sqf
Accidentally replaced select with wrong variable, resulting in scope adjustments using elevation for both windage and elevation.
> Hotfix for projectile direction adjustment in Scopes module

- addons/slideshow/functions/fnc_makeList.sqf
Will now trim splitted input strings rather then remove all whitespace. Fixes #2222
> Allow spaces in slideshow module

- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
This is for the `6: Action parameters <ANY> (Optional)`
Compile self uses `{}`
compile external uses `[]` which I think makes more sense
ref #2228
> Compile Self Menu, set "Default Params" to array instead of code

- addons/medical/stringtable.xml
Fielddressing and Aid kit are the same in the german translation which is missleading.
Changed to "Erste-Hilfe-Set" (first aid kit) which is less missleading.
> Changed german strings for aid kit

- addons/medical/ACE_Medical_Treatments.hpp
Make bandaging longer as it is not very fast process.
Make putting on tourniquet faster cause it's should be easy to put one on limb, so it's actually useful now and with above change (putting it on before was longer than bandagin).
> Bandage and tourniquet on adv. medical change proposal

- addons/repair/CfgVehicles.hpp
- addons/repair/functions/fnc_addRepairActions.sqf
- addons/repair/script_component.hpp
**Overview:**
Adds a framework for custom hitpoint positions/selection names to be used as position to render the repair action of the specified hitpoint. Most default selections (except Winch) have position of `[0,0,0]` which obviously doesn't work, the check if it's on that location was added to prevent being over the base interaction menu (if it is on zero location, it will be grouped into the base interaction menu as before).
**Config entries:**
`GVAR(hitpointPositions[]) = { {"HitPointName", {position}} };`
Example:
`GVAR(hitpointPositions[]) = { {"HitEngine", {0, 1, -1}}, {"HitFuel", {0, 0, -0.5}} };`
(It is impossible to use array in a config array, so I decided to parse the string into an array.)
Instead of a position it can also be a selection name:
`GVAR(hitpointPositions[]) = { …
> Custom Hitpoint Repair Positions Framework

- addons/medical/ACE_Medical_Treatments.hpp
Around 15 seconds seems optimal (for dead bodies that are left in **one** piece).
> Increase "load in bodybag" action time to 15s

- addons/cargo/CfgEventHandlers.hpp
- addons/cargo/XEH_postInit.sqf
- addons/cargo/XEH_preInit.sqf
- addons/cargo/functions/fnc_addCargoItem.sqf
- addons/cargo/functions/fnc_getSizeItem.sqf
- addons/cargo/functions/fnc_initVehicle.sqf
- addons/cargo/functions/fnc_loadItem.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
Replaced `cargo_hideUnit` event with already existing `hideObjectGlobal` from common.
Added new events to cargo:
Type | Event Name | Passed parameter(s) `_this` | Locality
------ | --------------- | ------------------------------------ | ---------
Listenable | "cargoLoaded" | [_item, _vehicle] | Global
Listenable | "cargoUnloaded" | [_item, _vehicle] | Global
Listenable | "cargoAddedByClass" | [_item, _vehicle, _amount] | Global
Callable | "LoadObject" | [_item, _vehicle] | Local
Callable | "UnloadObject" | [_item, _vehicle] | Local
Callable | "AddCargoByClass" | [_item, _vehicle, _amount (default: 1)] | Local
> Cargo Events

- addons/repair/ACE_Repair.hpp
- addons/repair/CfgVehicles.hpp
- addons/repair/XEH_preInit.sqf
- addons/repair/functions/fnc_addRepairActions.sqf
- addons/repair/functions/fnc_canMiscRepair.sqf
- addons/repair/functions/fnc_doRepair.sqf
- addons/repair/script_component.hpp
**Overview:**
Adds a framework to allow grouping of multiple hitpoints into one by config. This means only the first hitpoint in the config array gets the repair action, all the rest in that group get repaired simultaneously when the main one gets repaired. They repair to full even if the main repair is only partial, this should have no issues though.
**Config entries:**
`GVAR(hitpointGroups[]) = { {"hitpointName1", {"hitpointName2"}} };`
Example:
`GVAR(hitpointGroups[]) = { {"HitGlass1", {"HitGlass2"}} };`
(`HitGlass1` is the one which gets the action here and `HitGlass2` is grouped under it.)
**To-do:**
> Repair Hitpoint Groups Framework

- addons/cargo/functions/fnc_canLoad.sqf
- addons/cargo/functions/fnc_initVehicle.sqf
Should fix #2281 
Will probably make #2185 unnecessary 
CreateAction doesn't add the canInteractWith check, so that's why both actions are showing at the same time when they should be mutually exclusive.
Should also solve stuff like people loading objects that others are carrying.
> Add canInteractWith checks for cargo

- addons/hearing/CfgWeapons.hpp
`"H_HelmetSpecB"` and `"H_HelmetB_light"` (and their variations) have visible Peltor Headsets on the 3d model. Those are electronical and will block/damp sounds that are too loud as soon as the sound appears but won't dampen environment sounds like earplugs would.
> Add Hearing Protection to Helmets with Peltor Headsets

- addons/hearing/XEH_postInit.sqf
- addons/hearing/functions/fnc_addEarPlugs.sqf
- addons/hearing/functions/fnc_earRinging.sqf
- addons/hearing/functions/fnc_explosionNear.sqf
- addons/hearing/functions/fnc_firedNear.sqf
- addons/hearing/functions/fnc_hasEarPlugsIn.sqf
- addons/hearing/functions/fnc_moduleHearing.sqf
- addons/hearing/functions/fnc_putInEarplugs.sqf
- addons/hearing/functions/fnc_removeEarplugs.sqf
- addons/hearing/functions/fnc_updateVolume.sqf
Code cleanup of Hearing module.
> Code cleanup of Hearing module

- addons/interact_menu/XEH_clientInit.sqf
Checks if the key pressed matches the zeus menu keybind and only fires the code to handle CBA keybinds if true. Should fix the majority of weirdness with keybinds in zeus. However, not perfect as shared keybinds with different modifiers will still fire and it's really an un-ideal workaround.
Fixes #1951
> Prevent CBA keybindings in zeus interface

- addons/hearing/CfgEventHandlers.hpp
- addons/hearing/functions/fnc_explosionNear.sqf
- addons/hearing/functions/fnc_firedNear.sqf
- addons/hearing/functions/fnc_moduleHearing.sqf
Fix 	#1988  - the "hearing damage" switched from a 0-1 scale to 0-20.
It's still not perfect because we can only get an event when taking direct explosive damage,
Also got some nice performance improvements with new `isKindOf` command in firedNear
0.230 ms vs 0.081 ms
> Hearing stuff

- addons/common/XEH_postInit.sqf
- addons/optics/XEH_postInit.sqf
- addons/optics/functions/fnc_onDrawScope2D.sqf
~~The camera for the pip opctics break intros with cameras. This is because the camera effect "internal" breaks whenever a new camCreate command is used.
Unfortunately there is no command that returns all cameras. The only solution for this problem I can come up with (without adding random sleeps and hoping for the best) is for mission makers to use a predifned variable name for their cameras.~~
```
~_camera = "camera" camCreate [0,0,0];~
~_camera cameraEffect ["internal", "back"];~
```
~becomes:~
```
~ACE_CustomCamera = "camera" camCreate [0,0,0];~
~ACE_CustomCamera cameraEffect ["internal", "back"];~
```
~~We probably should add this to the wiki if this PR gets merged.
Also fixes the camera being broken when entering the VA for the first time.~~
Completely solved this by using the …
> fix custom cameras (for intros) being broken with ACE, fix #2248

- addons/overheating/CfgWeapons.hpp
This fixes the issue with unselectable grenades when spawning as autorifleman of every faction (except for FIA?).
Reason is that grenades can be added to the throw muzzle by config, even though there is not enough space in the inventory. This fix was in AGM, but probably got lost during porting...
The spare barrel still weights 1.36kg. Considering it's "usefulness" this seems more approriate anyway.
> fix autoriflemen spawning with 0x frag grenade bug

- addons/goggles/functions/fnc_checkGoggles.sqf
- addons/goggles/functions/fnc_isGogglesVisible.sqf
Fixes #1721 and #1342
Originally I introduced a canUseWeapon check to fix the FFV seats. Then when it came to considering the second issue I think it makes sense to just remove any special treatment for gunners anyway:
- It simplifies the code and offers a slight performance benefit (that function is used by a PFH)
- If you intend to be a vehicle gunner, you probably shouldn't be wearing unsuitable glasses anyway. Besides it's not the end of the world if you do, you can still see after all.
- It makes things more consistent
- Overlay already persists when using a UAV
- Would be inconsistent for the weirdly configured commander seats/co-pilot seats
- All the other effects checked by that function will now still take place when in a vehicle (if the vehicle goes underwater/etc.)
- We will be …
> Fix gunner goggles

- addons/grenades/CfgAmmo.hpp
- addons/grenades/CfgMagazines.hpp
- addons/grenades/Effects.hpp
- addons/grenades/XEH_preInit.sqf
- addons/grenades/functions/fnc_flare.sqf
- addons/grenades/functions/fnc_throwGrenade.sqf
This is the only way I know of to fix the flickering flares #1079 
benefits:
- hand flares can bounce like normal grenades
- they have impact sounds
- no flickering
- more options to adjust light
disadvantages:
- it's scripted
- it's not config
> scripted approach to hand flares, fix #1079

- addons/maptools/functions/fnc_updateMapToolMarkers.sqf
If you have your aspect ratio set wrong map tools will draw incorrectly (dot wobbles inside crosshairs):
It really is more of a user problem, but we can handle it.
> MapTools - Handle Bad Aspect Ratio

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_runAfterSettingsInit.sqf
From https://github.com/acemod/ACE3/issues/1842#issuecomment-120689590
Adds a way to run a function w/ parameters after settings are initialized.
We really need something like this for when we run code on objects that depends on settings, as the order isn't guaranteed in dedicated MP.
For example: @ViperMaul @Glowbal - the new medical FUNC(init) can run before settings are init
https://github.com/acemod/ACE3/blob/medical-adjustments/addons/medical/functions/fnc_init.sqf
@jonpas did something very similar in https://github.com/acemod/ACE3/pull/2187/files#diff-75f4a28dd014c00256df94dd2f6e929fR28
Helper function, otherwise you can just do something like:
```
if (!EGVAR(common,settingsInitFinished)) exitWith {
EGVAR(common,runAtSettingsInitialized) pushBack [FUNC(init), _this];
};
```
> Setting init delay functions

- addons/cargo/functions/fnc_initVehicle.sqf
I think it makes sense, if a vehicle is locked you probably can't get into the trunk either. Automatically compatible with `vehiclelock` as well obviously.
> Prevent Cargo opening if vehicle is locked

- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_copyDeadBody.sqf
- addons/medical/functions/fnc_setDead.sqf
- addons/medical/functions/fnc_setStructuralDamage.sqf
Killing a soldier by shooting him in the chest causes the whole body to get bloody. This is because `setDamage 1` is called in fnc_setDead. I wrote a function that can manipulate the structural damage without changing the hitpoints to prevent this.
Possibly needs to be used in more places. I have no idea when setDamage is intended (e.g. `setDamage 0` for a complete heal) and where it's not.
Uses the new hit index system. Pretty neat.
Plz review Glowbal.
> setStructuralDamage function

- addons/grenades/CfgAmmo.hpp
makes more sense to me and the misc. grenade group is really big already.
> sort flashbang under explosive grenades, not misc grenades

- addons/medical/functions/fnc_actionCheckBloodPressureLocal.sqf
Fixes #2400
fnc_getBloodPressure returns:
`[_bloodPressureLow max 0, _bloodPressureHigh max 0]`
> change order of BloodPressure readout, fix #2400

- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_determineIfFatal.sqf
- addons/medical/functions/fnc_handleDamage_advanced.sqf
- addons/medical/functions/fnc_handleDamage_basic.sqf
- addons/medical/functions/fnc_handleDamage_caching.sqf
- addons/medical/functions/fnc_treatmentBasic_bandageLocal.sqf
Some minor tweaks to medical based upon user feedback from RC testing.
> Medical tweaks

- addons/interact_menu/XEH_clientInit.sqf
Ref #2437 (not our fault so it's not a fix)
At mission start checks for interaction menu compiles on all units and vehicles and spits out a message to users that there is a problem.
Designed to help users identify when mods break XEH (with RHS update I see this happening even more).
May help with #1171
> Bad xeh check

- addons/medical/functions/fnc_treatmentAdvanced_CPRLocal.sqf
> Fix CPR params

- addons/map/CfgVehicles.hpp
- addons/map/functions/fnc_blueForceTrackingModule.sqf
#2503
module had `if (!hasInterface) exitWith {};` so settings never set on dedi
> Run BFT module on server

- addons/repair/functions/fnc_canMiscRepair.sqf
- addons/repair/functions/fnc_canRemove.sqf
- addons/repair/functions/fnc_canRepairTrack.sqf
- addons/repair/functions/fnc_canReplaceTrack.sqf
- addons/repair/functions/fnc_canReplaceWheel.sqf
#2525
There is no canInterctWith check for repair actions, so right now you can remove wheels when underwater or handcuffed.
Does it make sense to do repairs underwater, if so we will want to add an exception for that??
> Add CanInteractWith checks for repair

- addons/overheating/XEH_postInit.sqf
>But anyway you can't clear a weapon jam while turned out of a vehicle
>Like when using fire from vehicle in a commander hatch
The `EFUNC(common,canUseWeapon)` already limits this keybind to FFV / turned out animations states, so this should be safe.
Without this, there is no way to clear a jam.  (Shift+R) just reloads and does't fix the jam.
> Allow fixing jam when in FFV slot

- addons/common/functions/fnc_disableUserInput.sqf
Also fixes that all buttons where ignored in that state. Was an leftover from AGM that is no longer needed with CBA keyhandling.
> Use CBA PFH in disableUserInput

- addons/captives/functions/fnc_canApplyHandcuffs.sqf
#2524
Can always take Unconsciou units captive regardless of GVAR(requireSurrender) (still does side checking from ace_setting)
> Take Unconscious captive

- addons/explosives/functions/fnc_addExplosiveActions.sqf
Fix #2537
I think we have to delay one frame because the interaction menu could still be partially open and the same mouse click used to select will trigger the setupExplosive click detector.
> Delay one frame when selecting explosives

- addons/spectator/functions/fnc_setSpectator.sqf
If you call setSpectator directly from init.sqf you'll be put into some
weird limbo mode with borders and spectator not working. This should fix
it
> fix spectator view if called instantly

- addons/medical/functions/fnc_setUnconscious.sqf
Fixes #148
Confirmed working
5 AIs with
`[this, true] call ace_medical_fnc_setUnconscious`
in init box
No medic modle: 3 die and 2 are unconscious
With module and "AI Unconsciousness" set to "Enabled": All 5 unconscious
> delay setUnconscious until the settings are inited

- addons/cargo/functions/fnc_addCargoItem.sqf
- addons/cargo/functions/fnc_loadItem.sqf
And disabled it when called through `addCargoItem`, for example `addSpareParts`, which happens on vehicle init, would show the hint, even if the vehicle would be spawned during the mission.
> Optionalized Cargo Loaded Hint

- addons/medical/functions/fnc_moduleAssignMedicalVehicle.sqf
#2423
For prefilled vehicles (not empty) `syncronizedObjects` of the module will goto the driver not the vehicle itself.
This just runs the setVariable on `vehicle _x` instead of `_x`.
```
_x=medevac1d, _xVehicle=medevac1"
```
> assign vehicle module fix for prefilled veh

- addons/captives/XEH_postInit.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
"SetHandcuffed"/"SetSurrendered" are target events
This adds a global event for "CaptiveStatusChanged", after effects are applied
It's a similar format
`[_unit, _state, _cause]`
> Global Event for "CaptiveStatusChange"

- addons/medical/functions/fnc_treatmentAdvanced_bandageLocal.sqf
[Issue: Adv. Medical Heal hitpoints doesn't work #2498.](https://github.com/acemod/ACE3/issues/2498)
With "ace_medical_healHitPointAfterAdvBandage" enabled fully bandaging wounded body parts were not healing those body parts in the Arma engine. ACE's interface would show body parts fully bandaged and undamaged but the player's uniform would remain bloody and the effected parts would remain non-functional (E.g.: Even though ACE thinks your legs are healed, Arma doesn't and you can't run. Your pants are also full of blood).
This fix checks to see if an ACE body part is fully bandaged and then heals the respective Arma body part while keeping in mind that Arma does not have separate body parts for left & right arms and legs.
> Fix healHitPointAfterAdvBandage - Issue #2498.

- addons/medical/stringtable.xml
> PAK and Surgical Kit strings normalized inside modules.

- addons/laser_selfdesignate/CfgWeapons.hpp
- addons/missileguidance/CfgAmmo.hpp
- addons/missileguidance/CfgWeapons.hpp
redo #2434 for master
Fix #2349 #1363 #1898
As far as I can tell, this is what missleguidance will be enabled for:
Name | Ammo  | Magazine | Weapon
------------- | ------------- | ------------- | -------------
DAGR | M_PG_AT | 24Rnd_PG_missiles | missiles_DAGR
Hydra70 | ACE_Hydra70_DAGR | 6Rnd_ACE_Hydra70_DAGR | missiles_DAGR
Hellfire (ComancheTest?) | ACE_Hellfire_AGM114K | 6Rnd_ACE_Hellfire_AGM114K | missiles_DAGR
Javelin Man | ACE_Javelin_FGM148 | Titan_AT | launch_Titan_short_base
Javelin Static | ACE_Javelin_FGM148_static | 1Rnd_GAT_missiles | missiles_titan_static
But right now we're setting `canLock` for the base **RocketPods** which breaks stuff like the `missiles_SCALPEL` (9K121 Vikhr) which the Greyhawk/AAF CAS use. Also the GBU.
I think we just want to mess with `canLock` on …
> #2349 - Don't disable locking for base RocketPods

- tools/sqf_validator.py
So it can be used without specifying python version from command line.
> Add shebang line to specify python version to SQF validator

- README.md
- docs/README_DE.md
- docs/README_PL.md
- Fixed Slackin badge links (were still pointing to koffeinflummi.de)
- Added Travis CI build status (master branch) badge
- Updated version in non-English files
- Updated download size
The Travis CI build status badge is at the end now, might be better to move it elsewhere, feel free to give suggestions.
> Update README.md files

- addons/map/functions/fnc_simulateMapLight.sqf
Fix #2734
Should fix map darkness and map flashlights for trippleHead users.
For everyone else `safeZoneWAbs = safeZoneW` so it should have no effect.
Taging @voiperr as it messes with flashlight, but this should be good to go.
> Map effects / flashlights for TrippleHead

- addons/sitting/functions/fnc_sit.sqf
> Use AGL for sitting setPos

- addons/map/CfgVehicles.hpp
- addons/map/functions/fnc_compileFlashlightMenu.sqf
- addons/map/stringtable.xml
Currently each flashlight has 2 mutually exclusive child actions
This just shortens the depth of the action tree and puts the toggle action on the flashlight itself. 
(The 4th level can be hard to reach on some interface sizes)
@voiperr - If you were planning on adding other actions besides on/off or have any other objections to this please let me know.
before
after
> Simplify Map Light Interactions

- addons/fcs/XEH_clientInit.sqf
- addons/fcs/functions/fnc_keyDown.sqf
- addons/fcs/functions/fnc_keyUp.sqf
Fix lead calculation aspect of #2126
> Fix lead calculation for vehicle FCS

- addons/cargo/CfgVehicles.hpp
I've fixed small UAV carrying allot of cargo.
The following parameters were active:
```ace_cargo_hasCargo = 1;```
```ace_cargo_space = 8;```
This is due to the fact that the UAV inheritance the class ```Helicopter```
> Fixed small UAV carrying allot of cargo.

- addons/realisticnames/CfgWeapons.hpp
- addons/vehicles/CfgVehicles.hpp
- addons/vehicles/CfgWeapons.hpp
Fix #2701
weapon LMG_coax  uses `usti hlavne3`, 
AMV's default weapon and model expect `...2`
> - Fix gun smoke on AMV

- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_translateSelections.sqf
This addition tries to deal with the new hitpoints introduced in Arma3 v1.50 and above. It converts new selection names to by the current medical system usable selection names.
This is only a temporarily patch, while we are still working on a larger overhaul to account both the new hitpoints and any potential new features / polishing.
> Add method to deal with new hitpoints

- addons/common/functions/fnc_addScrollWheelEventHandler.sqf
- addons/common/functions/fnc_cachedCall.sqf
- addons/common/functions/fnc_getDeathAnim.sqf
- addons/common/functions/fnc_progressBar.sqf
- addons/common/functions/fnc_setVariablePublic.sqf
- addons/common/functions/fnc_throttledPublicVariable.sqf
- addons/common/functions/fnc_waitAndExecute.sqf
- addons/disarming/functions/fnc_disarmDropItems.sqf
- addons/dragging/functions/fnc_startCarry.sqf
- addons/dragging/functions/fnc_startDrag.sqf
- addons/dragging/functions/fnc_startDragPFH.sqf
- addons/explosives/functions/fnc_detonateExplosive.sqf
- addons/fcs/functions/fnc_keyUp.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/javelin/functions/fnc_onOpticLoad.sqf
- addons/magazinerepack/functions/fnc_simulateRepackEvents.sqf
- addons/map/functions/fnc_determineMapLight.sqf
- addons/medical/XEH_respawn.sqf
- addons/medical/functions/fnc_addHeartRateAdjustment.sqf
- addons/medical/functions/fnc_onMedicationUsage.sqf
- addons/medical/functions/fnc_playInjuredSound.sqf
- addons/medical/functions/fnc_setUnconscious.sqf
- addons/medical/functions/fnc_treatmentAdvanced_medicationLocal.sqf
- addons/mk6mortar/functions/fnc_dev_simulateFindSolution.sqf
- addons/mk6mortar/functions/fnc_dev_simulateShot.sqf
- addons/overheating/functions/fnc_cooldown.sqf
- addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- addons/scopes/functions/fnc_showZeroing.sqf
I think I've gone over this carefully enough to not have replaced any instances that is supposed to say ACE_time (again).
> Changed ACE_time back to time in comments where appropriate

- addons/main/script_debug.hpp
- addons/main/script_macros.hpp
- addons/main/script_mod.hpp
Removed macros that are now in CBA (stable and released), unused macros (`EXPLODE_n`) and some redundant definitions. Also made debug ifs nicer.
> Cleanup Macro Definitions

- addons/logistics_wirecutter/CfgVehicles.hpp
- addons/logistics_wirecutter/functions/fnc_interactEH.sqf
- addons/logistics_wirecutter/functions/fnc_isFence.sqf
Update isFence configs, was missing some (industrial and razor) and had some that didn't make any sense (damaged fences and pipes)
Use 1.50's `getModelInfo` which seems to be about 3x faster than doing string old string find.
> Wirecutters - Update Fence Configs, Use faster getModelInfo

- addons/nametags/functions/fnc_initIsSpeaking.sqf
acre_api_fnc_isBroadcasting isn't needed as isSpeaking will be true, 
plus it used wrong acePlayer instead of _unit.
Thanks to @Sniperhid
> Nametags - Cleanup isSpeaking for ACRE

- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_translateSelections.sqf
Adds a backup method to get the correct selection if the model/uniform is weird.
fix #2768 - VR people have weird hitpoint selection names:
```
class HitHead: HitHead {
name = "hitHead";
```
Seems to fix odd RHS uniforms (eg, this guy could not take damage from headshots):
```
bob = group player createUnit ["B_soldier_F", Position player, [], 0, "FORM"];
bob addUniform "rhs_uniform_cu_ucp";
```
> Medical - Better handle odd selection/hitpoint names

- addons/medical/functions/fnc_displayPatientInformation.sqf
- addons/medical/functions/fnc_modifyMedicalAction.sqf
- addons/medical_menu/functions/fnc_updateUIInfo.sqf
Fix #2772
With GVAR(level) = 2, but advanced not enabled for AI, the AI won't get any `GVAR(openWounds)`.
This will use the "basic" method of showing wound info if the unit doesn't `hasMedicalEnabled`
> Display basicMed wounds for AI in mixed mode

- addons/advanced_ballistics/functions/fnc_calculateAmmoTemperatureVelocityShift.sqf
- addons/advanced_ballistics/functions/fnc_handleFired.sqf
#2696 - fnc_calculateAmmoTemperatureVelocityShift threw script errors doing a `select 10` on empty array.  Not sure if it will fix issue as I can't reproduce.
#2709 - HandleFired `_muzzleVelocityShift` and `_ammoTemperatureVelocityShift` were never defined so velocity shifts didn't work
> RangeCard / AB fixes

- addons/movement/CfgMoves.hpp
From https://forums.bistudio.com/topic/140837-development-branch-changelog/?p=2922316:
> Fixed: Couldn't use sights in adjusted prone stance
If someone could confirm that on dev-branch that would be great, either way this PR removes that fix from ACE3, please set milestone to Backlog for now until it is in vanilla (stable branch).
> Remove enable optics in adjusted prone stances

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_readSettingsFromParamsArray.sqf
Just an idea, not sure if we need
Allows you to make settings changeable by mission params, so one mission can be played with different settings
for now just limited to SCALAR/BOOL
e.g.
```
class Params {
class ace_medical_level {
title = "Medical Level";
ACE_setting = 1;
values[] = {1,2};
texts[] = {"Basic", "Advanced"};
default = 2;
};
```
> Read settings from paramsArray (params in description.ext)

- addons/advanced_ballistics/functions/fnc_readWeaponDataFromConfig.sqf
Most guns don't have a `ACE_twistDirection` and they where defaulting to 0 instead of 1.
> AB - Fix ACE_twistDirection

- addons/missionmodules/functions/fnc_moduleAmbianceSound.sqf
Cleanup:
- switch to `params`
- removed unused privates
- added previously not declared privates
- merged two loops
Also fixed sounds not playing if the path had a leading backslash.
> Cleanup ambient sounds module

- addons/medical/functions/fnc_treatmentAdvanced_bandage.sqf
Close #2528
In advanced medical without enableFor AI. Bandaging an AI would exit
before adding log.
> Move bandage log before basic exit

- addons/overpressure/functions/fnc_fireLauncherBackblast.sqf
- addons/overpressure/functions/fnc_fireOverpressureZone.sqf
- addons/overpressure/functions/fnc_getDistance.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- Fix passing magazine/ammo to overpressure event
- Use AGL for nearEntities
- Fix getDistance returning nil
Use `lineIntersectsSurfaces` which should be faster and will fix issue #2747
> Overpresure - Misc fixes

- addons/fcs/functions/fnc_keyUp.sqf
- addons/fcs/functions/script_component.hpp
Fix #2750
KeyUp can take a specific distance as 3rd arg when using pageUp/Down.
The hud's distance was only set in getRange with the rangefinder's raw text
> Update FCS display after distance adjust

- addons/common/XEH_postInit.sqf
- addons/interaction/XEH_postInit.sqf
- addons/interaction/functions/fnc_joinTeam.sqf
- addons/nametags/XEH_postInit.sqf
This PR removes all occurences of assignTeam since this will be handled by the next version of CBA, see CBATeam/CBA_A3#185. The call of the ACE event has also been replaced with the CBA event.
> Remove manual team synching

- addons/captives/functions/fnc_handlePlayerChanged.sqf
- addons/captives/functions/fnc_handleZeusDisplayChanged.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_showHud.sqf
- addons/interaction/functions/fnc_hideMouseHint.sqf
- addons/interaction/functions/fnc_showMouseHint.sqf
Replaces `Showhud` with a common setter, so settings don't get overwritten.
For the 1.50 command that takes arrays
for use in #1857
> Showhud setter

- extensions/CMakeLists.txt
- extensions/advanced_ballistics/AdvancedBallistics.cpp
- extensions/break_line/ace_break_line.cpp
- extensions/clipboard/ace_clipboard.cpp
- extensions/common/p3d/animation.cpp
- extensions/common/p3d/animation.hpp
- extensions/common/p3d/model.hpp
- extensions/common/p3d/model_info.hpp
- extensions/common/p3d/parser.hpp
- extensions/common/p3d/skeleton.hpp
- extensions/common/transform_matrix.hpp
- extensions/common/vector.hpp
- extensions/fcs/ace_fcs.cpp
- extensions/medical/medical.cpp
- extensions/parse_imagepath/ace_parse_imagepath.cpp
This pull requests mainly does:
* Pedantic errors are added as compiling flags in GNU C++ compiler.
* Removed redefinition of M_PI in "extensions/advanced_ballistics/AdvancedBallistics.cpp" (defined already in "shared.hpp")
* Removed pedantic errors. Mainly extra ';' in definition on namespaces and "extern C" lines.
> Removed pedantic errors and redefinition of M_PI variable

- tools/make.py
- Prints all failed modules when make has completed
- No longer prints green OK text if a single module fails
- Gives a count of how many modules have failed to build
This is done to prevent overlooking of a failed pbo in the build process, since there is a huge amount of modules being build.
> Add mention when make fails to build all pbos.

- addons/medical/ACE_Medical_Treatments.hpp
- addons/medical/functions/fnc_handleBandageOpening.sqf
- addons/medical/functions/fnc_treatmentAdvanced_bandageLocal.sqf
Should fix #2878
Gets the correct wound for the bandage treatment config
Used for selecting most effective bandage and reopening
_className was something like "velocityWoundMedium"
but configs only had base class "velocityWound"
Debug Output:
```
fnc_treatmentAdvanced_bandageLocal.sqf:44","OPENWOUND: :  _target=q1_1,  _x=[1,4,1,1,0.02]"]
fnc_treatmentAdvanced_bandageLocal.sqf:54","Could Not Find Wound Type trying base class - not minor/major/large:  _className=AvulsionsMedium"]
fnc_treatmentAdvanced_bandageLocal.sqf:66","Changed to: _className=Avulsions"]
fnc_treatmentAdvanced_bandageLocal.sqf:78","Wound classes: :  _specificClass=-1,  _classID=4"]
fnc_handleBandageOpening.sqf:44","Could Not Find Wound Type trying base class - not minor/major/large:  _className=AvulsionsMedium"] …
```
> Add all wound types to bandage treatment configs

- addons/laserpointer/functions/fnc_drawLaserpoint.sqf
- addons/laserpointer/functions/fnc_onDraw.sqf
- addons/laserpointer/functions/fnc_switchLaserLightMode.sqf
> cleanup laserpointer

- addons/medical/CfgVehicles.hpp
- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_addDamageToUnit.sqf
- addons/medical/functions/fnc_displayPatientInformation.sqf
- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_handleDamage_basic.sqf
- addons/medical/functions/fnc_handleDamage_caching.sqf
- addons/medical/functions/fnc_setDead.sqf
- addons/medical/functions/fnc_translateSelections.sqf
- addons/medical/functions/fnc_treatmentBasic_bandageLocal.sqf
- addons/medical/functions/fnc_treatment_success.sqf
- addons/overpressure/functions/fnc_fireLauncherBackblast.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- Armor: With the 1.54 protection update, as far as I can tell most man hitpoints have armor of 1 and the actually protection is done on the Uniform/Vest/Helmet.
- Translate selections back to hitpoints for a few of the weird VR people.
- Calc newDamage using hitIndex because multiple hitpoints map to the same selection so `getHit` might not be correct. (right now _newDamage could be weird or negative)
- Fix isFalling was never being reset. So once you took falling damage that would be all you could ever take.
- Fix #1859 by delaying `setDamage 1` when inside of a handleDamage so the killedEH doesn't trigger twice
fnc_translateSelections has a sort of ugly overload
> Medical Fixes

- addons/repair/CfgVehicles.hpp
Some helicopters have the main rotor point on the tip of a single blade which can be problematic depending on the orientation of the helicopter so those have been moved to the center (to match others). The tail rotor is also in the complete wrong position for some.
Also the turret of `B_APC_Tracked_01_AA_F` was unreachable. It should be noted that there are two turret hitpoints with the same name so they are both moved to the new position (the second was overlapping with a different hitpoint anyway though).
> Define custom repair points for a few vehicles

- addons/interact_menu/functions/fnc_renderActionPoints.sqf
- addons/nametags/functions/fnc_drawNameTagIcon.sqf
> Remove nametags and actions on hidden units

- addons/vehicles/XEH_postInit.sqf
- addons/vehicles/functions/fnc_speedLimiter.sqf
> fix that in UGV dont work speedLimiter

- addons/repair/functions/fnc_addRepairActions.sqf
Fix #2902
B_UAV_01_F has no hitpoints and would throw error
Don't exit so "fullRepair" action still gets added
> Remove error and don't exit if veh has no hit points

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_checkPBOs.sqf
> Remove Sleep/WaitUntil from checkPBO

- addons/medical/functions/fnc_handleBandageOpening.sqf
Fix #2921 
`_openWounds ` was always set but only broadcast if it also existed in the bandaged array.
But because array references, it was having local effects on `QGVAR(openWounds)`.
> Don't update openWounds if not bandaged

- addons/rearm/stringtable.xml
This PR removes two "Original" entries from stringtables so this:
Becomes this:
Making it easier to edit stringtables with Tabler :)
> remove Original entries

- addons/common/functions/fnc_serverLog.sqf
- addons/maptools/functions/fnc_handleMouseButton.sqf
Trivial Fix for
`Performance warning: SimpleSerialization::Read
'ace_common_remoteFnc' is using type of ,'TEXT' which is not optimized
by simple serialization, falling back to generic serialization, use
generic type or ask for optimizations for these types`
> Send string to serverLog instead of strucText

- addons/repair/stringtable.xml
- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
Put all ERA hitpoints (up to 46 of them) onto a single point
and put that point on the main interaction point
Should fix #2991
There were way to many interaction points, era hitpoints blocked the points behind them so it became impossible to access the main interaction point.
> RHS Compat - Combine all ERA Hitpoints

- addons/repair/ACE_Repair.hpp
- addons/repair/ACE_Settings.hpp
- addons/repair/functions/fnc_getPostRepairDamage.sqf
- addons/repair/functions/fnc_isEngineer.sqf
- addons/repair/functions/fnc_repair.sqf
Fix #2982
Now respects `GVAR(consumeItem_ToolKit)` setting. I made the `ace_setting` default off so as not to change expected behavior (module is default off).
For Release Branch
> Fix PostRepairDamage and toolkit consumtion setting

- addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf
Fix #3038
InteractiMenu now checks `isObjectHidden`,
So now use dummy object instead of hiding a real one
> Building Interact - Dummy object instead of hiding

- addons/optics/XEH_postInit.sqf
Fix broken ThreeDen Camera when returning to editor from preview.
PIP will still work in preview.
Will have to take a look at 1.56 RC to see if command exists and eventually cleanup.
> Optics - Don't modify camera for ThreeDen Editor

- addons/laser_selfdesignate/XEH_post_init.sqf
This is never defined. It's treated as undefined variable and errors in unsheduled environment.
> Remove undefined laser selfdesignate macro

- addons/medical/functions/fnc_handleCreateLitter.sqf
- addons/medical_menu/functions/fnc_onMenuOpen.sqf
- Medical Menu didn't close when target moved out of range
- Litter was always created in the same direction
> Fix medical menu not closing on range, litter dir

- wiki/feature/medical-system.md
Fixes some thing like quickclot on Avulsions is listed as `high` but `effectiveness = 0.2;`
Generated via the following code (Thanks to @aaco)
```
private _wounds = "true" configClasses (configfile >> "ACE_Medical_Advanced" >> "Injuries" >> "wounds");
{
private _config = _x;
_treatmentsDiaryBuilder = format ["%1", configName (_config)];
{
private _wound = configName _x;
private _woundName = getText (_x >> "name");
private _effectivenessNumber = getNumber (_config >> _wound >> "effectiveness");
private _effectivenessText = switch true do {
case (_effectivenessNumber >= 0.85): { "highest" };
case (_effectivenessNumber >= 0.65): { "high" };
case (_effectivenessNumber >= 0.45): { "medium" };
case (_effectivenessNumber >= 0.25): { "low" };
default { "lowest" };
};
_treatmentsDiaryBuilder = …
```
> Update bandage effectiveness on wiki

- addons/explosives/CfgAmmo.hpp
- addons/explosives/CfgVehicles.hpp
- addons/explosives/functions/fnc_interactEH.sqf
When merged this pull request will
* remove the invalid `ACE_offset` config entry (which was ported from AGM but was never used)
* reduce the interaction distance from 5 to 1, so as an EOD you really have to get close to the explosives to arm or defuse them
* move interaction points for some explosives to more logical positions
* add a config setting where to attach the defuse helper object (same place as the interaction point in most cases, but could be different for other (e.g. modded) explosives)
Pinging the [maintainers](https://github.com/acemod/ACE3/blob/master/addons/explosives/README.md#maintainers) @esteldunedain and @CorruptedHeart
> Explosive enhancements

- addons/medical/ui/triagecard.hpp
Fix #3087 
Somehow the space is removed between `GVAR(TriageCardTarget) setvariable` when pboProject evals the macros
wrapping with `()` fixes and works with both make.py and build.py builds
> Fix Medical Triagecard Macro

- addons/map/functions/fnc_determineMapLight.sqf
A simple oneliner for what seems to be an obvious typo.
According to the comment, the idea is to provide unobscured map when
inside an enclosed vehicle (`!isTurnedOut`).
> fix inverted isTurnedOut for map lighting

- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
New pull request to replace #3037 because I'm bad at Git (but apparently did was I was trying after but oh well)
---
This is a fix for the issue mentioned [here](https://forums.bistudio.com/topic/181341-ace3-a-collaborative-merger-between-agm-cse-and-ace/page-116#entry2950880) in the ACE thread.
Additionally the other commit disables ACE FCS on the M113 family... turned out gunner without a laser range finder and all that.
> RHS Compat fix for RU Sprut turret + Disabling FCS for M113 family

- optionals/compat_rhs_afrf3/CfgAmmo.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgAmmo.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
The RHS M249 and M240 now have the overheating and change barrel, plus
the M4 and M16 branch should have overheating applied to them. The ammo
class should have all of the hand grenade fixes in there.
> RHS Compat Enhancement for Weapons and Grenades  

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_isPlayer.sqf
Adds support for non-local zeus remote controlled units in isPlayer.
So this command will now work consistantly on any machine.
Uses a BIS setVar from the zeus module, had to add a disconnect handler to clear variable.
Slightly faster as well.
I think this is important for consistent behavior, for example wind deflection does:
`if (!([_unit] call EFUNC(common,isPlayer))) exitWith {false};`
Right now only the zeus would run the code, so the bullet's path won't appear consistent with it's effects.
> Add support for non local Zeus RC in common-isPlayer

- addons/common/XEH_postInit.sqf
- addons/interact_menu/XEH_clientInit.sqf
Close #2937
CBA now adds keyDown EH to zeus interface, so #1951 (CTRL+V from climb blocking paste in zeus) is back.
- Adds "isNotInZeus" to caninteractWith conditions.
- Removed code to forward interaction keybind to CBA  as this is handled by CBA
- Use `CBA_curatorOpened/Closed` events from CBA to trigger ACE's zeus event (trivial savings from removing constant checking in PFEH).
@commy2 - tested with this code and it seems to handle scripted closing fine.
```
[] spawn {sleep 2; systemChat "scipted closing zeus"; (findDisplay 312) closeDisplay 1};
```
> CBA zeus integration

- addons/spectator/functions/fnc_setSpectator.sqf
Should fix #2989
There is a race condition between these 4 PFEH and the "onUnload" event
in handleInterface.
If the PFEHs run first they will use nil variables and throw a script
error.
This sets them to nil immediately when exiting spectator
@SilentSpike - I'm not 100% sure this is the right way to fix, but it seems to work.
Debug of the race condition:
```
handleCamera Frame:35839 (normal)
end spectator Frame:35840
handleCamera Frame:35840 (throws error)
Error in expression ... File z\ace\addons\spectator\functions\fnc_handleCamera.sqf, line 35
Killing CamHandler in handleInterface: onunload Frame:35840
handleCamera Frame:35841 (exits cleanly)
```
> Kill Spectator PFEH when exiting spectator

- addons/medical/functions/fnc_actionPlaceInBodyBag.sqf
ref: #3021
`["placedInBodyBag", {systemChat str _this}] call ace_common_fnc_addEventhandler`
0: dead body
1: body bag object
executed on all machines
> add event for placing units in body bags

- tools/make.py
Replace #3028 (that was on release branch)
Close #1127
If the version (from main) changes, reset cache
Same effect as "force"
> Reset make.py Cache on new build version

- addons/overpressure/functions/fnc_fireLauncherBackblast.sqf
When calculating damage due to backblast reflection, we used the distance between the launcher and the obstacle behind it. However, we failed to acount the fact that backblast has to travel twice that distance before hitting the firer, hence spreading twice as much. Hence the exaggeration of reflection damage compared to direct damage to nearby soldiers.
Fix #2890
> Nerf the amount of backblast received by the firer via reflection

- addons/medical/XEH_postInit.sqf
Need to call this after settingInitalized for `GVAR(litterCleanUpDelay)` to be set correctly from module settings.  
From closed PR #2758 (not sure why I fixed it there)
> Move littler syncedEH install to after settingInit

- addons/explosives/XEH_preInit.sqf
- addons/explosives/functions/fnc_addDetonateActions.sqf
- addons/explosives/functions/fnc_addTransmitterActions.sqf
- addons/explosives/functions/fnc_detonateExplosiveAll.sqf
- addons/explosives/stringtable.xml
This PR will add an action to the detonator menu to detonate all explosives associated with it.
Example can be seen [here](http://i.imgur.com/oGUEKTl.jpg?1)
This fixes #2108 and will probably deprecate #1219.
> Add action to detonate all explosives on a detonator

- addons/spectator/XEH_postInit.sqf
- addons/spectator/XEH_preInit.sqf
- addons/spectator/functions/fnc_handleInterface.sqf
- addons/spectator/functions/fnc_interrupt.sqf
- addons/spectator/functions/fnc_setSpectator.sqf
<ul>
<li>Storing the display in a <code>uiNamespace</code> variable allows me to explicitly close the right display and hopefully fix the interface staying open upon mission end.<br/><br/>
@Commy2's theory is that perhaps when the main display <code>46</code> is killed upon mission end, <code>findDisplay</code> can't find the spectator display to close it because the game thinks it doesn't exist.</li>
<br/>
<li>That was also a minor oversight introduced in the fix for #2989, the icon handler is a mission event handler that isn't self terminating so the index needs to be preserved until after it is removed via <code>removeMissionEventHandler</code>. It is safe to let the <code>onUnload</code> event take care of that (and preferable so that icons disappear while temporarily closed).</li> …
> Fix some spectator errors

- addons/medical/ACE_Settings.hpp
- addons/medical/CfgVehicles.hpp
- addons/medical/functions/fnc_isInMedicalFacility.sqf
- addons/medical/functions/fnc_isInMedicalVehicle.sqf
- addons/medical/functions/fnc_isMedic.sqf
- addons/medical/functions/fnc_moduleMedicalSettings.sqf
- addons/medical/stringtable.xml
Close #1259
Part of Focus #3134
Adds a ace_setting to boost medical training (via `FUNC(isMedic)` check) in medical vehicles or facilities.
boost by one: untrained becomes medic, medic becomes doctor
> Medical Locations Boost Training

- addons/main/script_macros.hpp
`SLX_XEH_COMPILE` doesn't cache anymore, it had been updated to a new version that takes new params.
Pretty trivial, but important to know about or the file patching won't do what you think it will. 
ACE devs need to use put this in a mission description.ext
```
class CfgSettings {
class CBA {
class Caching {
compile = 0;
};
};
};
```
OR 
Add `#define DISABLE_COMPILE_CACHE` to the module's script component 
(or top of main/script_macros.hpp)
You NEED to use this method if you recompile functions mid-mission as the others use `compileFinal`
OR
Just add `cba_cache_disable.pbo` from optionals
PreInit goes from ~4.5 seconds to less than 0.3 (cuts mission SP Editor restart time in half)
> Use Function Caching in CBA

- addons/overpressure/CfgEventHandlers.hpp
- addons/overpressure/CfgWeapons.hpp
- addons/overpressure/functions/fnc_cacheOverPressureValues.sqf
- addons/overpressure/functions/fnc_fireLauncherBackblast.sqf
- addons/overpressure/functions/fnc_fireOverpressureZone.sqf
- addons/overpressure/functions/fnc_firedEHBB.sqf
- addons/overpressure/functions/fnc_firedEHOP.sqf
- addons/overpressure/functions/fnc_getDistance.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- addons/overpressure/script_component.hpp
- Cleanup, headers, modern privates
- Fix #3156 (`lineIntersectsSurfaces` did not filter ffv shooter)
- Added both a3 tank weapons, I am unsure why there were not already added.
> Overpressure cleanup and fix distance check

- addons/explosives/CfgVehicles.hpp
- addons/explosives/stringtable.xml
Move detonate actions from "Detonate" layer to "Explosives" layer and remove inconsistent ">>" from explosive actions.
Reasoning is that the amount of detonators that someone can reasonably be expected to carry isn't large enough to warrant an extra layer to the interaction menu.
> Clean up explosive interaction menu

- addons/hearing/functions/fnc_handleRespawn.sqf
Avoids resetting the `ACE_hasEarPlugsin` variable if gear should be preserved by the respawn module.
Fix #3180.
> Do not add or remove earplugs if gear should be preserved

- addons/scopes/functions/fnc_applyScopeAdjustment.sqf
Fixing an issue discussed in #3171, where, even if the scope is not set to allow adjustment in a particular axis, the click sound will still play and the adjustment turret will still be displayed.
> Scopes: Don't show adjustment or play click sound if the adjustment doesn't happen

- addons/javelin/functions/fnc_onOpticDraw.sqf
Fix #3175
`switchCamera` seems to break zeus RC of untis, resets control with `remotecontrol`
> Javelin - Fix zeus RC after switchCamera

- addons/explosives/XEH_preInit.sqf
- addons/explosives/functions/fnc_detonateExplosiveTrigger.sqf
- addons/explosives/functions/fnc_scriptedExplosive.sqf
This function is designed to wrap `ace_explosives_fnc_detonateExplosive` for use in triggers or scripts, to detonate explosives placed down in the editor.
> Function to detonate explosives via script

- wiki/development/coding-guidelines.md
Add more documentation for the coding guidelines.
1. Add design considerations
2. Add specifications on code structures, including logging and design
3. Add naming conventions.
This will still require more discussion and additional documentation to cover more cases.
Additionally we could write a checklist for reviewing PRs.
> Documented coding guidelines and standards for the ACE project

- wiki/development/branching-and-release.md
- wiki/development/merging-pull-requests.md
- wiki/user/information-center.md
The "Class names" page has changed to being written as two separate words (hyphenated in the URL).
Also, formatted the preamble questionnaire to resemble the FAQ lists that follow it.
> Docs: cleanup & maintenance

- addons/vehiclelock/functions/fnc_onOpenInventory.sqf
Fix #3166
Not sure when this broke,but delaying a frame seems to fix.
> Fix Vehicle inventory is not locked

- addons/fcs/functions/fnc_keyDown.sqf
- addons/fcs/functions/fnc_keyUp.sqf
Fix #3160
This should match behaviour in pre-3.4.2
> Add missing FUNC to FCS key (Rangefinders)

- addons/spectator/functions/fnc_stageSpectator.sqf
Possible fix for #2677
I think the core problem is that voiperr's demo mission does setSpectator before calling stage.
SetSpectator updates the unitList that has the player in it.
This PR is really just a bandAid that restarts the display when they are called out of order.
> Restart specatator display if player in unitList

- addons/common/CfgLocationTypes.hpp
- addons/common/config.cpp
- addons/frag/XEH_postInit.sqf
- addons/frag/functions/fnc_fired.sqf
Redo #3100 for master
If spall is not enabled (default) then calculate which ammo types will
actually cause a frag event, cache and then only track those.
before: `(#2): 0.0883651ms  - CODE: {_this call ace_frag_fnc_fired}`
after: `(#2): 0.0179289ms  - CODE: {_this call ace_frag_fnc_fired}`
More importantly this skips running frag simulation (tracking bullet position in a PFEH) for rounds that will never trigger a frag event.
Adds a `ACE_HashLocation` to `CfgLocationTypes` to common that should never be visible on the map (will still put it @ -10000, -10000)
> Frag - only run addPfhRound on ammo that will frag (for master)

- addons/interact_menu/XEH_clientInit.sqf
- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/functions/fnc_addActionToClass.sqf
- addons/interact_menu/functions/fnc_addActionToObject.sqf
- addons/interact_menu/functions/fnc_addMainAction.sqf
- addons/interact_menu/functions/fnc_collectActiveActionTree.sqf
- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_compileMenuZeus.sqf
- addons/interact_menu/functions/fnc_createAction.sqf
- addons/interact_menu/functions/fnc_ctrlSetParsedTextCached.sqf
- addons/interact_menu/functions/fnc_findActionNode.sqf
- addons/interact_menu/functions/fnc_handlePlayerChanged.sqf
- addons/interact_menu/functions/fnc_isSubPath.sqf
- addons/interact_menu/functions/fnc_keyDown.sqf
- addons/interact_menu/functions/fnc_keyUp.sqf
- addons/interact_menu/functions/fnc_render.sqf
- addons/interact_menu/functions/fnc_renderActionPoints.sqf
- addons/interact_menu/functions/fnc_renderBaseMenu.sqf
- addons/interact_menu/functions/fnc_renderIcon.sqf
- addons/interact_menu/functions/fnc_renderMenu.sqf
- addons/interact_menu/functions/fnc_renderSelector.sqf
- addons/interact_menu/functions/fnc_setupTextColors.sqf
- addons/interact_menu/functions/fnc_splitPath.sqf
- addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf
- addons/interact_menu/functions/fnc_userActions_getHouseActions.sqf
- addons/interact_menu/script_component.hpp
Privates, params (~8% speedup)
I implemented but left disabled a fix for #2196 (Distance in ACE_Action's sub-actions not respected) (https://github.com/acemod/ACE3/commit/ed4cc42897fb4b00e8b31dd68f4f80b3168946d5#diff-078fc18f72c95b3cad3e8fdf7fca9d48R38)
It's a big change because most things have been written assuming that gets ignored. 
We can cleanup our stuff, but we risk breaking compatibility with missions/other addons by turing it on.
> Cleanup Interaction Menu

- addons/vehiclelock/CfgMagazines.hpp
- addons/vehiclelock/CfgWeapons.hpp
Close #3215
Removes all the keys from the VA so they are not obtainable from magic VA boxes in missions.
> Remove VehicleLock Items from Virtual Arsenal

- extensions/parse_imagepath/ace_parse_imagepath.cpp
Added the correct preprocessor macro for parse_imagepath, so that the source can now be compiled on Linux.
> Added the correct preprocessor macro for parse_imagepath

- addons/realisticnames/CfgMagazines.hpp
Display name says M67, but DNS says RGO.
This is a fix for the above.
> Fix Handgrenade DisplayNameShort

- addons/fcs/functions/fnc_keyUp.sqf
Since the `in` operator is case sensitive, the FCS code sometimes doesn't enter the part where it checks if the weapon's `initSpeed` is different from 0.
This is BI's fault for not consistently capitalizing their magazine names.
> Fix FCS not taking weapon initSpeed into account in some circumstances

- addons/explosives/functions/fnc_defuseExplosive.sqf
- addons/explosives/functions/fnc_placeExplosive.sqf
* add 2 new events: `defuse` and `explodeOnDefuse`
* add `_unit` to place event
Can be tested with:
```sqf
["ace_explosives_place", {
hint format ["Placed:\nexpl: %1\nunit: %2", _this select 0, _this select 3];
}] call ace_common_fnc_addEventHandler;
["ace_explosives_defuse", {
hint format ["Defused:\nexpl: %1\nunit: %2", _this select 0, _this select 1];
}] call ace_common_fnc_addEventHandler;
["ace_explosives_explodeOnDefuse", {
hint format ["ExplodedOnDefuse:\nexpl: %1\nunit: %2", _this select 0, _this select 1];
}] call ace_common_fnc_addEventHandler;
```
> Explosive events, fix #3104

- addons/scopes/functions/fnc_adjustScope.sqf
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
This was first and foremost a data problem. Due to the way `ace_scopes_fnc_adjustScope` is coded,  `ACE_ScopeAdjust_VerticalIncrement` needs to be none zero to quit when adjusting isn't possible.
~~It would also be possible to make changes to that function to prevent this from happening when zero is provided. Should I do that too?~~ I just did, so it's possible to set increment to zero to disable adjusting in that direction without capturing keys.
Close #3238
> Fix ace_scopes capturing native adjustment keys for the PSO scope. 

- addons/dragging/functions/fnc_canCarry.sqf
- addons/dragging/functions/fnc_canDrag.sqf
- addons/dragging/functions/fnc_canDrop.sqf
- addons/dragging/functions/fnc_canDrop_carry.sqf
- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dragObject.sqf
- addons/dragging/functions/fnc_dragObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/dragging/functions/fnc_getWeight.sqf
- addons/dragging/functions/fnc_handleAnimChanged.sqf
- addons/dragging/functions/fnc_handleKilled.sqf
- addons/dragging/functions/fnc_handlePlayerChanged.sqf
- addons/dragging/functions/fnc_handlePlayerWeaponChanged.sqf
- addons/dragging/functions/fnc_handleScrollWheel.sqf
- addons/dragging/functions/fnc_handleUnconscious.sqf
- addons/dragging/functions/fnc_initObject.sqf
- addons/dragging/functions/fnc_initPerson.sqf
- addons/dragging/functions/fnc_isObjectOnObject.sqf
- addons/dragging/functions/fnc_setCarryable.sqf
- addons/dragging/functions/fnc_setDraggable.sqf
- addons/dragging/functions/fnc_startCarry.sqf
- addons/dragging/functions/fnc_startCarryPFH.sqf
- addons/dragging/functions/fnc_startDrag.sqf
- addons/dragging/functions/fnc_startDragPFH.sqf
- modern privates / params / headers
- functional changes in https://github.com/acemod/ACE3/commit/3f1d6ffeb73eb174331dad0585385f7a6a78a5a9
Fixes a critical bug we've seen a few times where a person or object being dragged will be teleported to a random location often in the middle of the ocean (which is not good if that person is unconscious :smile:).
Problem seems to be that `attachTo` has effects on getPos and distance for a few frames.
debug from ace_dragging_fnc_dragObject
```
attachTo [2709.28,6047.91,2.31902] @ 1946.34
tick [-2532.71,1995.72,4.07294] @ 1946.36
tick [-2532.71,1995.73,4.07294] @ 1946.38
tick [-2532.71,1995.73,4.07294] @ 1946.39
tick [-2532.71,1995.74,4.07294] @ 1946.41
tick [-2532.7,1995.74,4.07293] @ 1946.43
tick [2709.3,6047.94,2.31901] @ 1946.44
tick …
```
> Fix dragging moving object to random location

- addons/sandbag/CfgVehicles.hpp
As per #2633 
Make Sandbag available for placement in editor (Under Objects)
Also renames ACE_SandbagObject to ACE_Sandbag
> Add Sandbag to editor

- addons/movement/CfgMoves.hpp
I'm not sure when should this be merged.
Close #3188, Close #3260
> Remove Swag Walk Fix

- addons/medical/XEH_preInit.sqf
Fix #3168 - thanks to killzonekid for the idea
Not pretty but it does seem to fix the issue.  Possible this could cause some stutter when zeus is spawning new statics, but I didn't notice any real problems.
> Manually pre-load for StaticWeapons and Car

- addons/medical/functions/fnc_determineIfFatal.sqf
- addons/medical/functions/fnc_handleDamage.sqf
- addons/medical/functions/fnc_handleDamage_caching.sqf
- addons/medical/functions/fnc_setDead.sqf
Fix #3306
Fix #3269
Enemy RPG to MRAP (driver):
```
HD: [carrd,"",1,<NULL-object>,"",-1]
HD: [carrd,"",1,<NULL-object>,"",-1]
HD: [carrd,"",1,O Alpha 1-1:1,"R_PG32V_F",-1]
```
Enemy RPG to MRAP (gunner):
```
HD: [carrg,"",1,O Alpha 1-1:1 REMOTE,"R_PG32V_F",-1]
```
35m fall veh explodes (driver):
```
HD: [carrd,"",1,<NULL-object>,"",-1]
HD: [carrd,"",1,<NULL-object>,"",-1]
HD: [carrd,"",1,carrd,"",-1]
```
35m fall veh explodes (gunner):
```
HD: [carrg,"",1,carrd,"",-1]
```
So in crashes, the shooter/source can be the pilot for non-drivers.
Switching the order in determine if fatal will handle RPG shots that blow up vehicles as there doesn't seem to be any hit point damage.
> Fix vehicle crashes

- addons/interact_menu/functions/fnc_renderBaseMenu.sqf
Fix #3270
I don't dare reduce this much more. Sometimes units that fall unconscious might partially clip through objects; the threshold distance prevents those units from getting inaccessible.
Anyway, the reduction seems enough to avoid the bug in common cases.
> Slightly reduce the distance for which the LOS check is skipped. 

- addons/refuel/functions/fnc_canConnectNozzle.sqf
Have you ever did refuel at gas station with **engine on**?
> nozzle additonal check condition

- addons/interaction/functions/fnc_addPassengerActions.sqf
- addons/interaction/functions/fnc_addPassengersActions.sqf
Fix #1690 #3309
When interacting with vehicle passangers we collected all actions for all crew which was very expensive for large transports (>100ms stutter each second). This only collects the passenger actions for the selected crew member.
ace_interact_menu_fnc_collectActiveActionTree_counter: Average: 8.04395s / 1326 = 6.06632ms
vs
ace_interact_menu_fnc_collectActiveActionTree_counter: Average: 0.46582s / 1175 = 0.396443ms
> Only get passenger actions for selected unit

- addons/dragging/CfgVehicles.hpp
- addons/interact_menu/XEH_clientInit.sqf
Minor changes for CBA 2.3
Fix `Updating base class CBA_Extended_EventHandlers->, by z\ace\addons\dragging\config.cpp/CfgVehicles/ReammoBox_F/EventHandlers/CBA_Extended_EventHandlers/ `
And the interaction_menu debug isn't necessary anymore as XEH should be be guaranteed.
> Changes for CBA 2.3

- addons/common/CfgEden.hpp
- addons/common/config.cpp
- addons/medical/CfgEden.hpp
- addons/medical/config.cpp
- addons/medical/stringtable.xml
- addons/repair/CfgEden.hpp
- addons/repair/config.cpp
http://i.imgur.com/LXfNjDB.jpg //units
http://i.imgur.com/ad0qBLq.jpg //vehicles
http://i.imgur.com/j6S7Tmo.jpg //props
> Repair & medical object attributes for eden editor

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/grenades/functions/fnc_flashbangThrownFuze.sqf
1. Make sure the light effect is rendered even if the grenade explodes further than 20m from the player. This provides much better feedback that the grenade exploded, even if the player is not affected.
2. Increase the amount of hearing damage from the bang. Should work nicely with the new hearing overhaul.
3. Increase the maximum range for blinding effect to 25m, but with a higher-than-linear falloff. Close #1539.
4. Make units heavily affected by the blast turn away from the light, as per @bux578 request.
Bottom line, this should improve both the UX of throwing flashbangs and their effectiveness.
> Better flash effects

- addons/tacticalladder/CfgVehicles.hpp
- addons/tacticalladder/XEH_preInit.sqf
- addons/tacticalladder/functions/fnc_handleScrollWheel.sqf
- addons/tacticalladder/functions/fnc_isLadderEmpty.sqf
- addons/tacticalladder/functions/fnc_positionTL.sqf
- addons/tacticalladder/stringtable.xml
Fixes #3077 
Somewhat hacky workaround, but it works quite reliably. Also disabled tilting because it's broken in many ways (unsuitable animation, ladder sinks into the ground, interaction point is completely offset) and with that also split the string for adjusting mouse hint.
> Prevent Tactical Ladder interaction if unit on ladder

- addons/parachute/CfgVehicles.hpp
Source: http://www.globalsecurity.org/military/systems/aircraft/systems/mc-5.htm
> The system's **identical main and reserve parachutes**, which can be interchanged, are 370 square feet, seven-celled, and are manufactured from 1.1 ounce F-111 nylon ripstop fabric.
MC-5 was steerable in ACE2 and I think we are simulating it here too right? There are non-steerable and steerable reserve parachutes but MC-5 has two identical chutes.
Also this fix makes so you don't magically stop while freefalling as it is with NonSteerable_Parachute_F.
I was able to open it 20 meters above ground cause all my falling speed is gone as soon as I click open parachute. Thats BS.
This fixes that.
Also MC-5 in RL, very similiar to A3 one right?
> Make reserve steerable

- addons/advanced_ballistics/functions/fnc_calculateBarrelLengthVelocityShift.sqf
- addons/advanced_ballistics/functions/fnc_readAmmoDataFromConfig.sqf
- optionals/compat_rhs_afrf3/CfgAmmo.hpp
Fix #3062
- Add basic AB configs for subsonic Russian bullets.
- When building ab ammo cache, if round is subsonic and does not have AB
configured attempt to use the parent's config, scaled down to the subsonic's round
speed.
Without this, AB would use the parents muzzle velocity which broke the sights
and more importantly it causes the silent bullet to still have normal speed/damage.
Linear scaling probably isn't going to be perfect, but it should be much closer than using the unmodified parent config; this will also put a warning in rpt (only once per game because this is all cached).
> AB - Handle subsonic ammo when configs not defined

- addons/rearm/XEH_postInit.sqf
- addons/rearm/functions/fnc_addRearmActions.sqf
- addons/rearm/functions/fnc_canRearm.sqf
- addons/rearm/functions/fnc_canStoreAmmo.sqf
- addons/rearm/functions/fnc_canTakeAmmo.sqf
- addons/rearm/functions/fnc_createDummy.sqf
- addons/rearm/functions/fnc_dropAmmo.sqf
- addons/rearm/functions/fnc_getConfigMagazines.sqf
- addons/rearm/functions/fnc_getMaxMagazines.sqf
- addons/rearm/functions/fnc_getNeedRearmMagazines.sqf
- addons/rearm/functions/fnc_grabAmmo.sqf
- addons/rearm/functions/fnc_handleKilled.sqf
- addons/rearm/functions/fnc_handleUnconscious.sqf
- addons/rearm/functions/fnc_makeDummy.sqf
- addons/rearm/functions/fnc_moduleRearmSettings.sqf
- addons/rearm/functions/fnc_pickUpAmmo.sqf
- addons/rearm/functions/fnc_rearm.sqf
- addons/rearm/functions/fnc_rearmEntireVehicle.sqf
- addons/rearm/functions/fnc_rearmEntireVehicleSuccess.sqf
- addons/rearm/functions/fnc_rearmEntireVehicleSuccessLocal.sqf
- addons/rearm/functions/fnc_rearmSuccess.sqf
- addons/rearm/functions/fnc_rearmSuccessLocal.sqf
- addons/rearm/functions/fnc_storeAmmo.sqf
- addons/rearm/functions/fnc_takeAmmo.sqf
- addons/rearm/functions/fnc_takeSuccess.sqf
- addons/rearm/script_component.hpp
Fixes the problem reported in #3242 with `setVehicleAmmo`
Also updates `params` with default values and datatypes
> Fixing setVehicleAmmo for rearm

- addons/explosives/functions/fnc_addDetonateActions.sqf
- addons/explosives/functions/fnc_onIncapacitated.sqf
- addons/explosives/stringtable.xml
Allows connecting explosives in inventory that work with the dead man switch (Satchel/Demo/IED but not mines).  Will trigger when killed/incapacitated or manually tirggered.
AKA "Suicide vest".
> Deadman switch - trigger explosives in inventory

- addons/laser_selfdesignate/CfgVehicles.hpp
- addons/missileguidance/CfgAmmo.hpp
- addons/missileguidance/CfgWeapons.hpp
As discussed with @Glowbal on slack, an intermediary change to fix the DAGR missile on both Comanche and Ka-60 Kasatka Helicopter.
[Demo](https://www.youtube.com/watch?v=nzmm5ExG_14)
Allow laserLock, set weaponLockSystem to Laser and move class ADDON to ACE_Hydra70_DAGR so it can be further tested on e.g. ACE_Comanche.
> Disable ACE_Laser for choppers (aka Changes to DAGR)

- addons/laser_selfdesignate/functions/fnc_findLaserSource.sqf
- addons/laser_selfdesignate/functions/fnc_initDesignatorActions.sqf
- addons/laser_selfdesignate/functions/fnc_laserHudDesignateOff.sqf
- addons/laser_selfdesignate/functions/fnc_laserHudDesignateOn.sqf
- addons/laser_selfdesignate/functions/fnc_unitTurretHasDesignator.sqf
Code Cleanup laser Self Designate Module.
> Code Cleanup laser Self Designate Module

- tools/make.py
- Fix possible undefined variable error when make.py exits before builds (`amountOfBuildsFailed` and `namesOfBuildsFailed` were getting initialized inside the if statement, but used outside)
- Rename `aceVersion` to `project_version` for consistency
- Update version check regex from CBA (could throw errors in edge-case PBO names)
> Fix make.py undefined variable and regex

- addons/medical/functions/fnc_treatment_failure.sqf
- addons/medical/functions/fnc_treatment_success.sqf
- addons/repair/functions/fnc_repair_failure.sqf
- addons/repair/functions/fnc_repair_success.sqf
`typeof (missionNamespace getVariable "")` = "EmptyDetector"
causes
```
Error call: Type Object, expected code
File z\ace\addons\repair\functions\fnc_repair_failure.sqf, line 46
```
> Fix empty callbacks in medical/repair

- addons/ballistics/CfgWeapons.hpp
- addons/flashsuppressors/CfgWeapons.hpp
Fix #3344 ?
I don't really know the JR stuff that well, but this seems to fix.
Should we switch other things to use the `compatibleItems` class instead of array?
> Add flashsupressor to asdg_MuzzleSlot_338

- addons/logistics_uavbattery/stringtable.xml
- addons/logistics_wirecutter/stringtable.xml
- addons/magazinerepack/stringtable.xml
- addons/medical/stringtable.xml
- addons/overheating/stringtable.xml
- addons/rearm/stringtable.xml
- addons/refuel/stringtable.xml
- addons/reload/stringtable.xml
- addons/reloadlaunchers/stringtable.xml
- addons/repair/stringtable.xml
- addons/respawn/stringtable.xml
- addons/vehiclelock/stringtable.xml
- addons/weather/stringtable.xml
Every occurance of `...` in stringtables now has a leading space. The leading space was chosen in favour of no leading space because the latter was less used.
> Unified ellipsis

- meta.cpp
1. Add protocol version to meta.cpp file. Without protocol version line Arma 3 Server ignores publishedid attribute and it won't propagate it to the client / Launcher.
> Add protocol version to meta.cpp

- addons/main/config.cpp
- addons/main/script_macros.hpp
Fix 
```
Attempt to override final function - slx_xeh_compile_new
```
Commy I'm almost positive this can be removed, just wanted to check.
> Cleanup old cba SLX_XEH_COMPILE_NEW code

- addons/cargo/menu.hpp
1. Fix #3334 
2. Fix cargo menu cut off `g`
3. Replace Purista font with Roboto in cargo menu (the rest shall be done in the next version to not break anything - #3401 )
> Fix #3334 replace Purista with Roboto in cargo menu

- addons/cargo/XEH_postInit.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/cargo/menu.hpp
1. Fix #3363 
2. Make sure `hideObjectGlobal` is executed before `setPosATL` by executing both on server, to ensure lamps will get rendered correctly
> Fix lamp unloading

- addons/captives/CfgEden.hpp
- addons/captives/functions/fnc_moduleHandcuffed.sqf
- addons/captives/functions/fnc_moduleSurrender.sqf
- addons/medical/CfgEden.hpp
- addons/medical/stringtable.xml
- addons/repair/CfgEden.hpp
Fix the 3den attributes
- Captives: expression only runs on server, so when checked on a remote unit it has no effect and throws
```
[z\ace\addons\captives\functions\fnc_setSurrendered.sqf:23] -ERROR- ERROR running surrender on remote unit
```
Replace with `FUNC(moduleHandcuffed) which handles it.
- Replace the broken `comboBox` control with custom ones for medical/repair. Looks nicer imho
- Replace all setVariables with the public version
> Fix 3den attributes

- addons/common/CfgLocationTypes.hpp
- addons/common/HintConfig.hpp
- addons/common/define.hpp
- addons/dagr/Dialog.hpp
- addons/dagr/RscTitles.hpp
- addons/finger/functions/fnc_perFrameEH.sqf
- addons/frag/functions/fnc_drawTraces.sqf
- addons/goggles/define.hpp
- addons/huntir/Dialog.hpp
- addons/huntir/RscTitles.hpp
- addons/interaction/RscTitles.hpp
- addons/map/MapTweaks.hpp
- addons/map_gestures/functions/fnc_drawMapGestures.sqf
- addons/medical/ui/RscTitles.hpp
- addons/medical/ui/triagecard.hpp
- addons/medical_menu/ui/menu.hpp
- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- addons/optionsmenu/gui/define.hpp
- addons/optionsmenu/gui/pauseMenu.hpp
- addons/optionsmenu/gui/settingsMenu.hpp
- addons/scopes/RscTitles.hpp
1. Replaces Purista with Roboto
2. Everywhere
> Replace Purista with Roboto - everywhere

- addons/captives/stringtable.xml
- addons/finger/CfgVehicles.hpp
- addons/microdagr/stringtable.xml
- addons/sitting/CfgVehicles.hpp
- addons/vehiclelock/stringtable.xml
1. Closes #2561
2. Remove `Source: <pboname>.pbo` from captives, microdagr and vehiclelock, only those had it and that should be on the documentation pages, it has no direct meaning for the mission maker.
3. Add missing finger module on-hover description.
> Cleanup some module descriptions

- addons/cargo/XEH_postInit.sqf
- addons/cargo/functions/fnc_startLoadIn.sqf
- addons/cargo/functions/fnc_startUnload.sqf
1. Reimplement the `[object, vehicle]` syntax for arguments as it initially was and as it is documented
Those events are considered public API, that's why I am tagging this with "Bug fix".
> Reimplement old parameter syntax for (Un)LoadCargo events

- addons/medical/functions/fnc_handleDamage.sqf
Add registration of the latest damage source.
Systems like ALiVE depend on the killed event handler to provide them with the source of whatever killed a unit. Since we are using `setDamage`, this source is always objNull. 
The goal of this PR is to introduce a solution that allows third party mods to do kill count registration without to much complication.
> Add registering last damage source

- addons/map/ACE_Settings.hpp
- addons/map/CfgVehicles.hpp
- addons/map/functions/fnc_blueForceTrackingModule.sqf
- addons/map/functions/fnc_blueForceTrackingUpdate.sqf
- addons/map/stringtable.xml
1. Add an option to the "Blue Force Tracking" module that will show individual players names instead of their group IDs, defaults to false.
> Added Show Player Names option to Blue Force Tracking Module

- addons/nametags/functions/fnc_onDraw3d.sqf
1. Fix error in nametags when a player disconnects due to object being null.
> Fix error in nametags when a player disconnects

- addons/fastroping/stringtable.xml
1. Translate fastrope module to French
2. FRIES was kept in English as it is a specific technologic term (seen with BaerMitUmlaut)
Equiper le FRIES
Equipe les hélicoptères compatibles avec un Fast Rope Insertion Extraction System.
Préparer le système de corde lisse
Déployer les cordes
Descendre à la corde
Détacher les cordes
Equiper l'hélicoptère avec le FRIES
Equipe l'hélicoptère sélectionné avec un Fast Rope Insertion Extraction System
> Fastrope French translation

- addons/interact_menu/functions/fnc_keyDown.sqf
- addons/interact_menu/functions/fnc_render.sqf
These is about two usability problems that happen in the IM while self interacting:
1. There are corner cases in which the interact menu collapses back to the action point while you try to select subactions while the expand animation is not complete. This makes lower speed animations a pain to use, specially if your are trying to be fast. This is visible in the video starting at time=6s
2. For slow animation speeds, the "Self Interact" opion doesn't auto expand instantly. That leads to the menu not expanding at all if you try to move the mouse to the right too quickly, That is visible in the video multiple times
**Video Before**:
https://youtu.be/dM18AVn-Yw8
**Video After**:
https://youtu.be/a7LcJgGKKL0
The issues described above happen both for the 3d and the cursor modes of the menu. …
> Prevent Self Interact Menu from bugging out during animations

- addons/repair/CfgEventHandlers.hpp
Don't throw error when createing fast rope helper.
> Don't try adding repair actions to fastrope helper

- wiki/missionmaker/mission-tools.md
- wiki/missionmaker/modules.md
Reverts acemod/ACE3#3271
[reason](https://github.com/acemod/ACE3/pull/3107#issuecomment-190926960)
> Revert "Add Headless module and mission tools documentation"

- addons/fastroping/stringtable.xml
Fixed wrong tag in Spanish Translation of Fast Rope module.
> Spanish translation of FastRope fixed

- addons/common/functions/fnc_addScrollWheelEventHandler.sqf
- addons/common/init_handleModifierKey.sqf
- addons/dragging/CfgEventHandlers.hpp
- addons/dragging/XEH_missionDisplayLoad.sqf
- addons/dragging/XEH_postInit.sqf
- addons/explosives/CfgEventHandlers.hpp
- addons/explosives/XEH_missionDisplayLoad.sqf
- addons/explosives/XEH_postInit.sqf
- addons/interaction/CfgEventHandlers.hpp
- addons/interaction/XEH_missionDisplayLoad.sqf
- addons/interaction/XEH_postInit.sqf
- addons/sandbag/CfgEventHandlers.hpp
- addons/sandbag/XEH_missionDisplayLoad.sqf
- addons/sandbag/XEH_postInit.sqf
- addons/tacticalladder/CfgEventHandlers.hpp
- addons/tacticalladder/XEH_missionDisplayLoad.sqf
- addons/tacticalladder/XEH_postInit.sqf
- addons/trenches/CfgEventHandlers.hpp
- addons/trenches/XEH_missionDisplayLoad.sqf
- addons/trenches/XEH_postInit.sqf
- addons/tripod/CfgEventHandlers.hpp
- addons/tripod/XEH_missionDisplayLoad.sqf
- addons/tripod/XEH_postInit.sqf
- Deprecate `EFUNC(common,addScrollWheelEventHandler)`
- Use `MouseZChanged` instead of `EFUNC(common,addScrollWheelEventHandler)`
- Fixes part of #3499 
Needs some testing to make sure it all works.
Also make sure to test with `ACE_Modifier = 1` as that has it's own problems.
> Replace addScrollWheelEventHandler with MouseZChanged Display EH

- README.md
- docs/README_DE.md
- docs/README_PL.md
- Remove "Download" badge from README.md (plus DE and PL versions)
- "Version" badge links to release page anyways
- Less stuff to maintain == more development time
> Remove download badge

- addons/backpacks/functions/fnc_isBackpack.sqf
- Revert change in `params` in #3125
- Allow string input in `isBackpack` function again
- Restores compatibility, this is a public function
> Allow string input for isBackpack

- addons/captives/XEH_postInit.sqf
Fix #3532 
Thanks to @Theowningone for spotting problem.
> Fix captivity system on dedicated

- addons/map/functions/fnc_blueForceTrackingUpdate.sqf
1. Fix player markers not showing up correctly in multiplayer when BFT_ShowPlayerNames is enabled
> Fix for player markers not showing up correctly with BFT_ShowPlayerNames

- addons/common/functions/fnc_fixPosition.sqf
- addons/dragging/functions/fnc_handleScrollWheel.sqf
Fix #3486
- Set "house" type objects to have a `getPos` hegiht of 0.
- Also update `carryDirection` after each re-attach from mouse wheel scrolling
> Fix portable light floating / dir when carrying

- addons/explosives/CfgVehicles.hpp
- Increase interaction distance with explosives from 1m to 1.5m. 
- Fix #3379
It's a nice usability enhancement, that makes placing explosives quicker and more streamlined.
> Increase interaction distance with explosives from 1m to 1.5m. 

- addons/common/XEH_postInit.sqf
- addons/refuel/XEH_postInit.sqf
- addons/refuel/functions/fnc_checkFuel.sqf
- addons/refuel/functions/fnc_connectNozzleAction.sqf
- addons/refuel/functions/fnc_refuel.sqf
- addons/refuel/functions/fnc_reset.sqf
- addons/refuel/functions/fnc_returnNozzle.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
- Closes #3541 
- Replaces all `execRemoteFnc` with `globalEvent` or `objectEvent`
- Increases refuel PFH to every 1 second (refuel rate stays the same as it's part of the pre-PFH calculation)
- Add `setVectorDirAndUp` and `setHitPointDamage` functions to common (both require object to be local)
Tagging @GitHawk for review. Tested locally only.
> Replace execRemoteFnc with events and increase fuel update delay in refuel

- addons/inventory/XEH_postInit.sqf
- addons/inventory/XEH_preInit.sqf
- addons/inventory/functions/fnc_forceItemListUpdate.sqf
- Use a CBA namespace for storing item configs by gui information
- fixes a bug where variables would not be defined when loading a savegame without ever loading a mission from start during the session
> use namespace for cargo filters, fixes problem with save games

- addons/explosives/functions/fnc_handleScrollWheel.sqf
- addons/explosives/stringtable.xml
- addons/interaction/functions/fnc_hideMouseHint.sqf
- addons/interaction/functions/fnc_showMouseHint.sqf
- addons/sandbag/functions/fnc_handleScrollWheel.sqf
- addons/sandbag/stringtable.xml
- addons/tacticalladder/functions/fnc_handleScrollWheel.sqf
- addons/trenches/functions/fnc_handleScrollWheel.sqf
- addons/trenches/stringtable.xml
- Allow scripted UI when using `showMouseHint` and `hideMouseHint`
- Remove `ACE_Modifier` requirement for rotating sandbags, tactical ladders, explosives and trenches
> Disable only action menu on mouse hint and modifier where unnecessary

- addons/explosives/XEH_PREP.hpp
- addons/explosives/XEH_missionDisplayLoad.sqf
- addons/explosives/functions/fnc_cancelPlacement.sqf
- addons/explosives/functions/fnc_setupExplosive.sqf
- addons/sandbag/XEH_missionDisplayLoad.sqf
- addons/sandbag/functions/fnc_deploy.sqf
- addons/sandbag/functions/fnc_deployCancel.sqf
- addons/sandbag/functions/fnc_deployConfirm.sqf
- addons/tacticalladder/XEH_missionDisplayLoad.sqf
- addons/tacticalladder/functions/fnc_cancelTLdeploy.sqf
- addons/tacticalladder/functions/fnc_confirmTLdeploy.sqf
- addons/tacticalladder/functions/fnc_positionTL.sqf
- addons/trenches/XEH_missionDisplayLoad.sqf
- addons/trenches/functions/fnc_placeCancel.sqf
- addons/trenches/functions/fnc_placeConfirm.sqf
- addons/trenches/functions/fnc_placeTrench.sqf
- FIxes "Cancel" action which is right mouse button when placing things
~~**Untested** (no access to Arma-capable machine at the moment)~~
> Fix Cancel (RMB) Action

- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/functions/fnc_addActionToClass.sqf
- addons/interact_menu/functions/fnc_addMainAction.sqf
- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_removeActionFromClass.sqf
- addons/interact_menu/functions/fnc_renderActionPoints.sqf
- addons/interaction/functions/fnc_addPassengerActions.sqf
- Store action menues in CBA pseudo namespaces instead of `format`ed mission namespace variables
- I can't reproduce the save game crash with this anymore
- I don't know why though, so don't close the issue for now (requires feedback)
ref #3397, #1098
> Store Interact Menus on CBA Namespaces

- addons/medical/functions/fnc_treatmentAdvanced_medicationLocal.sqf
> Fix empty callback for hr adjustment

- addons/sandbag/CfgVehicles.hpp
Apparently `side = -1` will show in 2d, but not 3d.
ref #3102 #2633
> Set sandbag side to civ to show in 3den

- addons/concertina_wire/CfgVehicles.hpp
- addons/dragging/CfgVehicles.hpp
- addons/explosives/CfgAmmo.hpp
- addons/fastroping/CfgVehicles.hpp
- addons/medical/CfgVehicles.hpp
- addons/repair/CfgVehicles.hpp
- addons/sitting/CfgVehicles.hpp
- addons/spottingscope/CfgVehicles.hpp
- addons/tripod/CfgVehicles.hpp
- addons/zeus/config.cpp
Standardize grammar of GVAR arrays in configs to place the square brackets outside the GVAR macro.
This prevents any possible confusion when the GVARs are used in code.
Put in 3.6.0 for absolute lack of priority, but no reason it can't be merged earlier.
> Standardize GVAR array brackets in configs.

- addons/dragging/CfgVehicles.hpp
- Disable drag and carry for StaticCannon
In RHS this covers M119 (2000 kilos) and the D-30A (3000 kilos)
Close #3528
> Disable drag and carry for StaticCannon

- addons/fastroping/CfgEventHandlers.hpp
- addons/fastroping/CfgVehicles.hpp
- addons/fastroping/XEH_PREP.hpp
- addons/fastroping/XEH_postInit.sqf
- addons/fastroping/XEH_preStart.sqf
- addons/fastroping/data/model.cfg
- addons/fastroping/functions/fnc_canCloseRamp.sqf
- addons/fastroping/functions/fnc_canPrepareFRIES.sqf
- addons/fastroping/functions/fnc_cutRopes.sqf
- addons/fastroping/functions/fnc_deployRopes.sqf
- addons/fastroping/functions/fnc_fastRope.sqf
- addons/fastroping/functions/fnc_fastRopeLocalPFH.sqf
- addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- addons/fastroping/functions/fnc_onCutCommon.sqf
- addons/fastroping/functions/fnc_onPrepareCommon.sqf
- Use the `preStart` XEH in fastroping
- Fix a major bug with multiple people fastroping simultaneously
- Add a hiding animation for either of the gantrys from the gantry type FRIES (#3475)
- Force ramps from vanilla helicopters open when fastroping
- Improve rope twitching and glitchyness *a lot*, additionally ropes no more break when flying too fast
- Fix a config change which broke all fastroping interactions
For some reason, the FRIES on the Wildcat is now completly misaligned on my machine. I didn't change anything in the model and have a feeling this is a problem on my side.
Also needs testing, please mark as WIP.
> Fastroping: post-release enhancements

- optionals/compat_rhs_afrf3/CfgEventHandlers.hpp
- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_afrf3/XEH_PREP.hpp
- optionals/compat_rhs_afrf3/XEH_preInit.sqf
- optionals/compat_rhs_afrf3/XEH_preStart.sqf
- optionals/compat_rhs_afrf3/config.cpp
- optionals/compat_rhs_afrf3/functions/fnc_onCut.sqf
- optionals/compat_rhs_afrf3/functions/fnc_onPrepare.sqf
- optionals/compat_rhs_afrf3/functions/script_component.hpp
- optionals/compat_rhs_afrf3/script_component.hpp
- optionals/compat_rhs_usf3/CfgEventHandlers.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/XEH_PREP.hpp
- optionals/compat_rhs_usf3/XEH_preInit.sqf
- optionals/compat_rhs_usf3/XEH_preStart.sqf
- optionals/compat_rhs_usf3/config.cpp
- optionals/compat_rhs_usf3/functions/fnc_canCloseDoor.sqf
- optionals/compat_rhs_usf3/functions/fnc_onCut.sqf
- optionals/compat_rhs_usf3/functions/fnc_onPrepare.sqf
- optionals/compat_rhs_usf3/functions/script_component.hpp
- optionals/compat_rhs_usf3/script_component.hpp
1. Add fastroping compatibility to the UH-60, CH-47, UH-1Y and Mi-8 Helicopters. Note that only the Mi-8 variants without a door gunner are supported.
2. ~~***Not work as of right now.***  
For some reason, the `ARR_2` macros do not resolve properly, and I need some help because I have no idea why.
For example `condition = QUOTE([ARR_2(this,'doorRB')] call FUNC(canCloseDoor));` resolves to `condition="[this";` which is obviously not correct.~~  
Works now, the issue were outdated Mikero tools.
> RHS Fastroping compatibility

- addons/refuel/functions/fnc_canTurnOn.sqf
- addons/refuel/functions/fnc_refuel.sqf
Extending #2954 by disallowing refueling with a running engine in both canTurnOn and the refuel PFH
> Disallow refueling with running engine

- addons/common/functions/fnc_checkFiles.sqf
- addons/main/config.cpp
- addons/main/script_mod.hpp
Will require https://github.com/CBATeam/CBA_A3/pull/290/
> Add CBA 2.3.1 to versioning check

- addons/interact_menu/XEH_preInit.sqf
ref: #1098
I have to set them to 0, because `ACE_diagTime` is still the value from the previous session and `execNextFrame` fails, because it relies on `GVAR(nextFrameNo)` (from common) which isn't refreshed either.
> reset interaction menu time variables on save game load

- addons/common/XEH_postInit.sqf
- Add alive _unit to the conditions required for interaction
- Prevent the interaction menu from being accessible while dead
- Prevent all keybinded actions from executing while dead (e.g. check ammo)
- Close #2900
> Add alive _unit to the conditions required for interaction

- addons/main/config.cpp
Trivial fix for mikero's dll 5.24 converting "true" to 1 in arrays, which will now causes minor rpt warning on cba dev build
> Fix versioning true when compiled

- addons/tagging/functions/fnc_tagTestingThread.sqf
- Replace usage of `ace_common_fnc_filter` in tagging component with `select CODE`
- Remove the last trace of `ace_common_fnc_filter` usage
> Replace usage of filter to select in tagging

- addons/fastroping/XEH_postInit.sqf
- addons/fastroping/functions/fnc_cutRopes.sqf
- addons/fastroping/functions/fnc_deployRopes.sqf
- addons/fastroping/functions/fnc_fastRopeLocalPFH.sqf
- addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- Revert a commit that broke the system after the first unit has fastroped
The bug is probably caused by the new way of resetting the helper. For 3.6.0 we could test deleting and recreating the "dummy" object, which is what AGM did.
> Revert the "Improve rope glitchyness" commit

- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- Fix nametag error popup
`rank` seems like it can return `""` right as unit is respawning.
```
Rank qq_1 is [LIEUTENANT]
Rank qq_1 is []
Rank qq_1 is [LIEUTENANT]
```
This might be a side-effect from using cachedCall to get all near men?
> Fix nametag error when rank is empty string

- addons/fastroping/XEH_postInit.sqf
- addons/fastroping/functions/fnc_cutRopes.sqf
- addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- Fix a network race condition that broke fastroping and got people stuck in mid air
- Fix ropes not properly detaching when cut
---
**Details on the network race condition that occured:**
Expected order on commands ran was:
- player gets moved out of the helicopter
- server PFH runs once, starts ropes unwinding
- player changes animation
- nothing really happens until the fast rope is done
What happened sometimes was:
- player gets moved out of the helicopter
- server PFH does *not* run in between here
- player changes animation
- server skips the ropes unwinding command
- ropes are stuck, player is stuck
The condition was changed and the rope unwinding command is now guaranteed to run once, which gets rid of the issue.
> Fixed fastroping race condition

- addons/advanced_ballistics/functions/fnc_displayProtractor.sqf
- Improve accuracy of the protractor display. The movement is now linear with the sin of the angle instead of the angle itself, to account for the distorsion in the dial.
- Close #3606
For best results, the needle should match the center of the numbers in the dial.
> Greatly improve the accuracy of the protractor display

- addons/medical/functions/fnc_handleDamage_caching.sqf
- Filter minor falling damage to non-leg hitpoints
With basic medical, a short fall will often cause bleeding from all 6 hitpoints, this increase the threshold for non-leg hitpoints to actually take damage from falls.
> Filter minor falling damage to non-leg hitpoints

- addons/explosives/functions/fnc_scriptedExplosive.sqf
- make FUNC(scriptedExplosive) work in scheduled env
- add option to directly add one explosive as object for convenience
the alternative syntax can do stuff like:
`_bomb call ace_explosives_fnc_scriptedExplosive`
(as well as:
`[_bomb] call ace_explosives_fnc_scriptedExplosive`
`[[_bomb]] call ace_explosives_fnc_scriptedExplosive`)
which is way easier on the eyes compared to:
`[[_bomb]] call ace_explosives_fnc_scriptedExplosive`
> make FUNC(scriptedExplosive) work in scheduled env, ref #3621

- addons/common/CfgEventHandlers.hpp
- addons/common/functions/fnc_setName.sqf
- addons/common/script_component.hpp
- artificially delay the FUNC(setName) to fix RPT spam
- fix nametags not working with zeus / alive spawned units
- close: #3622
- remove some commented out code
Should be noted that this worked before 1.56. The name was set on init, at least on local units. Not anymore. ~~The one second is arbitrary.~~ I spawned 1000 units and got no complaints in the RPT. `FUNC(setName)` itself is safe to be delayed and doesn't actually require a local unit.
> fix FUNC(setName) for Zeus and alive spawned units

- addons/advanced_ballistics/XEH_postInit.sqf
- addons/advanced_ballistics/functions/fnc_initializeTerrainExtension.sqf
Fix Terrain processor never running
- `FUNC(initializeTerrainExtension)` was called at postInit, before modules are read so `GVAR(enabled)` would be false
- `#endIf` - That capital I breaks everything with arma preProcessor. `ace_advanced_ballistics_fnc_initializeTerrainExtension` was compiling to just `{}`
> Fix AB Terrain Extension

- addons/zeus/functions/fnc_addObjectToCurator.sqf
- Fixes a `createVehicle` vehicle not always being added to zeus when on dedicated server.
Not sure why this is needed, but when using something like:
`"I_G_Offroad_01_repair_F" createVehicle getpos (allUnits select 0);`
on a dedicated server, the vehicle is not always added to zeus, delaying a frame seems to fix.
> Delay calling addCuratorEditableObjects for a frame

- addons/tagging/functions/fnc_createTag.sqf
- Throw a globalEvent when a tag is created. Useful for mission makers.
- Close #3521.
Parameters are:
```
0: Tag object, which can be used to get the position, orientation, etc <OBJECT>
1: Color ("black", "red", "green", "blue") <STRING>
2: Object that was tagged (objNull if it was the floor) <OBJECT>
3: Unit that created the tag <OBJECT>
```
@bux578, will you handle documentation?
> Throw a globalEvent when a tag is created. 

- wiki/development/setting-up-the-development-environment.md
- Always use junctions in manual setup instructions
- Complements #3652
> Always use junctions for manual setup on wiki

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
Due to https://github.com/CBATeam/CBA_A3/pull/303
PFEH will be run between preInit and postInit, so the "playerChanged" event happens before most event handlers are installed in postInit.
This breaks noRadio, and other things that count on the `playerChanged` event always happening.
> Wait until postInit to install playerChanged event

- tools/setup.py
- Close #1614 
- Always use junctions for development environment symlinks
- Junctions work from Vista upwards, so that should be no issue anymore
> Always use junctions for dev environment setup

- addons/overheating/functions/fnc_jamWeapon.sqf
- Raise an event when a player's weapon jams. 
This is a very minor (1 line!) change which will add an event upon weapon jamming to the public API. I personally have a use for it in an existing addon I am working on and I am sure that others may find it useful.
> Raise a local event when a weapon is jammed

- addons/goggles/functions/fnc_clearGlasses.sqf
- Close #3638
Animation only makes sense for primary weapon, so skip for others.
> Googles - Only play wipe anim for primary weapon

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_loadPerson.sqf
- addons/fastroping/CfgVehicles.hpp
- addons/fastroping/script_component.hpp
- Fix #3686
The FRIES is a "Helicopter" so we were trying to load into it, because it was closest.
Also disable Cargo system on it so we don't load other things into it
And remove all interactions on it as well.
> LoadPerson - Only try vehicles that have room

- addons/repair/CfgEventHandlers.hpp
- Prevent `repair` component from trying to add repair interactions to `ACE_friendsAnchorBar`
```
13:40:49 0:00:50.916 (0) [z\ace\addons\interact_menu\functions\fnc_addActionToClass.sqf:46] -ERROR- ERROR
13:40:49             Failed to add action
13:40:49 [ACE] (interact_menu) ERROR: action (ace_repair_fullRepair) to parent ["ACE_MainActions","ace_repair_Repair"] on object ACE_friesAnchorBar [0]
```
> Exclude FRIES from repair interactions

- addons/viewdistance/CfgVehicles.hpp
- addons/viewdistance/XEH_PREP.hpp
- addons/viewdistance/XEH_clientInit.sqf
- addons/viewdistance/functions/fnc_adaptViewDistance.sqf
- addons/viewdistance/functions/fnc_changeViewDistance.sqf
- addons/viewdistance/functions/fnc_returnObjectCoeff.sqf
- addons/viewdistance/functions/fnc_returnValue.sqf
- addons/viewdistance/functions/fnc_setFovBasedOvdPFH.sqf
- addons/viewdistance/script_component.hpp
- Fix view distance using "on foot" setting when in boats/ships instead of "in vehicle" setting.
- Cleanup view distance component (`params`, `private` keyword, camel case, `isEqualType `)
- Move constants to `script_component.hpp`
> Fix ship view distance using foot instead of vehicle setting

- addons/explosives/CfgVehicles.hpp
- Removes duplicate entries for explosives in eden, placing in editor makes no sense as they won't have needed `setVariables`
> Make explosives helpers hidden in eden.

- addons/gforces/ACE_Settings.hpp
- addons/gforces/XEH_PREP.hpp
- addons/gforces/XEH_postInit.sqf
- addons/gforces/functions/fnc_addPFEH.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
- addons/gforces/stringtable.xml
- Add ace_setting to gforces so the PFEH only runs when player is inside of a aircraft
Default is unchanged, but we might want to make default aircraft only (`1`)?
I don't think any ground vehicle can accelerate enough to have any real effect.
> Gforces - Add ace_setting to only run in aircraft

- addons/javelin/functions/fnc_onOpticDraw.sqf
- Fix #3668
`cursorTarget` will work through hills if the unit has prior knoweldge of target
Example: Green X is cursorTarget car:
> Javelin - Verify player has LOS to cursorTarget

- addons/concertina_wire/CfgVehicles.hpp
- addons/concertina_wire/functions/fnc_handleKilled.sqf
Close #3695
- Don't recoil broken wire
- Use midpoint to search for nearby cars, and ensure the veh was moving.
> Concertina Wire - Don't recoil broken wire, fix killer

- addons/common/functions/fnc__handleRequestSyncedEvent.sqf
- addons/common/functions/fnc__handleSyncedEvent.sqf
- addons/common/functions/fnc_addSyncedEventHandler.sqf
- addons/common/functions/fnc_removeSyncedEventHandler.sqf
- addons/common/functions/fnc_syncedEvent.sqf
-Better logging for synced events
Trying to track down cause of `[ACE] (common) ERROR: Synced event key not found.` on a jip
> Improve synced event error logging

- addons/cargo/CfgVehicles.hpp
- Adds cargo space to Taru Ammo, Cargo, Medical and Repair pods (same as their pre-attached to helicopter counterparts)
> Add cargo to Taru pods

- addons/vehiclelock/CfgEventHandlers.hpp
- addons/vehiclelock/XEH_postInit.sqf
- addons/vehiclelock/functions/fnc_onOpenInventory.sqf
- Make locked vehicle inventory more compatible with ACRE
Before, the vehicle's inventory display and the player's would be open in the same frame, which broke a script ACRE uses to add actions to the radios and to hide the linked radio slot.
Also switched to using `CBA_fnc_addClassEventHandler` to only add the inventory event handler when this feature is selected.
> vehicle inventory lock - compatibility with acre

- addons/reloadlaunchers/functions/fnc_addMissileReloadActions.sqf
- addons/reloadlaunchers/functions/fnc_canLoad.sqf
- addons/reloadlaunchers/functions/fnc_getLoadableMissiles.sqf
- addons/reloadlaunchers/functions/fnc_load.sqf
- addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- Cleanup reload launchers
Minor cleanup of params, and adds a fast exit for non supported weapons.
**Todo**: None of the launcher seem to have a good config for reload time and right now it's a 12 second progress bar which make this module pretty hard to use.
```
magazineReloadTime = 12;
```
I can't really find any good config value for the real reload time (about 3 seconds), it might be linked to the reload animation??
> Cleanup reload launchers

- addons/ui/functions/fnc_setElements.sqf
- UI / ShowHud - Ignore the indexes that we aren't explicitly setting (pass true instead of current)
Prevents problems from something like this:
```
["test", [false,false,false,false,false,false,false,false]] call ace_common_fnc_showHud; 
```
then change UI settings, then clear
```
["test", []] call ace_common_fnc_showHud; 
```
> UI - Don't overwrite other showHud indexes

- addons/weather/XEH_postInit.sqf
- addons/weather/stringtable.xml
- Add key to toggle wind info display
This would match the default behaviour of the compass, where it only shows up while the key is held down.  By default key is unbound so this will have no effect unless chosen by user.
Tag @Gwynblade
> Add key to toggle wind info display

- extensions/parse_imagepath/ace_parse_imagepath.cpp
Replace unsafe strncpy with safe strncpy_s.
> Fixed strncpy in parse_imagepath

- addons/trenches/CfgVehicles.hpp
- addons/trenches/XEH_PREP.hpp
- addons/trenches/XEH_preInit.sqf
- addons/trenches/config.cpp
- addons/trenches/functions/fnc_canContinueDiggingTrench.sqf
- addons/trenches/functions/fnc_canDigTrench.sqf
- addons/trenches/functions/fnc_canRemoveTrench.sqf
- addons/trenches/functions/fnc_continueDiggingTrench.sqf
- addons/trenches/functions/fnc_placeConfirm.sqf
- addons/trenches/functions/fnc_placeTrench.sqf
- addons/trenches/functions/fnc_removeTrench.sqf
- addons/trenches/functions/fnc_setTrenchPlacement.sqf
- addons/trenches/script_component.hpp
- addons/trenches/stringtable.xml
- Add remove trench and continue digging trench actions
- Add config vars to set time needed to dig or remove trench
- Make digging trench ~50% longer
- `Remove trench` or `continue digging trench` duration is based on config var and actual progress of trench "construction" e.g. if trench is finished in 50% removing this trench will take 50% of normal removal time.
- Move trench placement data from preInit to object config
- Remove grass behind the trench
Demo: https://www.youtube.com/watch?v=xqM6hCWkvLo
> Add remove trench and continue digging trench actions

- addons/spectator/XEH_postInit.sqf
- addons/spectator/functions/fnc_setSpectator.sqf
- title
- maybe fix #3614
Please someone test on a dedicated.
Note:
- This fix does not work for SP.
- This fix only kinda works for local hosted MP if the host him/herself is currently in the spectator view. Once the local host leaves the spectator mode by pressing ESC, the mission should end for everyone.
- On dedicated server, this should work without issues.
> end spectator by global mission end event from server

- addons/optics/CfgWeapons.hpp
- addons/scopes/CfgWeapons.hpp
correct mildot reticle LRPS/AMS/KHS
> AB - correct mildot reticle LRPS/AMS/KHS

- addons/parachute/CfgVehicles.hpp
- addons/parachute/functions/fnc_storeParachute.sqf
- Add NonSteerable Reserve Parachute
- Cleanup storeParachute
Close #3364
`ACE_NonSteerableParachute` -> `ACE_NonSteerableReserveParachute` - both are not steerable
`B_Parachute` -> `ACE_ReserveParachute` - both are steerable
> Add NonSteerable Reserve Parachute

- addons/explosives/XEH_postInit.sqf
- Move server event for explosives sync above `if (!hasInterface) exitWith {};`
- Use `CBA_fnc_getSharedGroup`
> Fix explosive sync on dedicated server

- addons/repair/functions/fnc_getWheelHitPointsWithSelections.sqf
- Fix #3759
The backup wheel detection just tries to find the closest hitpoint to the wheel, and for one RHS vic the engine is close than the actual wheel hitpoint. This just adds a blacklist for the engine.
> Repair - Improve wheel detection for RHS

- addons/common/functions/fnc_getWeaponMuzzles.sqf
- addons/common/functions/fnc_getWeaponState.sqf
- makes `FUNC(getWeaponMuzzles)` return the configs capitalization of the "this" muzzle instead of input (solves some case sensitivty issues with other functions using it)
- fix format of the array returned by `FUNC(getWeaponState)` (#3777)
- use `param` and `apply`
- `_weapon` argument defaults to the units current weapon
> fix getWeaponState, fix #3777

- addons/movement/functions/fnc_addLoadToUnitContainer.sqf
- addons/movement/functions/fnc_getWeight.sqf
- addons/movement/functions/fnc_handleVirtualMass.sqf
- makes `FUNC(getWeight)` respect virtual load
- adds possiblity to add load to the unit itself instead of one of it's containers
tag #3749
> show virtual load in inventory menu

- addons/refuel/functions/fnc_takeNozzle.sqf
- addons/refuel/script_component.hpp
- Moves part of "Take Nozzle" action execution into progress bar on success (set force walk, holster weapon and 2 variables) - fixes #3739 
- Prettifies `params` usage in take nozzle function.
Tagging @GitHawk for review
> Execute take nozzle actions only on progress bar success

- addons/repair/CfgEventHandlers.hpp
- addons/repair/functions/fnc_addSpareParts.sqf
- Removes initial spare part adding for all classes except `Car` and `Tank` - it is used only to add spare wheels and tracks to those 2 classes.
- Improves `FUNC(addSpareParts)` - due to above manual checking is not needed, it just added overhead, this also allows improved checking without adding it to `runAtSettingsInitialized` even if no part name is supplied.
> Remove redundant spare part adding and improve addSpareParts function

- addons/interaction/CfgVehicles.hpp
- addons/interaction/XEH_PREP.hpp
- addons/interaction/functions/fnc_canPush.sqf
- addons/interaction/functions/fnc_push.sqf
- Adds `ace_interaction_canPush` config entry which enables pushing on boats with mass over 2600.
- Moves interaction condition to it's own function (no idea who wrote original condition, so I can't include it in authors).
- Closes #3744 - CUP needs to add `ace_interaction_canPush = 1` to the RHIB config.
> Add canPush config entry

- addons/spectator/functions/fnc_handleInterface.sqf
- Account for decrement in node index when culling the tree of sides/groups/units
- Fix non-zero-based index `to` value when navigating the units in the tree
> Fix spectator unit tree refreshing

- addons/interaction/CfgVehicles.hpp
- addons/repair/CfgEventHandlers.hpp
- addons/repair/CfgVehicles.hpp
- Adds interaction support to `Motorcycle` class - for example CUP's M1030.
**Known issues:**
- Wheel repairing does not work for CUP's M1030 because it is not PhysX configured and ACE repair component expects it to be.
I probably missed a bunch of stuff that should be added, name them please!
> Add interaction support to Motorcycle class

- wiki/development/coding-guidelines.md
Minor updates to our coding guidelines
> Update coding guidelines

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_assignedItemFix.sqf
- addons/common/functions/fnc_getAllGear.sqf
- addons/goggles/XEH_postInit.sqf
The output of `getUnitLoadout` is different as `getAllGear`. Using a different format in the event would mean that any eventhandler depending on the inventory output would now be broken.
> Add backwards compatability for InventoryChanged

- addons/common/XEH_postInit.sqf
- addons/medical/functions/fnc_reviveStateLoop.sqf
- don't do 'playerInventoryChanged' just because ammo decreased after firing
ref: #3792
> skip 'playerInventoryChanged' after firing

- addons/common/functions/fnc_getTurretCommander.sqf
- addons/common/functions/fnc_getTurretCopilot.sqf
- addons/common/functions/fnc_getTurretGunner.sqf
- addons/common/functions/fnc_getTurrets.sqf
- addons/common/functions/fnc_getTurretsFFV.sqf
- addons/common/functions/fnc_getTurretsOther.sqf
- Since 1.55dev `fullCrew` can show unmanned positions. Since it also has a filter for specific turret types, it can replace the manual SQF filtering of `allTurrets`.
```
// merkava
cursorTarget call ACE_common_fnc_getTurretCommander
Before:
0.0758 ms
After:
0.0108 ms
```
> fullCrew new parameter to improve FUNC(getTurretX)

- addons/safemode/XEH_postInit.sqf
- Close  #3819
- Fix Can't toggle safemode in FFV seat
Also block safemode when no weapon
> Fix Can't toggle safemode in FFV seats

- addons/map/CfgAmmo.hpp
- addons/map/CfgLights.hpp
- addons/map/Effects.hpp
- addons/map/XEH_postInitClient.sqf
- addons/map/config.cpp
- addons/map/functions/fnc_flashlightGlow.sqf
- Fix https://github.com/acemod/ACE3/issues/3605
- Change external flashlight glow object from a sprite effect (infinite visibility) to a light source (~500m visibility; depends on conditions)
- Glow appears on unit's neck/chest, so you can no longer see it from behind or, when he's prone, from above
- Glow objects are now detached before being deleted, preventing dozens (potentially hundreds) of duplicate objNulls attached to players
**Preview Images**
5m old: http://i.imgur.com/0hEeKYq.png [plain] http://i.imgur.com/GeCLSQr.png [nvg]
5m new: http://i.imgur.com/YRHl50J.png [plain] http://i.imgur.com/kSa7AMP.png [nvg]
100m old: http://i.imgur.com/C1bKiJE.png [plain] http://i.imgur.com/rqun1L1.png [nvg]
100m new: http://i.imgur.com/jtFNK7l.png …
> ace_map: More realistic flashlight glow + minor fix

- addons/gforces/config.cpp
- Fix nil settings mistake from PR #3705
> gforces - Fix missing ace_settings.hpp include

- addons/flashsuppressors/CfgWeapons.hpp
- Close #3700 - Fix UBC errors and properly configure the 6.5mm weapons to use the right flash suppressors.
Quick version of how it works:
For most weapons we can just add it to the generic muzzle
eg `class asdg_MuzzleSlot_762MG: asdg_MuzzleSlot { ` we add the `*_B` item which is 7.62mm and these should work on any mod using these joint muzles.
JR has the vanilla 6.5mm weapons using the 7.62mm muzzles, so we do
```
class compatibleItems: compatibleItems {
ACE_muzzle_mzls_H = 1;
ACE_muzzle_mzls_B = 0;
};
```
to disable our 7.62 attachment and enable our 6.5mm version.
ACE's 7.62mm still shows up in VA, but is not attachable (and exported itemName is wrong), problem with VA - https://github.com/CBATeam/CBA_A3/pull/246#issuecomment-174171284
> FlashSuppressors - use next CBA's JM configs

- addons/common/functions/fnc_binocularMagazine.sqf
- addons/common/functions/fnc_getAllGear.sqf
- addons/common/functions/fnc_removeBinocularMagazine.sqf
> Use new binocular magazine CBA functions and deprecate ACE functions

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_deprecateComponent.sqf
- addons/sitting/CfgVehicles.hpp
- addons/sitting/XEH_clientInit.sqf
- Add support for deprecating components
- Deprecrates ACE Sitting. Moved to ACEX Sitting.
> Add Deprecate components support

- addons/goggles/XEH_postInit.sqf
- Fix script error
```
x5 = [{systemChat "z"}, [], 1] call CBA_fnc_waitAndExecute
```
Will throw an error. Way back, waitAndExecute returned the PFEH-ID, so there might be more of these.
> Goggles - Fix script error from CBA_fnc_waitAndExecute

- addons/common/XEH_postInit.sqf
- Fix `showHud` command is ignored if set before display loaded
@jonpas  - This was causing `ace_ui_groupBar` to have no effect in multiplayer.
> Fix showHud if set before display loaded

- addons/microdagr/functions/fnc_canShow.sqf
- Allow drivers of vehicles to show microDagr
Currently the microDagr follows the same rules as the vanilla GPS which blocks display when in "gunner" camera view. A lot of armored vehicles don't have a 3d interior and all crew are locked to gunner mode at all times making it difficult to use just because of a limitation of the vehicle.
This removes the "gunner" restriction for drivers.
> Allow drivers of vehicles to show microDagr

- addons/markers/CfgEventHandlers.hpp
- addons/markers/XEH_PREP.hpp
- addons/markers/functions/fnc_mapDisplayInitEH.sqf
- addons/markers/functions/fnc_onLBSelChangedColor.sqf
- addons/markers/functions/fnc_onLBSelChangedShape.sqf
1.60 adds ability to set color and marker type from the map interface (top right corner)
Luckily they use the same values and indexes as ACE :wink: 
This PR connects the two systems:
Selecting a color from the 1.60 map display will set the color in the
ace marker display and vice versa
> Integrate 1.60 marker shape color map interface

- addons/attach/functions/fnc_attach.sqf
- Moves attachment position of IR strobe/grenade to left shoulder. Previously, when on the right shoulder, the strobe was visible as a reflection when looking down some optics (Elcan from 3CB) which was intrusive whilst aiming.
> Moved IR Strobe to left shoulder when attached.

- addons/spottingscope/CfgVehicles.hpp
- Fix the interaction point of the spotting scope
- Correct the classname so it shows up in the miscellaneous items box
Here's the interaction point before and after:
> Spottingscope fixes

- addons/explosives/stringtable.xml
- addons/fastroping/stringtable.xml
- addons/gforces/stringtable.xml
- addons/overheating/stringtable.xml
- addons/repair/stringtable.xml
- addons/trenches/stringtable.xml
- addons/ui/stringtable.xml
Translated all remaining string from modules as stated: explosives, fastroping, gforces, overheating, repair, trenches, ui
> Translated remaining strings to PT-BR

- addons/ui/XEH_clientInit.sqf
- Add check if a UI class even exists in `SettingChanged` event
- Fix script error when changing certain other settings:
```
21:18:53 Error in expression <ex = ace_ui_elementsSet find [_element, !_show];
if (_index != -1) then {
if (_s>
21:18:53   Error position: <!_show];
if (_index != -1) then {
if (_s>
21:18:53   Error Generic error in expression
21:18:53 File z\ace\addons\ui\functions\fnc_setAdvancedElement.sqf, line 38
```
> Fix selective UI script error when changing certain other settings

- addons/medical/functions/fnc_handleDamage_advanced.sqf
Fix #3892
On current dev branch (1.63) they added an addition param to `HandleDamage` params.
When the changes are released we can do a simple proper fix with `params`, but for now I think this is a reasonable solution that will make adv medical compatible with both 1.60 and dev.
> Temp fix for change to handleDamage in dev branch

- addons/nametags/functions/fnc_drawNameTagIcon.sqf
Originally fixed by joko in #2882 , must have been lost in the rewrite
New `param` solution from @commy2 in slack
> Fix nametag error when assignedTeam is nil

- addons/movement/functions/fnc_handleVirtualMass.sqf
Playing as animal or human and removing everything throws div0 error as `load _unit` is 0.
@commy2 as best I can tell ` loadAbs _unit / load _unit;` is the same as the config
```
class CfgInventoryGlobalVariable {
maxSoldierLoad = 1000;
};
```
So using that should be faster and prevent the error.
> virtualMass - Fix div0 error when naked

- addons/medical/XEH_PREP.hpp
- addons/medical/config.cpp
- addons/medical/functions/fnc_showBloodEffect.sqf
- addons/medical/ui/CfgInGameUI.hpp
- addons/medical/ui/RscTitles.hpp
On the medical-adjustments branch the wound visuals on the uniform are flickering when shooting someone, because some hitpoints are reset for one frame.
I was told that this was added to prevent some BI effects when getting hit by a bullet.
No idea which effects exactly, but if it's only the blood fx, then this PR does it by config and not by scripting which is the prefered way imo.
> remove BI blood overlay

- addons/medical/stringtable.xml
- Change the names of certain bandages in the inventory and medical menu
The current german translation leads to confusion when it comes to bandages, because:
- "QuikClot" in the inventory is called "**Verbandpäckchen** (Gerinnungsmittel)"
- "Bandage (Basic)" in the interaction menu is called "**Verbandpäckchen**"
This lead to people confusing the basic bandages with QuikClots.
> Improved misleading translation of german bandages

- addons/fastroping/functions/fnc_fastRopeLocalPFH.sqf
- Only play fastroping sounds for player
When local hosting, the sounds were played for every AI unit fastroping.
> Only play fastroping sounds for player

- addons/fastroping/CfgVehicles.hpp
The helper "ace_fastroping_helper" inherits from class "Helicopter_Base_F", and take a look at this chain of inheritance. Call that Bohemia's fault, lol.
class CfgVehicles
{
class AllVehicles;
class Air: AllVehicles
{
class TransportItems
{
class _xx_FirstAidKit
{
name = "FirstAidKit";
count = 4;
};
};
};
class Helicopter: Air
{
};
class Helicopter_Base_F: Helicopter
{
};
class ace_fastroping_helper: Helicopter_Base_F
{
class TransportItems {};	// now overrides the first aid kits
};
};
Was a happy and funny surprise to pick up some decent medical supplies from one end of a cut rope.
> add a line to get rid of 4 first aid kits in the invisible fast roping helper

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_getMGRSdata.sqf
- addons/common/functions/fnc_getMapData.sqf
- add Tanoa Latitude to the getMGRS function
- add a tiny performance improvement in checking the map
> Tanoa map data

- addons/movement/functions/fnc_handleVirtualMass.sqf
`[objNull] call ace_movement_fnc_handleVirtualMass` throws error
`objNull getUnitTrait "loadCoef"` is nil, which breaks everything
> movement - Handle objNull in virtualMass

- addons/optics/XEH_postInit.sqf
- addons/optics/functions/fnc_handleFired.sqf
- addons/optics/functions/fnc_onDrawScope2D.sqf
- Fix #3899
Instead of creating the PIP camera at mission start, we only create it when actually needed when in scoped view, and destroy it after leaving.
Should clear up problems we've seen with mission's using camera scripts due to us always calling `cameraEffect`.
> Optics - Create PIP camera only when needed

- addons/medical/ACE_Medical_Treatments.hpp
Cherry picking a minor fix from PR #3632
Ensures that velocity wounds from a major hit will use the "Large" type of wound 
(which has more bleeding).
Otherwise something like 
```
[player, 2, "leg_r", "bullet"] call ace_medical_fnc_addDamageToUnit
```
Has a chance to only cause a medium wound
> Add maxDam for medium velocity wounds

- addons/medical/functions/fnc_actionCheckBloodPressureLocal.sqf
- addons/medical/functions/fnc_actionCheckPulseLocal.sqf
- addons/medical/functions/fnc_actionCheckResponse.sqf
- addons/medical/functions/fnc_actionDiagnose.sqf
- addons/medical/functions/fnc_addUnloadPatientActions.sqf
- addons/medical/functions/fnc_canAccessMedicalEquipment.sqf
- addons/medical/functions/fnc_canTreat.sqf
- addons/medical/functions/fnc_displayPatientInformation.sqf
- addons/medical/functions/fnc_displayTriageCard.sqf
- addons/medical/functions/fnc_dropDownTriageCard.sqf
- addons/medical/functions/fnc_getUnconsciousCondition.sqf
- addons/medical/functions/fnc_handleBandageOpening.sqf
- addons/medical/functions/fnc_onMedicationUsage.sqf
- addons/medical/functions/fnc_playInjuredSound.sqf
- addons/medical/functions/fnc_treatment.sqf
- addons/medical/functions/fnc_treatment_failure.sqf
- addons/medical/functions/fnc_treatment_success.sqf
- addons/medical_menu/functions/fnc_collectActions.sqf
- addons/medical_menu/functions/fnc_getTreatmentOptions.sqf
- addons/medical_menu/functions/fnc_handleUI_dropDownTriageCard.sqf
- addons/medical_menu/functions/fnc_onMenuOpen.sqf
- addons/medical_menu/functions/fnc_openMenu.sqf
- addons/medical_menu/functions/fnc_updateActivityLog.sqf
- addons/medical_menu/functions/fnc_updateBodyImage.sqf
- addons/medical_menu/functions/fnc_updateIcons.sqf
- addons/medical_menu/functions/fnc_updateInformationLists.sqf
- addons/medical_menu/functions/fnc_updateQuickViewLog.sqf
Minor improvements to ACE medical code part 2. Same as #3912.
Only a limited number of functions instead of everything, to avoid doing to many things at the same time in the same PR.
Biggest changes:
- Use private keyword.
- Remove excessive whitespace
- Add space where needed (set[ -> set [)
- Makes some lines more compact
> Minor improvements to ACE medical code part 2

- addons/interaction/functions/fnc_getVehiclePos.sqf
@esteldunedain - Improvements for your PR #3342
I noticed that big helicopters had interaction points from far away (screenshot is 12m distance)
- For helicopters I added a max width of 3 meters, which should cover the body, but not the rotors.
- Made the max height the same as eye level.  This might just be personal preference, but it feels more natural to me to not have to look way up for tall vehicles like the big choppers, and trucks.
> getVehPos - Tweak heli width, and put at eye level

- addons/attach/functions/fnc_detach.sqf
- Players can no longer reuse attached chemlights.
- Players can remove chemlights even if their inventory is full.
- Detach items before deleting them, to avoid objNull attaches.
> On Detach, Delete Used Chemlights

- addons/logistics_wirecutter/functions/fnc_interactEH.sqf
Fix #2976
If bad LOS to the helper, check again for LOS to the fence itself.
> Fix Line Of Sight check for wire cutter helper

- addons/ui/CfgEventHandlers.hpp
- addons/ui/XEH_PREP.hpp
- addons/ui/XEH_clientInit.sqf
- addons/ui/functions/fnc_findSetElement.sqf
- addons/ui/functions/fnc_setAdvancedElement.sqf
- addons/ui/functions/fnc_setElementVisibility.sqf
- addons/ui/functions/fnc_setElements.sqf
- Fix #3907 
- Add disabled message on changing basic config which has been set (forced) by mission config
- Remove redundant parameter from basic `setElements`
Todo:
> Fix basic UI being overwritten on RscDiary unload

- addons/medical/XEH_postInit.sqf
Advanced medical was never displaying the gray screen on low blood volume. This is because for advanced medical, the blood volume minimum level is around 40 before death. For basic medical, this is 0.
This PR scales the gray screen for advanced medical to the correct levels.
#3134
> Fix no gray screen for advanced medical

- addons/zeus/CfgEventHandlers.hpp
- addons/zeus/XEH_postInit.sqf
- addons/zeus/functions/fnc_addObjectToCurator.sqf
- Add the InitPost XEH event to `AllVehicles` only if the `autoAddObjects` setting is enabled
The XEH InitPost event only needs to be added if the `GVAR(autoAddObjects)` setting is enabled. This change will save on overhead when the setting is disabled and also removes some complexity from the function that runs in response to the event.
> Improve zeus auto-add XEH behaviour

- addons/laser_selfdesignate/CfgWeapons.hpp
- addons/missileguidance/CfgAmmo.hpp
- Completely restore the Comanche's DAGRs to vanilla. 
- Close #3671
If you recall, for 3.5 we decided to restore vanilla locking guidance for the Comanche, until ACE_Laser and ACE_MissileGuidance were made to work properly with non-self designators. That was done in #3305. However, there were some wrong config entries remaining on the DAGR ammo, which messed up vanilla behaviour, causing #3671. In this PR those entries are removed.
I still hope we can reenable ACE_Laser at some point, but there are still quite a few tasks remaining, tracked in #3308. In the meantime, hopefully this will make Comanche as OP as it is in Vanilla ;)
> Fix Comanche's weapon lock and guidance

- addons/spottingscope/functions/fnc_place.sqf
- Reduce the chance of spotting scopes rolling when placed on slopes
> Fix the placement of spotting scopes on slopes

- addons/captives/CfgEventHandlers.hpp
- addons/captives/XEH_PREP.hpp
- addons/captives/functions/fnc_handleAnimChangedHandcuffed.sqf
- addons/captives/functions/fnc_handleAnimChangedSurrendered.sqf
- addons/captives/functions/fnc_handleLocal.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- Make sure that if a captive unit switches locality, it's AnimChanged EH switches with it.
- Close #3950
I only did limited testing, but it seems to work as expected.
> Fix freeing prisoners after they've switched locality

- addons/dogtags/functions/fnc_canCheckDogtag.sqf
- addons/dogtags/functions/fnc_canTakeDogtag.sqf
- addons/dogtags/functions/fnc_checkDogtag.sqf
- addons/dogtags/functions/fnc_getDogtagItem.sqf
- addons/dogtags/functions/fnc_takeDogtag.sqf
Because you can take dogtags when they are just unconscios, you can set the `dogtagTaken` var before they die, so it will get copied over to respawned unit.
This PR will:
Store object instead of bool to indicate when dogtags have been taken
When object re-spawns, the the old object reference won't apply
> Fix issue with dogtag respawn/setVariable

- addons/dogtags/XEH_PREP.hpp
- addons/dogtags/functions/fnc_bloodType.sqf
- addons/dogtags/functions/fnc_getDogtagData.sqf
- adds a function that reports a blood type depending on the units name
- This will make sure the blood type of a player doesn't change each mission or even each respawn
> add function to report a blood type which is fixed to the units name

- addons/aircraft/config.cpp
- addons/fcs/config.cpp
- addons/gforces/config.cpp
- addons/realisticnames/config.cpp
- addons/vehicles/config.cpp
- adds `addonRootClass` so some of our components are ignored by the 1.60 CfgPatches changes for mission dependencies.
> fix some rogue mission dependencies

- addons/dogtags/XEH_PREP.hpp
- addons/dogtags/functions/fnc_getDogtagData.sqf
- addons/dogtags/functions/fnc_ssn.sqf
Similar to how we're handling blood types, uses the unit's name to generate a valid three/two/four format SSN.
For names less than 9 characters long this will currently generate a unique SSN only up to the length of the name and append valid digits as necessary. Not sure how best to handle those cases.
Output of some tests:
SilentSpike: 358-10-6325
esteldunedain: 156-18-0701
commy2: 919-91-0645 / 919-91-0774 / 919-91-0750
Glowbal: 181-98-7836 / 181-98-7837 / 181-98-7805
jonpas: 610-27-5955 / 610-27-5081 / 610-27-5438
#3962
> Generate SSN of unit from their name

- addons/common/XEH_postInit.sqf
For PR #3972
Still thinking about `ace_playerInventoryChanged` as right now this adds an extra call to `FUNC(getAllGear)` even when there are no listeners to the old event.
> Convert state checking to CBA playerEH

- optionals/compat_r3f/CfgAmmo.hpp
Fix correct "ACE_barrelLengths" for "R3F_127x99_Ball" and "R3F_127x99_PEI" according to the R3F_PGM_Hecate_II barrel length (700mm)
> Update compat_r3f CfgAmmo.hpp

- addons/missileguidance/functions/fnc_seekerType_Optic.sqf
Close #3374
Because func was undefined `_losOkay` was nil, so target leading was always skipped.
> missleGuidance - Fix seeker los check

- addons/fcs/CfgWeapons.hpp
Ref https://community.bistudio.com/wiki/A3_Locking_Review#ballisticsComputer
Prior to 1.60 I think it was `1` 
1.60 changed it to `4+2`
We want to disable the manual zeroing for FCS, 
but I don't see any reason to disable the "Target lead indication"
The thing in red:
> Fix lead indicator for B_APC_Tracked_01_AA_F

- addons/captives/XEH_postInit.sqf
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_assignedItemFix.sqf
- addons/disposable/XEH_postInit.sqf
- addons/dragging/XEH_postInit.sqf
- addons/gforces/XEH_postInit.sqf
- addons/goggles/XEH_postInit.sqf
- addons/hearing/XEH_postInit.sqf
- addons/interact_menu/XEH_clientInit.sqf
- addons/map/XEH_postInitClient.sqf
- addons/maptools/XEH_postInitClient.sqf
- addons/medical/XEH_postInit.sqf
- addons/mk6mortar/XEH_postInit.sqf
- addons/movement/XEH_postInit.sqf
- addons/nametags/functions/fnc_initIsSpeaking.sqf
- addons/nightvision/XEH_postInitClient.sqf
- addons/noradio/XEH_postInit.sqf
- addons/parachute/XEH_postInit.sqf
- addons/rearm/XEH_postInit.sqf
- addons/respawn/XEH_postInit.sqf
- addons/sandbag/XEH_postInit.sqf
- addons/scopes/XEH_postInit.sqf
- addons/tacticalladder/XEH_postInit.sqf
- addons/trenches/XEH_postInit.sqf
- addons/tripod/XEH_postInit.sqf
- addons/viewdistance/XEH_clientInit.sqf
> convert common events to CBA playerEvents

- addons/parachute/functions/fnc_storeParachute.sqf
Uses the backpack command to retrieve the classname of a unit's backpack instead of a select. Fixes incorrect index.
> Change use backpack command for backpack classname

- addons/fcs/functions/fnc_canUseFCS.sqf
Redo #3983 for 3.6/release
Fix doing FCS keyUp calculations/setVariable
when controlling a UAV while also in a turret with FCS enabled.
Normal rangefinder on the UAV will still work as FUNC(canUseRangefinder)
is still true
> Block FCS when controlling a UAV

- addons/tagging/functions/fnc_tag.sqf
- Align tags upward in non-horizontal surfaces
- Prevent stuff like this @ColdEvul: 
Ref #3696
> Align tags upward in non-horizontal surfaces

- addons/rearm/functions/fnc_dropAmmo.sqf
- addons/rearm/script_component.hpp
Should fix #4006
I could not reproduce the error, but I hope this will help.
In any case I dislike that with every vehicle change (even if not using the module) we did
` _unit selectWeapon nil`
> rearm - Skip selectWeapon on nil

- addons/medical/functions/fnc_displayPatientInformation.sqf
This fixes an issue were injured body parts were displayed as blue instead of red. Happens when using advanced medical with AI running in basic mode. @alganthe
> Fix injuries shown as blue instead of red

- addons/rearm/functions/fnc_rearmEntireVehicleSuccess.sqf
- addons/rearm/functions/fnc_rearmEntireVehicleSuccessLocal.sqf
- addons/rearm/functions/fnc_rearmSuccess.sqf
- addons/rearm/functions/fnc_rearmSuccessLocal.sqf
Rearm was doing some weird stuff with old execRemoteFnc:
`_turretOwnerID publicVariableClient QEGVAR(common,remoteFnc);` 
(https://github.com/acemod/ACE3/commit/0723df7dea5c0a0edbf5dd6f8698dbc93a615e87#diff-e700393f0d5b2d9446845839cb7e854bL40)
We can't do events to owners until cba 2.4.2, so I switched it to just blast a global event and filter using `turretLocal` on all recievers so it works.
Still need to test on dedicated, will do tomorrow.
> Fix rearm events

- addons/missileguidance/functions/fnc_checkLos.sqf
- addons/missileguidance/functions/fnc_onFired.sqf
Fix #4007
The onFired stuff is just a bandAid until 1.62 is out. 
We need to explicitly add config's to the new weapons (it's designed to ignore inheritance)
> Handle bad target when using apex titans

- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- This adds the possibility to overrule the `faction` reported by the game with a custom one
- It can be used together with `setUnitLoadout` and `setUnitTrait` to fully change a unit from, e.g. B_Soldier_F to a Bundeswehr soldier.
`_unit setVariable ["ace_nametags_faction", "BWA3_Faction"]`
> add possibility to overwrite a units faction for determining name tags

- addons/repair/config.cpp
- addons/repair/functions/fnc_addSpareParts.sqf
- addons/zeus/config.cpp
- addons/zeus/functions/fnc_moduleAddSpareTrack.sqf
- addons/zeus/functions/fnc_moduleAddSpareWheel.sqf
Fix Spare parts not being added in 3.6
Cargo event was renamed.
> Fix cargo event name - spare parts not being added

- addons/interact_menu/functions/fnc_renderActionPoints.sqf
This should be a fix for a side effect of #3342
I could not find the interaction point for the attached refuel nozzle.
In the cropped screenshot below, the refuel action would not be shown without this fix.
Interaction _sPos: [0.768666,0.525559,0.346336]
Refuel _sPos: [0.453124,0.457705,1.23955]
Delta: [-0.332239,-0.0714445,0.940485]
Distance2d: 0.322755
I think the vehicle's dynamic position is pushed so close to the player that it obscures things that it shouldn't.
This PR adds a 2nd requirement that the 2d screen pos distance needs to be small enough to make obscuring worthwhile.
> Less aggressive overlap detection

- addons/dragging/XEH_postInit.sqf
- addons/dragging/stringtable.xml
- Adds a keybind to start dragging the cursorObject.
- If player is currently dragging/carring it will be dropped (Just like Joko's #2333)
- Unbound by default.
I had a feature request for this from someone who had trouble finding the drag interaction point on a body that was laying oddly. Given all the interaction points on people it is easy for them to overlap; so this does seem reasonable to me.
Should let us close out https://github.com/acemod/ACE3/issues/2284#issuecomment-136550815
and might work for #3724
> Add Drag/Drop Keybind

- addons/overheating/CfgWeapons.hpp
- addons/overheating/functions/fnc_displayTemperature.sqf
- addons/overheating/functions/fnc_loadCoolestSpareBarrel.sqf
Fix #4044 
- Remove ACE_SpareBarrel from CfgWeapons as it is now a magazine
- Don't call updateTemperature in displayTemp, as unit may not be local
- Fix targetEvent error in loadCoolestSpareBarrel
> Fix overheating spare barrels

- addons/fcs/ACE_UI.hpp
- addons/reload/ACE_UI.hpp
- addons/ui/ACE_Settings.hpp
- addons/ui/CfgVehicles.hpp
- Title
- Defaults `ammoCount` to off
I think braces prevent pboProject from converting them, correct me if I am wrong.
> Fix pboProject converting boolean to numbers in UI config

- addons/medical/functions/fnc_reviveStateLoop.sqf
Fix #4035
Revive loop was always killing heartrate before it exited, even if they were healed by PAK
> Fix order of revive loop

- addons/overheating/XEH_preInit.sqf
- Title
- Function definition was added in https://github.com/acemod/ACE3/commit/62f598b2a6bca3049438c52154e3b9c612aac952 (and later renamed in another commit) to keep compatibility with CBA at the time.
> Remove redundant getMagazineIndex compatibility function

- addons/attach/stringtable.xml
- addons/repair/stringtable.xml
- Remove remaining >> signs from the interaction menu: "Attach >>" and "Repair >>"
We've removed most of these signs a long time ago, but for some reason these two actions kept them. For #3993 I'm planning on experimenting with adding some visual cue to indicate which actions have sub-actions.
> Remove remaining >> signs from interaction menu

- addons/goggles/ACE_Settings.hpp
- addons/goggles/CfgEventHandlers.hpp
- addons/goggles/XEH_postInit.sqf
- addons/goggles/functions/fnc_applyGlassesEffect.sqf
- addons/goggles/functions/fnc_externalCamera.sqf
- addons/goggles/functions/fnc_handleKilled.sqf
- addons/goggles/functions/fnc_removeGlassesEffect.sqf
- addons/goggles/stringtable.xml
- Add a ace_setting for change the level of effect simulation or goggles.
Can chose between none, tint/colorCC and full dust/dirt/rain/rotorwash.
XEH_postInit diff is a mess but it's mainly just skipping adding firedEH/PFEH depending on setting.
Not sure if this should be a client setting??
> Add goggle setting for level of effects

- addons/explosives/functions/fnc_canDefuse.sqf
- addons/explosives/functions/fnc_defuseExplosive.sqf
- addons/explosives/functions/fnc_startDefuse.sqf
Fix #4074
- Workaround for naval mines not working with deactivate
- Add "isNotSwimming" exception to defuse progress bar
> Allow defusing naval mines

- optionals/compat_rhs_usf3/config.cpp
Required because of 
```
modelOptics = "\z\ace\addons\javelin\data\reticle_titan.p3d";
```
> Add ACE javelin as required addon dependency

- addons/common/functions/fnc_blurScreen.sqf
- When updating language-arma-atom I noticed this public function is missing description and example (and was not included in the package for that reason). This just adds it as per our guidelines.
> Add description and example to blur screen function

- addons/vehicles/CfgWeapons.hpp
Fix #4098
Missing:
"500Rnd_65x39_Belt"
"500Rnd_65x39_Belt_Tracer_Red_Splash"
"500Rnd_65x39_Belt_Tracer_Green_Splash"
"500Rnd_65x39_Belt_Tracer_Yellow_Splash"
> Add missing vanilla magazines to LMG_Minigun

- addons/optionsmenu/gui/pauseMenu.hpp
Stick ace_options button placement to top left
so it doesn't interfere with apex singleplayer menu
> Fix MainMenu Ace_Options Placement to top left

- addons/microdagr/functions/fnc_updateDisplay.sqf
- Fix the degree displays on the MicroDAGR always having a trailing `.0`
> Fixed MicroDAGR trailing zero

- addons/fastroping/XEH_postInit.sqf
- #4111 to `release`
- Add a keybind (default unbound) to cut fastroping ropes
> Cut ropes keybind

- addons/dogtags/functions/fnc_ssn.sqf
Passes @bux578 's splendid test code: https://codeshare.io/jorDJ
Uses all chars of long names, and remixes input so that "A" does not always turn into 5
> Improve SSN hash

- addons/missileguidance/functions/fnc_checkLos.sqf
Fix #4126
RHS T72 `getPosASL` point is very low and can be bellow terrain level.
`ASLtoAGL getPosASL cursorObject` = [2457.5,820.846,-0.0508118]
So it would fail the terrainIntersectASL check.
> Fix terrain LOS check for vehicles with low getPos

- addons/particles/script_component.hpp
I am not sure why, but pboProject fails to build particles:
```
In File z\ace\addons\particles\script_component.hpp: Line 47 Cannot Handle single# in defines
```
This "fix" should work the same.
> Change macro for pboProject

- wiki/development/coding-guidelines.md
- Fix typos
- Correct some wording
- ~~Make formatting consistent (no empty lines after titles and before code blocks)~~ Kramdown needs this
- Use code syntax (`code`) for all commands
- Replace ACE3 events with CBA events (links to CBA wiki)
- Replace dead commy2's Gist link for CBA macros to CBA macros file in CBA repo
> Update coding guidelines (fix typos, wording, formatting, links)

- addons/spectator/functions/fnc_setCameraAttributes.sqf
Fix #3842
PFEH FUNC(handleCamera) will set camera position using GVAR(camPos)
> Fix spectator map click not changing cam pos

- addons/refuel/functions/fnc_refuel.sqf
- addons/refuel/functions/fnc_turnOff.sqf
- addons/refuel/functions/fnc_turnOn.sqf
- Fix #4128 
- The PFH runs constantly while the nozzle is connected, even when not refueling, thus old time has to be set in `turnOn` function.
> Fix refuel not respecting time acceleration and pause

- addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf
- impmrove speed of creating actions for buildings
On mission from jonpas with lots of wall objects inside of a warehouse, there was a huge stutter when creating actions (the building had ~8 doors + 2 ladders).
This PR improves the time from 137.893 ms -> 1.17631 ms
Thanks to @esteldunedain for the idea from the casing PR.
> Improve creation time of house actions dummy

- addons/main/script_macros.hpp
- Updates our log macros to also log file and line number
```
[ACE] (minedetector) ERROR: unit does not exist [<NULL-object>]
vs.
[ACE] (minedetector) ERROR: unit does not exist [<NULL-object>] File: z\ace\addons\minedetector\functions\fnc_playDetectorSound.sqf Line: 22
```
- except "INFO"
> log file and line numbers for warnings/errors/debug msgs

- addons/repair/functions/fnc_addRepairActions.sqf
This tweaks the placement of repair track actions.
The BW Leopard model center is at ground level so -1.75 below that is no good.
The hitpoint selection is usually pretty good in Z and X axis, but the Y is usually no good.
This uses the selection position and just sets the Y to 0.
Using this to test placement (red = old position, blue = selection, green = new):
```
addMissionEventHandler ["Draw3D", {
_selPos = cursorTarget modelToWorldVisual [-1.75, 0, -1.75];
drawIcon3D ["\A3\ui_f\data\map\markers\military\dot_CA.paa", [1,0,0,1], _selPos, 1, 1, 0, "1.75", 1, 0.02, "PuristaMedium"];
_selPos = cursorTarget modelToWorldVisual [1.75, 0, -1.75];
drawIcon3D ["\A3\ui_f\data\map\markers\military\dot_CA.paa", [1,0,0,1], _selPos, 1, 1, 0, "1.75", 1, 0.02, "PuristaMedium"];
{
_selection = getText …
```
> Fix track repair selection placement

- addons/medical/functions/fnc_modifyMedicalAction.sqf
- addons/medical/functions/fnc_treatmentAdvanced_bandageLocal.sqf
- decrease needed blood loss on selection to turn icon red. (Largest
wound bleedingRate is only 0.1)
- Don't print warning for basic medical bandage not having sub configs
> Minor tweaks to medical

- addons/dragging/CfgEventHandlers.hpp
- addons/dragging/XEH_postInit.sqf
- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_dragObject.sqf
- addons/dragging/functions/fnc_handleAnimChanged.sqf
- Installs the animChanged EH on demand instead of having it running all the time for all units
- Also Fix CBA_fnc_addPlayerEventHandler
animChanged runs on all units (including non-local)
for units moving it fires about 1/second/unit
With 100+ units the overhead adds up (about 1 ms / second for 100 units on my system)
This installs the EH just for the unit that starts dragging/carrying
> dragging - Don't run animChanged event on all units

- addons/cargo/CfgEventHandlers.hpp
> Fix static weapons not being loadable in cargo

- wiki/development/coding-guidelines.md
> Add createVehicle(Local) performance consideration to coding guidelines

- wiki/development/coding-guidelines.md
- Title
- Follow-up on #4211 and @commy2 's note.
> Improve createVehicle(Local) performance consideration description

- addons/captives/CfgEden.hpp
Fix default values, so we don't get two custom attributes per unit, even when the unit is not handcuffed/surrendered
Pretty simple fix, saves a lot of space when dealing with large framework scale SQMs
> Fix the captive module from creating attributes when not needed

- addons/medical/functions/fnc_treatmentAdvanced_bandageLocal.sqf
GVAR(healHitPointAfterAdvBandage) was only setting the hitpoint, but not changing the bodyPartStatus.
This caused later damage to always redamage the previously healed hitpoints because `FUNC(handleDamage_advancedSetDamage)` uses bodyPartStatus to set 4 hitpoints when taking new damage.
This changes advanced bandage to clear damage from bodyPartStatus when a hitpoint has been fully healed. It then calls `FUNC(handleDamage_advancedSetDamage)` to actually reset the damage.
Test case:
```
[] spawn { 
[player, 0.8, "leg_r", "bullet"] call ace_medical_fnc_addDamageToUnit; 
sleep 0.25; 
[player, "bandage", "leg_r"] call ace_medical_fnc_treatmentAdvanced_bandageLocal; 
sleep 0.25; 
[player, 0.2, "body", "bullet"] call ace_medical_fnc_addDamageToUnit; 
};
```
Would leave the unit limping as the …
> Heal hitpoint after bandage sets bodyPartStatus

- addons/logistics_wirecutter/CfgWeapons.hpp
The current mass makes it take a LOT of inventory space (~half of
an assault pack) which makes it impractical to carry around as a tool.
Lower it to use the same mass as the entrenching tool.
> lower wirecutter item mass

- addons/dogtags/$PBOPREFIX$
- addons/dogtags/Dogtag.hpp
- addons/dogtags/README.md
- addons/dogtags/config.cpp
- addons/dogtags/functions/fnc_addDogtagActions.sqf
- addons/dogtags/functions/fnc_addDogtagItem.sqf
- addons/dogtags/functions/fnc_bloodType.sqf
- addons/dogtags/functions/fnc_canCheckDogtag.sqf
- addons/dogtags/functions/fnc_canTakeDogtag.sqf
- addons/dogtags/functions/fnc_checkDogtag.sqf
- addons/dogtags/functions/fnc_checkDogtagItem.sqf
- addons/dogtags/functions/fnc_getDogtagData.sqf
- addons/dogtags/functions/fnc_getDogtagItem.sqf
- addons/dogtags/functions/fnc_sendDogtagData.sqf
- addons/dogtags/functions/fnc_showDogtag.sqf
- addons/dogtags/functions/fnc_ssn.sqf
- addons/dogtags/functions/fnc_takeDogtag.sqf
- addons/dogtags/script_component.hpp
- Add `$PBOPREFIX$`
- Improve function headers with examples
- Use `QQGVAR` macro instead of `QUOTE(QGVAR())`
- Add @esteldunedain do maintainers
- Update CfgPatches with new author stuff
- Add beautified component name
How was that missed... you know who you are...
> Add dogtags $PBOPREFIX$ and Improve function headers

- addons/javelin/XEH_pre_init.sqf
- addons/javelin/functions/fnc_onOpticDraw.sqf
Releated to #4079 , javelin can be the first thing to add the addActionEventHandler and get index 0.
- Only real change is in FUNC(enableFire): `_firedEH > 0` would fail if index is 0
- moved func defines to preInit
> Fix javelin fire block not being removed

- addons/cookoff/functions/fnc_engineFire.sqf
The funtion would call itself on other machines, where it would rebound to all other machines again. n^2
It's not infinite thanks to the `exitWith` above, but still unecessary.
> fix bug which would cause unecessary echo network traffic

- addons/advancedthrowing/CfgVehicles.hpp
- addons/advancedthrowing/XEH_postInitClient.sqf
- addons/advancedthrowing/functions/fnc_drawArc.sqf
- addons/advancedthrowing/functions/fnc_drawThrowable.sqf
- addons/advancedthrowing/functions/fnc_exitThrowMode.sqf
- addons/advancedthrowing/functions/fnc_pickUp.sqf
- addons/advancedthrowing/functions/fnc_prepare.sqf
- addons/advancedthrowing/functions/fnc_prime.sqf
- addons/advancedthrowing/functions/fnc_throw.sqf
- addons/advancedthrowing/functions/fnc_updateControlsHint.sqf
For PR #3477
- FUNC(drawThrowable): Fix issue getting correct `_throwableMag` when you have a primed grenade. If you had nothing in inventory it would end up being nil otherwise it would use the wrong grenade type's initSpeed. This was a little messy to fix because we just have the ammo type and there could possibly be multiple magazines that use the same ammo. Uses a lookup hash that gets generated at the start.
- FUNC(prepare): When you have no grenades in inventory and picking up a live grenade it would fail because selectNextGrenade returned true.
- Handle detaching from ace_attach.
> Improvments for advanced throwing branch

- addons/map/functions/fnc_blueForceTrackingUpdate.sqf
add BlueForceTracking filtering via an object variable
There's no good workaround for this:
* creating a dummy unit on [0,0,0] and making it leader prevents
grp members from entering vehicles
* joining group of a different side prevents grp members from seeing
blueforce tracking markers of their original side
Usage (_obj can be group or unit, depending on BFT_ShowPlayerNames):
_obj setVariable ["ACE_map_hideBlueForceMarker", true];
> add BlueForceTracking filtering via an object variable

- docs/wiki/framework/interactionMenu-framework.md
- Title
Hyphens only show up fine in local environment, dots don't, with new line dots show up correctly as well. Something to keep in mind.
> Fix list in interaction menu framework documentation

- docs/wiki/framework/events-framework.md
- Title
- Use `target="_blank"` for CBA Events documentation link
- ~~Add dots after section numbers~~
- Use code for component names
> Fix Events Framework documentation 3.1 section

- docs/wiki/development/coding-guidelines.md
- docs/wiki/framework/ui-framework.md
- Make all closing points follow documentation guidelines
```
1.
1.1
1.1.1
```
It appears I was the only one using the wrong style, I'll just shoot myself. :boom: :gun:
> Streamline closing points on wiki pages

- docs/_includes/dependencies_list.md
- tools/extract_dependencies.py
- Update `extract_dependencies.py` tool to extract them directly into `docs/_includes/dependencies_list.md`, had to be copied previously due to different branch
- Ignore `main` component as that is always required (and so denoted in the wiki page)
- Add newlines between Jekyll `if` statements for better readability
- Force Python to write LF line endings
> Streamline dependencies extraction tool

- addons/main/script_macros.hpp
ref https://github.com/CBATeam/CBA_A3/pull/466/
This is safe to merge now and something we want soon as sync TRACE is broken with current CBA master.
It is backwards compatible with last CBA 3.0 release for developers without dev CBA.
Whenever we switch to CBA 3.1 we can clean this up (and all modules script components).
> Update CBA_DEBUG_SYNCHRONOUS macro for new CBA

- addons/medical/ACE_Settings.hpp
- addons/medical/XEH_postInit.sqf
- addons/medical/functions/fnc_createLitter.sqf
- addons/medical/functions/fnc_handleCreateLitter.sqf
- addons/medical/functions/fnc_litterCleanupLoop.sqf
Ref discussion in #3537
- Uses `createSimpleObject` for medical litter
- ace_medical_litterSimulationDetail is now a server setting with global effects
Benifits:
- creation and cleanup loop code only runs on server
- no physX
- Objects do not show up in `(entities "")` - e.g. CBA xeh fallback won't waste time on them!
Drawbacks:
- @Glowbal mentioned that clients lose the ability to set their own litter levels.
```
_start = diag_tickTime;
_created = 0;
for "_xPos" from -25 to 25 do { 
for "_yPos" from 0 to 25 do { 
_position = getPosATL player; 
_position = _position vectorAdd [_xPos, _yPos, 0]; 
// _litterObject = createSimpleObject ["z\ace\addons\medical\data\littergeneric_bandages1.p3d", [0,0,0]]; 
_litterObject = "ACE_MedicalLitter_bandage1" createVehicleLocal [0,0,0];
_litterObject …
```
> Use createSimpleObject for medical litter

- addons/medical/functions/fnc_setUnconscious.sqf
- addons/medical/functions/fnc_treatmentBasic_epipen.sqf
Should fix #4250 
Manual calls to `FUNC(setUnconscious)` with set = false will clear the `inReviveState` var.
Only things calling the function like this are the epiPen and the zeus module.
> Clear reviveState when calling setUnconscious

- addons/hearing/config.cpp
- `"A3_Characters_F"` and `"A3_Characters_F_Kart"` are already required by `ACE_Main`
> Remove superfluous requiredAddons in hearing

- .travis.yml
- tools/deploy.py
- tools/extract_dependencies.py
- Run `extract_dependencies.py` (dependency extractor for wiki pages - Jekyll include) through Travis. If there are changes it will commit them through @ace3mod user. Will only perform it on commits on `master` and will skip another Travis run on that commit.
- Change token used for deployment to @ace3mod's instead of @KoffeinFlummi's.
> Run documentation dependencies extractor on Travis deployment

- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_handleDamage.sqf
Prevents the tank from cooking off when the commander turret takes damage.
Subturrets often have the same hitpoint name: (2x HitTurret)
`["HitHull","HitEngine","HitLTrack","HitRTrack","","","","","HitTurret","HitGun","HitTurret","HitGun"]`
The commander's turret was matching the `ammoLocation` and the tank was cooking off with 2 12.7mm shots to it.
I did some quick testing with the RHS BMD-1s which have 8 HitTurret hitpoints and it seemed to be ok, but this does assume that the main HitTurret will be listed first.
> Don't cookoff when commander turret is hit

- docs/wiki/framework/settings-framework.md
- Add a note that clarifies there is no need for a settings class in the serverconfig.
> Add note about no settings class for serverconfig

- addons/overheating/CfgVehicles.hpp
- addons/overheating/XEH_PREP.hpp
- addons/overheating/functions/fnc_canCheckSpareBarrelsTemperatures.sqf
- addons/overheating/functions/fnc_canSwapBarrel.sqf
- addons/overheating/functions/fnc_loadCoolestSpareBarrel.sqf
- addons/overheating/functions/fnc_sendSpareBarrelsTemperaturesHint.sqf
- Allow users to define custom spare barrel for a weapon 
- ACE_Overheating_barrelClassname = "GREY_GPMG_SpareBarrel"; to define a weapons spare barrel classname.
- If no custom spare barrel is defined then 'ACE_SpareBarrel' is used.
> Definable classname for Spare Barrel

- addons/common/XEH_postInit.sqf
- addons/noradio/XEH_postInit.sqf
It is possible that `CBA_fnc_addPlayerEventHandle`r has already been called and run,
We will NOT get any events for the initial state, so manually set ACE_player
e.g. in preInit or SP mission init.sqf do
```
["loadout", {
diag_log text format ["%1 - Loadout change - %2", time, _this];
}] call CBA_fnc_addPlayerEventHandler;
```
and `ace_player` will never bet set because the event has already happened.
Skimmed our use of the function and fixed noradio as well, everything else seemed ok.
> Fix null ace_player from early call to addPlayerEH

- addons/interact_menu/functions/fnc_addActionToClass.sqf
- addons/interact_menu/functions/fnc_createAction.sqf
- docs/wiki/framework/interactionMenu-framework.md
Handles the mess of adding actions to all units.
E.G. can add class actions to `CaManBase`.
> Allow inheritance for addActionToClass

- addons/cargo/CfgVehicles.hpp
- addons/interaction/CfgVehicles.hpp
- addons/interaction/XEH_PREP.hpp
- addons/interaction/functions/fnc_getVehiclePos.sqf
- addons/interaction/functions/fnc_getVehiclePosComplex.sqf
Fix #4233
Adds a varient of getVehiclePos function that should work better for air units.
Allows us to define a custom bounding box for a vehicle to limit to the main hull of a air unit and ignore it's wings or rotors.
Example, green is boundingBoxReal, blue is the effective custom one:
this function doesn't require higher scoped variables, so we can use it externally.
For example to get get the effective distance to a vehicle:
```
private _playerPosASL = eyePos _player;
private _targetInteractionPos = [_target, _playerPosASL] call FUNC(getVehiclePosComplex);
(ASLtoAGL _playerPosASL) distance (_target modelToWorld _targetInteractionPos)
```
> Improve interaction position for air units.

- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_afrf3/config.cpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/config.cpp
- Add rearm/refuel/repair actions for the applicable RHS AFRF vehicles (GAZ-66s, Urals)
- Add rearm/refuel/repair actions for the applicable RHS USF vehicles (M113 supply vehicle, HEMTT A4s)
So macros are a strange and new experience for me, full of wonder and amazement. I've never really worked with them before and while I think I've done it without screwing it up, someone should look them over before this is approved.
Also because setting up those three also requires disabling the vanilla equivalent system, should I add them to the requiredAddons?
> ACE rearm/refuel/repair actions for RHS vehicles

- addons/chemlights/XEH_postInit.sqf
- addons/chemlights/functions/fnc_compileChemlightMenu.sqf
- addons/chemlights/functions/fnc_isIRClass.sqf
- addons/chemlights/functions/fnc_removeIR.sqf
- addons/chemlights/functions/fnc_throwEH.sqf
- addons/chemlights/functions/fnc_throwIR.sqf
Minor cleanup of @voiperr 's chemlights
For the fired event handlers:
`FUNC(throwEH)` only does anything for local units so we can remove `firedPlayerNonLocal`; 
and I don't think AI have any idea how to use chemlights so I think we can skip `firedNonPlayer` as well?
Add support for handling primed IR grenades for advanced throwing (@jonpas)
> Chemlights cleanup

- addons/chemlights/CfgWeapons.hpp
- Title
- Apparently also remove excessive whitespace
> Fix Chemlight Shield Green and Red descriptions

- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_displayPatientInformation.sqf
- addons/medical/functions/fnc_getBloodVolumeChange.sqf
- addons/medical/functions/fnc_handleUnitVitals.sqf
- addons/medical/functions/fnc_init.sqf
- addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf
- addons/medical/functions/fnc_treatmentIVLocal.sqf
- Increase flow rate for basic medical (41ml/sec in an arm vein probably doesn't feel great :smile: )
- Don't queue bags - (2 bags flow twice as fast, instead of just doubling the total to add)
Uses a single unit variable `QGVAR(ivBags)` to hold all bag info.
We can skip calculations and syncing if the value is nil (no bags) which should be the common case.
> Increase blood bag flow rate for basic medical

- addons/medical/functions/fnc_handleDamage_advanced.sqf
- addons/medical/functions/fnc_handleDamage_wounds.sqf
Ref #4206
Fire damage comes in as a continuous stream, but each bit is lower than the threshold to trigger unknown damage. This saves the little chunks until together they addup to something that would be enough to trigger a wound from the extension.
Without this we add damage to `bodyPartStatus` but never create any wounds, so the damage would not be removable when in basic medical or healAfterBandage.
This also makes damage type `""` into `unknown` which is consistent with the non-dll wound code.
> Bundle fire damage into larger chunks

- addons/realisticweights/$PBOPREFIX$
- addons/realisticweights/CfgWeapons.hpp
- addons/realisticweights/config.cpp
- addons/realisticweights/script_component.hpp
- Tweak all weapon weights so the value shown in the inventory is correct.
The purpose of this is that all weapons have a comparable weight value, which is useful both for vanilla stamina and advanced fatigue.
Could potentially break loadouts that put weapons in backpacks, but since that is such a rarity and the majority of weights has been lowered I think this is totally fine.
The ASP-1 KIR and the Cyrus have not been adjusted since they are not based on real weapons and their weight value is close to what I would estimate.
> Realistic weights

- addons/medical_ai/$PBOPREFIX$
- addons/medical_ai/CfgEventHandlers.hpp
- addons/medical_ai/README.md
- addons/medical_ai/StateMachine.hpp
- addons/medical_ai/XEH_PREP.hpp
- addons/medical_ai/XEH_postInit.sqf
- addons/medical_ai/XEH_preInit.sqf
- addons/medical_ai/XEH_preStart.sqf
- addons/medical_ai/config.cpp
- addons/medical_ai/functions/fnc_canRequestMedic.sqf
- addons/medical_ai/functions/fnc_healSelf.sqf
- addons/medical_ai/functions/fnc_healUnit.sqf
- addons/medical_ai/functions/fnc_isInjured.sqf
- addons/medical_ai/functions/fnc_isSafe.sqf
- addons/medical_ai/functions/fnc_playTreatmentAnim.sqf
- addons/medical_ai/functions/fnc_requestMedic.sqf
- addons/medical_ai/functions/fnc_wasRequested.sqf
- addons/medical_ai/functions/script_component.hpp
- addons/medical_ai/script_component.hpp
- Make AI units heal themselves, each other and players in their group
- This only works when the AI units have to deal with basic medical (they won't do anything when the player is using advanced medical or advanced medical is enabled for AI units) due to the complexity of advanced medical
Some details on the implementation:
- This uses a CBA state machine, so performance will not be an issue at all, no matter the amount of AI
- AI units will treat themselves when not suppressed and not having shot at enemies since 30 seconds
- Only medic units will heal other units in their group, and only when they are not injured or under fire themselves
- Since AI units usually don't get custom loadouts with a balanced medical equipment they do not consume …
> Medical AI

- addons/nametags/ACE_Settings.hpp
- addons/nametags/CfgVehicles.hpp
- addons/nametags/functions/fnc_onDraw3d.sqf
- addons/nametags/stringtable.xml
- Make nametags fade depending on distance to the screens center
PS: This component needs some cleanup.
> Fade nametags towards screen border

- addons/overheating/CfgMagazines.hpp
- addons/overheating/config.cpp
Close #4325
Needs 1.64 to take effect, but should be fine on 1.62
> Add spare barrel to VA in 1.64

- addons/advanced_throwing/CfgVehicles.hpp
- addons/advanced_throwing/functions/fnc_canPrepare.sqf
- addons/advanced_throwing/functions/fnc_renderPickUpInteraction.sqf
- addons/advanced_throwing/script_component.hpp
- addons/chemlights/functions/fnc_throwEH.sqf
- addons/chemlights/functions/fnc_throwIR.sqf
- Title
Initially this was meant to fix mortar shells from being picked up, but they inherit from `GrenadeBase` as well, would be small overhead to filter them. However, it seems only smoke shell is the problem, with which I don't really have a problem with being picked up and thrown further.
> Fix pick up delay and IR chemlights, prevent picking up GL and mortar smoke shells

- addons/grenades/XEH_postInit.sqf
- addons/grenades/functions/fnc_throwGrenade.sqf
Neither of these should have really caused any problems, 
but this should make things cleaner when using advanced throwing.
> Grenades - disable throw mode / keybind if advThrow

- addons/explosives/scripts/TripflareEffect.sqf
- Use directCall on the tripflare effect
The beforeDestroyScript is run in scheduled environment (`canSuspend` returns true).
> Use directCall on tripflare effect

- addons/advanced_throwing/XEH_postInitClient.sqf
- addons/advanced_throwing/functions/fnc_canPrepare.sqf
- addons/advanced_throwing/functions/fnc_drawThrowable.sqf
- addons/advanced_throwing/functions/fnc_exitThrowMode.sqf
- addons/advanced_throwing/functions/fnc_prime.sqf
- addons/advanced_throwing/functions/fnc_throw.sqf
- Fix floating primed IR grenades on exiting throw mode without throwing - fix #4362
- Block vanilla throwing while a throwable is prepared with Advanced Throwing - fix #4363
- Add last thrown time support for vanilla throwing
- Add last thrown time support for dropping primed throwable
Author should really be @BaerMitUmlaut here, I may have abused him and stole all his time by making him do the research. :worried:
> Fix Advanced Throwing floating IR grenades and block vanilla throwing

- addons/advanced_throwing/functions/fnc_drawThrowable.sqf
- addons/advanced_throwing/functions/fnc_exitThrowMode.sqf
- addons/advanced_throwing/functions/fnc_prepare.sqf
- addons/advanced_throwing/functions/fnc_prime.sqf
- addons/weaponselect/XEH_postInit.sqf
- Fix vanilla throw block for primed throwables.
- Simplify muzzle ammo handling (can only be 0 or 1, setting it to 1 without an applicable throwable in the inventory won't have any impact).
- Fix select next grenade cycling between first 2 throwables due to `setAmmo` - fix #4375 
Sent to @alganthe for testing, he somehow keeps finding bugs with this magical _bugless_ throwing...
> Fix Advanced Throwing vanilla throw block for primed throwables

- docs/wiki/development/documentation-guidelines-and-tips.md
- Fix large white space due to Jekyll code being parsed inside markdown code block.
> Escape jekyll code in documentation guidelines page

- addons/cookoff/ACE_Settings.hpp
- addons/cookoff/XEH_PREP.hpp
- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_cookOffBox.sqf
- addons/cookoff/functions/fnc_handleDamage.sqf
- addons/cookoff/stringtable.xml
- Add an option to enable ammo boxes to cook off using the new ammunition detination
- Currently only occurs when hit with explosive ammo, should look into things like tracers and the incendiary grenade
- Uses the vanilla ammo box particle effects for smooth transition to actual destruction and consistent look
Note that ammo boxes must be kept "alive" until cook off is finished, because their destruction simulation makes them sink and disappear. Hence cook off is initiated from the handle damage event - unlike vehicles where their cook off occurs after destruction has occurred.
> Add ammo box cookoff

- tools/extract_dependencies.py
- Add `optionals` support to extract dependencies tool
- Assure paths are valid
- Fix writing of a "component" without a `config.cpp` file (not a real component)
> Add optionals support to extract dependencies tool

- addons/cookoff/CfgVehicles.hpp
- addons/cookoff/functions/fnc_engineFire.sqf
- addons/cookoff/functions/fnc_handleDamage.sqf
- addons/grenades/functions/fnc_incendiary.sqf
- addons/repair/CfgVehicles.hpp
- addons/repair/XEH_preInit.sqf
- destroyable wheels (including spare wheels)
- `GVAR(engineSmokeOffset)` for smoke effect
- fix `hithull` vs `hitbody` mixup
- delete destroyed `ACE_RepairItem` objects (after 5 seconds)
todo:
> incendiary and cookoff improvements

- addons/cookoff/CfgEden.hpp
- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/config.cpp
- docs/wiki/framework/cookoff-framework.md
When a vehicle is destroyed / killed, it will start secondairy explosives. If a mission has a single vehicle that the misson maker wishes to be destroyed, right now it will start secondairy explosives (with ammo cook off (#4376) it becomes a real party). This PR allows mission makers to disable cook off for individual vehicles.
This PR also adds initial framework documentation for cook off.
> Add object attribute to disable cookoff for individual vehicles

- addons/cookoff/CfgVehicles.hpp
- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_blowOffTurret.sqf
- addons/cookoff/stringtable.xml
- make it so that blown off turrets are added to all curators that own the wreck
- it also adds icons to the turrets. those huge ass question marks would be annoying, so I just use the corresponding tanks icon
- also OCD formatting
> auto add blown off turrets to curator

- addons/grenades/functions/fnc_incendiary.sqf
skips creating fire/effects at [0,0,0] if projectile is dead / deleted
> Skip incindinary effects if projectile is null

- addons/advanced_ballistics/functions/fnc_initializeTerrainExtension.sqf
Ref #4386
Adds 1 or 2 lines of debug info for the advanced ballistics terrain extension.
I don't think there is a problem, but this could help diagnose any possible issues.
> Add AB Terrain Extension Logging

- docs/wiki/feature/grenades.md
- Use Jekyll `baseurl` instead of hard coded url
See #4442
> Fix grenade docs base url

- addons/medical_ai/functions/fnc_canRequestMedic.sqf
- Filter player medics for Medical AI, so players will never become the assigned medic of a unit (in case there is both an AI and a player medic in the group)
> Medical AI: Filter player medics

- addons/advanced_fatigue/XEH_postInit.sqf
- addons/common/HintConfig.hpp
- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_watchVariable.sqf
Adds a dev function to easily watch multiple variables on the main display.
For numbers is can show delta change, and ratio if given min/max.
Supports any variable type.
Example showing fatigue values:
I often run out of debug watch windows and this is live updating; so you can use it to easily check vars on `cursorObject`.
> Debugging tool to watch variables on main display

- addons/optionsmenu/CfgEventHandlers.hpp
- addons/optionsmenu/gui/pauseMenu.hpp
- Currently the ACE menu is not shown in the main menu, no matter if you have `-world=empty` or not
- This is because BI changed some things around in 3den. And now the mission does not exist before the Main display is created
- therefore there is no way to check if the main menu mission is enabled
- there is a weird bug that causes the main menu to reload when you confirm the menu where you change your avatar with `OK`
- this makes the ACE menu button show up, but only if you have the main menu mission enabled
- turns out it's pretty bugged though. You can click all the other buttons which interfers with our menu
- this happens even when you manually hide the "spotlight" thingies in the middle with some additional scripting
- I therefore decided to …
> fix broken ace menu in main menu

- addons/advanced_throwing/functions/fnc_drawArc.sqf
- docs/wiki/feature/advanced-throwing.md
Ends grenade arc drawing when throw will collide with the GEOM or FIRE LOD.
Unfortunately many CUP buildings have bulletproof windows that do not pass grenades.
There are also other cases where we could show a throw as being safe when it will be blocked such as A3 Gratings.
However this also could introduce warnings when the shot will be fine.
But I believe the worst thing we can do is to tell the user that a shot will be safe when it could fail and kill their team.  Warning about a "false negative" is far less critical.
- Neither of these shots are possible, but would have been shown as safe:
- This shot is actually fine, but we still show a warning:
> End path drawing when passing through Geom/Fire

- addons/advanced_throwing/CfgEventHandlers.hpp
- addons/advanced_throwing/XEH_postInit.sqf
Fixes 2 minor issues with advanced throwing
- If advanced throwing is up, and player brings up map; clicking on the map would throw a grenaded
Now exits throw mode
- Custom firedXeh event handler was only run on clients
Renamed to XEH_postInit and moved to above the `!hasInterface` line.
> Fix throwing from map screen - global XEH

- addons/advanced_throwing/functions/fnc_prime.sqf
- optionals/compat_rhs_afrf3/CfgAmmo.hpp
Quick version of how RHS impact grenades work:
- magazine ammo is type `rhs_ammo_rgn`
- after creation rhs's script deletes and recreates as `rhs_ammo_rgn_sub` with same position and velocity
- on impact, it's deleted again and recreated as `rhs_ammo_rgn_exp`
Even without manually priming, there is delay between "pulling the pin" and throwing.
In that time the ammo is deleted and replaced.
User throws nothing and a live grenade is dropped at their feet.
Adds a simple config `ace_advanced_throwing_replaceWith` that will replace one ammo with another.
Base grenade ammo works fine, but it loses the scripted impact.
> Handle RHS impact grenades (RGN/RGO)

- addons/dogtags/config.cpp
Oddly #4446 broke passenger interaction because `ACE_Dogtag` ends up being before `MainActions`.
Adding requiredAddons will fix mod load order problems.
Should also take a look at making `ace_interaction_fnc_addPassengerAction` more robust.
> Fix passanger interaction

- addons/frag/functions/fnc_findReflections.sqf
PFEH never exited
Only effects when ace_frag_ReflectionsEnabled is true (non default)
Thanks to kingsley from slack for finding this
> Fix frag - reflectionsEnabled

- addons/hearing/functions/fnc_firedNear.sqf
- optionals/compat_rhs_usf3/CfgAmmo.hpp
Fix loudness of spotting rifle on the SMAW
Because of how launchers in Arma work the ammo needs to be type `RocketBase`
Which fired near would set as caliber 200 when it should be 9mm
Replaces joko's #2371 . 
This uses existing config entry `ACE_caliber` which should make things simpler.
> Fix spotting rifle loudness

- addons/missionmodules/functions/fnc_moduleAmbianceSound.sqf
Fix #4418
- Remove leading `\` for configfile sounds
- Cleanup randomized location code
Config has leading slash, but playSound doesn't want it
`playSound3d ["\a3\Ui_f\data\Sound\CfgNotifications\scoreRemoved.wss", player];` // throws rpt error
`playSound3d ["a3\Ui_f\data\Sound\CfgNotifications\scoreRemoved.wss", player];` // works
> Fix Ambient Sounds

- addons/ai/CfgWeapons.hpp
-  restore default aiDispersionCoef for vanilla weapons.
> Removed aiDispersionCoef for vanilla weapons

- addons/common/functions/script_component.hpp
`ERROR(` use of `throw` causes script error
None of the others are used.
> Cleanup old common macros

- addons/common/functions/fnc_checkFiles.sqf
- changes:
```
[ACE] (common) INFO: ACE is version 3.7.0.6.
[ACE] (common) INFO: CBA is version [3,1,0,160928] [min required [3,1,0]]
```
to:
```
[ACE] (common) INFO: ACE is version 3.7.0.6.
[ACE] (common) INFO: CBA is version 3.1.0.160928 (min required 3.1.0)
```
OCD
> fix formating of CBA version check

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_arithmeticGetResult.sqf
- addons/common/functions/fnc_arithmeticSetSource.sqf
Allows add/removing blocks of code that return numbers.
And performing arithmetic operations on those sets.
Allows a variable number of sources to provide input into a final calcuation. Like Aim Coefficent or possibly `fadeSound`)
Inspired by Baer's AF duty system.
Example:
```
[missionNamespace, "ace_AimCoef", "ace_medical", {
linearConversion [0,1,(ace_player getVariable "ace_medical_pain"),1,0.2,true]
}] call ace_common_fnc_arithmeticSetSource;
[missionNamespace, "ace_AimCoef", "ace_advancedFat", {
(1.0 + _fatigue ^ 2 * 0.1);
}] call ace_common_fnc_arithmeticSetSource;
[missionNamespace, "ace_AimCoef", "min"] call ace_common_fnc_arithmeticGetResult;
```
First arg can be any type of namespace (object, location, `missionNamespace`)
Can use the namespace in the code block:
```
[player, …
```
> Functions to perform arithmetic ops on sets

- addons/fastroping/CfgVehicles.hpp
Close #4490
I'm not sure if something changed on the wildcat or on our model??
I had done the reverse for the armed version: d7b0bde1ca3e6c455d63538f773733a615bc9b0b
Changing x-offset from positive to negative, which is the opposite of what this one needed,
> Fix FRIES attach point for unarmed wildcat

- tools/publish.py
This should lets us automate the publishing of ace to steam workshop.
It will let us upload each compatibility to separate mods
I believe next RHS will be available on steamworkshop, 
so this will let users get ACE, RHS and ACE's RHS compat all through steam.
This will take some final adjustments like actually creating the new mods on the workshop
> Add tool to upload ace and compats to workshop

- addons/advanced_fatigue/functions/fnc_mainLoop.sqf
- Caps assumed max speed while prone.
- This ensures that moves like diving to the ground while sprinting are not calculated as crawling with running speed.
- fixes #4481
the max speed I could do while crawling is 1.33_ with rifle. Don't think there is anything faster than 1.5 aside from the transitions we try to fix here ofc.
> fix fatigue when diving while sprinting

- addons/nametags/XEH_postInit.sqf
> remove civilian rank icons from nametags

- addons/dogtags/XEH_PREP.hpp
- addons/dogtags/XEH_postInit.sqf
- addons/dogtags/XEH_preInit.sqf
- addons/dogtags/functions/fnc_canCheckDogtag.sqf
- addons/dogtags/functions/fnc_canTakeDogtag.sqf
- addons/dogtags/functions/fnc_disableFactionDogtags.sqf
- adds function to disable dogtags for certain factions (e.g. rebels)
- use it to disable dogtags for civilians
> add function to disable dogtags for factions, and disable for civilians

- addons/refuel/XEH_PREP.hpp
- addons/refuel/functions/fnc_maxDistanceDropNozzle.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
- Fix #4523 
- Move drop PFH into separate function that gets added on progress bar success, it was getting added before and was exiting too fast in case of picking up from a direction that made the rope even longer.
> Fix fuel nozzle disconnect at maximum hose distance

- addons/medical/XEH_PREP.hpp
- addons/medical/functions/fnc_addPain.sqf
- addons/medical_damage/functions/fnc_woundsHandler.sqf
- addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf
- this adds the planned addPain function.
- it also caps the pain at 1 to avoid scenarios where > 3 morphine injectors are needed
- new received pain is scaled depending on the amount of already existing pain
this could be used to knock out or wake up a unit depending on if a certain pain threshold is reached via the state machine.
> add addPain function, cap pain

- addons/dogtags/functions/fnc_addDogtagActions.sqf
Fix #4476
The internal tag IDs were still visiable from action menu
> Don't show dogtag ID in action menu

- addons/refuel/CfgVehicles.hpp
- addons/refuel/functions/fnc_refuel.sqf
- Fix wrong fuel capacity for 3rd party helicopters/planes/ships by removing base class ACE3 fuel capacity config entry and fall-back to vanilla `fuelCapacity`.
- Not fix wrong fuel capacity for other ground vehicles, that is due to those using a different fuel consumption system (apparently at least) and require `fuelCapacity` to be `range * fuel factor`.
- Remove empty classes in refuel.
Previously MELB (modded) was being refueled slowly with 3000 liters (instead of expected 463 or 242) due to default helicopter `ace_refuel_fuelCapacity` config entry for example. That is not friendly to any mod, however sadly we can't do a fall-back to vanilla `fuelCapacity` for ground vehicles because they have a different fuel consumption system (formulated as …
> Fix 3rd party air and sea vehicle fuel capacity

- addons/medical_blood/functions/fnc_spurt.sqf
Fix #4571
```
[ACE] (medical_blood) TRACE: 16374 hit: _unit=bob, _causedBy=B Alpha 1-1:1 (Pabst Mirror), _damage=154523 z\ace\addons\medical_blood\functions\fnc_hit.sqf:18
```
`_damage=154523` 
So it was trying to create 618094 blood objects :smile: 
RPG-32 was doing about 27k damage hit.
> Sanatize damage value used for blood creation

- addons/interaction/functions/fnc_tapShoulder.sqf
Close #4577
Doesn't block movement or makes camera look down like `putDown` does.
> Faster, non movment blocking gesture for tap shoulder

- addons/main/script_mod.hpp
- addons/main/script_version.hpp
- docs/wiki/development/setting-up-the-development-environment.md
- tools/make.py
- Update `make.py` to 0.8 (enhancements, fixes, features from ACRE2's latest `make.py` version)
- Fix missing version number in version files with release build
- Add arguments to increment all 4 parts of version
- Move version definitions to own file for easier increment handling
- Make `optionals` directory optional (sounds funny!)
- Update building documentation overall and add proper `make.py` command line options documentation
- Improve `replace_file` function drastically by using `fileinput` library
- Streamline errors count and handling, display list and count at the end
- Make missing files (from `importantFiles` and `versionFiles` lists) throw errors like PBO errors
- Fix `get_project_version` being called multiple times, causing weird …
> Update make.py to 0.8

- addons/refuel/functions/fnc_makeJerryCan.sqf
- Fix makeJerryCan locality issues
The jerry can object was marked as such globally, but the interaction points were only added locally. The function will work when the object namespace variable wasn't synched yet, but once the first player has synched it the function will simply exit without adding the interaction points.
> Fix makeJerryCan locality issues

- addons/dogtags/CfgVehicles.hpp
- addons/dogtags/functions/fnc_addDogtagActions.sqf
- Title
- Remove redundant `format`
I also think we should display the name in the interaction menu, currently it's only `Dog Tag, Dog Tag, Dog Tag, ...` when checking dog tags you have taken. Doesn't seem to be as easy as it is communicated from the server rather than kept on client that has it. Reverting #4558 might be preferable in that case, simply to distinguish them (maybe that was the original idea anyways?).
> Allow checking dogtags inside vehicles and when sitting

- addons/kestrel4500/functions/fnc_generateOutputData.sqf
- `_windSpeed` is already an [absolute value](https://github.com/acemod/ACE3/blob/7b2d736ba35fb2c6808311ba61065076da4c9401/addons/kestrel4500/functions/fnc_measureWindSpeed.sqf#L21)
- `cos(_playerDir - _windDir)` is already applied in [`FUNC(measureWindSpeed)`](https://github.com/acemod/ACE3/blob/7b2d736ba35fb2c6808311ba61065076da4c9401/addons/kestrel4500/functions/fnc_measureWindSpeed.sqf#L26)
Closes: https://github.com/acemod/ACE3/pull/4552
> Fix Kestrel4500 wind speed calculation

- addons/realisticnames/CfgWeapons.hpp
- addons/realisticnames/stringtable.xml
Green Hex and Hex variants of:
- QBZ-95-1
- QBZ-95-1 GL
- QBZ-95-1 LSW
> Adds realistic names for the QBZ-95 camo variants

- addons/ballistics/CfgAmmo.hpp
- addons/ballistics/CfgWeapons.hpp
* Corrected AKS-U barrel length
* Corrected .338 250gr BC
* Corrected .338 API526 BC and muzzle velocity
* Slightly reduced 5.8x42mm muzzle velocity
> Minor corrections in the ballistics module

- docs/Dockerfile
- fix the dockerfile to use a proper entrypoint
- remove "--incremental" but by using an entrypoint a user could simply add the "--incremental" flag
```
#
```
> improve dockerfile

- addons/ballistics/CfgMagazines.hpp
- addons/ballistics/CfgWeapons.hpp
- addons/ballistics/stringtable.xml
* Add new 20rnd 6.5mm Creedmor and 6.5mm Lapua Scenar magazines
* Fix incorrect QBU-88 (DMR_07_base_F) `initSpeed`
* Fix 30rnd 6.5mm  Creedmor and 30rnd 6.5mm Lapua Scenar magazine `initSpeeds`
Closes: #4636
> Ballistics - Fixed 6.5mm magazine config

- addons/medical_blood/XEH_PREP.hpp
- addons/medical_blood/XEH_postInit.sqf
- addons/medical_blood/functions/fnc_serverCleanupBlood.sqf
Using a single ordered queue for blood drop cleanup 
instead of having every drop (up to 500) on a `waitAndExecute`
Every call to `CBA_fnc_waitAndExecute` does a `sort`, so it's best to keep the array small.
> Use single queue for blood cleanup

- addons/explosives/functions/fnc_spawnFlare.sqf
- this function is called via `directCall` which internally uses the assignment operator on the called functions return value.
https://github.com/acemod/ACE3/blob/98da86b74d4089bc3403d0b0c0074e6a46ce35d8/addons/explosives/scripts/TripflareEffect.sqf#L20
- this function itself ends with an assignment operator too unless the `TRACE()` is resolved in debug mode. The assignment operator is bugged in the SQF engine. It's the only "command" that reports `void` instead of e.g. `GameValueNil` in C++ land. Using the assignment operator on `void` causes the following script error:
```
0:33:15 Error in expression <ate "_CBA_return";
isNil {
_CBA_return = _CBA_arguments call _CBA_code;
};
if >
0:33:15   Error position: <= _CBA_arguments call _CBA_code;
};
if > …
```
> fix tripflares script error

- addons/medical/CfgEden.hpp
This fixes a typo in line 25, `ace_isMeidc_temp` to `ace_isMedic_temp`
> Fix typo in Eden Options

- addons/repair/ACE_Repair.hpp
Sometimes [damage command](https://community.bistudio.com/wiki/damage) returns 0 even if vehicle is almost fully destroyed. It's mentioned in Notes section on that wiki page. I found it can easily reproduced with HMG fire at Hunter.
damage can be replaced with [getAllHitPointsDamage](https://community.bistudio.com/wiki/getAllHitPointsDamage).
damage is also used for vehicles in [fnc_normalizeHitPoints.sqf](../blob/e60df02758e9dd997fb591ba8dfcbe2876c3b6ea/addons/repair/functions/fnc_normalizeHitPoints.sqf#L50) and  [fnc_setHitPointDamage.sqf](../blob/e60df02758e9dd997fb591ba8dfcbe2876c3b6ea/addons/repair/functions/fnc_setHitPointDamage.sqf#L37), but I didn't managed to understand the sense.
> Fix Full Repair menu not shown when damage returns 0

- addons/cookoff/CfgEden.hpp
- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_detonateAmmunition.sqf
- addons/cookoff/functions/fnc_secondaryExplosions.sqf
- Add a toggle to ammo boxes in 3den to disable their cook off individually
- Fix some explosives not working as part of ammo detonation
- Include shots of simulation type `shotsubmunitions` in ammo detonation
> Fix ammo cook off with certain explosives

- addons/tagging/functions/fnc_tagTestingThread.sqf
Close #4659
Cannot use `exitWith` inside select {} code.
```
x3 = [1,2,3,4,5] select { 
if (_x == 3) exitWith { 
false; 
}; 
true 
};
// x3 = false
```
> Fix tagTestingThread error

- addons/chemlights/CfgWeapons.hpp
Changed `ACE_Chemlight_Shield` to `public` from `protected`
> ACE_Chemlight_Shield not public

- addons/refuel/XEH_PREP.hpp
- addons/refuel/XEH_postInit.sqf
- addons/refuel/functions/fnc_handlePlayerWeaponChanged.sqf
- addons/refuel/functions/fnc_maxDistanceDropNozzle.sqf
- Fix #4601 
Refuel should use a `canInteractWith` (like carrying does), but that will need a bigger rework. Because of it not using `canInteractWith` Advanced Throwing is possible while carrying a fuel nozzle or jerry can.
Aditionally vanilla throwing is possible both with refuel and carrying, a `setAmmo` framework for that would be nice, but have no time to work on it at the moment.
> Prevent switching to weapon while carrying fuel nozzle

- addons/cargo/functions/fnc_canLoad.sqf
- addons/cargo/functions/fnc_canLoadItemIn.sqf
- addons/cargo/functions/fnc_findNearestVehicle.sqf
- addons/cargo/functions/fnc_startLoadIn.sqf
- Remaking of #4551 after a mess up in me trying to update my fork and being inexperienced with git 
- add the ability to exclude objects from the findNearestVehicle function. For situations like in the [image](https://camo.githubusercontent.com/e7201defd0e592011aca183596dc25bbed2ef8ce/687474703a2f2f692e696d6775722e636f6d2f42447571774c612e706e67) where a player might make an object like the quad loadable, and the findNearestVehicle is reporting the quad as still the closest even though im clipping into the truck.
- prevent object implosion. If a player decides to make an object capable of being cargo as well loadable.
- Added occupancy check when loading object.
- Update findNearestVehicle calls to pass new parameter.
> Fix cargo find nearest vehicle

- addons/interact_menu/functions/fnc_compileMenu.sqf
Fix #4664
playableLogic seems to be `VirtualMan_F` and it's children
`HeadlessClient_F`
`VirtualCurator_F`
`VirtualSpectator_F`
> Don't compile action menu for playable logics

- addons/fcs/functions/fnc_calculateSolution.sqf
- addons/fcs/functions/fnc_firedEH.sqf
Reincarnation of https://github.com/acemod/ACE3/pull/3561
* Add a correction to ACE_FCS to account for vanilla zeroing
* Allow ACE_FCS to work without requiring a compatibility PBO
**TODO** 
~~Think about hiding the vanilla zeroing control if necessary (**Edit:** I don't think that we should hide it)~~
Closes: https://github.com/acemod/ACE3/pull/3561
> FCS with no compat pbo required

- addons/advanced_fatigue/functions/fnc_getAnimDuty.sqf
- addons/advanced_fatigue/functions/fnc_handleEffects.sqf
- Allow you to crawl a bit further before getting fatigued
- Make swimming with normal clothes way harder than with a wetsuit 
- Steepen the animation slowdown in water to make it more noticable
Also see #4530.
This PR has a small somewhat unintended sideffect when wearing a wetsuit: Swimming on the surface is a bit slower than underwater and thus can consume no stamina. This creates a neat game mechanic where going to the surface is beneficial, but of course comes with the danger of getting discovered. I found that pretty interesting and left it in.
> Advanced Fatigue swimming/diving/crawling tweaks

- addons/fastroping/XEH_postInit.sqf
- addons/fastroping/script_component.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/config.cpp
Close #4683
Config from @Whigital - thanks!
This is for the `RHS_MELB_MH6M` variant, which already has the rope bars in the model.
Also added a little visual debugging for the memory points.
> Add RHS MELB fastrope, add 3d debuging of mem points

- addons/laser/XEH_postInit.sqf
- addons/laser/functions/fnc_addLaserTarget.sqf
- addons/laser/functions/fnc_laserTargetPFH.sqf
This makes it possible to change code while laser is on.
Before it would have no effect until turning off and on again.
> Update laser code if laser is already on

- addons/atragmx/RscTitles.hpp
- addons/atragmx/XEH_PREP.hpp
- addons/atragmx/functions/fnc_add_new_gun.sqf
- addons/atragmx/functions/fnc_read_gun_list_entries_from_config.sqf
- addons/atragmx/functions/fnc_trim_gun_name.sqf
* Reduce the gun list font size
* Change the listbox scrollbar design (new colors, smaller width)
* Add a negative offset for the horizontal text position in the gun list
* Limit the max. allowed length of custom gun names to 14 characters
Fixes: https://github.com/acemod/ACE3/issues/4669
| Before | After |
| --- | --- |
| ![before](http://image.prntscr.com/image/20ede22e18ce4936a37cb3fa442dd83e.png) | ![after](https://cloud.githubusercontent.com/assets/9437207/20358325/aa3dbebc-ac2b-11e6-9a29-4c9b572e1b36.jpg) |
> ATragMX - Improved gun list readability

- addons/scopes/ACE_Settings.hpp
- addons/scopes/CfgVehicles.hpp
- addons/scopes/CfgWeapons.hpp
- addons/scopes/functions/fnc_getCurrentZeroRange.sqf
- addons/scopes/functions/fnc_initModuleSettings.sqf
- addons/scopes/functions/fnc_inventoryCheck.sqf
- addons/scopes/stringtable.xml
* Fix `forceUseOfAdjustmentTurrets` setting affecting all scopes including iron sights
* Fix `ACE_ScopeZeroRange` config being ignored when placed in a weapon class
* Rework the `optic_Nightstalker`, `optic_NVS` and `optic_TWS` config settings
* Add a new `overwriteZeroRange` setting to have more control over the enforced overwriting of the zero range
**Rationale:**
* Different scopes should be able to have different zero ranges
* Some scopes come with red dot or iron sights on top of it which should be able to have different zero ranges
Both of which are not possible when we overwrite the zero range in code.
> Scopes - Fixes various minor issues

- .gibot.yml
- Add missing `is` to allow gibot to make its comments the right way!
> Fix missing word in gibot comment

- .github_changelog_generator
- .gitignore
- Title
- Add generated `CHANGELOG.md` to `.gitignore` as change logs are posted on release pages
Change Log Generation:
- Install https://github.com/skywinder/github-changelog-generator (Ruby gem)
- Generate GitHub token if you don't have it yet (to allow more than 50 API calls)
- Run in ACE3 clone root: `github_changelog_generator -t <token> --between-tags <tag>`
- Example: `github_changelog_generator -t 0000000000 --between-tags v3.8.2-rc1`
- Replace linked PR numbers (GitHub automatically links them)
- Regex: `"\[\\(.+?)\].*\)"` -> `"($1)"`
- Sort into sections and prettify accordingly
> Add GitHub Changelog Generator configuration file

- addons/atragmx/functions/fnc_calculate_truing_drop.sqf
* Fix a bug in the truing drop feature that occurs when the zero range is greater than the truing range
> ATragMX - Truing Drop fix

- addons/advanced_ballistics/ACE_Settings.hpp
- addons/advanced_ballistics/CfgVehicles.hpp
- Change the default simulation interval to 0.05s
> Advanced Ballistics - New default simulation interval

- addons/advanced_fatigue/functions/fnc_handlePlayerChanged.sqf
Removes the setVariable after removing the event handler.
Otherwise the EH would not be re-added when switching back to a previously controled unit.
Start Unit A - Add EH to A
Zeus Unit B - Remove from A, Add EH To B
Return to A - Remove from B, Would skip Adding to A because setVar was present
> AdvFatigue - Remove setVar when removing eh

- addons/realisticweights/CfgWeapons.hpp
Cyrus was set to weigh 300 units (~30lb?). The NATO equivalent, the Noreen
Bad News (or MAR-10) weighed 130, or 13lbs, equivalent to it's real life
counterpart. This just changes the weight to 140, similar to that of the
SVDK, a possible real-life counterpart for this rifle.
Fixes #4732
> Realisticweights: Updated cyrus weight

- addons/ballistics/CfgAmmo.hpp
- Remove all `caliber`, `hit` and `typicalSpeed` config entries form the vanilla ammo classes
(as discussed in https://ace3public.slack.com/messages/medical/)
- Remove all unused ammo classes
Related: #2931
> Ballistics - Cleanup

- optionals/compat_rhs_usf3/CfgAmmo.hpp
Makes rhs jav ammo work the same as vanilla.
> Unify javelin guidance for RHS ammo

- addons/rangecard/CfgVehicles.hpp
- addons/rangecard/XEH_postInit.sqf
- addons/rangecard/functions/fnc_openRangeCard.sqf
- addons/rangecard/functions/fnc_updateClassNames.sqf
- addons/rangecard/functions/fnc_updateRangeCard.sqf
- addons/scopes/XEH_PREP.hpp
- addons/scopes/functions/fnc_getBoreHeight.sqf
- addons/scopes/functions/fnc_getCurrentZeroRange.sqf
- addons/scopes/functions/fnc_inventoryCheck.sqf
- Use the actual bore height for the range card calculation
> RangeCard - Take bore height into account

- addons/advanced_throwing/XEH_postInit.sqf
> AdvThrow - Make sure ammo setVar is not empty

- addons/medical/XEH_preInit.sqf
- addons/medical/functions/fnc_conditionCardiacArrestTimer.sqf
- addons/medical/functions/fnc_enteredStateCardiacArrest.sqf
- Add some minor variation to the length of cardiac arrest, can only vary up to 10% of the setting value with a Gaussian distribution that favours the setting itself
> Introduce small variation to length of cardiac arrest

- addons/refuel/CfgVehicles.hpp
- addons/refuel/XEH_postInit.sqf
- Fix missing refuel menu on static fuel stations.
I think it would fix #4077.
I found that:
- to fix missing refuel menu it's enough to create vehicle of the same class (it can be deleted at once);
- it's much faster to check conditions in if-then condition inside `'true' configClasses` loop than to check conditions in configClasses parameter.
Save/load, respawn, jip compatible.
> Fix missing refuel menu on static fuel stations

- addons/explosives/XEH_postInit.sqf
- addons/explosives/functions/fnc_detonateExplosive.sqf
- addons/explosives/functions/fnc_onIncapacitated.sqf
- addons/explosives/functions/fnc_onInventoryChanged.sqf
- Fix deadman range (close #4688) in onIncapacitated.sqf
- Fix clacker transfer (close #4687) in onInventoryChanged
- Add use of `setShotParents` - should fix killed EH and correctly sets `ace_medical_lastDamageSource`
> Explosive Fixes

- addons/winddeflection/functions/fnc_updateTrajectoryPFH.sqf
`private _var` is about double as fast as `private [array]` and this is a PFH so its kinda important
0.0196ms for the 
```
private ["_accel", "_accelRef", "_bulletSpeed", "_bulletVelocity", "_deleted", "_deltaT", "_drag", "_dragRef", "_isWind", "_trueSpeed", "_trueVelocity"];
_accel                  = 0; 
_accelRef             = 0; 
_bulletSpeed        = 0; 
_bulletVelocity      = 0; 
_deleted               = 0; 
_deltaT                = 0; 
_drag                   = 0; 
_dragRef              = 0; 
_isWind                = 0; 
_trueSpeed          = 0; 
_trueVelocity        = 0; 
```
vs 0.0129ms for
```
private _accel                  = 0; 
private _accelRef             = 0; 
private _bulletSpeed        = 0; 
private _bulletVelocity      = 0; 
private _deleted               = 0; 
private …
```
> Use new private syntax for winddeflection PFH

- optionals/compat_adr_97/meta.cpp
- optionals/compat_rhs_afrf3/meta.cpp
- optionals/compat_rhs_usf3/meta.cpp
- Add meta.cpp files to RHS and ADR optionals
Since those mods are now Steam Workshop it just makes sense, that they get their own meta.cpp
> add optionals meta.cpp files

- addons/common/functions/fnc_addLineToDebugDraw.sqf
- addons/overpressure/ACE_Settings.hpp
- addons/overpressure/XEH_postInit.sqf
- addons/overpressure/config.cpp
- addons/overpressure/functions/fnc_cacheOverPressureValues.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- addons/overpressure/stringtable.xml
- optionals/compat_rhs_afrf3/CfgAmmo.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_afrf3/config.cpp
Close #4691
- Add ace_setting for overpressure distance
- Change overpressure config on 2a70 (used on the bmp-3/bmd-4; it has a very low muzzle velocity)
- fix rhs gl smoke causing frag
- improve debug line drawing
> Overpressure changes

- optionals/nouniformrestrictions/functions/fnc_exportConfig.sqf
I know it's not important for performance, but it's a good example script (e.g. for me) and I want it to be more perfect.
> Simplify config crawling in nouniformrestrictions

- addons/cookoff/functions/fnc_cookOffBox.sqf
- addons/grenades/XEH_postInit.sqf
- A faulty if condition which could cause locality issues
- Add the grenade fired EHs on HCs and dedicated servers
This should fix the following (partly undiscovered) issues:
- #4798
- No pin pulling sounds caused by dedicated/HC units
- AI thrown flashbangs having no effect
> Fix cookoff locality issues

- addons/hearing/XEH_postInit.sqf
- addons/hearing/functions/fnc_explosionNear.sqf
- addons/hearing/functions/fnc_firedNear.sqf
- addons/hearing/functions/fnc_updatePlayerVehAttenuation.sqf
Replaces #4278 (no event overhead with this method)
Fixes #2627 - Increase vehicle protection for MRAPs
Switches to dynamically adding `firedNear` event handlers via code based on Advanced Fatigue.
firedNear can trigger many times for a single shot;
filtering by player isn't that expensive, but will run a lot
only running the EH on the player/vic will be even faster.
> Hearing - player only event handlers

- addons/huntir/CfgWeapons.hpp
- addons/huntir/subConfig/config.cpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/subConfig/config.cpp
Close #4199
Based on work by @robalo https://github.com/toadie2k/NIArms/commit/365a10dcd8a51d3de358e8be2f82aacc3b84c32d
`+=` fails on inheritance in a single config; 
but it can work if done in separate configs
and we can include multiple config.cpp in a single pbo
Allows us to simplify our configs, and should help with compatibility with other mods using similar techniques.
Also will allows us to add multiple gl magazines without creating conflicts.  (ref #4506)
> Simplify huntIR configs using +=

- docs/wiki/framework/explosives-framework.md
I think there is a typo in the documentation, as there is no `scriptedExplosion`, only `scriptedExplosive`
> [typofix]  explosion -> explosive

- addons/concertina_wire/functions/fnc_dismount.sqf
- Decrease concertina "dismount" time
- IRL it’s just pushing them together again
- use ace checks to see if a unit is an engineer or an EOD
> Decrease concertina "dismount" time

- optionals/compat_rh_acc/CfgWeapons.hpp
- Enable map flashlight for RH Acc's Surefire flashlight
> Add RH Acc Surefire flashlight map compatibility

- addons/interaction/functions/fnc_getDoorAnimations.sqf
- Fix a typo in ace_interaction_fnc_getDoorAnimations
> fixing typo in ace_interaction_fnc_getDoorAnimations

- addons/missileguidance/CfgAmmo.hpp
Fix #4856
Ammo seems to need this config or AI just take their launcher out and then put them away.
Missile is still guided by script
> Fix Javelin for AI

- addons/nametags/XEH_PREP.hpp
- addons/nametags/XEH_postInit.sqf
- addons/nametags/functions/fnc_getCachedFlags.sqf
- addons/nametags/functions/fnc_onDraw3d.sqf
This will cache the Nametag Flags and _maxDistance for 2 seconds instead of reparsing them every Frame.
This will take about 0.0621ms of load from eachFrame and cache it.
After caching the load will be about 0.0323ms per frame.
0.03ms improvement call me crazy if you want.
This will also remove the unused privates from fnc_onDraw3d.
This will create lag from changing Nametag settings to them being visible. Sadly cachedCall can only use 1 Event and I used `cba_events_visionModeEvent` to be also able to cache the _maxDistance variable.
Calculating the _maxDistance variable takes 0.0267 ms so it's very worthwhile to be cached.
> Cache Nametags onDraw3D flags.

- addons/interaction/XEH_PREP.hpp
- addons/interaction/functions/fnc_getInteractionDistance.sqf
- addons/rearm/functions/fnc_canRearm.sqf
- addons/refuel/functions/fnc_canCheckFuel.sqf
- addons/refuel/functions/fnc_canConnectNozzle.sqf
- addons/refuel/functions/fnc_canReturnNozzle.sqf
- addons/refuel/functions/fnc_canTakeNozzle.sqf
Fix #4784
`ace_interaction_fnc_getInteractionDistance` should return something closer to the distance to the exterior of the vehicle. 
With the giant VTOL you could be standing right next to the hull and `distance` would be 7.5, which is further than the rearm/refuel actions allowed.
Could also look at integrating this into ace_cargo at some point.
> Add getInteractionDistance and fix VTOL refuel/arm

- addons/interact_menu/functions/fnc_compileMenu.sqf
Fix #4862
Thanks to @rebelvg for finding reproduction steps
ace_interaction_fnc_addPassengerAction always does `(_actionTrees select 0 select 1)`
If another mod loads first, it can could add an base interaction node before mainActions.
At action compile time this will verify and resort if necessary.
> Fix passenger actions - Ensure order of MainActions

- optionals/compat_rhs_usf3/CfgVehicles.hpp
> Fix RHS m113 compat

- addons/advanced_fatigue/XEH_postInit.sqf
- addons/advanced_throwing/XEH_postInit.sqf
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_setName.sqf
Needed for CBA 3.2, but bwc with current.
"visibleMap" event is weird now: at the time the event runs the command `visibleMap` returns the previous value.
The fatigue bar was only showing on the map, but not in-game :smile: 
Similar problem with "unit", the command `name` would return the name of the previous AI.
Player reinforcements all had AI names on their nametags.
> Handle changes to CBA_fnc_addPlayerEventHandler

- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgAmmo.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
**Compat RHS afrf and usf updated with the new 4.2 sniper rifles and scopes**
- add M40A5 and S&B M8541
- add ORSIS T-5000 .338LM and Dedal DH 5-26x56 
- update all sniper scopes with the new Scopes Framework (except PSO scopes)
- update all sniper and marksman rifles with the new Scopes Framework (except SVD and VSS)
- fix the .300 WM TempMuzzleVelocityShifts according with the ACE_762x67_Ball_Mk248_Mod_1 (ballistics/CfgAmmo.hpp)
> AB : compats RHS 4.2 updated 

- addons/concertina_wire/XEH_init.sqf
- addons/hearing/XEH_postInit.sqf
- addons/interact_menu/XEH_clientInit.sqf
- addons/laserpointer/XEH_postInit.sqf
- addons/spectator/functions/fnc_handleInterface.sqf
- docs/wiki/development/coding-guidelines.md
Thanks to a discovery from @dedmen  (ref https://github.com/CBATeam/CBA_A3/pull/588)
Passing a large code function to a BIS EH has a significant performance cost.
Using interact_menu as an example.
```
addMissionEventHandler ["Draw3D", {x3 = diag_tickTime}];
for "_index" from 1 to 2000 do {
// addMissionEventHandler ["Draw3D", FUNC(render)]; // (660 ms / 2000) = .33 ms
addMissionEventHandler ["Draw3D", {call FUNC(render)}]; // (28 ms / 2000) = 0.014 ms
};
addMissionEventHandler ["Draw3D", {diag_log text format ["2000 calls took %1 ms", 1000 * (diag_tickTime - x3)]}];
```
So an extra processing time of ~0.3 ms when passing the entire function vs passing a short bit of code that calls the function.
> Pass functions by "reference" to bis event handlers

- addons/hearing/CfgVehicles.hpp
- addons/hearing/functions/fnc_putInEarplugs.sqf
- addons/hearing/functions/fnc_removeEarplugs.sqf
Fix #4912
Hides the actions if combat deafness setting is disabled.
Also add exits on the functions in case they are manually called by a script/mission
> Hide earplug actions if setting disabled

- addons/slideshow/CfgVehicles.hpp
- addons/slideshow/functions/fnc_createSlideshow.sqf
- addons/slideshow/functions/fnc_moduleInit.sqf
- addons/slideshow/stringtable.xml
- docs/wiki/feature/slideshow.md
- docs/wiki/framework/slideshow-framework.md
- Fix #4901 
- Use `private KEYWORD` instead of `private ARRAY`
- Add `Set Name` setting to allow distinguishing between multiple slideshow sets (#4901)
- Remove `Reference INFO for object support.` as there is no "INFO" in Eden
- Update documentation
> Fix multiple slideshows sub-actions, Add set name setting

- addons/gunbag/functions/fnc_offGunbagCallback.sqf
> Fix lost magazines when restoring gunbag mags

- addons/common/functions/fnc_setVariablePublic.sqf
Fix #4932
setVariablePublic should call itself again with the current value, not the value from the first call
> Fix setVariablePublic reseting to old values

- addons/main/script_mod.hpp
- Title
We only really require v3.2.0, but requiring v3.2.1 will prevent reports like #4949.
> Require CBA v3.2.1

- addons/ballistics/CfgWeapons.hpp
**Update Katibas barrel length**
- change the Katiba barrel length to 20" for the standard and GL version (default 28.7")
- change to 15,5" for the carbin version (default 26.8")
The KH2002 seems to be a bullpup version from a Chinese clone of a M16A1 (NORINCO CQ),
so the barrel length can't be 28.7".
For the carbin version, i didn't find a decent documentation
so i used my favorite, empiric and not perfect system : 
http://images.akamai.steamusercontent.com/ugc/90472493360168854/BC06354458D486A26955BFAE1E17B13A0709A949/
> AB : Katibas barrel length

- addons/zeus/XEH_PREP.hpp
- addons/zeus/functions/fnc_moduleAddOrRemoveFRIES.sqf
- addons/zeus/functions/fnc_moduleAddSpareTrack.sqf
- addons/zeus/functions/fnc_moduleAddSpareWheel.sqf
- addons/zeus/functions/fnc_moduleCaptive.sqf
- addons/zeus/functions/fnc_moduleSearchNearby.sqf
- addons/zeus/functions/fnc_moduleSetMedic.sqf
- addons/zeus/functions/fnc_moduleSetMedicalFacility.sqf
- addons/zeus/functions/fnc_moduleSetMedicalVehicle.sqf
- addons/zeus/functions/fnc_moduleSimulation.sqf
- addons/zeus/functions/fnc_moduleSurrender.sqf
- addons/zeus/functions/fnc_moduleUnconscious.sqf
- addons/zeus/functions/fnc_showMessage.sqf
- addons/zeus/functions/fnc_ui_defendArea.sqf
- addons/zeus/functions/fnc_ui_groupSide.sqf
- addons/zeus/functions/fnc_ui_patrolArea.sqf
- addons/zeus/functions/fnc_ui_searchArea.sqf
- Add a function for zeus messages and change all displayTextStructured calls to it. New function uses `BIS_fnc_showCuratorFeedbackMessage` for zeus messages, which shows a slightly fancier message on the top bar of the zeus ui.
> New Function to Show BIS Style Curator Messages

- addons/common/CfgLocationTypes.hpp
- addons/tagging/XEH_postInit.sqf
Needed due to changes on profiling/dev:
Keep old type in case someone else was using, profiling branch will now print:
`Wrong location draw style - "WARNING-ACE_HashLocation_is_deprecated"`
> Cleanup use of ACE_HashLocation

- addons/rangecard/functions/fnc_updateRangeCard.sqf
Fix #4962
I think this is right
line 229 does `} forEach [0, 3, 8];`
> Fix rangecard not showing wind/lead

- addons/gforces/functions/fnc_addPFEH.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
Fix #4952
gforces averages the last 6 seconds
on zeus RC it would only use the last 0.2 seconds, so it could spike high
> Fix gforce avg on switching to aircraft

- addons/cookoff/functions/fnc_cookOffBox.sqf
> also fix cooking off ammo boxes

- addons/cookoff/functions/fnc_cookOff.sqf
- addons/cookoff/functions/fnc_cookOffBox.sqf
- fix #4900
Randomness would be calculated on every machine, but only vehicle explosion and sound are done by the server. Smoke, light and fire sfx are done by each client.
> Fix cookoff desynch
