acemod/ACE3

addons/medical_engine/data/model.cfg

- Add model.cfg required to binarize unconscious RTM files
- Fixes broken build after #7363

Medical - Add missing model.cfg to unconscious animation rtms

---

AUTHORS.txt
addons/logistics_wirecutter/script_component.hpp

- Add mising Contact DLC fences.
- Add missing Malden DLC vineyard fence
- Include myself in AUTHORS.txt because I forgot to on my first PR.

Logistics Wirecutter  - Add additional Contact and Malden fences

---

AUTHORS.txt
docs/team.md

Add veteran29 to maintainers

---

addons/tagging/functions/fnc_tag.sqf

Fix #7769
This seems to be the original intent based on comment

Tagging - Fix tag orientation on walls

---

tools/publish.py

New SteamWS entry created (currently private)

Tools - Prep publish for new RHS SAF compat

---

addons/tagging/functions/fnc_addTagActions.sqf
addons/tagging/functions/fnc_applyCustomTag.sqf

- This pull request check if a string is localize and return the localization if available.
- If check of ìsLocalize`

Tagging - Add: Support of localized string for tagging interaction

---

addons/common/script_component.hpp

- Allow players to dig trenches on snow on Thirsk Winter map

Common - Fix trenches on snow terrain on Thirsk Winter map

---

addons/goggles/config.cpp

- Adds CBRN facewear support using textures from the overlays specified on the [BI Community Wiki](https://community.bistudio.com/wiki/Arma_3_CBRN#Facewear_Overlays)

Goggles - Add CBRN facewear overlays from Contact

---

addons/viewdistance/CfgEventHandlers.hpp

View Distance - Update view distance on video options changes

---

addons/gforces/CfgWeapons.hpp

- Add the helipilot coverall G-force reduction to the LDF gear (to match the other helipilot coveralls)

G-Forces - Add G-force reduction to Heli Pilot Coveralls [LDF]

---

addons/trenches/CfgVehicles.hpp
addons/trenches/XEH_preInit.sqf
addons/trenches/functions/fnc_continueDiggingTrench.sqf
addons/trenches/functions/fnc_removeTrench.sqf
addons/trenches/initSettings.sqf
addons/trenches/stringtable.xml

- Allow to customize trenches digging/removing durations.

Trenches - Add settings to configure dig/remove trenches durations

---

addons/microdagr/gui_controls.hpp

MicroDAGR - Fix contour interval info showing on compass

---

addons/cargo/CfgEventHandlers.hpp
addons/cargo/XEH_PREP.hpp
addons/cargo/XEH_preInit.sqf
addons/cargo/functions/fnc_handleDeleted.sqf
addons/cargo/functions/fnc_handleDestroyed.sqf

- title, Close #7844 
- Don't think `validateCargoSpace` needs to run on server
- Also delete loaded cargo when vehicle is deleted

Cargo - Fix loaded cargo not being deleted when vehicle is destroyed

---

addons/arsenal/ACE_Arsenal_Sorts.hpp
addons/arsenal/defines.hpp
addons/arsenal/functions/fnc_compileSorts.sqf
addons/arsenal/functions/fnc_fillLeftPanel.sqf
addons/arsenal/functions/fnc_fillSort.sqf
addons/arsenal/functions/fnc_handleStats.sqf
addons/arsenal/functions/fnc_onArsenalOpen.sqf
addons/arsenal/functions/fnc_onSelChangedLeft.sqf
addons/arsenal/functions/fnc_showItem.sqf
addons/arsenal/functions/fnc_sortPanel.sqf
addons/arsenal/ui/RscAttributes.hpp

- Fix the face, voice, and insignia tabs after #7719

Arsenal - Fix face, voice, insignia in arsenal

---

addons/arsenal/functions/fnc_sortPanel.sqf
tools/build.py

- Changing the active sort would break the top item's name when using the search bar

Arsenal - Fix sorting when using search

---

addons/advanced_throwing/stringtable.xml
addons/grenades/stringtable.xml

- Add french translations in `grenades` module,
- Fix french translations in `grenades` module.
- Fix french translations in `advanced throwing` module.

Translations - Update / Fix French Translations (Grenades and Advanced Throwing)

---

addons/map_gestures/functions/fnc_drawMapGestures.sqf

Map Gestures - reduce the size of the procedural texture and don't generate mipmaps

---

optionals/compat_rhs_usf3/CfgVehicles.hpp

- Fix RHS USAF CH-47 ramp actions
Close #7905

Compat RHS USAF - Fix CH-47 ramp actions

---

docs/package-lock.json

remove useless file

---

docs/src/package-lock.json
docs/src/package.json

fix more vulnerabilities in old docs node modules

---

AUTHORS.txt
addons/fastroping/stringtable.xml
addons/zeus/stringtable.xml

- Fix french translation of Fastroping in `fastroping` module
- Fix french translation of Fastroping in `zeus` module

Translations - Fix french translations (Fastroping)

---

addons/arsenal/ui/RscAttributes.hpp

Arsenal - Fix invalid usage of ARR macro

---

addons/hearing/CfgVehicles.hpp

Hearing - Fix invalid usage of ARR macro

---

addons/medical_treatment/CfgVehicles.hpp

- Fix build of medical_treatment

Medical Treatment - Fix invalid usage of ARR macro

---

addons/frag/CfgAmmo.hpp

Frag - Add frag values to R_MRAAWS_HE_F

---

tools/make.py

- Fail CI builds with failing PBOs

Tools - Set non zero exit code if any addons fail to build

---

addons/fastroping/CfgVehicles.hpp

- Change remaining conditions to use nested ARR macros like other statements in fastroping CfgVehicles
- Fix build of fastroping with newer mikero tools

Fastroping - Fix inconsistent usage of ARR macro

---

addons/explosives/stringtable.xml

- Add french translations in `explosives` module,
- Fix french translations in `explosives` module.

Translations - Update / Fix French Translations (Explosives)

---

addons/cookoff/CfgVehicles.hpp

Cookoff - Fix engine fire position of Kamaz trucks

---

addons/cargo/XEH_postInit.sqf
addons/cargo/functions/fnc_loadItem.sqf

- Fix #7295
Kind of a sledgehammer approach, but I don't think there are any downsides - correct me if I'm wrong.

Cargo - Fix loaded objects taking damage

---

addons/vehiclelock/functions/fnc_lockpick.sqf

- As requested at: https://github.com/acemod/ACE3/issues/3594#issuecomment-699551537

Vehicle Lock: add events

---

addons/interaction/ACE_ZeusActions.hpp
addons/interaction/XEH_PREP.hpp
addons/interaction/functions/fnc_doRemoteControl.sqf
addons/reload/CfgEventHandlers.hpp
addons/reload/XEH_PREP.hpp
addons/reload/functions/fnc_onTake.sqf

- Fixes 2 issues that occur when building with hemtt

Reload/Interaction - Fix 2 hemtt ingame errors

---

AUTHORS.txt
addons/slideshow/functions/fnc_addSlideActions.sqf
addons/slideshow/functions/fnc_autoTransition.sqf
addons/slideshow/functions/fnc_createSlideshow.sqf

- add an event upon the changing of a slide in a slideshow.

Slideshow - Add "SlideChanged" event

---

addons/zeus/functions/fnc_canCreateModule.sqf

Zeus -  Don't allow creating a new zeus module if we already are one

---

addons/arsenal/XEH_postInit.sqf
addons/arsenal/functions/fnc_onArsenalClose.sqf
addons/arsenal/functions/fnc_openBox.sqf

- Provide a reference to the current box
Useful for mods that modify the arsenal

Arsenal - Provide reference to the current box

---

addons/gunbag/CfgEventHandlers.hpp
addons/gunbag/XEH_PREP.hpp
addons/gunbag/functions/fnc_BIArsenalClose.sqf
addons/gunbag/functions/fnc_BIArsenalOpen.sqf
addons/gunbag/script_component.hpp

- Prevent the weapon from being cleared from the gunbag after opening the BI arsenal.

Gunbag - Add BI Arsenal Compatibility

---

docs/wiki/development/arma-3-issues.md
docs/wiki/framework/slideshow-framework.md

- Title - Fix in Arma 3 v2.00 (currently on dev-branch)
> 06-05-2020
> Fixed: Texture not found when using setObjectTextureGlobal from a Dedicated Server - FT-T80668
https://feedback.bistudio.com/T80668

Documentation - Remove slideshow note

---

addons/ballistics/CfgMagazineWells.hpp

Remove MAR-10 magazines from AWM magwell

---

addons/medical_ai/XEH_postInit.sqf
addons/medical_ai/XEH_preInit.sqf
addons/medical_ai/functions/fnc_isSafe.sqf

Medical AI - Fix AI healing itself too fast when hit

---

addons/arsenal/ACE_Arsenal_Sorts.hpp
addons/arsenal/XEH_PREP.hpp
addons/arsenal/functions/fnc_sortStatement_protection.sqf
addons/arsenal/stringtable.xml

Idea From @Elgin675 - https://github.com/acemod/ACE3/issues/3594#issuecomment-698439972

Arsenal - Sort by protection (helm, uniform, vest)

---

addons/medical_treatment/stringtable.xml

- title, for consistency with other items

Medical Treatment - Title case autoinjector item names

---

AUTHORS.txt
docs/team.md

Add Dahlgren to maintainers

---

addons/medical_treatment/stringtable.xml

- Fix french translation in medical_treatment module,
- Add french translation in medical_treatment module.
EDIT : sorry for the multiples commits :( !

Translations - Update / Fix French Translations (Medical Treatment)

---

addons/arsenal/stringtable.xml
addons/markers/stringtable.xml
addons/medical_gui/stringtable.xml

- Add french translations in `arsenal` module,
- Add french translations in `markers` module,
- Add french translations in `medical_gui` module.

Translations - Update French Translations (Arsenal, Markers and Medical GUI)

---

addons/medical_treatment/stringtable.xml

- Add french translation in `medical_treatment` module.
Sorry, I forgot to translate this string in my last PR :( !

Translations - Update French Translations (Medical Treatment)

---

addons/medical_status/functions/fnc_setUnconsciousState.sqf

- Fix unconscious AI aiming at enemies
- Fix #6460 in case this is still an issue (could not replicate)
This was still a problem with vehicle gunners.

Medical Status - Fix unconscious AI aiming at enemies

---

addons/medical_ai/functions/fnc_canRequestMedic.sqf

Medical AI - Fix unconscious medics not being healed by other AI medics

---

addons/explosives/functions/fnc_addClacker.sqf
docs/wiki/framework/events-framework.md

I want to keep track of available clackers.

Explosives - Add `clackerAdded` event

---

addons/medical_statemachine/functions/fnc_resetStateDefault.sqf

Medical Statemachine - Fix players occasionally being invincible after respawning

---

.github/ISSUE_TEMPLATE/bug_report.md

Add issue template alteration warnings

---

addons/arsenal/ACE_Arsenal_Sorts.hpp

Arsenal - Fix sort by load

---

addons/medical_treatment/functions/fnc_tourniquetRemove.sqf

- title.
There is no error before this PR as well (`true` goes to `default` in `switch`). Not tested.

Medical Treatment - Fix fnc_addToInventory call

---

addons/arsenal/functions/fnc_fillLeftPanel.sqf

See: https://github.com/acemod/ACE3/pull/8017

Arsenal - Remove useless isClass check in configClasses

---

addons/map_gestures/functions/fnc_getProximityPlayers.sqf

Fix error `Error append: Type Group, expected Array`.

Map Gestures - Fix briefing mode group

---

.github/workflows/extensions.yml

- Use `**` wildcard to match any sub-folder - introduced in https://github.blog/changelog/2019-09-30-github-actions-event-filtering-updates/

CI - Simplify extension paths condition

---

addons/ballistics/CfgMagazineWells.hpp

- Enable SCARs with EGLM attachment to use ACE 556 STANAG magazines

Ballistics - Add 30rnd 556 magazines to SCAR EGLM magwell

---

tools/build.py

makepbo can't build pbos with non-binerized p3ds.......

Build dev (filepatching) with hemtt if installed

---

docs/_config.yml

fix docs version of ace3, close #8068

---

addons/tripod/functions/fnc_adjust.sqf

Thanks to @mjc4wilton for report in slack

Tripod - Fix blocking mouse wheel input handler

---

addons/arsenal/functions/fnc_fillRightPanel.sqf

Arsenal - Fix custom categories not working for some Misc item types

---

addons/goggles/CfgVehicles.hpp

Goggles - Allow wiping in more states

---

addons/flashsuppressors/CfgWeapons.hpp
addons/main/script_mod.hpp

lmg now uses standard muzzle configs

Flashsuppresssors - Update configs for 2.02

---

addons/medical_statemachine/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/microdagr/stringtable.xml
addons/mk6mortar/stringtable.xml
addons/nightvision/stringtable.xml
addons/nlaw/stringtable.xml
addons/noradio/stringtable.xml
addons/quickmount/stringtable.xml
addons/realisticnames/stringtable.xml
addons/rearm/stringtable.xml
addons/refuel/stringtable.xml
addons/reload/stringtable.xml
addons/respawn/stringtable.xml
addons/zeus/stringtable.xml

Spanish Translations - Chery pick 6868fa5600841a3e929531367e6c500306a39c65

---

addons/medical_feedback/XEH_postInit.sqf

Medical - Enable forgotten unconscious fade in/out effects

---

addons/hellfire/CfgMagazines.hpp
addons/hellfire/stringtable.xml

- Add descriptions for hellfire variants that show in Eden Attributes Pylons and Zeus Enhanced Pylons menus

Hellfire - Improve descriptions for hellfire variants

---

addons/artillerytables/config.cpp
addons/dragon/config.cpp
addons/fastroping/config.cpp
addons/medical_treatment/config.cpp
addons/tacticalladder/config.cpp

Various - Add missing units/weapons to cfgPatches

---

docs/wiki/development/setting-up-the-development-environment.md

- Instruct user to do #8093 manually, as `-B` on command line does not seem to work properly.

Documentation - Add Mikero binarization note

---

.gitattributes

- title
- improves how GitHub counts language usage in the repository
- https://github.com/github/linguist/blob/master/docs/overrides.md
`docker run -v %cd%:/pwd -w /pwd inloopx/linguist linguist`
Before:
```
55.76%  C++
37.61%  SQF
2.51%   C
1.84%   PAWN
1.76%   Python
0.28%   SourcePawn
0.22%   CMake
0.00%   Batchfile
```
After
```
65.69%  SQF
29.67%  C++
2.59%   C
1.82%   Python
0.23%   CMake
0.00%   Batchfile
```

Update linguist settings

---

addons/mk6mortar/README.md

- Make @BaerMitUmlaut happy, maybe, who knows really

Mk6 Mortar - Fix README.md typo

---

docs/wiki/framework/crew-served-weapons-framework.md

Improve CSW documentation

---

addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf
addons/medical_damage/initSettings.sqf
addons/medical_damage/stringtable.xml

Co-authored-by: @TyroneMF
Alternative to #8170
- Adds a percentage slider for surviving a fatal injury.

Medical - Add Alternative Survival Chance

---

AUTHORS.txt
optionals/particles/script_component.hpp

Particles - Fix macro

---

addons/medical_engine/functions/fnc_setUnconsciousAnim.sqf

- Check vehicle type for Taru pods and don't eject unit from them
- Close #8167

Medical - Allow unconscious unit in Taru pods

---

docs/wiki/development/setting-up-the-development-environment.md

- Remove DeTex as requirement, is subscriber-only now

Documentation - Remove DeTex requirement

---

optionals/compat_rhs_usf3/CfgWeapons.hpp

update the NXS scopes according with the [Nightforce Catalog 2011 (MIL values)](http://www.nightforceusa.com/PDF/nightforce-2011-catalog.pdf#page=12).

RHS USAF Compat - Nightforce NXS scopes updated

---

addons/microdagr/XEH_clientInit.sqf
addons/microdagr/functions/fnc_saveCurrentAndSetNewMode.sqf
addons/microdagr/stringtable.xml

- Add 2 keybinds to cylce through the MicroDAGR modes/pages.
- Changed ERROR to LOG in fnc_saveCurrentAndSetNewMode to stop it from spamming the RPT, internal function anyway.

MicroDAGR - Add mode switching keybinds

---

AUTHORS.txt
addons/nightvision/CfgWeapons.hpp
addons/nightvision/config.cpp
addons/nightvision/stringtable.xml

- Add 3 default color variants (black, brown & green) to all gens/versions of NVGs.

Night Vision - Add color variants to all generations

---

addons/parachute/functions/fnc_cutParachute.sqf

ref #8226 
although it applies to both random failure and intentional cutting

Parachute - Add sound effect when cutting

---

addons/hellfire/stringtable.xml
addons/interact_menu/stringtable.xml
addons/interaction/stringtable.xml
addons/markers/stringtable.xml
addons/maverick/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/microdagr/stringtable.xml
addons/nightvision/stringtable.xml
addons/parachute/stringtable.xml
addons/ui/stringtable.xml
addons/vehiclelock/stringtable.xml

- Add french translation in `hellfire` module,
- Add french translation in `interact_menu` module,
- Add french translation in `interaction` module,
- Add french translation in `markers` module,
- Fix french typo in `markers` module,
- Add french translation in `maverick` module,
- Add french translation in `medical_damage` module,
- Add french translation in `medical_treatment` module,
- Add french translation in `microdagr` module,
- Add french translation in `nightvision` module,
- Add french translation in `parachute` module,
- Add french translation in `ui` module,
- Add french translation in `vehiclelock` module.

Translations - French

---

AUTHORS.txt
addons/arsenal/config.cpp
addons/arsenal/functions/fnc_addSort.sqf
addons/arsenal/functions/fnc_compileSorts.sqf
addons/arsenal/functions/fnc_fillSort.sqf
addons/arsenal/functions/fnc_sortPanel.sqf
addons/arsenal/functions/fnc_sortStatement_accuracy.sqf
addons/arsenal/functions/fnc_sortStatement_amount.sqf
addons/arsenal/functions/fnc_sortStatement_magCount.sqf
addons/arsenal/functions/fnc_sortStatement_mass.sqf
addons/arsenal/functions/fnc_sortStatement_mod.sqf
addons/arsenal/functions/fnc_sortStatement_rateOfFire.sqf
addons/arsenal/functions/fnc_sortStatement_scopeMag.sqf
addons/medical_gui/functions/fnc_modifyActionTriageLevel.sqf
addons/medical_treatment/functions/fnc_canPlaceInBodyBag.sqf

- Fix my name in existing files
- Add myself to contributors

fix my name, add it to contributers

---

addons/medical_treatment/ACE_Medical_Treatment.hpp

Medical: fix minor cut re-opening

---

addons/arsenal/functions/fnc_buttonLoadoutsDelete.sqf
docs/wiki/framework/arsenal-framework.md

- Close #7858 
Forced pushed because my editor broke the markdown formatting

Arsenal - Add on loadout delete event

---

addons/interaction/CfgVehicles.hpp

Interaction - Disable open box action when inventory is locked

---

addons/vehiclelock/CfgMagazines.hpp
addons/vehiclelock/CfgWeapons.hpp

Vehicle Lock - Increase vehicle key mass to 0.1

---

.gitignore
tools/.vscode/tasks.json

VSCode - Add test/build tasks

---

optionals/compat_rh_de/CfgAmmo.hpp
optionals/compat_rh_m4/CfgAmmo.hpp
optionals/compat_rh_m4/CfgWeapons.hpp
optionals/compat_rh_pdw/CfgWeapons.hpp
optionals/compat_rhs_usf3/CfgGlasses.hpp
optionals/tracers/CfgMagazines.hpp
tools/check_strings.py
tools/config_style_checker.py
tools/sqf_validator.py

- Fix current validation issues in optionals
- Validate optionals in future builds

Add optionals to validation tools

---

addons/huntir/stringtable.xml

- `HuntIR monitor` > `HuntIR Monitor`

Translations: Capitalize huntir monitor

---

addons/explosives/stringtable.xml

- Fix french translation in `explosives` module.

Translations - Fix French Translations (Explosives)

---

addons/rangecard/CfgVehicles.hpp

Makes the interaction-menu match the keybind (ref https://github.com/acemod/ACE3/pull/1576)

Rangecard - Allow use inside vehicles via interaction menu

---

optionals/compat_sog/CfgEventHandlers.hpp

- Make macros work with pboproject
- Add placeholder files for VN assets

pboProject fixes for S.O.G. Prairie Fire Compatibility

---

addons/common/initSettings.sqf
addons/common/stringtable.xml

- Fix ACE Common category duplication in Russian

Common  - Fix ACE category duplication in Russian

---

addons/common/functions/fnc_addToInventory.sqf

- Fix the weapon replacing bug/issue in addToInventory.
fixes #8328

Common - Fix `addToInventory` replacing existing weapon

---

addons/common/functions/fnc_unloadPersonLocal.sqf

- Fixes issues with not being able to unload players from vehicles that are remote to the unloaded player

Common - Fix unloading person on non-local vehicles

---

addons/markers/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_treatment/stringtable.xml

- Add french translations in `markers` module,
- Add french translations in `medical_treatment` module,
- Fix french translations in `medical_treatment` module,
- Fix typo in `medical_damage` module.

Translations - Update / Fix French Translations (Markers, Medical Damage and Medical Treatment)

---

addons/dragging/functions/fnc_carryObject.sqf
addons/dragging/functions/fnc_dragObject.sqf
addons/dragging/functions/fnc_dropObject.sqf
addons/dragging/functions/fnc_dropObject_carry.sqf
addons/dragging/functions/fnc_startCarry.sqf
addons/dragging/functions/fnc_startDrag.sqf

- Remove 4th never used parameter on doAnimation call
_label: "ignore changelog"  needed_

Dragging - Remove never used parameter on `doAnimation` call

---

addons/medical_treatment/stringtable.xml

- Add Russian translation in `medical_treatment` module,

Translation - Russian

---

addons/overheating/CfgWeapons.hpp
addons/overheating/XEH_postInit.sqf

- Add a misc item version of the spare barrel.
This version gets replaced with the magazine version once added to inventory. Done for simplicity for finding item in arsenal.

Overheating - Add Spare Barrel Misc Item

---

addons/artillerytables/functions/fnc_rangeTableOpen.sqf

Artillery tables - Remove duplicates from mags array

---

optionals/compat_rhs_afrf3/CfgVehicles.hpp

RHS Compat - Add TZ-8-255B1 to list of fuel trucks

---

addons/overheating/CfgWeapons.hpp

- Title.
Version modeled in game still has barrel detachment lever in place.

Overheating - Allow LIM-85 to switch barrel

---

addons/reloadlaunchers/CfgWeapons.hpp

Reload Launchers - Add Tanks DLC Weapons Support

---

addons/ballistics/stringtable.xml

- Title.
Addresses some confusion with the magazine names. Also no one calls the round by that name.

Ballistics - Change 7.62x67 to .300 WM in stringtables

---

addons/reloadlaunchers/CfgWeapons.hpp

Fix undefined base class in #8408

---

addons/realisticnames/CfgWeapons.hpp
addons/realisticnames/stringtable.xml

Realistic Names - Add strings for Khaki MX variants

---

addons/common/functions/fnc_getAwakeAnim.sqf

Common - Fix `getAwakeAnim` for some vehicles

---

addons/medical/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_engine/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_statemachine/stringtable.xml
addons/medical_treatment/stringtable.xml

Medical - Polish translations updates

---

addons/grenades/stringtable.xml

Grenades - Polish translations updates

---

addons/arsenal/stringtable.xml
addons/dragging/stringtable.xml
addons/maverick/stringtable.xml
addons/realisticnames/stringtable.xml
addons/ui/stringtable.xml
addons/vehiclelock/stringtable.xml

Various polish translation updates

---

addons/cookoff/functions/fnc_cookOff.sqf

- title
Fixes setting to enable cook-off not working as expected (#8611)

Cookoff - Fix enable setting

---

docs/wiki/feature/fcs.md
docs/wiki/user/how-to-make-a-feature-request.md

- Fix spelling "ACE3" as "ACE 3" within our docs

Documentation - Fix ACE3 spelling

---

addons/towing/XEH_postInit.sqf
addons/towing/functions/fnc_startTow.sqf
addons/towing/functions/fnc_towStateMachinePFH.sqf
addons/towing/script_component.hpp

Towing - Add conditions to cancel towing in exceptional scenarios

---

AUTHORS.txt
addons/fortify/XEH_PREP.hpp
addons/fortify/XEH_postInit.sqf
addons/fortify/functions/fnc_createObjectMarker.sqf
addons/fortify/functions/fnc_deployConfirm.sqf
addons/fortify/initSettings.sqf
addons/fortify/stringtable.xml

- Merge https://github.com/acemod/ACEX/pull/258 left from ACEX (unreviewed) by @Seb105

Fortify - Add map area markers for Fortify objects

---

addons/repair/CfgVehicles.hpp
addons/repair/XEH_PREP.hpp
addons/repair/XEH_preInit.sqf
addons/repair/XEH_preStart.sqf
addons/repair/functions/fnc_canRepair.sqf
addons/repair/functions/fnc_getPostRepairDamage.sqf
addons/repair/functions/fnc_getRepairItems.sqf
addons/repair/functions/fnc_hasItems.sqf
addons/repair/functions/fnc_repair.sqf
addons/repair/initSettings.sqf
addons/repair/script_component.hpp
optionals/compat_gm/CfgVehicles.hpp

- title
I'm not sure if it's the best way to do it but that was quick and it works.
Closes #8574

Repair - Support all modded toolkits 

---

.github/workflows/pboproject.yml
tools/make.py

- Update make.py to work both with previous and latest public tools
- Update GitHub Actions CI to use public Mikero Tools as of 2021-11-06

Tools - Update Mikero to public version 2021-11-06

---

addons/rearm/XEH_preStart.sqf
docs/wiki/development/setting-up-the-development-environment.md
tools/make.py

Tools - Binarize configs in make.py

---

addons/fortify/initSettings.sqf

Fortify - Make Progress Bar settings Global

---

addons/arsenal/functions/fnc_addRightPanelButton.sqf
docs/wiki/feature/arsenal.md
docs/wiki/framework/arsenal-framework.md

Documentation - Add Arsenal custom sub-item categories

---

addons/fire/stringtable.xml

Add Spanish translation

---

.github/PULL_REQUEST_TEMPLATE.md

- improve the PR Template
- add focus on documentation and make it a per se requirement for PRs
- add fancy checkboxes to click

GitHub - Improve PR template

---

optionals/compat_sog/CfgWeapons/helmets.hpp

- Add missing hearing and dust protection for SOG:PF helmet SVH4
Close https://github.com/acemod/ACE3/issues/8695

Compats - Add SOG helmet hearing and dust protection

---

addons/medical_damage/stringtable.xml

- Title.
OCD is a hell of a drug.

Medical - Capitalize 'Crushed Tissue' strings

---

addons/fire/stringtable.xml

Fire - Add ellipsis & decapitalize 'patting down fire' string

---

addons/common/stringtable.xml
addons/fire/stringtable.xml
addons/fortify/stringtable.xml
addons/overheating/stringtable.xml
addons/slideshow/stringtable.xml
addons/viewdistance/stringtable.xml

- Add german translations in `common` module
- Add german translations in `fortify` module
- Add german translations in `fire` module
- Add german translations in `slideshow` module
- Add german translations in `viewdistance` module
This my very first pull request, please provide any feedback if I can make improvements on something in this process.
Thanks

Translations - Add german translations

---

addons/overheating/functions/fnc_setAmmoTemperature.sqf
addons/overheating/functions/fnc_setWeaponTemperature.sqf

Overheating - Fix set temperature functions

---

addons/mk6mortar/stringtable.xml

Mk6 Mortar - Add [CSW] prefix to magazines

---

addons/medical_treatment/stringtable.xml

- Title.
For consistency's sake with the other progress strings.

Medical Treatment - Add ellipsis to 'Stitching' string

---

addons/medical_gui/stringtable.xml

Medical GUI - Improve descriptions for blood loss and damage color settings

---

addons/medical_ai/functions/fnc_healingLogic.sqf

- Title.
- Close #8724.
*This is fine*.

Medical AI - Fix AI not performing CPR

---

addons/cookoff/functions/fnc_smoke.sqf

Cookoff - Fix invalid function name in example

---

optionals/compat_rhs_afrf3/CfgWeapons.hpp

- Title.
12.4" as per Kalashnikov Concern.

RHS Compat - Improve AK104/5 barrel length

---

docs/wiki/framework/medical-framework.md

- Fix documentation mistakes from #8278

Documentation - Fix Medical Framework page parsing

---

docs/src/package-lock.json
docs/src/package.json

ran `npm install node-sass@latest`

Docs - Update package-lock.json

---

optionals/compat_rhs_gref3/CfgEventHandlers.hpp
optionals/compat_rhs_gref3/CfgVehicles.hpp
optionals/compat_rhs_gref3/XEH_PREP.hpp
optionals/compat_rhs_gref3/XEH_preInit.sqf
optionals/compat_rhs_gref3/XEH_preStart.sqf
optionals/compat_rhs_gref3/config.cpp
optionals/compat_rhs_gref3/functions/fnc_canCloseDoor.sqf
optionals/compat_rhs_gref3/functions/fnc_onCut.sqf
optionals/compat_rhs_gref3/functions/fnc_onPrepare.sqf
optionals/compat_rhs_gref3/functions/script_component.hpp

- Add F.R.I.E.S options to UH-1H helicopters from RHS:GREF

Compats - Add RHSGREF UH-1H F.R.I.E.S capability

---

optionals/compat_gm/CfgMagazines.hpp

GM Compat - Fix explosives not being placeable

---

addons/fire/functions/fnc_burn.sqf

Fire - Fix fire damage not causing burn wounds

---

addons/advanced_fatigue/XEH_postInit.sqf
addons/advanced_fatigue/XEH_preInit.sqf
addons/advanced_fatigue/functions/fnc_addDutyFactor.sqf
addons/advanced_fatigue/functions/fnc_getMetabolicCosts.sqf
addons/advanced_fatigue/functions/fnc_handleStaminaBar.sqf
addons/advanced_fatigue/functions/fnc_mainLoop.sqf
addons/advanced_fatigue/functions/fnc_removeDutyFactor.sqf

- Adds non-breaking adv fatigue changes from #8763.
- Add band-aid fix to non-fading stamina bar.
- Check ACE_Weather_Enabled variable for weather duty factor instead of checking if mod is loaded.
- Use hashMap for dutyFactor functions.
- Switch to LINKFUNC macro in player eventhandler.

Advanced Fatigue - Improve misc. code

---

addons/grenades/functions/fnc_incendiary.sqf

Grenades - Add fire source to incendiary grenades

---

addons/csw/stringtable.xml
addons/field_rations/stringtable.xml
addons/finger/stringtable.xml
addons/noradio/stringtable.xml
addons/overpressure/stringtable.xml

- Added Missing Translation in CSW
- Added Missing Translation in field_radio
- Added Missing Translation in finger
- Added Missing Translation in noradio
- Added Missing Translation in overpressure

Add Missing German Translation

---

addons/csw/functions/fnc_ai_reload.sqf

Fix `Error Type String, expected Array` during AI reloading of CSW.

CSW - Fix AI reloading

---

addons/csw/XEH_PREP.hpp
addons/csw/functions/fnc_aceRearmGetCarryMagazines.sqf
addons/csw/functions/fnc_assemble_pickupWeapon.sqf
addons/csw/functions/fnc_getCarryMagazine.sqf
addons/csw/functions/fnc_reload_actionsUnload.sqf
addons/csw/functions/fnc_staticWeaponInit_unloadExtraMags.sqf

- move duplicate code for getting of carry magazine to separate function.

CSW - Move carry mag getting code to function

---

addons/maptools/CfgVehicles.hpp
addons/maptools/functions/fnc_canUseMapTools.sqf

MapTools - Allow mod maps and compasses to use map tools

---

addons/interaction/functions/fnc_openDoor.sqf

Interaction - Fix handle animation name for carrier doors

---

addons/cookoff/functions/fnc_cookOffEffect.sqf

fire add/remove event are server only

Cookoff - Fix locality of `fire_removeFireSource` event

---

optionals/compat_sog/XEH_postInit.sqf

- Fix punji traps handler not working due to broken postInit (fix for #8755)

Explosives - SOG Compat - Fix punji traps handler not working

---

addons/vehicles/XEH_postInit.sqf
addons/vehicles/functions/fnc_speedLimiter.sqf

- title;
- optimize and fix some code.
Also looks like `autoThrottle` is not working for UAV planes, don't know if it's intentional @TheCandianVendingMachine.

Vehicles - Add cruise control/speed limiter to boats

---

addons/cargo/functions/fnc_renameObject.sqf

Cargo - Limit rename text length

---

tools/check_strings.py

ref
```
#define TAG(name,col) class TRIPLES(ACE,name,col) { \
displayName = CSTRING(name); \
```
`String str_ace_tagging_name not defined`

Tools - Fix string check false positive on tagging macro

---

addons/casings/stringtable.xml
addons/common/stringtable.xml
addons/csw/stringtable.xml
addons/field_rations/stringtable.xml
addons/finger/stringtable.xml
addons/fire/stringtable.xml
addons/fortify/stringtable.xml
addons/laser/stringtable.xml
addons/magazinerepack/stringtable.xml
addons/marker_flags/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/noradio/stringtable.xml
addons/overheating/stringtable.xml
addons/overpressure/stringtable.xml
addons/realisticnames/stringtable.xml
addons/slideshow/stringtable.xml
addons/tacticalladder/stringtable.xml
addons/tagging/stringtable.xml
addons/trenches/stringtable.xml
addons/ui/stringtable.xml
addons/vehicles/stringtable.xml
addons/viewdistance/stringtable.xml
addons/viewports/stringtable.xml
addons/zeus/stringtable.xml
optionals/compat_rhs_afrf3/stringtable.xml
optionals/compat_rhs_usf3/stringtable.xml

- _Fill missing Japanese translation_
- _Weird translation fixes made long ago_

Translations - Add and Improve Missing Japanese

---

addons/casings/stringtable.xml
addons/common/stringtable.xml
addons/csw/stringtable.xml
addons/field_rations/stringtable.xml
addons/finger/stringtable.xml
addons/fire/stringtable.xml
addons/laser/stringtable.xml
addons/marker_flags/stringtable.xml
addons/medical_gui/stringtable.xml
addons/noradio/stringtable.xml
addons/overheating/stringtable.xml
addons/overpressure/stringtable.xml
addons/slideshow/stringtable.xml
addons/tagging/stringtable.xml
addons/ui/stringtable.xml
addons/vehicles/stringtable.xml
addons/viewdistance/stringtable.xml
addons/viewports/stringtable.xml
addons/zeus/stringtable.xml

- Add missing Polish Translations

Translations - Add Missing Polish

---

AUTHORS.txt
addons/casings/stringtable.xml
addons/common/stringtable.xml
addons/cookoff/stringtable.xml
addons/csw/stringtable.xml
addons/field_rations/stringtable.xml
addons/finger/stringtable.xml
addons/laser/stringtable.xml
addons/magazinerepack/stringtable.xml
addons/marker_flags/stringtable.xml
addons/medical_gui/stringtable.xml
addons/repair/stringtable.xml
addons/trenches/stringtable.xml
addons/ui/stringtable.xml
addons/vehicles/stringtable.xml
addons/viewports/stringtable.xml
optionals/compat_rhs_afrf3/stringtable.xml
optionals/compat_rhs_usf3/stringtable.xml

- _As the title says._ Complete zh-hans again.

Translation - Add Simplified Chinese translation

---

optionals/compat_rhs_saf3/CfgMagazines.hpp

- Disable vanilla use action on placable explosives
Fix https://github.com/acemod/ACE3/issues/8980

RHSSAF Compat - Fix vanilla use action for explosives

---

addons/fortify/XEH_postInit.sqf
addons/fortify/functions/fnc_deployConfirm.sqf

- Fix funds being lost if you cancel a fortification deployment
Fix https://github.com/acemod/ACE3/issues/8948

Fortify - Fix funds being lost when cancelling deploy

---

.github/workflows/pboproject.yml

- Fix build issues when pull request requires and contains updated pDummies
- Example https://github.com/acemod/ACE3/pull/8974

CI - Use pull request branch pDummies during build

---

addons/trenches/functions/fnc_continueDiggingTrench.sqf
addons/trenches/functions/fnc_placeConfirm.sqf
docs/wiki/framework/events-framework.md

Trenches - Add "placed" and "finished" events

---

addons/missileguidance/functions/fnc_cycleAttackProfileKeyDown.sqf

https://community.bistudio.com/wiki/weaponsInfo

Missile Guidance - Use `weaponsInfo` to optimize fire-mode selection

---

addons/novehicleclanlogo/$PBOPREFIX$
addons/novehicleclanlogo/CfgEventHandlers.hpp
addons/novehicleclanlogo/README.md
addons/novehicleclanlogo/XEH_PREP.hpp
addons/novehicleclanlogo/XEH_postInit.sqf
addons/novehicleclanlogo/XEH_preInit.sqf
addons/novehicleclanlogo/XEH_preStart.sqf
addons/novehicleclanlogo/config.cpp
addons/novehicleclanlogo/functions/fnc_removeClanLogo.sqf
addons/novehicleclanlogo/functions/script_component.hpp
addons/novehicleclanlogo/initSettings.sqf
addons/novehicleclanlogo/script_component.hpp
addons/novehicleclanlogo/stringtable.xml
docs/wiki/feature/novehicleclanlogo.md

- title
- Disables clan logo on vehicles in MP
- Disabled by default

Add No vehicle clan logo component

---

addons/cargo/functions/fnc_unloadCarryItem.sqf
docs/wiki/framework/cargo-framework.md

Cargo - Add a way to block auto carry after unload on classes

---

docs/wiki/framework/fortify-framework.md

- Adds the update budget function to the Fortify wiki.
Requested by @veteran29

Documentation - Add budget updates to Fortify.

---

addons/tagging/functions/fnc_createTag.sqf

Tagging - Fix: `ace_tagCreated` EH not fire when tagging vehicle

---

addons/explosives/XEH_PREP.hpp
addons/explosives/functions/fnc_checkDetonateHandlers.sqf
addons/explosives/functions/fnc_detonateExplosive.sqf
addons/explosives/functions/fnc_dialPhone.sqf
addons/explosives/functions/fnc_dialingPhone.sqf

- Add a check if there is RF blocking present before playing ringtone
Fix https://github.com/acemod/ACE3/issues/8859

Explosives - Fix cellphone ringing if RF blocking present

---

addons/arsenal/functions/fnc_buttonLoadoutsSave.sqf

Arsenal - Fixed fetching loadout from extended loadout

---

addons/viewports/stringtable.xml

Viewports - Polish translation update

---

addons/towing/stringtable.xml

Towing - Polish translation update

---

addons/marker_flags/stringtable.xml

Marker flags - Polish translation update

---

addons/trenches/stringtable.xml

Trenches - Polish translation update

---

addons/fortify/stringtable.xml

- Add missing Polish fortify translations

Fortify - Polish translation update

---

addons/interact_menu/functions/fnc_compileMenu.sqf

- title, LOS check could only be disabled for actions added through script

Interact Menu - Add doNotCheckLOS option for config actions

---

addons/explosives/Data/ace_m57.rvmat

- Title, required for future HEMTT versions

Explosives - Fix invalid m57 specularPower

---

addons/grenades/stringtable.xml

Didn't update Chinese cause idk, but all the others should be fine based on the other colors
- Title

Grenades - Change names of IR flares for consistency

---

optionals/compat_sog/CfgVehicles/boats.hpp
optionals/compat_sog/CfgVehicles/planes.hpp
optionals/compat_sog/CfgVehicles/tracked.hpp

fix warnings
```
Validating Config Style
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\boats.hpp Line number: 3
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\boats.hpp Line number: 8   
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\boats.hpp Line number: 13  
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\boats.hpp Line number: 18  
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\planes.hpp Line number: 8  
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\planes.hpp Line number: 13 
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\tracked.hpp Line number: 14
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\tracked.hpp Line number: 19
WARNING: bad class colon ../addons/compat_sog\CfgVehicles\tracked.hpp …
```

Sog Compat - Cleanup class inheritance formatting

---

addons/csw/functions/fnc_reload_canLoadMagazine.sqf

- Close #9103.
- Fix wrong config lookup.

CSW - Fix Belt Linking for Static Weapons

---

addons/refuel/stringtable.xml

- Added Korean translation related to Cargo Refuel

Added Korean Translation

---

docs/wiki/framework/repair-framework.md

- Improve repair framework docs

Repair - Improve framework documentation

---

docs/wiki/framework/refuel-framework.md

- Updated the refuel framework documentation analog to #9114

Refuel - Improve framework documentation

---

addons/ballistics/stringtable.xml
addons/captives/stringtable.xml
addons/cargo/stringtable.xml
addons/chemlights/stringtable.xml
addons/common/stringtable.xml
addons/disposable/stringtable.xml
addons/dogtags/stringtable.xml
addons/flashlights/stringtable.xml
addons/grenades/stringtable.xml
addons/huntir/stringtable.xml
addons/interact_menu/stringtable.xml
addons/microdagr/stringtable.xml
addons/optics/stringtable.xml
addons/realisticnames/stringtable.xml

- Corrected the awkwardness of the sentence and completed the translation of proper nouns into Hangul.

Korean Translation Improved

---

addons/explosives/XEH_postInit.sqf
addons/explosives/XEH_preInit.sqf

Explosives - Fix mine defuse exclusion not working before postInit is executed

---

addons/common/functions/fnc_getVehicleCargo.sqf

Common - Fix script error in fnc_getVehicleCargo

---

optionals/compat_sog/CfgVehicles/land.hpp

- Adds ACE Fuel compatibility for Land_vn_b_prop_fueldrum_01 - the fuel barrel with the hand pump on top
- [] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).

Refuel - Add `Land_vn_b_prop_fueldrum_01` compat

---

addons/arsenal/functions/fnc_addVirtualItems.sqf
addons/arsenal/functions/fnc_removeVirtualItems.sqf

- Use `isNull` instead of `== objNull`

Arsenal - Fix null comparison

---

AUTHORS.txt
addons/cargo/functions/fnc_unloadCarryItem.sqf
addons/common/functions/fnc_isModLoaded.sqf
addons/csw/functions/fnc_ai_handleGetIn.sqf
addons/csw/functions/fnc_ai_reload.sqf
addons/medical_statemachine/functions/fnc_enteredStateUnconscious.sqf
docs/team.md

Docs - Add Grim to maintainers

---

addons/frag/CfgAmmo.hpp
addons/medical_damage/CfgAmmo.hpp
optionals/compat_rhs_usf3/CfgAmmo.hpp

- Title. Allows for fragmentation to cause puncture wounds.
- Includes same changes to RHS shrapnel and explosive 12 gauge rounds.

Frag/Medical Damage - Treat shrapnel as grenade damage

---

addons/medical_treatment/functions/fnc_tourniquetRemove.sqf

Medical Treatment - Use shared equipment setting on tourniquet removal

---

optionals/compat_rhs_afrf3/CfgWeapons.hpp
optionals/compat_rhs_usf3/CfgWeapons.hpp

- Title.
This can be switched to RHS icons, too.

Compats - Add mod icon for CSW gunbags

---

addons/intelitems/CfgMagazines.hpp

- Title.
Found while testing #9040. If the intent is just to hide them from the arsenal, we should be using scopeArsenal.

Intel Items - Change scope for better Arsenal filtering

---

optionals/compat_sog/CfgWeapons/csw.hpp

Compat - Add arsenal mod icons for CSW

---

addons/repair/initSettings.sqf
addons/repair/stringtable.xml

- Title.
Old translations kept, but might need to be updated?

Repair - Change Repair Threshold setting descriptions

---

addons/medical/stringtable.xml

Medical - Change Epinephrine Wake Up Boost setting description

---

docs/wiki/framework/wirecutter-framework.md

- _Add documentation for changes to wirecutter framework as well as undocumented functionality.

Logistics Wirecutter - Add documentation

---

addons/common/functions/fnc_codeToString.sqf

- Updated to use [toString](https://community.bistudio.com/wiki/toString)

Common - Improve fnc_codeToString

---

addons/common/XEH_PREP.hpp
addons/common/functions/fnc_hasZeusAccess.sqf

- Add `ace_common_fnc_hasZeusAccess`. Does what it says on the tin.

Common - Add `FUNC(hasZeusAccess)`

---

docs/wiki/feature/vehicles.md

Following #8967.
Please suggest better sentences.

Vehicles - Document Resume/Set speed control functionality

---

optionals/compat_rhs_afrf3/CfgWeapons.hpp
optionals/compat_rhs_gref3/CfgWeapons.hpp
optionals/compat_rhs_saf3/CfgWeapons.hpp
optionals/compat_rhs_usf3/CfgWeapons.hpp

RHS Compat - Improve macro usage

---

addons/arsenal/functions/fnc_statTextStatement_scopeVisionMode.sqf

Arsenal - Improve NVG Supported stat detection

---

.github/workflows/pboproject.yml
tools/.vscode/tasks.json

ui_f_enoch  removed in https://github.com/acemod/ACE3/pull/8838

workflow/tools - trivial cleanup

---

addons/compat_ws/addon.toml
optionals/compat_sog/addon.toml
tools/make.py
tools/sqfvmChecker.py

- Update `preprocess` in addon.toml to be an object (HEMTT 1.7.1)

Tools - HEMTT preprocess is now an object

---

tools/make.py
tools/sqfvmChecker.py

can't just re-read() a file in python without moving cursor back or something
change to just read once

Tools - fix toml file read

---

addons/novehicleclanlogo/functions/fnc_removeClanLogo.sqf
addons/tagging/functions/fnc_createTag.sqf

- Title.
- Fix undefined variable in `TRACE`.

No Vehicle Logo - Skip removing clan tag if spray painted

---

extensions/CMakeLists.txt

ref https://github.com/google/googletest/issues/3663

Extensions - Fix gtest branch change

---

addons/reload/ACE_UI.hpp
addons/reload/config.cpp
addons/ui/functions/fnc_setAdvancedElement.sqf

- Title.
- Close #9182
- Update UI condition for ammo count added in ACE_Reload.
- Change some `count` loops to `forEach`.

UI - Fix UAVs not being considered vehicles for HUD elements

---

addons/arsenal/functions/fnc_replaceUniqueItemsLoadout.sqf

Arsenal - Fix for #9040 and #9293

---

addons/laser/RscInGameUI.hpp
addons/laser/config.cpp
addons/laser/functions/fnc_onLaserDesignatorDraw.sqf
addons/laser/script_component.hpp

Laser - Cleanup laser designator config and code

---

addons/medical_treatment/functions/fnc_loadUnit.sqf

- Title.
- Tried to remove an extra new line at the very bottom, unsure if I succeeded.

Medical treatment - Fix undefined variable in ace_medical_treatment_fnc_loadUnit

---

addons/arsenal/functions/fnc_updateUniqueItemsList.sqf

- Title.
- Credit to @LinkIsGrim for finding it.

Arsenal - Fix unique explosives showing up in the "all magazines" tab

---

addons/repair/functions/fnc_getHitPointsToIgnore.sqf

- Allow repairing headlights.
- Close #9177.
We might wanna look into having this as a separate action type, similar to wheels/tracks, with a custom display name instead, as lights hitpoints don't have consistent classnames and thus can't be localized reliably.

Repair - Make headlights repairable

---

addons/arsenal/functions/fnc_addStat.sqf
addons/arsenal/functions/fnc_onArsenalOpen.sqf
addons/arsenal/functions/fnc_renameDefaultLoadout.sqf
addons/arsenal/functions/fnc_replaceUniqueItemsLoadout.sqf
addons/arsenal/functions/fnc_statTextStatement_binoMag.sqf
addons/artillerytables/functions/fnc_interactMenuOpened.sqf
addons/common/functions/fnc_canDig.sqf
addons/common/functions/fnc_cbaSettings_convertHelper.sqf
addons/medical_damage/functions/fnc_getTypeOfDamage.sqf
addons/microdagr/functions/fnc_updateDisplay.sqf
addons/rearm/functions/fnc_addVehicleMagazinesToSupply.sqf

fix common_canDig
fix arsenal_renameDefaultLoadout
+trivial/logging bugs

Various - Misc Cleanup

---

addons/medical_gui/functions/fnc_updateCategories.sqf
addons/medical_gui/gui.hpp

- Add colouration for currently selected category.
- Add slight transparency increase when mousing over category

Medical GUI - Improve Selected Category colouration

---

addons/arsenal/functions/fnc_scanConfig.sqf
addons/arsenal/functions/fnc_updateUniqueItemsList.sqf

- Title.
- Teach Grim a lesson in triple-checking things before merging.

Arsenal - Fix virtual non-weapon magazines in inventory being treated as unique

---

addons/arsenal/functions/fnc_scanConfig.sqf

Arsenal - Fix magazine misc items categorization

---

addons/medical_damage/stringtable.xml

Translation for #8394
https://github.com/acemod/ACE3/pull/8394/commits/0f0d0b459b4700fd9c9b0f913c64ef53e16123d9#diff-6eef39b021ad51fd7d94380ea9f7e36cc6f59b727a62cc29165f14abe64a86f6

Add french translation for new painUnconsciousTreshold setting

---

addons/maptools/functions/fnc_updateMapToolMarkers.sqf

Map Tools - Fix for 2.14 aspect ratio changes

---

tools/make.py

Maybe fix random failed builds

Tools - make.py will try running pboProject once if it's not in registry

---

addons/explosives/CfgWeapons.hpp
addons/explosives/XEH_preInit.sqf
addons/explosives/XEH_preStart.sqf
addons/explosives/functions/fnc_canDefuse.sqf
addons/explosives/functions/fnc_interactEH.sqf

- Title, reads off of config property. Last tool in mod without this functionality afaik

Explosives - Add modded defusal kit support

---

addons/gunbag/XEH_preInit.sqf

- Title.
I consider this an exploit. Cleaner solutions welcome.

Gunbag - Add check for weapon in virtual items on loadout set

---

addons/arsenal/functions/fnc_onSelChangedRight.sqf

- Requires 2.14.
- See https://feedback.bistudio.com/T173880

Arsenal - Remove redundant fix for hand guns and binoculars with secondary muzzles

---

addons/fastroping/functions/fnc_deployAIWaypoint.sqf

Fastroping - Remove 2.12 compatibility

---

addons/main/script_mod.hpp
addons/maptools/functions/fnc_updateMapToolMarkers.sqf

Maptools - Cleanup pre-2.14 compatibility code

---

addons/common/functions/fnc_removeSpecificMagazine.sqf

- Title.
- Improve the function a bit.

Common - Improve `FUNC(removeSpecificMagazine)` with 2.14 changes

---

addons/medical_treatment/functions/fnc_hasItem.sqf
addons/medical_treatment/functions/fnc_useItem.sqf

- Title.
Requires 2.14. Could use CBA functions to do it in 2.12 if wanted.

Medical - Add treating with items from vehicle inventory

---

addons/nightvision/CfgWeapons.hpp

- Title.
Subjective? They are more advanced.

Night Vision - Change Apex and Wide NVGs to Gen 4

---

addons/advanced_fatigue/functions/fnc_getMetabolicCosts.sqf

Advanced Fatigue - Fix metabolic cost mass multiplier for walking

---

docs/wiki/framework/medical-framework.md

Docs - Add note in documentation regarding medical internal variables

---

addons/fire/functions/fnc_burnReaction.sqf

Fire - Fix macro

---

addons/ai/stringtable.xml
addons/arsenal/stringtable.xml
addons/ballistics/stringtable.xml
addons/cargo/stringtable.xml
addons/casings/stringtable.xml
addons/common/stringtable.xml
addons/cookoff/stringtable.xml
addons/dragging/stringtable.xml
addons/fastroping/stringtable.xml
addons/hunterkiller/stringtable.xml
addons/laser/stringtable.xml
addons/marker_flags/stringtable.xml
addons/medical_ai/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_status/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/nightvision/stringtable.xml
addons/novehicleclanlogo/stringtable.xml
addons/refuel/stringtable.xml
addons/reloadlaunchers/stringtable.xml
addons/repair/stringtable.xml
addons/tagging/stringtable.xml
addons/towing/stringtable.xml
addons/trenches/stringtable.xml
addons/ui/stringtable.xml
addons/viewports/stringtable.xml

Add Missing German Translations

Translation - Add German Translation

---

AUTHORS.txt
addons/ai/stringtable.xml
addons/arsenal/stringtable.xml
addons/ballistics/stringtable.xml
addons/cargo/stringtable.xml
addons/cookoff/stringtable.xml
addons/dragging/stringtable.xml
addons/hunterkiller/stringtable.xml
addons/laser/stringtable.xml
addons/medical_ai/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_status/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/nightvision/stringtable.xml
addons/refuel/stringtable.xml
addons/reload/stringtable.xml
addons/reloadlaunchers/stringtable.xml
addons/repair/stringtable.xml
addons/tagging/stringtable.xml

- Add missing polish translations
- Fix spelling in existing translations

Translations - Add Polish Translations

---

tools/make.py

Tools - Fix make.py failing when pboProject\Settings folder missing

---

tools/setup.py

ref https://ace3.acemod.org/wiki/development/setting-up-the-development-environment.html#411-file-patching-setup
e.g.
```
y: F:\DEV\ACE3\.hemttout\dev
n: F:\DEV\ACE3
(y/n):
```

Tools - Update setup.py for `hemmt dev` filepatching

---

addons/markers/functions/fnc_getEnabledChannels.sqf
addons/markers/functions/fnc_initInsertMarker.sqf
addons/markers/functions/fnc_onLBSelChangedChannel.sqf

Markers - Fix issues with custom channels

---

docs/wiki/framework/sitting-framework.md

- Add a missing property to the sitting docs

Docs - Fix missing sitting property in docs

---

docs/wiki/feature/irlight.md

Docs - Fix IR Lights docs

---

addons/irlight/CfgWeapons.hpp
addons/irlight/config.cpp
addons/laserpointer/CfgWeapons.hpp
addons/laserpointer/script_component.hpp
addons/laserpointer/script_macros_config.hpp

- Title.
- Remove `ace_laserpointer` dependency.

IR Lights - Fix visible pointers for DBAL

---

addons/casings/functions/fnc_createCasing.sqf

- Adds Western Sahara casings.

Casings - Add Western Sahara Casings

---

addons/grenades/functions/fnc_flashbangThrownFuze.sqf

- Title, previous sound was out of place in Arma

Grenades - Improve flashbang sound

---

addons/medical_treatment/functions/fnc_surgicalKitProgress.sqf

Medical Treatment - Fix clearing trauma after stitch with multiple wounds

---

addons/backpacks/XEH_postInit.sqf
addons/backpacks/functions/fnc_isBackpack.sqf

Backpacks - Code cleanup

---

addons/backpacks/functions/fnc_isBackpack.sqf

Backpacks - Add extra condition for backpack checking

---

addons/compat_ws/compat_ws_realisticnames/CfgWeapons.hpp
addons/compat_ws/compat_ws_realisticnames/stringtable.xml

- Removes caliber from weapon name. Follow up to (#9419)

Compat WS RealisticNames - XMS

---

addons/ai/stringtable.xml
addons/arsenal/stringtable.xml
addons/ballistics/stringtable.xml
addons/captives/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/concertina_wire/stringtable.xml
addons/cookoff/stringtable.xml
addons/dragging/stringtable.xml
addons/fastroping/stringtable.xml
addons/irlight/stringtable.xml
addons/laser/stringtable.xml
addons/medical_ai/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_engine/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_status/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/nightvision/stringtable.xml
addons/reload/stringtable.xml
addons/reloadlaunchers/stringtable.xml
addons/repair/stringtable.xml
addons/tagging/stringtable.xml

- Added Korean translation of strings to be updated later
- Improved Korean translation of few strings

Korean translation Updated

---

addons/medical_treatment/functions/fnc_canDigGrave.sqf

Medical Treatement - Don't allow conscious patients to be buried

---

addons/medical_treatment/ACE_Medical_Treatment.hpp
addons/realisticnames/CfgWeapons.hpp

these normally won't ever be parsed because of the addon.toml but doesn't hurt to fix up

Misc - Config caplitzation fixes

---

addons/compat_sog/CfgAmmo/explosives.hpp
addons/compat_sog/CfgMagazines/explosives.hpp
addons/compat_sog/CfgVehicles/explosives.hpp

- Title.
Changelog says there were 6 new mines added but those are the only 4 I found.

Compat SOG - Add explosives support to 1.3 mines

---

addons/ballistics/functions/fnc_statTextStatement_magazineMuzzleVelocity.sqf
addons/ballistics/functions/fnc_statTextStatement_weaponMuzzleVelocity.sqf

Close #9449
try to use AB if possible but if not then at least show initSpeed

Arsenal - Always show muzzle velocity even if not configured for AB

---

addons/trenches/functions/fnc_blockTrench_place.sqf
addons/zeus/functions/fnc_getModuleDestination.sqf
addons/zeus/functions/fnc_moduleLayTrench.sqf

`getModuleDestination` can run draw code each frame
shows exactly where trench blocks will go which can be confusing because we're limited to cardinal directions

Zeus - Show where trench will go 

---

addons/interact_menu/functions/fnc_keyUp.sqf

Interact Menu - Fix zeus cursor menu closing

---

addons/reload/ACE_Arsenal_Stats.hpp
addons/reload/config.cpp
addons/reloadlaunchers/ACE_Arsenal_Stats.hpp
addons/reloadlaunchers/config.cpp
addons/reloadlaunchers/stringtable.xml

I guess part bug report: where is the `800 rpm` from?

Arsenal - Add stats for reloadable launchers and belt linking

---

addons/medical_gui/initSettings.sqf

- Change default undamaged body image colors to improve contrast

Medical GUI - Change default body color to improve contrast

---

addons/medical_gui/XEH_PREP.hpp
addons/medical_gui/functions/fnc_onKeyDown.sqf
addons/medical_gui/gui.hpp

- Set up keyboard handling for medical menu
- Add keyboard shortcuts to select categories and body parts

Medical GUI - Add keyboard shortcuts for selecting medical menu categories and body parts

---

addons/fieldmanual/CfgHints.hpp
addons/fieldmanual/stringtable.xml

- Title.
Explains the keybinds and R/L indicators.

Field Manual - Add Medical Menu entry

---

addons/common/functions/fnc_swayLoop.sqf

Common - Increase sway update frequency

---

addons/medical_gui/functions/fnc_updateCategories.sqf

Medical GUI - Use selected color when triage category selected

---

addons/medical_gui/gui.hpp

Medical GUI - Fix action button width

---

.github/CONTRIBUTING.md

Docs - use draft PR over WIP

---

addons/fieldmanual/CfgHints.hpp
addons/fieldmanual/stringtable.xml

- Title.
- Add note on sutures being consumable items.
- Close #9508

Field Manual - Fix HuntIR Monitor & Fortify Tool display names

---

addons/medical_gui/gui.hpp

Medical GUI - Fix Medical Menu triage button position

---

addons/medical_gui/stringtable.xml

Translations - Update Chinessimp

---

addons/arsenal/XEH_PREP.hpp
addons/arsenal/functions/fnc_getVirtualItems.sqf

- Add API function for getting flat list of virtual items from a box.

Arsenal - Add `FUNC(getVirtualItems)`

---

addons/advanced_fatigue/XEH_postInit.sqf
addons/advanced_fatigue/initSettings.sqf
addons/advanced_fatigue/stringtable.xml

- Add settings to change sway multiplier while the player's weapon is rested or deployed

Advanced Fatigue - Add settings to change sway factor with weapon rested/deployed

---

addons/advanced_throwing/XEH_postInit.sqf
addons/advanced_throwing/functions/fnc_throwFiredXEH.sqf

Close #9532
```
ace_advanced_throwing_ammoEventHandlers:
[["SPE_SHG24",[{_this call SPE_fnc_grenade_firedEH}]],["GrenadeHand",[]]]
```

Advanced Throwing - Call ammo event handlers

---

addons/medical/stringtable.xml
addons/medical_feedback/initSettings.sqf
addons/medical_gui/initSettings.sqf

- Move the settings in the GUI and Feedback modules to a separate category

Medical - Move GUI and Feedback settings to separate category

---

addons/arsenal/functions/fnc_attributeAddItems.sqf

Arsenal - Fix editor attribute search

---

addons/medical_treatment/functions/fnc_placeInBodyBagOrGrave.sqf

- Title.
If created on a slope, graves would float.

Medical - Make dug graves respect terrain slope

---

addons/medical_gui/functions/fnc_onKeyDown.sqf

- Prevent switching to disabled or selected categories via keybinds
- Add sound feedback.

Medical GUI - Add sound and conditional switching to Medical Menu keybinds

---

.hemtt/project.toml
addons/compat_rhs_usf3/CfgVehicles.hpp

- title
- Adds RHS launch config to HEMTT
- Source, [page 5](https://apps.dtic.mil/sti/pdfs/ADA388153.pdf)

Compat RHS - Add hunterkiller support to M2A3

---

addons/arsenal/ACE_Arsenal_Stats.hpp
addons/arsenal/XEH_PREP.hpp
addons/arsenal/functions/fnc_statTextStatement_illuminators.sqf
addons/arsenal/stringtable.xml

Arsenal - Add stat for capabilities of pointer attachments

---

addons/dragging/functions/fnc_carryObject.sqf
addons/dragging/functions/fnc_carryObjectPFH.sqf
addons/dragging/functions/fnc_dragObject.sqf
addons/dragging/functions/fnc_dragObjectPFH.sqf
addons/dragging/functions/fnc_dropObject.sqf
addons/dragging/functions/fnc_dropObject_carry.sqf

- Title.
Blame @veteran29 for bringing this up.

Dragging - Prevent carrying crewed static weapons

---

addons/arsenal/XEH_PREP.hpp
addons/arsenal/functions/fnc_addVirtualItems.sqf
addons/arsenal/functions/fnc_onArsenalOpen.sqf
addons/arsenal/functions/fnc_openBox.sqf
addons/arsenal/functions/fnc_refresh.sqf
addons/arsenal/functions/fnc_removeBox.sqf
addons/arsenal/functions/fnc_removeVirtualItems.sqf
addons/arsenal/functions/fnc_updateVirtualItemsFlat.sqf
addons/arsenal/stringtable.xml

- Title.
- Move updating `GVAR(virtualItemsFlat)` to function
- Update English "No virtual item" stringtable to plural, rest are fine as they refer to "None" items being available.

Arsenal - Add support for modifying Virtual Items while opened

---

addons/arsenal/functions/fnc_attributeAddItems.sqf
addons/arsenal/functions/fnc_handleSearchbar.sqf

- Title.
- Readd the filter matching I removed.
- Close #9534 

Arsenal - Fix search case-sensitivy for non-ANSI characters

---

addons/medical_gui/CfgVehicles.hpp
addons/medical_gui/XEH_postInit.sqf
addons/medical_gui/functions/fnc_displayPatientInformation.sqf
addons/medical_gui/functions/fnc_updateInjuryList.sqf

- Title.
- Close #9510 
Just skips the injury list

Medical GUI - Skip body part-specific info for medical peek

---

addons/dragging/functions/fnc_getWeight.sqf
addons/dragging/initSettings.sqf
addons/dragging/stringtable.xml

- Add a setting to skip weight calculations entirely.

Dragging - Add setting for Max Weight Coefficient

---

addons/ai/stringtable.xml
addons/ballistics/stringtable.xml
addons/csw/stringtable.xml
addons/dragging/stringtable.xml
addons/hunterkiller/stringtable.xml
addons/irlight/stringtable.xml
addons/killtracker/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/nightvision/stringtable.xml
addons/noradio/stringtable.xml
addons/overheating/stringtable.xml
addons/reloadlaunchers/stringtable.xml
addons/ui/stringtable.xml
addons/viewports/stringtable.xml
addons/viewrestriction/stringtable.xml

- Add some missing french translations

Translations - Add missing french translations

---

addons/medical_treatment/CfgWeapons.hpp

- Fix a semicolon somebody missed. _shame._

Medical Treatment - Fix missing semicolon

---

addons/advanced_fatigue/stringtable.xml
addons/compat_rhs_usf3/compat_rhs_usf3_csw/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/dragging/stringtable.xml
addons/fieldmanual/stringtable.xml
addons/medical_ai/stringtable.xml
addons/medical_engine/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/reloadlaunchers/stringtable.xml
addons/zeus/stringtable.xml

- Add Missing German Translation
- (Field Manual is not complete, though.)

Translation - German Addition/Improvement

---

AUTHORS.txt
docs/team.md

- Title
- Tests if permissions are working properly.

Documentation - Add johnb432 to maintainers

---

addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
addons/medical_treatment/stringtable.xml

- An action for each color of bodybag
- Some translations need to be redone

Medical Treatment: separate actions for each bodybag

---

addons/arsenal/Cfg3DEN.hpp
addons/arsenal/Display3DEN.hpp
addons/attach/CfgVehicles.hpp
addons/cargo/CfgEden.hpp
addons/cargo/menu.hpp
addons/common/CompassControl.hpp
addons/common/functions/fnc_disableUserInput.sqf
addons/compat_sog/compat_sog_trenches/CfgVehicles.hpp
addons/explosives/CfgVehicles.hpp
addons/explosives/ExplosivesUI.hpp
addons/fcs/CfgVehicles.hpp
addons/hearing/CfgEventHandlers.hpp
addons/hearing/CfgVehicles.hpp
addons/interaction/CfgVehicles.hpp
addons/interaction/RscTitles.hpp
addons/javelin/RscInGameUI.hpp
addons/map_gestures/CfgEventHandlers.hpp
addons/markers/InsertMarker.hpp
addons/optionsmenu/gui/pauseMenu.hpp
addons/overheating/CfgVehicles.hpp
addons/tagging/CfgEden.hpp
addons/trenches/CfgVehicles.hpp
addons/vehicle_damage/CfgAmmo.hpp
addons/viewports/gui.hpp
tools/make.py

- Fix / suppress warnings from https://github.com/BrettMayson/HEMTT/pull/587

Tools - HEMTT PW3 fixes

---

addons/medical/stringtable.xml
addons/medical_ai/stringtable.xml
addons/medical_damage/stringtable.xml
addons/medical_engine/stringtable.xml
addons/medical_feedback/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_status/stringtable.xml
addons/medical_treatment/stringtable.xml

- _Add missing words_
- _Change some wording_

Translations - Improve Japanese Medical Localization

---

addons/fire/addon.toml
addons/fire/config.cpp
addons/medical/addon.toml
addons/medical/config.cpp
addons/medical_ai/addon.toml
addons/medical_ai/config.cpp
addons/medical_blood/addon.toml
addons/medical_blood/config.cpp
addons/medical_damage/addon.toml
addons/medical_damage/config.cpp
addons/medical_engine/addon.toml
addons/medical_engine/config.cpp
addons/medical_feedback/addon.toml
addons/medical_feedback/config.cpp
addons/medical_gui/addon.toml
addons/medical_gui/config.cpp
addons/medical_statemachine/addon.toml
addons/medical_statemachine/config.cpp
addons/medical_status/addon.toml
addons/medical_status/config.cpp
addons/medical_treatment/addon.toml
addons/medical_treatment/config.cpp
addons/medical_vitals/addon.toml
addons/medical_vitals/config.cpp
addons/realisticnames/addon.toml
addons/realisticnames/config.cpp
tools/make.py
tools/sqfvmChecker.py

- Alternative to #9612 
- Requires HEMTT 1.10.0 with https://github.com/BrettMayson/HEMTT/pull/592

Tools: HEMTT ignore has_include

---

addons/goggles/functions/fnc_applyDirtEffect.sqf
addons/goggles/functions/fnc_applyDustEffect.sqf
addons/goggles/functions/fnc_applyGlassesEffect.sqf
addons/goggles/functions/fnc_handleExplosion.sqf

Goggles - Draw under HUD (requires 2.16)

---

addons/medical_treatment/CfgWeapons.hpp

- Lowers mass from 1 to 0.1 for a more realistic weight.
- Closes #9628 

Medical Treatment - Lower suture weight from 1 to 0.1

---

addons/refuel/functions/fnc_connectNozzleAction.sqf
addons/refuel/functions/fnc_makeJerryCan.sqf
addons/refuel/functions/fnc_startNozzleInHandsPFH.sqf
addons/refuel/functions/fnc_takeNozzle.sqf
addons/refuel/stringtable.xml

Refuel - Add separate names for jerry can interactions

---

addons/towing/XEH_postInit.sqf
addons/towing/functions/fnc_startTow.sqf
addons/towing/functions/fnc_towStateMachinePFH.sqf

I don't really like all those global vars but looks like it's the best.
Please suggest better comments if you can.

Towing - Fix swimming issues

---

addons/medical_damage/initSettings.sqf

Medical - Change default Fatal Injuries Source setting to Either

---

.github/release-drafter.yml

- Add handling for `kind/change` label
- Add SETTINGS header for settings-related changes (add/remove/change default), under `kind/setting` label

Update release drafter for new labels

---

addons/advanced_fatigue/stringtable.xml
addons/ai/stringtable.xml
addons/arsenal/stringtable.xml
addons/captives/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/dragging/stringtable.xml
addons/field_rations/stringtable.xml
addons/fieldmanual/stringtable.xml
addons/irlight/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/realisticnames/stringtable.xml
addons/refuel/stringtable.xml
addons/reloadlaunchers/stringtable.xml
addons/zeus/stringtable.xml

- _Add missing words for Japanese_
- _Standardization of wording phrases with KAT Adv Med_

Translations - Improve Japanese

---

addons/hunterkiller/CfgVehicles.hpp
addons/hunterkiller/stringtable.xml

- Enable the Hunter Killer system on the Tanks DLC's Rooikat 120 (NATO Tank Destroyer);
- Add italian translations;

Hunter Killer - Enable on Rooikat 120 and add italian translations

---

addons/xm157/functions/fnc_keyPress.sqf

XM157 - Fix zeroing for secondary muzzles

---

.github/workflows/pboproject.yml

- Fix extraction of game data for pboproject during CI
Change in GitHub Actions: https://github.com/actions/runner-images/pull/8875

ci: Update 7zip function to extract game data

---

addons/medical_damage/functions/fnc_woundsHandlerVehiclehit.sqf
addons/medical_engine/functions/fnc_handleDamage.sqf

Medical - Fix hanging when vehicle crew receive fatal damage

---

addons/dragging/functions/fnc_canCarry.sqf
addons/dragging/functions/fnc_canDrag.sqf

Dragging - Minor optimisation

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

- Title, save time on new releases

Release Drafter - Sort changelog by PR title

---

.github/release-drafter.yml

- Change to ascending
Didn't see default was descending, whoops.

Fix release drafter sort direction

---

.hemtt/project.toml

- Remove an undocumented flag that is no longer used

Tools - Remove unused property from .hemtt

---

addons/arsenal/functions/fnc_fillRightPanel.sqf
addons/arsenal/functions/fnc_updateUniqueItemsList.sqf

- Title.
- Small optimization for cargo lookup.
Ignore changelog, not present in 3.16.1

Arsenal - Fix cargo backpacks not being shown in right panel

---

addons/arsenal/functions/fnc_fillRightPanel.sqf
addons/arsenal/functions/fnc_updateUniqueItemsList.sqf

- Disables #9694 for weapons.
- Uses `baseWeapon` for weapons and attachments when updating unique items.

Arsenal - Fix unique item edge cases and prevent increasing quantity of cargo weapons

---

addons/markers/functions/fnc_onLBSelChangedChannel.sqf

Fixes an issue introduced in this PR: https://github.com/acemod/ACE3/pull/9693

Markers - Fix logic error when selecting channel

---

addons/reload/functions/fnc_canCheckAmmoSelf.sqf

Reload - Disable 'Check Ammo' self interaction when unarmed

---

addons/arsenal/missions/Arsenal.VR/XEH_postInit.sqf

Arsenal - Fix wrong animation upon opening the arsenal in VR while empty-handed

---

addons/common/CfgMoves.hpp
addons/medical_engine/CfgMoves.hpp
addons/medical_status/functions/fnc_setUnconsciousState.sqf

Medical - Disable AI twitching when unconscious

---

addons/captives/functions/fnc_doEscortCaptive.sqf
docs/wiki/framework/events-framework.md

Captives - Added listenable escorting EH

---

addons/ballistics/functions/fnc_statTextStatement_magazineMuzzleVelocity.sqf
addons/ballistics/functions/fnc_statTextStatement_weaponMuzzleVelocity.sqf
addons/kestrel4500/functions/fnc_collectData.sqf
addons/rangecard/functions/fnc_calculateRangeCard.sqf
addons/rangecard/functions/fnc_updateRangeCard.sqf
addons/xm157/functions/fnc_ballistics_getData.sqf

- Title.
- Close #9669.
- Add better support for changing Advanced Ballistics settings mid-mission for the range card.

Ballistics - Respect Advanced Ballistics settings for displaying muzzle velocities

---

addons/nightvision/stringtable.xml

- _Hotfix 4th Gen NVG (Green WP) shown as 3rd Gen_

Translations - Fix Japanese NVG localization just one typo.

---

docs/wiki/framework/medical-treatment-framework.md

Add documentation for Medical Vehicles & Facilities

---

addons/marker_flags/CfgWeapons.hpp

- I feel like these should be reduced as with other items recently

Marker Flags - Reduce mass

---

addons/medical_engine/functions/fnc_handleDamage.sqf

- Title.
Found while testing #9732. Won't affect anything since 0 damage just results in no wounds anyway.

Medical Engine - Exit early if incoming damage is 0

---

addons/viewrestriction/XEH_clientInit.sqf

- It can be 0 or 2, only use ACE's when it is fully enabled in the difficulty settings

View Restriction -  Handle thirdPersonView difficulty setting correctly

---

addons/arsenal/functions/fnc_statTextStatement_scopeVisionMode.sqf
addons/arsenal/stringtable.xml

- Title.
Added two new string because otherwise 2 combined strings would be too long.
I'm not sure about the implementation, might be better to change it to something similar to what NVGs have instead.

Arsenal - Add thermal vision support to scopes vision mode stat

---

addons/medical_engine/functions/fnc_handleDamage.sqf

- https://github.com/acemod/ACE3/pull/9733#issuecomment-1892963588

Medical Engine - Don't skip hdbracket ever

---

addons/dragging/functions/fnc_startCarryLocal.sqf
addons/dragging/functions/fnc_startDragLocal.sqf

adds a little logging just in case

Dragging - Add logging for claimSafe failure

---

addons/arsenal/XEH_preInit.sqf
addons/arsenal/functions/fnc_buttonActionsPage.sqf
addons/arsenal/functions/fnc_buttonHide.sqf
addons/arsenal/functions/fnc_buttonStatsPage.sqf
addons/arsenal/functions/fnc_onArsenalClose.sqf
addons/arsenal/functions/fnc_onArsenalOpen.sqf

- Addresses #9722.
- Some cleanup.

Arsenal - Fixed stats & actions appearing when they shouldn't be

---

addons/common/XEH_postInit.sqf
addons/common/functions/fnc_statusEffect_addType.sqf
addons/common/functions/fnc_statusEffect_sendEffects.sqf

- Title.
- Close #9427
Useful for global arg/local effect commands.

Common - Add JIP support to status effects

---

addons/common/XEH_preInit.sqf

- Title.
Untested, but an undefined variable is definitely going to cause an error.

Common - Fixed status effects

---

addons/aircraft/stringtable.xml
addons/arsenal/stringtable.xml
addons/cargo/stringtable.xml
addons/common/stringtable.xml
addons/field_rations/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/rearm/stringtable.xml
addons/refuel/stringtable.xml
addons/repair/stringtable.xml
addons/zeus/stringtable.xml

- _fill missing cargo and arsenal words in last update_
- _tweak some wordings in Japanese localization_

Translations - Improve/Add Japanese localization

---

addons/cargo/functions/fnc_startLoadIn.sqf

Cargo - Fix object lock when failling to load a carried object

---

addons/arsenal/functions/fnc_fillLeftPanel.sqf

Arsenal - Make face tab adhere to mod icon setting

---

addons/hellfire/functions/fnc_getAttackProfileSettings.sqf

Fix hellfire script error

---

addons/common/define.hpp

Common - Cleanup define.hpp

---

addons/smallarms/CfgWeapons.hpp

- Title.
Why is this inheritance tree like this? Who knows.

Small Arms - Fix magazineReloadTime for vehicle FN Minimi SPW

---

addons/arsenal/XEH_preInit.sqf
addons/arsenal/defines.hpp
addons/arsenal/functions/fnc_addAction.sqf
addons/arsenal/functions/fnc_compileActions.sqf
addons/arsenal/functions/fnc_handleActions.sqf
addons/arsenal/ui/RscAttributes.hpp
docs/wiki/framework/arsenal-framework.md

Arsenal Actions - Add support for multiline text & updating on cargo event

---

docs/wiki/feature/atragmx.md

Documentation - Fix Wiki AtragMx links

---

addons/inventory/XEH_preStart.sqf

- Was accidentally added in #9706. It doesn't break anything, but it's pointless.

Inventory - Remove duplicate code

---

addons/arsenal/functions/fnc_fillLoadoutsList.sqf

Arsenal - Fill loadouts list over multiple frames

---

.github/workflows/arma.yml
.github/workflows/documentation.yml
.github/workflows/extensions.yml
.github/workflows/hemtt.yml
.github/workflows/pboproject.yml
.github/workflows/release-drafter.yml

CI - Use Node.js 20 actions

---

addons/cargo/stringtable.xml
addons/compat_cup_weapons/compat_cup_weapons_csw/stringtable.xml
addons/dogtags/stringtable.xml
addons/explosives/stringtable.xml
addons/hearing/stringtable.xml
addons/killtracker/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/medical_vitals/stringtable.xml

- _Update japanese localization_

Translations - Improve Japanese localization

---

addons/medical_gui/functions/fnc_updateInjuryList.sqf
addons/medical_gui/initSettings.inc.sqf
addons/medical_gui/stringtable.xml

- Adds an option to show the bleeding state, with or without the rate

Medical GUI - Show Bleeding Rate

---

README.md

- Replace hard-coded version badge in README

Improve version badge

---

addons/compat_cup_terrains/addon.toml
addons/compat_cup_terrains/config.cpp
addons/compat_cup_vehicles/addon.toml
addons/compat_cup_vehicles/config.cpp
addons/compat_cup_weapons/addon.toml
addons/compat_cup_weapons/config.cpp

This lets us release before or after

CUP Compats - Don't load if cup's compats present (temporary)

---

docs/team.md

Documentation - Add Kex to maintainers

---

AUTHORS.txt
docs/team.md

Documentation - Add MiszczuZPolski to Team page

---

AUTHORS.txt
docs/team.md

Documentation - Update management team

---

addons/rearm/functions/fnc_initSupplyVehicle.sqf

- Undefined variable caused issue in discord: https://discord.com/channels/976165959041679380/1210646913242759178.

Rearm - Fix actions not being added immeditately

---

addons/arsenal/stringtable.xml
addons/cargo/stringtable.xml
addons/hearing/stringtable.xml
addons/killtracker/stringtable.xml
addons/maptools/stringtable.xml
addons/markers/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/medical_vitals/stringtable.xml
addons/overheating/stringtable.xml

- Italian translations for all the new stuff added since d70fbd576527da300b26a82d51573f7950b163ab;

Translations - Complete Italian

---

addons/common/CfgMoves.hpp

- Fix was taken from the Arma discord (https://discord.com/channels/105462288051380224/108187245529268224/1215044051137728552), made by Leopard20.
- Unaware of unintended side effects.

Common - Fix players sliding when holstering weapons

---

addons/dragging/functions/fnc_startCarryLocal.sqf
addons/dragging/functions/fnc_startDragLocal.sqf

- Title.
- Fixes #9857.
I haven't tested this, but given the bug report, this is the only place where the bug can occur.

Dragging - Release ownership when target is too heavy to drag/carry

---

addons/csw/stringtable.xml
addons/dogtags/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/repair/stringtable.xml

Translations - Improve Japanese localization 3

---

addons/medical_treatment/functions/fnc_bandage.sqf

- Fix broken bandage effectiveness

Medical Treatment - Fix bandage effectiveness

---

addons/fire/XEH_postInit.sqf
docs/wiki/framework/fire-framework.md

- _Check for the_ `ace_fire_enableScreams` _variable as well as the setting before playing a scream sound._

Fire - Add ability to disable screams for individual units

---

addons/compat_cup_weapons/compat_cup_weapons_csw/CfgVehicles.hpp

- Had the wrong baseclass to begin with.

Compat CUP Weapons - Fix Metis UBC

---

addons/arsenal/functions/fnc_sortPanel.sqf

- Title.
- It was added in #9795, but as that hasn't been released, this won't be included in the changelogs.

Arsenal - Revert unicode support for sorting

---

addons/advanced_ballistics/functions/fnc_readAmmoDataFromConfig.sqf
addons/scopes/functions/fnc_calculateZeroAngleCorrection.sqf

AB/Scopes - Fix script errors on profiling branch

---

addons/dragging/functions/fnc_carryObject.sqf
addons/dragging/functions/fnc_carryObjectPFH.sqf
addons/dragging/functions/fnc_dragObject.sqf
addons/dragging/functions/fnc_dragObjectPFH.sqf
addons/dragging/functions/fnc_dropObject.sqf
addons/dragging/functions/fnc_dropObject_carry.sqf
addons/dragging/functions/fnc_handleScrollWheel.sqf
addons/dragging/functions/fnc_resumeCarry.sqf
addons/dragging/functions/fnc_startCarryLocal.sqf
addons/dragging/functions/fnc_startCarryPFH.sqf
addons/dragging/functions/fnc_startDragLocal.sqf
addons/dragging/functions/fnc_startDragPFH.sqf
addons/dragging/initSettings.inc.sqf

- Title.
- As I was looking through the code, realised that UAV crew handling wasn't optimal. I'll need to address that.

Dragging - Minor code cleanup

---

addons/advanced_throwing/stringtable.xml
addons/common/stringtable.xml

- _Add/Update new missing sway factor stringtable line_
Uh, Should I draft this and wait? 
Or should I create a new PR and deal with the next missing table? 
I don't know the optimal solution. 
However, by merging this PR, the Japanese translation will be 100%.

Translations - Improve Japanese localization part 4 (sway factor)

---

addons/mk6mortar/functions/fnc_handleFired.sqf

- Title. Return values are not necessary.

Mk6mortar - Remove return values from `FUNC(handleFired)`

---

docs/wiki/feature/maptools.md

Adds missing Information to MapTools/PlottingBoard

Documentation - Add Info about Plotting Board

---

addons/repair/XEH_postInit.sqf
addons/ui/XEH_clientInit.sqf

Repair/UI - Minor code cleanup

---

addons/compat_cup_terrains/addon.toml
addons/compat_cup_terrains/config.cpp
addons/compat_cup_vehicles/addon.toml
addons/compat_cup_vehicles/config.cpp
addons/compat_cup_weapons/addon.toml
addons/compat_cup_weapons/config.cpp

CUP Compats - Cleanup temp `__has_include`

---

addons/yardage450/functions/fnc_turnOn.sqf

Yardage - Make macros uppercase

---

addons/csw/functions/fnc_ai_reload.sqf
addons/csw/functions/fnc_assemble_deployTripod.sqf
addons/csw/functions/fnc_assemble_deployWeapon.sqf
addons/csw/functions/fnc_assemble_pickupTripod.sqf
addons/csw/functions/fnc_assemble_pickupWeapon.sqf
addons/csw/functions/fnc_getLoadActions.sqf
addons/csw/functions/fnc_getUnloadActions.sqf
addons/csw/functions/fnc_initVehicle.sqf
addons/csw/functions/fnc_reload_getLoadableMagazines.sqf
addons/csw/functions/fnc_reload_loadMagazine.sqf

- Title.
- Almost certainly more of this type of PR to follow in the future.

CSW - Minor code cleanup

---

addons/compat_cup_weapons/compat_cup_weapons_csw/CfgWeapons.hpp

- With only CBA, ACE and CUP Weapons loaded, the existing CSW config does not work.
I didn't try if it worked if you have CUP Units and/or Vehicles loaded, as I made this fix independently from that.

CSW - Fix CUP CSW

---

addons/advanced_throwing/stringtable.xml
addons/common/stringtable.xml
addons/fieldmanual/stringtable.xml
addons/hearing/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_treatment/stringtable.xml

add translation to advanced_throwing, common, medical_gui, hearing
fix translation in medical_treatment

Language Russian - Update translation

---

addons/cargo/CfgVehicles.hpp
addons/cargo/XEH_postInit.sqf
addons/cargo/functions/fnc_initVehicle.sqf

Cargo - Fix undefined variable and config entries

---

addons/common/CfgMoves.hpp

Common - Fix animations not playing

---

addons/grenades/functions/fnc_flashbangExplosionEH.sqf

Grenades - Fix flashbangs causing pain for invulnerable units

---

addons/grenades/functions/fnc_flashbangExplosionEH.sqf

Grenades - Fix unconscious AI being affected by flashbangs

---

docs/wiki/framework/grenades-framework.md

Grenades - Add missing documentation on flares and incendiaries

---

addons/common/stringtable.xml
addons/hearing/stringtable.xml

- Added 4 new Italian localizations in components `hearing` and `common`;

Translations - Updated Italian with recent additions

---

addons/cargo/CfgVehicles.hpp
docs/wiki/framework/cargo-framework.md

Cargo - Add documentation on adding cargo via config

---

addons/grenades/functions/fnc_flashbangThrownFuze.sqf

Grenades - Add 3 more sounds to flashbang detonations

---

addons/grenades/CfgAmmo.hpp

- Title.
Damage was doubled, as the incendiary grenade is pretty weak at the moment.

Grenades - Change damage from M14 incendiary grenade

---

addons/advanced_throwing/functions/fnc_prepare.sqf

AdvThrowing - Fix showing wind info when no grenades in inventory

---

addons/grenades/XEH_postInit.sqf
addons/grenades/XEH_preInit.sqf
addons/grenades/functions/fnc_nextMode.sqf

for https://github.com/acemod/ACE3/pull/10005
small optimization

Grenades - Rolling only add PFEH when needed

---

addons/hearing/XEH_preInit.sqf

- Title.
- Nothing is broken, but this avoids raising events for no reason.

Hearing - Fix volume being force updated when loadouts are set on AI

---

addons/arsenal/functions/fnc_onSelChangedLeft.sqf

Arsenal - Fix insignia not reapplying after switching vests & backpacks

---

addons/compat_ws/CfgWeapons.hpp
addons/compat_ws/compat_ws_realisticnames/Attachments.hpp
addons/compat_ws/compat_ws_realisticnames/CfgVehicles.hpp
addons/compat_ws/compat_ws_realisticnames/CfgWeapons.hpp
addons/compat_ws/compat_ws_realisticnames/config.cpp
addons/compat_ws/compat_ws_realisticnames/stringtable.xml

- Added attachments
- Added vehicles
Additionally covers things added in patch 1.1.3
- DMS Snake
- FN FAL Para
- RDS High Black/Sand
- GM6 Lynx

Compat WS - Update realistic names

---

addons/csw/stringtable.xml
addons/rearm/XEH_postInit.sqf
addons/rearm/functions/fnc_getMagazineName.sqf

- Title.
- Fixed localised `[CSW]` prefixes not being removed.

Rearm - Optimise getting magazine names

---

addons/cookoff/functions/fnc_cookOffEffect.sqf

- Title.
Increase damage, as current damage felt not severe enough.

Cookoff - Change cook-off fire damage

---

docs/wiki/framework/nametags-framework.md

Nametags - Add documentation

---

addons/compat_rf/$PBOPREFIX$
addons/compat_rf/CfgWeapons.hpp
addons/compat_rf/compat_rf_nouniformrestrictions/CfgVehicles.hpp
addons/compat_rf/compat_rf_nouniformrestrictions/config.cpp
addons/compat_rf/compat_rf_nouniformrestrictions/script_component.hpp
addons/compat_rf/compat_rf_realisticnames/Attachments.hpp
addons/compat_rf/compat_rf_realisticnames/CfgMagazines.hpp
addons/compat_rf/compat_rf_realisticnames/CfgVehicles.hpp
addons/compat_rf/compat_rf_realisticnames/CfgWeapons.hpp
addons/compat_rf/compat_rf_realisticnames/config.cpp
addons/compat_rf/compat_rf_realisticnames/script_component.hpp
addons/compat_rf/compat_rf_realisticnames/stringtable.xml
addons/compat_rf/config.cpp
addons/compat_rf/script_component.hpp

- Adds hearing properties where applicable
- Adds ballistics properties where applicable
- Adds no uniform restriction subcomponent
- Adds realistic names subcomponent

Reaction Forces Compatibility

---

addons/hitreactions/XEH_postInit.sqf
addons/hitreactions/XEH_preInit.sqf
addons/hitreactions/initSettings.inc.sqf

- `ace_firedNonPlayer` runs on all clients, so HitPart eh would trigger `dropWeapon` for every client connected
- also dynamically add ehs

Hit Reactions - Prevent AI's hitpart EH running on all clients

---

addons/compat_rf/compat_rf_realisticnames/Attachments.hpp
addons/compat_rf/compat_rf_realisticnames/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/cookoff/stringtable.xml
addons/grenades/stringtable.xml
addons/hitreactions/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/realisticnames/stringtable.xml
addons/zeus/stringtable.xml

- _Title_
- _Update Japanese_
- _Fix wrong and Improve WS/RF Realname_

Translations and Compat - Improve Japanese and CDLC WS/RF localization

---

addons/cookoff/stringtable.xml
addons/grenades/stringtable.xml
addons/hitreactions/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/realisticnames/stringtable.xml
addons/zeus/stringtable.xml

Translation - Update Russian for new features

---

addons/arsenal/functions/fnc_onArsenalClose.sqf
addons/arsenal/functions/fnc_onArsenalOpen.sqf
addons/arsenal/missions/Arsenal.VR/fnc_createTarget.sqf
addons/common/functions/fnc_errorMessage.sqf
addons/slideshow/functions/fnc_mapImage_init.sqf
addons/vehicle_damage/functions/fnc_handleVehicleDamage.sqf
addons/weather/init3DEN.sqf
addons/zeus/functions/fnc_getModuleDestination.sqf
addons/zeus/functions/fnc_ui_globalSetSkill.sqf
addons/zeus/functions/fnc_ui_groupSide.sqf
addons/zeus/functions/fnc_ui_setEngineer.sqf
addons/zeus/functions/fnc_ui_teleportPlayers.sqf

General - Cleanup event capitalization

---

addons/grenades/functions/fnc_incendiary.sqf

- #9983 handled vehicles only, this one handles objects only.

Grenades - Fix incendiary grenades damaging invulnerable objects

---

addons/cookoff/XEH_postInit.sqf

Cookoff - Fix engine fire not starting

---

addons/compat_rf/compat_rf_realisticnames/CfgVehicles.hpp
addons/compat_rf/compat_rf_realisticnames/stringtable.xml

- _Add HEMMT Fire Truck localization (for Equalization with A3 realistic name)_
- _Change Puma family naming and add missing variation_
- _Change HADES(Hera H6) name to Uppercase_

Compat RF - Improve/Change RF Realistic Name

---

addons/common/functions/fnc_addPlayerEH.sqf
addons/ui/XEH_clientInit.sqf

ref https://github.com/CBATeam/CBA_A3/pull/1670

Common - Update header for addPlayerEH

---

addons/cargo/stringtable.xml
addons/compat_cup_weapons/compat_cup_weapons_csw/stringtable.xml
addons/compat_cup_weapons/compat_cup_weapons_nightvision/stringtable.xml
addons/compat_rf/compat_rf_realisticnames/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/cookoff/stringtable.xml
addons/csw/stringtable.xml
addons/grenades/stringtable.xml
addons/hitreactions/stringtable.xml
addons/killtracker/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/microdagr/stringtable.xml
addons/overpressure/stringtable.xml
addons/realisticnames/stringtable.xml
addons/zeus/stringtable.xml

- Complete Italian translation of new strings;
- Complete German translation of new strings (still missing `addons/fieldmanual`);
- Complete Italian+German translation of new and old Compats;
- Fix some Italian/German typos and oversights;
- Fix English translation `Show MicoDAGR` typo;

Translations - Italian and German

---

addons/killtracker/stringtable.xml
addons/overpressure/stringtable.xml

- _Title_
- _Update killtracker overpressure localization for Japanese_

Translations - Improve Japanese (killtracker/overpressure)

---

addons/interaction/functions/fnc_canPassMagazine.sqf

Interaction - Disable magazine passing to dead and unconscious units

---

docs/wiki/framework/vehicledamage-framework.md

Vehicle damage - Add missing documentation

---

addons/dogtags/stringtable.xml

Dogtags - Make "Dog Tag" consistent

---

addons/nametags/functions/fnc_initIsSpeaking.sqf

Nametags - Only display talking waves when unit is alive and conscious

---

addons/spectator/functions/fnc_cam.sqf

Spectator - Remove spectator lights when exiting spectator

---

docs/wiki/class-names.md

- add entry to list
- Fixes #10124 

Documentation - Add `ACE_suture` entry to list of classnames 

---

addons/interaction/functions/fnc_canPush.sqf

Interaction - Hide push interaction if target is in ViV cargo

---

addons/dragging/functions/fnc_getWeight.sqf

- https://github.com/acemod/ACE3/pull/8457#issuecomment-2230284011

Dragging - Remove weight calculation workaround

---

addons/dogtags/functions/fnc_getDogtagItem.sqf

Dogtags - Add missing `private`

---

addons/laser/functions/fnc_addLaserTarget.sqf
addons/laser/functions/fnc_laserTargetPFH.sqf
addons/laser/functions/fnc_showVehicleHud.sqf
addons/laser/functions/fnc_toggleLST.sqf

- Title.
- Inspired from #7892.

Laser - Remove unnecessary EGVAR

---

addons/explosives/functions/fnc_addDetonateActions.sqf

Explosives - Only add "detonate all" action for dead man switch when necessary

---

addons/csw/functions/fnc_reload_handleAddTurretMag.sqf
addons/csw/functions/fnc_reload_handleReturnAmmo.sqf
addons/csw/functions/fnc_reload_loadMagazine.sqf

- Taken from #9234 to fix #9233.

CSW - Fix belt linking

---

addons/csw/dev/checkStaticWeapons.sqf
addons/csw/functions/fnc_aceRearmGetCarryMagazines.sqf
addons/csw/functions/fnc_ai_handleFired.sqf
addons/csw/functions/fnc_ai_handleGetIn.sqf
addons/csw/functions/fnc_ai_reload.sqf
addons/csw/functions/fnc_assemble_canDeployWeapon.sqf
addons/csw/functions/fnc_assemble_canPickupWeapon.sqf
addons/csw/functions/fnc_assemble_deployTripod.sqf
addons/csw/functions/fnc_assemble_deployWeapon.sqf
addons/csw/functions/fnc_assemble_deployWeaponModifier.sqf
addons/csw/functions/fnc_assemble_pickupTripod.sqf
addons/csw/functions/fnc_assemble_pickupWeapon.sqf
addons/csw/functions/fnc_canDeployTripod.sqf
addons/csw/functions/fnc_canGetIn.sqf
addons/csw/functions/fnc_canPickupTripod.sqf
addons/csw/functions/fnc_getCarryMagazine.sqf
addons/csw/functions/fnc_getLoadActions.sqf
addons/csw/functions/fnc_initVehicle.sqf
addons/csw/functions/fnc_proxyWeapon.sqf
addons/csw/functions/fnc_reload_canLoadMagazine.sqf
addons/csw/functions/fnc_reload_canUnloadMagazine.sqf
addons/csw/functions/fnc_reload_getLoadableMagazines.sqf
addons/csw/functions/fnc_reload_getVehicleMagazine.sqf
addons/csw/functions/fnc_reload_handleAddTurretMag.sqf
addons/csw/functions/fnc_reload_handleRemoveTurretMag.sqf
addons/csw/functions/fnc_reload_handleReturnAmmo.sqf
addons/csw/functions/fnc_reload_loadMagazine.sqf
addons/csw/functions/fnc_staticWeaponInit_unloadExtraMags.sqf

- Header changes from #9234. It's easier for me to review them in this form, so I can tell what's actually changed.
- Includes a handful of other trivial code changes.

CSW - Improve function headers & comments

---

addons/compat_cup_weapons/compat_cup_weapons_csw/CfgVehicles.hpp

Fix overlapping CSW interaction position for SPG-9, improve positions for Mk19 and DSHKM

---

addons/vehicle_damage/functions/fnc_addEventHandler.sqf
addons/vehicle_damage/functions/fnc_processHit.sqf

Vehicle damage - Fix ERA/SLAT not being detected

---

addons/quickmount/XEH_postInitClient.sqf

fix 
```
Error Params: Type Display (dialog), expected Object
File z\ace\addons\quickmount\functions\fnc_getInNearest.sqf, line 27
```

QuickMount - Fix keybind

---

addons/medical_treatment/initSettings.inc.sqf

Medical Treatment - Notify restart requirement

---

optionals/nouniformrestrictions/functions/fnc_exportConfig.sqf

No Uniform Restrictions - Update `FUNC(exportConfig)`

---

addons/compat_cup_weapons/compat_cup_weapons_explosives/CfgAmmo.hpp
addons/compat_cup_weapons/compat_cup_weapons_explosives/CfgMagazines.hpp
addons/compat_rhs_gref3/compat_rhs_gref3_explosives/CfgAmmo.hpp
addons/compat_rhs_gref3/compat_rhs_gref3_explosives/CfgMagazines.hpp
addons/compat_sog/ACE_CSW_Groups.hpp

Compats - Use `EGVAR` where possible

---

addons/realisticnames/CfgVehicles.hpp
addons/realisticnames/CfgVehiclesAttachments.hpp
addons/realisticnames/CfgWeapons.hpp
addons/realisticnames/CfgWeaponsAttachments.hpp

- Added realistic names to CfgVehicles item containers (all contact weapons, all weapon attachments, all P90s and some APEX weapons).
- Restructured `CfgVehicles.hpp` to fit `CfgWeapons`.

Realistic Names - Complete & cleanup

---

addons/compat_csla/compat_csla_explosives/CfgMagazines.hpp
addons/compat_gm/compat_gm_explosives/CfgMagazines.hpp
addons/compat_rhs_afrf3/compat_rhs_afrf3_explosives/CfgMagazines.hpp
addons/compat_rhs_saf3/compat_rhs_saf3_explosives/CfgMagazines.hpp
addons/compat_sog/CfgMagazines/explosives.hpp
addons/compat_spe/compat_spe_explosives/CfgMagazines.hpp
addons/explosives/ACE_Arsenal_Stats.hpp
addons/explosives/ACE_Triggers.hpp
addons/explosives/CfgAmmo.hpp
addons/explosives/CfgEventHandlers.hpp
addons/explosives/CfgMagazines.hpp
addons/explosives/CfgVehicles.hpp
addons/explosives/CfgWeapons.hpp
addons/explosives/config.cpp
addons/explosives/dev/test_magazines.sqf
addons/explosives/initSettings.inc.sqf

- Title.
- More cleanup to follow, but I have decided to split it into more manageable PRs.

Explosives - Trivial cleanup

---

addons/hearing/XEH_postInit.sqf

Fix shots by AI not causing explode event

Hearing - Fix explosions from AI fire

---

docs/wiki/framework/attach-framework.md
docs/wiki/framework/events-framework.md

maybe fix #10210
copied from `events-framework.md` as that seems to be valid

Doc - Try to fix framework-attach event list

---

addons/fortify/config.cpp
addons/quickmount/config.cpp
addons/realisticweights/config.cpp
addons/realisticweights/script_component.hpp

General - Add missing pretty names to components

---

docs/wiki/development/arma-3-issues.md

Docs - Update Arma 3 Issues

---

addons/realisticnames/CfgVehicles.hpp

Realistic Names - Fix bad inheritance from #10202

---

addons/dogtags/stringtable.xml
addons/medical_treatment/stringtable.xml

- Add and improve Portuguese entries on string tables

Translation - Improve Portuguese

---

addons/interaction/CfgVehicles.hpp

Interaction - Improve interaction anims locations for bags

---

addons/repair/CfgVehicles.hpp

Repair - Improve some locations for interaction anims

---

addons/compat_spe/CfgVehicles/wheeled.hpp
addons/interaction/CfgVehicles.hpp

- If only a single type of backpack is spawned, its localised name is used as the interaction name.
- If multiple backpack types are spawned, it will used a localised form of `Backpacks`.

General - Improve backpack interaction anim names

---

addons/compat_ws/compat_ws_realisticnames/CfgVehicles.hpp
addons/compat_ws/compat_ws_realisticnames/CfgVehiclesAttachments.hpp
addons/compat_ws/compat_ws_realisticnames/CfgWeapons.hpp
addons/compat_ws/compat_ws_realisticnames/CfgWeaponsAttachments.hpp
addons/compat_ws/compat_ws_realisticnames/config.cpp

WS Compat - Rename WS weapon holders when realistic names is loaded

---

addons/compat_rhs_afrf3/CfgVehicles.hpp
addons/compat_rhs_usf3/compat_rhs_usf3_refuel/CfgVehicles.hpp
addons/compat_rhs_usf3/compat_rhs_usf3_trenches/CfgVehicles.hpp

- Title.
- Fix bad inheritance for the Stryker in the refuel compat.
That's it from me for now concerning interaction anims, although I'll add a PR with documentation for the interaction anims.

RHS Compat - Add interaction anims for ammo boxes

---

addons/compat_spe/compat_spe_explosives/CfgVehicles.hpp

- Use string table entries from SPE.

SPE Compat - Improve SPE CfgVehicles explosives naming

---

addons/safemode/XEH_postInit.sqf

Safemode - Fix safemode being broken after respawning

---

addons/mk6mortar/initSettings.inc.sqf

Mk6 Mortar - Remove unnecessary restart notifications

---

addons/overpressure/functions/fnc_firedEHBB.sqf
addons/overpressure/functions/fnc_firedEHOP.sqf

- Removed non-existent variables, used `vectorMultiply` instead of `vectorDiff` (new is slightly faster).

Overpressure - Minor cleanup

---

addons/aircraft/stringtable.xml
addons/interaction/stringtable.xml
addons/maverick/stringtable.xml
addons/missileguidance/stringtable.xml
addons/ui/stringtable.xml
addons/vehicle_damage/stringtable.xml

Translate - Improve Russian [31.08]

---

addons/towing/config.cpp

Towing - Fix dependencies

---

addons/common/stringtable.xml
addons/dragging/functions/fnc_carryObjectPFH.sqf
addons/dragging/functions/fnc_dragObject.sqf
addons/dragging/functions/fnc_resumeDrag.sqf
addons/dragging/functions/fnc_setCarryable.sqf
addons/dragging/functions/fnc_setDraggable.sqf
addons/rearm/functions/fnc_grabAmmo.sqf
addons/rearm/functions/fnc_takeSuccess.sqf
addons/refuel/functions/fnc_startNozzleInHandsPFH.sqf
addons/towing/functions/fnc_attachRopePFH.sqf

General - Removed silent Dragging dependencies

---

addons/advanced_fatigue/CfgEden.hpp
addons/advanced_fatigue/initSettings.inc.sqf
addons/advanced_fatigue/script_component.hpp

- Title.
- Use `QUOTE` macro for code.
It's something that I forgot to add in #9714, hence the ignore changelog tag. However, we can add to the changelog if people desire it.

Advanced Fatigue - Increase per unit performance factor editor slider

---

addons/compat_spe/compat_spe_csw/stringtable.xml
addons/frag/stringtable.xml
addons/interaction/stringtable.xml
addons/maverick/stringtable.xml
addons/missileguidance/stringtable.xml
addons/scopes/stringtable.xml
optionals/tracers/stringtable.xml

- _Fill missing translations_
- _Rewrite old tracer Japanese translation before 2020_

Translations - Improve Japanese 3.18

---

addons/interaction/functions/fnc_initAnimActions.sqf

- Causes a bug with the offroad and the backpack removal, so reverting #10249.

Interaction - Revert #10249

---

addons/frag/stringtable.xml
addons/scopes/stringtable.xml

Translations - Improve Russian 3.18

---

addons/inventory/functions/fnc_forceItemListUpdate.sqf

- Title.
- Nothing bad happened, it just did an extra iteration.

Inventory - Fix wrong iteration count

---

addons/repair/functions/fnc_patchRemovedWheel.sqf

Repair - Use `EFUNC` macro

---

addons/cookoff/functions/fnc_cookOffLocal.sqf

- Title. Bug has existed since the beginning.
- Minor code optimisations & cleanup.

Cookoff - Fix wrong origin for 1 fire jet in fire ring

---

addons/frag/stringtable.xml
addons/interaction/stringtable.xml
addons/maverick/stringtable.xml
addons/missile_gbu/stringtable.xml
addons/missile_vikhr/stringtable.xml
addons/missileguidance/stringtable.xml
addons/ui/stringtable.xml

Translations - Italian

---

addons/missile_gbu/stringtable.xml
addons/missile_vikhr/stringtable.xml

- _Title. currently only adds missile names patches._

Translations - Improve Japanese 3.18 (part 2)

---

addons/cargo/stringtable.xml
addons/missile_gbu/stringtable.xml
addons/missile_vikhr/stringtable.xml

- Added rest of missing strings

Translations - Korean

---

addons/minedetector/XEH_preInit.sqf
addons/minedetector/functions/fnc_getDetectedObject.sqf

request from Ztrack on discord

Mine Detector - Change detectable hash so it can be editable by mission scripts

---

addons/medical_engine/functions/fnc_handleDamage.sqf

Medical - Fix zeus end keybind not killing units

---

addons/cargo/stringtable.xml
addons/zeus/stringtable.xml

Translations - Improve Japanese (After 3.18)

---

.github/workflows/pboproject.yml

- Fix some of the pboproject issues, there's some other issue with binarize and `CfgConvertFileChange`
- `O:\Arma3CommunityTools\CfgConvertFileChng\CfgConvertFileChange.exe returned error 22: Invalid argument`

CI - Update to latest Mikero Tools

---

addons/markers/functions/fnc_removeTimestamp.sqf

- Title
- Probably could do it better with regex, but I'm not willing to go down that road.

Markers - Optimise map marker timestamp filtering

---

addons/goggles/initSettings.inc.sqf

- This setting doesn't set anything up if the setting is turned off at the start.

Goggles - Notify restart req. for effects setting

---

addons/common/XEH_postInit.sqf
addons/common/functions/fnc_adjustMagazineAmmo.sqf
addons/csw/functions/fnc_reload_loadMagazine.sqf
addons/grenades/functions/fnc_incendiary.sqf
addons/interact_menu/functions/fnc_splitPath.sqf

General - Update miscellaneous to use 2.18 commands

---

addons/common/functions/fnc_addToInventory.sqf

- https://feedback.bistudio.com/T74244 has been addressed.

Common - Revert #9980 (`addToInventory`/throwables)

---

addons/medical_ai/functions/fnc_healingLogic.sqf
addons/medical_treatment/functions/fnc_ivBag.sqf
addons/medical_treatment/functions/fnc_ivBagLocal.sqf

- adds a small line to ivBagLocal to give the fluid bag back to the medic rather then poofing
-

Medical Treatment - Return IV bags when applicable

---

addons/hearing/XEH_preInit.sqf
addons/hearing/functions/fnc_handleRespawn.sqf
addons/hearing/functions/fnc_hasEarPlugsIn.sqf

- Fix a typo in `ACE_hasEarPlugsIn` (was lowercase `i`)
- (Partially) fix Baer's sanity

Hearing - Fix typo

---

addons/advanced_fatigue/functions/fnc_getMetabolicCosts.sqf
addons/advanced_fatigue/functions/fnc_mainLoop.sqf

- Moved duty calculation where it's used.

Advanced Fatigue - Minor cleanup

---

addons/frag/XEH_postInit.sqf

Frag - Fix rapid explosion holdoff

---

addons/field_rations/functions/fnc_handleEffects.sqf

Field Rations - Add small grace period between consciousness losses

---

addons/cargo/stringtable.xml
addons/frag/stringtable.xml
addons/missile_gbu/stringtable.xml
addons/missile_vikhr/stringtable.xml
addons/scopes/stringtable.xml

Translate French

---

addons/microdagr/functions/fnc_updateDisplay.sqf

- Fix Microdagr cursor disappearing when deleting last waypoint

Microdagr - Fix microdagr cursor disappearing when deleting last waypoint

---

addons/weaponselect/functions/fnc_selectNextGrenade.sqf

- Would fail to cycle through all grenades because of duplicates.

Weapon Select - Fix selecting next grenade

---

addons/cargo/stringtable.xml
addons/hearing/stringtable.xml
addons/hitreactions/stringtable.xml
addons/medical_treatment/stringtable.xml

Update:
- medical_treatment
- hearing
- hitreactions

Translations - Improve Russian

---

.hemtt/launch.toml

Tools - HEMTT launch profile for RF

---

addons/cookoff/XEH_postInit.sqf

- Title.
- See https://github.com/acemod/ACE3/pull/9962#discussion_r1843111419.

Cookoff - Remove animals from EH

---

addons/field_rations/stringtable.xml
addons/markers/stringtable.xml

- _add missing localization_
- https://github.com/DartRuffian/ACE3/pull/2
- and changes for https://github.com/acemod/ACE3/pull/10485/files

Translations - Improve Japanese (ZEUS Field Ration and Timestamp)

---

addons/compat_rhs_afrf3/CfgAmmo.hpp
addons/compat_rhs_usf3/CfgAmmo.hpp
addons/compat_spe/CfgAmmo/bombs.hpp
addons/compat_spe/CfgAmmo/explosives.hpp
addons/compat_spe/CfgAmmo/grenades.hpp
addons/frag/CfgAmmoFragParameters.hpp
addons/hot/CfgAmmo.hpp

config is accessed by `getNumber`
do this _complex_ math at build-time instead of run-time

Frag - de-quote number

---

addons/dragging/CfgVehicles.hpp

- Title, scope = 1 was overlooked & appears in editor etc

Dragging - Fix clone showing

---

docs/wiki/framework/frag-framework.md

- Clarify that the gurney shape factor is related to velocity

Frag - Improve document clarity on "Gurney shape factor"

---

addons/common/stringtable.xml
addons/field_rations/stringtable.xml
addons/hearing/stringtable.xml
addons/interaction/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/missile_aim120/stringtable.xml
addons/missile_sam/stringtable.xml

French Translate

---

addons/compat_rf/compat_rf_realisticnames/CfgVehicles.hpp
addons/compat_rf/compat_rf_realisticnames/CfgWeapons.hpp
addons/compat_rf/compat_rf_realisticnames/stringtable.xml

- Fixes broken inheritance changed by the patch.
- Adds realistic names to things that were added.

Compat RF - Fix/Update realistic names

---

addons/compat_rf/compat_rf_realisticnames/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/realisticnames/stringtable.xml

- _Change WS Kamaz Flatbed wording_
- _Add missing medical localization and improve for mixing with new word_

Translations - Improve Japanese (Medical, WS Kamaz Flatbed)

---

addons/compat_rf/CfgVehicles.hpp

RF Compat - Remove fuel sources from fire trucks

---

addons/csw/functions/fnc_initVehicle.sqf

CSW - Use LINKFUNC in initVehicle waitUntilAndExecute

---

addons/arsenal/stringtable.xml

- _Add missing localization for Japanese_
- _Change the conjunction a bit_

Translations - Improve Japanese (Arsenal)

---

addons/main/script_debug.hpp

ref https://github.com/acemod/ACE3/pull/10614
takes 3 args

Main - Update ENABLE_PERFORMANCE_COUNTERS macro: the sequel

---

addons/arsenal/stringtable.xml
addons/common/stringtable.xml
addons/explosives/stringtable.xml
addons/markinglaser/stringtable.xml
addons/medical_gui/stringtable.xml
addons/missile_clgp/stringtable.xml
addons/realisticnames/stringtable.xml

- _Add missing localization for Simplified Chinese in 3.19.0 RC1_

Translations - Improve Simplified Chinese in 3.19.0 RC1

---

addons/arsenal/stringtable.xml
addons/common/stringtable.xml
addons/explosives/stringtable.xml
addons/markinglaser/stringtable.xml
addons/medical_gui/stringtable.xml
addons/missile_clgp/stringtable.xml
addons/realisticnames/stringtable.xml

Update:
- common
- arsenal
- medical_gui
- realisticnames
- explosives
- missile_clgp
- markinglaser

Translations - Improve Russian (3.19.0)

---

addons/compat_gm/compat_gm_hearing/CfgWeapons.hpp

fix 
```
Updating base class gm_xx_headgear_headwrap_crew_01_base->gm_xx_headgear_headwrap_01_base, by z\ace\addons\compat_gm\compat_gm_hearing\config.cpp/CfgWeapons/gm_xx_headgear_headwrap_crew_01_oli/ (original gm\gm_characters\gm_xx_characters\config.bin)
Updating base class gm_xx_headgear_headwrap_crew_01_base->gm_xx_headgear_headwrap_01_base, by z\ace\addons\compat_gm\compat_gm_hearing\config.cpp/CfgWeapons/gm_xx_headgear_headwrap_crew_01_m84/ (original gm\gm_characters\gm_xx_characters\config.bin)
Updating base class gm_xx_headgear_headwrap_crew_01_base->gm_xx_headgear_headwrap_01_base, by z\ace\addons\compat_gm\compat_gm_hearing\config.cpp/CfgWeapons/gm_xx_headgear_headwrap_crew_01_grn/ (original gm\gm_characters\gm_xx_characters\config.bin)
Updating base class …
```

Compat GM - Fix headgear/hearing UBC

---

addons/irlight/stringtable.xml

IR Light - DBAL Casing

---

addons/field_rations/functions/fnc_scanFieldRations.sqf

Field Rations - Log ration magazines without item property to RPT

---

addons/hearing/functions/fnc_earRinging.sqf
addons/hearing/functions/fnc_removeEHP.sqf
addons/hearing/initSettings.inc.sqf
addons/hearing/script_component.hpp
addons/hearing/stringtable.xml

- Reduce EHP ducking, lengthen fade
- Add setting to disable ducking

Hearing - Tweak EHP effects, add 🦆ing setting

---

addons/flags/stringtable.xml
addons/hearing/stringtable.xml

- _add JP that missed in 3.19.0 update

Translations - Japanese

---

addons/logistics_uavbattery/stringtable.xml

Translations - Japanese (UAV Battery)

---

addons/compat_csla/CfgWeapons.hpp

- Change inheritance for the M60 to match CSLA 1.2 release, fixing related errors

CSLA Compat - Update for CSLA 1.2

---

addons/compat_ws/CfgWeapons.hpp

Compat WS - EHP

---

addons/nightvision/XEH_postInit.sqf

Nighvision - Fix overlay not applying to newly switched unit

---

docs/wiki/framework/flags-framework.md

- Add documentation for adding custom placeable and carryable flags

Docs - Add documentation for adding custom placeable and carryable flags

---

addons/common/functions/fnc_checkFiles.sqf

Common - Improve addon mismatch fix message for server admins

---

addons/medical_damage/functions/fnc_getTypeOfDamage.sqf

Medical - Fix out of scope var

---

addons/csw/ACE_Arsenal_Stats.hpp
addons/csw/XEH_PREP.hpp
addons/csw/config.cpp
addons/csw/functions/fnc_statTextCondition_tripods.sqf
addons/csw/functions/fnc_statTextStatement_tripods.sqf
addons/csw/stringtable.xml

- Displays which tripods are needed for CSW gun.

CSW - Add tripods stat

---

addons/advanced_fatigue/functions/fnc_renderDebugLines.sqf
addons/ai/functions/fnc_drawCuratorGarrisonPathing.sqf
addons/common/functions/fnc_checkPBOs.sqf
addons/common/functions/fnc_getMGRSdata.sqf
addons/common/functions/fnc_getTargetAzimuthAndInclination.sqf
addons/common/functions/fnc_getTargetObject.sqf
addons/common/functions/fnc_showHud.sqf
addons/huntir/functions/fnc_cam.sqf
addons/map/functions/fnc_initMainMap.sqf
addons/medical/functions/fnc_deserializeState.sqf
addons/missileguidance/functions/fnc_dev_ProjectileCamera.sqf
addons/movement/functions/fnc_canClimb.sqf
addons/spectator/functions/fnc_cam.sqf
addons/spectator/functions/fnc_ui_draw3D.sqf
addons/spectator/functions/fnc_ui_handleKeyDown.sqf
addons/vector/functions/fnc_getDirection.sqf
addons/zeus/functions/fnc_bi_moduleRemoteControl.sqf

Most are pretty trivial and only really effect when on the water
e.g. `call ace_vector_fnc_getDirection` was off by ~10 deg elevation if you are on dock

Various - Fix position types

---

addons/interact_menu/functions/fnc_createAction.sqf
docs/wiki/framework/arsenal-framework.md
docs/wiki/framework/dragging-framework.md
docs/wiki/framework/events-framework.md
docs/wiki/framework/explosives-framework.md
docs/wiki/framework/fastroping-framework.md
docs/wiki/framework/fire-framework.md
docs/wiki/framework/interactionMenu-framework.md
docs/wiki/framework/laser-framework.md
docs/wiki/framework/medical-framework.md
docs/wiki/framework/rearm-framework.md
docs/wiki/framework/refuel-framework.md
docs/wiki/framework/slideshow-framework.md
docs/wiki/framework/tagging-framework.md
docs/wiki/framework/ui-framework.md
docs/wiki/framework/vehiclelock-framework.md
docs/wiki/framework/vehicles-framework.md

- Clean up some functions and examples.
- Remove `SCALAR` wherever possible.
- `Type` -> `Type(s)` in functions.

Docs - Minor cleanup

---

addons/missileguidance/XEH_preInit.sqf
addons/missileguidance/dev/mock_weapons.hpp
addons/missileguidance/functions/fnc_MCLOS_buttonPressed.sqf

Missile Guidance - remove needed config entry on mclos weapons

---

addons/medical_damage/functions/fnc_parseConfigForInjuries.sqf
addons/medical_damage/functions/fnc_woundReceived.sqf

Fix https://github.com/acemod/ACE3/issues/10752

Medical Damage - Fix script error on drowning damage

---

addons/missile_aim120/CfgAmmo.hpp

- Visual feedback for loft mode

missile_aim120 - Visual feedback for loft mode

---

addons/medical_vitals/functions/fnc_consumeIVs.sqf

- Add item to local event parameters
Need this for ID-based blood bags

Medical Vitals - Improve IV consumption API

---

addons/intelitems/README.md
docs/wiki/development/coding-guidelines.md
docs/wiki/feature/flags.md
docs/wiki/feature/intelitems.md
docs/wiki/feature/marker-flags.md
docs/wiki/framework/explosives-framework.md

Docs - Add missing features

---

addons/magazinerepack/functions/fnc_startRepackingMagazine.sqf

Magazine Repack - Minor optimisation

---

addons/arsenal/stringtable.xml
addons/common/stringtable.xml
addons/compat_rf/compat_rf_realisticnames/stringtable.xml
addons/compat_spe/compat_spe_csw/stringtable.xml
addons/compat_ws/compat_ws_realisticnames/stringtable.xml
addons/csw/stringtable.xml
addons/explosives/stringtable.xml
addons/killtracker/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/missile_clgp/stringtable.xml
addons/missile_sdb/stringtable.xml
addons/missileguidance/stringtable.xml
addons/realisticnames/stringtable.xml

Translations - German

---

addons/hearing/initSettings.inc.sqf

- title
- accessibility change
https://github.com/acemod/ACE3/issues/3594#issuecomment-2633670654

Hearing - Make ear ringing unable to be overwritten

---

addons/csw/stringtable.xml
addons/explosives/stringtable.xml
addons/flags/stringtable.xml
addons/hearing/stringtable.xml
addons/killtracker/stringtable.xml
addons/laser/stringtable.xml
addons/missileguidance/stringtable.xml
addons/nametags/stringtable.xml

- Increase optimization and perfection

Translations - Improve Japanese (3.19.1 RC2)

---

addons/cargo/functions/fnc_getCargoSpaceLeft.sqf

- Addresses https://github.com/acemod/ACE3/issues/3594#issuecomment-2674433960.

Cargo - Make `FUNC(getCargoSpaceLeft)` public

---

addons/medical_vitals/functions/fnc_consumeMedications.sqf

probably skip the `medical,consumeMedications)` event?

Medical Vitals - Fix heart rate not updating

---

addons/common/functions/fnc_checkPBOs.sqf
addons/common/functions/fnc_checkVersionNumber.sqf
addons/common/stringtable.xml

- _Update `Stringtable.xml` for localized texts_
- _Add localized texts in `functions/fnc_checkPBOs.sqf`_
- _Add localized texts in `functions/fnc_checkVersionNumber.sqf`_

Common - Add localized texts in check PBOs

---

AUTHORS.txt
addons/optionsmenu/functions/contributorNames.inc.sqf

- Update the contributors list / AUTHORS.txt
- KJW said "Thank god I'm not on that list" so I added him, and did me too cause why not

Options Menu - Update contributors

---

addons/medical_treatment/initSettings.inc.sqf

Fix #10838

---

addons/common/stringtable.xml
addons/medical_treatment/stringtable.xml

Translations - Improve Japanese (3.19.3)

---

AUTHORS.txt
addons/optionsmenu/functions/contributorNames.inc.sqf
addons/safemode/stringtable.xml

- _Additional languages for ‘Toggle’._
- _Add me to authors!_

Translation - Fix Safe mode Toggle localization.

---

addons/fire/initSettings.inc.sqf

- Title
- Accessibility. Screams are sufficiently triggering for people with Issues

Fire - Make scream sounds setting unable to be overwritten

---

addons/apl/script_component.hpp

- Lowercase `APL` in addon name

APL - Lowercase component name

---

addons/common/stringtable.xml

Translation - Add missing `common` translations

---

addons/medical_statemachine/stringtable.xml
addons/repair/stringtable.xml
addons/respawn/stringtable.xml

- _Fix Turkish line break on medical statemachine_
- _Improve Japanese localizations_

Translations - Improve Japanese / Fix Turkish Line Break

---

addons/laser/stringtable.xml

- `Laser Spot Tracker: On` is unclear and can be confused with current state rather than state that will happen when you interact

Laser - Improve LST interaction text

---

addons/trenches/ACE_Arsenal_Stats.hpp
addons/trenches/functions/fnc_hasEntrenchingTool.sqf

Trenches - Support vests with `entrenchingTool` config

---

addons/compat_cup_weapons/CfgVehicles.hpp
addons/compat_cup_weapons/config.cpp

ref https://github.com/acemod/ACE3/pull/10810

Compat CUP - Add artillerytables ranging to D-30 AT

---

addons/weather/functions/fnc_calculateWindChill.sqf

- update fnc_calculateWindChill.sqf to be more readable
Can't test locally.

weather - Improve fnc_calculateWindChill.sqf to be more readable

---

addons/explosives/functions/fnc_addCellphoneIED.sqf
addons/explosives/functions/fnc_addClacker.sqf

Apply changes suggested by hemtt, improving readability.

Explosives - Improve readability of old code

---

addons/compat_cup_weapons/compat_cup_missileguidance/CfgAmmo.hpp
docs/tools/document_functions.py
tools/check_strings.py

>document_functions.py:78: DeprecationWarning: 'maxsplit' is passed as positional argument
check_strings.py:14: SyntaxWarning: invalid escape sequence '\='

Tools - update for changes to python

---

addons/arsenal/stringtable.xml
addons/common/stringtable.xml
addons/compat_spe/compat_spe_csw/stringtable.xml
addons/csw/stringtable.xml
addons/explosives/stringtable.xml
addons/killtracker/stringtable.xml
addons/medical_gui/stringtable.xml
addons/medical_treatment/stringtable.xml
addons/missile_clgp/stringtable.xml
addons/missile_sdb/stringtable.xml
addons/missileguidance/stringtable.xml
addons/realisticnames/stringtable.xml
addons/smallarms/stringtable.xml
optionals/tracers/stringtable.xml

- Can wait for #10859 and #10897, but not necessary.

Stringtables - Sort

---

addons/weather/functions/fnc_getMapData.sqf

- Check if description.ext contains a CfgWorlds entry with ACE Weather data, if so use it.
documention to be done in another PR
`ACE_TempDay`, `ACE_TempNight`, `ACE_Humidity`, `ACE_WindSpeedMax`, `ACE_WindSpeedMean`, `ACE_WindSpeedMin`, `ACE_WindDirectionProbabilities`

Weather - Allow CfgWorlds weather data to be read from description.ext

---

docs/wiki/framework/weather-framework.md

- Title.
- Covers #10875 as well.

Wiki - Add `weather` config documentation

---

addons/repair/stringtable.xml

- _Update Japanese_
- _Add missing/improve lines for repair_
todo: add missing lines for document header text (intel items)

Translations - Improve Japanese (3.20.0)

---

addons/refuel/functions/fnc_refuel.sqf

Refuel - Fix nozzle not resetting refuel amount between vehicles

---

addons/compat_cup_units/CfgVehicles.hpp
addons/compat_cup_units/CfgWeapons.hpp
addons/compat_cup_units/Cfgvehicles.hpp
addons/compat_cup_units/config.cpp

- Add Entrenchingtool Function to two Backpacks
- Add Entrenchingtool Function to two Vests

Compat CUP Units - Add `trenches` compatibility

---

addons/medical/functions/fnc_getBandagedWounds.sqf

Medical - Fix open wounds being returned instead of bandaged ones

---

addons/missile_gbu/CfgAmmo.hpp

missile_gbu - Improve aerodynamics

---

addons/nightvision/functions/fnc_onCameraViewChanged.sqf
addons/nightvision/functions/fnc_onVisionModeChanged.sqf
addons/nightvision/functions/fnc_pfeh.sqf
addons/nightvision/functions/fnc_setupDisplayEffects.sqf

- Make nightvision border & other fx handled properly
- Fix for https://github.com/acemod/ACE3/issues/10878

Nightvision - Improve handling with thermal vision

---

addons/compat_gm/compat_gm_csw/ACE_CSW_Groups.hpp
addons/compat_gm/compat_gm_csw/CfgMagazineWells.hpp
addons/compat_gm/compat_gm_csw/CfgMagazines.hpp
addons/compat_gm/compat_gm_csw/CfgVehicles.hpp
addons/compat_gm/compat_gm_csw/CfgWeapons.hpp
addons/compat_gm/compat_gm_csw/config.cpp
addons/compat_gm/compat_gm_csw/script_component.hpp
addons/compat_gm/compat_gm_csw/stringtable.xml

- Add a CSW carryable:
- MILAN 
- 9K111 Fagot 
- MG3
- Add CSW weapon interactions for
- 2B11 120mm Mortar
- M120 120mm Mortar

GM Compat - Add CSW Compatability

---

addons/casings/functions/fnc_createCasing.sqf

ref https://discord.com/channels/976165959041679380/976224344881655818/1378208879669936309
"FiredMan" fires on the player-unit when controlling UAVs

Casings - Fix creating casings for UAV weapons

---

addons/missile_sdb/CfgAmmo.hpp

missile_sdb - Increase lifetime

---

addons/cookoff/stringtable.xml
addons/intelitems/stringtable.xml

Translations - Improve Japanese (3.20.0 part 2)

---

addons/compat_spe/CfgWeapons/weapons.hpp

COMPAT SPE - Fix scoped rifles being open bolt

---

addons/ballistics/ACE_Arsenal_Stats.hpp
addons/csw/ACE_Arsenal_Stats.hpp
addons/explosives/ACE_Arsenal_Stats.hpp
addons/flashlights/ACE_Arsenal_Stats.hpp
addons/gforces/ACE_Arsenal_Stats.hpp
addons/hearing/ACE_Arsenal_Stats.hpp
addons/logistics_wirecutter/ACE_Arsenal_Stats.hpp
addons/nightvision/ACE_Arsenal_Stats.hpp
addons/overheating/ACE_Arsenal_Stats.hpp
addons/overpressure/ACE_Arsenal_Stats.hpp
addons/reload/ACE_Arsenal_Stats.hpp
addons/reloadlaunchers/ACE_Arsenal_Stats.hpp
addons/scopes/ACE_Arsenal_Stats.hpp
addons/trenches/ACE_Arsenal_Stats.hpp

General - Fix load order issues for arsenal `statBase`

---

addons/main/script_mod.hpp
addons/medical_damage/stringtable.xml

soft req from https://github.com/acemod/ACE3/pull/10947

bump req to 220, sort st

---

addons/cookoff/stringtable.xml

- Title.
@Apricot-ale Can you check if the Japanese translation is still correct?

Cookoff - Fix setting name

---

addons/compat_gm/compat_gm_csw/stringtable.xml
addons/cookoff/stringtable.xml
addons/intelitems/stringtable.xml
addons/medical_damage/stringtable.xml
addons/missileguidance/stringtable.xml
addons/repair/stringtable.xml
addons/spike/stringtable.xml
addons/ui/stringtable.xml

- _JP Localization Update for RC 3.20.0_

Translations - Improve Japanese (3.20.0 RC1)

---

addons/spike/CfgWeapons.hpp
addons/spike/XEH_postInit.sqf
addons/spike/functions/fnc_keyDown.sqf
addons/spike/stringtable.xml

Cherry pick from #11002 by @mrschick
- makes base class scope 1
- Adds olive camo
- Uses config enabled

Spike - Add Olive Launcher Variant

---

addons/overheating/CfgVehicles.hpp
addons/overheating/functions/fnc_getConsumableChildren.sqf

Overheating - Fix wrong unit's weapon being cooled

---

addons/cargo/XEH_postInit.sqf
addons/cargo/functions/fnc_handleDestroyed.sqf
addons/cargo/functions/fnc_unloadItem.sqf
addons/cargo/initSettings.inc.sqf
addons/cargo/script_component.hpp
addons/cargo/stringtable.xml

- Add a setting to allow a chance that cargo loaded into a vehicle is unloaded when the vehicle is killed.
- Moved over from #10017

Cargo - Add unloading of cargo to killed vehicles

---

addons/interaction/functions/fnc_tapShoulder.sqf

- Add _unit to the tap shoulder event

Interaction - Add _unit to tap shoulder event

---

addons/headless/functions/fnc_transferGroups.sqf

- fixes a small typo in the headless client transfer thingy

Headless Client - Fix typo in transfer for HC3

---

addons/advanced_throwing/functions/fnc_prime.sqf

AdvThrowing - Fix throwing not removing grenade on desynced inventory

---

docs/wiki/framework/repair-framework.md

- via https://discord.com/channels/976165959041679380/976224344881655818/1424156873422274601

Repair - Fix Error in docs
