acemod/ACE3

- addons/medical_statemachine/stringtable.xml
- Add french translation in `medical_statemachine` module.
> Translations - Update French Translations (Medical Statemachine)

- addons/medical_statemachine/Statemachine.hpp
Fix
```
Error Params: Type Bool, expected String,code
File x\cba\addons\statemachine\fnc_addEventTransition.sqf, line 38
```
tested with filepatching and with pboProject
> Medical Statemachine - Ensure bleedout condition string is code

- addons/captives/functions/fnc_addLoadCaptiveActions.sqf
- addons/captives/functions/fnc_canLoadCaptive.sqf
- addons/captives/functions/fnc_doLoadCaptive.sqf
- addons/common/functions/fnc_loadPersonLocal.sqf
- addons/common/functions/fnc_nearestVehiclesFreeSeat.sqf
- addons/common/functions/fnc_unloadPersonLocal.sqf
for pr #7980
captive used same logic but different loading logic that is hardcoded to reject non-cargo slots, so added optional param
> Fix cargo logic, adjust function for captives

- addons/captives/functions/fnc_addLoadCaptiveActions.sqf
- addons/captives/functions/fnc_canLoadCaptive.sqf
- addons/captives/functions/fnc_doLoadCaptive.sqf
- addons/common/functions/fnc_loadPersonLocal.sqf
- addons/common/functions/fnc_nearestVehiclesFreeSeat.sqf
- addons/common/functions/fnc_unloadPersonLocal.sqf
- Fix #2965 (from 2015 😄)
- Fix #4937
- Additionally, add a failsave when the eject action fails
I tested this with the AH-6 and eject only did not work before. This might fix this problem on other vehicles, too, not sure what causes it.
> Common / Medical - Fix loading patients into turret only seats

- addons/medical_engine/CfgActions.hpp
**Remove the vanilla actions to unload unconcious**
- People seem to accidentally hit this when trying to mount up (I know they should be using quickmount...)
- ACE adds it's own interaction to unload people
Needs MP test (hence draft)
> Medical Engine - Hide actions that have ACE interactions

- addons/tagging/XEH_preStart.sqf
Why? Because engine already checks
Also engine will get optimization for when condition == "true", so we'll benefit from that here too when it arrives
> Tagging - Remove useless isClass check in configClasses

- addons/missileguidance/functions/fnc_seekerType_ARH.sqf
- Fix bug where AGM-114L used `positionASL` instead of `positionAGL` to check for targets
When developing I always used Altis near sea level for moving targets. This caused me to not catch this. Whoops
> MissileGuidance - Active Radar Homing: Use AGL for `nearestObjects` check

- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_compileMenuZeus.sqf
- remove useless `true && {` code from empy/`true` interaction conditions;
- optimize `fnc_compileMenuZeus` a little.
Before:
```
true && {
[ACE_player, _target, ["isNotInside", "isNotSwimming", "isNotSitting"]] call ace_common_fnc_canInteractWith
}
```
After:
```
[ACE_player, _target, ["isNotInside", "isNotSwimming", "isNotSitting"]] call ace_common_fnc_canInteractWith
```
> Interact Menu - Optimize interaction menu conditions

- addons/grenades/functions/fnc_addChangeFuseItemContextMenuOptions.sqf
**Make use of fnc_addToInventory:**
- When you convert an explosive to a grenade, it'll try and go back in to the same container to stop it magically jumping from backpack to vest etc.
If there is a better way to get the original container rather than abusing `splitString` let me know
> Grenades - Use fnc_addToInventory

- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_saf3/CfgWeapons.hpp
- Add missing ACE_GForceCoef value for DF-15 uniforms.
- ACE_GForceCoef value is the same as for Vanilla counterparts(Many other mods are using these values for their uniforms as well)
> RHS Compat - Add ACE_GForceCoef value for DF-15 uniforms

- tools/make.py
Macros with unused variables are warnings in latest public version
This causes issues with logging macros being unused with disabled debug
> Disable pboproject warnings are errors in build script

- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/dragging/functions/fnc_startCarry.sqf
- addons/dragging/functions/fnc_startDrag.sqf
- Force `setMass` synchronization in dragging/carrying
- Prevent collision damage with dragged/carried objects in the first few seconds after performing the action
Mass synchronization in Arma is delayed, this forces synchronization.
Tested on multiplayer dedicated, a few times to confirm, manually executing global event in debug console on object carry/drag. Can also observe results with `getMass`.
> Dragging - Fix mass synchronization

- addons/quickmount/functions/fnc_addFreeSeatsActions.sqf
- title.
This variable was not fully cleaned up in #7692.
> Quick Mount - Cleanup unused variable

- addons/chemlights/CfgVehicles.hpp
- addons/fastroping/CfgVehicles.hpp
- addons/interact_menu/functions/fnc_collectActiveActionTree.sqf
- addons/interact_menu/initSettings.sqf
- addons/interact_menu/stringtable.xml
- addons/map/CfgVehicles.hpp
- addons/quickmount/CfgVehicles.hpp
- addons/quickmount/functions/fnc_canShowFreeSeats.sqf
- add setting to combine parent menu with single child;
- adapt `fastroping` `Cut ropes` action for the setting;
- clean up `chemlights` and `map` menu configs a little.
Setting is disabled by default. ~Still not sure about setting name and description.~
> Interact Menu - Combine parent menu with single child

- addons/medical_damage/functions/fnc_handleIncapacitation.sqf
- addons/medical_damage/initSettings.sqf
- addons/medical_damage/stringtable.xml
- Changes the default 10% chance of unconsciousness from pain to a slider.
> Medical Damage - Add setting for unconscious chance from pain

- addons/cargo/menu.hpp
- addons/common/CfgEventHandlers.hpp
- addons/common/HintConfig.hpp
- addons/common/ProgressScreen.hpp
- addons/common/define.hpp
- addons/dagr/Dialog.hpp
- addons/dagr/RscTitles.hpp
- addons/goggles/RscTitles.hpp
- addons/huntir/Dialog.hpp
- addons/huntir/RscTitles.hpp
- addons/interact_menu/CursorMenus.hpp
mikro would convert these to 1/0, hemmt doesn't and makes them quotes
It's not really necessary because `getNumber (..."false")` = 0 and  `getNumber (..."true")` = 1
but I think it's best to be explicit
`disableModuload` is from some old abandoned mod that can be cleaned up as well
> Convert all true/false in configs to 0/1

- optionals/compat_r3f/CfgAmmo.hpp
- optionals/compat_r3f/CfgMagazines.hpp
- optionals/compat_r3f/CfgWeapons.hpp
- optionals/compat_r3f/config.cpp
- Update for a better compatibility with the new R3F 5.56 and 7.62 BDC reticles and to fit with the R3F 3.7.1 values.
For example, the R3F J8 and J10 reticles work now, but only with the default ballistic (not designed to work with AB).
> R3F Compat - Update to the R3F weapons 3.7.1

- addons/csw/CfgEventHandlers.hpp
Small diff but formatting actually matters to CBA_fnc_compileEventHandlers
```
//Optimize "QUOTE(call COMPILE_FILE(XEH_preInit));" down to just the content of the EH script
if (toLower (_eventFunc select [0,40]) isEqualTo "call compile preprocessfilelinenumbers '" && {(_eventFunc select [count _eventFunc - 1]) isEqualTo "'"}) then {
```
> CSW - use preferred XEH format

- tools/make.py
On current tools (pboProject 2.89/dePbo7.97)
Project built successfully but has significant errors in-game
ace_rearm:
```
#define GET_NUMBER(config,default) (if (isNumber (config)) then {getNumber (config)} else {default})
#define DEFAULT_REARMCARGO GET_NUMBER(configFile >> 'CfgVehicles' >> typeOf _this >> QQGVAR(defaultSupply),-1)
defaultValue = QUOTE(DEFAULT_REARMCARGO);
// mikro: Missing else statement
defaultValue = "(if (isNumber (configFile >> 'CfgVehicles' >> typeOf _this >> ""ace_rearm_defaultSupply"")) then {getNumber (configFile >> 'CfgVehicles' >> typeOf _this >> ""ace_rearm_defaultSupply"")}";
// expected
defaultValue = "(if (isNumber (configFile >> 'CfgVehicles' >> typeOf _this >> ""ace_rearm_defaultSupply"")) then {getNumber (configFile >> 'CfgVehicles' >> typeOf _this >> …
```
> Tools - Make.py don't Binarise ANY configs

- addons/common/functions/fnc_getPylonTurret.sqf
- addons/main/script_mod.hpp
- addons/rearm/functions/fnc_getNeedRearmMagazines.sqf
- Improve `getPylonTurret` common function by using `getAllPylonsInfo` command (2.02)
> Common - Improve getPylonTurret by using getAllPylonsInfo

- addons/logistics_wirecutter/CfgEventHandlers.hpp
- addons/logistics_wirecutter/CfgVehicles.hpp
- addons/logistics_wirecutter/XEH_PREP.hpp
- addons/logistics_wirecutter/XEH_clientInit.sqf
- addons/logistics_wirecutter/XEH_postInit.sqf
- addons/logistics_wirecutter/XEH_preInit.sqf
- addons/logistics_wirecutter/functions/fnc_cutDownFence.sqf
- addons/logistics_wirecutter/functions/fnc_destroyFence.sqf
- addons/logistics_wirecutter/script_component.hpp
- Add some more fence types for wirecutting
- Replace fences with destroyed models when cut where possible
Some large fences are replaced by multiple smaller fences, sometimes the whole net is removed and just a pole remains - I tried to make it look as realistic as possible. Unfortunately I could not find a suitable replacement model for one of the most used fences on Altis and Stratis (the razor wire fence just in front of the radar dome in the screenshots below).
Before             |  After
:-:|:-:
> Wirecutter - Replace fences with destroyed models when cut

- addons/cookoff/XEH_postInit.sqf
- When you apply `cursorObject setDamage [1, false]` to destroy an object by skipping destruction effects the ammunition still cookoff
- So now we check if we want to skip destruction effects or not before calling cookoff ammunition
> cookOff - Fix: Disable ammunition cookoff and turret effect when skipping destruction effects

- addons/markers/XEH_PREP.hpp
- addons/markers/functions/fnc_initInsertMarker.sqf
- addons/markers/functions/fnc_onButtonClickConfirm.sqf
- addons/markers/functions/fnc_onCheckedChangedTimestamp.sqf
- addons/markers/functions/fnc_onLBSelChangedColor.sqf
- addons/markers/functions/fnc_onLBSelChangedShape.sqf
- addons/markers/functions/fnc_removeTimestamp.sqf
- addons/markers/initSettings.sqf
- addons/markers/script_component.hpp
- addons/markers/stringtable.xml
The pull request that added the auto timestamping to the marker menu was incredibly rushed and broken.
- properly aligns text with "Timestamp" checkbox vertically
- makes checkbox a square instead of a fucking rectangle
- fixes completely broken 12-hour clock
- properly handles 12:xx am (after noon) and 12:xx pm (after midnight); 00:00 am/pm is not a thing...
- avoids the broken space character, because it is not a space in most fonts, bad workaround
- instead, adds ace_marker_fnc_removeTimestamp function
- removes bad code formatting changes with mid line whitespace
- includes the vanilla header file in the common component header file instead of in 5 different functions...
before
after:
> Fix Multiple Issues With Timestamps

- tools/make.py
- Set the required exclude from pbo settings as defined in https://ace3mod.com/wiki/development/setting-up-the-development-environment.html while running make.py
> Apply needed pboProject settings in make.py via Windows Registry

- addons/attach/functions/fnc_detach.sqf
- addons/common/functions/fnc_addToInventory.sqf
- addons/csw/functions/fnc_reload_handleReturnAmmo.sqf
- addons/hearing/functions/fnc_removeEarplugs.sqf
- addons/interaction/functions/fnc_canPassMagazine.sqf
- addons/interaction/functions/fnc_passMagazine.sqf
- addons/magazinerepack/functions/fnc_canRepackMagazine.sqf
- addons/magazinerepack/functions/fnc_getMagazineChildren.sqf
- addons/magazinerepack/functions/fnc_startRepackingMagazine.sqf
- title.
This adds ability to put items to inventory when you have enough space but weight is over 100lb. You now can correctly put earplugs out, repack magazines or detach IR strobe etc.
I didn't test only CSW and `Pass magazine` code.
> Replace canAdd with CBA_fnc_canAddItem

- addons/advanced_throwing/functions/fnc_renderPickUpInteraction.sqf
- docs/wiki/framework/advanced-throwing-framework.md
- Close #8030 
- Usage: `OBJECT setVariable ["ace_advanced_throwing_disablePickUp", true, true]`
> Advanced Throwing - Add object variable to disable pick up of attached throwables

- addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
- addons/medical_treatment/initSettings.sqf
- addons/medical_treatment/stringtable.xml
- Adds two settings to limit use of a) saline and b) blood and plasma to specific locations
- Settings are separate to allow more differentiation of the IV types in the future
- Needs translations
Additionally, I noticed that the Treatment subcategory in settings is getting pretty big. Would it be worth moving this to its own category?
> Medical Treatment - Settings to limit IVs to certain locations

- addons/medical_status/XEH_preInit.sqf
- Close #8024.
- Adds "Inventory" action to unconscious units. Uses base Arma 3 inventory, action looks identical to vanilla action.
> Medical - Show "Inventory" action on unconscious units

- addons/common/XEH_postInit.sqf
- Starting loadout
`[["SMG_05_F","","acc_pointer_IR","optic_Aco",["30Rnd_9x21_Mag_SMG_02",30],[],""],[],[],[],["V_PlateCarrier1_rgr",[["ACRE_PRC343_ID_1",1],["30Rnd_9x21_Mag_SMG_02_Tracer_Green",1,30],["30Rnd_9x21_Mag_SMG_02_Tracer_Red",1,30]]],[],"","",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]`
- Use **scrollwheel** to reload green tracers
- Point at something with ace_finger or use ace_gesutres
- Ending loadout
`[["SMG_05_F","","acc_pointer_IR","optic_Aco",["30Rnd_9x21_Mag_SMG_02",30],[],""],[],[],[],["V_PlateCarrier1_rgr",[["ACRE_PRC343_ID_1",1],["30Rnd_9x21_Mag_SMG_02_Tracer_Red",1,30]]],[],"","",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]`
- reload is interrupted and `30Rnd_9x21_Mag_SMG_02_Tracer_Green` magazine has vanished …
> Common - Fix Gesture mutex for scroll-wheel reloads

- addons/missileguidance/CfgAmmo.hpp
there is a delay between initial push and main rocket firing,
but we had it set at 2 seconds which looks very odd, the missile is just hovering in mid-air
based on https://www.youtube.com/watch?v=0HbtJfKzpec
it should be much more brief
vanilla is 0.25
> Javelin - Reduce soft-launch motor delay

- addons/maverick/stringtable.xml
- it will change the short name for the magazine of Maverick L to MAVL for consumption by the F/A-18EF MFD
- Change the stringtable.xml to return MAVL
> Maverick - Change displayShortName to MAVL for Maverick L

- docs/wiki/user/how-to-report-an-issue.md
We want people to choose a template when creating a new issue
> Adjust "New issue" link to lead to template selection page

- addons/captives/functions/fnc_doEscortCaptive.sqf
- Fix typo in ACE_captives_fnc_doEscortCaptive usage example
> Typo in usage example

- tools/make.py
- title;
- make make.py `mkstemp` create temp files in `P:\temp` instead of system temp folder.
I found many `tmpXXXXXXXX` files in my system temp folder. They were created by `mkstemp` function. Files were not moved because they are somewhat opened right after `mkstemp` call. So `shutil.move` just copies file and doesn't remove it. Simple `os.close` call fixes this problem. Maybe this exception was made for this (I'm not python programmer so don't know): https://github.com/acemod/ACE3/blob/76676eee462cb0bbe400a482561c148d8652b550/tools/make.py#L647-L649
Also there is no sense to use system temp folder when there is build temp folder.
> Tools - Fix make.py temp files cleanup

- addons/medical_feedback/functions/fnc_playInjuredSound.sqf
- `inAreaArray` takes AGL if z-value is provided.
- `playInjuredSound` gives it ASL, which means only units above z/2 sea level are detected as nearby.
- This PR changes the provided position from ASL to AGL in the most straight forward way possible.
- fix #8208
As an aside, this should've never checked the z in the first place. You're wasting more cycles than you will ever save iterating over units 3 stories above you. Just let the distance attenuation handle heights...
> Medical Feedback - Fix Injured Sounds Not Playing At Altitudes Above 70

- addons/map/config.cpp
See #6200
* This PR changes `zoomDuration = 0;` to `zoomDuration = 0.1;` in map config.
> Map - Fix stuck map compass size (add 0.1 zoom duration)

- AUTHORS.txt
- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- This pull request adds the ability to set custom rank icons on an individual unit via `setVariable`.
- Usage: `_unit setVariable ["ace_nametags_rankIcon", "<path to .paa file>"]`
- This should override the faction rank icons if set, otherwise the faction icons or defaults will be used as appropriate.
- An advantage to using the direct path to the .paa file is that it should allow loading from both addons and the mission file, if I'm not mistaken.
> Name Tags - Add ability to set custom rank icon

- addons/ui/ACE_Settings.hpp
- addons/ui/ACE_UI.hpp
- addons/ui/XEH_clientInit.sqf
- addons/ui/XEH_preInit.sqf
- addons/ui/functions/fnc_setAdvancedElement.sqf
- addons/ui/initSettings.sqf
- addons/ui/script_component.hpp
- addons/ui/stringtable.xml
- title;
- replace some numeric idcs with macro from `defineResincl.inc`;
- add addon name check and replace magic variable in setting handler;
- optimize a little `fnc_setAdvancedElement` (move idd check out of loop).
The setting appears on dev branch only. It hides `11400` control group (`class BcgWIP: RscWIP`) which contains 2 controls: `WIP_VersionText` (`idc = 1001`) and `WIP_VersionNumber` (`idc = 1000`). KK wrote about more controls [here](http://killzonekid.com/arma-scripting-tutorials-how-to-remove-beta-watermark-other-things/) but I think it was about A3 beta watermark.
> User Interface - Add setting for Development Build watermark

- addons/interact_menu/initSettings.sqf
- Reimplement #6656 by just changing the default setting.
A majority agreed with this change in the old PR, I think that just got more support in the last years, I don't know when I've last seen radial used by not-completely-new players.
> Interact Menu - Make List default

- addons/vehiclelock/initSettings.sqf
- addons/vehiclelock/stringtable.xml
- Improve `Vehicle Starting Lock State` setting names.
Renamed the "Default" setting to "As Is" and changed the current "As Is" to "Remove Ambiguous Lock State" to avoid confusion.
closes #6828
> Vehiclelock - Improve setting name

- addons/attach/functions/fnc_attach.sqf
- addons/attach/functions/fnc_detach.sqf
- addons/attach/functions/fnc_placeApprove.sqf
- docs/wiki/framework/events-framework.md
Add local events for post-attach and pre-detach.
Pre-detach because you may want the object thats being detached before its deleted.
No post-detach as I don't see much use for it.
> Attach - Added attached/detaching events

- addons/cargo/XEH_postInit.sqf
- addons/cargo/functions/fnc_paradropItem.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- Cargo - Improve make event "ace_cargoUnloaded" always pass object instead of sometimes passing classname.
- Cargo - Change move "ace_cargoUnloaded" event invocation from "ace_unloadItem" eh to function unloadItem to facilitate aforementioned change.
Fixes #8200
> Cargo - paradrop fixes

- addons/parachute/CfgVehicles.hpp
- addons/parachute/XEH_PREP.hpp
- addons/parachute/XEH_postInit.sqf
- addons/parachute/XEH_preInit.sqf
- addons/parachute/functions/fnc_handleFailureChance.sqf
- addons/parachute/script_component.hpp
- addons/parachute/stringtable.xml
- docs/wiki/framework/parachute-framework.md
- Add setting to enable percentage based failing of parachutes (0% chance by default).
- Add config value to `ParachuteBase` to set the failure delay.
- Add documentation for the config value mentioned above.
This was [a request](https://github.com/acemod/ACE3/issues/3594#issuecomment-546740178) from @DevastatorCM
[A small demo](https://youtu.be/nrmtXdw9ooU)
> Parachute - Add failure chance

- addons/ballistics/stringtable.xml
- Correct the birdshot pellet size in stringtable
- These were originally intended to be No. 7 size shot, but the number of pellets was too high so I changed it to No. 4 size bird shot to reduce the pellet count. I guess I forgot to update the strings at that time.
> Ballistics - Fix wrong shot size in birdshot strings

- tools/make.py
`build.py` and `hemtt pack` create pbo files in `optionals` dir. `make.py` needs only dirs to copy and stops with error.
> Tools - Fix make after hemtt pack

- addons/attach/CfgVehicles.hpp
- Change IR Strobe blinking pattern to 0.1 s on, 0.9 s off
- Increase lifetime to 8 hours
- Close #4946 
- Replace #5233
> Attach - Improve IR Strobe blinking pattern and increase lifetime

- addons/explosives/CfgVehicles.hpp
- title, "Interactions" text on the main action node was missing
> Explosives - Fix missing action name for setup helper object

- addons/common/XEH_postInit.sqf
Fix lost ammo bug on some RHS launcher.
```
class rhs_weap_rpg7 { reloadAction = "RHS_GestureReloadRPG7";
class CfgGesturesMale { class RHS_GestureReloadRPG7
```
- This changes the code to search both locations for launchers
(should it search both for all weapons? I think it's valid to put them either place?)
> Common - Fix gesture anim lockout for some launchers

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_getVehicleIcon.sqf
- Should be more optimised using a native hashmap. This function is used in spectator and for vehicle actions.
> Common - Improve vehicle icon caching implementation

- addons/medical/XEH_PREP.hpp
- addons/medical/functions/fnc_deserializeState.sqf
- addons/medical/functions/fnc_serializeState.sqf
- addons/medical_status/XEH_postInit.sqf
- addons/medical_status/functions/fnc_initUnit.sqf
- Add functions to serialize / deserialize the medical state of a unit to / from JSON
I considered just returning the CBA namespace, but I think a JSON string is easier to handle for DBs and such.
> Medical - Add functions to serialize / deserialize the medical state of a unit

- addons/medical_treatment/functions/fnc_cprLocal.sqf
- addons/medical_treatment/initSettings.sqf
- addons/medical_treatment/stringtable.xml
- CPR success chance is interpolated between two settings, based on current blood volume
- Default values are the same to maintain current behaviour
I've left the old stringtable entries in for reference - is this a bad idea?
Interpolates based on blood volume between 60% (below this value you would immediately arrest again) and 85% (minimum threshold for waking up)
> Medical Treatment - Allow variable CPR chance based on blood volume (invalidates old setting)

- addons/dagr/Dialog.hpp
- DAGR - Fix #8293 
I simply took 2nd and 7th underlines as they are aligned with 1st and 8th digit respectively and recalculated x values based on these. It is not perfect but definitely good enough.
> DAGR - Align underlining in waypoint editing page

- addons/medical_engine/CfgFunctions.hpp
- addons/medical_engine/XEH_PREP.hpp
- addons/medical_engine/XEH_preInit.sqf
- addons/medical_engine/config.cpp
- addons/medical_engine/functions/fnc_disableThirdParty.sqf
- Automatically disable third party medical systems. Currently supported:
- Vanilla revive system
- SOG:PF advanced revive system
- Farooq revive (https://github.com/farooqaaa/far_revive)
This would allow you to play missions not made with ACE in mind at least to some degree (like SOG:PF's Mike Force).
Suggestions for other systems welcome, these are just the ones I know of.
> Medical Engine - Disable third party medical systems

- addons/rearm/functions/fnc_rearmSuccessLocal.sqf
-  Fix Rearming so that turrets that are comprised of multiple magazines of the same type, of which each existing one may be full, or each one may only have a max count of 1: will be properly rearmed by properly adding the missing magazines directly to the turret
Please see #8286 for a breakdown of the current problem.
Fixes #8286 
Fixes #8166
> Rearm - Fix rearming turrets comprised of multiple magazines of the same type

- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- Add the RHS_Ural_Ammo_Base and rhs_kamaz5350_ammo_base into the config to allow them to be used for ACE rearming (which were added in RHS AFRF update 0.5.6).
- Add the rhs_rk_sht_30_olive_engineer and rhs_rk_sht_30_emr_engineer (which both have wirecutters on their model) to the wirecutting list.
- Add sound muffling to the new tank crew helmet, 6b48.
> RHS ARF Compat - Add ammo URAL & Kamaz, wirecutter backpacks and crew helmet

- addons/interact_menu/functions/fnc_renderActionPoints.sqf
- title.
To understand how inline function `_fnc_renderNearbyActions` works I had to simplify it a little. Changes:
- use `continue` to decrease loop nesting depth;
- replace `_numInteractions` (int) with `_hasInteractions` (bool) because number is not used;
- fix `_classActions = _namespace getVariable typeOf _target` doesn't have default value;
- some small code optimizations.
It's better to view changes in IDE than here in GitHub.
> Interact Menu - Simplify fnc_renderActionPoints

- addons/vehicles/CfgVehicles.hpp
- addons/vehicles/XEH_PREP.hpp
- addons/vehicles/functions/fnc_addStartupDelayToObject.sqf
- addons/vehicles/functions/fnc_setVehicleStartDelay.sqf
- addons/vehicles/functions/fnc_startEngine.sqf
- addons/vehicles/script_component.hpp
- docs/wiki/framework/vehicles-framework.md
- Add configurable engine startup delay by config and script
- Add function to set delay per vehicle
- Set default delay to 1.3 as it was before
- Add vehicles framework wiki page
> Vehicles - Add configurable engine startup delay

- addons/cargo/CfgVehicles.hpp
Each time you unload `Land_Cargo20_IDAP_F` from a HEMTT, the container collide with the vehicle and go in space 
This is due to `[cursorObject, a, player, 10, true] call ace_common_fnc_findUnloadPosition` whitch return a too close position for this container. The calculation of that position mainly depend on this:
```
getNumber (configFile >> "CfgVehicles" >> "Land_Cargo20_IDAP_F" >> "ace_cargo_size")
````
return `4`
```
getNumber (configFile >> "CfgVehicles" >> "Land_Cargo20_military_green_F" >> "ace_cargo_size")
````
return `50`
As we notice there is a big difference between a Land_Cargo20_military_green_F and Land_Cargo20_IDAP_F
- Use the same value as `Land_Cargo20_military_green_F` cargo variant as they have the same size
- change config …
> Cargo - Fix collision when unloading a IDAP 20m long container from HEMTT

- addons/zeus/ACE_Settings.hpp
- addons/zeus/XEH_postInit.sqf
- addons/zeus/XEH_preInit.sqf
- addons/zeus/functions/fnc_bi_moduleMine.sqf
- addons/zeus/functions/fnc_bi_moduleProjectile.sqf
- addons/zeus/initSettings.sqf
- addons/zeus/script_component.hpp
- Move the settings to CBA native
- Update the vanilla functions we need to override for modules (just the projectile one has some minor changes)
> Zeus - Move to native CBA Settings

- addons/medical_damage/initSettings.sqf
- addons/medical_damage/stringtable.xml
- addons/medical_engine/XEH_preInit.sqf
- addons/medical_engine/initSettings.sqf
- addons/medical_engine/stringtable.xml
> Medical - Fix #8389

- addons/medical_treatment/functions/fnc_treatment.sqf
- addons/medical_treatment/functions/fnc_treatmentFailure.sqf
- addons/medical_treatment/functions/fnc_treatmentSuccess.sqf
- docs/wiki/framework/events-framework.md
Adds
- `ace_medical_treatment_treatmentStartedLocal`
- `ace_medical_treatment_treatmentSucceededLocal`, and
- `ace_medical_treatment_treatmentFailedLocal`
CBA events. All of them have the same six parameters passed unchanged from the treatment action:
`_medic`, `_patient`, `_bodyPart`, `_classname`, `_itemUser`, `_usedItem`.
Rationale:
I've been trying to write a ShackTac-style medical extension without forking ACE. When trying to add a "PlayerName is bandaging you"/"You are being assisted" hint, I've been stopped by the following drawbacks in existing `ace_medical_treatment_{TREATMENT}Local` (e.g. `ace_medical_treatment_bandageLocal`) events:
1) They are not a single convenient entry point;
2) They do not carry a `_medic` parameter.
[Here's an example of someone else trying to do this …
> Medical - Add treatment status events

- addons/captives/functions/fnc_doApplyHandcuffs.sqf
- addons/captives/functions/fnc_doRemoveHandcuffs.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- docs/wiki/framework/events-framework.md
> Captives - Add caller to captiveStatusChanged event

- addons/vehicles/XEH_PREP.hpp
- addons/vehicles/XEH_postInit.sqf
- addons/vehicles/functions/fnc_autoThrottle.sqf
- Add a speed-limiter type control to planes
Uses a basic PID Controller to control the throttle of a plane to keep it at some speed. PID was tuned in Simulink, so values work well. Once you have speed limiter on, you don't have to touch the throttle again.
[Video of it in action](https://youtu.be/cWYr35_laGw)
> Vehicles - Add Auto-Throttle to Planes

- addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
- addons/medical_treatment/functions/fnc_canCPR.sqf
- addons/medical_treatment/functions/fnc_checkResponse.sqf
- addons/medical_treatment/functions/fnc_cprProgress.sqf
- addons/medical_treatment/initSettings.sqf
- addons/medical_treatment/stringtable.xml
- docs/wiki/feature/medical-system.md
Adds a 3rd setting level to advancedDiagnose that shows death/CA state
Doing CPR for 5 minutes on your buddy, not sure if he's alive or dead, might be heartbreakingly realistic
but I feel like some players will want a way to diagnose their state easily without having to drop down to basic diagnose
> Medical Treatment - Allow diagnosing death/CA (invalidates old setting)

- docs/wiki/framework/events-framework.md
- Fix wiki docs for `ace_treatmentStarted` and `ace_treatmentFailed` events (incorrect copy-paste)
Sorry for the inconvenience, don't know how I missed it.
> Docs - Fix medical treatment event descriptions (follow-up to #8385)

- addons/dragging/functions/fnc_dropObject.sqf
- title.
This var should not be qouted when removing:
https://github.com/acemod/ACE3/blob/58730b82fd831783bcf97f2b3dc3f6268ba4c3d3/addons/dragging/functions/fnc_dragObject.sqf#L48-L50
https://github.com/acemod/ACE3/blob/58730b82fd831783bcf97f2b3dc3f6268ba4c3d3/addons/dragging/functions/fnc_dropObject.sqf#L23
> Dragging - Fix keyhandler removing when drop

- addons/ballistics/CfgWeapons.hpp
> Ballistics - Add weapon data for the Contact M14

- addons/common/functions/fnc_removeSpecificMagazine.sqf
- addons/csw/functions/fnc_ai_handleFired.sqf
- Title.
- Close #8305.
- Refactor common_fnc_removeSpecificMagazine to also handle objects.
> CSW - Fix AI reloading from GroundWeaponHolder

- addons/dagr/CfgVehicles.hpp
- addons/dagr/initKeybinds.sqf
- addons/kestrel4500/initKeybinds.sqf
- Title.
- Allow configure DAGR self action to be shown while map is open. Consistency with all other condition checks.
- Close #8272.
- Allow Kestrel to be opened with deviceKey keybind while in a vehicle as well.
> DAGR / Kestrel - Fix deviceKey condition

- addons/cargo/CfgVehicles.hpp
20ft containers (`Land_Cargo20_military_green_F`) can be loaded. But all children from `Slingload_01_Base_F` which share the same real size of a 20ft container can't be loaded (ex: `B_Slingload_01_Ammo_F`)
- This pull request enable the loading of  `Slingload_01_Base_F` childrens. It follow the current behavior of all 20 ft containers (https://github.com/acemod/ACE3/blob/e6a0772adb86d6d4d4ee038570326625e48ccdd3/addons/cargo/CfgVehicles.hpp#L534-L647)
> Cargo - Fix can't load `Slingload_01_Base_F`

- addons/common/functions/fnc_endRadioTransmission.sqf
> Common - Add TFAR 1.0 support to endRadioTransmissions

- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_setVolume.sqf
- addons/medical_status/functions/fnc_setUnconsciousState.sqf
- Title.
- Supersedes #4334.
- Remove setting of master radio control variable from common_fnc_setVolume.
If it's still necessary to have setVolume control radio transmission allowance, I can edit that to call the status effect instead.
> Captives - Disallow ACRE/TFAR radio usage on surrender/handcuff

- addons/arsenal/functions/fnc_fillRightPanel.sqf
- title, items were incorrectly considered as magazines since 3rd parameter to `_fnc_fill_right_Container` was `true`
> Arsenal - Fix items in custom panels having mass of zero

- addons/arsenal/functions/fnc_updateUniqueItemsList.sqf
- title, could result in duplicate entries in the list if an item (CfgWeapons) had the same class name as, for example, its placeable/ground holder equivalent (CfgVehicles)
> Arsenal - Fix updateUniqueItemsList incorrectly identifying backpacks

- addons/arsenal/functions/fnc_onArsenalClose.sqf
- addons/arsenal/functions/fnc_onArsenalOpen.sqf
- Preserve the curator camera's state while using arsenal
- Small QOL improvement since Zeus camera should not move unexpectedly when modifying a unit's loadout
- Happens because mouse movement and scroll wheel still move curator camera while using the arsenal
> Arsenal - Restore curator camera state when exiting

- docs/wiki/development/coding-guidelines.md
- Fix some minor example inconsistencies in `Development/Coding guidelines`
https://github.com/acemod/ACE3/blob/66ce0ba5ff79c9b43dea37b06b71649b720595b6/docs/wiki/development/coding-guidelines.md#L465-L477
https://github.com/acemod/ACE3/blob/66ce0ba5ff79c9b43dea37b06b71649b720595b6/docs/wiki/development/coding-guidelines.md#L484-L494
https://github.com/acemod/ACE3/blob/66ce0ba5ff79c9b43dea37b06b71649b720595b6/docs/wiki/development/coding-guidelines.md#L722
> Docs - Fix inconsistencies in coding guidelines

- optionals/compat_rhs_afrf3/config.cpp
- optionals/compat_rhs_gref3/config.cpp
- optionals/compat_rhs_saf3/config.cpp
- optionals/compat_rhs_usf3/config.cpp
Finally getting rid of my todo entry from august 2019 :D 
This just simplifies the requiredAddons, and we don't need to update anything in case RHS decides to move things around.
> RHS Compats - Use RHS loadorder CfgPatches for compats

- addons/repair/functions/fnc_setDamage.sqf
- addons/repair/functions/fnc_setHitPointDamage.sqf
_useEffects was probably inverted. Makes ERA/SLAT not explode when repairing unrelated hitpoints. See #7452.
- Close #7452.
- Change fnc_setHitPointDamage default value for destruction effects to false.
- Add _useEffects parameter to fnc_setDamage.
- Prevent destruction effects from being played when doing partial repair on vehicles.
This was _probably_ an oversight, given that previous description of _useEffects parameter said it skipped destruction effects rather than use them. See [setDamage](https://community.bistudio.com/wiki/setDamage) syntax.
> Repair - Skip destruction effects

- addons/common/functions/fnc_moduleLSDVehicles.sqf
- addons/common/initSettings.sqf
- addons/common/stringtable.xml
- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/nightvision/functions/fnc_onFiredPlayer.sqf
- Add a setting in Common for an epilepsy friendly mode
This mode will currently:
- Disable the NVG shutter effects (see #6119)
- Make the flashbang effect a dark shade of gray instead of bright white (inspired by [this reddit post](https://www.reddit.com/r/Rainbow6/comments/oudmii/hey_i_am_a_player_with_sensitivity_to_flashes_in/))
I also plan to integrate it into #7761. That's just three uses of it for now, but I believe it's a simple change that could help a few people.
> Common - Add epilepsy friendly mode

- addons/attach/functions/fnc_attach.sqf
- addons/attach/functions/fnc_detach.sqf
- addons/attach/functions/fnc_handleGetIn.sqf
- addons/attach/functions/fnc_placeApprove.sqf
- docs/wiki/framework/events-framework.md
I need this for GPS trackers on the player.
I want the tracker to be moved over to the vehicle instead of being deleted, for that I need to know when that happens.
> [Attach] Add event property to detect temporary detach/reattach

- addons/arsenal/functions/fnc_sortPanel.sqf
- title, sortPanel would reset any custom item name set through panel filled event handlers by getting the name from config again
- Used by ACE dogtags and ACRE radios
- Fix sortPanel not using correct item config in rare cases
> Arsenal - Fix sortPanel clearing custom item names

- docs/wiki/development/arma-3-scheduler-and-our-practices.md
- docs/wiki/development/coding-guidelines.md
- docs/wiki/development/setting-up-the-development-environment.md
- docs/wiki/feature/hellfire.md
- docs/wiki/feature/hot.md
- docs/wiki/feature/refuel.md
- docs/wiki/framework/advanced-throwing-framework.md
- docs/wiki/framework/cargo-framework.md
- docs/wiki/framework/events-framework.md
- docs/wiki/framework/explosives-framework.md
- docs/wiki/framework/field-rations-framework.md
- docs/wiki/framework/fortify-framework.md
- docs/wiki/framework/headless-framework.md
- docs/wiki/framework/interactionMenu-framework.md
- docs/wiki/framework/respawn-framework.md
- docs/wiki/framework/spectator-framework.md
- docs/wiki/framework/switchunits-framework.md
- docs/wiki/framework/vehiclelock-framework.md
- Make use of the SQF highlighting
Jekyll uses Rouge for highlighting and I added SQF highlighting to it a while ago (rouge-ruby/rouge#761). I've already replaced the tags for it on the arsenal framework page in #8650.
> Replace CPP highlighting with SQF highlighting

- addons/medical_feedback/XEH_postInit.sqf
- Set uncon toggle of DisableUserInput to false on death and featureCamera.
Forgot to add this in #8373.
> Medical Feedback - Enable User Input on featureCam

- addons/reload/CfgMagazines.hpp
See Title, the Cyrus magazine for some reason inherits from the HK121 belt box
> Cyrus magazine incorrectly configured as a belt

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/main/script_macros.hpp
- Debounce the flashbang reaction, which will make the 9 bang usable
- Fix the skill adjustment, so it doesn't lose sub skill values
- Store the flash strength on the unit, not used in ACE but I know I could use it in other mods personally
> Grenades - Flashbang reaction fixes

- addons/logistics_rope/CfgWeapons.hpp
model p3d is linked to Helicopter DLC
Apparently those who don't own the dlc cannot pickup item
> Logistics Rope - Use generic model instead of one linked to DLC

- addons/killtracker/README.md
- addons/killtracker/XEH_postInit.sqf
- addons/killtracker/config.cpp
Removes `ace_medical` from `requiredAddons`
> Killtracker - Remove medical from required addons

- addons/frag/functions/fnc_addPfhRound.sqf
- addons/frag/functions/fnc_pfhRound.sqf
- Title.
- Close #8073.
Current position of shooter was used instead of round's original position. If shooter moved beyond fuse distance, round would create fragmentation without any effects.
> Frag - Fix fuse-arming distance calculation

- addons/explosives/ACE_Triggers.hpp
- addons/explosives/functions/fnc_startTimer.sqf
- addons/overpressure/initSettings.sqf
title
~~This fix only works on client. I don't know if this function is supposed to be call server side.~~
~~As workaround, we could check if player is not null and pass _explosive as instigator.~~
- Pass the player setting the timer as instigator
- relevent function: 
- https://github.com/acemod/ACE3/blob/06336b8dcfa8128b37ecb0ffb9961def8e02c22f/addons/explosives/functions/fnc_detonateExplosive.sqf#L58
- https://github.com/acemod/ACE3/blob/87cfd9632e369dcd7529700f0f2e5bdd332697ab/addons/explosives/XEH_postInit.sqf#L28
> Explosives - Fix `objNull` reported as source and instigator in BI `handleDamage` event for explosive triggered by timer

- addons/fire/XEH_postInit.sqf
- addons/fire/initSettings.sqf
- addons/fire/stringtable.xml
Add a CBA setting that can disable/enable the screaming sounds when units are on fire. fixes https://github.com/acemod/ACE3/issues/8664 
Adds a CBA setting.
Adds check in "playScream" event before playing the screams.
> Fire - Adding option to disable screaming for units on fire

- addons/overheating/functions/fnc_coolWeaponWithItem.sqf
- addons/overheating/functions/fnc_coolWeaponWithWaterSource.sqf
- addons/overheating/functions/fnc_getBarrelMass.sqf
- addons/overheating/functions/fnc_swapBarrelCallback.sqf
- addons/overheating/functions/fnc_updateAmmoTemperature.sqf
- addons/overheating/functions/fnc_updateTemperature.sqf
- switch from params to select for single value returns when calling getWeaponData
> Overheating - Use `select` instead of `params`

- addons/fire/functions/fnc_burn.sqf
- addons/fire/functions/fnc_burnReaction.sqf
- Only play screams if unit on fire is a human
Though hilarious, not too immersive and in line the realism ACE strives for ....
> Fire - Fix animals screaming like humans

- optionals/compat_sog/functions/fnc_handlePunjiTrapDamage.sqf
> SOG Compat - Add `isDamageAllowed` check to punji damage handler

- addons/cookoff/functions/fnc_cookOff.sqf
- addons/cookoff/script_component.hpp
- title
**Reasoning:**
Advanced vehicle damage calculates the intensity (which indirectly also means duration) of the cook-off by getting the amount of the explosive ammo. This can result in ridiculously long cook-offs for vehicles that have autocannons with HE ammunition.
I've decided to use 10 intensity as maximum which roughly should limit it to ~7.5min (the intervals between cook-offs are randomised).
We could consider making this a setting but I'm not sure how to properly tell the user what it does.
**Reproduction of the issue:**
- spawn `O_APC_Tracked_02_cannon_F`
- spawn 'B_MBT_01_TUSK_F`
- shot IFV in the turret with the Tank Heat round
- ~15min cook-off
> Cookoff - Limit maximum cook intensity/duration

- docs/wiki/framework/arsenal-framework.md
- ~~Fix the title being "ACE Arsenal" instead of just "Arsenal" ([see here](https://ace3mod.com/wiki/framework/))~~
- Use tables for parameter documentation instead of copied doccomments
- Move "Access to ACE Arsenal" in front of "Virtual Items", since the latter requires the former
- Improve general consistency
<details>
<summary>Screenshot</summary>
</details>
> Documentation - Rework arsenal docs

- addons/medical_engine/functions/fnc_applyAnimAfterRagdoll.sqf
Semi related to PR #8623
Makes all clients pick the exact same animation instead of purely random.
The actual randomness is constant per unit and it only has 64 possible values so the distribution won't be perfect, 
but I think it's more than good enough for this application.
> Medical Engine - Synchronize random unconscious anims

- docs/wiki/framework/rearm-framework.md
- docs/wiki/framework/vehicledamage-framework.md
- add documentation for `ace_rearm_scriptedLoadout` to Rearm
- fix numbering in documentation for Vehicle Damage
> Documentation - Improve documentation for Rearm & Vehicle Damage

- addons/medical_engine/XEH_postInit.sqf
Fixes being stuck in the uncon animation when hit by a car but not really being unconscious. This happened after the change inside the CfgExtendedAnimation class for 3.14.1 RC0.
> Medical - Fix stuck in uncon animation after CfgExtendedAnimation change

- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgAmmo.hpp
Fix
```
Updating base class rhs_6b47_bare->H_HelmetB, by z\ace\addons\compat_rhs_afrf3\config.cpp/CfgWeapons/rhs_6b48/ (original rhsafrf\addons\rhs_c_troops\config.bin)
Updating base class O_Truck_02_covered_F->rhs_truck, by z\ace\addons\compat_rhs_afrf3\config.cpp/CfgVehicles/rhs_kamaz5350/ (original (rhsafrf\addons\rhs_c_kamaz\config.bin - no unload))
Updating base class rhsusf_ammo_reduced_penetrator->rhsusf_ammo_basic_penetrator, by z\ace\addons\compat_rhs_usf3\config.cpp/CfgAmmo/rhs_ammo_mk19m3_M430I_penetrator/ (original rhsusf\addons\rhsusf_c_heavyweapons\config.bin)
```
> RHS Compats - Fix various UBCs

- addons/slideshow/CfgVehicles.hpp
- addons/slideshow/functions/fnc_addSlideActions.sqf
- addons/slideshow/functions/fnc_autoTransition.sqf
- addons/slideshow/functions/fnc_createSlideshow.sqf
- addons/slideshow/functions/fnc_moduleInit.sqf
- addons/slideshow/stringtable.xml
- docs/wiki/framework/slideshow-framework.md
- Adds support for texture selections of objects instead of only using 0.
> Slideshow - Add support for texture selections

- addons/maptools/functions/fnc_canUseMapTools.sqf
- title
Reasoning:
Modded maps are not required to inherit from `ItemMap` class, but only items with `simulation` equal to `ItemMap` can be put into map slot.
> Map Tools - Improve modded maps support

- optionals/compat_rhs_usf3/CfgEventHandlers.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
- Only make the fuel jerrycans to, well, fuel jerrycans
- Adjust `Water source` interaction position for water jerrycans
- Make the them all carryable
Close https://github.com/acemod/ACE3/issues/8710
> Compats - Fix RHSUSF water Jerry Can having refuel actions

- addons/common/functions/fnc_assignedItemFix.sqf
- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_cookOff.sqf
- addons/cookoff/functions/fnc_smoke.sqf
- addons/fire/functions/fnc_burn.sqf
- addons/fire/functions/fnc_burnReaction.sqf
- addons/fire/functions/fnc_fireManagerPFH.sqf
- addons/headless/functions/fnc_transferGroups.sqf
- addons/intelitems/functions/fnc_deleteControl.sqf
- addons/interaction/functions/fnc_renameGroupUI.sqf
- addons/markers/functions/fnc_initInsertMarker.sqf
- addons/markers/functions/fnc_placeMarker.sqf
- addons/pylons/functions/fnc_onButtonApply.sqf
- addons/tagging/functions/fnc_applyCustomTag.sqf
- addons/vehicle_damage/functions/fnc_processHit.sqf
- addons/viewrestriction/functions/fnc_canChangeCamera.sqf
- addons/viewrestriction/functions/fnc_switchPreserveView.sqf
> General - Utilize `isNotEqualTo` command

- optionals/compat_rhs_gref3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
Fix some overheating issues with RHS M249 and MG42, since they had the `ace_overheating_closedBolt` set to `1` through inheriting from `Rifle_Base_F`.
- Fix RHS:USF M249/MiniMi having closed bolt
- Fix RHS:GREF MG42 having closed bolt
Partially fixes https://github.com/acemod/ACE3/issues/8790
> Compats - Fix RHS LMGs being classed as closed bolt systems

- addons/advanced_ballistics/XEH_postInit.sqf
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_deprecateComponent.sqf
- addons/common/functions/fnc_endRadioTransmission.sqf
- addons/common/functions/fnc_isModLoaded.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/nametags/functions/fnc_initIsSpeaking.sqf
- addons/overheating/XEH_postInit.sqf
- addons/overheating/functions/fnc_canCoolWeaponWithItem.sqf
- addons/overpressure/functions/fnc_firedEHBB.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- addons/zeus/functions/fnc_handleZeusUnitAssigned.sqf
- optionals/compat_sog/functions/fnc_handlePunjiTrapDamage.sqf
- Title.
- Move remaining manual CfgPatches lookups to use the function.
- Change a CfgVehicles >> typeOf lookup to configOf.
- Change overpressure damage to only show blood effect if damage is enabled.
> Common - Add cache to `fnc_isModLoaded`

- addons/cargo/XEH_postInit.sqf
- docs/wiki/framework/cargo-framework.md
- Add variable to allow disable renaming on object level _(Sometimes you might want a box to be named in a specific way.)_
_Need testing_
> Cargo - Add ability to disabled rename on object level

- addons/cargo/CfgVehicles.hpp
- addons/cargo/functions/fnc_getNameItem.sqf
- addons/fire/stringtable.xml
- Title.
- Block renaming 300l fuel container.
- Change config macro to GVAR from EGVAR.
> Cargo - Improve config and `fnc_getNameItem`

- optionals/compat_rhs_afrf3/stringtable.xml
- optionals/compat_rhs_usf3/stringtable.xml
> RHS Compats - Fix Stringtables (#8798)

- addons/medical_status/XEH_postInit.sqf
- addons/medical_status/functions/fnc_setDead.sqf
> Medical Status - Add `isDamageAllowed` check to `setDead`

- optionals/compat_sog/CfgMagazines/csw.hpp
vn_m1919_v_250_mag magazine has scopeArsenal attribute set to 0 so compat needs to address it.
- Make CSW ammo for M1919 show up in arsenal
> SOG Compat - Fix M1919 ammo not showing in arsenal

- addons/arsenal/functions/fnc_onSelChangedLeft.sqf
- addons/arsenal/functions/fnc_onSelChangedRight.sqf
- addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- Add `instant` param to addWeaponItem usage in arsenal so magazine is reloaded instantly. This was particularly noticeable with launchers.
- Remove obsolete comment in `reloadlaunchers` that implied reloading time was still being used.
- Change some `addXWeaponItem` usage to straight `addWeaponItem` so animations are skipped as well.
See: https://community.bistudio.com/wiki/addWeaponItem
> Arsenal - Improve `addWeaponItem` usage

- addons/common/functions/fnc_loadPerson.sqf
- addons/common/functions/fnc_loadPersonLocal.sqf
- addons/medical_treatment/CfgVehicles.hpp
- addons/medical_treatment/functions/fnc_loadUnit.sqf
- docs/wiki/framework/medical-treatment-framework.md
- Defines seats to prioritize when loading patients into vehicles
- Documentation for mod makers to add it to their vehicles
- If there are no preferred seats available, patients are loaded from highest cargo seat to lowest
https://user-images.githubusercontent.com/3946739/150858689-959180fa-bce7-4bb0-9b01-aa33ec19fb07.mov
> Medical Treatment - Add preferred seats for loading patients

- addons/weather/functions/fnc_calculateRoughnessLength.sqf
- fix https://github.com/acemod/ACE3/issues/8705
`nearObjects` apparenlty takes PosAGL, while the functions takes PosASL.
I am pretty sure it actually doesn't matter which position you provide and `nearObjects` actually ignores z entirely.
This would mean being 1000 meters above a town would give you high "roughness", even though you are well above the buildings.
Seems like the function is half assed and does not take building height into account at all. Could add a distance check to the buildings, but to be completely sure, you likely have to take building geometry into account.
Ngl, I am salty that half-assed stuff like this is in ACE. Would appreciate if anyone has a solution for this.
> Weather - Fix `calculateRoughnessLength` detecting buildings above sea level

- optionals/compat_rhs_usf3/CfgVehicles.hpp
- Fix 3DEN `Equip FRIES` attribute for RHS:USAF UH-1Y
Partially fixes https://github.com/acemod/ACE3/issues/6068.
Not sure about the other issues mentioned in the ticket: 
- Non pylon choppers not having the option to equip F.R.I.E.S through `Edit Pylons` (obviously)
- Can't really see any issues with where the F.R.I.E.S is attached to the UH-60's
- UH-60 MEV (ESSS) explicitly having it disabled (by design)
> Compats - Fix RHSUSF UH-1Y F.R.I.E.S options

- addons/nametags/functions/fnc_drawNameTagIcon.sqf
- fix #8719 
- Make sure `_icon` is never `nil`
- Looks like when a unit (player or IA) is killed, the `rank` return `""` just before the ACE nametags disappear
> Nametags - Fix ACE nametag drawIcon3D parameter error when player controlled unit dies

- addons/arsenal/functions/fnc_onSelChangedLeft.sqf
Improve the removal of magazines when switching weapons in the arsenal.
Current behaviour:
- When a new weapon is selected, only magazines defined in the "magazines" attribute of the old weapon's class were deleted.
See [here](https://github.com/acemod/ACE3/blob/936dd5d9786cd32b3061cf702f9ce45b45fa852a/addons/arsenal/functions/fnc_onSelChangedLeft.sqf#L32).
This leads to inconsistent and unnecessary magazine removal upon weapon switching.
- When a new weapon is selected, it would consume a magazine from the loadout.
See [here](https://github.com/acemod/ACE3/blob/936dd5d9786cd32b3061cf702f9ce45b45fa852a/addons/arsenal/functions/fnc_onSelChangedLeft.sqf#L62).
Improved behaviour:
- When a new weapon is selected, it will remove all magazines from the …
> Arsenal - Improve magazine removal after weapon switch

- addons/interact_menu/functions/fnc_keyDown.sqf
- Prevent the interaction menu from activating if currently focused control on any display is of type CT_EDIT.
My interaction keys are in E and F, and the interact menu opens while searching in ZEN. This blocks that.
> Interact Menu - Add blocking while editing CT_EDIT

- addons/magazinerepack/functions/fnc_startRepackingMagazine.sqf
- addons/magazinerepack/initSettings.sqf
- addons/magazinerepack/stringtable.xml
Previously you'd just sit there doing nothing for X seconds and at times people can question why you're just sitting still for 10 seconds doing apparently nothing.
Needs some translation help because I can only google translate and I do not trust its handling of the excluded languages in this PR.
- _Adds the 'Gear' idle animation when a player starts repacking magazines_
- _Adds an ACE setting to allow for disabling of the new animation_
> Magazine Repack - Add idle animation when a player starts repacking magazines

- addons/finger/functions/fnc_incomingFinger.sqf
- addons/finger/functions/fnc_perFrameEH.sqf
- addons/finger/initSettings.sqf
- addons/finger/stringtable.xml
- add two settings to scale the size of the visual marker; `sizeCoef` will scale the size directly from the setting value, default 1x is the same as the current size; `proximityScaling` will scale the size based on the distance between the observer and the pointer, 2x the size at `maxRange`, 0.25x at 0m, interpolated in between.
> Finger - Add scaling settings

- addons/vehicles/XEH_postInit.sqf
- addons/vehicles/initSettings.sqf
Before if you set speedlimter at 22
22->27->32
now
22->25->30
> Vehicles - Mousewheel will set speed limiter value to even multiples

- addons/vehicles/XEH_postInit.sqf
- addons/vehicles/functions/fnc_speedLimiter.sqf
- addons/vehicles/script_component.hpp
- addons/vehicles/stringtable.xml
- docs/wiki/feature/vehicles.md
- Adds cruise control by pressing `Insert`
- Interacts smoothly with the speed limiter
Example:
- Player is driving 30 km/h
- Enables speed limiter, set to 30 km/h
- Player slows to 15 km/h
- Enables cruise control, vehicle will accelerate to 30 km/h
- Player increases the speed limit to 50 km/h, cruise control will accelerate to 50 km/h
- Player enables speed limiter, cruise control will disable, speed limit still set to 50 km/h
> Vehicles - Add cruise control

- addons/maptools/CfgVehicles.hpp
- addons/maptools/XEH_postInitClient.sqf
- addons/maptools/functions/fnc_handleMouseMove.sqf
- addons/maptools/functions/fnc_updateMapToolMarkers.sqf
- Show the Map Tools not in the bottom-left corner of the map when first opened, but right where your mouse is (as soon as mouse is moved slightly; might need further improvement here) 
- see https://youtu.be/pjgQJSyNKTs for a quick demo of the new behaviour
- does not affect the documentation of Map Tools
- sorry no; such a small change does not justify reading through all of that :-/
> maptools - Improve behaviour upon first open (show under mouse position instead of bottom-left corner)

- addons/laser/functions/fnc_seekerFindLaserSpot.sqf
- Fixes an issue with laser seeker return value mentioned [here](https://github.com/acemod/ACE3/pull/8531#issuecomment-954865110)
- Chooses the owner with most hits instead of the last one in the hashmap iteration order
> Laser - Fix seeker owner return value

- addons/common/XEH_postInit.sqf
- addons/common/XEH_preInit.sqf
Moved ace_common_isModLoadedCache from postinit to preinit. The hash object can be used before post init which then produces errors.
> Common - Fix undefined variable for isModLoadedCache

- addons/pylons/functions/fnc_showDialog.sqf
Same as vanilla does in Eden editor.
> Pylons - Show ammo description in pylon loadout tooltips

- addons/spottingscope/XEH_preInit.sqf
Fix `Error setposasl: Type Object, expected Array` when destroying Spotting Scope.
> Spottingscope - Fix destruction of Spotting Scope

- addons/vector/CfgWeapons.hpp
We don't rotate the numbers, so it doesn't make sense to rotate the reticule.
> Vector - Disable tilting the reticule when zoomed

- addons/laser/initSettings.sqf
- addons/laser/stringtable.xml
- addons/laserpointer/stringtable.xml
Add
- `laser`: Add missing Hungarian translation of laser (BI doesn't have it translated).
Change
- `laser`: Change `localize` to `LLSTRING`.
Fix
- `laser`: Fix capitalization of laser. It's used in settings and looks off with only "laser" but no other setting in lowercase.
- `laserpointer`: Fix Japanese translation of "Laser" to match the one in the `laser` module.
Note
- The same translation of "Laser" now exists in both the `laser` and `laserpointer` modules. Maybe it should be put in `common`?
- "レーザー" and "レーザ" are mixed in the aforementioned modules. I guess the former should be used: a Japanese person I asked said the former is correct and the latter wrong, BI uses the former, Wikipedia redirects to the former, most dictionaries I've looked in translates "laser" to the former, but …
> Laser/Laserpointer - Fix localization of laser

- addons/cargo/functions/fnc_canLoadItemIn.sqf
Loading a cooked-off item and waiting until it is no longer cooked-off will allow you to unload it in a state in which it cannot be interacted with. The proposed commit prevents you from being able to do that. If trying it will just say for example `Basic Ammo [NATO] could not be loaded`. This does not remove the `Load` action on the item however. Maybe someone else can add that.
> Cargo - Remove the ability to load cooked-off items

- addons/medical_vitals/functions/fnc_handleUnitVitals.sqf
- docs/wiki/framework/events-framework.md
- Add a local event in the main vitals loop so that extension mods can run updates in-sync without having to write their own loop.
> Medical Vitals - Add event to vitals loop

- addons/ui/CfgInGameUI.hpp
- addons/ui/config.cpp
- addons/ui/initSettings.sqf
- addons/ui/stringtable.xml
- Implement #6193 with a setting.
Tested the setting in config, works nicely, and even defaults to the default value correctly (copied from vanilla config).
> User Interface - Add ability to hide Default Action Icon

- addons/csw/functions/fnc_assemble_deployTripod.sqf
- addons/csw/functions/fnc_assemble_pickupWeapon.sqf
- addons/csw/functions/fnc_reload_getVehicleMagazine.sqf
- addons/csw/functions/fnc_staticWeaponInit_unloadExtraMags.sqf
- fix missing magazine on assembling some launchers (I know only about CUP Metis);
- fix `fnc_reload_getVehicleMagazine` header arguments.
When you place loaded with rocket CUP Metis to its internal tripod (you don't need an external one) it's assembled but without rocket in it. Rocket is just disappeared from your inventory. Also when you disassemble static Metis to portable launcher it's empty and rocket(s) is placed near you. This PR makes new launcher loaded if it was loaded before (dis)assembling.
> CSW - Fix missing magazine on assembling

- addons/casings/$PBOPREFIX$
- addons/casings/CfgEventHandlers.hpp
- addons/casings/README.md
- addons/casings/XEH_PREP.hpp
- addons/casings/XEH_postInit.sqf
- addons/casings/XEH_preInit.sqf
- addons/casings/XEH_preStart.sqf
- addons/casings/config.cpp
- addons/casings/functions/fnc_createCase.sqf
- addons/casings/functions/fnc_createCasing.sqf
- addons/casings/functions/script_component.hpp
- addons/casings/initSettings.sqf
- addons/casings/script_component.hpp
- addons/casings/stringtable.xml
- It's a stripped down and basic version of (https://github.com/acemod/ACE3/pull/4132).
- Only impacts infantry weapons, no vehicles etc
- Fully local, no network sync
- Has some settings (on/off, maximum amount of brass)
I've been using a version of this since 2020. It works fairly well, will have odd floating cases, especially near the edges of objects and buildings etc. I've taken most of the vector bits from the original PR, math could probably be better if anyone wants to have a go!
I've left esteldunedain in the authors as I'm using parts of his original code. Also @diwako helped me with this a while ago, happy to add you on to this too bud!
> Casings - Add infantry bullet casings

- addons/cargo/XEH_PREP.hpp
- addons/cargo/XEH_postInit.sqf
- addons/cargo/functions/fnc_unloadCarryItem.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/dragging/script_component.hpp
- Title.
Player will start carrying or dragging item after unloading from cargo if possible. Includes weight checking.
> Cargo - Make player carry/drag item on unload

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_setVolume.sqf
- addons/medical_status/functions/fnc_setUnconsciousState.sqf
- Add new status effect `blockSpeaking` to block acre direct voice
- Set `blockSpeaking` in `setUnconsciousState`
> Common - Add separate blockSpeaking status for acre direct

- addons/fastroping/CfgVehicles.hpp
- addons/fastroping/script_component.hpp
- addons/fastroping/script_macros.hpp
- optionals/compat_rhs_gref3/CfgVehicles.hpp
- optionals/compat_rhs_gref3/script_component.hpp
- optionals/compat_rhs_usf3/CfgVehicles.hpp
- optionals/compat_rhs_usf3/script_component.hpp
- optionals/compat_sog/CfgVehicles.hpp
- Cleanup copypasted FRIES macro
- Remove unused FRIES macro from SOG PF compat
- Fix UBC issues in RHS compats due to overriden Attributes classes
- Test in game
- Verify UBC issues are fixed
> Fastroping - Improve FRIES macro and fix UBC issues in RHS Compats

- addons/overheating/functions/fnc_getWeaponData.sqf
- docs/wiki/framework/overheating-framework.md
- Add an optional config value for barrel mass to overheating.
This is intended to allow mod makers to individually tweak the heating and cooling potential of their weapons to better reflect their actual ability.
> Overheating - Add barrel mass config value

- optionals/compat_sog/CfgMagazines/explosives.hpp
- optionals/compat_sog/CfgVehicles/explosives.hpp
- Fix spiked ammo box not setup for ace explosives
- Closes #8886
> Explosives - SOG Compat - Fix Spiked ammo box placing wrong ammo type

- docs/wiki/feature/viewports.md
- docs/wiki/framework/viewports-framework.md
- Fix documentation failing to build regression from #8480.
Used 3.15.0, but we can change to 3.14.x later if necessary.
> Documentation - Fix Viewports versions

- docs/_config.yml
- docs/_config_dev.yml
- Fix `GitHub Metadata: site.name is set in _config.yml, but many plugins and themes expect site.title to be used instead. To avoid potential inconsistency, Jekyll GitHub Metadata will not set site.title to the repository's name.`
> Documentation - Use title instead of name

- addons/cookoff/functions/fnc_cookOff.sqf
- addons/cookoff/initSettings.sqf
- addons/cookoff/stringtable.xml
- Add a setting to always destroy vehicles after cooking off
- The vehicle will be destroyed without explosion
- Catastrophic kill effect will trigger if `_detonateAfterCookoff` is true
- Addresses https://github.com/acemod/ACE3/issues/8715
> Cookoff - Add setting to destroy vehicle after cooking off

- addons/cookoff/functions/fnc_getVehicleAmmo.sqf
- Fix ammo not being removed from turrets which have "additional" FFV, eg. in tanks after turning out from gunner pos
> Cookoff - Fix ammo not being removed from turrets with additional FFV

- addons/cookoff/functions/fnc_cookOff.sqf
- addons/cookoff/functions/fnc_cookOffEffect.sqf
The main purpose is to fix vehicles like a vodnik spawning the fire jet effect because it doesn't really make any sense and looks odd.
- Adds `ace_cookoff_canHaveFireJet` config number value that determines if its allowed to create a fire jet during cookoff (no set value defaults to enabled)
> Cookoff - Add ability to disable fire jet effect in configs

- addons/logistics_wirecutter/script_component.hpp
- make the wirecutter able to cut through all new wire fences. (there was some addition to the fences of vanilla ArmA (e.g. at the airport on Altis).
- fences for @cup_terrains_core are also included.
> Logistics Wirecutter - Add new fences models for the wirecutter

- addons/cookoff/CfgVehicles.hpp
- docs/wiki/framework/cookoff-framework.md
Ref issue https://github.com/acemod/ACE3/issues/8952
- Removes CfgVehicles changes to dead `ace_cookoff_ignoreTurret` parameter that has since been replaced with `ace_vehicle_damage_turretFireProb`
- Updates cookoff doc's `Ignore damage to turret` reference to the correct `ace_vehicle_damage_turretFireProb` variable.
> Cookoff - Removed references to unused ignoreTurret parameter in code and docs

- addons/interact_menu/CursorMenus.hpp
- Fix closing the display for the black screen option on Profiling branch and Arma 2.10
- Removed the "unset" on display unload as it created a race condition when a new display was opened
> Interaction Menu - Fix black screen option not removing background properly

- addons/vehicle_damage/initSettings.sqf
As stated in https://github.com/acemod/ACE3/pull/8734#discussion_r787918244, Maintainers have decided that Advanced Vehicle Damage should disabled by default.
- Change default setting of advanced vehicle damage to false
- Allow https://github.com/acemod/ACE3/pull/8734 to be merged
> Advanced Vehicle Damage - Change default setting to disabled

- addons/overpressure/CfgWeapons.hpp
- addons/overpressure/XEH_PREP.hpp
- addons/overpressure/XEH_postInit.sqf
- addons/overpressure/functions/fnc_cacheOverPressureValues.sqf
- addons/overpressure/functions/fnc_firedEHBB.sqf
- addons/overpressure/functions/fnc_firedEHOP.sqf
- addons/overpressure/functions/fnc_getOverPressureValues.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- docs/wiki/development/ace3-config-entries.md
- docs/wiki/framework/overpressure-framework.md
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- optionals/compat_rhs_gref3/CfgWeapons.hpp
- optionals/compat_rhs_saf3/CfgWeapons.hpp
- optionals/compat_rhs_usf3/CfgWeapons.hpp
- Add backblast offset to shoulder launchers
- Change overpressure cache from missionNamespace vars to a hashMap
- Update docs with new `ace_overpressure_offset` attribute
Fix https://github.com/acemod/ACE3/issues/8979
> Overpressure - Fix backblast originating at projectile

- addons/fire/functions/fnc_burn.sqf
- Change mempoint used for fire sound source to avoid RPT errors
Removes the current RPT error:
```13:51:29 Error: Invalid memory point 'destructionEffect1' provided to attachTo on shape 'a3\characters_f\blufor\b_soldier_01.p3d'```
> Fire - Fix incorrect mempoint for sound source

- addons/csw/functions/fnc_ai_reload.sqf
- addons/csw/functions/fnc_reload_loadMagazine.sqf
- Title.
- Close #8986.
- Formatting.
> CSW - Fix loading with ammo from vehicle cargo

- optionals/compat_sog/CfgVehicles/turrets.hpp
Fixed an issue preventing the M1919A6 from being disassembled back into it's gun-bag form once it's been placed.
> SOG Compat - Fixed an issue preventing the M1919A6 from being disassembled

- addons/captives/functions/fnc_findEmptyNonFFVCargoSeat.sqf
- reverse the list of steats for loading captives
> Captives - Change load captives seats list order so captives are first loaded in the back

- optionals/compat_rhs_usf3/CfgAmmo.hpp
- Add missing `ace_rearm_caliber` attribute to `rhs_ammo_30x173mm_GAU8_mixed`
Fix https://github.com/acemod/ACE3/issues/8860
> RHSUSF Compat - Fix A-10A 30mm 5:1 DU:HEI mag rearm

- AUTHORS.txt
- addons/cargo/functions/fnc_unloadCarryItem.sqf
- addons/cargo/initSettings.sqf
- addons/cargo/stringtable.xml
- Add a setting to disable automatically carrying/dragging cargo on unload
> Cargo - Add setting for carry after cargo unload

- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/script_component.hpp
- _Randomize the delay from start of cookoff and ammunition detonation_
Something I've noticed with cookoff is in certain circumstances almost at the exact same time that a vehicle is hit with AT you'll hear the ammo detonation cookoff sound effects, this seems quite odd as you'd expect the hit to have a short delay of 1+ seconds before the ammo would even begin to cookoff, give it a bit of time to for the "fire" to be lit.
I'm open to more modular ways to handle this (as cookoff in general isn't very tweakable at runtime)
> Cookoff - Randomized the delay from start of cookoff and ammunition detonation

- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_cookOff.sqf
- Fix cookoff effects cleanup not working in a dedicated environment
Previous method assumed the vehicle entity would still exist by the time the CBA global event was received by clients but in testing it becomes NULL and the local effects variables are unable to be retrieved.
Refactor switches to adding the Deleted EH on globally when a cookoff occurs and the EH triggers a local event for cleanup allowing for use of vehicle entity and access to the local effects variable stored on the vehicle.
> Cookoff - Tweaked effects cleanup to work in dedicated environment

- addons/arsenal/XEH_PREP.hpp
- addons/arsenal/XEH_postInit.sqf
- addons/arsenal/XEH_preInit.sqf
- addons/arsenal/functions/fnc_addDefaultLoadout.sqf
- addons/arsenal/functions/fnc_buttonExport.sqf
- addons/arsenal/functions/fnc_buttonImport.sqf
- addons/arsenal/functions/fnc_buttonLoadoutsLoad.sqf
- addons/arsenal/functions/fnc_buttonLoadoutsRename.sqf
- addons/arsenal/functions/fnc_buttonLoadoutsSave.sqf
- addons/arsenal/functions/fnc_fillLoadoutsList.sqf
- addons/arsenal/functions/fnc_getLoadout.sqf
- addons/arsenal/functions/fnc_onArsenalClose.sqf
- addons/arsenal/functions/fnc_onArsenalOpen.sqf
- addons/arsenal/functions/fnc_verifyLoadout.sqf
- addons/arsenal/missions/Arsenal.VR/XEH_postInit.sqf
- addons/arsenal/missions/Arsenal.VR/initPlayerLocal.sqf
- addons/arsenal/stringtable.xml
- addons/common/XEH_postInit.sqf
- addons/gunbag/XEH_preInit.sqf
- addons/headless/XEH_postInit.sqf
- addons/headless/functions/fnc_transferGroups.sqf
- addons/hearing/XEH_postInit.sqf
- addons/respawn/functions/fnc_handleKilled.sqf
- addons/respawn/functions/fnc_restoreGear.sqf
- docs/wiki/framework/arsenal-framework.md
Doesn't require this, it is compatible before and after the CBA PR is merged. There is an if statement that can be removed after the linked CBA PR is merged.
- https://github.com/CBATeam/CBA_A3/pull/1548
- Add earplugs to CBA extended loadouts
- Add gunbag weapon to CBA extended loadouts
- Add face and speaker to loadouts saved in the ACE arsenal (default off)
- Add insignia to loadouts saved in the ACE arsenal (default on)
- Respawn keep gear uses CBA extended loadouts
- Headless naked fix uses CBA extended loadouts (not sure about this one, may not be needed)
<details>
<summary>Settings Changes</summary>
</details>
> Common - Add CBA extended loadout

- addons/medical_blood/XEH_preInit.sqf
- addons/medical_blood/XEH_preStart.sqf
- addons/medical_blood/functions/fnc_handleWoundReceived.sqf
- addons/medical_damage/ACE_Medical_Injuries.hpp
- docs/wiki/framework/medical-framework.md
- title
- Added `noBlood` config param to the damageTypes configs in ACE_Medical_Injuries
- Docs
> Medical - Disable blood spurts for fire, burn and drown damage types

- addons/towing/XEH_PREP.hpp
- addons/towing/XEH_preInit.sqf
- addons/towing/functions/fnc_addRopeToVehicle.sqf
- addons/towing/initSettings.sqf
- addons/towing/stringtable.xml
- add setting to add rope to all `Car` and `Tank` vehicles inventory.
Cars get 6m rope; tanks, APCs and trucks get 12m rope. There is `ace_cargo_hasCargo` config value check to handle all those quadbike/cart/etc vehicles.
Setting needs restart only on disabling.
Not completely sure about:
- default setting value (enabled now);
- setting category (`Logistics` now, can be `Vehicles`);
- should add caching for vehicle classes (I don't think it's worth it);
At least some CUP trucks have `Car_F` parent instead of `Truck_F` so they get 6m rope but I don't think it's a big problem.
> Towing - Add rope to vehicle inventory

- addons/goggles/config.cpp
- addons/goggles/functions/fnc_applyGlassesEffect.sqf
- Flip the Enoch `G_AirPurifyingRespirator_*` and `G_RegulatorMask_F` overlays according to their `RcsTitles` angle
Close https://github.com/acemod/ACE3/issues/8127
> Goggles - Fix APR and Regulator mask overlays being flipped

- addons/trenches/ACE_Arsenal_Stats.hpp
- addons/trenches/CfgWeapons.hpp
- addons/trenches/README.md
- addons/trenches/XEH_PREP.hpp
- addons/trenches/XEH_preInit.sqf
- addons/trenches/XEH_preStart.sqf
- addons/trenches/config.cpp
- addons/trenches/functions/fnc_canCamouflageTrench.sqf
- addons/trenches/functions/fnc_canContinueDiggingTrench.sqf
- addons/trenches/functions/fnc_canDigTrench.sqf
- addons/trenches/functions/fnc_canRemoveTrench.sqf
- addons/trenches/functions/fnc_continueDiggingTrench.sqf
- addons/trenches/functions/fnc_handlePlayerInventoryChanged.sqf
- addons/trenches/functions/fnc_hasEntrenchingTool.sqf
- addons/trenches/functions/fnc_removeTrench.sqf
- docs/wiki/framework/trenches-framework.md
> Trenches - Add modded Entrenching Tools support

- addons/field_rations/XEH_postInit.sqf
- addons/field_rations/functions/fnc_canRefillItem.sqf
- addons/field_rations/functions/fnc_consumeItem.sqf
- addons/field_rations/functions/fnc_getConsumableChildren.sqf
- addons/field_rations/functions/fnc_getRefillChildren.sqf
- addons/field_rations/functions/fnc_refillItem.sqf
- docs/wiki/framework/field-rations-framework.md
- Basic support of CfgMagazine items for field rations
- No additional features
Adding this so I can use CfgMagazines SOG:PF food props with field rations. In the future, the system could be expanded with the feature of refilling/draining the magazine "rounds" (eg. SOG:PF food mags have 100 "rounds" each)
> Field Rations - Basic CfgMagazines support

- docs/wiki/framework/cargo-framework.md
- docs/wiki/framework/events-framework.md
- Added missing "unload type" param from the Cargo Framework documentation.
> Docs/Cargo - Include missing "unload type" param

- optionals/compat_rhs_afrf3/CfgAmmo.hpp
- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- Add missing ballistic attributes for ammo: `rhs_B_545x39_7U1_Ball`, `rhs_B_762x39_U_Ball`, `rhs_B_9x39_SP5` and `rhs_B_9x39_SP6`
- Add missing barrel attributes for weapons: `rhs_weap_asval` and `rhs_weap_vss`
_Note: Values taken from various sources and extrapolated when data points were missing. Current values seems to be within the envelope when testing though, so I'm hoping best effort is better than nothing._
Fix #8940
> RHSAFRF Compat - Fix subsonic ammo ballistic attributes

- optionals/compat_rhs_afrf3/CfgWeapons.hpp
- Add hearing protection to 6M2, 6M2-1, 6B47 (6M2) and 6B47 (6M2-1)
> RHS AFRF Compat - Add hearing protection to 6M2 and 6B47

- addons/arsenal/missions/Arsenal.VR/XEH_postInit.sqf
- Shows attached objects when in the ACE Arsenal mission
Allows mods like <https://github.com/gruppe-adler/grad_slingHelmet/> using extended loadouts to appear correctly
> Arsenal - Show attached objects in arsenal mission

- addons/hearing/XEH_postInit.sqf
- addons/hearing/XEH_preInit.sqf
- Add `CBA_loadoutSet` event and `CBA_loadoutGet` event server and player side
> Hearing - Fix: CBA Extended Loadouts do not catch earplugs server side

- addons/cargo/CfgVehicles.hpp
- Updates both the V-44 Blackfish & Y-32 Xi'an VTOLs cargo sizes to fit the size of the vehicle.
- Blackfish is now at 20
- Xi'an is at 10.
Resolves #9031
> Cargo - Update VTOL Cargo sizes

- addons/fastroping/CfgVehicles.hpp
- title, previously when the helper was destroyed it would create an explosion
> Fastroping - Disable destruction for helper object

- optionals/compat_rhs_afrf3/CfgVehicles.hpp
- Adds viewports support for all BMP3s, model wise they are the same for view ports positions
video:
https://imgur.com/a/Zg85Rju
> Viewports - Add viewports for RHS BMP3

- addons/refuel/CfgVehicles.hpp
- Fix macro and access property in refuel addon causing warnings with latest pboProject
> Refuel - Fix warnings when building with latest pboProject

- docs/wiki/framework/fortify-framework.md
- Fortify states there is only `description.ext` and code methods, config is also an option.
- Changed `myMissionObjects` to `TAG_MyPreset`
> Documentation - Expand fortify to include config

- addons/safemode/functions/fnc_lockSafety.sqf
- addons/safemode/functions/fnc_setWeaponSafety.sqf
- addons/safemode/functions/fnc_unlockSafety.sqf
- Adds an optional flag (to public fnc) to suppress the hint for safety on/off
I figure a lot of peoples frameworks use this fnc to auto-safety weapons at game start and it's just one less pop up to have. It defaults to true and works with the arg omitted so shouldn't impact any existing missions or change current behaviour.
> Safety - Add optional flag to hide hint

- addons/parachute/functions/fnc_showAltimeter.sqf
Bug fix
CBA_fnc_removePerFrameEventHandler was used to remove the calculations for the altimeter, but does not exist. Replaced with CBA_fnc_removePerFrameHandler to rectify this issue.
- Fix a bug with the perframehandler never being removed.
> Parachute - Fix Broken Altimeter PerFrameHandler removal

- addons/arsenal/functions/fnc_fillRightPanel.sqf
- Fix the use of the loop variable `_x` in a function and instead use the local variable holding the same value
> Arsenal - Fix non-local loop variable use in fnc_fillRightPanel.sqf

- optionals/compat_ws/$PBOPREFIX$
- optionals/compat_ws/CfgWeapons.hpp
- optionals/compat_ws/config.cpp
- optionals/compat_ws/script_component.hpp
- Add a compatibility addon for the Western Sahara CDLC
- Mostly just adds ballistics values to weapons and hearing protection to helmets that need it.
- Sidenote: the XMS rifles are a weird off-shoot of the XM8 rifles and there is no data to use for barrel lengths, compared to the vanilla CTAR it's around the same length barrel so the values are matched from that.
> Western Sahara Compatibility

- docs/wiki/development/setting-up-the-development-environment.md
- Fix the wrong foldername that the CBA files are located in
> Documentation - Fixed wrong CBA location

- addons/zeus/functions/fnc_moduleGarrison.sqf
- Fix an edge case where garrisoning a group with player units would cause the players to involuntarily disembark their vehicles.
> Zeus - Fix group players disembarking on garrison module

- addons/quickmount/functions/fnc_canShowFreeSeats.sqf
- Fix an bug where you could teleport to an  UAV with an free seat, through the change seat action while controlling it with the UAV terminal (for example the UGV Stomper).
> Quickmount - Fix teleport bug in UAV through change seat

- addons/common/functions/fnc_disableUserInput.sqf
- title, would cause mouse to flicker and the respawn button could not be clicked
- Close #9043
> Common - Fix disableUserInput blocking respawn

- addons/medical_blood/XEH_postInit.sqf
- addons/medical_blood/functions/fnc_createBlood.sqf
- addons/medical_blood/functions/fnc_onBleeding.sqf
- addons/medical_blood/functions/fnc_spurt.sqf
> Medical Blood - Add source of blooddrop to events

- addons/weaponselect/XEH_postInit.sqf
ref https://github.com/acemod/ACE3/issues/5591#issuecomment-334680323
I don't think this keybind makes sense any more
There is a dedicated vanilla counter-measure keybind that works
I think the game used to require you to select "smoke" as a weapon but that isn't the case anymore??
the while loop https://github.com/acemod/ACE3/blob/master/addons/weaponselect/functions/fnc_fireSmokeLauncher.sqf#L34
never exits normally, and only continues when it hits the 10k limit
> Weapon Select - Remove vehicle smoke selection key

- addons/common/functions/fnc_progressBar.sqf
- _Due to the way the map control works we have to manually call into CBA to hook eventhandlers onto the display to work_
> Common - Fixed CBA keybinds not working with progress bar

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_getFiremodeIndex.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/dragging/functions/fnc_startCarry.sqf
- Improve weapon reselect behaviour when dropping carried objects
- Previously, this would always reselect the primary weapon but now reselects whatever weapon (or none) was held when carrying was started
> Dragging - Improve weapon reselect behaviour

- addons/refuel/functions/fnc_initSource.sqf
- addons/refuel/functions/fnc_makeJerryCan.sqf
- addons/refuel/functions/fnc_makeSource.sqf
- docs/wiki/framework/refuel-framework.md
- Add ´ace_refuel_fuelSourceInitialized´ and `ace_refuel_jerryCanInitalized´ events
- Update documentation accordingly
Depending on whether this or #9122 get merged first, the documentation of the other needs to be updated.
Analog to #9134
> Refuel - Add events for fuel source and jerry can creation

- addons/rearm/functions/fnc_makeSource.sqf
- docs/wiki/framework/rearm-framework.md
Add ´ace_rearm_sourceInitialized´ event
Update documentation accordingly
Depending on whether this or https://github.com/acemod/ACE3/pull/9114 get merged first, the documentation of the other needs to be updated.
Analog to #9133
> Rearm - Add event for rearm source creation

- addons/medical_status/functions/fnc_initUnit.sqf
- Reset `causeOfDeath` and `lastWakeUpCheck` on respawn
Because `causeOfDeath` was only reset locally, letting AI take over a unit after it respawned caused the `causeOfDeath` on the server being the new truth, which persisted even when reslotting as that unit. This in turn caused `fnc_enteredStateDeath` to fail and exit early. TBH, that [`exitWith`](https://github.com/acemod/ACE3/blob/master/addons/medical_statemachine/functions/fnc_enteredStateDeath.sqf#L19) seems unnecessary to me, but I don't know what the original intention was. I think `setDead` should always be called.
> Medical - Fix respawn when letting AI take over playable units

- addons/casings/functions/fnc_createCasing.sqf
- Add missing vanilla shell casing models.
Most noticeable with 7.62x39, where they swap from steel to brass casings on landing.
> Casings - Add missing vanilla casing types

- docs/wiki/framework/rearm-framework.md
- Add documentation about how to use `ace_rearm_fnc_makeSource` to create rearm source object at runtime
- Removed outdated/wrong note
- Unify terminology and improve ordering
I've guessed the version (3.12.5) from which on it was included in ACE from the date it was committed and then took the next ACE release from the milestones. So if someone has a better way of determining that, lemme know. From looking at the logs it might also have been 3.12.3.
I also tried to mirror how it's documented for `refuel` as much as possible, since it's been copied from there anyway, but the points on each page are not in the same order and putting it at the bottom like in `refuel` would have disconnected it from the config way of setting it up. I guess this could …
> Rearm - Improve framework documentation

- optionals/compat_gm/XEH_preinit.sqf
- title
- handle additional insignia and player/character name on the front pocket
GM does it like this:
```sqf
[missionNamespace, "arsenalClosed", {player call gm_core_characters_fnc_updateUniformDetails}] call bis_fnc_addScriptedEventhandler;
```
> Arsenal - GM Compat - Add uniform details support

- addons/viewdistance/functions/fnc_changeViewDistance.sqf
- Fix setting viewdistance to videosettings viewdistance
Close https://github.com/acemod/ACE3/issues/7611
***NOTE*** Utilizes new `getVideoOptions` command in `2.12`
> View Distance - Fix viewdistance from video settings

- addons/fortify/ACEX_Fortify_Presets.hpp
- addons/fortify/functions/fnc_addActions.sqf
- addons/fortify/functions/fnc_getPlaceableSet.sqf
- addons/fortify/functions/fnc_registerObjects.sqf
- addons/fortify/stringtable.xml
- docs/wiki/framework/fortify-framework.md
> Fortify - Categories

- addons/respawn/functions/fnc_updateRallypoint.sqf
initRallypoint calls `["ace_rallypointMoved", [_rallypoint, _side]] call CBA_fnc_globalEvent;`
which calls `ace_respawn_fnc_updateRallypoint` but it's missing 3rd arg
causes (in spawned code) `Error Undefined variable in expression: _position`
> Respawn - fix script error

- addons/maptools/functions/fnc_handleMouseButton.sqf
- Use polyline instead of rectangular marker for drawing straight lines
> Map Tools - Use polyline marker for straight lines

- addons/medical_gui/stringtable.xml
- _Replace "Caebça" with "Cabeça", the correct translation of "head"_
> Medical GUI - Fix portuguese translation of "head"

- addons/common/functions/fnc_getTurretConfigPath.sqf
cwr british fv4030
```
class Turrets: Turrets {  
particlesPos = "usti hlavne"; 
particlesDir = "konec hlavne"; 
class CommanderOptics: CommanderOptics {
```
`["cwr3_b_uk_fv4030", [0,0]] call BIS_fnc_turretConfig` 
returns `bin\config.bin/CfgVehicles/cwr3_challenger1_base/Turrets/MainTurret/Turrets/particlesPos`
should be `bin\config.bin/CfgVehicles/cwr3_challenger1_base/Turrets/MainTurret/Turrets/CommanderOptics`
`BIS_fnc_turretConfig` and `ace_common_fnc_getTurretConfigPath` both parse it wrong and ends up causing
```
Warning Message: 'particlesDir/' is not a class ('ace_fcs_Enabled' accessed)
```
I think the config is bad but `CBA_fnc_getTurret` handles it right 
and is slightly faster (0.018 vs 0.012) so I don't see any reason not to switch over
ref …
> Common - switch getTurretConfigPath to use cba func

- addons/xm157/XEH_postInit.sqf
`EFUNC(common,getMapData)` can return `[]`
> xm157 - Fix latitude calc for maps not in `getMapData`

- .github/workflows/arma.yml
- .github/workflows/extensions.yml
- .hemtt/project.toml
- docs/wiki/development/setting-up-the-development-environment.md
- tools/setup.bat
- Add setup script that installs a specific version of HEMTT to the local project
- Works in combination with `build.bat` in root.
- Document HEMTT setup and builds.
> Add HEMTT setup script for Windows and document HEMTT use

- addons/interaction/functions/fnc_openDoor.sqf
Fix #9143
e.g. land_gm_euro_house_11_wL
```
_door = "door_01"; // from getDoor
class openDoor_1 {
condition = "this animationSourcePhase 'door_1_sound_source' <= 0.5";
statement = "([this, 1, 1] call BIS_fnc_Door);";
```
bis_fnc_door checks
```
// _door is a number
if ((_structure getVariable [format ["bis_disabled_Door_%1", _door], 0]) != 1) 
```
so if we get a "door_0X" then we just check both vars
> Interaction - Fix opening locked doors for GM buildings

- addons/scopes/CfgWeapons.hpp
- addons/scopes/dev/checkScopes.sqf
- addons/xm157/CfgWeapons.hpp
I think this is close but could use another look, I'm not positive the results are correct
```
** Checking 67 scopes **
Mismatch optic_MRD - Actual 1.94867 vs Config 2.8
ACO[0.25] = eye (1.94867)
Mismatch optic_MRD_black - Actual 1.94867 vs Config 2.8
ACO[0.25] = eye (1.94867)
** Checking 103 weapons **
Mismatch LMG_Zafir_F - Actual 1.12161 vs Config 0.996651
Muzzle [-0.517082,4.34779e-005,0.0894913] - Top [0.123988,-0.00138879,0.100707]
Mismatch arifle_SPAR_01_blk_F - Actual 2.96535 vs Config 3.20768
Muzzle [-0.335041,6.07815e-005,0.061947] - Top [-0.000982652,2.00588e-005,0.0916006]
```
> Scopes - Add tool to diagnose scope height

- addons/towing/functions/fnc_startTow.sqf
- addons/towing/functions/fnc_towStateMachinePFH.sqf
Adds a tow rope deploy event.
Adds a tow rope deploy cancel event.
Antistasi currently needs these events for removing undercover mode for towing. 
- ropeDeployed event:
params:
<object>_unit - unit that deployed the ropes/ started towing
<object> _target  - target object for towing
<string> _ropeClass - rope className
- ropeDeployedCanceled event:
params:
<object>_unit - unit that deployed the ropes/ started towing
<string> _ropeClass - rope className
> Towing - Add CBA event for towing start and cancel

- addons/explosives/XEH_postInit.sqf
- docs/wiki/framework/explosives-framework.md
ref https://github.com/acemod/ACE3/pull/9171#issuecomment-1495046739
I don't think this needs an actual setting, setVar should be fine imho
> Explosives - Add getVar to disable setShotParents

- addons/explosives/functions/fnc_setupExplosive.sqf
- docs/wiki/framework/events-framework.md
- Add an event to the "fnc_setupExplosive" for when an explosive is successfully placed down.
Currently, the "ace_explosives_place" event only triggers when a "trigger" is added to the explosive. This adds an event that passes in the placed explosive's vehicle, the mag class and the unit that placed the explosive.
Personally, the current event should be renamed and this one should be named "place" however, to avoid fallout with other mods that depend on this one, I've simply created a new one to keep the two separate and not cause other mods to need to be updated.
> Explosives - Add "ace_explosives_setup" CBA Event

- addons/hearing/CfgAmmo.hpp
- addons/hearing/config.cpp
**When` merged this pull request will:**
- Remove outdated 2015 `B_127x108_Ball` `audibleFire = 15;`.
All 12.7x99 and 108mm have now an `audibleFire=120;`.
Probably missed something but that makes sense to keep `15` only for 12.7x108 ammunitions ?
> Hearing - Remove outdated 12.7x108mm audibleFire value

- addons/atragmx/functions/fnc_initGunList.sqf
- addons/ballistics/CfgAmmo.hpp
- addons/ballistics/CfgWeapons.hpp
- Update 12.7x108mm `ACE_muzzleVelocities` according to `5Rnd_127x108_Mag` `initSpeed` 820 m/s (ASM standard conditions).
- AtragMx preset 12.7x108mm: Fix `airFriction`, update `Scope Base Angle` and `Muzzle Velocities vs. Temperature Interpolation` .
AtragMx GunList will need to be refreshed with the Eden Editor Debug Console, execute:
- `call ace_atragmx_fnc_clear_user_data` (LOCAL EXEC)
or
- `call ace_atragmx_fnc_initGunList` (LOCAL EXEC)
**/!\ All private AtragMx GunList values must be saved manually before.**
> Ballistics - Improve B_127x108_Ball values

- addons/dragging/XEH_postInit.sqf
- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/dragging/script_component.hpp
- allowing carried object to be loaded into vehicle by key or mouse
- carrying mouse hint updates to show possibility of loading
- dragging behaviour is not modified due to need to to move backwards and thus not immediately looking toward target vehicle
- https://youtu.be/hVRH48DeybQ
> Dragging - Improve carrying by allowing carried object to be loaded into vehicle by key or mouse

- addons/common/functions/fnc_addToInventory.sqf
- Replace [addMagazineCargoGlobal](https://community.bistudio.com/wiki/addMagazineCargoGlobal) with [addItemToUniform](https://community.bistudio.com/wiki/addItemToUniform)/[addItemToVest](https://community.bistudio.com/wiki/addItemToVest)/[addItemToBackpack](https://community.bistudio.com/wiki/addItemToBackpack) when adding magazines to units to make added throwables throwable.
- Closes #9185.
> Common - Fix added throwables not being throwable

- addons/logistics_wirecutter/functions/fnc_isFence.sqf
- Change the behavior of `ace_logistics_wirecutter_fnc_isFence` to check the `FENCE_P3DS` list even if `isFence` is unset (or set to 0) in the object's config.
- It seems unlikely that `isFence` would get set to 0 on an object _and_ its model would be added to `FENCE_P3DS`. We don't even explicitly set this value to 0 anywhere anyways...
closes https://github.com/acemod/ACE3/issues/9165
> Logistics Wirecutter - Check if fence model is in `FENCE_P3DS` even if config check fails.

- addons/medical_engine/XEH_postInit.sqf
Issue:
```
class class CAManBase: Man {
class Reflectors {
class CustomLight_1 {
hitpoint         = "Light";
```
will cause
```
getAllHitPointsDamage player param [0, []]; ->
[..."hitrightleg","ace_hdbracket","#light"]
```
and break medical completely, this pr should at least allow medical to add the EH and the results seem normal
But I'm not really sure if this is a good fix, I don't have much experience working with `class Reflectors`
> Medical Engine - Ignore Reflector Hitpoints

- addons/vehicle_damage/functions/fnc_handleDamage.sqf
- _Change damage handling get the overall damage from the vehicle if the hit selection is blank_
**Repro steps**
Using `CUP_B_BMP2_CZ` for testing, some observations: 
- I can drive full-speed into pretty much anything without consequence, very rarely take a wound from a head-on collision with a tree, rock, or building 
- Those collisions will cause track damage usually, but they also damage the front lights (#l svetlo/#p svetlo)
- At some point after enough collisions I'll start taking damage, sometimes quite catastrophically, sometimes less so
I iterated on all kinds of different damage combinations and eventually discovered what seems to be one cause (I'm sure the logic means it applies in other ways as well): 
- If those front lights mentioned …
> Vehicle Damage - Fix blank hit selections resulting in absurd damage to the driver

- addons/javelin/functions/fnc_onOpticDraw.sqf
>load an AT missile and switch to top-down, then reload an AP missile, you can't de-activate top-down mode and the missile guidance stops working for the AP missile
happens in vanilla, but it's something we can easily fix???
issue https://feedback.bistudio.com/T171012
> Javelin - Fix weapon being in top-attack when loading AP magazine

- addons/vehicles/XEH_PREP.hpp
- addons/vehicles/XEH_postInit.sqf
- addons/vehicles/functions/fnc_autoThrottle.sqf
- addons/vehicles/functions/fnc_speedLimiter.sqf
- addons/vehicles/functions/fnc_toggleSpeedControl.sqf
- add `Set`/`Resume` functionality on `Speed-`/`Speed+` keys (like `SET-`/`RES+` buttons)
- make `Autothrottle` work for UAV planes
- fix `Autothrottle` not working for copilots
- fix speed control for UGV gunner
- disable speed control activating if engine is off
- disable speed control activating in UAV when map is opened
- disable CC activating if speed < 1 (stopped or moving backward)
- disable speed control when `Feature Camera` starts (`Zeus`, `Splendid Camera`, etc.)
`Speed Control` means `Cruise Control` and `Speed Limiter` here.
I don't know if it's worth touching setting strings. I would just add ` / Resume` to `<English>Increase Speed Limit</English>` line but not for other languages. Deleting them would be rude to translators. Commenting …
> Vehicles - Add Resume/Set functionality to speed control

- addons/repair/initSettings.sqf
> Repair - Move to separate settings menu

- addons/field_rations/CfgWeapons.hpp
- addons/field_rations/XEH_PREP.hpp
- addons/field_rations/XEH_postInit.sqf
- addons/field_rations/XEH_preInit.sqf
- addons/field_rations/XEH_preStart.sqf
- addons/field_rations/functions/fnc_scanFieldRations.sqf
- addons/field_rations/script_component.hpp
- docs/wiki/framework/field-rations-framework.md
- Title.
Same deal as #9220. This also caches the items in UI namespace in case anyone wants to take a crack at reducing the footprint on `fnc_createConsumableChildren` and `fnc_consumeItem`. I tried but I don't want more migraines today.
> Field Rations - Add arsenal category

- addons/medical_treatment/CfgWeapons.hpp
- addons/medical_treatment/XEH_PREP.hpp
- addons/medical_treatment/XEH_postInit.sqf
- addons/medical_treatment/XEH_preInit.sqf
- addons/medical_treatment/XEH_preStart.sqf
- addons/medical_treatment/functions/fnc_scanMedicalItems.sqf
- addons/medical_treatment/script_component.hpp
- docs/wiki/framework/medical-treatment-framework.md
- Add "ACE Medical" category to ACE Arsenal through API function
Contains all items in ACE_Medical_Treatment_Actions, compatible with third party mods that add medical items (OPTRE, KAM (though not all items from KAM are added apparently? This should be fixed on their end with API)). Should clean up Misc Items a bit.
Uses Medical GUI icon if that's available. Vanilla medical icon is ugly.
See also #9221.
> Medical - Add arsenal category

- addons/medical_treatment/functions/fnc_surgicalKitProgress.sqf
- Title.
Early exit meant callbackSuccess wasn't called and Medical Menu wouldn't reopen. Suture consumption remains unchanged.
> Medical Treatment - Remove early exit when stitching with sutures

- addons/medical/functions/fnc_deserializeState.sqf
- Handle wound hashmaps being deserialized as CBA_namepsaces in medical deserialization
- Fixes #9244 
*Note*
- This has the least surface area of changes
- I also have a version where `[_json, 2] call CBA_fnc_parseJSON` is used, which creates native hashmaps instead of CBA_namespaces for the deserialized object types, however this also required updating every state read and using `toLower` for the keys as hashmap keys are [case sensitive](https://community.bistudio.com/wiki/get#:~:text=key%3A%20HashMapKey%20%2D-,Case%20sensitive%20key,-Return%20Value%3A) and the serialization produces all lower case keys
- Let me know if that [version](https://github.com/tbeswick96/ACE3/commit/ffc5acafcd9f6124e4739b257b1ec32fb8166da6) would be preferred and I'll …
> Medical - Fix wound hashmaps deserialized as CBA_namespaces

- addons/logistics_wirecutter/CfgWeapons.hpp
- addons/logistics_wirecutter/XEH_postInit.sqf
- addons/logistics_wirecutter/XEH_preStart.sqf
- addons/logistics_wirecutter/script_component.hpp
Enable child classes of ACE_wirecutter to have the same functionality.
> Logistics Wirecutter - Add modded class support

- addons/gunbag/XEH_preInit.sqf
- [This](https://github.com/acemod/ACE3/blob/ab2207924f6311fcb15dd6372cccc27ca1db682d/addons/gunbag/XEH_preInit.sqf#L38) line overwrites the gunbag that was loaded within the arsenal using `CBA_fnc_setLoadout`. This PR fixes this issue.
> Gunbag - Fix arsenal caching conflicting with CBA_fnc_setLoadout

- addons/dragging/functions/fnc_canCarry.sqf
- addons/dragging/functions/fnc_canDrag.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- Change the limping damage threshold in `FUNC(canCarry)` and `FUNC(canDrag)` to use the actual point at which a unit starts limping.
- Add a check for carrier limping `FUNC(carryObjectPFH)`. Previously if the carrier started limping after picking up an object they wouldn't drop it.
> Dragging - Add limping check to carrier and improve limping check for target unit

- addons/mk6mortar/CfgWeapons.hpp
- Title.
Removing the burst modes breaks `doArtilleryFire` and AI firing the weapon. No reason to do that anymore as we just replace the whole weapon.
I don't know how many issues this closes. Probably a few. I'll track them down later.
> Mk6 Mortar - Fix AI firing and doArtilleryFire

- addons/overpressure/functions/fnc_firedEHBB.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- Title.
- If you go into the ACE arsenal mission and fire the MAAWS with some of the virtual blocks/barriers to your back, you will take backblast damage. This PR addresses such unintended behaviour.
- Includes some very minor cleanup.
> Overpressure - Fix invulnerable units taking backblast damage when firing launchers

- addons/arsenal/missions/Arsenal.VR/XEH_postInit.sqf
- addons/arsenal/missions/Arsenal.VR/fnc_createTarget.sqf
fix 
```
Trying to add inventory item with empty name to object [VR Entity]
âž¥ Context: 	[] L18 (z\ace\addons\arsenal\missions\Arsenal.VR\initPlayerLocal.sqf)
[] L17 (z\ace\addons\arsenal\missions\Arsenal.VR\initPlayerLocal.sqf)
[] L55 (z\ace\addons\arsenal\missions\Arsenal.VR\fnc_createTarget.sqf)
```
and
```
Trying to add inventory item with empty name to object [VR Entity]
âž¥ Context: 	[] L1 ()
[] L20 (z\ace\addons\arsenal\functions\fnc_onArsenalClose.sqf)
[] L27 (x\cba\addons\events\fnc_localEvent.sqf)
[] L27 (x\cba\addons\events\fnc_localEvent.sqf)
[] L27 (x\cba\addons\events\fnc_localEvent.sqf)
[] L118 (z\ace\addons\arsenal\missions\Arsenal.VR\XEH_postInit.sqf)
[] L96 (z\ace\addons\arsenal\missions\Arsenal.VR\XEH_postInit.sqf)
```
unrelated to anything recent
this might only show …
> Arsenal - Fix adding inventory item with empty name to dummies

- addons/common/stringtable.xml
- addons/dragging/XEH_postInit.sqf
- addons/dragging/config.cpp
- addons/dragging/functions/fnc_canCarry.sqf
- addons/dragging/functions/fnc_canDrag.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- The improvement part of https://github.com/acemod/ACE3/pull/9269, plius a third one (last in the list below).
1. Makes `ace_dragging` depend on `ace_cargo`. There are functions and stringtable entries from `ace_cargo` that are called, see [here](https://github.com/acemod/ACE3/blob/aead9a8eb4949714ddcb5d7b07b57f0c798a4ea0/addons/dragging/functions/fnc_dropObject_carry.sqf#L105), [here](https://github.com/acemod/ACE3/blob/aead9a8eb4949714ddcb5d7b07b57f0c798a4ea0/addons/dragging/functions/fnc_carryObjectPFH.sqf#L61) and [here](https://github.com/acemod/ACE3/blob/aead9a8eb4949714ddcb5d7b07b57f0c798a4ea0/addons/dragging/functions/fnc_carryObjectPFH.sqf#L65). If `ace_dragging` isn't supposed to be dependent on `ace_cargo`, then `ace_dragging` will need …
> Dragging - Fix unintended Cargo dependency and improve ragdoll/disconnection handling

- addons/common/XEH_postInit.sqf
- addons/medical_gui/CfgVehicles.hpp
- addons/medical_treatment/functions/fnc_unloadUnit.sqf
- Title.
- Change one string comparison to `isNotEqualTo`.
- Change Medical's "Load Patient" interaction to only show if there is a vehicle nearby.
- Allow using Medical's "Unload Patient" interaction on dead units.
- Close #8001.
Behavior is maintained. Ref https://github.com/acemod/ACE3/pull/7959#issuecomment-1646452185.
> Common/Medical - Change `vehicle` checks to `objectParent`

- addons/common/functions/fnc_loadPersonLocal.sqf
- Close #9257.
- Fix script error when loading captive/unconscious patient into a FFV cargo seat.
Side-effect: unconscious enemies can and will fire upon waking up in an FFV seat.
> Common - Fix loading units into FFV cargo seats

- addons/interact_menu/functions/fnc_keyDown.sqf
- Fix losing ability to interact if you close the map while having an open notepad from Intel Items
> Interact Menu - Ignore text controls from invisible map

- addons/dragging/XEH_postInit.sqf
- When a unit is taken captive or surrenders, the unit is forced to drop dragged/carried objects.
> Dragging - Add handling of captivity when dragging/carrying

- addons/main/script_macros.hpp
- addons/repair/CfgVehicles.hpp
- addons/repair/functions/fnc_getHitPointsToIgnore.sqf
- Fix bug in detection for ignoring repair hitpoints
> Repair - Fix bug in detection for ignoring hitpoints

- addons/arsenal/functions/fnc_onSelChangedRight.sqf
- addons/arsenal/functions/fnc_replaceUniqueItemsLoadout.sqf
- Fix script error when saving a loadout with a weapon in a container.
- Readd magazine refill when clicking on equipped magazine in arsenal.
Missed while testing #9040.
> Arsenal - Fix #9040 bugs/regressions

- addons/arsenal/ACE_Arsenal_Stats.hpp
- addons/arsenal/XEH_PREP.hpp
- addons/arsenal/functions/fnc_statTextStatement_binoMag.sqf
- addons/arsenal/functions/fnc_statTextStatement_binoVisionMode.sqf
- addons/arsenal/functions/fnc_statTextStatement_magCount.sqf
- addons/arsenal/functions/fnc_statTextStatement_scopeMag.sqf
- addons/arsenal/stringtable.xml
- addons/ballistics/ACE_Arsenal_Stats.hpp
- addons/nightvision/ACE_Arsenal_Stats.hpp
- addons/nightvision/XEH_PREP.hpp
- addons/nightvision/config.cpp
- addons/nightvision/functions/fnc_statTextStatement_NVGeneration.sqf
- addons/nightvision/stringtable.xml
- Add magnification stat for binoculars.
- Improve magnification stat for optics: shows magnification range of primary optic mode if detected, otherwise minimum and maximum magnification between all optics modes.
- Add vision mode stat for binoculars and NVGs.
- Add night vision generation stat for NVGs.
- Add ammo count stat for magazines.
- Improve conditions on ballistics stats.
> Arsenal - Add and Improve stats

- addons/logistics_wirecutter/ACE_Arsenal_Stats.hpp
- addons/logistics_wirecutter/config.cpp
- addons/trenches/ACE_Arsenal_Stats.hpp
- Title.
- The config is based off of the entrenching tool stat.
- Brought macro usage to entrenching tool stat (seeing as this PR was based off of the entrenching tool stat).
> Logistics wirecutter - Add wirecutter stats to ACE arsenal

- addons/advanced_fatigue/functions/fnc_mainLoop.sqf
- Previously, muscle damage could go above 1 and [cause issues with stamina calculation](https://github.com/acemod/ACE3/blob/628d62d329a7550053c359bcb7c8ced2c6eba2e7/addons/advanced_fatigue/functions/fnc_mainLoop.sqf#L42). Realistically this could probably never happen, as getting muscle damage up to 1 is quite a challenge, but I think it's best to be cautious nonetheless.
TODO: Implement muscle damage recovery, as it could technically pose a problem, although practically I don't know if it does.
I'm hoping to be able to fix advanced fatigue with high performance factor and recovery factor values, but so far I haven't had any luck in reproducing any errors. Any help is appreciated.
> Advanced Fatigue - Add cap to muscle damage

- addons/arsenal/functions/fnc_sortPanel.sqf
- Minor tweak to sorting, behaviour that was introduced by #9040.
> Arsenal - Tweaked sorting

- addons/csw/XEH_postInit.sqf
- Title.
`turretLocal` is used to check who handles the extra mags, but that returns true for all clients on Init, resulting in mags being multiplied by the number of players on the server.
> CSW - Fix mag multiplication in multiplayer

- addons/interaction/functions/fnc_joinTeam.sqf
- Title - `assignTeam` is global in Arma 3 and sync is fixed since Arma 3 v1.62 (ref. https://github.com/CBATeam/CBA_A3/pull/511)
> Interaction - Use `assignTeam` instead of deprecated CBA event

- AUTHORS.txt
- addons/nightvision/CfgWeapons.hpp
- addons/nightvision/config.cpp
- addons/nightvision/functions/fnc_pfeh.sqf
- addons/nightvision/functions/fnc_refreshGoggleType.sqf
- addons/nightvision/script_component.hpp
- addons/nightvision/stringtable.xml
- Adds White Phosphor NVGs in Gen3/Gen4/Wide.
- Direct continuation of #6190
- The original authors are credited in `authors.txt`
- Moved things to stringtable as requested in original PR.
- Used the alternative `colorPreset` provided in a comment on that PR in this one. (Comment mentions an issue with FFV, but not present on this.)
- both `colorPreset` are now defines.
- Issue mentioned with A3 Thermal Improvement I haven't reconfirmed, I don't use it.
- Close #6190 
Previews: (24 June, 2035 - 03:00)
> Nightvision - Add White Phosphor NVGs

- addons/fastroping/XEH_postInit.sqf
- addons/fastroping/config.cpp
- addons/fastroping/initSettings.sqf
- addons/fastroping/stringtable.xml
- docs/wiki/feature/fastroping.md
- docs/wiki/framework/fastroping-framework.md
Integrated ArmaForces/Mods component
- Integrate https://github.com/ArmaForces/Mods/tree/aaaa420df0fecc0ff996dbb5e92e1f9b629b5c57/addons/fries (https://github.com/ArmaForces/Mods/pull/40)
- Add "Auto add FRIES" setting which is just a global version of the per-object property.
- Streamline component name documentation (same as component now)
> Fastroping - Add Auto add FRIES setting

- addons/arsenal/XEH_PREP.hpp
- addons/arsenal/functions/fnc_addAction.sqf
- addons/arsenal/functions/fnc_addSort.sqf
- addons/arsenal/functions/fnc_buttonActionsPage.sqf
- addons/arsenal/functions/fnc_compileActions.sqf
- addons/arsenal/functions/fnc_compileSorts.sqf
- addons/arsenal/functions/fnc_compileStats.sqf
- addons/arsenal/functions/fnc_handleActions.sqf
- addons/arsenal/functions/fnc_removeAction.sqf
- addons/gunbag/ACE_Arsenal_Actions.hpp
- docs/wiki/framework/arsenal-framework.md
> Arsenal - Add arsenal actions addition and removal via functions

- addons/medical_status/XEH_PREP.hpp
- addons/medical_status/XEH_postInit.sqf
- addons/medical_status/functions/fnc_handleKilled.sqf
- addons/medical_status/functions/fnc_setStatusEffects.sqf
- addons/medical_status/functions/fnc_setUnconsciousState.sqf
- If a unit was unconscious and then died, they would have the `setHidden`, `blockRadio` and `blockSpeaking` status effects still applied. The first is not important, but the two others are, especially `blockSpeaking`, which (I believe) prevented spectators talking in the spectator view when using TFAR.
This PR reverses those status effects upon death.
Unsure if ACRE is affected in any negative way.
> Medical Status - Remove status effects upon death/featureCamera

- addons/weather/functions/fnc_calculateWindChill.sqf
> Weather - Fix number in `fnc_calculateWindChill.sqf`

- addons/nightvision/XEH_postInit.sqf
- addons/nightvision/functions/fnc_refreshGoggleType.sqf
fixes drones having player's nvg effects, really only noticeable in pilot view as it's zoomed out so much:
> Night Vision - Use default effects when controlling UAVs

- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_unloadUnitWeapon.sqf
- Previously, if you start unloading a weapon and switch to another, it will duplicate the magazine of the newly selected weapon. This is fixed with this PR.
- The unload action can be spammed, making it play the reload sounds as many times as the action was spammed.
- Previously, you could press the unload keybind in turrets. It would play the sound, but do nothing. This PR makes it so that you need to be able to use the weapon in order to unload it.
- Because of the fixes above, `ace_common_fnc_unloadUnitWeapon` now can take an additional argument: `_magazine`.
- Additionally, for the reloading sounds it also looks for files with the `.ogg` extension.
> Common - Improve weapon unloading

- addons/repair/functions/fnc_addRepairActions.sqf
- Title.
- Addresses https://github.com/acemod/ACE3/issues/8609.
I tested a bit with both Vanilla and RHS vehicles; the results are promising. The position for all interactions I tested was in the center of the wheel hub.
> Repair - Improve wheel repair interaction position

- addons/common/initSettings.sqf
- addons/laserpointer/initSettings.sqf
- addons/reload/CfgEventHandlers.hpp
- addons/reload/CfgVehicles.hpp
- addons/reload/XEH_PREP.hpp
- addons/reload/XEH_postInit.sqf
- addons/reload/functions/fnc_canCheckAmmo.sqf
- addons/reload/functions/fnc_canCheckAmmoSelf.sqf
- addons/reload/functions/fnc_checkAmmo.sqf
- addons/reload/functions/fnc_displayAmmo.sqf
- addons/reload/functions/fnc_getAmmoToLinkBelt.sqf
- addons/reload/functions/fnc_onTake.sqf
- addons/reload/functions/fnc_startLinkingBelt.sqf
- addons/reload/initKeybinds.sqf
- addons/reload/initSettings.sqf
- addons/reload/stringtable.xml
- addons/weaponselect/initSettings.sqf
- Title.
- Improvements/Changes:
- Previously, when linking a belt, a magazine was removed upon the action start from the unit's (who was trying to link) inventory and readded in case of failure. This PR changes it: It now only removes the magazine at the end of the progressbar upon successful completion. It will check if it was able to remove the magazine; if not, the interaction is cancelled.
- Upon completion or failure of a belt linking, a notification shows up. #9202 (or a follow-up PR) could be made to disable these notifications.
- Previously, there was some very specific behaviour concerning UGLs and checking of their ammo. This has been expanded to where if any secondary muzzle has no ammo left, it will show the number of compatible …
> Reload - Code cleanup and various improvements

- addons/reloadlaunchers/CfgEventHandlers.hpp
- addons/reloadlaunchers/CfgVehicles.hpp
- addons/reloadlaunchers/CfgWeapons.hpp
- addons/reloadlaunchers/XEH_PREP.hpp
- addons/reloadlaunchers/XEH_postInit.sqf
- addons/reloadlaunchers/config.cpp
- addons/reloadlaunchers/functions/fnc_addMissileReloadActions.sqf
- addons/reloadlaunchers/functions/fnc_canLoad.sqf
- addons/reloadlaunchers/functions/fnc_getLoadableMissiles.sqf
- addons/reloadlaunchers/functions/fnc_load.sqf
- addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- Title.
- Some changes :
- If a launcher has two muzzles, e.g. RHS SMAW, and if the secondary muzzle were loaded but not the first, you could not use the reload action. Same happened if the launcher had a magazine in the primary muzzle with 0 ammo in it. This PR makes it so that it only checks the primary muzzle and checks if the ammo is 0.
- The compatible magazines check did not check for magazines in magwells. This PR adds support for magwells.
The changes were included in this PR because I deemed them to be relatively small.
> Reload Launchers - Code cleanup

- addons/reload/functions/fnc_checkAmmo.sqf
- addons/reload/functions/fnc_getAmmoToLinkBelt.sqf
- addons/reload/functions/fnc_startLinkingBelt.sqf
- addons/reloadlaunchers/functions/fnc_addMissileReloadActions.sqf
- addons/reloadlaunchers/functions/fnc_canLoad.sqf
- addons/reloadlaunchers/functions/fnc_getLoadableMissiles.sqf
- addons/reloadlaunchers/functions/fnc_reloadLauncher.sqf
- Some things I missed in #9334 and #9343.
> Reload/Reload Launcher - Fix headers

- addons/map/functions/fnc_updateMapEffects.sqf
After #8343 the cost has become something we can afford everyframe (~0.05ms)
this makes the effects less strobe-like when passing street lights rapidly as there is a smooth ramping of lighting up and down
> Map - Update map lighting effect every frame

- tools/make.py
dumps useful info at end if build fails
useful for automated check builds
example
```
- compat_spe build failed!
Log P:\temp\compat_spe.packing.log tail:
3474: duplicated 'ace_csw_baseTripod'
3475:
3476: \z\ace\addons\compat_spe\config.cpp Rapify:Rap: In File \z\ace\addons\compat_spe\CfgVehicles\turrets.hpp: circa Line 19 Rap: duplicated token or class
```
> Tools - make.py print tail of packing log on error

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_escapeRegex.sqf
- Add function to escape special characters used by regex from a string.
> Common - Add `FUNC(escapeRegex)`

- addons/arsenal/functions/fnc_attributeAddItems.sqf
- addons/arsenal/functions/fnc_handleSearchbar.sqf
- Title.
- Allow searching for multiple, not necessarily adjacent, words in sequential order (AK GL will show AK-15 GL, Opscore AOR1 will show Opscore 2 AOR1, etc.)
Removes need to `toLower` everything.
~~I was working on changing searching so words would be considered individually (so searching for "AK GL" would show AKs with GLs) but I'm not happy with that yet.~~
> Arsenal - Use regex for searchbar

- addons/ai/XEH_PREP.hpp
- addons/ai/XEH_postInit.sqf
- addons/ai/XEH_preInit.sqf
- addons/ai/functions/fnc_assignNVG.sqf
- addons/ai/functions/fnc_assignNVGpfh.sqf
- addons/ai/initSettings.sqf
- addons/ai/stringtable.xml
- Adds functionality (disabled by default) where AI will get NVG automatically assigned during night time and unassigned during day time.
---
Better naming ideas welcome.
> AI - Add automatic NVG equip/unequip

- addons/compat_ws/compat_ws_nouniformrestrictions/CfgVehicles.hpp
- addons/compat_ws/compat_ws_nouniformrestrictions/config.cpp
- addons/compat_ws/compat_ws_nouniformrestrictions/script_component.hpp
- Add No Uniform Restrictions subconfig for Western Sahara CDLC
- Merge https://github.com/Theseus-Aegis/Mods/tree/6ccdc9ed8c35adf6e20019dd99f46e922f96eb87/optionals/ws_nouniformrestrictions
> Compat WS - Add No Uniform Restrictions subconfig

- addons/laserpointer/XEH_postInit.sqf
- addons/main/script_mod.hpp
req https://github.com/CBATeam/CBA_A3/pull/1595
> Laserpointer - Block laser attachments if setting disabled (CBA 3.16.0)

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_throwWeapon.sqf
- addons/fire/functions/fnc_burnReaction.sqf
- addons/hitreactions/XEH_PREP.hpp
- addons/medical_status/config.cpp
- addons/medical_status/functions/fnc_setUnconsciousState.sqf
- addons/medical_status/initSettings.sqf
- addons/medical_status/stringtable.xml
- Added setting to allow a change of dropping held weapon when going unconscious (Default 0% chance / off)
- Moved `throwWeapon` function from `hitreactions` to `common`.
> Medical - Add dropping weapons on unconsciousness

- addons/markers/functions/fnc_canMove.sqf
> Markers - Don't try to move poly-line markers

- addons/zeus/functions/fnc_moduleGroupSide.sqf
- Fixes following issue that was found:
```SQF
20:23:46 Error in expression <dTeam _x;
[_x] joinSilent _newGroup;
_x assignTeam _team;
} forEach units _unit;>
20:23:46   Error position: <assignTeam _team;
} forEach units _unit;>
20:23:46   Error Foreign error: Unknown enum value: ""
20:23:46 File /z/ace/addons/zeus/functions/fnc_moduleGroupSide.sqf..., line 343
```
- If `assignedTeam` returns `""`, the default team is `"MAIN"`.
I'm convinced that prior to `2.14` this was not an issue. I think there were some related changes, but I can't remember for sure.
> Zeus - Fix Group Side module

- addons/advanced_ballistics/functions/fnc_initializeTerrainExtension.sqf
On certain maps, such as Virtual Reality, `getNumber (configFile >> "CfgWorlds" >> worldName >> "MapSize")` results in 0
> Advanced Ballistics - Fix `_mapSize` sometimes 0 by using engine command

- addons/dragging/functions/fnc_initObject.sqf
- docs/wiki/framework/dragging-framework.md
> Dragging - Add config support for weight ignoring

- addons/cargo/XEH_postInit.sqf
- addons/cargo/functions/fnc_paradropItem.sqf
- Implements `setVelocity` changes from #8204. This means that now `setVelocity` is run where `_object` is local.
Should fix #8199, but I haven't checked.
- Takes the gist from #7128: This PR makes both `_object` and the parachute temporarily invulnerable (2 seconds).
- Parachute is now attached at half the height of the object. Previously it was constant (1 m).
- Adds a missing parameter to the `QGVAR(paradropItem)` event. This fixes an issue with the Zeus module where (at least in theory) it would show the hint, but actually the hint was unwanted.
https://github.com/acemod/ACE3/blob/f7b520b56b770dc232f70c751767e2fc1e08703d/addons/zeus/functions/fnc_moduleCargoParadropWaypoint.sqf#L65
> Cargo - Fix/Improve FUNC(paradropItem)

- addons/compat_rhs_usf3/CfgJointRails.hpp
- addons/compat_rhs_usf3/config.cpp
- Title.
I have many theories as to why specifically this attachment was disabled. They all make no sense: the variants are available and it's a compatible suppressor on every other weapon.
> RHS Compat - Readd basic 5.56 suppressor to 5.56 muzzle slot

- addons/common/XEH_postInit.sqf
Adds [`lockInventory`](https://community.bistudio.com/wiki/lockInventory) status effect, for cross-mod compatibility possibilities.
Tested both in singleplayer and multiplayer settings.
> Common - Add lockInventory status effect

- addons/common/functions/fnc_lightIntensityFromObject.sqf
- addons/laserpointer/CfgEventHandlers.hpp
- addons/laserpointer/XEH_preInit.sqf
- addons/laserpointer/XEH_preStart.sqf
- docs/wiki/development/ace3-config-entries.md
```
[ACE] (laserpointer) TRACE: 9148 blocking switching to unsupported laser mode: _x=CUP_acc_LLM01_hex_V z\ace\addons\laserpointer\XEH_preInit.sqf:4
[ACE] (laserpointer) TRACE: 9148 blocking switching to unsupported laser mode: _x=CUP_acc_LCU_PM_Laser_V z\ace\addons\laserpointer\XEH_preInit.sqf:4
[ACE] (laserpointer) TRACE: 9148 blocking switching to unsupported laser mode: _x=CUP_acc_ANPEQ_15_Top_Flashlight_Black_V z\ace\addons\laserpointer\XEH_preInit.sqf:4
...
```
> Laserpointer - Block switching to unsupported visible lasers

- .hemtt/project.toml
- addons/compat_ws/compat_ws_realisticnames/CfgWeapons.hpp
- addons/compat_ws/compat_ws_realisticnames/config.cpp
- addons/compat_ws/compat_ws_realisticnames/script_component.hpp
- addons/compat_ws/compat_ws_realisticnames/stringtable.xml
- include/x/cba/addons/main/script_macros_common.hpp
- tools/stringtable_validator.py
- Adds realistic names to weapons for Western Sahara.
- XMS wasn't done (see comment in `CfgWeapons`)
Assumes https://github.com/CBATeam/CBA_A3/pull/1608 will be merged
> Compat WS - Realistic Names

- addons/cargo/CfgVehicles.hpp
- Alter cargo space for vehicles depending on the size/realistic space you would expect within the vehicle.
- Added Laws of War Transport/Cargo Van
- Things like Repair trucks would have low amounts of space since apparently they carry everything they need to repair any vehicle.
- I didn't touch object space size as I feel it's perfectly fine as is, just vehicles.
- Fixed the comments as they were bothering me.
> Cargo - Improve cargo space values

- addons/nightvision/functions/fnc_refreshGoggleType.sqf
Old code would sometimes mix up nvg source from vehicle turret or player's googles
With new WP-nvg it's very noticeable if it's wrong
e.g. cup mi-8 ("CUP_B_Mi17_CDF") left gunner would show green nvg when in gunner view
> Nightvision - Fix detecting if vehicle's turret has NVGs

- addons/captives/CfgGlasses.hpp
- addons/captives/CfgVehicles.hpp
- addons/captives/XEH_PREP.hpp
- addons/captives/XEH_preInit.sqf
- addons/captives/XEH_preStart.sqf
- addons/captives/config.cpp
- addons/captives/functions/fnc_canBlindfoldCaptive.sqf
- addons/captives/functions/fnc_canEscortCaptive.sqf
- addons/captives/functions/fnc_canRemoveBlindfoldCaptive.sqf
- addons/captives/functions/fnc_doBlindfoldCaptive.sqf
- addons/captives/initSettings.sqf
- addons/captives/stringtable.xml
- Add an interaction that puts a Contact DLC blindfold from one's own inventory onto a captive unit;
- If the captive unit already has some form of goggles on they will be preserved by being moved to the capturer's inventory before being replaced with a blindfold;
> Captives - Blindfold captive units

- addons/repair/XEH_PREP.hpp
- addons/repair/functions/fnc_addRepairActions.sqf
- addons/repair/functions/fnc_fullRepairProgress.sqf
- addons/repair/functions/fnc_getFullRepairTime.sqf
- addons/repair/functions/fnc_getHitPointsToIgnore.sqf
- addons/repair/functions/fnc_getSelectionsToIgnore.sqf
- Title.
- Close #9426.
Tested with vanilla and RHS vehicles and `CUP_B_M113A1_desert_USA`.
> Repair - Fix adding actions for hitpoints with the same name

- addons/medical_damage/ACE_Medical_Injuries.hpp
- Title.
With an average vest (armor 20, passthrough 0.3) and 5.56 (hit 9) this allows bruises to actually knock someone out from pain at default settings.
> Medical - Increase pain from bullet-inflicted bruises

- addons/compat_sog/CfgMagazines/belts.hpp
- addons/compat_sog/CfgWeapons/weapons.hpp
- Add barrel swapping to the following SOGPF weapons: MG42 and L4.
- Change the drum magazines for MG42 to be considered belts. This will allow belt linking with these magazines.
> Compat SOG - Add barrel swap for MGs and belt linking for drum magazines

- .hemtt/project.toml
It was matching `fnc_deviceAddWaypoint`
> Tools - Modify HEMTT ASC exclude to match

- addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
- addons/medical_treatment/functions/fnc_canDigGrave.sqf
- Change isAwake check for grave digging to only apply to CaManBase and not to burying bodybags from #9442 
- Change required as bodybags are always awake apparently
> Medical Treatment - Change isAwake check for grave digging to only apply to CAManBase

- addons/tagging/stringtable.xml
fix
[ACE] (tagging) ERROR: Failed compiling ACE_Tags for tag: ACE_square_filled_Black - missing displayName
> Tagging - Fix stringtable

- addons/zeus/functions/fnc_bi_moduleCurator.sqf
Close #9445
bis_fnc_activateaddons:
```
if (time > 0) exitwith {"The function can be activated only during the mission init." call bis_fnc_error; []};
```
so there's no point in calling it after mission start
ace_zeus already handles the activating
https://github.com/acemod/ACE3/blob/a5a8b5387a610580f8bf182e94bd9b9387295749/addons/zeus/XEH_postInit.sqf#L52-L55
> Zeus - Fix `bis_fnc_activateaddons` error in moduleCurator

- addons/medical_ai/functions/fnc_healingLogic.sqf
- addons/medical_ai/functions/fnc_itemCheck.sqf
- addons/medical_ai/initSettings.sqf
- addons/medical_ai/stringtable.xml
ref https://github.com/acemod/ACE3/discussions/9432#discussioncomment-7171178
I guess time to do this is now as we're free to change the setting type to list
> Medical AI - Add setting to replace gear for AI

- addons/medical_gui/functions/fnc_updateInjuryList.sqf
- addons/medical_gui/stringtable.xml
- addons/medical_treatment/stringtable.xml
- Change the layout of the injury list to separate global and limb-specific information
- Add new non-issue text to positively indicate lack of conditions
- Deemphasize non-issues with darkened text color
> Medical GUI - Reformat injury list to clarify global vs. limb-specific information

- addons/medical_gui/XEH_postInit.sqf
- addons/medical_gui/initSettings.sqf
- addons/medical_gui/stringtable.xml
- Add a keybind to temporarily show your patient information display
> Medical GUI - Add keybind to show player's patient information display

- addons/medical_gui/XEH_postInit.sqf
- addons/medical_gui/initSettings.sqf
- addons/medical_gui/stringtable.xml
- Temporarily show the player's patient information display when hit
> Medical GUI - Peek Medical Info on Hit

- addons/captives/functions/fnc_canBlindfoldCaptive.sqf
- addons/captives/functions/fnc_canRemoveBlindfoldCaptive.sqf
- addons/captives/functions/fnc_doBlindfoldCaptive.sqf
- addons/disarming/functions/fnc_canBeDisarmed.sqf
- addons/disarming/functions/fnc_disarmDropItems.sqf
- Allow disarming of captives in vehicles, the items will then be dropped in the vehicle's inventory;
- Allow blindfolding or removing the blindfold from captives in vehicles;
This is somewhat of a continuation of #9361.
To allow manipulating captives in vehicles I removed some `isNull objectParent _captive` exit conditions that check if the captives are not in any vehicle. Not sure what they were needed for and if they shouldn't be removed, but everything seems to work fine from my testing.
> Captives - Allow disarming and blindfolding of captives in vehicles

- addons/medical_engine/script_macros_medical.hpp
- addons/medical_gui/functions/fnc_updateInjuryList.sqf
- addons/medical_gui/stringtable.xml
- Specify the severity of bleeding in the injury list with an adjective and color
> Medical GUI - Display qualitative bleed rate in injury list

- addons/medical_gui/gui.hpp
- addons/medical_gui/stringtable.xml
- Label the right and left sides of the body image in the medical menu
> Medical GUI - Add R and L labels on body image

- addons/repair/XEH_postInit.sqf
- docs/wiki/framework/repair-framework.md
- Allow setting spare wheels and tracks counts for a vehicle in its config
> Repair - Allow setting spare wheels/tracks count in config

- addons/repair/functions/fnc_addRepairActions.sqf
Should fix #9478
I think because of recent lines
```
if !(EGVAR(common,settingsInitFinished)) exitWith {
EGVAR(common,runAtSettingsInitialized) pushBack [FUNC(addRepairActions), _this];
};
```
there might be an edge case when jipping for the object to become null, which would explain the
`Reserved variable in expression`
because type was ""
> Repair - Fix script error if vehicle is null

- addons/medical_gui/functions/fnc_onMenuOpen.sqf
- addons/medical_gui/gui.hpp
- Fix asymmetry in the overall layout of the medical menu
- Add a center dividing line in the bottom panel
> Medical GUI - Fix asymmetry in the medical menu

- addons/compat_spe/CfgVehicles.hpp
- addons/compat_spe/CfgVehicles/land.hpp
- Adds ACE Fuel compatibility for `Land_SPE_Fuel_Barrel_German` and `class Land_SPE_Fuel_Barrel_US`
- [] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
> SPE Compat - Add Spearhead 1944 fuel drums to refuel system

- addons/arsenal/functions/fnc_onArsenalOpen.sqf
- addons/arsenal/functions/fnc_statTextStatement_magCount.sqf
> Arsenal - Fix saving loadouts on new profiles

- addons/medical_treatment/XEH_preInit.sqf
- addons/medical_treatment/stringtable.xml
- As medical tab would gather all medical items from not only ACE, i suggest changing display name from ACE Medical to general "Medical Items"
- I got translations from native speakers that help with KAM translations
> Medical Treatment - Improve display name for arsenal tab

- addons/nightvision/functions/fnc_refreshGoggleType.sqf
- addons/nightvision/script_component.hpp
- docs/wiki/framework/nightvision-framework.md
- Prefixes `colorPreset`
- ~~Adds BWC for `"colorPreset"`~~
- Update framework wiki page because the standard doesn't seem to be `GVAR(x)`
> Night Vision - Add prefix to `colorPreset`

- addons/csw/functions/fnc_staticWeaponInit.sqf
- addons/dragging/functions/fnc_initPerson.sqf
Fixes:
put down turret and put `deleteVehicle this` in it's init
```
Error Reserved variable in expression
File /z/ace/addons/interact_menu/functions/fnc_addActionToClass.sqf..., line 62
[ACE] (interact_menu) ERROR: Failed to add action - action (ace_csw_magazine) to parent ["ACE_MainActions"] on object  [0]
```
Discord `W-Cephei` mentioned
> I think there is a bug happening with CSWs. If you load a mission saved with the previous version that had CSWs with the new version you will see this:
And I think it's related but not positive
> CSW/Dragging - Handle null objects causing script errors

- addons/medical_damage/initSettings.sqf
- addons/medical_gui/functions/fnc_updateBodyImage.sqf
- With changes from this #8444 in Line 94 we get zero divisor if damage threshold is set at 0. 
I think that easiest fix for this is just changing minimal value from settings.
> Medical GUI - Change minimal value of damage threshold

- addons/dragging/CfgEventHandlers.hpp
- addons/interaction/CfgVehicles.hpp
- Title.
Weapon/helmet slinging compatibility
> Interaction/Dragging - Remove actions from scripted weaponHolders

- addons/medical_treatment/CfgVehicles.hpp
- Title
- close #9549 
I am not sure if sutures should be added to basic crate (i guess in "basic" bandages dont reopen so no need for stitching).
60 sutures should be more than anough.
> Medical Treatment - Add missing sutures to advanced crate

- addons/common/functions/fnc_replaceRegisteredItems.sqf
e.g.  `ace_medical_treatemtn_convertItems` // 0: Enabled 1: RemoveOnly 2:Disabled
setting 1 had no effect because it hit `if (_replacements isNotEqualTo []) then {` before the `removeItems`
small optimization by delaying item counting until later
note: unrelated to this PR,
I have seen the item replacement failing after using arsenal, but haven't been able to replicate
> Common - Fix `replaceRegisteredItems` if replacing item with nothing

- addons/common/functions/fnc_checkFiles.sqf
- Title.
Probably shouldn't code while hungover, huh?
> Common - Fix mod compat string and add source of main to outdated error

- addons/compat_rhs_saf3/compat_rhs_saf3_explosives/config.cpp
- addons/compat_rhs_usf3/compat_rhs_usf3_explosives/CfgMagazines.hpp
- addons/explosives/dev/test_magazines.sqf
> Compat RHS - Fix explosives compat

- addons/medical_engine/functions/fnc_getItemArmor.sqf
- Title.
I forgot to take uniform hitpoint armor being multiplied by unit overall armor into account when adding up everything. This should also make stacking armored uniforms with vests less broken.
> Medical Engine - Disable uniform passthrough scaling, increase passthrough effect on vests

- addons/nightvision/stringtable.xml
- Improved one NVG's Korean name fixed for for grammar. (I obviously fixed this before, but I don't know why it's been rolled back.)
> Translation - Korean minor fix

- AUTHORS.txt
- docs/team.md
- Add Moderators to Team page
- Rename "Project maintainers" header to "Project Managers" to standardize naming across platforms.
> Documentation - Add Moderators to Team page

- addons/arsenal/functions/fnc_attributeAddItems.sqf
- Change ACE Arsenal attribute not to use lowercase displayName
- For #9565 
> Arsenal - don't lowercase displayName

- addons/medical_treatment/ACE_Medical_Treatment.hpp
- addons/realisticnames/CfgWeapons.hpp
These addons never get linted because of the has_include
probably a good idea to occasionly replace
`#if __has_include\(.*\)` with `#ifdef NEVERDEFINED`
and 
```
[rapify]
enabled = false
```
to true
so hemtt can take a look at them
> Configs - Fix case

- .github/workflows/hemtt.yml
- Run a HEMTT Windows build on pull requests and after merge to main
- Make the Arma 3 Tools made available via `arma-actions/arma3-tools` for access to `binarize_x64.exe`, requires `pull_request_target` instead of `pull_request`
- Using `pull_request_target` means it will use files from base branch by default. To get around this it will copy `addons`, `optionals` and `include` from the PR files into build directory.
Example Windows build: https://github.com/Dahlgren/ACE3/actions/runs/6658953635/job/18096958599, I accidentally flipped the names during test build so `-nobin` is the binarized one from Windows
- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull …
> CI - Run HEMTT on Windows for binarization

- addons/nightvision/functions/fnc_setupDisplayEffects.sqf
- Fix #6819
- Require Arma 3 v2.16 to have effect (backwards-compatible implementation)
Thanks to BI @Leopard20 for implementing [`cutRsc`](https://community.bistudio.com/wiki/cutRsc) `drawOverHUD` parameter!
> NightVision - Draw under HUD (requires 2.16)

- addons/refuel/functions/fnc_getCapacity.sqf
Fix #9620
handle weird edge case when trying to run on "camera"/CfgNonAIVehicles which won't support setVariable and will inf-loop
getCapacity calls setFuel
setFuel calls getCapacity
normally works fine but some objects don't support setVariable and cause infinity loop
e.g. `"camera" camCreate (getpos player)`
I took out the warning because it was just getting spammed by the mod but I could leave it in
```
[ACE] (refuel) WARNING: trying to getCapacity from non-CfgVehicle [164071: honeybee.p3d]
[ACE] (refuel) WARNING: trying to getCapacity from non-CfgVehicle [164077: cl_leaf3.p3d]
[ACE] (refuel) WARNING: trying to getCapacity from non-CfgVehicle [82674: t_ficusb1s_f.p3d]
```
> Refuel - Fix infinite recursion for `getCapacity` on a non-CfgVehicle

- addons/arsenal/functions/fnc_attributeAddItems.sqf
- addons/arsenal/functions/fnc_handleSearchbar.sqf
- Title.
```
"Песочный" regexMatch "Песочный"; // true
"Песочный" regexMatch (toLower "Песочный"); // false
forceUnicode 1;
"Песочный" regexMatch (toLower "Песочный"); // true
```
> Arsenal - Use forceUnicode for search functions

- addons/cargo/functions/fnc_canLoadItemIn.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/dragging/script_component.hpp
- title
- Remove distance checks for `cargo` loads as it's redundant due to `fnc_cargo_canLoadItemIn`
- Rename the distance define to indicate it's used only for "Man" loading, cargo has it's own one which had the same name
> Dragging - Fix being able to load people into vehicles from any distance

- addons/interaction/CfgVehicles.hpp
- Fixes #8699.
- Unsure of unintended side effects, but I did try with a larger modset and no negative side effects were noticed.
> Interaction - Allow pulling bodies out of wrecks

- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- title
- Not sure if it should be in `fnc_cargo_canLoadItemIn` or directly in dragging, this implementation has least chance to break anything
- Whole dragging/carrying integration feels a bit spaghetti
Without the fix, if cargo is disabled you can load stuff in and you won't be able to get it back.
> Dragging - Fix being able to load cargo if the system is disabled

- addons/medical_engine/functions/fnc_getHitpointArmor.sqf
- Title.
I haven't tested it yet, I will test it in about 3-4 hours.
> Medical Engine - Fix script error for 0 overall hitpoint armor

- addons/attach/functions/fnc_attach.sqf
- addons/attach/functions/fnc_placeApprove.sqf
- docs/wiki/framework/attach-framework.md
Add an optional parameter to config for item attach system that describes the item's orientation. This allows to make custom items that are not symmetric and define when attached to vehicles what side should be "outwards". 
This came about while I was looking into what I could do to make my custom item be oriented the right way when used with ACE attach system. If this doesn't fit or it's a bad way to solve the problem feel free to close the PR. I could probably solve this by applying the same orientation change in my own mod by listening to the ``ace_attach_attached`` event, but thought it might make more sense to have the option in ACE. 
Parameter added for config is:
```
ACE_attachable_orientation[] = {0,-1,0};
```
So config in the example video …
> Attach - Add config property to set object orientation

- addons/cargo/functions/fnc_loadItem.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/zeus/XEH_postInit.sqf
- Title. I found it mildly annoying to see ACE cargo objects attached to the vehicle they belong to in the zeus interface.
This only applies if the `ace_zeus` component is loaded
- `QGVAR(addObjects)` and `QGVAR(removeObjects)` event in the `ace_zeus` component can now accept an array of curators instead of just a single curator or all.
- I have tested this in SP only. I imagine it should work fine in MP, but I don't know the locality of `objectCurators`, as the wiki doesn't mention it.
> Cargo - Remove cargo objects from zeus editable objects

- addons/cargo/XEH_postInit.sqf
- addons/interaction/XEH_PREP.hpp
- addons/interaction/functions/fnc_addPassengersActions.sqf
- addons/interaction/functions/fnc_canInteractWithVehicleCrew.sqf
- addons/quickmount/config.cpp
- addons/quickmount/functions/fnc_canShowFreeSeats.sqf
- If one or more passengers in a vehicle are conscious, not captive and hostile to the interacting unit, interactions such as ACE passenger and cargo actions will not appear.
- Updated `FUNC(addPassengerActions)`. Using `objectParent` instead of `vehicle`.
- Addresses https://github.com/acemod/ACE3/pull/9618#issuecomment-1796694348.
I opted not to go with adding a condition for interacting via `EFUNC(common,addCanInteractWithCondition)`, as I don't want to impose this for all vehicle interactions.
- [Development …
> Interaction - Add crew status check for some vehicle interactions

- addons/arsenal/functions/fnc_onArsenalClose.sqf
- addons/arsenal/functions/fnc_openBox.sqf
- addons/arsenal/functions/fnc_refresh.sqf
- addons/arsenal/functions/fnc_removeBox.sqf
- Title.
- Fixes https://discord.com/channels/976165959041679380/1167933574654205993/1169139121281839155. In case message is delete, `[player, player, true] call ace_arsenal_fnc_openBox` stopped working after 3.16.0.
> Arsenal - Fix closing arsenal when ignoring content

- addons/arsenal/XEH_postInit.sqf
- addons/arsenal/functions/fnc_addVirtualItems.sqf
- addons/arsenal/functions/fnc_attributeInit.sqf
- addons/arsenal/functions/fnc_initBox.sqf
- addons/arsenal/functions/fnc_openBox.sqf
- addons/arsenal/functions/fnc_removeBox.sqf
- addons/arsenal/functions/fnc_removeVirtualItems.sqf
- Title.
- Fix for https://discord.com/channels/976165959041679380/1174212946793074768.
- The arsenal now refreshes globally if `FUNC(addVirtualItems)` or `FUNC(removeVirtualItems)` was applied globally.
The side effect is that all changes are stored in the JIP queue until the arsenal or its object is deleted. I'm not sure how to handle this any better.
- Title of this PR uses our standard template `Component - …
> Arsenal - Fix `FUNC(removeVirtualItems)` for JIP players

- addons/interact_menu/functions/fnc_createVehiclesActions.sqf
- Show distance to vehicle in action name for vehicle actions. See screenshot below.
> Interaction Menu - Show distance to target on vehicle actions

- addons/artillerytables/CfgWeapons.hpp
- addons/captives/CfgWeapons.hpp
- addons/hearing/CfgWeapons.hpp
- addons/intelitems/CfgMagazines.hpp
- addons/maptools/CfgWeapons.hpp
- addons/medical_treatment/CfgWeapons.hpp
- addons/mk6mortar/CfgWeapons.hpp
- addons/overheating/CfgMagazines.hpp
- addons/overheating/CfgWeapons.hpp
- addons/rangecard/CfgWeapons.hpp
- Title.
In mass units:
- Cable Ties: 1 -> 0.3
- Range Cards/Artillery Tables: 1/0.5 -> 0.1
- Intel Items: 1 -> 0.1
- Ear Plugs: 1 -> 0.1
- Bandages: 1 -> 0.6
- Spare Barrel: 60 -> 25
~~- IVs: 2.5, 5, 10 -> 2.5, 4, 7 (reward carrying larger bags)~~ Reverted
> General/Medical - Lower inventory size for misc items

- addons/repair/functions/fnc_getClaimObjects.sqf
- addons/repair/functions/fnc_repair.sqf
- Add param to `FUNC(getClaimObjects)` to sort objects by damage. Default false, `FUNC(canRepair)` only checks for object existence, actual repair sorts.
Better yet would be to choose which items are used for the repair IMO but that's another pile of scrap.
> Repair - Use object with lowest damage for changing wheels/tracks

- addons/cargo/functions/fnc_onMenuOpen.sqf
> Cargo - Add item index and damage to cargo menu

- addons/dragging/XEH_postInit.sqf
- addons/dragging/functions/fnc_setCarryable.sqf
- addons/dragging/functions/fnc_setDraggable.sqf
- Title.
- `FUNC(handleKilled)` must be called locally, which I completely forgot to take into account when improving the dragging component.
- Some minor code cleanup.
> Dragging - Fix captives

- addons/cargo/functions/fnc_onMenuOpen.sqf
- addons/cargo/functions/fnc_startUnload.sqf
- addons/zeus/CfgVehicles.hpp
- addons/zeus/XEH_PREP.hpp
- addons/zeus/config.cpp
- addons/zeus/functions/fnc_moduleUnloadFromCargo.sqf
- addons/zeus/stringtable.xml
> Zeus - Add zeus modules for unloading cargo

- addons/arsenal/functions/fnc_fillRightPanel.sqf
- addons/arsenal/functions/fnc_handleSearchbar.sqf
- If two or more items had the same display name and you selected e.g. the second one, it would select the top most one when searching. E.g. having the `M1 Garand` selected from the CDLC SPE, but when updating the search bar, it would select the `M1 Garand` from the Iron Front mod.
The fix for this is to find the class name instead of the display name. 
- When searching in the listnbox panels (i.e. container content), it would deselect the currently selected item when removing characters from the search. E.g. seaching for `rope` and having the item `Rope 15.2 meters` selected, then updating the search to `rop` would deselect the item `Rope 15.2 meters`.
Now it only deselects the item if it isn't part of the search results.
- If an item wasn't found …
> Arsenal - Search fixes

- addons/medical/functions/fnc_deserializeState.sqf
> Medical - Prevent running `FUNC(deserializeState)` in scheduled environment

- docs/wiki/framework/vehiclelock-framework.md
- Fix a spelling mistake in vehicle lock docs
> Wiki - Fix spelling in vehicle lock framework wiki page

- addons/compat_rhs_usf3/compat_rhs_usf3_arsenal/CfgWeapons.hpp
- Title.
- Fix `baseWeapon` property on top-mounted lasers.
Want a fun repro? Load pure RHS, equip a M952V, switch to one of the combo attachments, reequip the M952V, press Ctrl-C, congratulations, you have a free laser.
Addresses https://discord.com/channels/976165959041679380/1182576398418849862/1182576398418849862
> Compat RHS - Fix USAF flashlights materializing PEQ-15s

- addons/arsenal/functions/fnc_buttonCargo.sqf
- addons/arsenal/functions/fnc_fillRightPanel.sqf
- addons/arsenal/functions/fnc_updateUniqueItemsList.sqf
- Unique items would not show up in containers when they were available in the arsenal. E.g. If you put NVGs in your backpack, they wouldn't show up in the backpack's items when using an arsenal that has those NVGs available in the NVG tab.
- If a unit had weapons in a container, it would show all of its accessories as unique items. Now you no longer see a weapon's accessories.
This essentially reverts some of the changes I made in #9040, but it's for the better.
- [Development …
> Arsenal - Fix displaying virtual items & weapon attachments in cargo

- addons/markers/functions/fnc_onLBSelChangedChannel.sqf
Make channel changes in the marker placement window based on the `lbData` of the selection, instead of its index in the list. This way, the order of the items won't matter, and mods that manipulate the list (e.g. deletes items) won't break its functionality.
> Markers - Use lbData for channel selection

- addons/arsenal/functions/fnc_fillRightPanel.sqf
- addons/arsenal/functions/fnc_updateRightPanel.sqf
- addons/arsenal/script_component.hpp
- Title. Makes items also respect config `allowedSlots[]` property now.
- Drop mass property from right panel cache and ListNBox. I'm 99% 3rd parties don't use this anyway.
- Drop itemInfo param and lookups from right panel cache. Not needed due to dropping mass.
> Arsenal - Use `canAdd` to check if item can be added to container

- addons/advanced_fatigue/XEH_postInit.sqf
- addons/common/functions/fnc_isModLoaded.sqf
- addons/compat_sog/functions/fnc_handlePunjiTrapTrigger.sqf
- addons/csw/functions/fnc_assemble_deployTripod.sqf
- addons/csw/functions/fnc_staticWeaponInit.sqf
- addons/dogtags/XEH_postInit.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- addons/killtracker/XEH_postInit.sqf
- addons/overpressure/functions/fnc_firedEHBB.sqf
- addons/overpressure/functions/fnc_overpressureDamage.sqf
- addons/zeus/functions/fnc_bi_moduleArsenal.sqf
- addons/zeus/functions/fnc_moduleSetMedic.sqf
- addons/zeus/functions/fnc_moduleSetMedicalFacility.sqf
- addons/zeus/functions/fnc_moduleSetMedicalVehicle.sqf
- Title.
- We could make it so that `ace_common_fnc_isModLoaded` is not case sensitive, but that means adding a `toLowerANSI`. 
> Common - Make `FUNC(isModLoaded)` case-insensitive

- addons/inventory/XEH_preStart.sqf
- addons/inventory/functions/fnc_forceItemListUpdate.sqf
- addons/inventory/functions/fnc_inventoryDisplayLoad.sqf
- addons/logistics_rope/CfgWeapons.hpp
- Title.
- Add missing .paa file extension to logistics ropes.
- Replace a while loop.
- Replace a count loop with forEach.
> Inventory - Fix filtering for items without file extension in picture property

- addons/inventory/XEH_preStart.sqf
- addons/inventory/functions/fnc_forceItemListUpdate.sqf
- addons/inventory/functions/fnc_inventoryDisplayLoad.sqf
- addons/logistics_rope/CfgWeapons.hpp
- Close #9163.
Needs #9696.
This does make the filtering run every frame instead of only when needed, but the performance loss is negligible unless dealing with inventories with hundreds of unique items displayed at once (in which case, you have other concerns anyway).
> Inventory - Fix item lockup when dragging into same inventory

- addons/inventory/CfgEventHandlers.hpp
- addons/inventory/RscDisplayInventory.hpp
- addons/inventory/XEH_PREP.hpp
- addons/inventory/XEH_postInit.sqf
- addons/inventory/XEH_preStart.sqf
- addons/inventory/functions/fnc_addCustomFilter.sqf
- addons/inventory/functions/fnc_currentItemListBox.sqf
- addons/inventory/functions/fnc_displayNameWeight.sqf
- addons/inventory/functions/fnc_filterBackpacks.sqf
- addons/inventory/functions/fnc_filterGrenades.sqf
- addons/inventory/functions/fnc_filterHeadgear.sqf
- addons/inventory/functions/fnc_filterItems.sqf
- addons/inventory/functions/fnc_filterMagazines.sqf
- addons/inventory/functions/fnc_filterMedical.sqf
- addons/inventory/functions/fnc_filterUniforms.sqf
- addons/inventory/functions/fnc_filterVests.sqf
- addons/inventory/functions/fnc_filterWeapons.sqf
- addons/inventory/functions/fnc_forceItemListUpdate.sqf
- addons/inventory/functions/fnc_inventoryDisplayLoad.sqf
- addons/inventory/functions/fnc_onLBSelChanged.sqf
- addons/inventory/initSettings.inc.sqf
- addons/medical_treatment/XEH_preStart.sqf
- addons/movement/CfgEventHandlers.hpp
- addons/movement/XEH_PREP.hpp
- Moved name-weight bar modification from `ace_movement` into `ace_inventory`.
- Improved medical item detection.
- Improved item filtering:
- Now removes medical and face wear items from 'items' tab, as they have their own tabs (face wear is in the head gear tab).
- Fixed an issue with a bad macro, making vests pop up in the 'items' tab when they shouldn't.
- Closes https://github.com/acemod/ACE3/issues/7150.
- Title of this …
> Inventory - Improve multiple aspects

- addons/arsenal/functions/fnc_addDefaultLoadout.sqf
- addons/arsenal/functions/fnc_buttonLoadoutsRename.sqf
- addons/arsenal/functions/fnc_loadoutsChangeTab.sqf
- addons/arsenal/functions/fnc_removeDefaultLoadout.sqf
- Title.
- Disable renaming default loadouts mid-mission.
> Arsenal - Add JIP support to Default Loadouts added mid-mission

- addons/overheating/ACE_Arsenal_Stats.hpp
- addons/overheating/XEH_PREP.hpp
- addons/overheating/config.cpp
- addons/overheating/functions/fnc_statTextStatement_allowSwapBarrel.sqf
- addons/overheating/functions/fnc_statTextStatement_boltType.sqf
- addons/overheating/stringtable.xml
- Adds an arsenal stat to show if the weapon is open or closed bolt.
- Adds an arsenal stat to show if the weapon's barrel can be swapped.
Baer lied to me and changing the branch name closed #9717 (or maybe I screwed up the name change lol)
> Overheating - Add stats to arsenal

- addons/maptools/CfgVehicles.hpp
- addons/maptools/CfgWeapons.hpp
- _Change Plotting Board descriptionShort CSTRING target `(Description)` (Map Tool description) to `(PlottingBoard_Description)` (True Plotting Board description)_
- _Change Plotting Board map interaction menu name CSTRING target `(name)` (item name "Map Tools") to `(ToMapToolLabel)` ("To Maptool" string)_
> Map Tools - Fix wrong Plotting Board strings targets

- addons/compat_ws/compat_ws_realisticnames/stringtable.xml
- addons/fcs/stringtable.xml
- addons/map/stringtable.xml
- addons/map_gestures/stringtable.xml
- addons/maptools/stringtable.xml
- addons/marker_flags/stringtable.xml
- addons/markers/stringtable.xml
- addons/nightvision/stringtable.xml
- addons/overheating/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/tagging/stringtable.xml
- addons/zeus/stringtable.xml
- _change/add Japanese strings to maptools for plotting board and some tweaks_
- _change/add Japanese strings to markers for milliseconds and some tweaks_
- _add Japanese strings to overheating for stat bolt type and barrel type description_
- _change Japanese strings in realisticnames (vanilla and for ws) for the display names, add camouflage details and hex wording katakana to kanji_
- _change Japanese strings in nightvision for the display names, some generation(4th) and wp version has wrong display name, and make matching to vanilla games name_
- _change Japanese strings in map for the Add-on options menu, some explanations are incorrect_
- _change Japanese strings in map_gestures for the Add-on options menu, some explanations are incorrect_
- …
> Translations - Improve/Add Japanese localization.

- addons/common/functions/fnc_getVehicleUAVCrew.sqf
- addons/dragging/functions/fnc_canCarry.sqf
- addons/dragging/functions/fnc_canDrag.sqf
- addons/gforces/XEH_postInit.sqf
- addons/medical_engine/XEH_postInit.sqf
- addons/medical_status/XEH_preInit.sqf
- Title.
As of 2.14 `unitIsUAV` does the same thing as the config lookup
> General - Change UAV unit config lookups to `unitIsUAV`

- addons/compat_cup_units/$PBOPREFIX$
- addons/compat_cup_units/CfgWeapons.hpp
- addons/compat_cup_units/compat_cup_nouniformrestrictions/CfgVehicles.hpp
- addons/compat_cup_units/compat_cup_nouniformrestrictions/config.cpp
- addons/compat_cup_units/compat_cup_nouniformrestrictions/script_component.hpp
- addons/compat_cup_units/config.cpp
- addons/compat_cup_units/script_component.hpp
- Title, mostly ACE Hearing & No uniform restrictions
- Not an original CUP compat, just something Me and Jonpas have used for years that's nice to have.
> Add CUP Units Compatibility

- addons/cargo/functions/fnc_startLoadIn.sqf
- addons/cargo/functions/fnc_startUnload.sqf
- addons/cargo/stringtable.xml
- Title. Screenshots attached.
- Invalidate old translations.
> Cargo - Show item and vehicle in progress bar text

- addons/medical_treatment/functions/fnc_checkPulseLocal.sqf
- Title.
Checking pulse while CPR is being performed can be used to diagnose death, as dead units will not have their pulse updated.
> Medical - Fix getting no pulse on a dead patient receiving CPR

- addons/maptools/functions/fnc_updateMapToolMarkers.sqf
> Map Tools - Fix tools showing after item is dropped out of inventory

- addons/compat_rhs_afrf3/compat_rhs_afrf3_arsenal/CfgWeapons.hpp
- addons/compat_rhs_afrf3/compat_rhs_afrf3_arsenal/config.cpp
- addons/compat_rhs_usf3/compat_rhs_usf3_arsenal/CfgWeapons.hpp
> Arsenal/RHS Compats - Removed bad illuminator stats for RHS attachments

- addons/compat_cup_terrains/$PBOPREFIX$
- addons/compat_cup_terrains/CfgEventHandlers.hpp
- addons/compat_cup_terrains/CfgVehicles.hpp
- addons/compat_cup_terrains/XEH_postInit.sqf
- addons/compat_cup_terrains/config.cpp
- addons/compat_cup_terrains/script_component.hpp
- Merges CUP Terrains Compat from CUP to ACE.
> Add CUP Terrains Compatibility

- addons/medical_status/functions/fnc_setUnconsciousState.sqf
> Medical - Prevent uncon AI from talking

- addons/explosives/XEH_PREP.hpp
- addons/explosives/XEH_preInit.sqf
- addons/explosives/functions/fnc_addDetonateActions.sqf
- addons/explosives/functions/fnc_cycleActiveTrigger.sqf
- addons/explosives/functions/fnc_selectTrigger.sqf
- addons/explosives/initKeybinds.inc.sqf
- addons/explosives/stringtable.xml
- docs/wiki/feature/explosives.md
- Add `Cellphone` Keybind (unbound by default) to open the Cellphone interface;
- Add `Detonate All on Active Detonator` Keybind (unbound by default) to detonate all explosives tied to the current `Active Detonator`;
When connecting the first explosive to a detonator, that detonator will be selected as the active one, afterwards it's possible to switch the `Active Detonator` as desired via a `Set Active Detonator` interaction on any non-active detonator;
- Add `Cycle Active Detonator` Keybind (unbound by default) to cycle between the currently carried triggers, thereby selecting which is the `Active Detonator`, is visualized by ~~[`CBA Notification`](https://cbateam.github.io/CBA_A3/docs/files/ui/fnc_notify-sqf.html#CBA_fnc_notify)~~ …
> Explosives - Add Cellphone/Detonator Keybinds

- addons/csw/functions/fnc_staticWeaponInit.sqf
- Title. This is relevant for ZEN's placement preview feature, which breaks magazine unloading if advanced assembly is enabled.
`simulationEnabled objNull` is `true` so this handles the csw being deleted
> CSW - Delay init for CSW with simulation disabled

- addons/nightvision/XEH_preInit.sqf
- addons/nightvision/functions/fnc_setupDisplayEffects.sqf
- Title
- Close #9781
- Drop `BIS_fnc_rscLayer` in nightvision component as it's no longer needed.
This might be overkill but if the linked issue is not intended behavior, we can't really make it happen on purpose, so it's best to be consistent instead IMO.
> Nightvision - Register effects during preInit

- addons/arsenal/defines.hpp
- addons/arsenal/functions/fnc_addAction.sqf
- addons/arsenal/functions/fnc_compileActions.sqf
- addons/arsenal/functions/fnc_handleActions.sqf
- addons/arsenal/script_component.hpp
- addons/arsenal/ui/RscAttributes.hpp
- addons/arsenal/ui/RscCustomArsenalButton.hpp
- Move some things around to reduce duplicate code
- Remove an unused variable
- Fix hidden controls potentially going outside of actions control group area
- Remove action focus setting. Root cause for lockups was found to be above
> Arsenal - Cleanup action UI code

- addons/arsenal/XEH_preInit.sqf
- addons/arsenal/defines.hpp
- addons/arsenal/functions/fnc_addListBoxItem.sqf
- addons/arsenal/functions/fnc_fillLeftPanel.sqf
- Port code changes from #9785
- Add mission variable mapping left panel tab button IDCs to the virtualItems map IDs
- Add support for campaign unit insignias, prevent unacessible insignias from being shown in the arsenal (two insignias with the same classname from different configs).
- Add support for mission makers to disable specific faces/voices/insignias at the mission level via scripting (by modifying a copy of the configFile cache).
- Add some comments to hopefully help the next poor sod who touches this.
~~I'm not sure if this is faster (should be, but I haven't done any profiling), but it sure is smaller.~~
There's a minimal performance increase:
```
12:07:07 [ACE] (arsenal) INFO: fill left panel old performance: [17.1853,59] panel item …
```
> Arsenal - Left panel code improvements

- addons/arsenal/functions/fnc_verifyLoadout.sqf
- addons/gunbag/XEH_preInit.sqf
- docs/wiki/framework/arsenal-framework.md
- Raise an event during loadout verification with loadout data and extended info.
See gunbag changes in diff for intent and use.
> Arsenal - Add `ace_arsenal_loadoutVerified` event

- addons/common/functions/fnc_cachedCall.sqf
- Title. BWC should have been kept.
> Common - Allow multiple events to clear a cached call

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- docs/wiki/framework/grenades-framework.md
- Adds new events for units affected by flashbangs
> Grenades - Flashbang events

- addons/killtracker/CfgEventHandlers.hpp
- addons/killtracker/XEH_postInit.sqf
- addons/killtracker/XEH_preInit.sqf
- addons/killtracker/initSettings.inc.sqf
- addons/killtracker/stringtable.xml
- Add an option to disable tracking of kills of AI units when using ACE Kill Tracker. Configurable through Addon Settings
- CfgEventHandlers.cpp
- Added PreInit to Extended Event Handlers
- XEH_postInit.sqf
- Added check if AI tracking is enabled and track AI kills only if so
- XEH_preInit.sqf
- Added call to init Addon Settings
- initSettings.inc.sqf
- Added the actual add settings call
- stringtable.xml
- Added necessary translations
> KillTracker - Add option to filter out AI unit kills

- addons/compat_ws/CfgWeapons.hpp
- Add barrel swapping to the SA-77 and SA-77 Compact.
- IRL version of the gun, Vektor SS-77, is quick change capable and that appears to be reflected in the WS model.
> Compat WS - Add barrel swap to WS machine guns

- addons/compat_spe/CfgAmmo.hpp
- addons/compat_spe/CfgAmmo/bullets.hpp
- addons/compat_spe/CfgMagazines.hpp
- addons/compat_spe/CfgMagazines/flamethrower.hpp
- Fixes flamethrower magazines not appearing in ace arsenal
- Sets ACE_Caliber on SPE 50 cal ammo to put it more in line with vanilla ammo when it comes to causing deafness (Without it earplugs were ineffective)
> SPE Compat - Fix flamethrower magazines not showing in arsenal / 50 Cal deafness

- addons/hearing/XEH_postInit.sqf
- addons/hearing/initKeybinds.inc.sqf
- addons/hearing/stringtable.xml
- This request will add keybind for put or take out earplug
- Default ~~ALT+H~~ unbound
- Addon Controls -> ACE Equipment
> Hearing - Keybind for putting or taking out earplugs

- addons/compat_cup_weapons/compat_cup_weapons_nightvision/CfgWeapons.hpp
- addons/compat_cup_weapons/compat_cup_weapons_nightvision/config.cpp
- addons/compat_cup_weapons/compat_cup_weapons_nightvision/stringtable.xml
- Fixes binocular NVGs having Monocular vision.
- Adds WP variants of GPNVGs, PVS-14/15s as Pabst suggested.
> CUP Weapons Compat - Add WP NVGs

- addons/artillerytables/functions/fnc_rangeTableUpdate.sqf
- addons/mk6mortar/CfgMagazines.hpp
- addons/mk6mortar/XEH_preInit.sqf
- addons/mk6mortar/initKeybinds.inc.sqf
- Make 82mm Mortar Ammo visible in the Arsenal and Zeus inventory Editor, allowing individual rounds to be added and removed from inventories without throwing errors (at least with ZEN);
- Add a keybind to open the 82mm Artillery Rangetable directly;
- Fix the last selected charge not being remembered when reopening an artillery rangetable (not just 82mm), it appears this feature was incompletely implemented in the past;
**Further improvements for the future:**
> Artillery - Add Rangetable Keybind, Fix remembering last charge

- addons/medical_gui/functions/fnc_updateInjuryList.sqf
- addons/medical_treatment/stringtable.xml
- Shows the IV type on receiving
- Brought over from KAT so they don't need to overwrite the function, most non-KAT groups probably only use one type anyway
- The translations were modified with AI, they seem to be fine though, prompt said to stay close to the original, just add the type
> Medical GUI - Display IV Type

- addons/common/functions/fnc_addToInventory.sqf
- Allows `ace_common_fnc_addToInventory` to add partial magazines to specific containers
> Common - Fix addToInventory for magazines

- addons/fortify/functions/fnc_registerObjects.sqf
- Was this intentional? I don't understand what the purpose is if it is intentional.
> Fortify - Fix invalid object filtering

- addons/medical_gui/stringtable.xml
> Translations - Improve Japanese localization 2

- addons/refuel/functions/fnc_canTakeNozzle.sqf
- addons/refuel/functions/fnc_connectNozzleAction.sqf
- addons/refuel/functions/fnc_dropNozzle.sqf
- addons/refuel/functions/fnc_startNozzleInHandsPFH.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
- Fixes #9753.
- Minor optimisation.
- You can still check the amount of fuel left in a jerry can when someone is carrying it. I left it in because I felt it was ok to leave in.
- Race condition for claiming the object can most likely occur, but I'm not willing to rewrite the component with `ace_common_fnc_claimSafeServer` now.
- I'm not sure which interaction expections should be checked for, but in my testing it worked. I was testing the virtual world with vehicles, did not test anything related to swimming, being on ladder, inside vehicles etc - I only tested the basic and most used use cases.
- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the …
> Refuel - Add ownership concept to nozzles & jerry cans

- addons/overheating/functions/fnc_calculateCooling.sqf
- addons/overheating/functions/fnc_coolWeaponWithItem.sqf
- addons/overheating/functions/fnc_coolWeaponWithWaterSource.sqf
- addons/overheating/functions/fnc_updateSpareBarrelsTemperaturesThread.sqf
- addons/overheating/functions/fnc_updateTemperature.sqf
- addons/overheating/script_component.hpp
- Open bolt guns have airflow down the bore that increases convective cooling a small amount.
- I've applied this to spare barrels as well as they are not in a gun and so cannot have a bolt closed on them.
> Overheating - Increase cooling for open bolt guns and spare barrels

- addons/arsenal/ACE_Arsenal_Stats.hpp
- addons/arsenal/XEH_PREP.hpp
- addons/arsenal/functions/fnc_statTextStatement_load.sqf
e.g. trying to find a backpack that will fit a specific item
> Arsenal - Show load stat's actual value

- addons/parachute/RscTitles.hpp
- addons/parachute/functions/fnc_showAltimeter.sqf
- Add `seconds` to the digital clock on the Altimeter Watch, changing its format to `HH:MM:SS`. Making it more useful for timing explosives or tracking artillery TOF accurately;
> Parachute - Add Seconds Indicator to Altimeter Watch

- addons/compat_cup_weapons/compat_cup_weapons_nightvision/CfgWeapons.hpp
- addons/compat_cup_weapons/compat_cup_weapons_nightvision/config.cpp
- addons/compat_cup_weapons/compat_cup_weapons_nightvision/stringtable.xml
fixes new classnames to be consistent (format `X_WP`)
this matches all the others such as `class CUP_NVG_GPNVG_tan_WP: CUP_NVG_GPNVG_tan`
> Cup Weapon Compat - Fix NVG classnames

- addons/repair/stringtable.xml
> Repair - Wheel Patching - Tooltip rephrasing

- addons/grenades/functions/fnc_flashbangExplosionEH.sqf
- With epilepsy mode enabled, screen goes grey instead of pure white, but as the effect fades out you get a white flash as you're able to see again. It's just as bad as the initial (non-epilepsy mode) effect. Now uses whatever blend was selected instead of hard setting white.
I tested, screen goes grey, stays that way and comes back instantly. Not exactly the nicest way but the original is not epilepsy friendly.
> Grenades - Fix Flashbang in epilepsy mode

- addons/dragging/functions/fnc_startCarryPFH.sqf
- Fixes a bug in `ace_dragging_fnc_startCarryPFH`: Previously, it would try to get the dragged object when trying to drop the carried object if the action timed out. Now it gets the carried object. I'm not sure how to add that to the title.
> Dragging - Fix dropping incorrect object when carrying fails

- addons/fortify/functions/fnc_deployConfirm.sqf
- docs/wiki/framework/fortify-framework.md
- Title.
- Fixes #9729.
- Updated documentation to reflect reality.
> Fortify - Skip placement animation for no cost fortifications

- addons/rearm/functions/fnc_addRearmActions.sqf
- title
- Continuation of https://github.com/acemod/ACE3/pull/9644/files
> Rearm - Show distance to target on actions

- addons/advanced_fatigue/XEH_postInit.sqf
> Advanced Fatigue - Disable sway when Advanced Fatigue is off

- addons/hearing/XEH_postInit.sqf
- addons/hearing/XEH_preInit.sqf
- addons/hearing/functions/fnc_addEarPlugs.sqf
- Title.
- Moved `TRACE` down to where it's actually called, in case it's called before CBA settings are ready.
@BrettMayson you added `remoteExec`, is there any specific reason why? I couldn't find anything on the PR.
> Hearing - Removed `remoteExec` & added microoptimisations

- addons/arsenal/functions/fnc_addRightPanelButton.sqf
- addons/arsenal/functions/fnc_scanConfig.sqf
- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_adjustMagazineAmmo.sqf
- addons/common/functions/fnc_getCountOfItem.sqf
- addons/common/functions/fnc_uniqueItems.sqf
- addons/medical_gui/functions/fnc_countTreatmentItems.sqf
- addons/medical_treatment/CfgMagazines.hpp
- addons/medical_treatment/CfgVehicles.hpp
- addons/medical_treatment/CfgWeapons.hpp
- addons/medical_treatment/config.cpp
- addons/medical_treatment/functions/fnc_hasItem.sqf
- addons/medical_treatment/functions/fnc_medication.sqf
- addons/medical_treatment/functions/fnc_treatmentFailure.sqf
- addons/medical_treatment/functions/fnc_useItem.sqf
- docs/wiki/framework/arsenal-framework.md
- Moving over from KAT so they can stop overwriting ACE functions
- Converts the painkiller to a magazine
> Medical - Support Magazine Treatment Items

- addons/fortify/functions/fnc_deployConfirm.sqf
- addons/fortify/functions/fnc_deployObject.sqf
- docs/wiki/framework/fortify-framework.md
- _Add a_ `ace_fortify_onDeployStop` _local event for when deploying is cancelled before confirming_
- I.e. is called when right clicking after the menu appears
- Is also called when `ace_fortify_deployCanceled` is
> Fortify - Add onDeployStop event for cancelling before confirming

- addons/interaction/functions/fnc_passMagazine.sqf
- Add optional _animate parameter
- Change to removing the magazine from _player using CBA_fnc_removeMagazine
_animate is optional and the Default is true so should not break anything. Function can then be used for tossing magazines and the like.
> Interaction - Make magazine passing animation optional

- addons/advanced_throwing/functions/fnc_canThrow.sqf
- addons/advanced_throwing/functions/fnc_throw.sqf
- addons/captives/functions/fnc_handleOnUnconscious.sqf
- addons/common/functions/fnc_fixLoweredRifleAnimation.sqf
- addons/common/functions/fnc_getDeathAnim.sqf
- addons/common/functions/fnc_goKneeling.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/explosives/functions/fnc_canDefuse.sqf
- addons/fastroping/functions/fnc_fastRopeLocalPFH.sqf
- addons/fastroping/functions/fnc_fastRopeServerPFH.sqf
- addons/goggles/functions/fnc_applyRainEffect.sqf
- addons/goggles/functions/fnc_applyRotorWashEffect.sqf
- addons/medical_ai/functions/fnc_playTreatmentAnim.sqf
- addons/medical_blood/functions/fnc_handleWoundReceived.sqf
- addons/medical_blood/functions/fnc_onBleeding.sqf
- addons/medical_engine/functions/fnc_setUnconsciousAnim.sqf
- addons/medical_feedback/XEH_postInit.sqf
- addons/nightvision/functions/fnc_onCameraViewChanged.sqf
- addons/nightvision/functions/fnc_onVisionModeChanged.sqf
- addons/scopes/functions/fnc_adjustZero.sqf
- addons/scopes/functions/fnc_canAdjustZero.sqf
- addons/scopes/functions/fnc_canResetZero.sqf
- addons/scopes/functions/fnc_resetZero.sqf
- addons/switchunits/functions/fnc_isValidAi.sqf
- addons/volume/XEH_postInitClient.sqf
- addons/zeus/functions/fnc_bi_moduleArsenal.sqf
- Converts `vehicle _unit == unit` into `isNull objectParent _unit`, it's better and already used in some areas.
> General - Convert vehicle to objectParent

- addons/advanced_throwing/XEH_postInit.sqf
- addons/advanced_throwing/functions/fnc_exitThrowMode.sqf
- addons/advanced_throwing/functions/fnc_prepare.sqf
- addons/advanced_throwing/initSettings.inc.sqf
- addons/advanced_throwing/stringtable.xml
- addons/weather/XEH_postInit.sqf
- addons/weather/functions/fnc_displayWindInfo.sqf
- Make Wind Info indication more permissible, by preventing it from being disabled when looking at the map, carrying, dragging or entering a vehicle (useful for mortar/turret windage correction);
- Temporarily enable Wind Info while in the Advanced Throwing interface, to aid in placing smoke grenades effectively;
> Weather - More permissive wind info indicator + auto-enabling when throwing grenades

- .github/release-drafter.yml
- Adapt Release Drafter for below changes to labels used in this project
I adapted some of our labels in accordance with the use in the past years and what @BaerMitUmlaut applied to ACE-Anvil.
- `kind/Focus Feature` -> `area/focus-feature`
- `kind/feature request` -> `kind/feature`
- `area/translations` -> `kind/translation`
- `kind/bug fix` -> `kind/bug-fix` 
- `ignore changelog` -> `ignore-changelog`
- ~`kind/refactor`~ _(and some other ones that were not widely used)_
Release Drafter now includes only `kind/` labels. Notable example being `area/compatibility` which should always be used in combination with `kind/feature`, `kind/bug-fix` or `kind/change`. We should see less duplicates in the changelog now and those that remain are more likely to …
> Improve GitHub labels and Release Drafter

- addons/optionsmenu/initSettings.inc.sqf
ref https://github.com/acemod/ACE3/blob/master/addons/optionsmenu/init_loadMainMenuBox.sqf#L22-L23
was expecting value set in profileNamespace like how ace_settings used to work
> Options Menu - Fix main-menu news setting not working

- addons/common/stringtable.xml
imho we could also drop the `ACE` because it's already under ace common?
> Common - Add word `weapon` to sway setting

- addons/casings/functions/fnc_createCasing.sqf
- Adds the 2 casings provided by CUP.
> Casings - Add CUP Casings

- addons/yardage450/functions/fnc_turnOn.sqf
Fix #9891
Before the code would spam `74210 cutText ["", "PLAIN"];` each frame
which should be valid, but it does create a new display each time
for some reason the `onUnload` of the last display would run after the `onLoad` of the new display
(apparently fixed in profiling branch)
```
Normal 2.16.151618:
[ACE] (yardage450) TRACE: 2198 before cut: (uiNamespace getVariable "ACE_RscYardage450")=any z\ace\addons\yardage450\functions\fnc_turnOn.sqf:46
"""onLoad"""
[ACE] (yardage450) TRACE: 2198 after cut: (uiNamespace getVariable "ACE_RscYardage450")=Display #-1 z\ace\addons\yardage450\functions\fnc_turnOn.sqf:50
[ACE] (yardage450) TRACE: 2226 before cut: (uiNamespace getVariable "ACE_RscYardage450")=Display #-1 z\ace\addons\yardage450\functions\fnc_turnOn.sqf:46
"""onLoad"""
"""onUnload""" …
```
> Yardage - Fix broken display in 2.16

- addons/interaction/XEH_postInit.sqf
> Interaction - Check `canInteractWith` before taking dropped weapons

- addons/cargo/functions/fnc_initVehicle.sqf
- Title, see https://discord.com/channels/976165959041679380/1224777806647398612/1224777806647398612.
> Cargo - Fix undefined variable

- addons/arsenal/functions/fnc_baseAttachment.sqf
- Title.
- This *assumes* that each attachment that has valid entries redefines them.
- Needs more testing. I tested with RHS, but I want more testing from others.
> Arsenal - Fix `FUNC(baseAttachment)` returning non-CBA item modes

- addons/ai/functions/fnc_garrison.sqf
- addons/common/functions/fnc_switchToGroupSide.sqf
- addons/interact_menu/functions/fnc_collectActiveActionTree.sqf
- addons/interaction/functions/fnc_getDown.sqf
- addons/interaction/functions/fnc_sendAway.sqf
- addons/laser/functions/fnc_seekerFindLaserSpot.sqf
- addons/medical_damage/functions/fnc_interpolatePoints.sqf
- addons/missileguidance/functions/fnc_seekerType_ARH.sqf
- addons/missionmodules/functions/fnc_moduleAmbianceSound.sqf
- addons/overheating/functions/fnc_loadCoolestSpareBarrel.sqf
- addons/overheating/functions/fnc_sendSpareBarrelsTemperaturesHint.sqf
- addons/rangecard/functions/fnc_updateRangeCard.sqf
- addons/repair/functions/fnc_canRepair.sqf
- addons/repair/functions/fnc_getHitPointString.sqf
- addons/repair/functions/fnc_repair.sqf
- addons/spottingscope/CfgVehicles.hpp
- addons/switchunits/functions/fnc_switchUnit.sqf
- addons/vehicle_damage/functions/fnc_processHit.sqf
- addons/vehiclelock/functions/fnc_addKeyForVehicle.sqf
- addons/weaponselect/functions/fnc_fireSmokeLauncher.sqf
- addons/zeus/functions/fnc_moduleSuppressiveFire.sqf
- Title. I might have missed a few, but I think the PR is big enough as it is.
- Part of effort to break up #8801 into smaller PRs.
> General - Change `count` to `isEqualTo` where appropriate

- addons/medical_treatment/functions/fnc_bandageLocal.sqf
- Title.
- This would still throw an error, but at least the unit could be bandaged.
Experienced the following in a test mission:
```
16:37:04 Error in expression <ndage, _bodyPart, _bandageEffectiveness * ace_medical_treatment_bandageEffective>
16:37:04   Error position: <* ace_medical_treatment_bandageEffective>
16:37:04   Error *: Type Bool, expected Number,Not a Number
16:37:04 File /z/ace/addons/medical_treatment/functions/fnc_bandageLocal.sqf..., line 421
16:37:06 Ref to nonnetwork object 564990: <no shape>
16:37:19 Ref to nonnetwork object 565123: <no shape>
16:37:19 Error in expression <ndage, _bodyPart, _bandageEffectiveness * ace_medical_treatment_bandageEffective>
16:37:19   Error position: <* ace_medical_treatment_bandageEffective> …
```
> Medical Treatment - Enforce bandage effectiveness variable type

- docs/wiki/framework/attach-framework.md
- Change tab chars on attach-framework wiki page to space, so the wiki search feature works again
- Replace inline code-text `` with single ` to follow the standard from the other pages
Currently trying to search on the live wiki:
Searching on local hosted wiki with this PR:
> Wiki - Fix search being broken by the attach-framework page

- addons/interact_menu/functions/fnc_collectActiveActionTree.sqf
- title.
Currently consolidated menu runs original condition code before statement but with child custom params. This can lead to error when child params are different to parent params.
Thanks @mrschick for another pointing to problem in #9876.
`_insertChildrenChild` changes are made just for consistency. In fact it can be replaced with `{}` because it looks like it's never used after `fnc_collectActiveActionTree`.
I don't know why this wasn't implemented in #8060 :-(
> Interact menu - Fix condition in consolidated menu

- addons/hearing/CfgEventHandlers.hpp
- addons/hearing/XEH_postInit.sqf
- Title.
- Means that `FUNC(addEarPlugs)` isn't called every time a unit is placed if hearing is off.
> Hearing - Use class EH instead of extended EH

- addons/hearing/functions/fnc_addEarPlugs.sqf
- Title.
- In theory, if a unit's loadout in config would have earplugs, it would add a second pair because it would never check the unit's inventory. However, I haven't actually encountered this because I don't play with hearing enabled, so I don't know how necessary it is.
> Hearing - Add earplugs only if not present

- addons/common/functions/fnc_addToInventory.sqf
- `FUNC(addToInventory)` has been changed so that when you convert explosives using the CBA context menu, you don't have to drop them in order for you to use them. This change can be reverted once the bug in question (https://feedback.bistudio.com/T74244) has been addressed.
> Common - Fix adding unusable throwables

- addons/chemlights/stringtable.xml
- addons/compat_cup_weapons/compat_cup_weapons_nightvision/stringtable.xml
- addons/gunbag/stringtable.xml
- addons/irlight/stringtable.xml
- addons/laserpointer/stringtable.xml
- addons/realisticnames/stringtable.xml
- addons/smallarms/stringtable.xml
- optionals/tracers/stringtable.xml
ref https://github.com/acemod/ACE3/pull/9975
> CUP Compat - Fix NVG Black/Green translations

- addons/medical_treatment/functions/fnc_cprLocal.sqf
- docs/wiki/framework/medical-treatment-framework.md
> Medical Treatment - Fix low SpO2 making units go into cardiac arrest again

- addons/maptools/XEH_postInitClient.sqf
- addons/maptools/functions/fnc_canUseMapGPS.sqf
Fix #10006
Ref #9885
I don't think we even need the itemType check as only gps/uav should fit in that slot?
> Maptools - Fix gps detection

- addons/interact_menu/XEH_clientInit.sqf
- addons/interact_menu/XEH_preInit.sqf
- addons/interact_menu/functions/fnc_addActionToClass.sqf
- addons/interact_menu/functions/fnc_addMainAction.sqf
- addons/interact_menu/functions/fnc_compileMenu.sqf
- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_initMenuReorder.sqf
- addons/interact_menu/functions/fnc_removeActionFromClass.sqf
- addons/interact_menu/functions/fnc_renderActionPoints.sqf
- addons/interact_menu/functions/fnc_splitPath.sqf
- addons/interact_menu/functions/fnc_userActions_getHouseActions.sqf
- addons/interaction/functions/fnc_addPassengerActions.sqf
- Title.
- Optimised the function `ACE_interact_menu_fnc_splitPath`.
> Interact Menu - Use hashmaps for interactions

- addons/arsenal/functions/fnc_onSelChangedRight.sqf
ref https://github.com/CBATeam/CBA_A3/pull/1663
backwards compatible
> Arsenal - Changes for CBA Disposable hashs

- addons/cargo/functions/fnc_addCargoItem.sqf
- addons/cargo/functions/fnc_initVehicle.sqf
- Title.
- Prints warnings if config defined cargo doesn't fit in a vehicle.
> Cargo - Add checks for adding cargo via config

- addons/grenades/functions/fnc_flashbangThrownFuze.sqf
- docs/wiki/framework/grenades-framework.md
> Grenades - Make flashbang detonation sound configurable via config

- addons/csw/functions/fnc_reload_handleReturnAmmo.sqf
- When returning ammo, it could find weapon holders when ammo storage was set to ammo box and vice versa. This changes makes it so it respects the setting strictly.
> CSW - Force `QGVAR(handleExtraMagazinesType)` to be respected

- addons/medical_treatment/functions/fnc_checkResponse.sqf
- addons/medical_treatment/initSettings.inc.sqf
- addons/medical_treatment/stringtable.xml
Adds a new option to the diagnose setting
shows state of patient with clear un-ambiguous language
> Medical Treatment - Allow diagnosing cardiac arrest with clear language

- addons/hearing/CfgEventHandlers.hpp
- addons/hearing/CfgVehicles.hpp
- addons/hearing/CfgWeapons.hpp
- addons/hearing/XEH_PREP.hpp
- addons/hearing/XEH_postInit.sqf
- addons/hearing/XEH_preInit.sqf
- addons/hearing/functions/fnc_earRinging.sqf
- addons/hearing/functions/fnc_explosionNear.sqf
- addons/hearing/functions/fnc_firedNear.sqf
- addons/hearing/functions/fnc_handleRespawn.sqf
- addons/hearing/functions/fnc_hasEarPlugsIn.sqf
- addons/hearing/functions/fnc_moduleHearing.sqf
- addons/hearing/functions/fnc_putInEarplugs.sqf
- addons/hearing/functions/fnc_removeEarplugs.sqf
- addons/hearing/functions/fnc_updateHearingProtection.sqf
- addons/hearing/functions/fnc_updatePlayerVehAttenuation.sqf
- addons/hearing/functions/fnc_updateVolume.sqf
- addons/hearing/initKeybinds.inc.sqf
- addons/hearing/initSettings.inc.sqf
- Title. Cleaned up code not done in #9933.
> Hearing - Code cleanup

- addons/hearing/functions/fnc_updateVolume.sqf
ref #10039
We still want this or sound effects will stack up when tabbed out and then play all at once when tabbing back
> Hearing - prevent audio from stacking when tabbed out

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_disableUserInput.sqf
- addons/common/functions/fnc_setDead.sqf
- addons/field_rations/functions/fnc_handleEffects.sqf
- addons/medical_status/functions/fnc_setDead.sqf
- Title.
- Added to be used in #9988 and other.
> Common - Add `setDead` API

- addons/vehicle_damage/XEH_PREP.hpp
- addons/vehicle_damage/XEH_postInit.sqf
- addons/vehicle_damage/functions/fnc_detonate.sqf
- addons/vehicle_damage/functions/fnc_medicalDamage.sqf
- addons/vehicle_damage/functions/fnc_processHit.sqf
- Requires #10045.
- Fixes medical damage application:
- It would try damage non-local units, making it fail.
- It would injure invulnerable units.
- I've added a new function to address those issues. If medical is not loaded, it will apply vanilla damage to the crew.
> Vehicle Damage - Fix applying medical damage to non-local and invulnerable units

- addons/artillerytables/initSettings.inc.sqf
- addons/cargo/initSettings.inc.sqf
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_cbaSettings_settingChanged.sqf
- addons/cookoff/initSettings.inc.sqf
- addons/csw/initSettings.inc.sqf
- addons/fastroping/initSettings.inc.sqf
- addons/headless/initSettings.inc.sqf
- addons/interact_menu/initSettings.inc.sqf
- addons/interaction/initSettings.inc.sqf
- addons/map/initSettings.inc.sqf
- addons/microdagr/initSettings.inc.sqf
- addons/parachute/initSettings.inc.sqf
- addons/rearm/initSettings.inc.sqf
- addons/refuel/initSettings.inc.sqf
- addons/repair/initSettings.inc.sqf
- addons/sitting/initSettings.inc.sqf
- addons/tagging/initSettings.inc.sqf
- addons/vehicle_damage/initSettings.inc.sqf
- addons/vehiclelock/initSettings.inc.sqf
- addons/viewrestriction/initSettings.inc.sqf
- addons/volume/initSettings.inc.sqf
- addons/weaponselect/initSettings.inc.sqf
- addons/weather/initSettings.inc.sqf
- See https://github.com/acemod/ACE3/pull/10017#discussion_r1622568355.
> General - Cleaned up `cbaSettings_settingChanged`

- addons/common/functions/fnc_addWeapon.sqf
- Adds 2 new parameters:
- `_removeLinkedItems` controls the removal of linked items
- `_magazines` allows the caller to define which magazines, along with ammo count, are inserted into the gun.
- See https://github.com/acemod/ACE3/pull/9539#pullrequestreview-2092076430 (not even needed for that PR anymore).
If magazines are passed the AI is prevented from reloading against our wishes.
- Title of this PR uses our standard …
> Common - Improve `addWeapon`

- addons/vehicle_damage/functions/fnc_abandon.sqf
- docs/wiki/framework/vehicledamage-framework.md
> Vehicle Damage - Add API to prevent AI from dismounting from immobile vehicles

- addons/gunbag/functions/fnc_offGunbagCallback.sqf
- addons/gunbag/functions/fnc_swapGunbagCallback.sqf
- addons/gunbag/functions/fnc_toGunbagCallback.sqf
> Gunbag - Optimise weapon taking/storing code

- addons/compat_rf/compat_rf_realisticnames/stringtable.xml
- addons/mk6mortar/stringtable.xml
- addons/zeus/stringtable.xml
- _Title_
- _RF Drone40 ammo names made more natural_
- _Correction of old wording related to mortars and improvement of mistranslation_
- _Reverted unnecessary equal addition caused by using a spreadsheet_
> Translations - Improve Japanese (Mortar and some)

- addons/compat_cup_units/CfgGlasses.hpp
- addons/compat_cup_units/config.cpp
- Adds ACE Goggles compatibility to CUP facewear.
- Resolves #10054
> Compat CUP Units - Goggles Compatibility

- addons/killtracker/XEH_postInit.sqf
- addons/killtracker/initSettings.inc.sqf
- addons/killtracker/stringtable.xml
- addons/medical_statemachine/functions/fnc_enteredStateDeath.sqf
Follow up to https://github.com/acemod/ACE3/pull/10045#issuecomment-2137912295
- Sends source and instigator to medical's setDead
- Adds a setting to killtracker to show kills from a vehicle to all crew members
before this, kills would usually go to the driver of a vehicle, not the trigger puller
so this setting attempts to mimic and expand that behavior
> Kill Tracker - Add setting to show kills from vehicle to crew

- addons/medical_vitals/functions/fnc_updateHeartRate.sqf
- Since blood volume below class III is always below class II, the condition is unnecessary.
> Medical - Refactor target blood pressure

- addons/artillerytables/functions/fnc_firedEH.sqf
- addons/artillerytables/functions/fnc_rangeTableOpen.sqf
- docs/wiki/framework/artillery-tables-framework.md
> Artillery Tables - Support for ammo that has native `airFriction`

- addons/dogtags/functions/fnc_addDogtagItem.sqf
- addons/dogtags/functions/fnc_canTakeDogtag.sqf
> Dogtags - Drop dogtag on ground if unit doesn't have inventory space

- addons/aircraft/functions/fnc_droneAddActions.sqf
- addons/aircraft/functions/fnc_droneSetWaypoint.sqf
- addons/aircraft/stringtable.xml
- addons/logistics_uavbattery/functions/fnc_canRefuelUAV.sqf
- Add a "Follow Unit" Waypoint Action to Drones, to emulate the vanilla "Follow Unit" behaviour from the UAV Terminal, which is unfortunately only available on other drones unless "friendly map content" is enabled;
- Fix the "recharge" action being shown on destroyed drones;
> Aircraft - Drone "Follow Unit" Waypoint Action

- addons/dogtags/functions/fnc_canTakeDogtag.sqf
- Fixes the whoopsie I did in #10094.
> Dogtags - Stop throwing error when trying to take dog tags

- addons/captives/functions/fnc_canEscortCaptive.sqf
- addons/captives/functions/fnc_canLoadCaptive.sqf
- addons/captives/functions/fnc_doEscortCaptive.sqf
- addons/captives/functions/fnc_handleAnimChangedHandcuffed.sqf
- addons/captives/functions/fnc_handleAnimChangedSurrendered.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- addons/common/functions/fnc_disableAI.sqf
- addons/common/functions/fnc_nearestVehiclesFreeSeat.sqf
- addons/dogtags/functions/fnc_canCheckDogtag.sqf
- addons/dogtags/functions/fnc_canTakeDogtag.sqf
- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- addons/gforces/functions/fnc_pfhUpdateGForces.sqf
- addons/goggles/functions/fnc_canWipeGlasses.sqf
- addons/interaction/functions/fnc_canJoinGroup.sqf
- addons/interaction/functions/fnc_canJoinTeam.sqf
- addons/interaction/functions/fnc_canTapShoulder.sqf
- addons/medical_gui/CfgVehicles.hpp
- addons/towing/functions/fnc_towStateMachinePFH.sqf
> General - Use `ace_common_fnc_isAwake` where possible

- addons/common/functions/fnc_uniqueItems.sqf
- Title.
- For items, it would return duplicates if the unit had multiple containers.
- For magazines, it would return duplicates if the unit had more than 1 magazine of a type.
> Common - Fix `ace_common_fnc_uniqueItems`

- addons/common/functions/fnc_hasItem.sqf
- addons/common/functions/fnc_hasMagazine.sqf
- Title.
- Use `ace_common_fnc_uniqueItems` for `ace_common_fnc_hasMagazine` to improve performance.
> Common - Clean up `ace_common_fnc_hasItem` & `ace_common_fnc_hasMagazine` functions

- addons/dogtags/XEH_postInit.sqf
- addons/dogtags/functions/fnc_addDogtagItem.sqf
- addons/dogtags/functions/fnc_showDogtag.sqf
- Title.
- Name is displayed as "unknown".
> Dogtags - Improve displaying dogtags from bodies with no name

- addons/sitting/functions/fnc_getRandomAnimation.sqf
- addons/sitting/functions/fnc_sit.sqf
- docs/wiki/framework/sitting-framework.md
> Sitting - Add config overwrite for random animation pool

- addons/quickmount/XEH_postInitClient.sqf
- addons/quickmount/functions/fnc_getInNearest.sqf
- When testing ViV, I found that the "Get In" interaction would make the player get into the parent vehicle and not the vehicle being interacted with. This PR fixes that: if an object is passed to the function `getInNearest`, it will be used as the target to mount up in.
- Code cleanup.
> Quickmount - Fix quickmount for vehicle interactions

- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_dragObject.sqf
- Required by and already in #7984, but imo it might take a while until its merged.
> Dragging - Fix dragging/carrying failing for items in ViV

- addons/compat_rhs_afrf3/config.cpp
- addons/compat_rhs_gref3/config.cpp
- addons/compat_rhs_saf3/config.cpp
- addons/compat_rhs_usf3/config.cpp
> RHS Compats - Add `common` to loadorder

- addons/cargo/functions/fnc_loadItem.sqf
- addons/cargo/functions/fnc_unloadItem.sqf
- addons/common/XEH_PREP.hpp
- addons/common/XEH_postInit.sqf
- addons/common/functions/fnc_disableAiUAV.sqf
- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_carryObjectPFH.sqf
- addons/dragging/functions/fnc_dragObject.sqf
- addons/dragging/functions/fnc_dragObjectPFH.sqf
- addons/dragging/functions/fnc_dropObject.sqf
- addons/dragging/functions/fnc_dropObject_carry.sqf
- Adds a new function to common which handles turning off UAV AI, instead of deleting the UAV crew as was done previously.
Cargo doesn't handle UAV crew at all currently, meaning if airbourne vehicles are >100m above the ground and enemies are in sight, the turret shoots when possible.
> Cargo & Dragging - Disable UAV AI when being dragged, carried or cargo

- addons/cargo/functions/fnc_paradropItem.sqf
- Forgot to add this in #10100.
> Cargo - Reenable UAV AI when on ground when paradropped

- addons/medical_ai/XEH_postInit.sqf
- addons/medical_ai/functions/fnc_healUnit.sqf
- addons/medical_ai/functions/fnc_healingLogic.sqf
- addons/medical_ai/initSettings.inc.sqf
- According to the code, if a unit had more than 5 medications in their system they couldn't apply splints. This doesn't make sense to me, so I removed that check.
- `_target` could potentially be `nil` in an instance (I doubt this could happen under normal circumstances, but it's been added as a precaution).
- Setting could add multiple EH, making the replace function run multiple times. This has been rectified by making the setting require a mission restart.
- [Development …
> Medical AI - Fix splints not being applied in special circumstance & setting adding multiple EH

- addons/medical_ai/functions/fnc_healingLogic.sqf
- This ***doesn't*** add full tourniquet support, instead it allows the AI, for the most part, to work around tourniquets used on them by players or other scripted means.
- This PR makes the AI select a non-tourniqueted limb to medic when trying to inject drugs or use IVs. If all limbs are tourniqueted, a random limb is chosen, which will cause the medic to block on the treatment (already the case before this PR, this PR just reduces the chances of this happening).
It also makes AI stabilise bleeding body parts only, so it will ignore tourniqueted limbs.
- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the …
> Medical AI - Make AI take tourniquets into account when medicing

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_switchAttachmentMode.sqf
Maybe needed for https://github.com/acemod/ACE3/pull/10119 and https://github.com/acemod/ACE3/pull/8154
> Common - Add `ace_common_fnc_switchAttachmentMode`

- addons/fire/addon.toml
- addons/fire/functions/fnc_burnSimulation.sqf
- addons/fire/script_component.hpp
`#if has_include` for sqf is evaluated at build time
e.g. the compiled .sqfc was 
`private _damageToAdd = [0.15, _intensity / 10] select (!alive _unit || {0 < (1 + random 0.2)});`
> Fire - Fix medical macros in compiled sqfc

- addons/dogtags/XEH_postInit.sqf
alt to https://github.com/acemod/ACE3/pull/10102
soft-requires https://github.com/CBATeam/CBA_A3/pull/1329
> Dogtags - Rename inventory items via CBA

- addons/medical/dev/test_hitpointConfigs.sqf
improves error for mods with bad configs
before, strange error with no way to tell the cause
` missing ace hitpoints: ["hitleftarm","hitrightarm","hitleftleg","hitrightleg","hithead","hitbody"] - class hitpoints: []`
now:
`gmx_cdf2022_army_uniform_crew_digittsko has invalid uniformClass gmx_cdf2022_army_crew_trg21_ttsko`
> Medical - Gracefully handle bad configs in testHitpoints

- addons/medical_ai/functions/fnc_healingLogic.sqf
- addons/medical_ai/functions/fnc_playTreatmentAnim.sqf
- addons/medical_ai/functions/fnc_requestMedic.sqf
- addons/medical_ai/stateMachine.inc.sqf
- Bring injured unit in a state where CPR is effective (for cardiac arrest induced by blood loss).
- If medic is waiting on blood, allow him to apply splints during that time.
- Prevent AI medics from sending patients into cardiac arrest by using drugs (look at HR and go from there).
- Added triage card and activity logs for AI.
- Prevent adding the same unit twice to the heal queue of a medic.
- Some code cleanup.
- Title of …
> Medical AI - Give blood in Cardiac Arrest before doing CPR

- addons/advanced_ballistics/initSettings.inc.sqf
- addons/field_rations/initSettings.inc.sqf
> Advanced Ballistics/Field Rations - Notify restart requirement

- addons/medical_ai/XEH_PREP.hpp
- addons/medical_ai/XEH_postInit.sqf
- addons/medical_ai/functions/fnc_addHealingCommandActions.sqf
- addons/medical_ai/functions/fnc_healUnit.sqf
- Medics and injured units must be part of the player's group in order to be able to command the AI to heal.
> Medical AI - Add command actions to heal injured units

- docs/wiki/framework/interactionMenu-framework.md
- Add missing information to the Interaction Menu Framework Documentation:
- New table listing interaction exceptions, their parent component and a short (almost redundant) description;
- Complete the Config attribute table with additional interaction parameters `[showDisabled,enableInside,canCollapse,runOnHover,doNotCheckLOS]`, to the best of my knowledge, most of them appear to be not implemented;
> Docs - Add missing info to Interaction Menu Framework

- addons/advanced_ballistics/XEH_postInit.sqf
- addons/common/XEH_preStart.sqf
> Common - Move missing compats warning to pre start

- addons/vehicles/CfgWeapons.hpp
- Title.
- This resolves the Minigun incompatibility issue with Aegis.
- I don't understand why the 7.62mm magazines were added in the first place. They were ported over in https://github.com/acemod/ACE3/commit/9219909ec7cba37155187feda10bd06a258b0008#diff-e9a51ed9e439407632d86afb53fb5bf6fd4a54b7b25c47562fd47955b52cac9cR12, which doesn't make a lot of sense to me, as it's a 6.5mm weapon. We could either leave it as is, add all valid 7.62mm belts or remove the existing 7.62mm belts. Thoughts?
EDIT: Leaving as is for now.
- …
> Vehicles - Remove unneeded magazines

- addons/common/functions/fnc_switchAttachmentMode.sqf
- addons/interaction/functions/fnc_getWeaponAttachmentsActions.sqf
- addons/interaction/functions/fnc_switchWeaponAttachment.sqf
this is for PR #10145
I included `switchAttachementMode` changes from https://github.com/acemod/ACE3/pull/10119
I think we could move this func over to cba and have `CBA_accessory_fnc_switchAttachment` use it as well
simplifies `switchWeaponAttachment` to just do add or removal and moves changing mode to SAM
it had problems with the laser mode not switching because we just passed `[_currentWeapon, _x, ""]` 
so it never did the removal and delay
was also removing extra scopes from inventory
> change interact_SWA to use common_SAM

- addons/medical_feedback/functions/fnc_playInjuredSound.sqf
- Add parameters to allow changing distances for sounds for each severity.
- Add parameter to allow unconscious units to do sounds.
- This does not impact the default functionality.
> Medical Feedback - Add parameters to fnc_playInjuredSound

- addons/csw/CfgMagazines.hpp
- addons/csw/stringtable.xml
- Title. It would only display `40`, instead of how many rounds were left and the maximum possible (e.g. `20/20`).
- Took the stringtable entry from the base game and just changed the number of rounds.
> CSW - Fix round count in GMG belt description

- addons/compat_gm/compat_gm_explosives/CfgMagazines.hpp
- addons/compat_rhs_afrf3/compat_rhs_afrf3_explosives/CfgMagazines.hpp
- addons/compat_rhs_saf3/compat_rhs_saf3_explosives/CfgMagazines.hpp
- addons/compat_rhs_usf3/compat_rhs_usf3_explosives/CfgMagazines.hpp
- addons/compat_spe/compat_spe_explosives/CfgMagazines.hpp
- addons/explosives/CfgMagazines.hpp
- docs/wiki/development/ace3-config-entries.md
- docs/wiki/framework/explosives-framework.md
- Title.
- As far as I can tell, it `ACE_delayTime` was used as a delay when setting up explosives back in 3.0.0. Somewhere along the way it was removed from usage, but still prevailed in mod for some reason.
> Explosives - Remove `delayTime` for explosives, as it no longer serves any purpose

- addons/medical_ai/functions/fnc_healingLogic.sqf
- Bug was introduced in #10158, so it never made it into a release.
- Tourniquets, splints, epinephrine and morphine weren't being consumed, because `_treatmentClass` for those is `""`.
> Medical AI - Fix specific treatment items not being removed

- addons/compat_rhs_afrf3/XEH_postInit.sqf
> RHS Compats - Remove nametags related functions being called if nametags isn't loaded

- addons/arsenal/XEH_PREP.hpp
- addons/arsenal/functions/fnc_saveLoadout.sqf
- docs/wiki/framework/arsenal-framework.md
- Add a public function to save a given loadout
> Arsenal - Add `ace_arsenal_fnc_saveLoadout` as API to save loadouts

- addons/medical_ai/functions/fnc_healingLogic.sqf
- Addresses this comment: https://github.com/acemod/ACE3/pull/10166#issuecomment-2270654786
> Medical AI - Improve tourniquet removal (for #10166)

- addons/medical_ai/functions/fnc_healingLogic.sqf
- addons/medical_ai/functions/fnc_isInjured.sqf
Follow up to #10158
not sure if needed?
but AI would leave a tourniquete on forever and just endlessly pop morphine for the pain 😄
> Medical AI - AI will remove tourniquets

- addons/compat_aegis/$PBOPREFIX$
- addons/compat_aegis/CfgVehicles.hpp
- addons/compat_aegis/config.cpp
- addons/compat_aegis/script_component.hpp
- "Compat" is too strong of a term, the purpose of this is to only overwrite some changes Aegis makes, in order to fix the stuff that is currently broken when loading both Aegis and ACE.
I've added the "ignore-changelog" tag because I don't want people thinking this is an official ACE-Aegis compat, as atm it's only doing fixes. Personally I'm not planning on adding any compatibility, but I decided to add it for future use.
In order to drop the word "compat", the only alternative would be to add this into the vehicles addon directly.
- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the …
> Aegis Compat - Overwrite some Aegis changes

- addons/medical_gui/XEH_postInit.sqf
- addons/medical_gui/initKeybinds.inc.sqf
- Initially part of #9593. but better off as a separate PR.
- Make the postInit easier to read.
- Minor changes, such as removing `false` from the `keyUp` code, as it does nothing and adding a whitespace where needed (old line 53, `_target =_intersectObject`).
> Medical GUI - Make separate file for keybinds

- addons/attach/functions/fnc_attach.sqf
- addons/captives/functions/fnc_handleRespawn.sqf
- addons/captives/functions/fnc_setHandcuffed.sqf
- addons/captives/functions/fnc_setSurrendered.sqf
- addons/common/XEH_postInit.sqf
- addons/explosives/functions/fnc_setupExplosive.sqf
- addons/rearm/functions/fnc_dropAmmo.sqf
- addons/rearm/functions/fnc_grabAmmo.sqf
- addons/rearm/functions/fnc_takeSuccess.sqf
- addons/refuel/functions/fnc_handleDisconnect.sqf
- addons/refuel/functions/fnc_returnNozzle.sqf
- addons/refuel/functions/fnc_startNozzleInHandsPFH.sqf
- addons/refuel/functions/fnc_takeNozzle.sqf
- addons/sandbag/functions/fnc_deploy.sqf
- addons/sandbag/functions/fnc_deployCancel.sqf
- addons/sandbag/functions/fnc_deployConfirm.sqf
- addons/switchunits/functions/fnc_initPlayer.sqf
- addons/tacticalladder/functions/fnc_cancelTLdeploy.sqf
- addons/tacticalladder/functions/fnc_confirmTLdeploy.sqf
- addons/tacticalladder/functions/fnc_positionTL.sqf
- addons/trenches/functions/fnc_placeCancel.sqf
- addons/trenches/functions/fnc_placeConfirm.sqf
- addons/trenches/functions/fnc_placeTrench.sqf
> General - Use `QUOTE(ADDON)` for status effects

- addons/compat_cup_weapons/compat_cup_weapons_explosives/CfgVehicles.hpp
- Use stringtable entries.
- Remove `ace_explosives_offset` attributes (invalid).
> CUP Compat - Improve explosives compat

- addons/common/XEH_postInit.sqf
- addons/explosives/CfgAmmo.hpp
- addons/explosives/XEH_postInit.sqf
- docs/wiki/framework/explosives-framework.md
- Title.
- This would allow explosives that can't be triggered by damage to exist. The APERS mine dispenser is one of those with these changes.
Do we want the APERS mine dispenser not to explode when destroyed?
TODO:
> Explosives - Use `triggerAmmo` instead of `setDamage`

- addons/interact_menu/functions/fnc_compileMenuSelfAction.sqf
- addons/interact_menu/functions/fnc_keyDown.sqf
> Interact Menu - Fix self actions when handcuffed

- addons/explosives/CfgVehicles.hpp
- addons/realisticnames/CfgMagazines.hpp
- addons/realisticnames/compat_explosives/CfgMagazines.hpp
- addons/realisticnames/compat_explosives/CfgVehicles.hpp
- addons/realisticnames/compat_explosives/config.cpp
- addons/realisticnames/compat_explosives/script_component.hpp
- Title.
- Use base game stringtable entries for correct names in `explosives`'s CfgVehicles.
- Add a subcomponent to realistic names that loads dynamically to rename them.
> Explosives/Realistic Names - Improve CfgVehicles explosives naming

- addons/headless/functions/fnc_transferGroups.sqf
- `_trasnfer` in headless transfer groups is never set to true, so no groups ever transfer
> Headless - Fix unable to transfer groups

- addons/compat_sog/CfgAmmo/explosives.hpp
- addons/explosives/functions/fnc_detonateExplosive.sqf
- Follow up to #10182.
- Never mentioned in the documentation, so not considered API imo.
- This means that SOG explosives placed via ACE no longer blow up when destroyed.
> Explosives - Remove replacement explosives

- addons/arsenal/functions/fnc_sortStatement_mod.sqf
- Title. It was printing `ModParams - Undefined or empty mod directory` for base game weapons, because their addon is `""`.
> Arsenal - Fix `modParams` printing messages in RPT

- docs/tools/document_functions.py
- Title. At the moment, all functions are not alphabetically sorted (e.g. https://ace3.acemod.org/wiki/functions/explosives).
- When hosting the website locally, no changes are needed to have it alphabetically sorted, but I don't have the same SW versions.
- It's not efficient, but it does the job.
> Docs - Force functions to be alphabetically sorted on wiki

- addons/explosives/CfgMagazines.hpp
- addons/explosives/functions/fnc_addDetonateActions.sqf
- addons/explosives/functions/fnc_addExplosiveActions.sqf
- Title. Currently, the explosives interactions for the APERS mine dispenser and the training mine include "descr. short", which is ugly imo and can be avoided.
- There are two solutions to the problem described above: The first is that we make explosives use `displayName` directly (so what this PR does). Having loaded RHS & CUP, no CUP explosives set `displayNameShort` and only the WW2 mines in RHS set it. Given explosives have no submenus, imo it's acceptable and moreover necessary to use `displayName` directly, as some of the RHS `displayNameShort` are identical for 2 mines.
The other solution is to set `displayNameShort` (which was previously used as a 1st priority) to `""`  for the APERS mine dispenser and the training mine (see first commits). …
> Explosives - Use full magazine name in interaction menu

- .hemtt/project.toml
- Use `extends` for non-default launch presets
> HEMTT - Use extends for launch presets

- addons/magazinerepack/functions/fnc_canRepackMagazine.sqf
- addons/magazinerepack/functions/fnc_getMagazineChildren.sqf
- docs/wiki/framework/magazine-repack-framework.md
- Adds optional ability to disable magazine repacking by `CfgMagazines` entry.
> Magazine Repack - Add ability to disable repacking via class

- addons/intelitems/CfgWeapons.hpp
- addons/intelitems/XEH_postInit.sqf
- addons/intelitems/config.cpp
- addons/medical_treatment/CfgWeapons.hpp
- addons/medical_treatment/XEH_postInit.sqf
- addons/medical_treatment/config.cpp
- addons/overheating/CfgWeapons.hpp
- Fixes painkillers, notepad and spare barrel not being available in the "equipment storage" attribute in the editor.
- It's either this (or some variant of item replacement) or we rewrite the attribute's function to accommodate.
> General - Add replacement items for editor inventory management

- addons/compat_gm/CfgVehicles.hpp
- addons/compat_gm/compat_gm_refuel/CfgVehicles.hpp
- addons/compat_gm/compat_gm_repair/CfgVehicles.hpp
- addons/compat_gm/compat_gm_repair/config.cpp
- addons/compat_gm/compat_gm_repair/script_component.hpp
- addons/compat_gm/compat_gm_trenches/CfgVehicles.hpp
- addons/compat_gm/compat_gm_trenches/config.cpp
- addons/compat_gm/compat_gm_trenches/script_component.hpp
- Adds #6144 to GM vehicles.
- Requires #10233 to work properly, but doesn't strictly need it.
- Replaced text with string table entries for helicopter doors.
> GM Compat - Add interaction anims to GM vehicles

- addons/compat_spe/CfgVehicles/wheeled.hpp
- addons/compat_spe/compat_spe_refuel/CfgVehicles.hpp
- addons/compat_spe/compat_spe_repair/CfgVehicles.hpp
- addons/compat_spe/compat_spe_repair/config.cpp
- addons/compat_spe/compat_spe_repair/script_component.hpp
- addons/compat_spe/compat_spe_trenches/CfgVehicles.hpp
- addons/compat_spe/compat_spe_trenches/config.cpp
- addons/compat_spe/compat_spe_trenches/script_component.hpp
- Adds #6144 to SPE vehicles.
- The number of tracks received from vehicles such as the Panther, Jagdpanther and Tiger is lower than the visual amount of tracks. The reason is a bit balancing (Tiger would be spawning in 26 Tracks, Panther & Jagdpanther would be 6), which imo is excessive.
> SPE Compat - Add interaction anims to SPE vehicles

- addons/interaction/functions/fnc_initAnimActions.sqf
e.g.
```
cursorObject setVariable ["ace_interaction_animsItems_crate_l1_unhide", []];
```
to disable unloading ammo boxes
this pr provides some basic feedback on why nothing happens
> Interaction - Give some feedback if action is disabled

- addons/interaction/functions/fnc_initAnimActions.sqf
- According to the wiki, `animateSource` is better in MP (https://community.bistudio.com/wiki/animateSource). Testing in SP suggests all existing interactions work as before.
> Interaction - Use `animateSource` instead of `animate` for interaction anims

- addons/common/functions/fnc_getVehicleIcon.sqf
- Suggests a possible fix when the ".paa" extension is not included\*.
- This specifically would fix GM's vehicle icons not being retrieved.
\* Apparently the ".paa" on a vehicle's icon config entry is optional.
> Common - Make `FUNC(getVehicleIcon)` check for strings without the .paa extension

- addons/cargo/CfgVehicles.hpp
- Fixes #10262.
- Fixes the IDAP 10 & 40 cargo containers not having any cargo.
- Removed `Land_Cargo40_vr_F`, as it doesn't exist in the base game.
- Removed unnecessary XEH definitions. I've been unable to find out why they were added in the first place.
- Removed unnecessary inheritance stuff.
> Cargo - Fix missing cargo box sizes & cleanup

- addons/dragging/functions/fnc_setCarryable.sqf
- addons/dragging/functions/fnc_setDraggable.sqf
- Title.
- Cleaned up headers.
- Return `nil`, to avoid returning action path.
> Dragging - Add parameters check for `FUNC(setDraggable)` & `FUNC(setCarryable)`

- addons/mk6mortar/stringtable.xml
- Improve English and German entries for `STR_ACE_Mk6Mortar_airResistanceEnabled_Description`.
- Removed `Does not affect AI mortars.` (and all translations of it) from `STR_ACE_Mk6Mortar_useAmmoHandling_Description`, because it affects all mortars.
> Mk6 Mortar - Improve and correct string table entries

- addons/common/XEH_postInit.sqf
- addons/csw/functions/fnc_initVehicle.sqf
- addons/csw/functions/fnc_proxyWeapon.sqf
- addons/csw/functions/fnc_staticWeaponInit_unloadExtraMags.sqf
- Title.
- ~~`FUNC(initVehicle)`: Nothing guarantees that the CSW will still be local in the next frame, so better to see if CSW is local in the next frame.~~ Addressed in  #10273, by removing the delay by a frame.
- `FUNC(proxyWeapon)`: Both calls to it (with the change above) check if the turret is local and quit if it isn't, so it should be fine. My worry is if it's called from a 3rd party, but idk how likely that is, so I'm unsure how needed this change is.
- `FUNC(staticWeaponInit_unloadExtraMags)`: Removes magazines from all turrets, a frame after the vehicle has been initialised, which technically leaves some time for a unit to be moved into a turret, which could force a locality switch if said unit is remote.
- If the contribution affects …
> CSW - Handle turret locality safer

- addons/csw/functions/fnc_assemble_deployTripod.sqf
- addons/csw/functions/fnc_assemble_deployWeapon.sqf
- addons/csw/functions/fnc_initVehicle.sqf
- addons/csw/functions/fnc_staticWeaponInit_unloadExtraMags.sqf
- Turn off vanilla assembly for placed tripods and assembled CSWs, so that `FUNC(initVehicle)` can handle enabling/disabling vanilla assembly when the `QGVAR(assemblyMode)` is set on the vehicle.
- Only set the status effect where the gunner's turret is local. Until now, every machine set a status effect that has a global effect, which is useless.
- Removed the `execNextFrame` in `FUNC(initVehicle)`, because it runs 1 second after a vehicle has been created, so no need for the frame of delay.
- Optimised `FUNC(staticWeaponInit_unloadExtraMags)` slightly (from #9901).
- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on …
> CSW - Improve "disableWeaponAssembly" status effect usage

- .hemtt/launch.toml
- .hemtt/lints.toml
- .hemtt/project.toml
- Safe for CI to merge before the release of HEMTT 1.13.0, but will temporarily break `hemtt launch` on master until HEMTT 1.13.0
- Moves launch configs to `launch.toml`
- Creates `lints.toml` and ignores broken commands ACE is using
> HEMTT - Update for 1.13

- docs/wiki/framework/disposables-framework.md
- docs/wiki/framework/dragging-framework.md
- docs/wiki/framework/grenades-framework.md
- docs/wiki/framework/javelin-framework.md
- Better warning for deprecation of disposable framework (copied from the settings one).
- Remove non-public warning of dragging functions, because headers say they are public.
- 2 Grenade titles weren't correct.
- Fixed minor typo in Javelin.
> Docs - Misc fixes

- addons/medical_treatment/functions/fnc_hasItem.sqf
- addons/trenches/functions/fnc_hasEntrenchingTool.sqf
- addons/vehiclelock/functions/fnc_hasKeyForVehicle.sqf
> General - Use `findAny` where possible

- .github/workflows/arma.yml
- .github/workflows/extensions.yml
- .github/workflows/hemtt.yml
- ~~Fix HEMTT CI annotations not shown since HEMTT v1.11. This was fixed by arma-actions/hemtt#2.~~ Edit: Tag was updated.
- Fix HEMTT artifacts not uploaded. `actions/upload-artifact` v4.4 changed the behavior of hidden files. They're now excluded by default [[Source]](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes).
- Bump up [`actions/upload-artifact` in `extensions.yml`](https://github.com/Timi007/ACE3/blob/e23a26da1c0ca940b5e4c03aa9661cf3868b91c0/.github/workflows/extensions.yml#L60) to v4 since [v2 is already deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), …
> CI - Fix HEMTT CI artifacts not uploaded

- addons/common/XEH_PREP.hpp
- addons/common/functions/fnc_addExplosionEventHandler.sqf
- addons/hearing/XEH_postInit.sqf
- addons/hearing/functions/fnc_explosion.sqf
Add an explosion event handler to common so multiple systems can hook into the same event
- Local event
- ace_hearing take the local event and re-broadcasts
(might be worthwhile to only broadcast to close-distance units?)
> Common - Add `ace_common_fnc_addExplosionEventHandler`

- addons/trenches/XEH_preInit.sqf
- addons/trenches/XEH_preStart.sqf
- Save entrenching tools to a hash map on preStart instead of saving code
> Trenches - Make entrenching tool cache use hashMap

- addons/compat_rf/CfgVehicles.hpp
- addons/compat_rf/config.cpp
Adds config properties for reaction forces vehicles which can carry drinking water.
> Compat RF - Field Rations - Watersource Offsets

- addons/compat_spe/CfgMagazines/csw.hpp
- 50 round .30-06 belts for the M1919 are linkable belts as far as I can tell, so I made them linkable.
- Don't set `ACE_isBelt = 0;` on all 7.92x57 Gurttrommeln, imo there's no reason to.
- Make the .50 BMG belt linkable.
> SPE Compat - Make 50Rnd M1919 & M2 100Rnd belts linkable

- docs/wiki/framework/crew-served-weapons-framework.md
- Explicitly say that a proxy weapon is optional.
- Document that proxy weapon entry can be a function name. In ACE, it's only used in the mortar framework, but that will be removed with #9238. Question is: Do we really want to add it as API or leave it undocumented?
> Docs - Update CSW proxy weapon information

- README.md
- docs/README_DE.md
- docs/README_PL.md
> Docs - Updated C/C++ to Rust

- addons/advanced_fatigue/CfgEden.hpp
Without arma crashes with
```
ErrorMessage: File z\ace\addons\advanced_fatigue\CfgEden.hpp, line 5: Config: End of line encountered after 
Application terminated intentionally
```
> Advanced Fatigue - Fix config macro

- addons/vehicle_damage/functions/fnc_handleCookoff.sqf
`_source` was being shadowed
`_injurer` didn't exist
> Adv Vehicle Damage - Fix cookoff event args

- addons/missileguidance/functions/fnc_doAttackProfile.sqf
- addons/missileguidance/functions/fnc_guidancePFH.sqf
Shoot ace dagr without any laser source and it spams
`[ACE] (missileguidance) ERROR: attack profile [LIN] returned bad pos [0,0,0]`
this restores to how it worked before rewrite (see line 51)
another possibility is to change `_pitchRate` to 0 if an attack profile wants to fly straight, but this felt like the simplest way and should have the best backward compatibility
> Missile Guidance - Allow attackProfiles to return [0,0,0]

- addons/interaction/CfgVehicles.hpp
- Fix unlocalized `"$str_assign_main"` in `ACE_TeamManagement` - The string is correct, but the "$STR" part is [case sensitive.](https://community.bistudio.com/wiki/Stringtable.xml#Config)
> Interaction - Fix unlocalized string in ACE_TeamManagement

- addons/cargo/XEH_postInit.sqf
- addons/cargo/stringtable.xml
- Title
- Should help when deciding what to load in a vehicle.
- Not super happy with the icon I choose, if someone has a better one I'm happy to change it.
> Cargo - Add an action to check size of cargo object

- addons/medical_treatment/functions/fnc_diagnose.sqf
> Medical Treatment - Fix script error on diagnosing dead patient in basic

- addons/dragon/functions/fnc_onFired.sqf
- addons/maptools/functions/fnc_isInsidePlottingBoard.sqf
> Maptools - Fix undefined macro for plotting board

- addons/vehicle_damage/functions/fnc_handleDamage.sqf
> Vehicle Damage - Fix zeus end keybind not killing units

- addons/hearing/functions/fnc_explosion.sqf
- Title.
This makes a grenade @ 10m equivalent to a ~50 round burst from a .50 BMG static. Manageable with earpro, but still quite loud when closer. Grenades exploding at a player's feet will still blow out their eardrums, but hey, realism.
> Hearing - Tone down strength of explosion hearing damage

- addons/hearing/stringtable.xml
- addons/hitreactions/stringtable.xml
> Translations - Japanese

- tools/stringtable_sort.py
- Continuation of #6446.
- Improved by taking all stringtables into account (didn't take subaddons into account before)
- Added: Sort languages as well, with English always being at the top (otherwise an error is printed)
Unfortunately, the XML parser ignores comments and when writing after having sorted, it leaves a blank line where the comment originally was, which makes `stringtable_validator.py` throw an error.
I'm not sure how to handle comments if we sort, maybe we should ban them in string tables?
Furthermore, I'm not sure when and if we want to run this automatically. It might cause more merge conflicts if it's run every time something is merged to master. Thoughts?
- If the contribution affects [the …
> Tools - Add script to sort all stringtables

- addons/arsenal/missions/Arsenal.VR/initPlayerLocal.sqf
- addons/zeus/functions/fnc_ui_searchArea.sqf
- Ref https://github.com/BrettMayson/HEMTT/pull/806
> Common - Improve MarkerLocal

- addons/cookoff/functions/fnc_handleDamageBox.sqf
> Cookoff - Fix zeus end keybind not killing ammo containers

- addons/medical_gui/functions/fnc_updateBodyImage.sqf
- Would previously throw errors because of incompatible types.
> Medical - Fix limb damage in medical menu

- docs/wiki/feature/arsenal.md
- Uses the extension for reading now
> Docs - Remove outdated Arsenal keybind warning

- addons/overheating/functions/fnc_getWeaponData.sqf
- Save the config path to the given weapon to a variable, and using that instead
- There are not functionality changes in this PR.
> Overheating - Improve `getWeaponData` by saving weapon config to variable

- addons/common/XEH_preInit.sqf
- addons/common/functions/fnc_statusEffect_addType.sqf
- addons/common/functions/fnc_statusEffect_resetVariables.sqf
- addons/common/functions/fnc_statusEffect_sendEffects.sqf
Alt to #10468
Allows custom event names for status effects
Switch to hashmap
> Common - Allow custom event name for status effects

- addons/medical/XEH_PREP.hpp
- addons/medical/functions/fnc_fullHeal.sqf
- addons/medical_treatment/functions/fnc_fullHeal.sqf
- Add a public API function to full heal a unit
- This is just a wrapper with some param checking
- Add optional parameter to `medical_treatment_fnc_fullHeal` to not add the full heal log message
> Medical - Add API for fully healing a unit

- addons/advanced_throwing/functions/fnc_drawThrowable.sqf
- addons/advanced_throwing/functions/fnc_exitThrowMode.sqf
- addons/advanced_throwing/functions/fnc_prepare.sqf
- addons/advanced_throwing/functions/fnc_prime.sqf
- Grenades with multiple rounds (e.g. SOG's `vn_v40_grenade_mag`) would not behave nicely with advanced throwing, which was hard coded to only handle grenades with 1 round.
> Advanced Throwing - Fix multiple round grenades

- addons/markers/functions/fnc_canTimestamp.sqf
- addons/markers/stringtable.xml
Updates the checks in the fnc_canTimestamp.sqf to also check for GPS and UAV's.
@BOT-Garry and @DartRuffian rubbed their braincells together for this one.
> Markers - Improve Timestamps check for GPS/UAV Terminals

- addons/nightvision/XEH_postInit.sqf
- Launch mp from 3den
- "SlotItemChanged" event never fires
(other use of this eh in map and hearing both seem to be ok)
> Nightvision - Fix when in 3den multiplayer

- addons/refuel/XEH_postInit.sqf
- Refuel sources defined via the eden editor attributes didn't have their fuel added, as the `QGVAR(initSource)` EH was registered too late, making it miss all calls at mission start. Even if the EH was registered earlier, the actions weren't.
This PR moves both the EH and actions into post init, not waiting for the CBA settings to be initialised.
- See: https://discord.com/channels/976165959041679380/1312983103551045733/1312983103551045733
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, …
> Refuel - Fix editor fuel sources

- addons/cookoff/XEH_postInit.sqf
- addons/cookoff/functions/fnc_detonateAmmunitionServer.sqf
- addons/cookoff/functions/fnc_detonateAmmunitionServerLoop.sqf
- addons/cookoff/functions/fnc_isMagazineFlare.sqf
Shoot `m-atv (hmg)` with rocket
` _object addMagazineAmmoCargo [_magazineClassname, -1, _ammoCount];`
has no effect on vehicles that are not alive
so mags are never removed
and cookoff effect never ends
> Cookoff - Fix endless loop on dead vehicles

- addons/fastroping/CfgVehicles.hpp
- addons/intelitems/CfgVehicles.hpp
```
Warning: Cannot evaluate ''
âž¥ Context: bin\config.bin/CfgVehicles/ACE_friesBase.ACE_friesBase
->Last modified by: ace_fastroping
Warning: Cannot evaluate 'DesturctNo'
âž¥ Context: bin\config.bin/CfgVehicles/ace_intelitems_base.ace_intelitems_base
->Last modified by: ace_intelitems
```
not entirely sure, but this seems to be the intention
warning seems new (might only be on profiling build)
> Fastrope/IntelItems - Fix destType

- addons/medical_ai/functions/fnc_isInjured.sqf
- Title.
- If you set their blood to below the stable limit, they wouldn't be considered as injured and not get any treatment.
> Medical AI - Add missing blood as an injury condition

- addons/medical_treatment/functions/fnc_treatment.sqf
- addons/medical_treatment/functions/fnc_useItem.sqf
> Medical Treatment - Add missing bools for creating litter

- addons/advanced_throwing/functions/fnc_renderPickUpInteraction.sqf
- addons/cookoff/XEH_postInit.sqf
- addons/explosives/functions/fnc_interactEH.sqf
- addons/fastroping/functions/fnc_cutRopes.sqf
- addons/frag/functions/fnc_dev_clearTraces.sqf
- addons/grenades/functions/fnc_incendiary.sqf
- addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf
- addons/logistics_wirecutter/functions/fnc_interactEH.sqf
- addons/spectator/functions/fnc_cam.sqf
- addons/spectator/functions/fnc_ui_handleKeyDown.sqf
- addons/tagging/functions/fnc_createTag.sqf
> General - Use 2.18 syntax of `deleteVehicle`

- addons/explosives/functions/fnc_interactEH.sqf
- Title.
Depending on how dense the mines are, just switching from `allMines` to `nearestMines` is >10x speedup. Switching from `typeOf` to `configOf` is 2x.
> Explosives - Optimise mine interaction code

- addons/markinglaser/functions/fnc_onAircraftInit.sqf
`[ACE] (markinglaser) WARNING: Class CUP_O_Mi8_SLA_1 does not have a pilot camera nor a turret that could be equipped with an IR marking laser.`
fairly common for transport helicopters
> Marking Laser - Change warning to info

- addons/attach/functions/fnc_attach.sqf
- addons/attach/stringtable.xml
- addons/explosives/functions/fnc_setupExplosive.sqf
- addons/explosives/stringtable.xml
- addons/interaction/groupRename_GUI.hpp
- addons/interaction/stringtable.xml
- addons/marker_flags/functions/fnc_placeFlag.sqf
- addons/marker_flags/stringtable.xml
- addons/refuel/stringtable.xml
> General - Use `common`'s cancel stringtable entry

- addons/compat_sog/CfgMagazines/food.hpp
- Title
- Add 2x rice sacks as food sources.
> Compat SOG - Add field rations to 'Survival' tab in arsenal

- addons/fire/compat_medical_engine/ACE_Medical_Treatment_Actions.hpp
- addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
- addons/medical_treatment/functions/fnc_treatment.sqf
- addons/medical_treatment/initSettings.inc.sqf
- addons/medical_treatment/stringtable.xml
- Add "Skilled" Variants of the treatment time setting for 
- Auto-Injector
- Tourniquet
- IV Bag
- Splint
"Skilled" is defined as exceeding the required skill level for treatment. 
Eg If anyone can do it then skilled is Medic or Doctor
If a Medic is required, then Skilled is a Doctor
> Add Separate Treatment Times for Exceeding Required Skill level

- addons/fastroping/functions/fnc_fastRopeLocalPFH.sqf
- Holster your weapon after reaching the ground.
IMO reaching the ground and being instantly ready to fire is a bit immersion breaking.
I don't think there is a way to have the weapon holstered **before** running the fastroping animation? Holstering before L39 doesn't work.
> Fastroping - End descent with weapon holstered

- addons/advanced_ballistics/functions/fnc_diagnoseWeapons.sqf
- addons/rangecard/functions/fnc_updateRangeCard.sqf
- addons/xm157/functions/fnc_ballistics_getData.sqf
- extension/src/ballistics/zero.rs
`"ace" callExtension ["ballistics:zero_advanced",[200,0,6.69248,15,1013.25,0,0.5,1,"ICAO"]]`
will crash game, key number probably is 2nd (muzzle velocity of 0)
can reproduce with western sahri AA12
todo:
```
panicked at extension\src\ballistics\drag.rs:167:45:
attempt to subtract with overflow
```
> Rangecard - fix CTD on weapons with invalid configs

- addons/compat_aegis/compat_aegis_hearing/CfgWeapons.hpp
- addons/compat_aegis/compat_aegis_hearing/config.cpp
- addons/compat_aegis/compat_aegis_hearing/script_component.hpp
- addons/hearing/CfgWeapons.hpp
- addons/hearing/script_macros_hearingProtection.hpp
> Compat Aegis - Remove EHP from Beanies

- addons/field_rations/CfgVehicles.hpp
- addons/field_rations/XEH_postInit.sqf
- addons/field_rations/functions/fnc_addWaterSourceInteractions.sqf
- addons/field_rations/functions/fnc_checkWater.sqf
- addons/field_rations/functions/fnc_drinkFromSource.sqf
- addons/field_rations/functions/fnc_refillItem.sqf
Changes moved here from #10675.
- Add water actions directly to the vehicle instead of the helper object if the vehicle has no custom `"waterActionPosition"`.
This was causing the helper object to be attached to the center of the vehicle, making the interaction almost impossible to access from the outside.
- Allow accessing the water source of vehicles with no custom `"waterActionPosition"` from the inside.
> Field Rations - Improve Vehicle Watersource Actions

- addons/medical_damage/ACE_Medical_Injuries.hpp
- addons/medical_damage/functions/fnc_woundReceived.sqf
- Title.
Alternatively, can check for `QUOTE(ADDON) in _handlerName`. We can ignore our own API within this component.
> Medical Damage - Throw no errors for the last damage handler

- .vscode/tasks.json
- tools/build_current_addon.py
- Add a task to just build the given addon
- E.g. Doing `Ctrl+Shift+P` -> `Run: Task` -> `Build: HEMETT -just` and writing `common` will run `hemtt build --just common`
> Tools - Add a VS Code task to just build a given addon

- addons/hearing/XEH_postInit.sqf
If "Only units with heavy weapons" selected auto add earplugs not working on dedicated server because cache variable does not exist on server without interface.
Cache should exist on client and server.
On client getAmmoLoudness called from firedNear.
On server from addEarPlugs
> Hearing - Earplugs not added on dedicated server

- addons/missile_sdb/CfgAmmo.hpp
- Remove IR guidance capability from ammo
Technically this doesn't change anything as far as using goes, but any guides/tooltips created via script would show ability for it to lock via laser
> missile_sdb - Fix IR guidance

- addons/missile_aim120/CfgAmmo.hpp
- addons/missile_aim120/CfgWeapons.hpp
- Change aim120d model to aim120c (pointy tip - 120d has minor visual difference to c in real life, BI didn't predict properly)
- TextureTypes from https://github.com/acemod/ACE3/pull/10768 because I'm blind
> missile_aim120 - Visual enhancements

- addons/attach/functions/fnc_detach.sqf
- addons/captives/functions/fnc_doBlindfoldCaptive.sqf
- addons/csw/functions/fnc_reload_handleReturnAmmo.sqf
- addons/hearing/functions/fnc_removeEHP.sqf
- addons/hearing/functions/fnc_removeEarplugs.sqf
- addons/interaction/functions/fnc_switchWeaponAttachment.sqf
- addons/magazinerepack/functions/fnc_canRepackMagazine.sqf
- addons/magazinerepack/functions/fnc_getMagazineChildren.sqf
- addons/magazinerepack/functions/fnc_startRepackingMagazine.sqf
> General - Replace `CBA_fnc_canAddItem` with `canAdd`

- addons/medical_damage/functions/fnc_woundsHandlerVehiclecrash.sqf
- addons/medical_damage/functions/fnc_woundsHandlerVehiclehit.sqf
```
[ACE] (medical_damage) ERROR: Wound handler 'ace_medical_damage_woundsHandlerVehiclehit' missing latest param in return readding. This will be deprecated in the future check Medical Framework wiki.
> Medical Damage - Fix wound handler returns

- addons/compat_cup_vehicles/CfgVehicles.hpp
- Close #10789 
- It's difficult to find out exactly which vehicles had this system or an analogue of it, but it seems that rudimentary versions were available as early as the M47 Patton and T-55
> Compat - CUP - Add hunterkiller to most CUP tanks and some IFVs

- addons/fortify/functions/fnc_canFortify.sqf
- addons/trenches/functions/fnc_hasEntrenchingTool.sqf
Fix #10799
could also have `ace_common_fnc_uniqueItems` return a copy, but most times that isn't needed
> Fortify/Trenches - Fix blowing-up uniqueItems cache

- addons/advanced_ballistics/RscTitles.hpp
- addons/arsenal/Cfg3DEN.hpp
- addons/artillerytables/RscRangeTable.hpp
- addons/atragmx/RscTitles.hpp
- addons/attach/CfgVehicles.hpp
- addons/common/define.hpp
- addons/compat_spe/CfgAmmo/bullets.hpp
- addons/compat_spe/CfgAmmo/shells.hpp
- addons/dragon/CfgAmmo.hpp
- addons/dragon/CfgVehicles.hpp
- addons/field_rations/CfgMoves.hpp
- addons/frag/CfgAmmo.hpp
- addons/goggles/CfgGlasses.hpp
- addons/grenades/CfgAmmo.hpp
- addons/grenades/CfgMagazines.hpp
- addons/hot/CfgAmmo.hpp
- addons/kestrel4500/RscTitles.hpp
- addons/laserpointer/script_macros_config.hpp
- addons/map/MapTweaks.hpp
- addons/missile_clgp/CfgAmmo.hpp
- addons/mx2a/CfgWeapons.hpp
- addons/rangecard/RscTitles.hpp
- addons/spottingscope/CfgVehicles.hpp
- addons/spottingscope/CfgWeapons.hpp
- addons/vector/CfgWeapons.hpp
- addons/vehicles/CfgVehicles.hpp
- addons/weather/RscTitles.hpp
- addons/xm157/RscInGameUI.hpp
- addons/yardage450/CfgWeapons.hpp
- optionals/realisticdispersion/CfgWeapons.hpp
- Unquote math that HEMTT can do at compile time
Related discussion, should HEMTT also want numbers in strings to be just numbers? Like `w = "1";`, should it suggest doing `w = 1;`?
> Common - Unquote math

- addons/disarming/CfgEventHandlers.hpp
- addons/disarming/XEH_PREP.hpp
- addons/disarming/functions/fnc_canBeDisarmed.sqf
- addons/disarming/functions/fnc_canPlayerDisarmUnit.sqf
- addons/disarming/functions/fnc_disarmDropItems.sqf
- addons/disarming/functions/fnc_eventCallerFinish.sqf
- addons/disarming/functions/fnc_eventTargetFinish.sqf
- addons/disarming/functions/fnc_eventTargetStart.sqf
- addons/disarming/functions/fnc_getAllGearContainer.sqf
- addons/disarming/functions/fnc_getAllGearUnit.sqf
- addons/disarming/functions/fnc_openDisarmDialog.sqf
- addons/disarming/functions/fnc_showItemsInListbox.sqf
- addons/disarming/functions/fnc_verifyMagazinesMoved.sqf
- addons/disarming/gui_disarm.hpp
- Title.
- Header fixes.
- Optimisations.
- Changes:
- Use `lifeState` instead of `getVariable "ACE_isUnconscious"` for unconsciousness.
- Players can only disarm units that are either in the same vehicle as them or if player and target are both on foot.
Not too sure about this change, but imo it's weird to be able to disarm a person in a vehicle, when you are not in it.
- Title of this PR uses our standard template …
> Disarming - Code cleanup

- addons/missileguidance/XEH_postInit.sqf
- Fix MCLOS direction error
The controls were named wrong. The comments changed show that left was always bound to right, and vice versa.
Strictly speaking, not tested in game. But this is realistically the only path which this got changed so it should work - hopefully.
> missileguidance - fix MCLOS direction error

- addons/laser/functions/fnc_addLaserTarget.sqf
This primarily effects marking laser module
before the laser origin would be model's center
now properly from the targeting pod
> Laser - Fix getting laser position from aircraft `pilotCamera`

- addons/compat_cup_vehicles/CfgVehicles.hpp
fix
```
Updating base class CUP_M60A3_Base->Tank_F, by z\ace\addons\compat_cup_vehicles\config.cpp/CfgVehicles/CUP_M60A3_TTS_Base/ (original CUP\TrackedVehicles\CUP_TrackedVehicles_M60\config.bin)
Updating base class CUP_T72_Base->Tank_F, by z\ace\addons\compat_cup_vehicles\config.cpp/CfgVehicles/CUP_T72_ACR_Base/ (original CUP\TrackedVehicles\CUP_TrackedVehicles_T72\config.bin)
```
> compat_cup - Fix T72 and M60 inheritance

- addons/common/functions/fnc_checkVersionNumber.sqf
- Ignore ACEX addons in PBO version check
All ACEX CfgPatches classes have equivalent ACE CfgPatches classes and only exist for BWC. Therefore, the normal ACE version check should already cover all ACEX addons. We don't need to check them a second time.
> Common - Remove ACEX addons from PBO version check

- addons/repair/initSettings.inc.sqf
Increased maximum value limit of setting `ace_repair_miscRepairTime` from 60 to 3600.
Increased maximum value limit of setting `ace_repair_wheelChangeTime` from 60 to 3600.
**Why?**  
Some TvT servers play a mission for hours, and maximum repairing time for 60 seconds isn't enough.
For example, we prefer to set repairing time to 15 minutes
> Repair - Change max time limits

- AUTHORS.txt
- addons/safemode/XEH_postInit.sqf
- addons/safemode/functions/fnc_lockSafety.sqf
- addons/safemode/stringtable.xml
- Add a new Keybind to `ACE Weapons` that allows to bind unlock safemode only to a key
> Safemode - Add new unlock only keybind

- addons/advanced_throwing/XEH_postInit.sqf
- addons/advanced_throwing/XEH_preInit.sqf
- addons/advanced_throwing/functions/fnc_drawThrowable.sqf
- docs/wiki/framework/advanced-throwing-framework.md
Create a simple GVAR in advanced throwable to enable mod authors to hide the grenade preview with alternative animations are sought. 
CBA Setting not created to mitigate settings bloat. 
Discussed on Discord in ace3-dev
> Advanced Throwing - Add GVAR so mod authors can disable grenade preview during preparation.

- addons/artillerytables/functions/fnc_turretChanged.sqf
- addons/artillerytables/functions/fnc_turretPFEH.sqf
ref https://discord.com/channels/105462288051380224/122121444703338496/1350954562466480249
>I´d like to have a weapon display both the ACE elevation and azimuth numbers and PgUp / PgDwn zeroing numbers at the same time. 
Issue is, they seem to be getting displayed in the same place by default, so I can only see one of them 🤔
For turrets not using an elevation mode (i.e. mouse controls elevation instead of pageUp/Down)
Show the info 1 step below, so it doesn't block vanilla ranging (discreteDistance)
vanilla zeroing will have a negative effect, so it's best to range as low as possible
Could possibly handle the vanilla zeroing, but it would be a lot of work for something pretty uncommon
just range 100 and it's very close
> Artillery Tables - Don't block zeroing for turrets without `elevationMode`

- .hemtt/launch.toml
- addons/compat_cup_units/CfgWeapons.hpp
- title
- also: add CUP mods to `launch.toml`
Context:
> Only the goggles versions of the K6-3 Combat Helmet have ACE Hearing Protection values defined
on the CUP Discord. The Goggles Variant inherits differently and get their values from `CUP_H_RUS_Altyn` which has its values in CUP directly.
> compat_cup_units - Add Hearing Protection to `CUP_H_RUS_K6_3` Helmets

- addons/compat_aegis/compat_aegis_javelin/CfgWeapons.hpp
- addons/compat_aegis/compat_aegis_javelin/config.cpp
- addons/compat_aegis/compat_aegis_javelin/script_component.hpp
- title
- Adds Javelin subcompat to compat Aegis
- Adds Javelin compat to the two Titan MPRL shoulder variants added by Aegis
> Compat Aegis: Add Aegis Titan variants Javelin compat

- addons/medical_treatment/functions/fnc_treatment.sqf
Fix
`WARNING: animation [] for [CheckResponse] has no duration defined`
> Medical Treatment - Don't warn for diagnose animation duration

- addons/ballistics/stringtable.xml
- addons/smallarms/CfgMagazines.hpp
- addons/smallarms/CfgWeapons.hpp
- addons/smallarms/stringtable.xml
- _Fix ACE 16Rnd 9x19 magazine description was the display name for the non-existent 30Rnd 9x19 magazine._
- _Fix BIS 16rnd 9x21 tracer magazine display name shown as 16Rnd despite being 17Rnd by ACE._
- _Add missing FNX-45 magazine displaynameshort. That is displayed like other .45 magazines._
Note: The localization is based on what we copied from the game, so it should be fine.
- Title of this PR uses our standard template …
> Balistics, SmallArms - Fix 9mm magazines Displaynames and Descriptions

- addons/compat_cup_vehicles/CfgVehicles.hpp
- addons/compat_cup_weapons/CfgWeapons.hpp
- addons/compat_gm/CfgVehicles.hpp
- addons/compat_gm/CfgWeapons.hpp
Add `noReflection` config for BM-21
Fix some offsets on some artillery
- Was at breech not muzzle ![p](https://github.com/user-attachments/assets/2f976ce5-374b-47c3-8b8e-fadab859f326)
> GM/CUP Compat - Fix overpressure settings for various artillery

- addons/common/functions/fnc_getWheelHitPointsWithSelections.sqf
- addons/repair/functions/fnc_addRepairActions.sqf
- addons/repair/functions/fnc_getSelectionsToIgnore.sqf
- Adds a method to `ace_common_fnc_getWheelHitPointsWithSelections` to find GM wheels and a selection that  does not disappear when wheel damage is one / the wheel proxy goes away.
- Adds a handle to skip normal GM wheel hitpoint selections and to add repair action to GM vehicles
Open to any feedback on how to make this less jank. I don't think anyone else uses proxies for wheels besides GM devs, so I only check for their work (they set a config flag on top of the DLC config entry).
> Repair - Patch to detect GM Wheel position and selection

- addons/compat_rhs_afrf3/compat_rhs_afrf3_missileguidance/CfgAmmo.hpp
- Remove changes made to the 9M113, disabling ACE missile guidance
- Address part of https://github.com/acemod/ACE3/issues/10872
> Compat RHS AFRF - Remove 9M113 from Missile Guidance Compat

- addons/overheating/functions/fnc_jamWeapon.sqf
- fix `for "_i" from count _jamTypesAllowed` steps, should only have returned the strings like "Feed" but was returning numbers as well and therefore always failing the `if !(_jamCurretType in ["eject", etc]` check and falling back to default .
- new param for the type of jam
- add defaults for weapon and jam type
- make jam types case insensitive
> Overheating - fix/improve ace_overheating_fnc_jamWeapon

- addons/repair/stringtable.xml
- Adds some missing hit point localisation.
> Repair - Add RHS BMP hit point localisation

- addons/cargo/functions/fnc_startDeploy.sqf
- addons/common/functions/fnc_addActionEventHandler.sqf
- addons/dragging/functions/fnc_carryObject.sqf
- addons/dragging/functions/fnc_resumeCarry.sqf
- addons/sandbag/functions/fnc_deploy.sqf
- addons/tacticalladder/functions/fnc_positionTL.sqf
- addons/trenches/functions/fnc_placeTrench.sqf
- addons/tripod/functions/fnc_adjust.sqf
It wouldn't intercept mouse button inputs when in FFV seats
- Title: It would intercept mouse button clicks when in FFV seats. I'm guessing it's been broken for years, as I found a ticket from 2018 talking about the cause of the issue: https://feedback.bistudio.com/T131585.
- As a result, both jamming and weapon safety was broken when in FFV seats.
- Use the `_caller` instead of the `_target` for the statement (see https://community.bistudio.com/wiki/addAction).
- [Development …
> Common - Fix `FUNC(addActionEventHandler)`

- addons/compat_cup_vehicles/CfgVehicles.hpp
- addons/compat_cup_weapons/compat_cup_weapons_csw/config.cpp
- addons/compat_rhs_usf3/CfgVehicles.hpp
- addons/compat_sog/CfgVehicles/turrets.hpp
- Title. Specific vehicles are:
- RHS HIMARS
- CUP Hiluxes with MLRS or UB-32
- SOG H12
- Change addon dependency casing to remove warning from RPT (drive-by change).
- Closes #10821.
> Misc. compats - Exclude some MLRS vehicles from own backblast

- addons/repair/functions/fnc_isNearRepairVehicle.sqf
- Expand what types of objects can be considered repair vehicles to things like ammo boxes and portable cranes.
> Repair - Change isNearRepairVehicle to include more types of objects

- .hemtt/launch.toml
- addons/compat_cfp/$PBOPREFIX$
- addons/compat_cfp/CfgVehicles.hpp
- addons/compat_cfp/CfgWeapons.hpp
- addons/compat_cfp/config.cpp
- addons/compat_cfp/script_component.hpp
- Adds a new component for Community Factions Project
- Adds wirecutter function to a vest and a backpack
- Adds cfp to launch.toml as an extension of cup
> Compat CFP - Add `logistics` compatibility

- addons/field_rations/functions/fnc_addWaterSourceInteractions.sqf
- addons/field_rations/functions/fnc_canRefillItem.sqf
- addons/field_rations/functions/fnc_consumeItem.sqf
- addons/field_rations/functions/fnc_getConsumableChildren.sqf
- addons/field_rations/functions/fnc_getRefillChildren.sqf
- addons/field_rations/functions/fnc_handleEffects.sqf
- addons/field_rations/functions/fnc_scanFieldRations.sqf
- docs/wiki/framework/field-rations-framework.md
- Title.
- Minor optimisation: Use `EFUNC(common,uniqueItems)` to get magazines
- Use `_player` instead of `ACE_player`.
> Field Rations - Support negative thirst and hunger values

- addons/nametags/functions/fnc_onDraw3d.sqf
- Add `GVAR(treatAsPlayer)` variable to treat AI units as a player, including enemy AI.
- Use case is for having AI be disguised to players. Experienced players would immediately know they're an enemy due to the name tag not showing
- Moved common conditions to inline function
> Name Tags - Add variable to treat AI as players

- addons/markinglaser/CfgEventHandlers.hpp
```
[ACE] (markinglaser) INFO: Class B_Parachute_02_F does not have a pilot camera nor a turret that could be equipped with an IR marking laser.
> Marking Laser - Fix parachute rpt spam

- addons/explosives/functions/fnc_selectTrigger.sqf
- Fixes the "Active Detonator" not being reset to a different detonator used to arm a new explosive, when the current active one had no connected charges remaining.
> Explosives - Fix "Active Detonator" not being reset after no charges remaining

- addons/aircraft/RscInGameUI.hpp
- Use different base classes to inherit from instead.
> Aircraft - Remove unused base classes

- addons/nightvision/functions/fnc_onVisionModeChanged.sqf
- addons/nightvision/functions/fnc_pfeh.sqf
- addons/nightvision/functions/fnc_setupDisplayEffects.sqf
```
_fogApply = linearConversion [0, 1, ace_nightvision_>
Error position: <linearConversion [0, 1, ace_nightvision_>
Error Type Any, expected Number
File z\ace\addons\nightvision\functions\fnc_pfeh.sqf..., line 165
```
fix script error when going directly to thermals
e.g. the MX binoc from ace or some mods that have vics with just thermals (no nvg first)
also skips all other effects if just in thermal
> Nightvision - Fix script error when switching to thermals

- addons/medical_treatment/functions/fnc_canTreat.sqf
- addons/medical_treatment/initSettings.inc.sqf
- Enhanced handling of the allowSelfTreatment property:
- New Case: `2`
- Requires Medic to be a Doctor to perform Self Treatment
- Added selectable Option, limiting selfstitching to only doctors.
- Updated `QGVAR(allowSelfStitch)` Setting
- Updated `QGVAR(allowSelfPAK)` Setting
- Updated `QGVAR(allowSelfIV)` Setting
- Can upgrade to `No, Yes, Doctors Only` if needed but would require new stringtable entry.
> Medical Treatment - Enhanced Setting: Add option to allow Self-Stitch/PAK/IV only for Doctors

- addons/missileguidance/functions/fnc_SACLOS_onFired.sqf
- addons/missileguidance/functions/fnc_seekerType_SACLOS.sqf
e.g. GM BMP-1P
the saclos is fired from a sub-turret from the main `[0,0]`
so we need to take into account the animation of both turrets
`CBA_fnc_turretDir` seems to be ok for this
IIRC it isn't as accurate as using the raw anim, but seems to do a reasonably good job
> Missile Guidance - Fix SACLOS on sub-turrets

- addons/arsenal/XEH_preStart.sqf
- addons/arsenal/functions/fnc_addListBoxItem.sqf
Getting DLC info takes very long. Getting mod pictures also takes some time, so avoid both if not necessary.
- Title.
- Use separate caches for images.
> Arsenal - Reduce tab switching times

- addons/advanced_throwing/functions/fnc_prime.sqf
- _Add gunner as a parameter in Throw Fired XEH_
- _~Each change in a separate line~_
**Explain:**
According to the [BI wiki](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Fired), gunner is available as a parameter in Fired EH since 1.66.
This PR simply use `_unit` in `FUNC(prime)` as gunner, and the `_unit` is from: 
https://github.com/acemod/ACE3/blob/7adb188b854316defa076d4ecd9d8f1287ebb2d8/addons/advanced_throwing/functions/fnc_onMouseButtonDown.sqf#L45
https://github.com/acemod/ACE3/blob/7adb188b854316defa076d4ecd9d8f1287ebb2d8/addons/advanced_throwing/functions/fnc_throw.sqf#L24
So it should matches the BI wiki parameter explain "gunner whose weapons are firing"
- If the contribution affects [the …
> Advanced Throwing - Add gunner as a parameter in Throw Fired XEH

- addons/interaction/functions/fnc_switchWeaponAttachment.sqf
e.g. GM G3 Bayonet
`"\gm\gm_weapons\gm_attachments\gm_muzzles\gm_bayonet_g3\data\ui\picture_gm_bayonet_g3_blk_ca"`
missing .paa, shows up as raw text
> Interaction - Fix showing weapon attachment icon

- addons/aircraft/XEH_postInit.sqf
- Fix turret returning to old stabilized position when zooming in from unstabilized mode to stabilized mode
- Currently ace adds turret optics modes `ACE_Wide: ACE_WideUnstabilized`. When zooming in from ACE_WideUnstabilized to ACE_Wide (stabilized), the turret will return to where it was last stabilized. Thus if the player had previously slewed the camera while in ACE_WideUnstabilized, then on zoom-in the camera will move uncommanded.
- This pr checks for such an occurrence and prevents the move by locking the turret to the current target position for 1 frame then unlocking it.
- https://www.youtube.com/watch?v=KXQA1u3yoW8
> Improve Aircraft - Fix turret returning to old stabilized position

- addons/csw/CfgMagazineGroups.hpp
- addons/mk6mortar/CfgMagazines.hpp
- addons/mk6mortar/functions/fnc_csw_getProxyWeapon.sqf
Fix #10986
Allows unloading the new illum rounds
Changes the CSW magazine to use the new ammo type
This does means both new and old vanilla flare mags will unload to the same ace mag
but our description for the round was always `[CSW] 82mm Illumination Round`
so I think this is fine, but I could also add a brand new mag if desired
> CSW - Fix 2.20 mk6 illumination round

- addons/vehicle_damage/functions/fnc_processHit.sqf
- Changes `_addedDamage` modification to work as a function of a very rough estimation of time of flight.
- Current implementation relies on `_airFriction * _distance` resulting in large reductions in damage for projectiles with non-infinitesimal `"airFriction"` values. i.e., RHS uses penetrators for their AP ammo with airFriction of `-0.08` resulting in shots at 200m applying ~1e-7 damage
- This doesn't account for projectile bounces or deflections, but neither did the old method.
- Previous version reduced damage by typically by ~5% for typical AP projectiles at 1km, this results in damage reduction from 10% to 30% for typical AP projectiles at 1km
> vehicleDamage - Change fnc_processHit AP Damage Reduction

- addons/medical_gui/CfgVehicles.hpp
Allowed for loading patients while swimming
- Allow loading unconscious into vehicles while swimming
> Change unconcious loading exceptions to allow while swimming

- addons/laser/functions/fnc_laserPointTrack.sqf
- Fix the TGP of aircraft drifting across terrain while laser designating in AREA track, mainly when looking far towards the sides of the aircraft.
Ref https://github.com/acemod/ACE3/issues/10766#issuecomment-2693065582
Fixes #10766 
Fixes #9968
> Laser - Fix TGP Drift while Designating in AREA Track

- addons/compat_aegis/compat_aegis_vehicles/CfgVehicles.hpp
- addons/compat_aegis/compat_aegis_vehicles/config.cpp
- Overwrite Aegis' changes back to ACE' changes.
- Correct MG would be the Kord with 12.7x108 mm ammo
- ACE has the correct name, but wrong ammo (it's .50 BMG)
- Aegis has correct ammo, but wrong name (NSVT instead of Kord)
- I would have liked to change ACE to use 12.7x108 ammo instead, but as it's set to .50 BMG for quite a while now, I'm scared it would break missions with preexisting magazine loadouts.
- Title of this PR …
> Compat Aegis - Fix T-14 commander MG not having ammo

- addons/medical_gui/functions/fnc_updateInjuryList.sqf
Alt to #11038
Just touches medical_gui
This matches code from https://github.com/acemod/ACE3/blob/master/addons/medical_gui/functions/fnc_updateBodyImage.sqf#L104
> Medical GUI - Improve minimum damage thresholds to prevent div0

- addons/intelitems/XEH_preInit.sqf
- resolves #11049 
- Add EH for Arsenal Opened
- get MagID's for each Intel Items and store in GVAR
- Add EH for Arsenal Closed
- get old magID's, get magID's for each new IntelItems, get IntelID for each, add new magID to intelMal with previous intelID.
> IntelItem - Fix: Intel Items lose Data when updating containers in arsenal
